### PR TITLE
Fix s390x more and make amd64.md file not executable.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build  failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@jaykrell s390x still fails to compile:

```
mini-s390x.c: In function 'mono_arch_tailcall_supported':
mini-s390x.c:7579:41: error: 'ArgInfo' has no member named 'storage'
   res = IS_SUPPORTED_TAILCALL (ainfo [i].storage != RegTypeStructByAddr)
                                         ^
mini-s390x.c:7559:65: note: in definition of macro 'IS_SUPPORTED_TAILCALL'
 #define IS_SUPPORTED_TAILCALL(x) (is_supported_tailcall_helper((x), #x))
                                                                 ^
mini-s390x.c:7580:39: error: 'ArgInfo' has no member named 'storage'
    && IS_SUPPORTED_TAILCALL (ainfo [i].storage != RegTypeStructByAddrOnStack);
                                       ^
mini-s390x.c:7559:65: note: in definition of macro 'IS_SUPPORTED_TAILCALL'
 #define IS_SUPPORTED_TAILCALL(x) (is_supported_tailcall_helper((x), #x))
                                                                 ^
Makefile:2004: recipe for target 'libmini_la-mini-s390x.lo' failed
make[4]: *** [libmini_la-mini-s390x.lo] Error 1
```

**Comment by vargaz** [comment]
It might be better to just revert the changes to those arches since we don't have CI.

**Comment by jaykrell** [comment]
I can somewhat cross build this, but it fails because MonoContext isn't defined. powerpc didn't have that problem.

**Comment by jaykrell** [comment]
Anyway I can fix  it. @akoeplinger how did you find the error?

**Comment by akoeplinger** [comment]
We do have CI, just not on PRs: https://jenkins.mono-project.com/job/test-mono-mainline-community/label=centos-s390x/, that's how I found it :)

I think Jo can also get you access to a machine if you need it.

**Comment by jaykrell** [comment]
I guess I should try qemu-user again. It should work plenty.

**Comment by nealef** [comment]
If you need access to a real s390x system I can give you an account on a system running a clone of CentOS 7.4.1708. Just let me know.

**Comment by jaykrell** [comment]
Please. Cross build should suffice but isn't. Code inspection also  should, it is so minor. Just give you public ssh key?

**Comment by nealef** [comment]
In mono-context.h –


typedef ucontext_t MonoContext;

is what’s defined for s390x.

**Comment by jaykrell** [comment]
MonoContext: of course, but  it doesn't work. Maybe I need more cross packages or somesuch..

**Comment by jaykrell** [comment]
please ping me in private slack or email for  public key  (yeah, I know I should be safe pasting it here..)

**Comment by nealef** [comment]
Hey guys, I’ve been the s390x person since 2003 with mono so just let me know what you need to do and I can help. I’m not sure what prompted the changes for the tailcall stuff I put in but let me know what you are attempting to do and I can help. I’ve implemented the s390x ABI for mono, libffi, and the early OpenJDK project.

In brief the calling convention is:

R2-R6 are used for passing values 1, 2, 4, 8 bytes in size (including structures). Otherwise the parameter is placed on the stack starting at SP+0x160. Floating point parameters are passed in FP registers 2, 4, and 6. Results are returned in R2 for values 1,2,4,8 bytes in length or FP0 for floating point registers. (The situation is more complicated for SIMD which I’ve started to implement.) s390x had been passing the tailcall tests as of about a month ago so I am not sure what tests it has started failing since that time. I’ve been preoccupied by other work so I’ve not been able to devote much time on things.

I have a copy of the latest s390x ABI document if you need it.

**Comment by nealef** [comment]
I don’t slack so what’s your email?

**Comment by nealef** [comment]
I am not sure what’s breaking now as I’ve used this for some time doing context switching stuff.

**Comment by jaykrell** [comment]
git  log mono/master | grep -i  jay | head

**Pull request merged**
