### PR TITLE
[wasm] Add throwing PNSE to where currently disabled tests throw something different

### PR DESCRIPTION
**Pull request by MaximLipnin**
https://github.com/mono/mono/issues/18735

cc @steveisok @lewing

### CODE REVIEW

**Comment by lewing** [comment]
This looks ok, I wonder if we should do an analysis run that checks for those exceptions too and use that to break down the list.

**Comment by lewing** [comment]
@monojenkins build

**Comment by lewing** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by MaximLipnin** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by MaximLipnin** [comment]
Not sure if `Windows x64 FullAOT+LLVM` lane failure is related.

**Comment by akoeplinger** [comment]
The failure is happening in MonoTests.test-sgen-bridge-ms-simple-tarjan-bridge.sgen-bridge.exe and I see that in other PRs too, seems to be unrelated.

**Comment by MaximLipnin** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Pull request merged**
