### PR TITLE
[wasm] Add generated xml doc to sdk build.

### PR DESCRIPTION
**Pull request by kjpou1**
- Add the WebAssembly.Bindings.xml to the package.
- Add the WebAssembly.Net.Http.xml to the package.

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kg** [comment]
Does this have an observable impact on behavior? It seems fine to me.

**Comment by kjpou1** [comment]
@kg yes, this includes the intelisense XML files for the library.  When the sdk nugets are loaded in a project the intelisense now works.

**Comment by kjpou1** [comment]
There is an issue for this here.  https://github.com/mono/mono/issues/11329

**Pull request merged**
