### PR TITLE
Fix early return in Process.Start

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes https://github.com/mono/mono/issues/17204
Fixes https://github.com/mono/mono/issues/19836

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
Needs a backport as well.

**Review by lambdageek — APPROVED** [review]

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins backport to 2020-02

**Pull request merged**
