### PR TITLE
Make function pointers readonly.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by vargaz** [comment]
What problem does this PR solve ?

**Comment by jaykrell** [comment]
Just how things should generally be — readonly data, readonly function pointers to reduce attack surface, remove memcpy — the struct lifetime shall equal code lifetime.

Readonly maybe not on all targets & the static init might incur relocs where dynamic does not, if anyone counts those.

**Comment by jaykrell** [comment]
The other PR is better and maybe now I see its problem.

**Comment by jaykrell** [comment]
Well, the other thing is confusing, because:
```
#ifdef LINK_ICALLS
	/* Link in our own linked icall table */
	static const MonoIcallTableCallbacks mono_icall_table_callbacks =
	{
		MONO_ICALL_TABLE_CALLBACKS_VERSION,
		icall_table_lookup,
		icall_table_lookup_symbol
	};
	mono_install_icall_table_callbacks (&mono_icall_table_callbacks);
#endif

#ifdef NEED_NORMAL_ICALL_TABLES
	mono_icall_table_init ();
#endif
```
need to see if these are mutually exclusive or such.

**Comment by jaykrell** [comment]
https://github.com/mono/mono/pull/14361 is preferable if I finally noticed why it was failing, pretty narrow sighted that I missed it before.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
The other is proving a lot of trouble. Maybe I come back to it another day.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Fails with zero change. Will rebase to current master.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
