### PR TITLE
[Mono.Posix] Disable Unix-specific tests on Windows

### PR DESCRIPTION
**Pull request by akoeplinger**
They don't make sense there.

### CODE REVIEW

**Comment by jonpryor** [comment]
I disagree with the assessment that "they dont't make sense." The *Unix* tests don't make sense, but not all tests are for Unix. Some tests are for C89, and *should* be able to run on Windows, such as [StdioFileStreamTest](https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Test/Mono.Unix/StdioFileStreamTest.cs), and probably [UnixEncodingTest](https://github.com/mono/mono/blob/master/mcs/class/Mono.Posix/Test/Mono.Unix/UnixEncodingTest.cs).

**Comment by akoeplinger** [comment]
@jonpryor agreed. I updated the commit to only disable the Unix-specific tests.

**Comment by jonpryor** [comment]
I didn't know you could `Assert.Ignore()` within `[TestFixtureSetup]` to ignore all tests in that fixture. That's interesting.

That said, wouldn't the "conventional" course of action be to use Categories? For example, [`RealTimeSignumTest` has `[Category("NotOnMac")]`](https://github.com/mono/mono/blob/863dc73/mcs/class/Mono.Posix/Test/Mono.Unix.Native/RealTimeSignumTests.cs#L22); couldn't we have a `[Category("NotOnWindows")]` to inhibit execution on Windows?

You could update [`$(PLATFORM_TEST_HARNESS_EXCLUDES)` within `mcs/build/platforms/win32.make`](https://github.com/mono/mono/blob/fb9a077/mcs/build/platforms/win32.make#L10) to include `NotOnWindows`, [as is done in `darwin.make`](https://github.com/mono/mono/blob/fb9a077/mcs/build/platforms/darwin.make#L10), which would allow you to substantially reduce the changes present in this PR.

**Comment by marek-safar** [comment]
You could also just do `[Platform("Unix")]`

**Comment by jonpryor** [comment]
I forgot about `[Platform]`. :-)

**Comment by akoeplinger** [comment]
I like the category approach better :) I actually wondered why we didn't have it for Windows a while back, but didn't get around to asking. Sounds like we should just do it, we can then also remove similar code that uses Environment checks in the future.

**Pull request merged**
