### PR TITLE
[merp] Add assertions against initing dumper from signal handler

### PR DESCRIPTION
**Pull request by alexanderkyte**
There's been a few instances of telemetry which seems to show the SIGTERM signal handler firing and starting a dump, and then dying at the end due to not having the place to output the created dump. 

```
INFO [2019-03-28 17:53:08Z]: Add-in loaded: MonoDevelop.VBBinding
INFO [2019-03-28 17:53:08Z]: [Inspector] Initializing
INFO [2019-03-28 17:53:08Z]: Add-in loaded: Xamarin.TestCloud.NUnit
Pkilling 0x70000eb4c000 from 0x7fffa3728380
Pkilling 0x70000d72e000 from 0x7fffa3728380
Pkilling 0x70000e949000 from 0x7fffa3728380
Pkilling 0x70000d52b000 from 0x7fffa3728380
Pkilling 0x70000d222000 from 0x7fffa3728380
Pkilling 0x70000e746000 from 0x7fffa3728380
Pkilling 0x70000e543000 from 0x7fffa3728380
Pkilling 0x70000e340000 from 0x7fffa3728380
Pkilling 0x70000e13d000 from 0x7fffa3728380
Pkilling 0x70000df3a000 from 0x7fffa3728380
Pkilling 0x70000dd37000 from 0x7fffa3728380
Pkilling 0x70000db34000 from 0x7fffa3728380
Pkilling 0x70000ed4f000 from 0x7fffa3728380
Pkilling 0x70000d931000 from 0x7fffa3728380
Entering thread summarizer pause from 0x7fffa3728380
Finished thread summarizer pause from 0x7fffa3728380.
2019-03-28 17:53:09.133 VisualStudio[3647:189384] error: * Assertion at mono-state.c:1017, condition `mem' not met

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native
```

The best way to catch that promptly should be to assert the minute that we try to call into the non-controlling pathway into the dumper, if a dump hasn't been started yet. Otherwise it can look as if the crash happened due to issues in the MERP backend.

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@lambdageek could you please review

**Comment by alexanderkyte** [comment]
Could either of the assigned reviewers @lambdageek or @lateralusX take a look at this? 

I am going to re-trigger the build so we see that it still is safe to merge onto master.

**Pull request merged**
