### PR TITLE
[bitcode] Fix building -with-runtime-preset=bitcode.

### PR DESCRIPTION
**Pull request by jaykrell**
Not clear if this is correct, but let build progress.

### CODE REVIEW

**Comment by jaykrell** [comment]
Otherwise:
```
jaymac1:profiler jay$ make V=1
../../doltlibtool  --tag=CC   --mode=link gcc  -Wall -Wunused -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes  -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wno-cast-qual -Wwrite-strings -Wno-switch -Wno-switch-enum -Wno-unused-value -Wno-attributes -Wno-format-zero-length -Qunused-arguments -Wno-unused-function -Wno-tautological-compare -Wno-parentheses-equality -Wno-self-assign -Wno-return-stack-address -Wno-constant-logical-operand -Wno-zero-length-array -g -O0 -std=gnu99 -fno-strict-aliasing -fwrapv -DMONO_DLL_EXPORT -g -Werror-implicit-function-declaration -no-undefined  -o libmono-profiler-aot.la -rpath /usr/local/lib aot.lo  ../../mono/eglib/libeglib.la -liconv   -lpthread
libtool: link: gcc -dynamiclib  -o .libs/libmono-profiler-aot.0.dylib  .libs/aot.o   -Wl,-force_load,../../mono/eglib/.libs/libeglib.a  -lm -liconv -lpthread  -g -O0 -g   -install_name  /usr/local/lib/libmono-profiler-aot.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_mono_class_from_mono_type", referenced from:
      _add_type in aot.o
  "_mono_class_get_context", referenced from:
      _add_class in aot.o
  "_mono_class_get_image", referenced from:
      _prof_jit_done in aot.o
      _add_class in aot.o
  "_mono_class_get_name", referenced from:
      _add_class in aot.o
  "_mono_class_get_namespace", referenced from:
      _add_class in aot.o
  "_mono_class_get_nesting_type", referenced from:
      _add_class in aot.o
  "_mono_error_ok", referenced from:
      _add_method in aot.o
  "_mono_jit_aot_compiling", referenced from:
      _mono_profiler_init_aot in aot.o
  "_mono_method_full_name", referenced from:
      _add_method in aot.o
  "_mono_method_get_class", referenced from:
      _prof_jit_done in aot.o
  "_mono_method_get_context", referenced from:
      _add_method in aot.o
  "_mono_method_get_token", referenced from:
      _prof_shutdown in aot.o
  "_mono_method_signature_checked", referenced from:
      _add_method in aot.o
  "_mono_profiler_create", referenced from:
      _mono_profiler_init_aot in aot.o
  "_mono_profiler_set_jit_done_callback", referenced from:
      _mono_profiler_init_aot in aot.o
  "_mono_profiler_set_runtime_shutdown_end_callback", referenced from:
      _mono_profiler_init_aot in aot.o
  "_mono_signature_full_name", referenced from:
      _add_method in aot.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by vargaz** [comment]
Maybe set libmono_dep instead in the if-else-if block below.

**Comment by jaykrell** [comment]
Oh like for better incremental building, or style? Ok I'll look.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows i386

**Pull request merged**
