### PR TITLE
[corlib] Suppress finalization of underlying console FileStreams

### PR DESCRIPTION
**Pull request by lambdageek**
We already suppress the finalization of the CStreamReader and CStreamWriter, but during shutdown, the underlying FileStream may be finalized which invalidates its access field which can lead to a crash.

Addresses https://github.com/mono/mono/issues/19005

### CODE REVIEW

**Comment by lambdageek** [comment]
This feels very fragile.

**Comment by steveisok** [comment]
I'm not sure there's a better way w/o some refactoring.

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
Maybe a better approach is to mark the underlying streams with `GC.SuppressFinalize()` so that they're not cleaned up during shut down.  The `CStreamWriter` objects for the standard streams are already marked in `Console.SetupStreams`

**Comment by lambdageek** [comment]
@monojenkins backport to 2020-02

**Pull request merged**
