### PR TITLE
[mono-api-html] removal of obsolete is fine

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by atsushieno** [comment]
I noticed that ClassComparer unlike InterfaceComparer does not inherit from MemberComparer (wut) and therefore it still reports removal of obsoleted class as warning. It should go away too.

Actually what I wanted to kill is about lost Enum type, which is even weird to be handled by this change, but anyways...

**Comment by atsushieno** [comment]
Now this PR is rebased, containing only one commit.

**Comment by akoeplinger** [comment]
@atsushieno do we still want this? looks like it has a merge conflict now.

**Comment by atsushieno** [comment]
Wait, wat, it was still not applied?

It is going to be another example case of that we should split out modules into smaller pieces and unbind from non-responsible ownership.

For the time being it is still wanted change, but if it is not applied then I will just ignore Android API compatibility diffs. That's what people wanted.

**Comment by akoeplinger** [comment]
@atsushieno I think it was just overlooked (was approved already), so you should just need to resolve the merge conflict.

**Comment by jonpryor** [comment]
I thought I had suggested that `[Obsolete]`d member removal only be find if `ObsoleteAttribute.IsError` is true, i.e. it's not possible (with compliant compilers) to reference the member *at all*...

**Pull request merged**
