### PR TITLE
Bump corert

### PR DESCRIPTION
**Pull request by ntherning**
Bumps to the latest commit in Mono's CoreRT fork.

### CODE REVIEW

**Comment by marek-safar** [comment]
@ntherning the API changes look fine, please update the PR to point to head of corert fork

**Comment by ntherning** [comment]
@marek-safar Thanks for taking a look. What do I do about the failing *Linux x64 mcs* job? It looks like `external/corert/src/System.Private.CoreLib/src/System/Array.cs` uses C# syntax that MCS cannot handle [here](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/src/System/Array.cs#L921)?

And what to do about the *Project Files Diff* failing job? Do I update the project files in my PR or is that done automatically once this PR has been merged?

**Comment by marek-safar** [comment]
For mcs issue, use #if __MonoCS__ to have mcs compatible implementation.

The csproj will be updated automatically before merging

**Comment by ntherning** [comment]
I tried adding the alternate piece of code for MCS below but it still tries to compile the code in the `#else` block and errors out. If I use `#if MONO` instead the Mono specific block is used and compiles fine with MCS. 

```diff
diff --git a/src/System.Private.CoreLib/src/System/Array.cs b/src/System.Private.CoreLib/src/System/Array.cs
index c237cb421..235d4789f 100644
--- a/src/System.Private.CoreLib/src/System/Array.cs
+++ b/src/System.Private.CoreLib/src/System/Array.cs
@@ -913,6 +913,19 @@ namespace System
             if (length <= 1)
                 return;

+#if MonoCS
+            ref T p = ref Unsafe.As<byte, T>(ref array.GetRawSzArrayData());
+            int i = index;
+            int j = index + length - 1;
+            while (i < j)
+            {
+                T temp = Unsafe.Add(ref p, i);
+                Unsafe.Add(ref p, i) = Unsafe.Add(ref p, j);
+                Unsafe.Add(ref p, j) = temp;
+                i++;
+                j--;
+            }
+#else
             ref T first = ref Unsafe.Add(ref Unsafe.As<byte, T>(ref array.GetRawSzArrayData()), index);
             ref T last = ref Unsafe.Add(ref Unsafe.Add(ref first, length), -1);
             do
@@ -923,6 +936,7 @@ namespace System
                 first = ref Unsafe.Add(ref first, 1);
                 last = ref Unsafe.Add(ref last, -1);
             } while (Unsafe.IsAddressLessThan(ref first, ref last));
+#endif
         }

         public void SetValue(object value, long index)
```

**Comment by marek-safar** [comment]
The correct define is `__MonoCS__` sorry for confusion

**Comment by marek-safar** [comment]
That's mcs bug which I should be able quickly fix

**Comment by marek-safar** [comment]
@ntherning the mcs issue should be resolved if you rebase on top of master and bump this https://github.com/mono/mono/blob/master/mcs/build/common/basic-profile-check.cs#L44 to 5.19

**Comment by ntherning** [comment]
I still get this exception from MCS:

```
Unhandled Exception:
Mono.CSharp.InternalErrorException: ..\..\..\external\corert\src\System.Private.CoreLib\shared\System\Threading\Tasks\ConcurrentExclusiveSchedulerPair.cs(201,22): System.Threading.Tasks.Concurrent                                                    ExclusiveSchedulerPair.CompleteTaskAsync() ---> System.NotImplementedException: CloneTo not implemented for expression Mono.CSharp.DefaultLiteralExpression
  at Mono.CSharp.Expression.CloneTo (Mono.CSharp.CloneContext clonectx, Mono.CSharp.Expression target) [0x00010] in <e920d9aac4c24fa69cc564f16723087b>:0
  at Mono.CSharp.Expression.Clone (Mono.CSharp.CloneContext clonectx) [0x0000c] in <e920d9aac4c24fa69cc564f16723087b>:0
  at Mono.CSharp.Argument.Clone (Mono.CSharp.CloneContext clonectx) [0x00000] in <e920d9aac4c24fa69cc564f16723087b>:0
  at Mono.CSharp.Arguments.Clone (Mono.CSharp.CloneContext ctx) [0x00027] in <e920d9aac4c24fa69cc564f16723087b>:0
```

MCS version is now:

```
NIKLAS-DELL+niklas@NIKLAS-DELL /cygdrive/c/p/mono
$ MONO_PATH="mcs/class/lib/monolite-win32/D5B35FED-5DF9-413F-8463-57269F340FA7;mcs/class/lib/monolite-win32/D5B35FED-5DF9-413F-8463-57269F340FA7/Facades;$MONO_PATH" /cygdrive/c/p/mono/runtime/mono-wrapper  mcs/class/lib/monolite-win32/D5B35FED-5DF9-413F-8463-57269F340FA7/mcs.exe --version
Mono C# compiler version 5.19.0.0
```

My branch has the MCS fix you pushed: https://github.com/mono/mono/commit/e830b55f051a8136cb03af3526323e2de595d0f2

**Comment by ntherning** [comment]
@marek-safar Any insights on why MCS might still fail?

**Comment by ntherning** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
It looks like we no longer rebuild monolite automatically to include the latest fixes. Let me find how to retrigger that

**Comment by marek-safar** [comment]
@monojenkins build deb with monolite

**Comment by ntherning** [comment]
@marek-safar Looks like the "Debian Package" job failed: https://jenkins.mono-project.com/job/build-package-dpkg-mono-pullrequest/label=ubuntu-1404-amd64/289//console

**Comment by marek-safar** [comment]
@monojenkins build deb with monolite

**Comment by ntherning** [comment]
@monojenkins build failed

**Comment by ntherning** [comment]
@monojenkins build failed

**Comment by ntherning** [comment]
@marek-safar What do you think of the API diffs? Anything I need to fix?

**Comment by marek-safar** [comment]
@ntherning apidiff is good, just update the submodule path and this can go in

**Comment by ntherning** [comment]
Opened a PR in Mono's CoreRT fork: https://github.com/mono/corert/pull/25. Please merge it first and I'll update this PR to point at the correct CoreRT fork repo.

**Comment by ntherning** [comment]
Ok, this should now be mergeable if it looks ok.

**Comment by ntherning** [comment]
@marek-safar Should be mergable now. Please have a look when you find the time. Thanks!

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Pull request merged**
