### PR TITLE
[sgen] add internal mem type for critical finalizer queue

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by kumpera** [comment]
One alternative is to signal somehow to the test bridge that it's shutdown time and everything should be finalizable.

**Comment by lewurm** [comment]
I guess "somehow" means there isn't an API available yet for that purpose?

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
removing changes for testcase, #3211 is the proper fix for that.

**Comment by lewurm** [comment]
build

**Pull request closed without merging**
