### PR TITLE
[System.Windows.Forms] Remove obsolete theme code.

### PR DESCRIPTION
**Pull request by filipnavara**
Related to issue #7268.

The use of MONO_THEME environment variable was supposed to be removed by commit 93724d2. However, it remained used at one more place in ThemeElements, which was probably unintentional.

ThemeClearlooks, ThemeNice and ThemeGtk have been unused since commit 910c669 in 2008. Since there seems to be zero interest in maintaining them it seems reasonable to remove it altogether. There's a new Gtk theme backend based on the Visual Styles framework, which remains available. 

cc @jpobst

### CODE REVIEW

**Comment by marek-safar** [comment]
whitelist

**Comment by marek-safar** [comment]
@monojenkins whitelist

**Comment by akoeplinger** [comment]
@filipnavara could you please remove the mention of `MONO_THEME` from man/mono.1 as well?

**Comment by filipnavara** [comment]
@akoeplinger Sure, I didn't notice it.

**Comment by filipnavara** [comment]
Submitted pull request for the documentation (https://github.com/mono/mono/pull/7282).

**Pull request merged**
