### PR TITLE
[fullaotinterp/fullaotinterp_llvm] Use CoreFX System.IO

### PR DESCRIPTION
**Pull request by alexischr**
/cc @BrzVlad

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter

**Comment by lewurm** [comment]
`Linux x64 FullAOT+Interpreter` job is shown as failing, although it actually passed. This is shown at the very end of the log:
```
23:07:09 I: Copying back the cached apt archive contents
23:07:09 I: unmounting /mnt/jenkins/workspace/test-mono-pull-request-fullaot+interpreter filesystem
23:07:09 I: unmounting dev/pts filesystem
23:07:09 I: unmounting dev/shm filesystem
23:07:09 I: unmounting proc filesystem
23:07:09 I: unmounting sys filesystem
23:07:09 I: cleaning the build env 
23:07:09 I: removing directory /mnt/jenkins/buildplace/13058 and its subdirectories
23:07:10 Container name contains invalid characters
23:07:10 ERROR: Step ‘Upload artifacts to Microsoft Azure Storage’ aborted due to exception: 
23:07:10 java.io.IOException: Plugin can not continue, until previous errors are addressed
23:07:10 	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:399)
23:07:10 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
23:07:10 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
23:07:10 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
23:07:10 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
23:07:10 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
23:07:10 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
23:07:10 	at hudson.model.Run.execute(Run.java:1835)
23:07:10 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
23:07:10 	at hudson.model.ResourceController.execute(ResourceController.java:97)
23:07:10 	at hudson.model.Executor.run(Executor.java:429)
23:07:11 INFO: Starting to record.
23:07:11 INFO: Processing NUnit-2.x (default)
23:07:11 INFO: [NUnit-2.x (default)] - 23 test report file(s) were found with the pattern 'mcs/class/**/TestResult*.xml, mono/**/TestResult*.xml, runtime/**/TestResult*.xml, acceptance-tests/**/TestResult*.xml' relativ
```
could `+` in the name be a problem? /cc @akoeplinger @directhex

**Comment by directhex** [comment]
Yeah, storage containers have very tight naming requirements. The job is uploading to `${JOB_NAME}`. We can sanitize this - we do in a few other jobs where JOB_NAME isn't a valid storage container name

**Pull request merged**
