### PR TITLE
[cominterop] Implement native-to-managed safearray marshalling.

### PR DESCRIPTION
**Pull request by nsivov**
This is a case of CCW calling managed method with object[] argument.

### CODE REVIEW

**Comment by nsivov** [comment]
I don't quite understand why it fails, looks like it only happens with cygwin builds? Is this the problem?

> cominterop.exe
> =============== cominterop.exe.stdout ===============
> cant resolve internal call to "Tests/_TestClass::.ctor" (tested without signature also)
> 
> Your mono runtime and class libraries are out of sync.
> The out of sync library is: D:\j\workspace\w\mono\tests\cominterop.exe

**Comment by nsivov** [comment]
Ok, I'll take a closer look.

**Comment by nsivov** [comment]
@vargaz please take a look, I fixed broken wrapper logic that corrupted user-allocated argument.

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
