### PR TITLE
[System.IO] Finish initializing all FileSystemWatchers, not just the f…

### PR DESCRIPTION
**Pull request by alexischr**
…irst one

Fixes https://github.com/mono/mono/issues/8712

- [ ] Test

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build OS X Package

**Comment by marek-safar** [comment]
Which backend is it, the old one or corefx ? It'd make sense if the initialization was static (done only once) but this way we are serializing all constructor calls and opening doors for deadlock

**Comment by Therzok** [comment]
Just a note, it's also needed on 2018-04

**Comment by alexischr** [comment]
@monojenkins build

**Comment by luhenry** [comment]
@alexischr could you please rebase on top of master so we can get it merged?

**Comment by alexischr** [comment]
@luhenry this fix is not ready (failing tests), I will merge when it is

**Comment by alexischr** [comment]
@monojenkins backport to 2018-04

**Comment by Therzok** [comment]
When can we expect this in 2018-04?

**Pull request merged**
