### PR TITLE
[System.Windows.Forms] Fix crash of DataGridView in case of assigning a custom Column Header.

### PR DESCRIPTION
**Pull request by NVoronchev**
This PR fix crash of `DataGridView` in case of assigning a custom Column Header.

### CODE REVIEW

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
LGTM

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
@monojenkins build

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins build Linux AArch64

**Pull request merged**
