### PR TITLE
[wasm] Incremental compilation support.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
With these changes, a very minimal change to a hello world (like changing Hello to Bye) will build in 15s down from 30s for a full build.
10s of this is the final wasm linker, which seems to run some kind of optimization passes.

**Comment by jaykrell** [comment]
@monojenkins build  Linux x64 C++

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
