### PR TITLE
Bump msbuild to track mono-2018-08

### PR DESCRIPTION
**Pull request by radical**
.. to pick up update for the NuGetSdkResolver.
https://github.com/mono/msbuild/pull/92

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
Failing tests:
```
MonoTests.test-unhandled-exception-2-255-with-managed-handler.unhandled-exception-3.exe
MonoTests.test-unhandled-exception-2-255-without-managed-handler.unhandled-exception-3.exe
MonoTests.test-sgen-regular-ms-conc-simple.sgen-new-threads-dont-join-stw.exe_timedout
MonoTests.test-sgen-regular-ms-simple.sgen-new-threads-dont-join-stw.exe_timedout
```

**Comment by lambdageek** [comment]
Linux AArch64 FullAOT failed with an unrelated error
```
Ran out of trampolines of type 3 in '/home/builder/jenkins/workspace/test-mono-pull-request-arm64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll' (limit 4000)
```

**Comment by akoeplinger** [comment]
Looks good. /cc @directhex as I guess this needs some fixups on the Linux side too.

**Pull request merged**
