### PR TITLE
[corlib]: Misc updates from CoreFX.

### PR DESCRIPTION
**Pull request by baulig**
* `CancellationTokenRegistration`: use the CoreFX version.

* `String`: add `implicit operator String (ReadOnlySpan<char> value)`.

* `TimeSpan`: add `TimeSpan operator / (TimeSpan timeSpan, double divisor)`
  and `double operator /(TimeSpan t1, TimeSpan t2)`.

* `BitConverter`: add `uint ToUInt32(ReadOnlySpan<byte> value)` and
  `ulong ToUInt64(ReadOnlySpan<byte> value)`.

### CODE REVIEW

**Comment by akoeplinger** [comment]
There are some ambiguous calls in the tests that need to be fixed:

```
corlib: Test/System.IO/PathTest.cs(437,24): error CS0121: The call is ambiguous between the following methods or properties: 'Path.GetFileName(string)' and 'Path.GetFileName(ReadOnlySpan<char>)'

System.Numerics: Test/System.Numerics/BigIntegerTest.cs(977,31): error CS0121: The call is ambiguous between the following methods or properties: 'BigInteger.TryParse(string, out BigInteger)' and 'BigInteger.TryParse(ReadOnlySpan<char>, out BigInteger)'
```

**Comment by baulig** [comment]
@monojenkins commit api-diff

**Comment by baulig** [comment]
@monojenkins commit apidiff

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff and csproj

**Pull request merged**
