### PR TITLE
[profiler] Fix profiler compilation under bitcode.

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by alexrp** [comment]
build

**Comment by akoeplinger** [comment]
The last iteration fixes the issue in maccore 👍

**Comment by alexrp** [comment]
@kumpera can you have a look?

**Comment by alexrp** [comment]
OK'd by @kumpera.

@monojenkins merge

**Comment by alexrp** [comment]
Merging manually since this was already green.

**Pull request merged**
