### PR TITLE
fix for https://bugzilla.xamarin.com/show_bug.cgi?id=36724

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
This is a fix for the
https://bugzilla.xamarin.com/show_bug.cgi?id=36724

also patch for portage was created - https://github.com/gentoo/dotnet/pull/147

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins whitelist

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by ArsenShnurkov** [comment]
Where to read, what I should be aware about "whitelist" mode?

**Comment by akoeplinger** [comment]
@ArsenShnurkov you can ignore it, it's just instructions for our CI bot.

**Pull request merged**
