### PR TITLE
Fix time zone issue when jumping into DST 

### PR DESCRIPTION
**Pull request by MaximLipnin**
There is an issue with jumping into DST for some time zones when the incorrect date-time offset is returned for date-time in UTC (which comes from DateTime.Now). The fix is to just check if the incoming date-time is in UTC
Also I added set of tests for some time zones but they verify jumping into DST in general.
Fixes https://github.com/mono/mono/issues/16395

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@steveisok what's the plan with this PR?

**Comment by steveisok** [comment]
@MaximLipnin Asked me to test and then we'll move it forward.

**Comment by steveisok** [comment]
Ran local device tests with the sample in https://github.com/mono/mono/issues/16395.  Works as expected.

**Comment by steveisok** [comment]
@monojenkins backport 2019-08

**Comment by steveisok** [comment]
@monojenkins backport 2019-06

**Pull request merged**
