### PR TITLE
Sockets: Foo_internal to Foo_icall and ves_icall_Foo_internal to ves_icall_Foo.

### PR DESCRIPTION
**Pull request by jaykrell**
The first is to avoid requiring the signature matching in icall resolution.
The second is just to shorten names.

Arguably a better form would mono_Foo_icall, so that the tail matches between C# and C.
Arguably mono_ves_icall_Foo_icall is preferred for that reason, despite saying "icall" twice.

There were very few overloads -- add "_array_" to the name like C did.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by lambdageek** [comment]
What does this accomplish? Is it required as part of something else?

**Comment by jaykrell** [comment]
Right I’d like to skip all the signature parsing & checking, in the code & by humans.

**Comment by jaykrell** [comment]
Several of these function signatures will change, to remove handles. This splits up that work. 
Shorter names are also eaiser for humans.
And a little extra churn isn’t so bad.

**Comment by jaykrell** [comment]
i.e. this is split out from larger PR:
https://github.com/mono/mono/pull/17978

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by vargaz** [comment]
I also think that this signature matching is just overhead, it's hard to write, hard to process, needs to be rewritten when signatures change etc. So we should get rid of it if possible at least for our icalls.

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
There is an argument for “stronger matching” but we don’t do that thoroughly by far.
Merge conflict to resolve shortly.

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
wierd


https://jenkins.mono-project.com/job/test-mono-pull-request-arm64-fullaot+interpreter/10109/parsed_console/log_content.html

```

MONO_PATH="./../../../class/lib/build:$MONO_PATH" CSC_SDK_PATH_DISABLED= /home/builder/jenkins/workspace/test-mono-pull-request-arm64-fullaot+interpreter/runtime/mono-wrapper  --aot-path=/home/builder/jenkins/workspace/test-mono-pull-request-arm64-fullaot+interpreter/mcs/class/lib/build --gc-params=nursery-size=64m /home/builder/jenkins/workspace/test-mono-pull-request-arm64-fullaot+interpreter/external/roslyn-binaries/Microsoft.Net.Compilers/3.4.0/csc.exe /shared:monomake /codepage:65001 /nologo /noconfig /deterministic /unsafe  -d:NET_1_1 -d:NET_2_0 -d:NET_2_1 -d:NET_3_5 -d:NET_4_0 -d:NET_4_5 -d:MONO -d:MOBILE,MOBILE_LEGACY -d:DISABLE_REMOTING -d:DISABLE_SECURITY -nowarn:1699 -nostdlib /debug:portable -d:FULL_AOT_INTERP -d:DISABLE_COM -optimize /features:peverify-compat /langversion:latest  -r:./../../../class/lib/testing_aot_full_interp/I18N.dll -r:./../../../class/lib/testing_aot_full_interp/mscorlib.dll  -sourcelink:./../../../build/common/sourcelink.json /keyfile:../../mono.pub  -target:library -out:../../../class/lib/testing_aot_full_interp/I18N.Rare.dll  @./../../../build/deps/_testing_aot_full_interp__I18N.Rare.dll.response
CP852.cs(351,10): error CS8120: The switch case has already been handled by a previous case.
CP852.cs(352,10): error CS8120: The switch case has already been handled by a previous case.

```

I guess just retry. :(

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins squash

**Pull request merged**
