### PR TITLE
[jit] Also allow System.Runtime.CompilerServices.Unsafe intrinsics from the System.Runtime.CompilerServices assembly, not just corlib.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
The failures are relevant.

**Comment by lewurm** [comment]
Is it safe to assume that the same intrinsic should be used for an arbitrary assembly which happens to have the same name?

**Comment by vargaz** [comment]
Unfortunately, there is no way to identify the 'official' assembly, so yes.

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
