### PR TITLE
Fix a crash in the MONO_LLS_FOREACH_SAFE macro

### PR DESCRIPTION
**Pull request by alexrp**
See aa0d58f2e87e317996dae86ec7ec447cc39ef520 for an explanation.

### CODE REVIEW

**Comment by alexrp** [comment]
@kumpera: this should be ready for review.

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
@schani / @BrzVlad: could one of you review c093c2cc8055e609a7fe5c553c8262eaeb9cc4a3 (+ the rest of the PR if you've got some time to spare, but mainly that commit)?

**Comment by akoeplinger** [comment]
@alexrp please take a look at the Windows build issue (the other failures are from known flaky tests).

**Comment by alexrp** [comment]
Bloody hell. Looks like MSVC needs to be a special snowflake again. So much for the nicer macro style.

**Comment by kumpera** [comment]
@alexrp how's the MSVC fix going?

**Comment by alexrp** [comment]
@kumpera done and ready for review.

**Pull request merged**
