### PR TITLE
[merp] Increase buffer size for state dump

### PR DESCRIPTION
**Pull request by alexischr**
Addresses https://github.com/mono/mono/issues/18796

### CODE REVIEW

**Comment by lambdageek** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins backport to 2020-02
@monojenkins backport to 2019-12
@monojenkins backport to 2019-10

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by CoffeeFlux** [comment]
Can we not just reallocate with double the size if we don't have enough space? Is there a reason we have to perfectly guess how large it could be beforehand?

**Comment by lambdageek** [comment]
> Can we not just reallocate with double the size if we don't have enough space? Is there a reason we have to perfectly guess how large it could be beforehand?

We're running in a signal handler, everything we do should be async signal safe.  Including possibly because `malloc` failed due to native heap corruption. So we can't `malloc`.

`mono_state_alloc_mem` is not actually a `malloc` wrapper - it's an `open; lseek; write; mmap` wrapper. 😬

**Comment by jaykrell** [comment]
Still, can't you make two passes?
The first time, write nowhere but track the length, and then mmap and run the logic again?

**Comment by lambdageek** [comment]
Yea, doing two passes would work. By the time we're serializing the collected crash data, we should be in a pretty stable state where we can afford to do two passes over the data.

**Comment by lambdageek** [comment]
ok, made an issue to consider doing it dynamically.  https://github.com/mono/mono/issues/18843
thanks folks!

**Comment by alexischr** [comment]
I agree that a flexible arrangement is better. It'd be harder to reason around re-allocating but it is possible I think; if we can do `open; lseek; write; mmap` once we can do an `close; unlink` and another sequence of `open; lseek; write; mmap` later but still in the same post-crash runtime phase.

But if the two-phase idea isn't a mess to implement that's less risky.

**Comment by akoeplinger** [comment]
what's the state of this PR? I see that the 2019-10 backport was merged but this one and the other backports are still open.

**Comment by alexischr** [comment]
These should all go in but we rushed the 2019-10 merge. Merging all now

**Pull request merged**
