### PR TITLE
Remove handles from Mono.RuntimeMarshal, Mono.SafeStringMarshal.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build deb with monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by jaykrell** [comment]
Seems like too many breaks for a retry to fix but we'll see and I can look closer later.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
