### PR TITLE
[netcore] Make System.Reflection.Tests.TypeTests.GetEnumUnderlyingType Pass

### LINKED ISSUE #15350: [netcore] Make System.Reflection.Tests.TypeTests.GetEnumUnderlyingType Pass
The test currently fails with:

```
System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(enumTypeW: SampleMetadata.GenericEnumContainer`1, expectedUnderlyingTypeW: System.Int16) [FAIL]
      System.ArgumentException : Type provided must be an enum.
      Stack Trace:
           at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.ComputeEnumUnderlyingType()
           at System.Reflection.TypeLoading.RoType.GetEnumUnderlyingType()
           at System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(TypeWrapper enumTypeW, TypeWrapper expectedUnderlyingTypeW)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(enumTypeW: SampleMetadata.GenericEnumContainer`1[System.Int32], expectedUnderlyingTypeW: System.Int16) [FAIL]
      System.ArgumentException : Type provided must be an enum.
      Stack Trace:
           at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.ComputeEnumUnderlyingType()
           at System.Reflection.TypeLoading.RoConstructedGenericType.ComputeEnumUnderlyingType()
           at System.Reflection.TypeLoading.RoType.GetEnumUnderlyingType()
           at System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(TypeWrapper enumTypeW, TypeWrapper expectedUnderlyingTypeW)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes #15350.

### CODE REVIEW

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
This doesn't seem right.  the recursive call will parse verything after the `+` including type parameters.  So something like `Outer+Inner`1[System.String]` will be parsed incorrectly, I think.

**Comment by lambdageek** [comment]
Just tried the code from this PR using my example program from above, and it seems to go wrong on the first call to `Type.GetType`:

```
FullName: HelloWorld.GenericEnumContainer`1+GenericEnum, HelloWorld, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35
!!! Parsing ##HelloWorld.GenericEnumContainer`1+GenericEnum, HelloWorld, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35## from 0
!!! Parsing ##HelloWorld.GenericEnumContainer`1+GenericEnum, HelloWorld, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35## from 34

Unhandled Exception:
System.IO.FileNotFoundException: 
File name: 'Version=42.42.42.42'
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.TypeNameParser.ResolveAssembly(String name, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(ParsedName pname, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase)
   at HelloWorld.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: 
File name: 'Version=42.42.42.42'
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.TypeNameParser.ResolveAssembly(String name, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
   at System.TypeNameParser.ConstructType(ParsedName pname, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase)
   at HelloWorld.Program.Main(String[] args)
```

(The `!!!` lines are a from `Debug.WriteLine ("!!! Parsing ##{0}## from {1}", name, pos);` at entry to `ParseName`)

**Comment by lambdageek** [comment]
I think the problem is with this `if` statement: https://github.com/mono/mono/blob/8fe4109eadc3213a7cdc23ffe02fc25f17531e2a/netcore/System.Private.CoreLib/src/System/TypeNameParser.cs#L247-L248

I think that `res.Names.Add` should be done always, not just if `res.Names.Count == 0`.

**Comment by MaximLipnin** [comment]
No overload for `Type.GetType ("", true, null, null, true, false)` .
`Type.GetType ("", null, null, true, false)` throws `System.TypeLoadException: A null or zero length string does not represent a valid Type.` That's correct.

**Pull request merged**
