### PR TITLE
[corlib] Switch to CharUnicodeInfo from corefx

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by steveisok** [comment]
The mcs failure is significant.  

The wasm one may be, but not 100% sure.

```
WASM: FAIL: System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncodingWithFinalBlockFalse
WASM: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OutOfMemoryException: Out of memory
WASM:   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x34297f0 + 0x000ce> in <758e4f696ce0429c87765a52350cb572>:0 
WASM:    --- End of inner exception stack trace ---
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x34297f0 + 0x000f6> in <758e4f696ce0429c87765a52350cb572>:0 
WASM:   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) <0x37ba2e8 + 0x00014> in <758e4f696ce0429c87765a52350cb572>:0 
WASM:   at WasmRunner.Run () <0x37190c8 + 0x00766> in <0d91d0de794645e09cfd3d0c7a47b7d2>:0
```

**Comment by NattyNarwhal** [comment]
Careful, I remember a switch from custom refsrc to normal refsrc failed because of some endianness BS caused by some crazy pointer arith in refsrc's Unicode char info classes

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
It looks like we have GC problem handling large Span blocks. @BrzVlad is this enough for you to investigate (it repros consistently) ?

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Pull request merged**
