### PR TITLE
Zlib cleanup

### PR DESCRIPTION
**Pull request by directhex**
Move zlib to its own directory, and re-enable subdir-objects

This has the following benefits:

* Clearer structure for mirroring
* Slight build time improvement on bundled zlib use (as it only builds once)
* Removes pages of subdir-objects spew from autogen

### CODE REVIEW

**Comment by directhex** [comment]
I've tested this on Linux w/ bundled, static, and system zlib. Let's see what CI thinks.

**Comment by directhex** [comment]
Ci thinks I messed up my Windows changes 😅

**Comment by vargaz** [comment]
The linux failures look relevant.

**Comment by directhex** [comment]
31 failed lanes is the score to beat!

**Comment by directhex** [comment]
`16:32:00 make: *** [build-sdk] Segmentation fault (core dumped)` 🤷‍♂

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build failed

**Pull request merged**
