### PR TITLE
Fixing FileSystemWatcher problem in VSMac

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes https://github.com/mono/mono/issues/11635.

Main changes are in https://github.com/mono/corefx/pull/225.

Some initial work was done in https://github.com/mono/mono/pull/11945

The idea is to share CFRunLoop for FSEventStreams.

### CODE REVIEW

**Comment by jaykrell** [comment]
I suggest a bit more wording in the title.

**Comment by lambdageek** [comment]
@MaximLipnin I think `s_watcherRunLoop` is garbage when `UnscheduleFromRunLoop` is called from the finalizer on shutdown.  I think it's because by that point the thread that runs `WatchForFileSystemEventsThreadStart` is already finished, so it called `CFRelease` and the runloop was destroyed.

If I add this patch, I don't get a crash anymore

```patch
From 57eb7a44327f8f3a005a74862bcfaf4f5cbcd905 Mon Sep 17 00:00:00 2001
From: Aleksey Kliger <alklig@microsoft.com>
Date: Thu, 27 Dec 2018 12:33:30 -0500
Subject: [PATCH] set s_watcherRunLoop to zero when calling CFRelease

---
 .../src/System/IO/FileSystemWatcher.OSX.cs                       | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs b/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
index b3da8a1f14..ede6f81d9a 100644
--- a/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
+++ b/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs
@@ -257,6 +257,7 @@ namespace System.IO
                     {
                         lock (s_lockObject)
                         {
+			    s_watcherRunLoop = IntPtr.Zero;
                             Interop.CoreFoundation.CFRelease(runLoop);
                         }
                     }
-- 
2.19.1
```

**Comment by marek-safar** [comment]
@MaximLipnin please bump the CoreFX dependency

**Comment by marek-safar** [comment]
@MaximLipnin could you fix the merge conflict?

**Comment by MaximLipnin** [comment]
Can it be merged?

**Comment by slluis** [comment]
It would be nice to have this in 2018-08.

**Comment by marek-safar** [comment]
@MaximLipnin do you have to bump corefx again to bring the second fix?

**Comment by MaximLipnin** [comment]
@marek-safar Could we bump the second fix within separate PR? I've tested changes from https://github.com/mono/corefx/pull/231 applied to current PR locally but it looks like some other corefx commits made before require separate bump/check on CI.

**Comment by marek-safar** [comment]
@MaximLipnin there is now a conflict anyway :-(

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins commit apidiff and csproj

**Comment by Therzok** [comment]
Can we backport this to 2018-08?

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@MaximLipnin please backport this to remaining branches as well

**Pull request merged**
