### PR TITLE
[arm] remove cross compiling guard for MONO_ARCH_SOFT_DEBUG_SUPPORTED

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
build

**Comment by vargaz** [comment]
Was this tested with a cross compiler ? Enabling it might enable code paths which reference MonoContext/sigcontext which is kinda problematic when cross compiling.

**Comment by lewurm** [comment]
it was tested in the context of https://github.com/mono/mono/pull/4958 on iOS/armv7.  Other targets (e.g. arm64) don't have that guard.  I assume, if there would be problems, we should have seen them already on arm64?

**Comment by vargaz** [comment]
Tested this on ios and it seems to work.

**Pull request merged**
