### PR TITLE
 [ppc] Fixes to get mono to build on big endian ppc. 

### PR DESCRIPTION
**Pull request by BillSeurer**
[ppc] Basic fixes to get mono to build on power BE 

This is a basic set of patches that should allow mono to build on power big endian.  See https://bugzilla.xamarin.com/show_bug.cgi?id=28679

### CODE REVIEW

**Comment by vargaz** [comment]
Could you address the comments so this can be merged ?

**Comment by directhex** [comment]
This appears to fix some BE issues on 32-bit PPC, but leaves behind 2 major 32-bit bugs that prevent building Mono on BE32.

https://gist.github.com/directhex/f890350006e72be706af is my quick analysis - of the 50something failures, almost all are caused either by a missing opcode, or an assert. Presumably a misplaced ifdef is to blame for the former, I'm not sure about the latter.

**Comment by directhex** [comment]
At Alex's suggestion, moving the ATOMIC_ADD_I4/I8 cases up out of the `#ifdef __mono_ppc64__` and increasing the instruction length to 28 in cpu-ppc.md has fixed one of the issues, reducing the ppc32 failures from 51 to 30. The assert remains.

**Comment by BillSeurer** [comment]
Replacing this with a better commit

**Pull request closed without merging**
