### PR TITLE
Fixing debugger hang that would occur when inspecting a field that ha…

### LINKED ISSUE #20209: Debugger hangs when inspecting an element that has `Debugger.Break` in it's accessor
## Steps to Reproduce

1. Build sample code with debug and put a breakpoint on the second `Console.ReadKey()`
2. Run sample code and attach Unity debugger.
3. Hit a key to trigger breakpoint.
4. Inspect foo.bar and observe hang. Happens with both VSTU and Rider

```
using System;
using System.Diagnostics;

namespace HangDebuggerProj
{
    class Program
    {
        private class Foo
        {
            private string bar
            {
                get
                {
                    Debugger.Break();
                    return "Foo";
                }
            }
            
        }
        static void Main(string[] args)
        {
            Foo foo = new Foo();
            Console.ReadKey();
            Console.ReadKey();
        }
    }
}
```
### Current Behavior
Hangs mono runtime

### Expected Behavior
No hang. I checked the .Net runtime and it appears to ignore the `Debugger.Break` command.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[X] Windows

**Version Used**:
```
Mono JIT compiler version 6.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

### PR DESCRIPTION
**Pull request by UnityAlex**
…s a Debugger.Break in it's accessor.

fixes #20209

### CODE REVIEW

**Comment by UnityAlex** [comment]
cc @jbevain

**Comment by UnityAlex** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by UnityAlex** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by UnityAlex** [comment]
@monojenkins build Linux WebAssembly

**Pull request merged**
