### PR TITLE
Fixed runtime dependency on libgdiplus with developer soname

### PR DESCRIPTION
**Pull request by Mailaender**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=34314.

### CODE REVIEW

**Comment by Mailaender** [comment]
See this patch in action on a real Linux packaging VM: https://build.opensuse.org/request/show/351820

**Comment by akoeplinger** [comment]
The Xamarin .deb/.rpm libgdiplus packages ship `libgdiplus.so` (as a symlink to .so.0.0.0) and there is no `libgdiplus-devel` package, so this is likely why it didn't impact us. 

Changing libsuffix isn't the right way though, it's used in a few other places for other libs.
IMHO applying the patch mentioned in the bug report for config.in seems better to me, or patch it in [configure.ac#L3252](https://github.com/mono/mono/blob/da63cf5b2de55db356d6278259de384593927268/configure.ac#L3252).

**Comment by Mailaender** [comment]
> Changing libsuffix isn't the right way though, it's used in a few other places for other libs.

*ugh* What did I break exactly?

**Comment by akoeplinger** [comment]
Here are a few other usages of `libsuffix`: https://github.com/mono/mono/blob/master/data/config.in#L8-L12 (I don't know if those work with .so.0).

We could also introduce another variable for libgdiplus like INTL/SQLITE3 above that has the correct soname for each platform (the Xamarin libgdiplus package ships `libgdiplus.so.0` to that should work).

**Comment by Mailaender** [comment]
Your build system is a monster. I tried to update accordingly.

New https://build.opensuse.org/request/show/351965 works for @OpenRA and KeePass on my machine

**Comment by lewurm** [comment]
build

**Comment by akoeplinger** [comment]
Sorry this patch fell off my radar, but this should really go to @directhex to review.

**Comment by directhex** [comment]
Sure, fine, doesn't seem to have broken anything

**Comment by lewurm** [comment]
@monojenkins merge

**Pull request merged**
