### PR TITLE
[test-runner] Use Parallel.ForEach instead of handwritten mechanism

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
:heart: thanks for all the work on test-runner! it fixes all the races I experienced while testing #2129 :smile:

**Comment by vargaz** [comment]
On my machine, the original code runs in 14s, this one takes 23s.

**Comment by ludovic-henry** [comment]
That must be because of the threadpool heuristic which can take a few
seconds before launching enough threads. I will add setting the minimum
number of threadpool thread, so there shouldn't be any ramp up time.

**Comment by directhex** [comment]
build

**Comment by akoeplinger** [comment]
@ludovic-henry fyi, I merged a few small additions to test-runner.cs so this'll need a rebase.

**Pull request closed without merging**
