### PR TITLE
[coop] Fix managed-to-native wrapper

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by xmcclure** [comment]
This is LGTM but I do not feel I have the background to make a good judgement on 98a94ddc.

**Comment by vargaz** [comment]
Looks ok.

**Comment by ludovic-henry** [comment]
I get a failed test in pinvoke2.exe:
```
test_0_return_vtype failed: got 1, expected 0
Regression tests: 90 ran, 1 failed in Tests
```

But it only fails on ARM, which is weird as there is no thread involved, meaning it's not a race condition.

I will investigate that further, and we cannot merge it as long as it's not fixed.

**Comment by vargaz** [comment]
Its probably caused by the VTADDR changes.

**Comment by ludovic-henry** [comment]
build

**Comment by ludovic-henry** [comment]
@vargaz would you please mind looking at that crasher on ARM? I unfortunately don't have access to a ARM dev board, and it seems to be in the mini ARM backend, as there is not platform dependence in this code. Thank you!

**Comment by ludovic-henry** [comment]
@monojenkins merge

**Comment by xmcclure** [comment]
Awesome!

**Pull request merged**
