### PR TITLE
Fix some on-demand initialization race conditions.

### PR DESCRIPTION
**Pull request by jaykrell**
i.e. MONO_STATIC_POINTER_INIT.
i.e. more of https://github.com/mono/mono/pull/17849

### CODE REVIEW

**Comment by naricc** [comment]
This still seems pretty big for one PR. The changes to each file seem to all be independent, right?

**Comment by jaykrell** [comment]
Yes, independent, and kinda two sorts of changes. I can split up further.

**Comment by jaykrell** [comment]
Split up into 12 roughly per-file PRs.

**Comment by baulig** [comment]
Well, IMHO it would have been easier to review this in this PR - especially when people have general questions or remarks that apply to all of them.

When we're adding those macros - how does this work in terms of code formatting?  Shouldn't we re-indent the block between those?

**Comment by CoffeeFlux** [comment]
I agree, splitting it up per-file is actually more difficult to review, but what's done is done.

**Comment by jaykrell** [comment]
The formatting is minimal damage in this case, and ignoring that, I'm not sure.
Perhaps we should have a style of putting braces on the uses:
```
MONO_POINTER_INIT {
  ..
} MONO_POINTER_INIT_END
```
It might help editing and it should work.

**Pull request closed without merging**
