### PR TITLE
Fix various bugs causing hangs on Xunit

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by adamralph** [comment]
nice work @alexanderkyte! I'm really looking forward to being able to run xunit 2.0 in Mono

**Comment by NTaylorMullen** [comment]
+1 to what @adamralph said hah.

**Comment by alexanderkyte** [comment]
I think it's safe to say that all the tests for this are passing, as the broken one looks like a jenkins bug I've been seeing on other bug builds.

**Comment by alexrp** [comment]
build

**Comment by alexanderkyte** [comment]
I'm seeing the 

```
* Assertion at mini-arm.c:3781, condition `pdata.found == 1' not met
```

error that has been haunting us on public jenkins arm for a while.

**Comment by mattzink** [comment]
What's the holdup on this being merged? XUnit 2 support is a high priority for many projects.

**Comment by alexanderkyte** [comment]
@kumpera I've updated the PR to bring the fixes to castclass, and extracted the caching behavior into a function. The indents look a bit absurd in a diff, but when in an editor where a tab is 8 spaces, as per the style guide, it's lined up.

**Pull request merged**
