### PR TITLE
[filewatcher] Fall back to default if a new instance cannot be created

### PR DESCRIPTION
**Pull request by alexischr**
Fixes https://github.com/mono/mono/issues/12535

### CODE REVIEW

**Comment by marek-safar** [comment]
@alexischr seems to cause issues on osx

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
I tried to test this out locally to see if it would fail in the same spot.  Turns out it did.  I wanted to see if a reboot helped and that seemed to do the trick.  I was able to run through the system tests (where it's failing) successfully. 

@alexischr since this has been hanging for a while, can you spot why there would be a hang w/ this PR?

**Comment by alexischr** [comment]
@steveisok I am back to working on this one. I am still not sure which resource is scarce in this case - or which other reason this fails on mac. It looks like it's a mutex failure, but the usual `pthread_mutex` debug line (or Mono's expected `g_error`) do not show up.

The test really should shut down all the FileSystemWatchers; it doesn't because that exposes a different bug, a shutdown race condition. For now, I will disable the test on Mac, and follow-up with a issue/fix for the rapid-shutdown problem.

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
There was a crash on System.dll on Windows, don't know if it's related (https://jenkins.mono-project.com/job/w2/791/parsed_console/log.html). I'll run again

**Comment by alexischr** [comment]
@monojenkins build failed

**Pull request merged**
