### PR TITLE
Restore domain in error path.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by lambdageek** [comment]
This is code churn.  There's no functional change here.

**Comment by jaykrell** [comment]
Isn’t domain supposed to remain constant even in case of error?

**Comment by lambdageek** [comment]
Oh, I see. in the case where `current_domain != domain` and queueing the work item fails, the new code restores the domain back to `current_domain`.  Sorry.

**Comment by jaykrell** [comment]
@monojenkins build  Linux ARMv7 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux ARMv7 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build Linux x64

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 C++

**Comment by jaykrell** [comment]
@monojenkins quash

**Comment by jaykrell** [comment]
@monojenkins squash

**Pull request merged**
