### PR TITLE
[aot] Emit the same instances in hybrid aot mode as in full aot mode.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/7086.

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build Windows x64

**Comment by luhenry** [comment]
@monojenkins build OS X i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Coop GC

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by luhenry** [comment]
@monojenkins build Linux i386 Coop GC

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Pull request merged**
