### PR TITLE
[linker] Add exclusions for some AsyncTaskMethodBuilder methods calle…

### PR DESCRIPTION
**Pull request by vargaz**
…d by the debugger. Fixes #59015.

### CODE REVIEW

**Comment by marek-safar** [comment]
This is wrong as we don't want them in Release build and we already handle this in our linker logic, see https://github.com/xamarin/xamarin-macios/blob/master/tools/linker/MobileMarkStep.cs#L262

**Comment by vargaz** [comment]
That code needs to handle get_ObjectIdForDebugger as well.

**Comment by marek-safar** [comment]
Then that's the right fix

**Comment by marek-safar** [comment]
I mean adding it there is the right fix

**Pull request closed without merging**
