### PR TITLE
[tests] Disable bug-10127.exe runtime test on Windows x64 C++

### PR DESCRIPTION
**Pull request by akoeplinger**
It hangs: https://github.com/mono/mono/issues/18827

### CODE REVIEW

**Comment by jaykrell** [comment]
This does not appear to have anything to do with Windows/x64/C++.
It is a deadlock in the runtime because the test calls GC.Collect on multiple threads.
Some suspend others, and there is deadlock. You can see threads waiting on locks, that suspended threads hold. Perhaps the suspended threads will be resumed, and perhaps it is Windows/x64/C++ related but I don't think so.

Also the test highlights how lock acquire/release is slow because it involves heap allocation, for the interrupt tokens.

**Comment by jaykrell** [comment]
Then again, I can only repro with verifier, which I think adds locking to InitializeCriticalSection, even with the NO_DEBUG_INFO flag, which maybe otherwise does not.
Also could be specific to which version of Windows, I'd need to check.
What does Jenkins run?

**Comment by akoeplinger** [comment]
@monojenkins backport 2020-02

**Comment by jaykrell** [comment]
The test should work in master now though.

**Pull request merged**
