### PR TITLE
[System] Disables compiled regex

### LINKED ISSUE #7828: Invalid instruction generated by regex runtime when using dapper
When using Hangfire an by extension Dapper, the regex runtime in mono is making an invalid instruction which is making the call to CreateDelegate fail.

```
Application startup exception: System.InvalidProgramException: Invalid IL code in (wrapper dynamic-method) System.Text.RegularExpressions.CompiledRegexRunner:FindFirstChar6 (System.Text.RegularExpressions.RegexRunner): IL_0021: bge       IL_0332


  at (wrapper managed-to-native) System.Delegate.CreateDelegate_internal(System.Type,object,System.Reflection.MethodInfo,bool)
  at System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) [0x002f0] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System/Delegate.cs:286 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure) [0x00000] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System/Delegate.cs:301 
  at System.Delegate.CreateDelegate (System.Type type, System.Reflection.MethodInfo method) [0x00000] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System/Delegate.cs:306 
  at System.Reflection.Emit.DynamicMethod.CreateDelegate (System.Type delegateType) [0x00029] in /home/dylan/Desktop/git/mono/mcs/class/corlib/System.Reflection.Emit/DynamicMethod.cs:175 
  at System.Text.RegularExpressions.CompiledRegexRunnerFactory.CreateInstance () [0x00005] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/CompiledRegexRunnerFactory.cs:25 
  at System.Text.RegularExpressions.Regex.Run (System.Boolean quick, System.Int32 prevlen, System.String input, System.Int32 beginning, System.Int32 length, System.Int32 startat) [0x0005c] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:1004 
  at System.Text.RegularExpressions.Regex.IsMatch (System.String input, System.Int32 startat) [0x0000e] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:619 
  at System.Text.RegularExpressions.Regex.IsMatch (System.String input) [0x0000e] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:603 
  at Dapper.SqlMapper.GetLiteralTokens (System.String sql) [0x0000e] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at Dapper.SqlMapper.GetCacheInfo (Dapper.SqlMapper+Identity identity, System.Object exampleParameters, System.Boolean addToCache) [0x0007c] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at Dapper.SqlMapper+<QueryImpl>d__136`1[T].MoveNext () [0x00075] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in /home/dylan/Desktop/git/mono/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1164 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /home/dylan/Desktop/git/mono/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:88 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000e] in /home/dylan/Desktop/git/mono/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at Dapper.SqlMapper.Query[T] (System.Data.IDbConnection cnn, System.String sql, System.Object param, System.Data.IDbTransaction transaction, System.Boolean buffered, System.Nullable`1[T] commandTimeout, System.Nullable`1[T] commandType) [0x0003c] in <63a8cc06dfb842f1823bc51677815d4b>:0 
  at Hangfire.PostgreSql.PostgreSqlConnection.GetAllEntriesFromHash (System.String key) [0x00035] in <fffd65c6cfa9476589e18fb16c03227a>:0 
  at Hangfire.RecurringJobManager.AddOrUpdate (System.String recurringJobId, Hangfire.Common.Job job, System.String cronExpression, Hangfire.RecurringJobOptions options) [0x000b6] in <9a531424b2e740ba9386e067e53e78dc>:0 
  at Hangfire.RecurringJobManagerExtensions.AddOrUpdate (Hangfire.IRecurringJobManager manager, System.String recurringJobId, Hangfire.Common.Job job, System.String cronExpression, System.TimeZoneInfo timeZone, System.String queue) [0x0004e] in <9a531424b2e740ba9386e067e53e78dc>:0 
  at Hangfire.RecurringJob.AddOrUpdate (System.Linq.Expressions.Expression`1[TDelegate] methodCall, System.String cronExpression, System.TimeZoneInfo timeZone, System.String queue) [0x00028] in <9a531424b2e740ba9386e067e53e78dc>:0
```

### PR DESCRIPTION
**Pull request by marek-safar**
Fixes #7828

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by marek-safar** [comment]
We never supported compiled regex (we disabled it in referencesource as well)  so this won't be performance regression.

The issue mentioned that it happened with the same regex randomly, see #7975 for task tracking

**Comment by migueldeicaza** [comment]
We did support compilation, I am not sure when it was disabled :-)

And there is no better proof than the fact that we are disabling it now.

I had time to think about this over lunch.   The race condition is not on Regex itself, this is likely a race somewhere else.   This patch is a bandaid for the root problem, and we do not know what that problem is.

**Comment by marek-safar** [comment]
@migueldeicaza maybe we did (but I don't this so) but not anytime recently please see https://github.com/mono/mono/blob/master/mcs/class/referencesource/System/regex/system/text/regularexpressions/Regex.cs#L1408-L1416

I agree this is nothing else than a workaround and as mentioned above the future work to track this down is in #7975

**Comment by migueldeicaza** [comment]
Thanks - for the sake of making this easier to reproduce, without building a whole Mono just to fix 7975, would you mind if we make this definition overridable with an environment variable instead?

**Comment by borgdylan** [comment]
A simple git pull origin, ./autogen.sh, make && make install leads to a mono build that fails like it used to without this commit. Something s overriding the dsiablement somehow.

**Pull request closed without merging**
