### PR TITLE
[mini] Fix unused variables warnings in dump_native_stacktrace().

### PR DESCRIPTION
**Pull request by nsivov**

### CODE REVIEW

**Comment by lewurm** [comment]
On what platform do you get the warning? mention it in the PR description/commit message, including the warning itself. removing those `#ifdef`s is wrong, just moving the declaration of the MonoContext variable should do it.

**Comment by nsivov** [comment]
I'm getting warnings on Linux/GCC, so TARGET_OSX is not defined.

This patch has no functional change otherwise, it simply replaces multiple ifdef-ed blocks with a single one. And no, it's not only about 'mctx' variable, 'leave' is also only read when TARGET_OSX is defined, same for 'dump_for_merp' or 'output'. Where do you see a wrongly removed condition?

P.S. I'll post compiler warnings once I get past unrelated build failures with current master.

**Comment by nsivov** [comment]
@lewurm here is the output:

  CC       libmini_la-mini-posix.lo
mini-posix.c: In function ‘dump_native_stacktrace’:
mini-posix.c:1036:13: warning: unused variable ‘leave’ [-Wunused-variable]
    gboolean leave = FALSE;
             ^~~~~
mini-posix.c:1034:15: warning: unused variable ‘mctx’ [-Wunused-variable]
   MonoContext mctx;
               ^~~~
mini-posix.c:1033:10: warning: unused variable ‘output’ [-Wunused-variable]
   gchar *output = NULL;
          ^~~~~~
In file included from ../../mono/utils/mono-threads.h:16,
                 from ../../mono/metadata/handle.h:23,
                 from ../../mono/metadata/threads-types.h:19,
                 from ../../mono/metadata/object-internals.h:14,
                 from ../../mono/metadata/gc-internals.h:17,
                 from mini-posix.c:56:

**Comment by lewurm** [comment]
you are right @nsivov, sorry! @kyte I believe this will going to conflict with some existing (future?) PRs of yours? could you chime in please

**Comment by lewurm** [comment]
@alexanderkyte please have a look

**Comment by luhenry** [comment]
@alexanderkyte please take a look at it.

**Comment by alexanderkyte** [comment]
This is all in the external caller of the dumper, that API isn't going to change much. @lewurm

**Comment by alexanderkyte** [comment]
@nsivov your PR seems to have some conflicts with mini-posix.c on master. Could you 
`git remote add upstream https://github.com/mono/mono` and `git pull --rebase upstream master` to fix it? 

One of us can do it if you're too busy, just let us know

**Comment by nsivov** [comment]
Sure, I'll update it.

**Comment by nsivov** [comment]
I don't see such warnings in current git, looks like it was reworked. Closing.

**Pull request closed without merging**
