### PR TITLE
[runtime] Read fields out of TransparentProxies correctly in debugger agent FIXES 36823

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@vargaz

**Comment by vargaz** [comment]
Looks ok, could you add a test to it to the test suite in mcs/class/Mono.Debugger.Soft ?

**Comment by alexanderkyte** [comment]
Test added

**Comment by vargaz** [comment]
Looks good.

**Pull request merged**
