### PR TITLE
Fix IndexOutOfRangeException in MethodInfo.ReturnParameter.IsDefined(type)

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes https://github.com/mono/mono/issues/12069

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Pull request merged**
