### PR TITLE
Remove unused MONO_PATCH_INFO_SET_TLS_TRAMP, corresponding unused JIT icalls, etc.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
We can remove this for now, but we might need it in the future.

**Comment by jaykrell** [comment]
I'm hoping if it comes back, just as a regular `JIT_ICALL_ADDR_NOCALL`.
i.e. if https://github.com/mono/mono/pull/15226 works.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
