### PR TITLE
Cross-platform complex math / MS Threadpool portability

### PR DESCRIPTION
**Pull request by tritao**

### CODE REVIEW

**Comment by tritao** [comment]
@ludovic-henry Can you review?

**Comment by kumpera** [comment]
All of those functions are all pretty small that they should be inlineable.

**Comment by tritao** [comment]
I had them all as macros actually but decided to convert them to proper functions before sending the pull... Should I kill the source file and move everything to the header?

**Comment by kumpera** [comment]
How about static inline functions in the header? We do it in other places and seems to work fine.

Macros where actual functions work is always a bad idea.

**Comment by tritao** [comment]
Re-implemented as static inlines.

**Comment by ludovic-henry** [comment]
It looks good to me. Thank you!

**Pull request merged**
