### PR TITLE
Add denied assembly versions from previous ms extensions nugets 

### PR DESCRIPTION
**Pull request by radical**
Extracted from Microsoft.NET.Build.Extensions

	2.1.0-preview1-62414-02   # https://github.com/dotnet/cli/blob/501e11d928c21608999c934f0a7078570b688c6c/build/DependencyVersions.props
	15.5.0-preview-20171027-2 # https://github.com/dotnet/cli/blob/ed916bb13e798a470855fb4f60acd3cabb2765fc/build/DependencyVersions.props
	2.0.0-preview3-20170622-1 # https://github.com/dotnet/cli/blob/7c928a9f18f81001e586e5bf0411f9bfa92e30d4/build/DependencyVersions.props

And also remove incorrect entries from earlier version
2.1.0-preview1-62516-03 , which were not committed to mono's msbuild.

A future commit will sort and de-dedup the lists, but this one avoids
removing any existing duplicates, to make review easier.

### CODE REVIEW

**Comment by radical** [comment]
@akoeplinger @marek-safar Could you please review this?

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
@monojenkins backport 2017-10

**Comment by radical** [comment]
@marek-safar Did you mean to backport to 2017-12 and not 2017-10?

**Comment by radical** [comment]
@monojenkins backport 2017-12

**Pull request merged**
