### PR TITLE
Speculative fix for https://github.com/mono/mono/issues/14957

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build pkg

**Comment by directhex** [comment]
@monojenkins build pkg

**Comment by directhex** [comment]
@monojenkins build pkg

**Comment by directhex** [comment]
@monojenkins build pkg

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build pkg

**Comment by lewing** [comment]
I think this outdated so I'm closing it.  Please reopen if I'm wrong.

**Pull request closed without merging**
