### PR TITLE
[Coop] Convert System.Decimal

### PR DESCRIPTION
**Pull request by jaykrell**
Fairly trivial.

### CODE REVIEW

**Comment by vargaz** [comment]
Esp. some of these ones need to remain non-handle to avoid overhead.

**Comment by jaykrell** [comment]
I'm told we don't like mono_error_set_pending_exception.
And removal of mono_error_set_pending_exception is conflated with icall-def.h HANDLES().
System.Decimal is probably little used, though when used perhaps performance sensitive.
Perhaps we should plan to rewrite this in C#, or corefx already has?
Or perhaps we don't dislike mono_error_set_pending_exception enough to really remove it.
It is much less bad than raw pointers?

**Comment by marek-safar** [comment]
yes, this code will migrate to managed once I have someone available to do it

**Comment by jaykrell** [comment]
Hold off on this.

**Pull request closed without merging**
