### PR TITLE
If0 dead Boehm code.

### PR DESCRIPTION
**Pull request by jaykrell**
Alternative to https://github.com/mono/mono/pull/15224.

### CODE REVIEW

**Comment by jaykrell** [comment]
@joncham on this variation too.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
As per https://github.com/mono/mono/pull/15224#issuecomment-504217795 I think we can close this and decide what to do in the other PR.

**Comment by jaykrell** [comment]
Agreed.

**Pull request closed without merging**
