### PR TITLE
[interp] Conserve stack in leave.

### PR DESCRIPTION
**Pull request by jaykrell**
And free up some space for other opcodes (e.g. enum_hasflag).

Contributes to https://github.com/mono/mono/issues/16172.
This should be more effective than https://github.com/mono/mono/pull/16357.
This turns child_frame into a union that can be *carefully* reused in non-recursive paths for locals.

### CODE REVIEW

**Comment by lewurm** [comment]
that's a bit too clever imho. is it really worth it?

**Comment by jaykrell** [comment]
Imho yes.

Most opcodes do not use child_frame, but they all kinda pay for it.
That space might as well be repurposed.


It is somewhat "important" and clear distinction in the code, once you study it a bit.

1. leave gets in the way of "everything else".
It is kinda the most complicated opcode, with its heavy use and mutation of locals and several exit conditions.

2. This can be used a bit more, like for enum_hasflag
 and maybe others that I outlined.

Or else https://github.com/mono/mono/pull/16461.
 Which obviates a lot, but not all, of my changes.
 
Or else, the recursive/nonrecursive split.
 I think w/o that split I can get to 0x98 (https://github.com/mono/mono/pull/16457)
 Or maybe 0x88 bytes w/ the split -- which granted is a heavy price,
 but I'll try it, maybe get lower.
 but again #16461 pretty much obviates everything else, except small code quality fixes.

**Comment by BrzVlad** [comment]
@jaykrell Does this save two stack slots ? Is child_frame pointer allocated into a stack_slot or is the structure referenced directly from frame base pointer offset ?

**Comment by BrzVlad** [comment]
I was wondering if when doing _child_frame->field1_, _child_frame->field2_ the compiler loads it through _mov rbp(offset1)_, _mov rbp(offset2)_  directly or it first loads the child_frame pointer from local variable (_mov rbp(child_frame_ptr_offset), rax_; _mov rax(field1_offset)_, _mov _rax(field2_offset)_). Or I'm asking if a stack_slot (local) is allocated for child_frame*

**Comment by BrzVlad** [comment]
Yeah, I just checked and no change on gcc. Check clang please. No local is created for child_frame* so at least that is good. The change looks decent, but let's make sure that there is improvement.

**Comment by BrzVlad** [comment]
It's ok to have it outlined for now

**Pull request closed without merging**
