### PR TITLE
[System] Fixes dead lock in SafeSocketHandle

### PR DESCRIPTION
**Pull request by esdrubal**
SafeSocketHandle.UnRegisterForBlockingSyscall locks blocking_threads
before removing the current thread from it.

The entire while loop of SafeSocketHandle.ReleaseHandle also locked
blocking_threads preventing any UnRegisterForBlockingSyscall to finish.
So it was impossible to remove threads from blocking_threads and
the cycle would abort.

The abort exception only occurred it there was pending system calls, but
it would every time that was the case.

This was fixed by moving the SafeSocketHandle.ReleaseHandle lock into the
while loop, and by doing the Monitor.Wait without a lock on
blocking_threads.

For an unknown reason it is not possible to reproduce the problem in a virtual machine. Let's run Jenkins on this two or three times see if it solves the flaky SendAsyncFile test.

### CODE REVIEW

**Comment by marek-safar** [comment]
It does not look correct to me. For example `cancel_blocking_socket_operation` can be call many times until we hit abort count

**Comment by esdrubal** [comment]
It is not granted that the blocking syscall will be aborted by calling cancel_blocking_socket_operation, it may fail 1, 2, 3 times, with decreasing probability each time. That is why we are doing 10 attempts but it should be very rare to fail 10 times.

cancel_blocking_socket_operation will never be called more than 10 times per thread, and rarely more than once or twice.

**Comment by akoeplinger** [comment]
I tried this in a loop on one of the bots and ran into the following exception eventually (in about 60 tests):

```
55) MonoTests.System.Net.Sockets.SocketTest.SendAsyncFile : System.Threading.SynchronizationLockException : Object is not synchronized
at System.Threading.Monitor.ObjWait (System.Boolean exitContext, System.Int32 millisecondsTimeout, System.Object obj) [0x0004d] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/corlib/System.Threading/Monitor.cs:87
at System.Threading.Monitor.Wait (System.Object obj, System.Int32 millisecondsTimeout, System.Boolean exitContext) [0x00011] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/referencesource/mscorlib/system/threading/monitor.cs:210
at System.Threading.Monitor.Wait (System.Object obj, System.Int32 millisecondsTimeout) [0x00000] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/referencesource/mscorlib/system/threading/monitor.cs:220
at System.Net.Sockets.SafeSocketHandle.ReleaseHandle () [0x000ec] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/System/System.Net.Sockets/SafeSocketHandle.cs:79
at System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (System.Boolean dispose) [0x000d2] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:227
at System.Runtime.InteropServices.SafeHandle.InternalDispose () [0x00011] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:156
at System.Runtime.InteropServices.SafeHandle.Dispose (System.Boolean disposing) [0x00006] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/referencesource/mscorlib/system/runtime/interopservices/safehandle.cs:262
at System.Runtime.InteropServices.SafeHandle.Dispose () [0x00000] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/referencesource/mscorlib/system/runtime/interopservices/safehandle.cs:254
at System.Net.Sockets.Socket.Dispose (System.Boolean disposing) [0x00047] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/System/System.Net.Sockets/Socket.cs:3322
at System.Net.Sockets.Socket.Dispose () [0x00000] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/System/System.Net.Sockets/Socket.cs:3328
at System.Net.Sockets.Socket.Close () [0x00007] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/System/System.Net.Sockets/Socket.cs:3257
at MonoTests.System.Net.Sockets.SocketTest.SendAsyncFile () [0x0013b] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/System/Test/System.Net.Sockets/SocketTest.cs:4281
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in /media/ssd/jenkins/workspace/test-mono-mainline-linux/label/debian-8-armhf/mcs/class/corlib/System.Reflection/MonoMethod.cs:309
```

**Comment by esdrubal** [comment]
I am misusing the monitors, I need to reconsider the issue and the fix. Closing the pull request.

**Pull request closed without merging**
