### PR TITLE
[arm64] Add a known TLS offset.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by lewurm** [comment]
is this needed on `2017-12` and `2018-02` too?

**Comment by rolfbjarne** [comment]
@lewurn: no, it's not necessary to backport this, it just silences a warning message.

**Comment by BrzVlad** [comment]
I think this code is dead. Do we still get tls values from other threads ?

**Comment by rolfbjarne** [comment]
@BrzVlad every iOS app prints this warning without this fix: https://github.com/mono/mono/blob/91b64b4560b78cf05ec99faec693737d7f63d093/mono/utils/mach-support-arm64.c#L193

**Comment by BrzVlad** [comment]
@rolfbjarne Yes. I think it basically prints a warning about dead code not working.

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv5

**Pull request merged**
