### PR TITLE
[jit] Avoid an assert when gsharedvt enums are boxed.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/13297.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins backport 2019-02

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-10

The xamarin-macios team hit this too.

**Comment by lambdageek** [comment]
@monojenkins backport to 2018-08

**Pull request merged**
