### PR TITLE
[external] bump nunit-lite in order to include fix for racy FinallyDelegate

### PR DESCRIPTION
**Pull request by lewurm**
submitting PR here to test changes ( https://github.com/mono/NUnitLite/pull/5 ) with CI.

### CODE REVIEW

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
@alexrp is this new? https://jenkins.mono-project.com/job/test-mono-pull-request-armhf/9106/testReport/junit/(root)/MonoTests/profiler_test_busy_exe_report_legacy_calls_alloc_/

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
@akoeplinger @alexischr is this a new crash? 

```***** MonoTests.System.ServiceModel.Channels.BinaryMessageEncodingBindingElementTest.ConnectionTcpTransport
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Net.Sockets.Socket.Receive_internal (intptr,byte*,int,System.Net.Sockets.SocketFlags,int&,bool) [0x00023] in <fe86f76b92ad45569c10dde7ead074e1>:0
  at System.Net.Sockets.Socket.Receive_internal (System.Net.Sockets.SafeSocketHandle,byte*,int,System.Net.Sockets.SocketFlags,int&,bool) [0x00006] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/System/System.Net.Sockets/Socket.cs:1519
  at System.Net.Sockets.Socket.Receive (byte[],int,int,System.Net.Sockets.SocketFlags,System.Net.Sockets.SocketError&) [0x0002e] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/System/System.Net.Sockets/Socket.cs:1296
  at System.Net.Sockets.Socket.Receive (byte[],int,int,System.Net.Sockets.SocketFlags) [0x00000] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/System/net/System/Net/Sockets/Socket.cs:1769
  at System.Net.Sockets.NetworkStream.Read (byte[],int,int) [0x0009b] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/System/net/System/Net/Sockets/NetworkStream.cs:513
  at System.IO.Stream.ReadByte () [0x00007] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/system/io/stream.cs:756```

from https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/5840/parsed_console/log.html


other then that, it looks good: four CI runs, without the symptom happening that https://github.com/mono/NUnitLite/pull/5 is trying to fix 🎉

**Comment by akoeplinger** [comment]
@lewurm if you look more closely you'll see that the reason for the "crash" is because it reached a timeout and the test was aborted:

```
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/scripts/ci/babysitter: Command `make` timed out
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/scripts/ci/babysitter: Saw timeout in test case MonoTests.System.ServiceModel.Channels.BinaryMessageEncodingBindingElementTest.ConnectionTcpTransport (never allowed). Will halt testing.
```

... and yes, that is something we've seen in the System.ServiceModel tests occasionally.

**Comment by lewurm** [comment]
nunit PR got merged, updated this PR, so it's ready to be reviewed 🙂

**Pull request merged**
