### PR TITLE
Add temporary workaround for internal StreamContent constructor.

### PR DESCRIPTION
**Pull request by baulig**
This is a temporary workaround and not a final solution.  Please read my detailed comment in https://github.com/mono/mono/issues/12996#issuecomment-464142887 for details.

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build

**Comment by marek-safar** [comment]
Actually I think we need this xammac

**Comment by baulig** [comment]
@monojenkins commit csproj

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by baulig** [comment]
@monojenkins build failed

**Pull request merged**
