### PR TITLE
[mobile_static] Merge changes for valgrind bitcode lane

### PR DESCRIPTION
**Pull request by alexanderkyte**
This injects valgrind into the places where we run entirely AOT, and fixes a memory mapping thing. This is what the bots have been building, with frequent rebases onto master. Valgrind appears to run on our AOT pipeline pretty well. After merge the lane will be changed to point to master.

This also offers a framework to use gcov and similar tools, by changing what RUNTIME_TOOLING_INJECT is.

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@luhenry is this useful at all at this point in time?

**Comment by alexanderkyte** [comment]
It was my old debugging code, it adds valgrind integration. Valgrind only really works with AOT.

**Comment by luhenry** [comment]
It's useful if it ever helped you debug something, since it might helps somebody else. So if you think it could be useful to anybody else, then please fix it and a quick documentation paragraph somewhere appropriate on how to use it.

**Comment by lewurm** [comment]
I'm closing it for now, feel free to reopen.

**Pull request closed without merging**
