### PR TITLE
Update the `System.Diagnostics.Tracing` namespace to better match the .NET API

### PR DESCRIPTION
**Pull request by qmfrederik**
(giving it one more try to see if the Xamarin both behaves well this time ;-))

A couple of constructors, method and properties are missing on the `EventSource` class, causing .NET code that makes use of these constructors, methods or properties to fail on Mono.

This patch adds these constructors, method and properties with no-op implementations, like the reset of the `EventSource` class.

All feedback is welcome!

### CODE REVIEW

**Comment by akoeplinger** [comment]
Thanks! I'll take a closer look next week, but here's some initial feedback:

- you need to add the new files to the .sources file of the assembly, the csproj is autogenerated and isn't used by the Mono build
- we're aiming to replace more and more code with the open-sourced code by MS, which makes it easier to maintain for us. Some types like the enums can be taken directly from https://github.com/mono/referencesource/tree/mono/mscorlib/system/diagnostics/eventing (e.g. by including them in the .sources file, like [this example](https://github.com/mono/mono/blob/master/mcs/class/corlib/corlib.dll.sources#L917)).

**Comment by qmfrederik** [comment]
Hi @akoeplinger,

That makes sense, thanks!

I've updated the PR to take files, where possible, from the Reference source. Just re-using `EventSource.cs` entirely didn't seem to be an option as it is tied to ETW on Windows.

I've updated the `.sources` file as well, we should be good there.

I may follow up with a PR which actually implements some of the event messaging logic, but let's keep this one for the missing methods - this should suffice to make code that uses the EventSource class run on Mono.

Let me know if there are changes that need to be made before you can accept this PR.

Cheers,

**Comment by qmfrederik** [comment]
Hi @akoeplinger ,

Just wondering whether you've had some time to have a look at this?

We'd love to see this get merged - currently prevents our app from running on Mono :-).

Frederik.

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
I did a few small fixed and squashed/pushed this to master with https://github.com/mono/mono/commit/ce24528b41d28a15feceb4485409d326b8608bc8. Thanks!

**Pull request closed without merging**
