### PR TITLE
Fix process leak in process enumeration.

### PR DESCRIPTION
**Pull request by jaykrell**
Dispose rejected ones.

This is https://github.com/mono/mono/issues/10143 and fix is from there.

I considered nulling skipped array elements, and then the tail, to help the GC, but I don't think it really helps, right?

Fixes https://github.com/mono/mono/issues/10143

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux ARMv7

**Comment by jaykrell** [comment]
@monojenkins build OS X x64

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-08

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-06

**Pull request merged**
