### PR TITLE
Fix assert to print and not crash, build the eglib tests and fix their warnings.

### PR DESCRIPTION
**Pull request by jaykrell**
g_assert isn't printing correctly, and can crash, depending on which target.

Also build the eglib tests and fix their warnings.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build OS X i386

**Comment by jaykrell** [comment]
Sure but I don't think it is warranted. C89 suffices, again.

**Comment by lambdageek** [comment]
I think you need a `va_end (args);` before you can call `va_start (args, format);` for a second time.

**Comment by jaykrell** [comment]
This fixes https://github.com/mono/mono/issues/8734.

**Comment by jaykrell** [comment]
@monojenkins build ARMv7

**Comment by jaykrell** [comment]
@monojenkins build ARMv5

**Comment by jaykrell** [comment]
@monojenkins build Aarch64

**Comment by jaykrell** [comment]
@monojenkins build Aarch64 Coop Suspend

**Comment by jaykrell** [comment]
@monojenkins build  failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
