### PR TITLE
Move much of mono-tls.h to mono-tls-inline.h.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by vargaz** [comment]
Whats the purpose of this ? mono-tls.h is included into mono-tls-inline.h.

**Comment by jaykrell** [comment]
It just limits exposure a bit.
Not a big deal. 
I was editing this and it’d reduce recompile.
mono-tls.h is included more than mono-tls-inline.h.

**Comment by jaykrell** [comment]
Hypothetically faster build. Hygiene. Not huge.

**Comment by jaykrell** [comment]
This is still good from the point of view, of "including less into less.".

**Pull request closed without merging**
