### PR TITLE
Do not set thread name repeatedly.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
This isn't as bad as it looks, or even perhaps bad at all.
The repetition appears not to be per work item, but per scheduling quantum, due to:

```
                //
                // Loop until our quantum expires.
                //
                while ((Environment.TickCount - quantumStartTime) < ThreadPoolGlobals.tpQuantum)
```

and if a thread can be a threadpool worker, and then not, and back and worth, then setting the name repeatedly is appropriate. I suspect that threads never stop being a threadpool worker but I could be wrong.

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
We need to reset the thread name because it might be changed in managed, and the API wants the thread name to be reset.

**Comment by vargaz** [comment]
We reset the thread name because that is what MS.NET does.

**Pull request closed without merging**
