### PR TITLE
Generate LLVM IR for OP_XEQUAL that is recognized by LLVM's vector pattern recognizers.

### PR DESCRIPTION
**Pull request by imhameed**
See the discussion in https://github.com/mono/mono/pull/16984#discussion_r326911650.

Fixes https://github.com/mono/mono/issues/16935.

Given:
```csharp
        [MethodImpl(MethodImplOptions.NoInlining)]
        static bool testfunc(Vector<float> vec1, Vector<float> vec2) {
            return vec1 == vec2;
        }

```

Before:
```asm
0000000000000000 <loWorld_Program_testfunc__System_Numerics_Vector_1_single__System_Numerics_Vector_1_single__>:
<BB>:1
   0:	c4 e1 f9 6e c6       	vmovq  %rsi,%xmm0
   5:	c4 e1 f9 6e cf       	vmovq  %rdi,%xmm1
   a:	c5 f1 6c c0          	vpunpcklqdq %xmm0,%xmm1,%xmm0
   e:	c4 e1 f9 6e c9       	vmovq  %rcx,%xmm1
  13:	c4 e1 f9 6e d2       	vmovq  %rdx,%xmm2
  18:	c5 e9 6c c9          	vpunpcklqdq %xmm1,%xmm2,%xmm1
  1c:	c5 f8 c2 c1 00       	vcmpeqps %xmm1,%xmm0,%xmm0
  21:	c4 e3 79 04 c8 0e    	vpermilps $0xe,%xmm0,%xmm1
  27:	c5 f0 54 c0          	vandps %xmm0,%xmm1,%xmm0
  2b:	c4 e3 79 04 c8 e5    	vpermilps $0xe5,%xmm0,%xmm1
  31:	c5 f8 54 c1          	vandps %xmm1,%xmm0,%xmm0
  35:	c4 e3 79 14 c0 00    	vpextrb $0x0,%xmm0,%eax
  3b:	c3                   	retq   
```

After:
```asm
0000000000000000 <loWorld_Program_testfunc__System_Numerics_Vector_1_single__System_Numerics_Vector_1_single__>:
<BB>:1
   0:	c4 e1 f9 6e c6       	vmovq  %rsi,%xmm0
   5:	c4 e1 f9 6e cf       	vmovq  %rdi,%xmm1
   a:	c5 f1 6c c0          	vpunpcklqdq %xmm0,%xmm1,%xmm0
   e:	c4 e1 f9 6e c9       	vmovq  %rcx,%xmm1
  13:	c4 e1 f9 6e d2       	vmovq  %rdx,%xmm2
  18:	c5 e9 6c c9          	vpunpcklqdq %xmm1,%xmm2,%xmm1
  1c:	c5 f8 c2 c1 00       	vcmpeqps %xmm1,%xmm0,%xmm0
  21:	c5 f8 50 c0          	vmovmskps %xmm0,%eax
  25:	31 c9                	xor    %ecx,%ecx
  27:	83 f8 0f             	cmp    $0xf,%eax
  2a:	b8 ff ff ff ff       	mov    $0xffffffff,%eax
  2f:	0f 45 c1             	cmovne %ecx,%eax
  32:	c3                   	retq   
***
```

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Comment by imhameed** [comment]
@monojenkins build failed

**Comment by imhameed** [comment]
@monojenkins build

**Comment by imhameed** [comment]
@monojenkins merge

**Pull request merged**
