### PR TITLE
[DRAFT]: Alternative SystemNative_FileCopy() implementation for Unix.

### PR DESCRIPTION
**Pull request by baulig**
Trying to get https://github.com/mono/mono/issues/16573 fixed.

Instead of creating two `FileStream`s, this does the entire operation in native code, so we can use the

```
int open(const char *pathname, int flags, mode_t mode);
```

variant.

When overwrite is not set, we use `O_CREAT | O_EXCL` to create the file, then skip the `fchmod()`.

Otherwise, we do `O_TRUNC` then `fchmod()` and if that fails, do a bit-by-bit comparison of the permissions - failing if the target file's permissions are less permissive than the source.

### CODE REVIEW

**Comment by filipnavara** [comment]
In upstream CoreFX I had to do something similar to support `clonefile`. Unfortunately it's not as easy as it looks. My initial version didn't match the file locking behavior of the managed code which resulted in observable changes. I tried to get it right (https://github.com/dotnet/corefx/pull/42458) but the duplicated code is difficult to maintain. I'm looking into some other solutions now...

**Comment by baulig** [comment]
Yeah, it's really tricky.  I actually looked at what the system `cp` command does and that's really complicated: https://github.com/coreutils/coreutils/blob/master/src/copy.c.

**Comment by baulig** [comment]
This currently breaks some tests:

> FileInfoTest.CopyTo1_DestFileName_AlreadyExists
FileInfoTest.CopyTo2_DestFileName_AlreadyExists
FileTest.Copy_DestFileName_AlreadyExists
FileTest.Copy_SourceFileName_DestFileName_Same
IsolatedStorageFileTest.CopyFile
IsolatedStorageFileTest.CreateSubDirectory
IsolatedStorageFileTest.DirectoryExists
IsolatedStorageFileTest.MoveDirectory

I'll have a look at those.

**Comment by baulig** [comment]
Looking at those failing tests, both `FileInfoTest.CopyTo1_DestFileName_AlreadyExists` and 
`FileInfoTest.CopyTo2_DestFileName_AlreadyExists` are cosmetic, it's just differences in error messages.

`Copy_SourceFileName_DestFileName_Same()` is a real regression; `File.Copy (source, source, true)` is supposed to throw but it doesn't with my patch.

The `IsolatedStorageFileTest` tests seem unrelated and then we have

```
9) TestCtors (MonoTests.System.TimeZoneTest.TestCtors)
     A04
  String lengths are both 19. Strings differ at index 12.
  Expected: "10/27/2002 03:00:00"
  But was:  "10/27/2002 02:59:59"
  -----------------------^
```

**Comment by Taloth** [comment]
One question I have here is why should file permissions be copied?   
The regular `cp` command doesn't so it unless you add a specific cmdline switch.    
Mono didn't copy permissions in the full framework. Nor does .Net Framework / .Net Core on Windows.   
Copies of files receive the default permissions in all those cases. Moves are different story.

**Comment by MichaIng** [comment]
@Taloth 
Exactly. This is highly unexpected and unpredictable since not all file systems (or dirs with permission flags) support permissions or changing them. If whichever user/program invokes mono to copy a file, it should be simply created with default permissions or the permissions forced by the file system mount option or dir flags. If for any reason permissions want to be preserved, at least it must be handled gracefully if this is not possible, similar to how `cp -p` handles it.

**Pull request closed without merging**
