### PR TITLE
[netcore] Avoid loading the globalization native lib in invariant mode.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by EgorBo** [comment]
In theory we could port our non-ICU based implementation so .NET could have three modes: ICU, invariant and "mobile". 🙂

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
