### PR TITLE
[I18N] Include missing subset of shift_jis characters 

### PR DESCRIPTION
**Pull request by resurrexit**
Fixes [bug 28321](https://bugzilla.xamarin.com/show_bug.cgi?id=28321).

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins build

**Comment by atsushieno** [comment]
There is no point of moving tools/uni2tab.c to CJK. All those C tools are collected there for consistency.

**Comment by marek-safar** [comment]
@resurrexit could you please revert your 67b89f23b220b34af29ff00ffd9fa27b8784dd8f change to allow us to merge your PR

**Comment by resurrexit** [comment]
@marek-safar Change reverted

**Comment by marek-safar** [comment]
approve

**Comment by resurrexit** [comment]
@marek-safar what do I need to do now?

**Pull request merged**
