### PR TITLE
Fix bug #46917

### PR DESCRIPTION
**Pull request by ylatuya**
The removed validation does not seems to be correct, for example
the generated Onvif media client has a GetVideoSources function that
is a combination of a first message with an input parameter and
a second message with the reply that is not void.
Removing this checks makes the client work correctly

### CODE REVIEW

**Comment by migueldeicaza** [comment]
build

**Comment by ylatuya** [comment]
Why is the CI system marking the build as not successful? If I go the details of the builds the results are:
	0 errors, 4 warnings
And warnings are unrelated to the changes.

**Comment by akoeplinger** [comment]
You can ignore those, GitHub only has success/failure states and there are a few unrelated flaky tests.

Do you think you can write a unit test that covers the problem? Probably something similar to https://github.com/mono/mono/blob/master/mcs/class/System.ServiceModel/Test/System.ServiceModel.Dispatcher/Bug32886Test.cs

**Comment by ylatuya** [comment]
I can try to copy a subset of the ONFIV protocol that reproduces the issue.

**Comment by ylatuya** [comment]
Added a new unit test for the bug that fails with the current implementation and second commit that fixes the issue

**Comment by ylatuya** [comment]
Link to the bug: https://bugzilla.xamarin.com/show_bug.cgi?id=46917

**Comment by marek-safar** [comment]
@akoeplinger could you review the change

**Comment by akoeplinger** [comment]
build

**Comment by ylatuya** [comment]
ping

**Comment by luhenry** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Pull request merged**
