### PR TITLE
[build] Skips RemoteExecutor bases tests on monodroid

### PR DESCRIPTION
**Pull request by marek-safar**
The proper implementation will be written later

/cc @grendello

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by akoeplinger** [comment]
do we have a tracking issue for enabling the proper support?

**Comment by marek-safar** [comment]
We don't as we don't own the runner either but will check if XA folks made an issue for this or not

**Pull request merged**
