### PR TITLE
Fixes #17817

### LINKED ISSUE #17817: DataContractSerializer does not call custom DataContractResolver for properties of type Object
1. Make a DataContract serializable class with a DataMember property of type Object. 
2. Make a custom DataContractResolver to encode/decode type info when serializing.
3. Use custom DataContractResolver to serialize instance of class.

Result: TryResolveType will not be called on custom DataContractResolver to specify the namespace and type string for the XML. Instead, the default namespace and type for the type of the contained object will be written. This is not correct, TryResolveType should be called for any object that is not the exact type of the property containing it.

This problem was noticed under mono running on linux. I have not tried to reproduce it using mono on other platforms, but I can confirm that .net framework on Windows does *not* have the issue.

I have tracked it down to this line of code:
https://github.com/mono/mono/blob/18dd48cad81592f66ce7d21a5293c76d69864501/mcs/class/System.Runtime.Serialization/ReferenceSources/XmlFormatWriterGenerator_static.cs#L512

Associated Blame Commit:
https://github.com/mono/mono/tree/8a1e9242f6d25e408644d0339dcf5c222d95671d

Associated Issue:
https://xamarin.github.io/bugzilla-archives/37/37116/bug.html

The commit states that the change was made because, "While serializing any type into a contract member of type object an exception would be thrown." This appears to be based on a misunderstanding of how Data Contracts are intended to work, because the described problem is, in fact, the correct behaviour. If the type of an object referenced by a given property is not exactly the declared type of that property, the serializer is supposed to throw an exception unless:

a) the object type was supplied as a "known type"
b) a custom DataContractResolver was supplied, and it returns "true" from TryResolveType

My guess is that the code that was failing before this commit was written against a more permissive implementation of DataContractSerializer, and then started to fail when the implementation was brought in line with the MS source. Instead of fixing the failing code to correctly use DataContractSerializer, DCS was changed to allow it to succeed. In the process, it broke custom DataContractResolvers for properties of type object.

The simplest solution would be to simply roll back the commit above and return the mono implementation to follow the MS one. I suspect would break code in other projects, however. There may not be any problem keeping DCS more permissive under mono if that is desired, but not calling the custom resolver should be fixed. This problem was found while porting an application to mono from .net framework, so, again, I can positively confirm that the custom resolver is called in the same scenario in the MS implementation. Custom resolvers are simply broken under mono without a fix to this  issue. 

 It would be nice if we could condition the line:

`} else if (memberType == Globals.TypeOfObject) {`

...on whether or not a custom resolver had been specified. Unfortunately, there is no access to this information at this point. Only the context object knows about the resolver, and it has it as a protected property. To make the decision here, we'd have to change XmlObjectSerializerContext to expose information about the presence or absence of a resolver.

It thus likely makes sense to instead revert that part of the code back, and instead implement the change in XmlObjectSerializerWriteContext.InternalSerializeReference. The code there could be nearly identical to the block inside the 'else if' above, but could also check for the presence of a custom resolver.

I am happy to implement, test, and submit this change if there is agreement about it.

Many Thanks,

Rob McCready

**Note:** When it comes to the question of whether or not to keep the existing permissiveness, it's worth considering that the implementation is inconsistent. It only allows derived types to be serialized with a default namspace & name when the declared type is Object. Properties of any other declared type will still throw an exception if the serializer finds a derived type instead.

### PR DESCRIPTION
**Pull request by RobCoder**
Fixes #17817

Separate commit fixes a single-line formatting issue I noticed while trying to get things to line up in my editor with the whitespace style used in the file. One existing line had spaces instead of the tabs used in the rest of the file.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@RobCoder looks like this breaks a few tests in DataContractJsonSerializerTest.

**Comment by RobCoder** [comment]
Ok, will look at.

**Comment by akoeplinger** [comment]
Given there was no activity on this PR for a few months I'm closing it for now, please feel free to reopen once you have a new fix :)

**Pull request closed without merging**
