### PR TITLE
[WinForms] Related Forms closing issue (#13150)

### LINKED ISSUE #13150: [WinForms] Related Forms closing
Assume one click a `button` on a Form `ButtonedForm` in the following program:
```
using System;
using System.Drawing;
using System.Windows.Forms;

namespace forms_closing_issue
{
    public partial class ButtonedForm : Form
    {
        private Button button = new Button();
        private Label label = new Label();
        
        public OnClosedForm onClosedForm;

        public ButtonedForm()
        {
            this.Controls.Add(button);
            this.Controls.Add(label);
            
            button.Click += click_Button;
            
            this.Text = "ButtonedForm";
            button.Text = "Click to Close";
        }

        protected void click_Button(object sender, EventArgs e)
        {
            // this.Controls.Remove(button); // !!!
            onClosedForm.Close();
        }
    }
    
    public partial class OnClosedForm : Form
    {
        public ButtonedForm buttonedForm;

        public OnClosedForm()
        {
            this.Text = "OnClosedForm";
        }

        protected override void OnClosed(EventArgs e)
        {
            base.OnClosed(e);
            buttonedForm.Close();
        }
    }
    
    public partial class MainForm : Form
    {
        public MainForm()
        {
            var onClosedForm = new OnClosedForm();
            var buttonedForm = new ButtonedForm();
            
            onClosedForm.buttonedForm = buttonedForm;
            buttonedForm.onClosedForm = onClosedForm;

            onClosedForm.Show();
            buttonedForm.Show();
            
            this.Text = "MainForm";
        }
    }
    
    static class Program
    {
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }
}
```
Let's consider two cases:
1.  The line `this.Controls.Remove(button); // !!!` is commented ...
2. ... and the line is uncommented.

### The line is commented
The `Button` is always present on the Form `ButtonedForm`. Click on this `button` leads to the following exception:
```
System.ArgumentException: Cannot activate invisible or disabled control.
  at System.Windows.Forms.ContainerControl.set_ActiveControl (System.Windows.Forms.Control value) [0x00221] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/ContainerControl.cs:210 
  at System.Windows.Forms.Control.Select (System.Windows.Forms.Control control) [0x00018] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs:1314 
  at System.Windows.Forms.Form.SelectActiveControl () [0x00079] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs:238 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Form.SelectActiveControl()
  at System.Windows.Forms.Form.WmClose (System.Windows.Forms.Message& m) [0x00115] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs:2597 
  at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x000de] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/Form.cs:2425 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs:228 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x00000] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/Control.cs:209 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x00085] in /home/voron/src/mono/mcs/class/System.Windows.Forms/System.Windows.Forms/NativeWindow.cs:240 
```
The origin of it is clear: `System.Windows.Forms.Form.SelectActiveControl ()` tries to select the `button` on the already closed Form `ButtonedForm`. This is so, because disposed `ButtonedForm` stores the `button` in the filed `active_control`.

### The line is ucommented
In this case forms hang. The Form `ButtonedForm` is closed and disposed, but the `child_controls` filed stores a link to the Label `label`. Note, that the `label.Parent` is already `null`. This condition turns the `while` loop in the `System.Windows.Forms.Control.SelectNextControl()` to be infinite. The unselectable `label` is the only child of Form, but the `Parent` link is broken. Therefore `SelectNextControl()` cann't move higher in the controls hierarchy and select a someone.

### PR DESCRIPTION
**Pull request by NVoronchev**
Fixes #13150

### CODE REVIEW

**Comment by marek-safar** [comment]
approve

**Comment by marek-safar** [comment]
Could you please try to include your test too

**Comment by marek-safar** [comment]
@filipnavara any objections?

**Comment by filipnavara** [comment]
There are more bugs in the logic around the active controls, but I never got around to test and clean it up. This is step in a good direction to at least test and fix known broken cases, so I am fine with the change.

**Pull request merged**
