### PR TITLE
[threads] Split abort/suspend into self and async cases

### PR DESCRIPTION
**Pull request by ludovic-henry**
Depends on https://github.com/mono/mono/pull/2554

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@lewurm comments are at https://github.com/ludovic-henry/mono/commit/d5d30fa61d8194bcbef2f39d4eb4bcdc817faeba and https://github.com/ludovic-henry/mono/commit/52336c5772d3faa088f1c65b3530adb34e0016aa

**Comment by lewurm** [comment]
looks good to me!  thanks for investing some time for code hygiene ;)

**Comment by ludovic-henry** [comment]
Previous @kumpera at:
https://github.com/ludovic-henry/mono/commit/70ee67c00604a5a9bdb8ab92047db075f8f44018
https://github.com/ludovic-henry/mono/commit/75b57414e82164b97c18394c02e80a7a95bd502f
https://github.com/ludovic-henry/mono/commit/d691db6f322b6901cac8e8e075a3e8eea0150653
https://github.com/ludovic-henry/mono/commit/b941271a33b755d16f8705fdb670b986948a06f6
https://github.com/ludovic-henry/mono/commit/53720a77a75c74b8dcf5cc8ce68eaf321664d835

**Comment by ludovic-henry** [comment]
build

**Comment by ludovic-henry** [comment]
build

**Comment by kumpera** [comment]
The code looks ok. The commit message still bad.

Explaining what's being done is important. It makes reading and understanding the commit a lot easier.

The explanation burden is on the author and not on everyone else.

**Comment by ludovic-henry** [comment]
@monojenkins merge

**Comment by ludovic-henry** [comment]
build

**Pull request merged**
