### PR TITLE
[wasm][debugger] Don't download unnecessary assemblies to DebugProxy

### PR DESCRIPTION
**Pull request by thaystg**
Identify if an assembly has debug information and only download it to debug proxy if it has, this will speed up a lot the debugger initialisation.

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
Should I do something?

**Comment by lewing** [comment]
@monojenkins Linux x64 FullAOT+Interpreter+LLVM

**Comment by lewing** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter+LLVM

**Comment by thaystg** [comment]
With or without the implementation in this PR, when we don't have debug information(PDB) we don't show the method in the callstack.
thays (1)

**Comment by thaystg** [comment]
Yes, if the assembly doesn't have embedded ppdb and doesn't have external pdb, there will not be the checksum and we will not load the assembly in the debugger proxy.

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Pull request merged**
