### PR TITLE
[wasm] Unify csc settings with the rest of Mono tree

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by vargaz** [comment]
Needs this one as well:
https://github.com/vargaz/mono/commit/254f4505cacdbc013dd19ba993c460ed5363f0c0

**Comment by akoeplinger** [comment]
@vargaz that's already covered by `/langversion:latest`

**Comment by marek-safar** [comment]
That's already in (this is master PR)

**Comment by alexischr** [comment]
@monojenkins backport to 2018-04

**Pull request merged**
