### PR TITLE
Add SignedCms to the TypeForwards in the System.Security.Cryptography.Pkcs facade

### PR DESCRIPTION
**Pull request by steveisok**
Fixes https://github.com/mono/mono/issues/18323

### CODE REVIEW

**Comment by marek-safar** [comment]
There are about 48 types in netstandard version, we should add them all (even if with PNSE)

**Comment by EgorBo** [comment]
@marek-safar the type is not part of the NS (at least 2.x) as far as I understand.

**Comment by marek-safar** [comment]
This is BCL not netstandard assembly so we can provide our own API but considering there are no _._ for Xamarin we should be a superset of NS2.1 implementation.

**Comment by steveisok** [comment]
In looking at the System.Security.Cryptography.Pkcs netstandard 2.1 package, these types are not in our facade:

```
System.Security.Cryptography.Pkcs.CmsSigner
System.Security.Cryptography.Pkcs.Pkcs12Builder
System.Security.Cryptography.Pkcs.Pkcs12CertBag
System.Security.Cryptography.Pkcs.Pkcs12ConfidentialityMode
System.Security.Cryptography.Pkcs.Pkcs12Info
System.Security.Cryptography.Pkcs.Pkcs12IntegrityMode
System.Security.Cryptography.Pkcs.Pkcs12KeyBag
System.Security.Cryptography.Pkcs.Pkcs12SafeBag
System.Security.Cryptography.Pkcs.Pkcs12SafeContents
System.Security.Cryptography.Pkcs.Pkcs12SafeContentsBag
System.Security.Cryptography.Pkcs.Pkcs12SecretBag
System.Security.Cryptography.Pkcs.Pkcs12ShroudedKeyBag
System.Security.Cryptography.Pkcs.Pkcs8PrivateKeyInfo
System.Security.Cryptography.Pkcs.Pkcs9LocalKeyId
System.Security.Cryptography.Pkcs.Rfc3161TimestampRequest
System.Security.Cryptography.Pkcs.Rfc3161TimestampToken
System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo
System.Security.Cryptography.Pkcs.SignerInfo
System.Security.Cryptography.Pkcs.SignerInfoCollection
System.Security.Cryptography.Pkcs.SignerInfoEnumerator
```

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins commit apidiff and csproj

**Comment by steveisok** [comment]
@monojenkins backport 2019-12

**Comment by steveisok** [comment]
@monojenkins backport 2019-10

**Pull request merged**
