### PR TITLE
[Crypto] Include CngKeyBlobFormat from reference sources (rm old)

### PR DESCRIPTION
**Pull request by knocte**
CngKeyBlobFormat was never included in the build, but anyway
we can include the one from referencesource now.

Detected by a user of Npgsql 3.0.5 which reported the problem
in stackoverflow:
http://stackoverflow.com/questions/35016066/failure-to-resolve-system-security-cryptography-cngkeyblobformat-when-using-npgs

### CODE REVIEW

**Comment by akoeplinger** [comment]
LGTM

**Comment by kumpera** [comment]
On hold.

**Comment by kumpera** [comment]
I got no objections, @marek-safar ?

**Comment by knocte** [comment]
I guess the failures of jenkins are not related to this PR, as it breaks in ARM Linux but passes on the rest.

**Comment by knocte** [comment]
build

**Pull request merged**
