### PR TITLE
[System] Improve Settings behavior (#15818, #2315)

### PR DESCRIPTION
**Pull request by ermshiperete**
Various changes and fixes mainly to ApplicationsSettingsBase class to improve the behavior. This fixes Xamarin bugs [#15818](https://bugzilla.xamarin.com/show_bug.cgi?id=15818) and [#2315.](https://bugzilla.xamarin.com/show_bug.cgi?id=2315)

### CODE REVIEW

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by ermshiperete** [comment]
Yes, it would be great if it could be merged.

**Comment by lewurm** [comment]
@ermshiperete could you rebase your changes on top of current master please?

**Comment by ermshiperete** [comment]
Changes rebased on current master - in the hopes that it will be merged this time :smile:

**Comment by migueldeicaza** [comment]
build

**Pull request closed without merging**
