### PR TITLE
Fix babysitter script to work on Windows (Cygwin) builders

### PR DESCRIPTION
**Pull request by xmcclure**
The babysitter script used for CI results was previously able to run
either on Windows or standard UNIX. However, the builders run Cygwin,
which turns out to need special support. To make Cygwin work two
changes were made:

1. Paths which are exported to Mono get filtered through `cygpath`.
Paths received back from Mono are filtered in reverse. The script now
tracks two sets of path strings.

2. Under certain circumstances in Cygwin, pgkill() attempts to close a
process group and finds it does not exist. My assumption is that this
is because it has already been closed. I dealt with this by simply
catching the failure and printing a warning.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@xmcclure LGTM. You'll need to remove the `if [[ "$OSTYPE" == "cygwin" ]]` in run-step.sh to enable the babysitter on cygwin.

**Comment by xmcclure** [comment]
Oh, right D:

**Comment by xmcclure** [comment]
I guess something's wrong, I'm only finding "azure artifacts" on the windows 32 and 64 builds but not on any unix platform :|
https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/5107
Added some debugging to run-step

**Comment by akoeplinger** [comment]
@xmcclure `23:59:59 scripts/ci/run-step.sh: line 3: scripts/ci/babysitter: Permission denied` you removed the execute flag from the script 😄

**Comment by xmcclure** [comment]
I really hate living in the same universe as git.

**Comment by xmcclure** [comment]
After enabling the babysitter I can get results in the viewer, but the Windows builds are failing with weird build failures. I don't see an obvious way this could have been introduced by my patch, so i'm going to merge and hope for the best…!

**Pull request merged**
