### PR TITLE
Indirect calls for easier atomic patching and some day read only code.

### PR DESCRIPTION
**Pull request by jaykrell**
I don't think direct calls are worthwhile.

They are never used on Mac or Windows. Only Linux.

When Xen is absent.
So the extra map32 and Xen checks.
Map32 recently having caused problems on Apple systems.

The instructions need to be and are padded for alignment.

Is the check for upper bits being zero sufficient?
It doesn't mean distance is within 2GB.

They aren't necessarily faster than direct.

nops consume processor resources.

Indirect is a good approach also I think to fix
 PowerPC, which isn't atomic and has known
 but not understood consistent failures.

Eventually, if the thunks are moved further away,
code pages could become readonly once full.
Granted, direct calls could be patched with an mprotect cycle also
with synchronization.

Separately, indirect need not use r11,
but can be thunks like this PR does.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Hm, Mac worked locally.

**Comment by jaykrell** [comment]
In one of the crashes, instruction pointer was off by one, leading to sigill.

**Comment by jaykrell** [comment]
Local test was with configure disable-system-aot.
That probably was it.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Any chance of this going in?

It simplifies the code a fair amount.
  Unifies more of the platforms -- no more Linux-specificity.
  Conserves a register in some paths (r11).
And *might* make it faster. Reports vary.
And is a hypothetical step towards readonly code pages.
And provides a model for PowerPC to follow, which kinda needs it.
But I've said all this before.

**Comment by lewurm** [comment]
My intuition tells me direct calls are worth it. Please backup your PR with some actual benchmark numbers.

**Comment by jaykrell** [comment]
https://github.com/mono/mono/issues/16018#issuecomment-521097802

"In the past I believe some other developers have looked at call indirect vs call + jmp with patchable target. Results varied based on hardware as you might expect, I think indirect call was concluded to be a little faster typically."


https://github.com/mono/mono/issues/16018#issuecomment-521107149

Also, it depends on how many indirect calls you got on the hot path. If there is less than 10, the indirect call is faster thanks to indirect call predictor. More than 10 and less than 1000, direct call to direct jump is faster because of the indirect call predictor gets filled in and does not help anymore. More than 1000, the performance becomes equal. L0/L1 caches are filled in and the performance is dominated by cache misses. 10 and 1000 thresholds vary based on hardware.

RIP relative call/jmp also has a one cycle penality I recall reading, but have to find it.
One would think the RIP relative+indirect has the same penality. I'll have to find the reference.

But there is also that nops require decoding.
I think we output multiple nops instead of multi byte nops.

And read only pages might help cache coherence. But if that does matter, it won't for a while, i.e not with this PR.

I'll try to collect some data.

**Comment by SamMonoRT** [comment]
@jaykrell - any benchmarking data to back these changes ?

**Comment by jaykrell** [comment]
No. Are there any mono has already?
How about taking https://github.com/mono/mono/pull/16699 instead/first? It is a subset of this. It still uses direct calls, on Linux, sometimes, but the indirect calls through a register are replaced by indirect calls through memory.
More so, PowerPC should adopt this approach, to fix race conditions, and resolve unresolved frequently seen bugs in the direct call patching.

**Comment by jaykrell** [comment]
Not having to align things also simplifies instruction sizing.

**Comment by akoeplinger** [comment]
The mono/mono repository is focused on stability and limiting code churn now so I don't think this change is worth doing here. If you think the change is important please reopen it in dotnet/runtime, thank you!

**Pull request closed without merging**
