### PR TITLE
Experimental pull request to explore increasing the inline limit to 100 instructions

### PR DESCRIPTION
**Pull request by migueldeicaza**
Per the discussion on this thread:

https://github.com/mono/mono/issues/6397

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
Should this be done for JIT only?

**Comment by lewurm** [comment]
looks like we do have some interesting bugs around inlining

**Comment by marek-safar** [comment]
More likely tests issue with missing `[MethodImpl(MethodImplOptions.NoInlining)]` where we check stack length

**Comment by migueldeicaza** [comment]
Ah that is a relief, I will update also the tests to more freely allow us to change this in the future.

**Comment by kumpera** [comment]
What's the objective of this PR?

**Comment by kumpera** [comment]
This change is not needed to experiment with bigger inline limits, there's an env var that does the same.

**Pull request closed without merging**
