### PR TITLE
Replace two loops with one loop.

### PR DESCRIPTION
**Pull request by jaykrell**
Cut the code in roughly half, depending on if the optimizer saw through it.

### CODE REVIEW

**Comment by jaykrell** [comment]
Noticed working on bugsweek.

**Comment by kumpera** [comment]
The new code is doing some cryptic boolean magic, the two existing loops a lot simpler to understand even without comments. 👎

**Comment by marek-safar** [comment]
Closing as such changes make Mono code even less attractive for external contributors

**Comment by jaykrell** [comment]
It isn't cryptic really. You see the two loops, almost identical, you wonder why the duplication, you see there is an easy to derive commonality; they just have reversed starting value and reversed termination condition and value, but still checking the same conditions over the same data.

**Pull request closed without merging**
