### PR TITLE
Match ext libgc api

### PR DESCRIPTION
**Pull request by ivmai**
Proposed 2 commits are code refactoring of libgc (and mono/metadata/boehm-gc.c, accordingly) to match API (semi-private part of libgc used by mono) of recent BDWGC master (https://github.com/ivmai/bdwgc). This should simplify optional replacement of internal libgc with the external one without any mono functionality loss.

### CODE REVIEW

**Comment by vargaz** [comment]
We suggest using the built-in sgen garbage collector of mono instead of libgc. sgen depends on the runtime portability code, so it can be ported to new platforms with little effort if the runtime already runs there.

**Comment by kumpera** [comment]
Hey @ivmai thanks for this patch set.

Right now we're trying to avoid changes in boehm as it's our fallback GC in cases something bad happens with mono's.

But it would be pretty cool to enable mainline boehm to be usable by mono.

From skimming through it, most changes look harmless, but it requires a more extensive review.

@lambdageek do you mind taking a pass on this PR?

**Comment by pr0vieh** [comment]
yes the boehm GC is hardcoded used for e.g. mkbundle :-1:

**Comment by ivmai** [comment]
Hello @kumpera and @vargaz,

Thank you for the feedback. I tried to prepare as small commits as possible.
Some of the benefits of using mainline boehm gc:
* has no compiler warning (currently libgc is compiled by default producing tons of warnings if a moderately recent gcc is used)
* more targets supported (e.g. arm64)
* no trouble with back-porting gc patches.

**Comment by lambdageek** [comment]
LGTM.

**Pull request merged**
