### PR TITLE
Revert 8862921b8611220f5d744f5b7f5d7e064a9769b6

### PR DESCRIPTION
**Pull request by DavidKarlas**
Reverts mono/mono#2090

### CODE REVIEW

**Comment by alexrp** [comment]
Why?

**Comment by 7sharp9** [comment]
Due to https://bugzilla.xamarin.com/show_bug.cgi?id=35579 and there was also an android issue too I think...

**Comment by kumpera** [comment]
@DavidKarlas can you include it in the SR1 board?

**Comment by pjbeaman** [comment]
Some further discussion on https://trello.com/c/lUhlZ1bP/425-mono-35548-9-new-msbuild-test-failures-on-cycle6-35579-recent-xbuild-changes-result-in-breakages-to-f-compiler-tools.

**Pull request merged**
