### PR TITLE
[runtime] Disable a test which asserts because of an abi break in rec…

### PR DESCRIPTION
**Pull request by vargaz**
…ent xcode/clang versions. Works around #58901.

### CODE REVIEW

**Comment by akoeplinger** [comment]
please revert https://github.com/mono/mono/commit/4d89d5f17bb72fb2e192736653923d8d90741a01 too so it actually gets used

**Comment by vargaz** [comment]
We shouldn't disable the whole test suite, this pr is a smaller fix:
https://github.com/mono/mono/pull/5423

**Comment by akoeplinger** [comment]
@vargaz not sure what you mean, https://github.com/mono/mono/commit/4d89d5f17bb72fb2e192736653923d8d90741a01 is already in master (that's why we should replace it with your more targeted workaround)

**Comment by vargaz** [comment]
I mean we should disable the test case and not the whole pinvoke2.exe.

**Comment by lewurm** [comment]
yes, your workaround is better @vargaz, but the referenced commit by @akoeplinger is already in master (you should rebase this PR and then add a revert for https://github.com/mono/mono/commit/4d89d5f17bb72fb2e192736653923d8d90741a01).

**Pull request merged**
