### PR TITLE
[2018-06] [merp] Batch of fixes

### PR DESCRIPTION
**Pull request by alexanderkyte**
This contains the fixes and tests I'm going to call "service pack 1" for ease of grouping

https://github.com/mono/mono/pull/11884
https://github.com/mono/mono/pull/11855
https://github.com/mono/mono/pull/11636
https://github.com/mono/mono/pull/11909
https://github.com/mono/mono/pull/12036

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins build deb with monolite

**Comment by alexanderkyte** [comment]
I really want to make sure that all of this works for VS4M before merging

**Comment by alexanderkyte** [comment]
@monojenkins build deb with monolite

**Comment by alexanderkyte** [comment]
@monojenkins build deb with monolite

**Comment by alexanderkyte** [comment]
Okay, this has been through some tests locally and it seems to work on toy examples / unit tests.

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
Why is this running on linux x64 if I added it to 


```
if HOST_DARWIN
else
PROFILE_DISABLED_TESTS += \
	merp-json-valid.exe
endif

```

**Comment by alexanderkyte** [comment]
So the OSX failure I'm seeing is:
```
osx/mcs/class/lib/net_4_x /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/runtime/mono-wrapper --debug /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/lib/net_4_x/nunit-lite-console.exe -exclude=MonoBug,BadTest -format:nunit2 -labels -result:/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/acceptance-tests/TestResult-ms-test-suite-conformance.xml ConformanceTests.dll
21:37:22 NUnitLite 1.0.0 (.NET 4.5 Debug)
21:37:22 Copyright 2013, Charlie Poole
21:37:23 
21:37:23 Runtime Environment -
21:37:23     OS Version: Unix 16.7.0.0
21:37:23   Mono Version: 4.0.30319.42000
21:37:23 
21:37:23 System.TypeLoadException: Could not resolve type with token 0100005b from typeref (expected class 'System.Collections.Generic.Stack`1' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
21:37:23   at (wrapper managed-to-native) System.Reflection.MonoMethodInfo.get_method_info(intptr,System.Reflection.MonoMethodInfo&)
21:37:23   at System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) [0x00000] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/corlib/System.Reflection/MonoMethod.cs:67 
21:37:23   at System.Reflection.MonoMethod.GetPseudoCustomAttributes () [0x00002] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/corlib/System.Reflection/MonoMethod.cs:410 
21:37:23   at System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) [0x0000a] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/corlib/System/MonoCustomAttrs.cs:77 
21:37:23   at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x00032] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/corlib/System/MonoCustomAttrs.cs:320 
21:37:23   at System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) [0x00000] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/corlib/System.Reflection/MonoMethod.cs:391 
```

**Comment by alexanderkyte** [comment]
The linux one looks legitimate. Reproducing now.

**Comment by luhenry** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
```MonoTests.runtime.finally_block_ending_in_dead_bb.exe
ParallelEnumerableTests.TestGroupBy```

and 

```
MonoTests.test-sgen-regular-ms-simple.bug-17590.exe
MonoTests.test-sgen-regular-ms-conc-simple.bug-17590.exe```

are almost certainly unrelated

**Comment by luhenry** [comment]
We still want to ship these fixes as part of 15.9.

**Comment by akoeplinger** [comment]
@monojenkins build

**Pull request merged**
