### PR TITLE
[System.Reflection] CoreFX import for EventInfo type.

### PR DESCRIPTION
**Pull request by MaximLipnin**
Part of #9660.

The changes:
- included corefx version of EventInfo type;
- included related xunit tests from corefx System.Reflection;
- made System.Reflection/EventInfo.cs partial and left some Mono-specific stuff only there.

Some changes will be done in corefx part.

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
@monojenkins build OS X x64 iOS SDK

**Comment by MaximLipnin** [comment]
@monojenkins build Linux AArch64

**Comment by marek-safar** [comment]
@MaximLipnin could you resolve the conflict?

**Comment by marek-safar** [comment]
@monojenkins commit apidiff and csproj

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Comment by marek-safar** [comment]
@MaximLipnin please rebase this one

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Comment by MaximLipnin** [comment]
Thanks for review!

**Pull request merged**
