### PR TITLE
[wasm][framework] Add signing of the framework assemblies

### PR DESCRIPTION
**Pull request by kjpou1**
Uses the Open key to sign the framework packages.

Closes https://github.com/mono/mono/issues/15275

### CODE REVIEW

**Comment by kjpou1** [comment]
Will do that as well but under another issue.  Wanted to get this in before Blazor takes another drop.

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build

**Comment by lewing** [comment]
@monojenkins build failed

**Pull request merged**
