### PR TITLE
Bump macsdk msbuild hash to msbuild that uses new roslyn, matching mono master

### PR DESCRIPTION
**Pull request by kg**
There's a comment in this script that says to 'fix run-test-mac-sdk.sh' but i can't find anything to fix in that script. Is that comment dead?

### CODE REVIEW

**Comment by radical** [comment]
@kg That refers to the *version* number in `(self, 'mono', 'msbuild', '15', ` -- `15` here, which doesn't need to be changed.

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by kg** [comment]
@monojenkins build makeinstall

**Comment by kg** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@radical shouldn't we change the version number since we're shipping msbuild 16? (I know it's just a cosmetic fix since it only shows up in the Mac installer).

**Comment by radical** [comment]
@akoeplinger Does it show up in the installer? I was under the impression that it is just used for creating staging directories by bockbuild.

**Pull request merged**
