### PR TITLE
[threadpool-io-poll] Use mono_poll instead of platform specific poll/WSAPoll

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by Therzok** [comment]
This fixed the build on Windows mingw32

**Comment by tritao** [comment]
LGTM

From what I could tell mono-poll uses select, so is there any performance impact to moving away from poll/WSAPoll?

**Comment by ludovic-henry** [comment]
select will have the same complexity as poll/WSAPoll. But as @Therzok  pointed out, it fixes the build on master, and does not break anything on other platforms.

**Comment by ludovic-henry** [comment]
It's been merged on master

**Pull request closed without merging**
