### PR TITLE
[System.IO] Enable CoreFX FilesystemWatcher on Android

### PR DESCRIPTION
**Pull request by alexischr**
Merge with https://github.com/mono/corefx/pull/130

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins build

**Comment by alexischr** [comment]
@monojenkins commit apidiff and csproj

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build failed

**Pull request merged**
