### PR TITLE
[jit] Implement RuntimeHelpers.IsReferenceOrContainsReferences intrin…

### PR DESCRIPTION
**Pull request by vargaz**
…sic. Fixes #53153.

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins build interpreter

**Comment by akoeplinger** [comment]
@monojenkins build interpreter

**Comment by vargaz** [comment]
This causes test failures because the non-intrinsic version always return true.

**Comment by vargaz** [comment]
Depends on:
https://github.com/mono/mono/pull/4509

**Comment by marek-safar** [comment]
build

**Comment by lewurm** [comment]
why do we need this intrinsic?  is `IsReferenceOrContainsReferences` used that often?

**Comment by vargaz** [comment]
Yes, its used all over the place in the bcl to avoid things like clearing arrays in List.Clear () etc.

**Pull request merged**
