### PR TITLE
check for iconv only once

### PR DESCRIPTION
**Pull request by saper**
It is enough to check for iconv
dependencies once in the eglib/configure
- just use the generated libtool
  library file to automatically
  add additional dependencies (if any).

While here, make sue libeglib.a
has libraries returned by LTLIBTOOL
as a libtool dependency.

### CODE REVIEW

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by saper** [comment]
build

**Comment by lewurm** [comment]
@saper please rebase your changes.

**Comment by saper** [comment]
Hi @lewurm the rebase was easy. I think CI is all fine.

**Comment by lewurm** [comment]
hey @saper, sorry to bother you again, can you have another look at this PR and rebase it? in the meantime, we moved `eglib` to a different folder...

**Pull request closed without merging**
