### PR TITLE
[llvm] Avoid using the preserveall calling convention in another plac…

### PR DESCRIPTION
**Pull request by vargaz**
…e on watchos.

Fixes https://github.com/mono/mono/issues/9318.

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
needs backport up to `2017-12`

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins backport 2018-06

**Comment by lewurm** [comment]
@monojenkins backport 2018-04

**Comment by lewurm** [comment]
@monojenkins backport 2018-02

**Comment by lewurm** [comment]
@monojenkins backport 2017-12

**Pull request merged**
