### PR TITLE
[checked-build] Add compile flag to disable checked-build tests selectively

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@xmcclure could you please review? Thank you!

**Comment by xmcclure** [comment]
I would prefer this default to on, as I am concerned about the mempool checking being turned off forever if it has to be specially turned on. That is not a blocker however and LGTM.

**Comment by kumpera** [comment]
I think this is a bad way of enabling feature selection for checked build.

--with-checked-build=yes should enable all checks that are ready to be used.

What we can have is flag to disable some of those checks.

--disable-checked-build-test=LIST

It should include every new kind of check we have.

The way to do it is just like we do with --enable-minimal.

**Comment by ludovic-henry** [comment]
@xmcclure @kumpera I updated it to add a flag to disable the checked build features selectively: gc, metadata or threads

**Comment by xmcclure** [comment]
Perfect, LGTM

**Comment by ludovic-henry** [comment]
@monojenkins merge

**Pull request merged**
