### PR TITLE
2017 10 Problem after generating mkbundle always shows "ERROR: [FAIL] -1073741511"

### PR DESCRIPTION
**Pull request by sourceskyboxer**
I always tried to use Mono Runtime 5.8.0 x86 from download of Mono.

But it throws error:

> C:\Users\Jens\source\repos\Example\Example\bin\Debug>mkbundle --deps Example.exe --static -c -o temp.c -oo temp.o -v
> OS is: Windows
> Sources: 1 Auto-dependencies: True
> Attempting to load assembly: Example.exe
> Assembly Example.exe loaded successfully.
> Attempting to load assembly from: .\I18N.West.dll
> Attempting to load assembly from: .\I18N.dll
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\gtk-sharp
> Attempting to load assembly from: .\glib-sharp
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\System
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\System.Configuration
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\System.Xml
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\System
> Attempting to load assembly from: .\System.Configuration
> Attempting to load assembly from: .\System
> Attempting to load assembly from: .\System.Xml
> Attempting to load assembly from: .\atk-sharp
> Attempting to load assembly from: .\glib-sharp
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\gdk-sharp
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\glib-sharp
> Attempting to load assembly from: .\pango-sharp
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\glib-sharp
> Attempting to load assembly from: .\Mono.Cairo
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\Mono.Cairo
> Attempting to load assembly from: .\pango-sharp
> Attempting to load assembly from: .\Mono.Cairo
> Attempting to load assembly from: .\glib-sharp
> Attempting to load assembly from: .\mscorlib
> Attempting to load assembly from: .\I18N
> Attempting to load assembly from: .\mscorlib
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\Example.exe
>  config from: C:\Users\Jens\source\repos\Example\Example\bin\Debug\Example.exe.config
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\mscorlib.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\gtk-sharp.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\glib-sharp.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\System.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\System.Configuration.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\System.Xml.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\atk-sharp.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\gdk-sharp.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\pango-sharp.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\Mono.Cairo.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\I18N.West.dll
>    embedding: C:\Users\Jens\source\repos\Example\Example\bin\Debug\I18N.dll
> AS = as (default)
> as -o temp.o temp.s
> **ERROR: [Fail] -1073741511**

I always checked current paths of Visual Studio 2015 and 2017 and MSBuild.

What does it mean "-1073741511"?

I have path to Cygwin x86 ( D:\Cygwin )

Can you check if errors are thrown.... If it already fixed than I will download mono 5.4.1.6 and recompile

### CODE REVIEW

**Comment by sourceskyboxer** [comment]
Welcome @dnfclas!

@akoeplinger, really initial mono bundle for Android? Wow I thought Mono can't work for tablets and phones - I never listen about next release. Nice! I would like to get new release and they will try mono-bundled apk into Android 7.x and 8.x+ You said "monodroid" .

**Comment by luhenry** [comment]
Why are you trying to merge the 2017-10 branch into master?

**Comment by luhenry** [comment]
Please fill up a bug on https://bugzilla.xamarin.com if you are witnessing one.

**Comment by evincarofautumn** [comment]
Side note, -1073741511 = 0xC0000139 = Entry Point Not Found. It should show an error message indicating which symbol is missing in the DLL.

**Pull request closed without merging**
