### PR TITLE
[build] Enable Link Time Optimization by default

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@schani could we performance test this PR? I would like to know if we could get a substantial gain from Link Time Optimization

**Comment by vargaz** [comment]
How does this affect build times ?

**Comment by lewurm** [comment]
builddeb

**Comment by akoeplinger** [comment]
The PR doesn't build, so `builddeb` won't work: https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/1804/parsed_console/log_content.html#ERROR1

**Comment by alexrp** [comment]
A few thoughts:

1. I don't think enabling LTO by default is a good idea. Countless systems/distros have fragile LTO support that requires special setup to work or just doesn't work at all. No objection to adding a flag to easily enable it, though.
2. It's quite likely that we have multiple functions in the runtime which are written to assume that LTO doesn't happen. Stuff like GC keep-alive functions. We'd need to audit these as stuff could break in subtle ways.
3. I'm a bit worried that at our current default of `-O2`, LTO won't do much for us, or at least, it will be significantly less effective than it could be. I think we should seriously look into making `-O3` the default. Similarly, `-fwhole-program` is a flag worth looking into for linking the final `mono` executable.

**Comment by ludovic-henry** [comment]
We get a linker error with gcc on linux. It's complaining it cannot find TLS variable. I am putting that PR on hold for now, and I will investigate later.

**Comment by kumpera** [comment]
gcc and clang get orders of magnitude more testing and exposure to -O2 than all optimization level above that combined.

The same applies for mono. We are consistently shipping O2 for half a decade now. We did hit a few compiler bugs during that time.

This all means a much much bigger chance of us being hit by compiler bugs or issues due to bad code in mono. Perf numbers must be mind blowing to justify the extra cost on the team.

**Pull request closed without merging**
