### PR TITLE
Remove hacks.h.

### PR DESCRIPTION
**Pull request by jaykrell**
Looks kinda no-opish, except isunordered.
These ifdef/define games confuse things because these are functions in C++, not macros.
The only likely difference is HPUX64 + non-gcc.
Which would be IA64 or HPPA64.
The C99 enabling is likely redundant with compiling for C99.
Part of https://github.com/mono/mono/pull/10764.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Comment by jaykrell** [comment]
There was one alive looking part, isordered, for 64bit HP-UX, when not using gcc. Which would imply HPPA64 or IA64. So ok to delete for now and probably forever?

**Comment by jaykrell** [comment]
Also the define C99 could be kept but probably not needed. I guessing it dates to not compiling overall as C99.

**Comment by lewurm** [comment]
it's a leftover from 2001.

**Pull request merged**
