### PR TITLE
[wasm][debugger] evaluateOnCallFrame use double numbers

### PR DESCRIPTION
**Pull request by lewing**
Numbers are doubles not ints so support the full size.  I'll add tests before committing.

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
Um wasm failed with:

```
stderr: Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
stderr:
stdout:
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.Regex.Match(String input)
   at WebAssembly.Net.Debugging.TestHarnessStartup.<>c__DisplayClass9_0.<LaunchAndServe>b__0(Object sender, DataReceivedEventArgs e) in /mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/ProxyDriver/TestHarnessStartup.cs:line 87
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Test Run Aborted.
Total tests: Unknown
     Passed: 4
 Total time: 18.1238 Seconds
Makefile:740: recipe for target 'run-debugger-tests' failed
make: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm'
```

**Comment by lewing** [comment]
Yeah, that looks like something related to the build or the bot.  I'm at a loss for how this change could have triggered a problem at connection time.

**Comment by lewing** [comment]
@monojenkins build failed

**Pull request merged**
