### PR TITLE
[merp] Revert 7a0425e which is causing xamarin-android failures

### PR DESCRIPTION
**Pull request by naricc**
This commit https://github.com/mono/mono/commit/7a0425e81ffe0e77a4ba22ff45e691934ecc49a1 is causing the following xamarin-android issue: https://github.com/mono/mono/issues/20275

This pull request reverts it.

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
Are we waiting until we confirm a new build off `2020-02-test` succeeds to merge this?

**Comment by naricc** [comment]
> Are we waiting until we confirm a new build off `2020-02-test` succeeds to merge this?

Yes. And some failed builds, but I think that is random. Do you know how to verify if 2020-02-test actually produced the package we need? Or who to ask about that?

**Comment by naricc** [comment]
@monojenkins rebuild-failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by naricc** [comment]
@monojenkins backport to 2020-02

**Pull request merged**
