### PR TITLE
Add O_NOATIME to OpenFlags

### PR DESCRIPTION
**Pull request by turbo**
O_NOATIME (Linux > 2.6.8): Do not update the file last access time (st_atime in the inode) when the file is read(2). Programs that merely index the existence of a file (backup programs e.g.) can reduce disk load using this flag.

### CODE REVIEW

**Comment by luhenry** [comment]
Hi @turbo, thank you for your contribution! For your change to work, you would need to update https://github.com/mono/mono/blob/master/support/old-map.c#L24-L50 and https://github.com/mono/mono/blob/master/support/map.c#L4004-L4112. Thank you

**Comment by turbo** [comment]
@luhenry Thanks, will do.

**Comment by luhenry** [comment]
@monojenkins build

**Comment by luhenry** [comment]
It seems you are missing the declaration of `Mono_Posix_OpenFlags_O_NOATIME` that you are using at https://github.com/mono/mono/pull/8993/files#diff-d01845e9b82f6e765dad0f3c3d9b4d52R4079 and https://github.com/mono/mono/pull/8993/files#diff-47c1c0df803d9b35c0d219363fd54433R45. You have to declare it at https://github.com/mono/mono/blob/9add1a79714a50f0ef2ef473dc41e2e30bb1b1fa/support/map.h#L775-L810

**Comment by luhenry** [comment]
@monojenkins build

**Comment by marek-safar** [comment]
build

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff

**Pull request merged**
