### PR TITLE
Bump msbuild 2018-06 branch to track xplat-master

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build

**Comment by radical** [comment]
@akoeplinger 
Any idea what is wrong here?

OSX Extended:

```+ scripts/ci/run-jenkins.sh
*** start: bockbuild
/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/ci/babysitter: Could not execute command `CFLAGS=  -ggdb3 -O2 -m64 -arch x86_64`
*** end(0): bockbuild: \e[41mFailed\e[0m```

**Comment by akoeplinger** [comment]
@radical yes, I fixed that with https://github.com/mono/mono/compare/0e5a7816e7cb33a484052710176e00c2df97366b%5E...cff5aefe1d5a4600190ac6a84b7ec7a2e59e0ffa%5E but forgot to retrigger your builds. I did that now.

**Comment by radical** [comment]
@akoeplinger I think that change is not present in `2018-06`.

**Comment by akoeplinger** [comment]
MSBuild tests succeeded, merging.

**Pull request merged**
