### PR TITLE
[runtime] Fix resolution of a type with an incorrect assembly name.

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by migueldeicaza** [comment]
This looks good to go.

**Comment by kumpera** [comment]
This change conflicts with the callers that expect a NULL image to mean probe corlib.

**Comment by migueldeicaza** [comment]
There is one documented case, this one:

mono_reflection_type_from_name

Which states that this will look at corlib if NULL is returned, but when I see its references, when NULL is returned, this surfaces the result as a type load exception.

Was there another use that I missed?

**Comment by kumpera** [comment]
https://github.com/mono/mono/blob/master/mono/metadata/icall.c#L1285

This fix looks to be in the wrong place. A broken assembly lookup should be handled in the assembly lookup code and not on type lookup.

This change effectively breaks corlib probing as image will be null when it reaches that point.
Here's the test that exercise that path:

using System;

class Program
{
	static void Main()
	{
		Type good = System.Type.GetType("System.Nullable`1[[System.Int32, mscorlib]]");
		Type bad = System.Type.GetType("System.Nullable`1[[System.IO.Pipes.PipeOptions, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]");

		Console.WriteLine ("good is {0}", good);
		Console.WriteLine ("bad is {0}", bad);
	}
}

The right fix is to check for a null image at the beginning and use corlib in such case.

**Comment by alexanderkyte** [comment]
@ninjarobot I pinpointed the bug as being that we were using corlib as a default for the image but not the rootimage. The test that @kumpera said is a test for the desired defaulting behavior has been added to the test suite and it all works locally.

**Pull request merged**
