### PR TITLE
Replace mono_object_get_class with mono_object_class to avoid gc transitions.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64

**Comment by lambdageek** [comment]
@monojenkins backport to 2018-10
@monojenkins backport to 2018-08
@monojenkins backport to 2018-06

**Comment by jaykrell** [comment]
Note that, in the related series, there are merge conflicts. If we want them all. Merge conflicts not fatal of course.

**Comment by marek-safar** [comment]
@jaykrell the backports fail to build, could you update them?

**Pull request merged**
