### PR TITLE
return_val_and_set_pending_if_nok macro is missing do { } while (0);

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by lambdageek** [comment]
I think we should work to get rid of uses of this macro (which are in a single non-handleized icall in `locales.c`) and not spend time on fixing it.  `mono_error_set_pending_exception` is a stopgap that we're living with until all icalls route MonoErrors out to their handlized wrapper.

**Comment by jaykrell** [comment]
Fair enough, I hadn't noticed that.

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT

**Pull request merged**
