### PR TITLE
[ci] run regression tests with AOT

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Looks like it fails on Linux x86 / macOS x86 and Windows.

```
Mono Ahead of Time compiler - compiling assembly /mnt/jenkins/workspace/test-mono-pull-request-i386/mono/mini/iltests.exe
AOTID A23F364D-172E-95C4-BDB9-8A033A17186F
* Assertion: should not be reached at mini-x86.c:5878
...
```

On windows it can't find clang.exe ;)

**Comment by lewurm** [comment]
It's expected to fail on i386 linux/osx, see https://github.com/mono/mono/issues/11091 and https://github.com/mono/mono/pull/11089.

For windows, let us not run there for now. I'll disable it.

**Comment by jaykrell** [comment]
Is my understanding correct: The intent here, is that this stuff already runs, but in a way that failures are hidden from the automation. So run them again, earlier? (or later, ok), in a way that isn't hidden? 

Wasteful of course, and would be nice to surface the errors from the other run, or maybe have CI search out assertion failures, but ok. The duplication is likely small.

**Comment by lewurm** [comment]
It's a bit duplication, but hard to share: `test_op_il_seq_point.sh` either uses `--aot` or `--compile-all` to trigger a compilation with the JIT for a specific method and extracts some information. It also runs the JIT with slightly different configuration than default (`MONO_DEBUG=no-compact-seq-points,single-imm-size `).

While I agree that it would be good to fix `test_op_il_seq_point.sh` to do proper error propagation, we should also run the AOT mini regression tests, which this PR does (that makes fixing `test_op_il_seq_point.sh` kinda not necessary anymore 😄 ).

**Comment by akoeplinger** [comment]
@monojenkins build Linux i386
@monojenkins build OS X i386

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by akoeplinger** [comment]
@lewurm this seems to still fail on Linux/OSX i386, can you try merging master?

**Comment by lewurm** [comment]
There is some problem on linux/macos i386. I'll look into it.

**Comment by lewurm** [comment]
@monojenkins build failed

**Pull request merged**
