### PR TITLE
Callspec unit testing and a bugfix

### PR DESCRIPTION
**Pull request by urisimchoni**
This patch set adds some unit tests for call specifications in --trace and log profiler, and fixes a bug.

The bug is that when specifying a method (e.g. --trace=M:NameSpace.Foo:Bar), it matches same method of a different class (e.g. NameSpace.Foo2:Bar) if the matched class's name begins with the callspec class name (e.g. Foo2 begins with Foo)

The first commit adds the test suite and some passing tests, the second commit fixes the bug, the third commit adds a test which could not pass without the bugfix.

### CODE REVIEW

**Comment by urisimchoni** [comment]
I can see the OS X build fails compiling the .cs test file into an exe. I need to compile some C# code for the unit test, so that I can load and process the resulting assembly. Can someone please send some guidance / examples of the proper portable way to do it?
Thanks,
Uri

**Comment by vargaz** [comment]
The .cs file should be compiled using:

CLASS=$(mcs_topdir)/class/lib/$(DEFAULT_PROFILE)

with_mono_path = MONO_PATH=$(CLASS)

RUNTIME = $(with_mono_path) $(top_builddir)/runtime/mono-wrapper

MCS_NO_UNSAFE = $(TOOLS_RUNTIME) $(CSC) -debug:portable \
	-noconfig -nologo \
	-nowarn:0162 -nowarn:0168 -nowarn:0219 -nowarn:0414 -nowarn:0618 \
	-nowarn:0169 -nowarn:1690 -nowarn:0649 -nowarn:0612 -nowarn:3021 \
	-nowarn:0197 $(PROFILE_MCS_FLAGS)
MCS_NO_LIB = $(MCS_NO_UNSAFE) -unsafe

MCS = $(MCS_NO_LIB)

%.exe: %.cs
	$(MCS) -r:$(CLASS)/System.dll -r:$(CLASS)/System.Xml.dll -r:$(CLASS)/System.Core.dll -out:$@ $<

**Comment by urisimchoni** [comment]
2nd version - Hopefully fixed the makefile.
Thanks,
Uri

**Comment by urisimchoni** [comment]
Looks like the unit tests run before the .cs=>.exe compilation. I'll figure it out...

**Comment by urisimchoni** [comment]
Hmmm, still failing. Seems like I forgot to test without installing first, and it's looking for mscorlib in its install location (at least the Linux x64 build). I'll fix that.

**Comment by urisimchoni** [comment]
test fails on macOS, mutex operation fails. Probably I'm missing some initialization code in the unit test to initialize that mutex.

I have no access to macOS machines in order to debug this. What I can do is update the pull request with a version that prints a backtrace if lldb is installed on the build machine, and if it's acceptable to use the project's resources for debugging pull requests.

I have no idea what the Windows failure is about...

**Comment by kumpera** [comment]
Hi, I fixed your test. Thanks for contributing one!
I'll merge this PR once building results come in

**Comment by urisimchoni** [comment]
Thanks for picking this up!
I was bogged down with other things, and also kind of puzzled how to go about this, given that it was failing on a platform I had no access to, so thanks for doing this work.

**Comment by kumpera** [comment]
The test program doesn't link correctly on linux, I'll take a look early next week.

**Comment by urisimchoni** [comment]
Adding another commit to fix x64 build - let's see how that goes with other arches...

**Comment by urisimchoni** [comment]
Now it seems to be passing (Aarch64 failure doesn't seem to be related). @kumpera - Shall I squash the added two commits into the first to remain "git-bisect-correct"? (asking because I'm not the author of the 4th commit. Alternatively, if the intent is to squash them all into one, then it doesn't matter. I made the split because it separates adding unit test infrastructure from fixing a bug)

Thanks,
Uri

**Comment by kumpera** [comment]
Merged, failures are unrelated.

**Pull request merged**
