### PR TITLE
Enable Float32, fix linears optimization, and rework localloc

### PR DESCRIPTION
**Pull request by nealef**
- Enable full float32 support  
  - Add instructions for FP operations: abs[f]/ceil[f]/floor[f]/round[f]/sqrt[f]/trunc[f]
  - Enable these instructions in mono_arch_emit_inst_for_method()
  - Handle return of float32 results
  - Correct rounding mode for OP_LCONV_TO_R_UN processing
- Enable MONO_OPT_LINEAR optimizations
  - Correct prolog processing of structure returned variable
- Rework OP_LOCALLOC for cases where alloc size > 4k
- Add OP_POPCNTxx support
- Minor typo (missing tab)

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by nealef** [comment]
Please hold as I think I found a bug.

**Comment by nealef** [comment]
Should be good to go.

**Comment by akoeplinger** [comment]
@nealef looks like the sync bot runs into a merge conflict, would you mind manually porting this to dotnet/runtime?

**Pull request merged**
