### PR TITLE
[DO NOT MERGE] Memory accounting

### PR DESCRIPTION
**Pull request by evincarofautumn**
For benchmarking purposes.

### CODE REVIEW

**Comment by evincarofautumn** [comment]
builddeb

**Comment by evincarofautumn** [comment]
builddeb

**Comment by akoeplinger** [comment]
Your branch is missing some recent fixes that unbroke the tarball build, I'd suggest rebasing against master.

**Comment by evincarofautumn** [comment]
builddeb

**Comment by akoeplinger** [comment]
Another package break snuck in 😢 Please rebase again or pick b6b15257095a7aa8ff1a75e515e843ceea454d0f into your branch, this one is green.

**Comment by evincarofautumn** [comment]
😞

**Comment by evincarofautumn** [comment]
builddeb

**Comment by evincarofautumn** [comment]
When running Roslyn on my machine, with master it’ll take ~9s, spending ~5% of the execution time in `__psynch_mutexwait`—looks like the GC lock. With this branch, sometimes that figure shoots up to 15–20s, with 15–20% of the execution time spent in `__psynch_mutexwait` in a long tail near the end of the run.

**Comment by schani** [comment]
@kumpera We'd like to merge this.  A customer is waiting for help with memory accounting problems: https://bugzilla.xamarin.com/show_bug.cgi?id=40912

Objections?

**Comment by akoeplinger** [comment]
@schani @evincarofautumn this breaks the build on ARM and Windows, you need to fix this before you can merge.

**Comment by kumpera** [comment]
I'm fine with the mono_valloc changes.

The eglib changes are a mix of hacks and plain bad.

There's a PR to add the standard glib malloc hooks that could be used for that and I think it's a much saner approach. I suggest you guys to adopt that PR and get it through.

**Pull request closed without merging**
