### PR TITLE
Convert K&R warning farm to ANSI and add static/const.

### PR DESCRIPTION
**Pull request by jaykrell**
Also smaller part fix C-vs.-C++-isms.

### CODE REVIEW

**Comment by lewurm** [comment]
where are those files in `mcs/jay` coming from? are we c/p them from somewhere upstream?

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT

**Comment by jaykrell** [comment]
There are so many hits on this things on the web that it isn't quick to find a/the canonical one. I did find another in github where they also ANSI-ifed it according to the checkin comments. Apparently this is quite the popular LALR parser generator for targeting Java and C#. But there are many others like javacc, antlr/pccts, etc.

**Comment by migueldeicaza** [comment]
Yes, I am fine with the changes.

**Pull request merged**
