### PR TITLE
Change license and publish xamarin mono extensions

### PR DESCRIPTION
**Pull request by kumpera**
See http://www.mono-project.com/news/2016/03/31/mono-relicensed-mit/

### CODE REVIEW

**Comment by tritao** [comment]
:+1:

**Comment by kumpera** [comment]
build

**Comment by scottstanfield** [comment]
Watching this from Microsoft Build 2016. Congrats Xamarin. This is huge.

**Comment by ghuntley** [comment]
Fantastic news, thanks for doing this!

**Pull request merged**
