### PR TITLE
[jit] Add beginnings of llvmonly+interp mixed mode support.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
mini tests fail on wasm:
```
Stacktrace: 

Error
   at Anonymous function (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/mono.js:1:22990)
   at _emscripten_asm_const_i (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/mono.js:1:23510)
   at Module[_mono_wasm_invoke_method] (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/mono.js:1:202025)
   at BINDING.call_method (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/mono.js:1:168287)
   at Anonymous function (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/mono.js:1:170396)
   at App.init (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/runtime.js:290:5)
   at Anonymous function (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/runtime.js:120:5)
   at Anonymous function (/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm/bin/test-suite/mono.js:1:151802)
WASM-ERR: * Assertion at /mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini-exceptions.c:288, condition `<disabled>' not met
ABORT: undefined
Stacktrace: 

```

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
Reverted some commits which didn't work on wasm.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
