### PR TITLE
Fix for issues 9653, 22297 

### PR DESCRIPTION
**Pull request by SoujiSeta**
This is a fix for the System.ObjectDisposedException caused by editing a text cell in a DataGridView control a second time.
The issue was caused by calling dispose on a static DataGridViewTextBoxEditingControl object after it has been set as the editingControl for the DataGridView

The full explanation of the cause of this issue is located in this comment https://bugzilla.xamarin.com/show_bug.cgi?id=9653#c5

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by vargaz** [comment]
The pull request includes a merge commit which is not needed.

**Comment by migueldeicaza** [comment]
Applied the patch manually, without the merge.

**Comment by migueldeicaza** [comment]
Actually, I did not apply that patch, it was a band aid.

I applied a better fix that solves the problem correctly (and deals with multiple instances of DataGridView running at the same time as well)

**Pull request closed without merging**
