### PR TITLE
[MacSDK] Bump NuGet to 4.8.1

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
cc: @mrward

**Comment by alexischr** [comment]
@monojenkins build OS X package

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by radical** [comment]
@akoeplinger any clue what happened with `Backport to 2018-08 - Failure while triggering jenkins job`?

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by radical** [comment]
The failure doesn't seem related to this PR. Could this be merged, please?
/cc @marek-safar @akoeplinger

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Pull request merged**
