### PR TITLE
mono_string_to_utf32 produces unused data.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build armv7 hard float

**Comment by jaykrell** [comment]
@monojenkins build linux armv7 hard float

**Comment by jaykrell** [comment]
@monojenkins build linux arm v5 soft float

**Comment by jaykrell** [comment]
@monojenkins build Windows i386

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Pull request merged**
