### PR TITLE
[Mono.Options] Write to NULL if we are building for PCL/NetStandard

### PR DESCRIPTION
**Pull request by mattleibow**
Mono.Options is built for:
 - net4
 - pcl/portable
 - netstandard/netcore

In the cross-platform instances, `System.Console` is not always available. This PR makes this "optional" by requiring the user to specify a writer.

### CODE REVIEW

**Comment by jonpryor** [comment]
Uh....no? At least, not without seeing your NuGet package?

My concern is that developers may/will see the PCL version and immediately consider it the "superior" version, because it can be used everywhere. At which point they'll use `CommandSet` and wonder why nothing happens.

That's *really* a poor experience.

I can see three "sane" solutions here:

1. Provide a `TextWriter` subclass which uses `Debug.WriteLine()`. This is also not entirely desirable, as `Debug.WriteLine()` output is also frequently (usually?) not shown, but at least it's *possibly* shown.
2. Use the "Bait and Switch" PCL trick in the NuGet package, so that on "decent" platforms/profiles -- those with `System.Console` -- the non-PCL version is used.
3. Require that `output` and `error` be non-`null`, and remove the default to `Console.Out`/`Console.Error`.

Making a likely-to-be-widely-used version *useless* "by default" is not acceptable.

**Comment by mattleibow** [comment]
@jonpryor I made some changes, which I think solve a few problems. Firstly, I am building for - and including the netstandard1.3 in the NuGet, which will be nice for everyone (except WP8/Win8). 

The Full .NET Framework has its own build. The actual PCL is really now just going to be used a reference assembly, but still works fine.

Next, I split the constructor into two - one requires 2 `TextWriter`s (in both PCL/Net4/NetStd) and the other uses the default `Console` (in Net4/NetStd).

I also added some features back (which I had removed for PCL) for .NET Standard.

**Comment by jonpryor** [comment]
This looks better.

However, since you've changed the constructor, the docs are now out-of-date. Please run:

    make doc-update

to update the `mcs/class/Mono.Options/Documentation` directory and then please correct/add the documentation for the new `CommandSet` constructors.

**Comment by mattleibow** [comment]
@jonpryor Done

**Pull request merged**
