### PR TITLE
Make enum values obvious.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by lambdageek** [comment]
Why?

**Comment by jaykrell** [comment]
So when I read the header I can know their values quickly.
More readable code. Less writable or mergable, but readable wins.

**Comment by jaykrell** [comment]
I can only eyeball a few lines to count them. 30 is too many to eyeball.

**Comment by vargaz** [comment]
Adding values in the middle will be painful though.

**Comment by jaykrell** [comment]
There are multiple options for adding values:
 1 don't add them in the middle
 2 renumber carefully to preserve readability at the cost of writability
 3 if you really need to add to the middle and renumbering is really difficult, undo this change then

**Comment by jaykrell** [comment]
@monojenkins build  failed

**Comment by jaykrell** [comment]
@monojenkins build  Linux AArch64 Coop Suspend

**Comment by jaykrell** [comment]
@monojenkins build Windows i386

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Pull request merged**
