### PR TITLE
[sdks] Add a configure script, disable all platforms by default, use …

### PR DESCRIPTION
**Pull request by vargaz**
…configure to enable them.

### CODE REVIEW

**Comment by vargaz** [comment]
We want to be explicit as to what we build, instead of building a bunch of stuff which has external dependencies so it won't even build without an android sdk, etc.

**Comment by luhenry** [comment]
The way it's integrated in the products is for the products to call `make -C sdks/builds {configure,build,package}-{android,ios-{...}`, and have it just work without any previous steps like `configure`. So how is this PR going to impact the integration with the products?

I agree it would be nice for us to have this `configure` command to enable only what you want so you don't need to pass environment variables for each `make `invocation, but that shouldn't conflict with products integration. A workaround I would propose is to have the following at https://github.com/mono/mono/pull/6054/files#diff-772aabcfba33ba70a3a510b16b75ce1fR5 :

```
ENABLE_BCL?=true
ENABLE_ANDROID?=true
ENABLE_IOS?=true
ENABLE_WASM?=true
```

Would that fit what you want to achieve?

**Comment by vargaz** [comment]
Shouldn't these be FALSE by default ?

**Comment by vargaz** [comment]
So what I would like to achieve is when I type make in builds/, it wouldn't start building stuff that I don't need, and it would not even compile without the proper sdks.

**Comment by luhenry** [comment]
@vargaz it has to allow us to build specific targets without having to go through extra steps. It doesn't matter much to me if these specific targets are build by default or not when you do `make -C sdks/builds package`, and that is a different discussion.

**Pull request closed without merging**
