### PR TITLE
Cast constants to (U)IntPtr in a single mov

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes: https://github.com/mono/mono/issues/16805

Test case:
```csharp
static unsafe IntPtr FromConst() => (IntPtr)42;
```
CoreCLR:
```asm
mov eax, 0x2a
ret
```

Mono-LLVM (Before):
```asm
mov    QWORD PTR [rsp-0x8],0x0
mov    QWORD PTR [rsp-0x8],0x2a
mov    rax,QWORD PTR [rsp-0x8]
ret 
```

Mono-LLVM (After):
```asm
mov eax, 0x2a
ret
```

It's mostly a hack (workaround) but according to Zoltan, a proper fix is quite complicated:

> the problem is that IntPtr is a valuetype.
> so even through the call is inlined, we still have to take the address of a local etc.
> which leads to worse code.
> since we don't have a pass to get rid of those things, or the pass is not good enough.
> i.e. here is how the code looks:
> IL_0003: ldloca.s V_0
> IL_0005: ldc.i4.4
> IL_0006: call native int [System.Runtime]System.IntPtr::op_Explicit(int32)
> since IntPtr is a valuetype, the 'this' argument is passed by ref.
> so the easy solution is to add an intrinsics.
> the more complicated one is to fix the 'alias-analyis' pass in the jit to get rid of the ldloca.

### CODE REVIEW

**Comment by filipnavara** [comment]
@marek-safar I believe the fix is simple enough that it's not worth writing an issue for that. The general case is already handled in the alias analysis and I submitted #16812 to fix this specific issue.

**Comment by marek-safar** [comment]
@filipnavara are you saying this fix is no longer needed after your fix?

**Comment by filipnavara** [comment]
@marek-safar Yes, assuming my fix is correct.

**Comment by EgorBo** [comment]
Closing in favor of https://github.com/mono/mono/pull/16812

**Pull request closed without merging**
