### PR TITLE
Use an init-tools script to install a local dotnet for wasm.

### PR DESCRIPTION
**Pull request by steveisok**

### CODE REVIEW

**Comment by steveisok** [comment]
@monojenkins build OS X WebAssembly

**Comment by MaximLipnin** [comment]
https://github.com/mono/mono/pull/16628 could be a workaround for `OS X WebAssembly` lane failure.

**Comment by steveisok** [comment]
I think the jenkins script needs adjusted for osx, but I don't know to what degree yet.

**Comment by steveisok** [comment]
@monojenkins build Linux WebAssembly

**Comment by lewing** [comment]
@monojenkins build OS X WebAssembly

**Pull request merged**
