### PR TITLE
Use the right FileSystemWatcher sources

### LINKED ISSUE #16486: FileSystemEventArgs.FullPath throws ArgumentNullException
## Steps to Reproduce

1. N/A, see https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972836?src=WorkItemMention&src-action=artifact_link

### Current Behavior

FileSystemEventArgs.FullPath throws ArgumentNullException:
```
ERROR [2019-08-14 00:15:27Z]: An unhandled exception has occurred. Terminating Visual Studio? False
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
  at System.IO.Path.Combine (System.String path1, System.String path2) [0x000a0] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/Path.cs:127 
  at System.IO.FileSystemEventArgs.get_FullPath () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/System/System.IO/FileSystemEventArgs.cs:66 
  at MonoDevelop.Projects.FileWatcherWrapper.OnFileDeleted (System.Object sender, System.IO.FileSystemEventArgs e) [0x00000] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs:283 
  at System.IO.FileSystemWatcher.RaiseEvent (System.Delegate ev, System.EventArgs arg, System.IO.FileSystemWatcher+EventType evtype) [0x00060] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/System/System.IO/FileSystemWatcher.cs:438 
  at System.IO.FileSystemWatcher.OnDeleted (System.IO.FileSystemEventArgs e) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/System/System.IO/FileSystemWatcher.cs:460 
  at System.IO.FileSystemWatcher+<>c__DisplayClass70_0.<DispatchEvents>b__1 () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/System/System.IO/FileSystemWatcher.cs:524 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
```

### Expected Behavior

No exception?

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Running on Mono 6.4.0.161 (2019-06/893099f23fd) (64-bit)

## Stacktrace

```
Please paste the stack trace here if available.
```

### PR DESCRIPTION
**Pull request by Therzok**
The corefx code for FileSystemEventArgs has some changes to support
constructing one with a null filename.

Fixes #16486

### CODE REVIEW

**Comment by Therzok** [comment]
We need this backported down to 2019-06 at least.

**Comment by Therzok** [comment]
@steveisok @alexischr

**Comment by Therzok** [comment]
@monojenkins commit csproj

**Comment by Therzok** [comment]
Based on https://dev.azure.com/devdiv/DevDiv/_workitems/edit/972836, 2019-02 is the target

**Comment by steveisok** [comment]
@monojenkins backport 2019-08

**Comment by steveisok** [comment]
@monojenkins backport 2019-06

**Comment by steveisok** [comment]
@monojenkins backport 2019-02

**Comment by Therzok** [comment]
@steveisok should I do a manual backport to 2019-02?

**Comment by akoeplinger** [comment]
@Therzok yes, please do

**Comment by Therzok** [comment]
https://github.com/mono/mono/pull/16560

**Pull request merged**
