### PR TITLE
Fix WS-Discovery and other protocols using duplex channels

### PR DESCRIPTION
**Pull request by ylatuya**
This fixes several issues for [1468](https://bugzilla.xamarin.com/show_bug.cgi?id=1468) and WS-Discovery finally works in mono

### CODE REVIEW

**Comment by akoeplinger** [comment]
build

**Comment by akoeplinger** [comment]
Could you please add a test for the fix?

**Comment by ylatuya** [comment]
Sure. I'll add some tests for the different bugs

**Comment by ylatuya** [comment]
Is it ok to add an integration test that starts a DiscoveryService and a DiscoveryClient? I can't find a way to test it otherwise, since UdpClient or the underlying sockets are not mockable for unit tests.

**Comment by akoeplinger** [comment]
@ylatuya yes that's fine. You can use `NetworkHelpers.FindFreePort ()` to find a free port for the service.

**Comment by ylatuya** [comment]
Fixed parsing of EndpointAdress in more reliable way and added unit tests and integration test for DiscoveryClient.

**Comment by migueldeicaza** [comment]
build

**Comment by ylatuya** [comment]
The test is passing fine in OS X, and it looks like it's also passing in one of the builds (Linux i386). I suspect the timeout might be a bit low, it's set to 1 second, but that should be enough.
Do you have any recommendation on what timeout to use in this kind of tests based on your experience with CI hardware/service?

**Comment by ylatuya** [comment]
Can you trigger a new build with the fix? I increased the FindCriteria from 1 to 5 seconds, which was probably causing the issue in some of slower ci builders.

**Comment by ylatuya** [comment]
ping

**Comment by huangjinshe** [comment]
Is the TCP support duplex channel ?  When the code will be merge in?

**Comment by huangjinshe** [comment]
Could you please also update System.ServiceModel.DuplexChannelFactory? Looks like that will be throw Not implement exception when use mobile platform.

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
Closing this because of a lack of activity and current conflicts.  Please reopen if you would like to move forward with this.

**Pull request closed without merging**
