### PR TITLE
[RFC] [DO NOT MERGE] Check macros

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@kumpera @lambdageek @ludovic-henry

**Comment by lambdageek** [comment]
I'm not a big fan of these:

1. Things like `return foo(..., CHECK)` will compile (with a warning) and do the wrong thing.  `if (...) foo(..., CHECK)` will compile without a warning. It would be nice if we could boobytrap them somehow.
2. The CHECK_SET_PENDING macros are ok, but they shouldn't be necessary. Ideally each icall has the same implementation:
    ```
    {
        DECL_ERROR;
        Whatever result = function_that_does_real_work (..., error);
        mono_error_set_pending_exception (error);
        return result;
    }
    ```
    (In the coop future they'll also have entry/exit macros for registers and handles etc, but otherwise they should all look basically like this.)

3. The `CHECK` macro (and I assume also a `CHECK_(val)` macro) are okay for runtime functions that don't need to do any error cleanup, but not for ones that have to work with unmanaged resources.  I would prefer if they expanded out to `if (!is_ok(error)) goto fail;`.  The current implementations are fine once we convert to C++ and hold all unmanaged resources through RAII.

**Comment by vargaz** [comment]
The macros do have some drawbacks, but they save a _lot_ of boilerplate code. If we had some static analysis infrastructure, we could add a check for the if/return problem. Moving the icall bodies into separate functions sounds like a good idea to solve the pending exception problem. The problem with the goto fail approach is:
- lots of function don't have any cleanup
- its not valid c++, since c++ doesn't allow a goto to cross some variable declarations.

**Comment by lambdageek** [comment]
I'm not sure about the relative prevalence of cleanup code - I've been seeing it a lot, but maybe that's just my bad luck.  If you think overall there's more functions that would benefit from a cleanup-less macro, let's go with that.

I still think the "if" case is particularly nasty and easy to miss. I'm not even sure a static analysis tool would help.  Code like `if (cond) foo(..., error); if (!is_ok(error)) return; (void)0;` is a perfectly reasonable thing to write - in a lot of cases (like if it's not the first use of error) everything is initialized and if (cond) is sufficiently complicated the static analysis won't figure out that the is_ok is always true or always false.

Well in any case I don't have better suggestions.

**Pull request closed without merging**
