### PR TITLE
Avoid passing /features:peverify-compat to csc, it generates very inefficient code in some cases.

### PR DESCRIPTION
**Pull request by vargaz**
See https://github.com/mono/mono/issues/18572#issuecomment-595924767.

Fixes https://github.com/mono/mono/issues/18572.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins backport 2020-02

**Comment by akoeplinger** [comment]
Looks good, I'm just curious about @marek-safar comment on https://xamarin.github.io/bugzilla-archives/59/59967/bug.html#c3

> This is hurting us on performace we need to run roslyn in legacy IL codegen for BCL builds

@marek-safar do you remember what this was about? It sounds like there was some performance problem back then?

**Comment by akoeplinger** [comment]
@monojenkins backport 2020-02

**Comment by vargaz** [comment]
Looks like multiple assemblies fail the verifier.

**Comment by marek-safar** [comment]
@akoeplinger I think the newer Roslyn generated different code for some value-type operations (don't recall exactly) which JIT couldn't optimize but I'd expect this to be fixed since.

**Comment by vargaz** [comment]
Generating verifiable code will always be slower in some cases so I think we should turn this off. Maybe turn off the verifier tests if they fail.

**Comment by CoffeeFlux** [comment]
Another case where I wish ILVerify was updated and trustworthy :(

**Comment by marek-safar** [comment]
I think we should change the compatibility mode for mscorlib only

**Comment by jaykrell** [comment]
Is there a good explanation of the options and what they do?
Is reasonably efficiency verifiable code possible?
Can/should verification be weakened somewhat?

**Comment by akoeplinger** [comment]
How hard would it be to change the verifier to recognize `Cannot take the address of a init-only field`?

**Comment by akoeplinger** [comment]
@monojenkins backport 2020-02

**Pull request merged**
