### PR TITLE
[System] Initial port of System.Net.Sockets types from referencesource

### PR DESCRIPTION
**Pull request by akoeplinger**
These are the more trivial ones.

### CODE REVIEW

**Comment by tritao** [comment]
lgtm

**Comment by marek-safar** [comment]
This requires mono_corlib_version bump

**Comment by kumpera** [comment]
To bump the corlib version.

Edit mono/metadata/appdomain.c and increment the MONO_CORLIB_VERSION define.
Edit mcs/class/corlib/System/Environment.cs and set the mono_corlib_version field to have the same value as above.

**Comment by akoeplinger** [comment]
Rebased and bumped the mono_corlib_version.

**Pull request merged**
