### PR TITLE
Fix OSX aot compilation when there's a space in a file path.

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Comment by kumpera** [comment]
@tritao can you review this one?

**Comment by tritao** [comment]
Looks good

**Comment by akoeplinger** [comment]
It seems this breaks AOT on the ARM builds on Jenkins:

```
make[7]: Entering directory `/media/ssd/jenkins/workspace/test-mono-mainline/label/debian-armhf/mcs/class/aot-compiler'
MONO_PATH='./../../class/lib/build/' > build_aot.log 2>&1 /media/ssd/jenkins/workspace/test-mono-mainline/label/debian-armhf/runtime/mono-wrapper --aot=bind-to-runtime-version --debug ./../../class/lib/build//mscorlib.dll || (cat build_aot.log; exit 1)
gcc: error: : No such file or directory
AOT of image ./../../class/lib/build//mscorlib.dll failed.
Mono Ahead of Time compiler - compiling assembly /media/ssd/jenkins/workspace/test-mono-mainline/label/debian-armhf/mcs/class/lib/build/mscorlib.dll
Code: 5117864(69%) Info: 126695(1%) Ex Info: 1734290(23%) Unwind Info: 15209(0%) Class Info: 99205(1%) PLT: 6603(0%) GOT Info: 119040(1%) Offsets: 110307(1%) GOT: 60992
Compiled: 24712/24714 (99%), No GOT slots: 15989 (64%), Direct calls: 39490 (71%)
Executing the native assembler: "as"   -o /tmp/mono_aot_jn6nfR.o /tmp/mono_aot_jn6nfR
Executing the native linker: gcc --shared -o "/media/ssd/jenkins/workspace/test-mono-mainline/label/debian-armhf/mcs/class/lib/build/mscorlib.dll.so.tmp" "" "/tmp/mono_aot_jn6nfR.o" 
make[7]: *** [../../class/lib/build//mscorlib.dll.so] Error 1

```

**Comment by vargaz** [comment]
Should be fixed 06df64e8663c09fc53736f5f4c928c39096b0218.

**Pull request merged**
