### PR TITLE
[bcl] Add a finalizer to MemoryMappedFile.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by marek-safar** [comment]
Sadly, this breaks .net compatibility

**Comment by Therzok** [comment]
@marek-safar refsource handles this the same way

**Comment by marek-safar** [comment]
@Therzok where did you find that?

**Comment by Therzok** [comment]
In ReferenceSource, MemoryMappedFile contains a SafeMemoryMappedFileHandle which handles finalization correctly, as opposed to an opaque IntPtr which does not get handled. Even though MemoryMappedFile does not get finalized, the safe file handle does.

**Pull request merged**
