### PR TITLE
[wasm] Remove all use of ContainsKey from js bindings

### PR DESCRIPTION
**Pull request by lewing**
A few places in in the JS Bindings were using Dictionary.ContainsKey then immediately looking up the object, use TryGetValue instead.

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
Hey guys

Can we hold off merging this until it is tested.  There were some problems a while back with replacing the ContainsKey with TryGetValue that was causing the object to be held onto with the Dictionary.

**Comment by lewing** [comment]
Sure, this isn't urgent.  Do you remember where you were seeing the problem?

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build

**Comment by kjpou1** [comment]
> Sure, this isn't urgent. Do you remember where you were seeing the problem?

@lewing yes but I noticed after looking at the PR that non of the xxxFree methods were changed.  I went ahead and tested this anyway within the open TypedArray PR as well.  

It is approved.  👍

**Pull request merged**
