### PR TITLE
[threadpool] Remove Mono Threadpool

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Please remove `tpool-poll.c tpool-epoll.c tpool-kqueue.c` from EXTRA_DIST in metadata/Makfile.am as well, or it'll break make dist again (I added the new files in https://github.com/mono/mono/commit/884675574a3a795b8c0c1e9eaa072a2d48751631).

**Comment by directhex** [comment]
Hi

Jenkins can't build this, because it uses a submodule reference which doesn't exist (https://github.com/mono/referencesource/tree/0501dddc0b2195e4fa4d302df484b2a7e010f85f)

This is unfortunately a problem for any pull request with external dependencies - if those dependencies aren't in the repo yet (e.g. they are PRs or local forks) then Jenkins fails to resolve them.

**Comment by vargaz** [comment]
I think we should commit this to master, we have to clean up any instability before a new release.

**Comment by kumpera** [comment]
Let's do it then.

**Comment by ludovic-henry** [comment]
I will rebase and commit to master then. Thank you!!

**Pull request closed without merging**
