### PR TITLE
[NS2.1] IntPtr, UIntPtr, Encoding, Enum, Random, Thread, System.Net primitives

### PR DESCRIPTION
**Pull request by EgorBo**
Contributes to https://github.com/mono/mono/issues/11430
`Enum` and `Encoding` methods were copied from dotnet/coreclr.

### CODE REVIEW

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
This will need a merge/rebase due to corefx submodule changes.

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Pull request merged**
