### PR TITLE
[runtime] Rename more MonoX->RuntimeX classes.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build deb with monolite

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins commit csproj

**Comment by vargaz** [comment]
@monojenkins commit csproj

**Comment by vargaz** [comment]
@monojenkins commit apidiff and csproj

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins commit csproj

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
