### PR TITLE
Improve error handling on vtable setup code paths.

### PR DESCRIPTION
**Pull request by tritao**

### CODE REVIEW

**Comment by tritao** [comment]
build

**Comment by vargaz** [comment]
Perhaps we should add a function which prints out the error and aborts instead of
g_assert (mono_error_ok ()), since there is no way to know from that assertion why it happened.

**Comment by kumpera** [comment]
@vargaz good point, it will be easier both identifying the issue and greping for places lacking error handling.

**Comment by tritao** [comment]
Good idea, another thing I'm thinking is adding support for error chaining. In some cases we return an inner error message in MonoError but set the class failure to something from the outer frame.. Especially if we also want to move most of these class failures to something like `MONO_EXCEPTION_MONO_ERROR` instead.

**Comment by migueldeicaza** [comment]
This patch deserves a better explanation/rationale of what it does before it goes in.

We will be using the commit message during archeology debugging, and the description so far is not sufficient.

**Comment by tritao** [comment]
Updated patch series with some fixes and better commit messages.

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Pull request closed without merging**
