### PR TITLE
When csc fails, for any reason, retry once with -parallel-.

### PR DESCRIPTION
**Pull request by jaykrell**
This might give us higher ARM CI success rates, and might be much slower.
This will double up actual errors for incorrect C# source.

### CODE REVIEW

**Comment by jaykrell** [comment]
ARM64 CI failure rate is quite high lately.

For example:

https://github.com/mono/mono/pull/9527/files

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64-fullaot/1871/parsed_console/log.html

https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter-aarch64/6259/parsed_console/log.html

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/11640/parsed_console/log.html

https://jenkins.mono-project.com/job/test-mono-pull-request-arm64-fullaot/1801/parsed_console/log.html

**Comment by jaykrell** [comment]
It *appears* to have retried.
It *appears* the failure is in cil-stringreplacer.exe, not csc.exe.
But I could certainly be wrong about anything.
The switches are a little confusing: -parallel or -parallel- or -parallel+? I used -parallel-.

**Comment by jaykrell** [comment]
This does not address the current severe problems, but might still be reasonable.
See also https://github.com/mono/mono/pull/9529.

**Comment by marek-safar** [comment]
I know it's a hack but perhaps we should just always run in -parallel- mode on ARM for now

@akoeplinger thoughts?

**Comment by jaykrell** [comment]
It is reportedly quite slow which is why I put it in only upon failure.

**Comment by jaykrell** [comment]
The gsharedvt comment is meant for elsewhere, an issue, will move later.

**Comment by jaykrell** [comment]
Thinking about this more, is the failure path in csc to reliably crash, or could it appear to succeed but generate different/incorrect code?

**Comment by akoeplinger** [comment]
@marek-safar I have no objection to running with parallel- always for ARM, but we should measure the time increase.

Are we confident the issue is fixed by `parallel-` ?

**Comment by lewurm** [comment]
I don't have any numbers handy, but running with `parallel-` is _significantly_ slower. I wouldn't recommend that.

**Comment by jaykrell** [comment]
The underlying bug is fixed for x86/amd64, but we still fail, because:
 1. ARM memory model.
 2. Using system mono.

**Comment by marek-safar** [comment]
I'm closing this one as this is not a real solution, we cannot say everyone including other teams to keep compiling until it works.

**Pull request closed without merging**
