### PR TITLE
[wasm] Fix typo in call_method length check

### PR DESCRIPTION
**Pull request by lewing**
Fix the typo in the name and then fix all the signatures that were too long.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
Larry I will fix these up.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
The signature logic appears to be quite broken closing this for now

**Pull request closed without merging**
