### PR TITLE
Fix mkbundle alignment to work with Windows. See https://github.com/mono/mono/issues/8225.

### PR DESCRIPTION
**Pull request by jaykrell**
Consider doing this only for Windows.

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Could we do this for Windows only for now?   On Linux the page alignment should work at the 4k boundary for all the current distributions - otherwise we would pay the 61k price (well, say 32k on average) for those

**Comment by jaykrell** [comment]
Yeah, based on the “runtime” variable? Does arm64 require 64k? I should try. I also think, we are just mapping them all readonly, no execute, could map them all at once and only align the first to 64k, the rest to 4k. So 32k on average total instead of per image.

**Comment by jaykrell** [comment]
Oh, it looks like we already map once? So how about just align the first to 64k and the rest to 4k.
32k new waste per bundle, not per embedded file? For all platforms?

**Comment by jaykrell** [comment]
Strings are over-aligned?
And no guaranteed terminal nul?

**Comment by jaykrell** [comment]
Is 30k per bundle (not per file) worth optimizing out?
Esp. when we align strings to 4k unnecessarily?

**Comment by migueldeicaza** [comment]
You are right, we only map the file once, and then pass this single mapped file to the rest of the runtime.

Let us get your patch.

**Comment by migueldeicaza** [comment]
The way to check if the target is Windows is to check that the embedded Mono runtime has the signature MZ at the beginning.

**Comment by migueldeicaza** [comment]
The "style" usage here is wrong.    The style indicates what is used on the host, what you want to do is do the right thing for the target OS.

So what you want to do is determine that the alignment is 64k when the runtime that is being bundled i is a Windows runtime, which you can check if the executable that you are packaging up starts with "MZ"

**Comment by jaykrell** [comment]
?

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Comment by migueldeicaza** [comment]
The new changes for runtime detection are fine

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Approve?

**Pull request merged**
