### PR TITLE
[jit] Fix an assertion in the Thread.VolatileRead () intrinsic.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/18418.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by ptupitsyn** [comment]
Hi, is this fix included in some release? I still get the error on `6.8.0.123`, should I try alpha/beta/nightly?

**Comment by akoeplinger** [comment]
It's included in the nightly builds: https://www.mono-project.com/download/nightly/#download-mac

**Comment by ptupitsyn** [comment]
@akoeplinger 

Tried on today's nightly on Ubuntu 20:

```
> mono --version
Mono JIT compiler version 6.10.0.105 (tarball Mon May 18 08:30:37 UTC 2020)
```

Still get this:
```
* Assertion at intrinsics.c:1039, condition `mini_type_is_reference (fsig->params [0])' not met
```

This happens during JVM calls in Apache Ignite project:
https://github.com/apache/ignite/tree/master/modules/platforms/dotnet

Let me know if a detailed reproducer is needed.

**Comment by akoeplinger** [comment]
As mentioned in https://github.com/mono/mono/issues/18418#issuecomment-630194385 the Linux nightly builds are broken at the moment.

**Pull request merged**
