### PR TITLE
[Wasm] Additional signatures for SkiaSharp interop

### PR DESCRIPTION
**Pull request by jeromelaban**
This change adds the set of signatures required for SkiaSharp to work untouched using the signatures already provided for the existing platform.

This change should not be required, as it is very specific to a library set. The m2n generator should allow for an external set of cookies, provided by the additional libraries linked by the packager. See https://github.com/mono/mono/issues/19670 for a more detailed issue on a possible solution.

/cc @mattleibow

---

Here's the list of enabled methods by this change:

```
VIIFFII :
System.Void SkiaSharp.SkiaApi::sk_canvas_draw_arc(System.IntPtr,SkiaSharp.SKRect*,System.Single,System.Single,System.Boolean,System.IntPtr)
VIFFFI :
System.Void SkiaSharp.SkiaApi::sk_canvas_draw_circle(System.IntPtr,System.Single,System.Single,System.Single,System.IntPtr)
VIFFFFI :
System.Void SkiaSharp.SkiaApi::sk_canvas_draw_line(System.IntPtr,System.Single,System.Single,System.Single,System.Single,System.IntPtr)
VIFFI :
System.Void SkiaSharp.SkiaApi::sk_canvas_draw_point(System.IntPtr,System.Single,System.Single,System.IntPtr)
VIFI :
System.Void SkiaSharp.SkiaApi::sk_codec_get_scaled_dimensions(System.IntPtr,System.Single,SkiaSharp.SKSizeI*)
IIIIIFII :
System.IntPtr SkiaSharp.SkiaApi::sk_font_break_text(System.IntPtr,System.Void*,System.IntPtr,SkiaSharp.SKTextEncoding,System.Single,System.Single*,System.IntPtr)
FII :
System.Single SkiaSharp.SkiaApi::sk_font_get_metrics(System.IntPtr,SkiaSharp.SKFontMetrics*)
VIIIIF :
System.Void SkiaSharp.SkiaApi::sk_font_get_xpos(System.IntPtr,System.UInt16*,System.Int32,System.Single*,System.Single)
FIIIIII :
System.Single SkiaSharp.SkiaApi::sk_font_measure_text(System.IntPtr,System.Void*,System.IntPtr,SkiaSharp.SKTextEncoding,SkiaSharp.SKRect*,System.IntPtr)
VIIIFFII :
System.Void SkiaSharp.SkiaApi::sk_text_utils_get_path(System.Void*,System.IntPtr,SkiaSharp.SKTextEncoding,System.Single,System.Single,System.IntPtr,System.IntPtr)
IFFFFIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_arithmetic(System.Single,System.Single,System.Single,System.Single,System.Boolean,System.IntPtr,System.IntPtr,System.IntPtr)
IIIFFII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_distant_lit_diffuse(SkiaSharp.SKPoint3*,System.UInt32,System.Single,System.Single,System.IntPtr,System.IntPtr)
IIIFFFII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_distant_lit_specular(SkiaSharp.SKPoint3*,System.UInt32,System.Single,System.Single,System.Single,System.IntPtr,System.IntPtr)
IFFFFIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_drop_shadow(System.Single,System.Single,System.Single,System.Single,System.UInt32,SkiaSharp.SKDropShadowImageFilterShadowMode,System.IntPtr,System.IntPtr)
IIIFFIIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_matrix_convolution(SkiaSharp.SKSizeI*,System.Single*,System.Single,System.Single,SkiaSharp.SKPointI*,SkiaSharp.SKMatrixConvolutionTileMode,System.Boolean,System.IntPtr,System.IntPtr)
IIIFFII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_point_lit_diffuse(SkiaSharp.SKPoint3*,System.UInt32,System.Single,System.Single,System.IntPtr,System.IntPtr)
IIIFFFII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_point_lit_specular(SkiaSharp.SKPoint3*,System.UInt32,System.Single,System.Single,System.Single,System.IntPtr,System.IntPtr)
IIIFFIFFII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_spot_lit_diffuse(SkiaSharp.SKPoint3*,SkiaSharp.SKPoint3*,System.Single,System.Single,System.UInt32,System.Single,System.Single,System.IntPtr,System.IntPtr)
IIIFFIFFFII :
System.IntPtr SkiaSharp.SkiaApi::sk_imagefilter_new_spot_lit_specular(SkiaSharp.SKPoint3*,SkiaSharp.SKPoint3*,System.Single,System.Single,System.UInt32,System.Single,System.Single,System.Single,System.IntPtr,System.IntPtr)
FIFFF :
System.Single SkiaSharp.SkiaApi::sk_3dview_dot_with_normal(System.IntPtr,System.Single,System.Single,System.Single)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_3dview_translate(System.IntPtr,System.Single,System.Single,System.Single)
VIFFI :
System.Void SkiaSharp.SkiaApi::sk_matrix_map_vector(SkiaSharp.SKMatrix*,System.Single,System.Single,SkiaSharp.SKPoint*)
VIFFI :
System.Void SkiaSharp.SkiaApi::sk_matrix_map_xy(SkiaSharp.SKMatrix*,System.Single,System.Single,SkiaSharp.SKPoint*)
FIII :
System.Single SkiaSharp.SkiaApi::sk_matrix44_get(System.IntPtr,System.Int32,System.Int32)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_post_scale(System.IntPtr,System.Single,System.Single,System.Single)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_post_translate(System.IntPtr,System.Single,System.Single,System.Single)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_pre_scale(System.IntPtr,System.Single,System.Single,System.Single)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_pre_translate(System.IntPtr,System.Single,System.Single,System.Single)
VIIIF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_set(System.IntPtr,System.Int32,System.Int32,System.Single)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_set_scale(System.IntPtr,System.Single,System.Single,System.Single)
VIFFF :
System.Void SkiaSharp.SkiaApi::sk_matrix44_set_translate(System.IntPtr,System.Single,System.Single,System.Single)
IIIIIF :
System.Boolean SkiaSharp.SkiaApi::sk_paint_get_fill_path(System.IntPtr,System.IntPtr,System.IntPtr,SkiaSharp.SKRect*,System.Single)
VIIFF :
System.Void SkiaSharp.SkiaApi::sk_path_add_arc(System.IntPtr,SkiaSharp.SKRect*,System.Single,System.Single)
VIFFFI :
System.Void SkiaSharp.SkiaApi::sk_path_add_circle(System.IntPtr,System.Single,System.Single,System.Single,SkiaSharp.SKPathDirection)
VIFFFIIFF :
System.Void SkiaSharp.SkiaApi::sk_path_arc_to(System.IntPtr,System.Single,System.Single,System.Single,SkiaSharp.SKPathArcSize,SkiaSharp.SKPathDirection,System.Single,System.Single)
VIFFFIIFF :
System.Void SkiaSharp.SkiaApi::sk_path_rarc_to(System.IntPtr,System.Single,System.Single,System.Single,SkiaSharp.SKPathArcSize,SkiaSharp.SKPathDirection,System.Single,System.Single)
IFI :
System.IntPtr SkiaSharp.SkiaApi::sk_path_effect_create_2d_line(System.Single,SkiaSharp.SKMatrix*)
IFFI :
System.IntPtr SkiaSharp.SkiaApi::sk_path_effect_create_discrete(System.Single,System.Single,System.UInt32)
IFFI :
System.IntPtr SkiaSharp.SkiaApi::sk_path_effect_create_trim(System.Single,System.Single,SkiaSharp.SKTrimPathEffectMode)
VIIFFFF :
System.Void SkiaSharp.SkiaApi::sk_rrect_set_nine_patch(System.IntPtr,SkiaSharp.SKRect*,System.Single,System.Single,System.Single,System.Single)
VIIFF :
System.Void SkiaSharp.SkiaApi::sk_rrect_set_rect_xy(System.IntPtr,SkiaSharp.SKRect*,System.Single,System.Single)
IFIII :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_lerp(System.Single,System.IntPtr,System.IntPtr,SkiaSharp.SKMatrix*)
IFFIFI :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_perlin_noise_fractal_noise(System.Single,System.Single,System.Int32,System.Single,SkiaSharp.SKSizeI*)
IFFIF :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_perlin_noise_improved_noise(System.Single,System.Single,System.Int32,System.Single)
IFFIFI :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_perlin_noise_turbulence(System.Single,System.Single,System.Int32,System.Single,SkiaSharp.SKSizeI*)
IIFIIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_radial_gradient(SkiaSharp.SKPoint*,System.Single,System.UInt32*,System.Single*,System.Int32,SkiaSharp.SKShaderTileMode,SkiaSharp.SKMatrix*)
IIFIIIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_radial_gradient_color4f(SkiaSharp.SKPoint*,System.Single,SkiaSharp.SKColorF*,System.IntPtr,System.Single*,System.Int32,SkiaSharp.SKShaderTileMode,SkiaSharp.SKMatrix*)
IIIIIIFFI :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_sweep_gradient(SkiaSharp.SKPoint*,System.UInt32*,System.Single*,System.Int32,SkiaSharp.SKShaderTileMode,System.Single,System.Single,SkiaSharp.SKMatrix*)
IIIIIIIFFI :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_sweep_gradient_color4f(SkiaSharp.SKPoint*,SkiaSharp.SKColorF*,System.IntPtr,System.Single*,System.Int32,SkiaSharp.SKShaderTileMode,System.Single,System.Single,SkiaSharp.SKMatrix*)
IIFIFIIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_two_point_conical_gradient(SkiaSharp.SKPoint*,System.Single,SkiaSharp.SKPoint*,System.Single,System.UInt32*,System.Single*,System.Int32,SkiaSharp.SKShaderTileMode,SkiaSharp.SKMatrix*)
IIFIFIIIIII :
System.IntPtr SkiaSharp.SkiaApi::sk_shader_new_two_point_conical_gradient_color4f(SkiaSharp.SKPoint*,System.Single,SkiaSharp.SKPoint*,System.Single,SkiaSharp.SKColorF*,System.IntPtr,System.Single*,System.Int32,SkiaSharp.SKShaderTileMode,SkiaSharp.SKMatrix*)
VIIIFFII :
System.Void SkiaSharp.SkiaApi::sk_textblob_builder_alloc_run(System.IntPtr,System.IntPtr,System.Int32,System.Single,System.Single,SkiaSharp.SKRect*,SkiaSharp.SKRunBufferInternal*)
VIIIFII :
System.Void SkiaSharp.SkiaApi::sk_textblob_builder_alloc_run_pos_h(System.IntPtr,System.IntPtr,System.Int32,System.Single,SkiaSharp.SKRect*,SkiaSharp.SKRunBufferInternal*)
VIIIFFIII :
System.Void SkiaSharp.SkiaApi::sk_textblob_builder_alloc_run_text(System.IntPtr,System.IntPtr,System.Int32,System.Single,System.Single,System.Int32,SkiaSharp.SKRect*,SkiaSharp.SKRunBufferInternal*)
VIIIFIII :
System.Void SkiaSharp.SkiaApi::sk_textblob_builder_alloc_run_text_pos_h(System.IntPtr,System.IntPtr,System.Int32,System.Single,System.Int32,SkiaSharp.SKRect*,SkiaSharp.SKRunBufferInternal*)
```

### CODE REVIEW

**Comment by jeromelaban** [comment]
I forgot to rerun the generator, will do that.

**Comment by mattleibow** [comment]
Is there a tool that can be run to detect any apis that are missing? Then I can run it or something as part of CI... Or even just to list them all and then I can keep an eye on it... Or are there some compiler errors that I can get. Or is this all a manual thing for now?

**Comment by jeromelaban** [comment]
I made that list through that tool: https://gist.github.com/jeromelaban/ac625399c6e79e7f9d40141f7bbf9b3a

**Comment by jeromelaban** [comment]
@monojenkins build Linux WebAssembly

**Comment by jeromelaban** [comment]
@monojenkins build Linux WebAssembly

**Comment by mattleibow** [comment]
Oooh, fancy 😄 

Does adding these signature to mono somehow make binaries larger or something?
Also, is this a temporary way to do things, or due to restrictions in the WASM world we will always have to do this?

**Comment by vargaz** [comment]
We will add some tooling to automate this hopefully in the future.

**Comment by jeromelaban** [comment]
@monojenkins build Linux WebAssembly

**Comment by jeromelaban** [comment]
@monojenkins build Linux ARMv7

**Comment by jeromelaban** [comment]
It this error is expected ?

```
20:23:33 umount: /mnt/jenkins/buildplace/35204//mnt/jenkins/workspace/test-mono-pull-request-wasm: target is busy
```

I seem to get this on every build, but I'm not sure if it's related to what I've added.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by jeromelaban** [comment]
@monojenkins build Linux WebAssembly

**Comment by jeromelaban** [comment]
Got it finally ;)

**Comment by jeromelaban** [comment]
@monojenkins build Linux WebAssembly

**Comment by jeromelaban** [comment]
@monojenkins build Linux WebAssembly

**Comment by jeromelaban** [comment]
The wasm build is failing every time, most likely in tests, though it's not clear. I'm starting to wonder if adding the new signatures is the revealing factor of https://github.com/mono/mono/issues/19684.

**Pull request merged**
