### PR TITLE
[cecil] Bump external/cecil to the current head

### PR DESCRIPTION
**Pull request by spouliot**
xamarin-macios/cycle9 needs this to fix #51336 [1] and handle broken
.mdb [2]

[1] https://bugzilla.xamarin.com/show_bug.cgi?id=51336
[2] https://github.com/mono/cecil/commit/045b0f9729905dd456d46e33436a2dadc9e2a52d

### CODE REVIEW

**Comment by spouliot** [comment]
@marek-safar @akoeplinger afaict the above failures don't seems related to the cecil bump

**Comment by akoeplinger** [comment]
Yes, the failures seem unrelated.

**Comment by marek-safar** [comment]
@spouliot the failure is related, Cecil broke its API badly and all our Cecil based tools will break due to that. We fixed that in master but not sure I want to do that in C9. I'll create C9 branch of Cecil which we should bump to instead

**Comment by akoeplinger** [comment]
@marek-safar the build is green on 6 architectures and the OSX/Windows failures were due to the lldb plugin which was already fixed. Did you have something else in mind?

I took a look at the diff https://github.com/mono/cecil/compare/3f37ebd52b49e1a9ab3bfbc5881b6da01c134c0d...853320a1c5afe5f8bec3e5a2fd398e01545b7f5a#files_bucket before I merged and the only API change was the `Resolve (string, ReaderParameters)` removal which was fixed by https://github.com/mono/mono/pull/4223/commits/5412bf83f439a8ab0c9f79fc8ef4e835178e2d93. I think we already were on a Cecil version that had the major breaking changes in C9 before.

**Comment by marek-safar** [comment]
The build was green for Mono because we don't use Cecil that much as XI/XA and they will break. This PR should not be merged. I made another PR https://github.com/mono/mono/pull/4236 to undo the breaking change

**Comment by akoeplinger** [comment]
I checked XA and they had already migrated to the new Cecil in C9, but yeah, better to keep that. Sorry about it, just wanted to unblock Sebastien.

**Pull request merged**
