### PR TITLE
debugging-in-ci failing FullAOT LLVM Linux x64 tests.

### PR DESCRIPTION
**Pull request by jaykrell**
https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-fullaot+llvm/1044/parsed_console/

```
1) Create_Path_ReadOnly (MonoTests.System.IO.FileTest.Create_Path_ReadOnly)
   #1
  at MonoTests.System.IO.FileTest.Create_Path_ReadOnly () [0x0002a] in /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/corlib/Test/System.IO/FileTest.cs:157
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <4cda3d6a7b3d4fa5846f5a85e72fdf5c>:0

2) GetAttributes_ReadOnly (MonoTests.System.IO.FileTest.GetAttributes_ReadOnly)
     #2
  Expected: True
  But was:  False

  at MonoTests.System.IO.FileTest.GetAttributes_ReadOnly () <0x7f16d645e430 + 0x0006a> in <03c8f97dce4c42a0a554d2906ce1a501#125f9c7c5525eb77d5b7327ee595defc>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <4cda3d6a7b3d4fa5846f5a85e72fdf5c>:0
```

### CODE REVIEW

**Comment by jaykrell** [comment]
This didn't fix the problem. I suggest this is still an ok change, i.e. so the tests can run in parallel.
Maybe use guids, for each test, or the temp directory, as well.

The tests succeed locally run individually in a standalone form so I'm going to add Console.WriteLine.
Also maybe look at the codegen, but these seem kinda wierd -- the tests are pretty simple.
They do depend on exceptions, but at least one seems to fail by not raising.

Anyway I'll dig  more.

**Comment by vargaz** [comment]
tmpFolder is recreated in the SetUp () function which is ran before each test.

**Comment by jaykrell** [comment]
No multi-threaded test execution?

**Comment by vargaz** [comment]
Not with our current test runner.

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by jaykrell** [comment]
Ok, so, running maybe not the same Linux (Ubuntu18.04) and maybe therefore not the same compiler either (gcc 7.3), and building LLVM myself, and using CI_TAGS=linux-amd64,retry-flaky-tests,fullaot_llvm,pull-request ./scripts/ci/run-jenkins.sh  This does not repro.

I can try to match up more factors, or debug on the CI machine.

Or other things, like, extract the failing tests into a smaller test and run objdump -D on them. But debugging on CI I think is the next step. (Or maybe objdump of specific functions).

**Comment by jaykrell** [comment]
Next steps:
1. Try the llvm .deb
2. Try Ubuntu 14.04.

**Comment by akoeplinger** [comment]
> Actually it looks like CI does layer in some parallelism from above. [...]

No, that's not parallelism. What you're seeing are the five retries that we do for failing tests on PRs to make sure they're really failures and not just flaky tests.

**Comment by jaykrell** [comment]
(That's what I also guessed.)

**Comment by jaykrell** [comment]
This is pretty elusive.

no repro with make -C mcs/class/corlib run-test on builder.

Next is CI_TAGS=linux-amd64,retry-flaky-tests,fullaot_llvm,pull-request ./scripts/ci/run-jenkins.sh on builder. If that doesn't repro, despite all signs, I think will try a guid for the file path.
I expect that will still fail.

Then I'll try tweaking/adding test, and maybe objdump -D in situ, or printfs/system(ls -l) -- i.e. where we open/stat whatever... which will be needed anyway if the only repro is a full run-jenkins.sh. ugh.

But it isn't flaky. CI faiilure rate is 100%. non-CI failure rate is 0.

**Comment by jaykrell** [comment]
This understood now. LLVM CI runs as root and running as root behaves differently. It is nothing to do with LLVM.

**Comment by jaykrell** [comment]
https://github.com/mono/mono/issues/8903

**Pull request closed without merging**
