### PR TITLE
Fix race condition in XmlCharType.Instance

### PR DESCRIPTION
**Pull request by ww898**
Fix race condition in `XmlCharType.Instance` because:
```
if ( s_CharProperties == null ) {
    InitInstance();
}
```

### CODE REVIEW

**Comment by EgorBo** [comment]
Probably it makes sense to just replace the ref-source implementation with corefx:
https://github.com/mono/mono/blob/master/mcs/class/System.XML/common.sources#L371
to be
`../../../external/corefx/src/System.Private.Xml/src/System/Xml/XmlCharType.cs`

if it doesn't have this issue of course (from the quick glance - it doesn't).

**Comment by ww898** [comment]
We got `XmlReader` failures with probability 2% in our case. It's too big for use because more then 1000 builds broken in our ecosystem. After apply this fix in our mono branch no failures any more. Could you please approve the fix before switching to corefx version? It's very important for us.

This condition doesn't work properly for us: https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlTextReaderImpl.cs#L3443

**Comment by marek-safar** [comment]
build

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Pull request merged**
