### PR TITLE
[runtime] Fix #25679: memleak in get_gsharedvt_type()

### PR DESCRIPTION
**Pull request by maksqwe**
This change is released under the MIT license.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by tritao** [comment]
approve

**Comment by tritao** [comment]
Runtime contributions need to be explicitly MIT-licensed. Please add such a notice to this thread.

**Comment by maksqwe** [comment]
Done

**Pull request closed without merging**
