### PR TITLE
Embedded API. Fix method signature match failure for generic types wi…

### PR DESCRIPTION
**Pull request by Thesaurus**
…th multiple type parameters.

Resubmitting https://github.com/mono/mono/pull/2724/files

### CODE REVIEW

**Comment by akoeplinger** [comment]
approve

**Comment by kumpera** [comment]
LGTM

**Comment by knocte** [comment]
Use tabs, not spaces.

**Comment by Thesaurus** [comment]
Do want me to issue another PR?
What is the guide tab setting for C?

**Comment by kumpera** [comment]
We use tabs, not spaces.

**Comment by akoeplinger** [comment]
You don't need to open another PR, just amend your commit and force-push to the branch on your fork (that's why it's usually a good idea not to work in the `master` branch), GitHub will automatically update the PR.

**Comment by Thesaurus** [comment]
Is that failure anything to be concerned about? Don't look related to the PR.

**Comment by akoeplinger** [comment]
@Thesaurus no, you can ignore that. Could you please squash your change down to one commit (e.g. like described in this [blog post](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit))? If you run into troubles, let me know and I can do it.

**Comment by Thesaurus** [comment]
My initial attempt at this failed (doing this on Master was a bad idea). I can probably find time to have another go towards the end of the week but if you want to squash it yourself now thats fine.

**Comment by akoeplinger** [comment]
I squashed and pushed this in with https://github.com/mono/mono/commit/1e843e0607e11ee0865df9460111d4959d0e0ccc. Thanks!

**Pull request closed without merging**
