### PR TITLE
[sgen] Set up a critical region in the managed write barriers.

### PR DESCRIPTION
**Pull request by alexrp**
We consider the managed write barriers to be critical methods just like the managed allocators (`sgen_is_critical_method`) so it seems to me that we should be setting up a critical region in the write barriers for all the same reasons we do it in the managed allocators.

### CODE REVIEW

**Comment by alexrp** [comment]
cc @BrzVlad @kumpera

**Comment by BrzVlad** [comment]
So a write barrier store looks something like this : 
> *ptr = value
> wbarrier (native or call to managed)
> dummy_use value

Given we always extend the liveness of value until after the wbarrier has been executed, it shouldn't really matter if we interrupt in the write barrier method or not since value will be pinned anyways.

Wbarrier methods were made critical as of https://github.com/mono/mono/commit/efecad9153feade6a7726a1f43fe3c960bdc7ca7. It seems that back in those days we weren't extending the liveness of value so my guess is that this was the justification behind the commit. Which we no longer need today.

@schani Could you confirm the above ?

**Comment by vargaz** [comment]
These methods are very performance critical, putting atomic instructions/tls inside them slows them down way too much.

**Comment by alexrp** [comment]
I'm all for not setting up a critical region here if we can avoid it. I just care about correctness.

FWIW, the native write barrier functions rely on the conservative stack scan to pin the object. So you might be right that we can rely on the `OP_DUMMY_USE` to achieve the same. Mark added the dummy use in 56f09ea7d730ca37c59493624681fec0763e6e0b.

**Comment by kumpera** [comment]
We don't need crit regions on wb due to OP_DUMMY_USE?

**Comment by alexrp** [comment]
@kumpera @BrzVlad in that case, we should at least adjust `sgen_is_critical_method` to not consider the write barriers critical methods anymore, right? Not a correctness issue then, but more a performance one.

**Comment by BrzVlad** [comment]
@alexrp Yes, we should

**Pull request closed without merging**
