### PR TITLE
Add libusb-1.0 mapping

### PR DESCRIPTION
**Pull request by zboszor**
This fixes using USB devices with LibUsbDotNet and MonoLibUsb.

### CODE REVIEW

**Comment by zboszor** [comment]
@dotnet-policy-service agree

**Comment by madewokherd** [comment]
Hi, Mono development has moved to https://gitlab.winehq.org/mono/mono (see https://github.com/mono/mono/issues/21796)

**Comment by madewokherd** [comment]
Since the assembly using this library isn't built into Mono, I think it should be fixed there instead. You can put the dllmap in a .dll.config file (which is not a thing in .NET Framework but it is in Mono for precisely this scenario). See https://www.mono-project.com/docs/advanced/pinvoke/ for more information.

**Comment by akoeplinger** [comment]
Closing this PR based on the discussion above.

**Pull request closed without merging**
