### PR TITLE
[SocketResponder] Use Task instead of Thread + Use explicit delegate so it appears in stacktraces

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@alexrp could please review this PR? Thank you!

**Comment by alexrp** [comment]
There are some compilation failures in the `System.Web.Services` tests: https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/1737/parsed_console/log_content.html#WARNING2

But these are trivial to fix in the same way as the commits already do for the other tests. So other than those, LGTM.

**Comment by ludovic-henry** [comment]
build

**Comment by ludovic-henry** [comment]
@monojenkins merge

**Pull request merged**
