### PR TITLE
[fsharp] Try to build with F# 4.7

### LINKED ISSUE #16763: Bump F# to 4.7
Please update the F# compiler bundled to Mono distribution.

It's probably finally the time to have it updated after the 4.5 update celebration time. https://github.com/mono/mono/pull/10919#issuecomment-481821788 :)

### PR DESCRIPTION
**Pull request by chkn**
Fixes #16763

### CODE REVIEW

**Comment by chkn** [comment]
@monojenkins build pkg

**Comment by chkn** [comment]
@monojenkins build pkg

**Comment by chkn** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@chkn Looks like `patches/fsharp-GetFileNameWithoutExtension-type-inference.patch` is failing to apply

**Comment by chkn** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@chkn patches/fsharp-msbuild-16-0.patch failed too 😫 

`patches/fsharp-portable-pdb.patch` is required and I believe `patches/fsharp-custom-prefix.patch` is still required. Although thinking about it, we could just apply these to the `mono/fsharp` repo seeing as we own that?

**Comment by chkn** [comment]
@monojenkins build pkg

**Comment by chkn** [comment]
@nosami Good idea! Let's see if we can get this built properly first, and then we can look at cleaning things up

**Comment by chkn** [comment]
On second thought, `fsharp-custom-prefix.patch` failed too.. if it’s still needed, it might be easier to fix directly in `mono/fsharp` as you suggest

**Comment by nosami** [comment]
Looks like [mono/config.make](https://github.com/mono/fsharp/blob/master/mono/config.make) has diverged too much since the patch was created.

[fsharp-msbuild-16-0.patch](https://github.com/mono/mono/blob/master/packaging/MacSDK/patches/fsharp-msbuild-16-0.patch) still looks to be needed too.. it's probably easiest to make the changes directly into the repo.

**Comment by vshapenko** [comment]
Any update on this issue?

**Comment by nosami** [comment]
@vshapenko I'm taking another look at it now

**Comment by vshapenko** [comment]
I will explain, why i am worrying much about this. I am developing a mobile app using Fabulous. Current version of Fabulous requires FSharp version >= 4.6.2, which looks ok. So, using f# 4.7, currently i cannot build for ios using mac, only by scenario of pairing mac to visual studio.
And i understand, that with release of .net 5 this problem will fly away. If someone could guide where to dig to solve this problem, it would be amazing. As far as i understand, problem is into cmake+python build scripts for mono.

**Comment by KirillOsenkov** [comment]
@marek-safar apologies for bringing so many issues to you, but we have this one which is very impactful for VSMac. A lot of VSMac users want to use the latest F# compiler features, but they can't because Mono is using an old compiler. Would it be possible to pick up this PR and update the F# compiler to latest in Mono?

Related community feedback:
https://developercommunity2.visualstudio.com/t/F-47-support/924698
https://developercommunity2.visualstudio.com/t/No-support-for-FSharpCore-47/1192676

**Comment by marek-safar** [comment]
@steveisok could you get this completed and land it to 2020-02?

**Comment by steveisok** [comment]
Seems the most up to date PR for this is https://github.com/mono/mono/pull/17925

I'll need to ping @nosami there and see what's left.  At first glance, it seems there are some packaging problems.

**Pull request closed without merging**
