### PR TITLE
[System.Xml] Fix deserialization issue

### PR DESCRIPTION
**Pull request by MaximLipnin**
[This ](https://github.com/mono/mono/pull/11194/files#diff-ae54d9565e735005686191de0f19ed50R431-R435)change in `XmlTypeMapElementInfo.GetElement`  introduced the logic for handling the case of derived types deserialization. 
For some cases (like https://github.com/mono/mono/issues/16918) it breaks existing functionality because it returns wrong element for given element name after searching withing derived types collection.

image

Unfortunately, what I can do here is just reverting the related changes.

Fixes https://github.com/mono/mono/issues/16918

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
Possibly https://github.com/mono/mono/issues/16473 is related

**Comment by akoeplinger** [comment]
@majellin24 FYI we unfortunately had to revert your pull request https://github.com/mono/mono/pull/11194 as it caused a regression.

**Comment by marek-safar** [comment]
@monojenkins backport 2019-08

**Pull request merged**
