### PR TITLE
[2018-02] [runtime] Make sigterm dumper send file to merp

### PR DESCRIPTION
**Pull request by alexanderkyte**
backport of https://github.com/mono/mono/pull/9607

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins skip

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
As all of these changes that will change control flow and symbol visibility live behind an``` #ifdef TARGET_OSX``` , and because this is a backport to an old branch, I ask that people not focus on failures from lanes that are not on OSX.

**Comment by alexanderkyte** [comment]
https://xamjenkinsartifact.azureedge.net/build-package-osx-mono-pullrequest/pr/190/8db1598887bd67710e6082c6b6bc662b208548ee/MonoFramework-MDK-pr@8db1598887b-dirty-5.12.0.297.macos10.xamarin.universal.pkg

**Comment by lewurm** [comment]
is there a PR for `master` too?

**Comment by alexanderkyte** [comment]
Hmm, yeah I'll do this the right way so that the monojenkins bot can do all the paperwork

**Comment by alexanderkyte** [comment]
This was developed against 2018-02 because that's what VS4M needs packages for

**Pull request merged**
