### PR TITLE
[sdb] Disable an assert to avoid breaking debugging.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/8848.
Fixes https://github.com/mono/mono/issues/9262.
Fixes https://github.com/mono/mono/issues/8627.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins backport 2018-08

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build OS X x64

**Comment by vargaz** [comment]
@monojenkins build OS X x64

**Comment by luhenry** [comment]
@monojenkins backport to 2018-04

**Comment by luhenry** [comment]
@monojenkins backport to 2018-02

**Pull request merged**
