### PR TITLE
[profiler] Introduce runtime control API.

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by alexrp** [comment]
build profiler stress

**Comment by alexrp** [comment]
Failures look unrelated.

**Comment by luhenry** [comment]
Does that break backward compatibility? So could an older version of the Xamarin Profiler work with a newer version of Mono with this API?

**Comment by kumpera** [comment]
This is a new feature, so it won't work with older runtimes that don't support it.

**Comment by luhenry** [comment]
ok, but it won't break/remove features needed by previous runtime, right? It doesn't seem like it from the code, but I prefer to make sure :)

**Comment by kumpera** [comment]
LGTM

**Pull request merged**
