### PR TITLE
[wasm] Reenable the managed collation code, link it out by default, add a packager option to enable it.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by lewing** [comment]
When not linked out this will grow mscorlib by 340k but with the `--exclude-feature globalization` flag it should actually be smaller because things like calendar data will be removed.  Addresses https://github.com/mono/mono/issues/19034 by including the collation data.

**Comment by lewing** [comment]
cc @SteveSandersonMS

**Comment by vargaz** [comment]
Need this to be able to remove just the resources:
https://github.com/mono/linker/pull/1116

**Comment by SteveSandersonMS** [comment]
Thanks for pinging me @lewing :)

> When not linked out this will grow mscorlib by 340k but with the --exclude-feature globalization flag it should actually be smaller 

Not certain I follow exactly, but is it correct that there will be two possibilities after this change?

 1. `--exclude-feature globalization` => app gets a bit smaller, but loses some existing globalization functionality besides just `StringComparison.InvariantCultureIgnoreCase` (what functionality?)
 2. Without that flag => app gets 340KB bigger but gains `StringComparison.InvariantCultureIgnoreCase` support

If that's correct, then perhaps a third scenario is also required:

 3. Some new flag or absence of flags => app stays the same size and retains the same set of globalization features as before this PR

This is because we definitely wouldn't want to add 340 KB in the default case, nor would we want to lose any existing globalization functionality in the default case.

Does that sound reasonable? Or am I misunderstanding the situation (e.g., in case 1 no existing functionality is actually lost)?

**Comment by vargaz** [comment]
Working on a version which only disables the functionality which is disabled currently but using the linker instead of #ifdefs in the code.

**Comment by lewing** [comment]
current  1076173 mscorlib.dll.br
with collation tables 1192666 mscorlib.dll.br
so a difference of 116493 compressed

**Comment by lewing** [comment]
> Thanks for pinging me @lewing :)
> 
> > When not linked out this will grow mscorlib by 340k but with the --exclude-feature globalization flag it should actually be smaller
> 
> Not certain I follow exactly, but is it correct that there will be two choices after this change?
> 
> 1. With `--exclude-feature globalization` => app gets a bit smaller, but loses some existing globalization functionality besides just `StringComparison.InvariantCultureIgnoreCase` (what functionality?)

Calendars and DateTimeFormats
https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/RemoveFeaturesStep.cs#L100

> 2. Without that flag => app gets 340KB bigger but gains `StringComparison.InvariantCultureIgnoreCase` support
> 

Gains the full Globalization support of desktop mono

> If that's correct, then perhaps a third choice is also required:
> 
> 1. Some new flag or absence of flags => app stays the same size and retains the same set of globalization features as before this PR
> 

@vargaz is working on an alternative to enable removing resources in the linker

> This is because we definitely wouldn't want to add 340 KB in the default case, nor would we want to lose any existing globalization functionality in the default case, unless it's super-obscure functionality.
> 
> Does that sound reasonable? Or am I misunderstanding the situation (e.g., in case 1 no existing functionality is actually lost)?

**Comment by lewing** [comment]
So the bulk of the size increase comes from the collation tables that are currently stored as managed resources.  https://github.com/mono/linker/pull/1120 allows you to specify linking out the managed resource in the substitutions file.

**Comment by vargaz** [comment]
With the latest version, only the collation code is linked in/out.

**Comment by vargaz** [comment]
To backport, needs to backport
https://github.com/mono/mono/pull/19583
first.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins commit csproj

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by SteveSandersonMS** [comment]
@lewing We get the linker binaries from the Mono CI drops alongside the runtime. So if we update the runtime, we automatically update the linker as part of that. Not sure if that answers your question, so please ping me if not!

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Pull request merged**
