### PR TITLE
[LLVM] Change llvm submodule to dotnet-org fork of official LLVM git repo

### PR DESCRIPTION
**Pull request by directhex**
Previously, mono/llvm.git was forked from an unofficial mirror of LLVM from Subversion to GitHub. Now the LLVM project has unified on a GitHub monorepo, adjust accordingly.

### CODE REVIEW

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by lateralusX** [comment]
@directhex looks like the new repro has llvm sources one folder down compared to old and that is a change compared to the previous version, when we build we pass down root to repository that in the past was equal to the root of the repository. In build-external-llvm.bat we do a git submodule update --init using the passed inroot folder to sources, with the new repro that is llvm-project/llvm, but that will trigger an error since its not the git root of the repro and that will later mark exec as a failure. We would need to pass root of repository as source in _LLVMSourceDir and then in build-external-llvm.bat add /llvm to the path passed into cmake.

**Comment by lateralusX** [comment]
```
From b7220ad75f27bdd64c7756b8a7d81ef68fc5f360 Mon Sep 17 00:00:00 2001
From: lateralusX <lateralusx.github@gmail.com>
Date: Fri, 8 Nov 2019 09:39:07 +0100
Subject: [PATCH] Fix Windows LLVM build using new repository structure.

---
 msvc/build-external-btls.bat |  1 +
 msvc/build-external-llvm.bat | 10 +++++++++-
 msvc/mono.external.targets   |  2 +-
 3 files changed, 11 insertions(+), 2 deletions(-)

diff --git a/msvc/build-external-btls.bat b/msvc/build-external-btls.bat
index bd85f76ce39..650d8ab0090 100755
--- a/msvc/build-external-btls.bat
+++ b/msvc/build-external-btls.bat
@@ -235,6 +235,7 @@ if "%GIT%" == "" (
 )
 
 :: Make sure boringssl submodule is up to date.
+echo Updating submodule "%BTLS_DIR%"
 "%GIT%" submodule update --init -- "%BTLS_DIR%"
 if not ERRORLEVEL == 0 (
     "%GIT%" submodule init -- "%BTLS_DIR%"
diff --git a/msvc/build-external-llvm.bat b/msvc/build-external-llvm.bat
index 04cdd1c10de..4a7764f8045 100755
--- a/msvc/build-external-llvm.bat
+++ b/msvc/build-external-llvm.bat
@@ -239,6 +239,7 @@ if "%GIT%" == "" (
 )
 
 :: Make sure llvm submodule is up to date.
+echo Updating submodule "%LLVM_DIR%"
 "%GIT%" submodule update --init -- "%LLVM_DIR%"
 if not ERRORLEVEL == 0 (
     "%GIT%" submodule init -- "%LLVM_DIR%"
@@ -276,6 +277,13 @@ if not "%CMAKE_GENERATOR_ARCH%" == "" (
     set CMAKE_GENERATOR_ARCH=-A %CMAKE_GENERATOR_ARCH%
 )
 
+:: Check if LLVM_DIR is just repro root or if we should build
+:: a llvm subfolder within that repository.
+set "LLVM_SOURCE_DIR=%LLVM_DIR%"
+if exist "%LLVM_SOURCE_DIR%\llvm\CMakeLists.txt" (
+	set "LLVM_SOURCE_DIR=%LLVM_DIR%\llvm"
+)
+
 :: Run cmake.
 "%CMAKE%" ^
 -DCMAKE_INSTALL_PREFIX="%LLVM_INSTALL_DIR%" ^
@@ -293,7 +301,7 @@ if not "%CMAKE_GENERATOR_ARCH%" == "" (
 %CMAKE_GENERATOR_ARGS% ^
 -G "%CMAKE_GENERATOR%" ^
 %CMAKE_GENERATOR_ARCH% ^
-"%LLVM_DIR%"
+"%LLVM_SOURCE_DIR%"
 
 if not ERRORLEVEL == 0 (
     goto ON_ERROR
diff --git a/msvc/mono.external.targets b/msvc/mono.external.targets
index b47e4ac1998..919eed6de6b 100644
--- a/msvc/mono.external.targets
+++ b/msvc/mono.external.targets
@@ -112,7 +112,7 @@
 
     <PropertyGroup>
         <_LLVMSourceDir Condition="'$(_LLVMSourceDir)' == ''">$(MONO_INTERNAL_LLVM_SOURCE_DIR)</_LLVMSourceDir>
-        <_LLVMSourceDir Condition="'$(_LLVMSourceDir)' == ''">$(_MonoSourceDir)\external\llvm-project\llvm</_LLVMSourceDir>
+        <_LLVMSourceDir Condition="'$(_LLVMSourceDir)' == ''">$(_MonoSourceDir)\external\llvm-project</_LLVMSourceDir>
         <_LLVMBuildDir Condition="'$(_LLVMBuildDir)' == ''">$([System.IO.Path]::GetFullPath('$(MONO_BUILD_DIR_PREFIX)$(Platform)\obj\external\llvm-build\$(Configuration)'))</_LLVMBuildDir>
         <_LLVMInstallDir Condition="'$(_LLVMInstallDir)' == ''">$(_LLVMBuildDir)\install</_LLVMInstallDir>
         <_MonoLLVMConfig>$(_LLVMInstallDir)\bin\llvm-config.exe</_MonoLLVMConfig>
-- 
2.21.0.windows.1


```

**Comment by directhex** [comment]
@monojenkins backport to 2019-10

**Comment by directhex** [comment]
Grr

**Pull request merged**
