### PR TITLE
[profiler] Housecleaning

### PR DESCRIPTION
**Pull request by alexrp**
This is a whole bunch of cleanup and refactoring that had to be done in preparation for the runtime control API for the log profiler.

### CODE REVIEW

**Comment by kumpera** [comment]
LGTM

**Comment by kumpera** [comment]
hmm, this branch has conflicts for some reason, so it has not being tested.

**Comment by alexrp** [comment]
GitHub says there's no conflict though. No idea what happened here. I rebased, let's see what happens.

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
Opening a new PR to see if that fixes the weird Jenkins behavior.

**Pull request closed without merging**
