### PR TITLE
[corlib] Fix GetFrames_AsyncCalls test not to block

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@spouliot could you please check if `await StartAsyncCalls ().ConfigureAwait(false);` helps as well?

**Comment by spouliot** [comment]
@marek-safar it hangs at the same place

**Comment by marek-safar** [comment]
ok, just disabled it on mobile

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Comment by marek-safar** [comment]
@monojenkins backport master

**Comment by akoeplinger** [comment]
Manually ported to master with https://github.com/mono/mono/commit/fd71ea2fd35e3607d762e5b71f32f9439d70dc1c, since it was only missing `[Category("MobileNotWorking")]`.

**Pull request merged**
