### PR TITLE
[wasm] Integrate the m2n-gen.cs tool into mcs/tools/wasm-tuner.

### PR DESCRIPTION
**Pull request by vargaz**
It should be ran as:
mono wasm-tuner.exe --gen-interp-to-native <output file name> <extra assemblies>.

The <extra assemblies> will be searched for pinvoke methods, and their signatures
will be added to the set of supported signatures.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins commit csproj

**Comment by jeromelaban** [comment]
@vargaz would it make sense to add the signatures I provided in https://github.com/mono/mono/pull/19671/files#diff-ed19a6a2571eb995ebb5480aa8d7708fR136 ? Or do you have concerns over adding those signatures ?

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
Would rather solve this the right way by generating these during the build.

**Comment by vargaz** [comment]
We can add the signatures through until we have better tooling.

**Pull request merged**
