### PR TITLE
[coop] Convert System_Runtime_Remoting_Messaging_AsyncResult, etc.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
This was closed imho inappropriately.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@jaykrell Sorry about closing the other one - I wasn't sure if you were going to update #16504 or if it was going to come in as a few new PRs.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
