### PR TITLE
[runtime] Some WSL fixes.

### PR DESCRIPTION
**Pull request by alexrp**
WSL issues opened for these workarounds:

* a6c061d1d11824ca483fcd2dfe05d63d58b9f9ed: https://github.com/Microsoft/BashOnWindows/issues/2205
* 959eb46e17ac6544a2a6dc623392457446ee8aed: https://github.com/Microsoft/BashOnWindows/issues/2555

This PR supersedes #5003.

### CODE REVIEW

**Comment by BrzVlad** [comment]
@alexrp weird. On my machine uc_mcontext.fpregs is a pointer inside __fpregs_mem

**Comment by alexrp** [comment]
@BrzVlad yes, that's how it's supposed to be on a 'conforming' (as it were) Linux system. WSL gets the ABI wrong and doesn't set the `fpregs` field to point to `__fpregs_mem`.

**Comment by alexrp** [comment]
@BrzVlad following our discussion on Slack, I've changed the XMM commit to instead disable getting/setting XMM registers if we detect that the `fpregs` field is not set. It's not ideal since we won't scan XMM registers under those broken versions of WSL, but at least we won't crash outright on the first GC attempt.

**Comment by jaykrell** [comment]
WSL/arm64 has similar problems.
Can we skip fpcontext similarly there also?

**Comment by jaykrell** [comment]
https://github.com/Microsoft/WSL/issues/4007

**Comment by lewurm** [comment]
FYI that seems to be fixed with WSL2:
```
(lldb) p/x ((ucontext_t*)(ctx))->uc_mcontext.fpregs
(fpregset_t) $6 = 0x00007fffffffc940
```

I guess not surprising since it runs a real linux kernel?

**Comment by jaykrell** [comment]
Definitely not surprised.

**Pull request merged**
