### PR TITLE
[Microsoft.Build] Fix XS build error + Fix expected output newline from ProcessWrapper.OutputStreamChanged and ProcessWrapper.ErrorStreamChanged

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@radical would you ming reviewing this PR? That will fix 2 issues introduced by the previous Microsoft.Build and Process integration.

**Comment by ludovic-henry** [comment]
This PR depends on https://github.com/mono/mono/pull/2620 to fix XS crash.

**Comment by ludovic-henry** [comment]
@radical: any objection to merging this PR?

**Comment by radical** [comment]
@ludovic-henry Looks OK. Though I wasn't able to get to testing it out.

**Comment by ludovic-henry** [comment]
@radical do you prefer to test it out before merging, or can I merge now?
Otherwise, please feel free to merge it whenever you want. Thank you! :)

**Pull request merged**
