### PR TITLE
Instead of malloc0 + memcpy, use malloc + memcpy + memset the tail.

### PR DESCRIPTION
**Pull request by jaykrell**
Save a few cycles, perhaps, but code is larger.
Split this out of larger change -- either to leave it alone or split it out.

### CODE REVIEW

**Comment by jaykrell** [comment]
build

**Comment by jaykrell** [comment]
build Linux AArch64 ; build  Windows i386 ; build Linux i386

**Comment by luhenry** [comment]
@monojenkins Linux AArch64

**Comment by luhenry** [comment]
@monojenkins Linux AArch64 Interpreter

**Comment by luhenry** [comment]
@monojenkins Linux ARMv5 soft float

**Comment by luhenry** [comment]
@monojenkins Linux ARMv7 hard float

**Comment by luhenry** [comment]
@monojenkins Windows i386

**Comment by luhenry** [comment]
As pointed out by https://xamarinhq.slack.com/archives/C03CELHQQ/p1513673982000354 it's easier to waste some cycles (which the compiler might very well optimize away) and be easier to read/understand, than optimize at all cost.

**Comment by jaykrell** [comment]
The compiler is not going to optimize this, but ok.

**Comment by jaykrell** [comment]
As well, low level runtimes are usually held to a pretty high bar, correctness and performance.

**Comment by vargaz** [comment]
The compiler is not going to be able to optimize this. Also, this is a slowpath, so its not executed often, so optimizing it at the cost of worse readability and the possibility of adding bugs might not be worth it.

**Comment by jaykrell** [comment]
I think it is very readable. I'd like to address this another way as well, such as one or more of:
 - pass a minimum length to utf conversion
 - pass a custom allocator to utf conversion, that knows the minimum length
 - using "with_nuls" that might convert the whole thing, more correctly

**Pull request closed without merging**
