### PR TITLE
[corlib] Increase timeout for MonoTests.System.Runtime.Remoting.TestSynchronizationReleasedOnMultipleAcquire

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
do we know why it now takes so much longer?

**Comment by kumpera** [comment]
Why are we raising this value?
Can't this be hiding a performance regression with the corefx merge that caused it to fail?

**Comment by akoeplinger** [comment]
@kumpera it wasn't a corefx merge it was the XCode upgrade from 8.1-beta1 to 8.3

**Comment by kumpera** [comment]
@akoeplinger wasn't the xcode bump an issue for pinvoke2 on OSX 32bits?

**Comment by akoeplinger** [comment]
@kumpera both of them were caused by the bump

**Pull request merged**
