### PR TITLE
[interp] Pessimize exception handling a little, yielding 16 bytes of frame on gcc, 0 on clang.

### PR DESCRIPTION
**Pull request by jaykrell**
Contributes to https://github.com/mono/mono/issues/16172.
Maybe redundant with https://github.com/mono/mono/pull/16307.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@jaykrell please resolve the merge conflict

**Comment by lewurm** [comment]
or can this be closed due to #16307 ?

**Comment by jaykrell** [comment]
Probably nothing left after merge, will confirm later.

**Comment by jaykrell** [comment]
Nothing left here, closing.

**Pull request closed without merging**
