### PR TITLE
Enhanced logging - attempt 2.5

### PR DESCRIPTION
**Pull request by nealef**
Use correct base this time.

### CODE REVIEW

**Comment by lambdageek** [comment]
LGTM

**Comment by nealef** [comment]
I'm not sure why the sgen-toggleref test fails on Linux x64 (especially when it works on i386). What does that test attempt to exercise?

**Comment by nealef** [comment]
The Windows failures appear unrelated to this PR.

**Comment by nealef** [comment]
@lambdageek s it possible to kick this one again to send it through the check process? The Windows failures look jenkins related. The linux x64 appears to be the sgen-toggleref problem again although i386 worked for it. I am not sure what sgen-toggleref is trying to achieve and why it has anything to do with the logging changes. Last time it was due to the signature of mono_set_trace_handler() changing but we've now restored it with this set of fixes.

**Comment by lambdageek** [comment]
build

**Comment by lambdageek** [comment]
Failures on x64 and arm seem unrelated

**Comment by nealef** [comment]
Thanks @lambdageek for helping me through the process.

**Pull request merged**
