### PR TITLE
[android] Fix Mono.Debugger.Soft tests with Android SDKs

### PR DESCRIPTION
**Pull request by luhenry**
Depends on https://github.com/mono/NUnitLite/pull/20

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins commit csproj

**Comment by akoeplinger** [comment]
@luhenry it looks like we already got two hangs in the Mono.Debugger.Soft on the Android SDK lane after merging this:

- https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/9688/
- https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx-products-sdks-android/9691/

Can you please take a look?

**Comment by luhenry** [comment]
@akoeplinger in both cases, there is `INSTRUMENTATION_ABORTED: System has crashed` meaning the Android emulator has crashed. There is still a problem in `AndroidTestAssemblyRunner` at [1] which doesn't take into account that the instrumentation might not have launched successfully. I'll look into it.

[1] https://github.com/mono/mono/blob/master/mcs/tools/nunit-lite/NUnitLite/AndroidTestAssemblyRunner.cs#L48

**Pull request merged**
