### PR TITLE
[2020-02][MSBuild] Update to vs16.10 branch

### PR DESCRIPTION
**Pull request by mrward**
PR for main - https://github.com/mono/mono/pull/21083

### CODE REVIEW

**Comment by mrward** [comment]
@monojenkins build pkg

**Comment by mrward** [comment]
@monojenkins build pkg

**Comment by KirillOsenkov** [comment]
I was just going to get started on this! Good thing I checked! ❤️

**Comment by mrward** [comment]
@monojenkins build pkg

**Comment by mrward** [comment]
@monojenkins build pkg

**Comment by borgdylan** [comment]
Is the mono fork of MSBuild updated for 16.10 or has the upstream MSBuild applied the changes for supporting mono directly?

**Comment by borgdylan** [comment]
> The mono fork of MSBuild was updated to 16.10 here. Upstream dotnet/msbuild does not support mono currently.

Is the code now included in this repo or is it still in mono/msbuild ?

**Comment by mrward** [comment]
Mono's msbuild source is in the mono/msbuild repo although the 16.10 changes are not in that repo yet, just in my fork http://github.com/mrward/msbuild/tree/xplat-master-vs16.10 - at some point the changes will be in mono/msbuild.

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
