### PR TITLE
[System]: Fix bug in `WebResponseStream.GetResponse()` that will make some people happy.

### PR DESCRIPTION
**Pull request by baulig**
AKA The NuGet Lover's Pull Request.

### CODE REVIEW

**Comment by baulig** [comment]
Test: https://github.com/xamarin/web-tests/commit/0777c6bbe3adc2b678ee286cd8e06067f29e548f

You need to construct the response like in the test.  Total size of the response must be somewhere between 4082 and 4092 bytes and you must send this as a blob - that is, using a single write operation.

**Comment by alanmcgovern** [comment]
What releases and products should this end up in?

**Comment by baulig** [comment]
@alanmcgovern I'd need to check - this _might_ be a regression that got introduced during recent changes (because `BufferOffsetSize` is a recent addition).

If it needs to go into anything older than that, you _will_ have very nasty merge conflicts.  I'll have a look at it.

**Comment by baulig** [comment]
@monojenkins backport 2018-06

**Comment by baulig** [comment]
@monojenkins backport 2018-04

**Comment by baulig** [comment]
@monojenkins backport 2018-02

**Comment by baulig** [comment]
@alanmcgovern Okay, the code in question is not in 2017-12, but in 2018-02, 2018-04 and 2018-06

**Pull request merged**
