### PR TITLE
[System.Web] WizardStepType from reference source

### PR DESCRIPTION
**Pull request by kasthack**

### CODE REVIEW

**Comment by marek-safar** [comment]
@kasthack I know you are now writing any code here but could you sign/confirm cla it would make your contributions easier

**Comment by kasthack** [comment]
@marek-safar I believe, I've already signed it if you are talking about [this one](https://www.docusign.net/Signing/?ti=2e9d50cede094fb29c568498798962db).

**Comment by marek-safar** [comment]
You need to sign https://cla2.dotnetfoundation.org/

**Comment by kasthack** [comment]
Doesn't seem to work for me. I've signed the CLA (here
<https://www.docusign.net/Signing/?ti=03d2d51d5c7249c18d94928f500a3de2>) &
got an email but pull requests are still marked as 'cla-required'.


[image: Inline image 1]

**Comment by kasthack** [comment]
Doesn't seem to work for me. I've signed the .NET Foundation CLA ([here](https://www.docusign.net/Signing/?ti=03d2d51d5c7249c18d94928f500a3de2)) &
got an email but pull requests are still marked as 'cla-required'.

[!image](https://user-images.githubusercontent.com/1292818/32096580-8b3afc52-bb0f-11e7-9279-24773fa879b3.png)

**Comment by akoeplinger** [comment]
@kasthack that should be fine. It usually takes a few hours until the bot is updated, given that you got confirmation already and this is a no code change I think we can take this :)

**Pull request merged**
