### PR TITLE
[2019-12] Bump msbuild to track mono-2019-12

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@marek-safar @rodrmoya which nuget and dotnet sdk versions do we want to use with this?

**Comment by rodrmoya** [comment]
> @marek-safar @rodrmoya which nuget and dotnet sdk versions do we want to use with this?

we need, for vsmac 8.6, the tooling targetting vswin 16.6, so msbuild 16.6 and nuget 5.6

**Comment by radical** [comment]
Also, needs https://github.com/mono/roslyn-binaries/pull/39

**Comment by rodrmoya** [comment]
@monojenkins build pkg

**Pull request merged**
