### PR TITLE
Missed this float32 instruction: OP_RMOVE

### PR DESCRIPTION
**Pull request by nealef**
Add missing rmove/OP_RMOVE.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by nealef** [comment]
Please hold. We found an edge case regression with linears optimization and localloc.

**Comment by nealef** [comment]
It appears that the failure is not due to the optimization but exposes an issue with the mono GC (perhaps platform-specific).

@uweigand  had a closer look at the FinalizerTests problem, and it now seems to him that the linears optimization is correct even here, it just happens to change the code in a way that exposes another pre-existing problem.

The test case in question does the following:
```
       [ConditionalFact(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))] 
      public void Finalizer_OperationNotCompleted_CompletesOperation() 
      { 
          RemoteExecutor.Invoke(() => 
          { 
              var tracker = new OperationCompletedTracker(); 
              NotCompleted(tracker); 

              GC.Collect(); 
              GC.WaitForPendingFinalizers(); 

              Assert.True(tracker.OperationDidComplete); 
          }).Dispose(); 
      } 

      private void NotCompleted(OperationCompletedTracker tracker) 
      { 
          // This is in a helper method to ensure the JIT doesn't artifically extend the lifetime of the operation. 
          AsyncOperationManager.SynchronizationContext = tracker; 
          AsyncOperation operation = AsyncOperationManager.CreateOperation(new object()); 
          Assert.False(tracker.OperationDidComplete); 
      }
```

The interesting thing is the `AsyncOperation` object, which is created but never subsequently used anymore.   The finalizer of that object (when it is garbage collected) sets the OperationDidComplete flag, and the test case verifies that this happens during the `GC.Collect()` call above.

Now the problem seems to be that the address of that AsyncOperation object, in the code base built with the linears optimization, just so happens to be present in r5 at the end of the NotCompleted routine (and that remains unmodified until the `GC.Collect()` call).   It looks like the garbage collector treats all pointers in registers in roots, and therefore does not collect the object.

The code built without linears optimization just uses more registers, and therefore that pointer in r5 is overwritten before we reach the `GC.Collect()` call, and thus the object _is_ collected.   Also, I've verified that even in the code _with_ linears optimization, overwriting r5 in the debugger before NotCompleted returns also causes the test case to complete successfully.

I don't fully understand how exactly the garbage collector works, and how it determines the roots (there must be some platform-specific code to look at registers somewhere?), but just conceptually this seems wrong: since r5 is call-clobbered, any function call, including the call to `GC.Collect()`, will clobber its value.  Therefore, whatever value may be present in r5 at the time of that call _cannot_ point to an object that is still live, since the compiler cannot rely on that value even still being present after the call returns.  Why should the GC then use this value as a root?

I am now looking into the operation of the GC to see  if/where it collecst register values, and if it make sense to collect call-clobbered registers there.

**Comment by nealef** [comment]
This particular thread is calling `GC.Collect()` and so its register contents are being saved to the stack in the various trampolines (in particular into MonoLMF), and these values are found by the garbage collection logic.  It looks like Mono always uses the _conservative_ GC method by default, and this simply looks at __all__ slots on the stack, including those MonoLMF structures.

Given the conservative GC method, it seems to me there is no way that this test can reliably pass, so maybe it simply needs to be disabled when running under Mono.

We'll do some more research but I suspect I'll push a minor fix for another issue and leave the linear optimization enabled for s390x.

**Comment by nealef** [comment]
This should be good to go now.

**Pull request merged**
