### PR TITLE
[wasm] Move test suite to use ninja

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Comment by kumpera** [comment]
cc @kjpou1

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
The linux bots don't have ninja installed.

**Comment by kumpera** [comment]
let me fix that

**Comment by kumpera** [comment]
@monojenkins build failed

**Comment by kumpera** [comment]
@monojenkins build failed

**Comment by kumpera** [comment]
@monojenkins build failed

**Pull request merged**
