### PR TITLE
[Coop] Remove several raw string pointers. Introduce assignment for efficiency and ease of use.

### PR DESCRIPTION
**Pull request by jaykrell**
[Coop] Reduce raw pointers esp. from mono_string_new_checked.
Extracted from https://github.com/mono/mono/pull/15900.

[Coop] In-place object and string handle constructors to port loops w/o structural change.
Been here a few times before and it proves over and over again to provide for improved efficiency and ease of use.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
The mono/mono repository is focused on stability and limiting code churn now so I don't think this change is worth doing here. If you think the change is important please reopen it in dotnet/runtime, thank you!

**Pull request closed without merging**
