### PR TITLE
[MWF] Fix two issues in ListView

### PR DESCRIPTION
**Pull request by AsamK**
Fixes two issues when adding/removing items in a winforms ListView. See the commit messages for more information.

### CODE REVIEW

**Comment by akoeplinger** [comment]
Can you please add tests for this, e.g. in mcs/class/System.Windows.Forms/Test/System.Windows.Forms/ListViewTest.cs ?

**Comment by AsamK** [comment]
Unit tests added

**Comment by akoeplinger** [comment]
build

**Comment by akoeplinger** [comment]
Thanks!

**Pull request merged**
