### PR TITLE
[C#] Fix identifiers checking.

### PR DESCRIPTION
**Pull request by loganek**
This commit fixes bug #24968.

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by loganek** [comment]
Meanwhile, I've also filed new bug on bugzilla, about displaying 'unexpected character/symbol' form: https://bugzilla.xamarin.com/show_bug.cgi?id=27441

**Comment by alexrp** [comment]
@marek-safar this looks like your area

**Comment by marek-safar** [comment]
The issue #27441 was fixed few months ago

**Comment by akoeplinger** [comment]
@marek-safar This PR is about https://bugzilla.xamarin.com/show_bug.cgi?id=24968, which is still open :)

**Comment by marek-safar** [comment]
I got confused but #24968 should be fixed in master too

**Comment by migueldeicaza** [comment]
This has already been fixed differently.

**Pull request closed without merging**
