### PR TITLE
#23050 TransactionScopeAsyncFlowOption

### PR DESCRIPTION
**Pull request by Thorium**

### CODE REVIEW

**Comment by Thorium** [comment]
Not perfect yet, but we need fix for this:
https://bugzilla.xamarin.com/show_bug.cgi?id=23050

**Comment by marek-safar** [comment]
Please follow existing indentation (tabs/spaces).
You need to add new file to System.Transactions.dll.sources as well

**Comment by hardhub** [comment]
Any updates regarding this?

https://bugzilla.xamarin.com/show_bug.cgi?id=23050

**Comment by hardhub** [comment]
It raises NotImplementedException if AsyncFlow is used.

I just used version from corefx and it works fine.

I am not familar with mono source code enough good to make PR.

Maybe somebody can reuse corefx code in correct way?

**Comment by akoeplinger** [comment]
@hardhub you mean you used the source code of TransactionScope from corefx and that worked?

**Comment by hardhub** [comment]
@akoeplinger I think so. I did not tested it deeply. But I was able to compile mono, use it in my project which uses TransactionScope with async calls (using + scope.Complete). I do not use MS/DTC in that project, but I use multiple connections to the same instance of MySQL/MariaDB.  
So at least it looks working.

**Comment by akoeplinger** [comment]
@hardhub ok thanks. Can you please comment on https://github.com/mono/mono/issues/6972 with that info? It should be helpful once we tackle the import of System.Transactions from corefx.

**Comment by hardhub** [comment]
@akoeplinger Do you know any new info regarding that? Any plans to implement it?

I had to use my tricky version from Core FX.
Probably I need to investigate all more and prepare pull request myself.

**Pull request merged**
