### PR TITLE
Cleaning exceptions during static constructor loading

### LINKED ISSUE #13714: Exception during static constructor loading is not cleaned up
## Steps to Reproduce

1. Compiler following sample
```c#
using System;
using System.Reflection;


public static class Test
{
	static Test ()
	{
		throw new ApplicationException ();
	}

	public static void Foo ()
	{

	}
}

class Run
{
	public static void Main ()
	{
		var m = typeof (Test).GetMethod ("Foo");

		try
		{
			m.Invoke (null, null);
		}
		catch (Exception e)
		{
		}

		try
		{
			m.Invoke (null, null);
		}
		catch (Exception e)
		{
		}

		try
		{
			m.Invoke (null, null);
		}
		catch (Exception e)
		{
		}

		m.Invoke (null, null);
	}
}
```
2. mono sample.xe

### Current Behavior

The stack trace from each failure is accumulated with results like

```
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Test' threw an exception. ---> System.ApplicationException: Error in the application.
  at Test..cctor () [0x00001] in <c6d9d0a1394b4a2bbbf5f1d7351b1b11>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <c1faa05c43c14f57bc6406ddc22d57d3>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <c1faa05c43c14f57bc6406ddc22d57d3>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <c1faa05c43c14f57bc6406ddc22d57d3>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <c1faa05c43c14f57bc6406ddc22d57d3>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <c1faa05c43c14f57bc6406ddc22d57d3>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <c1faa05c43c14f57bc6406ddc22d57d3>:0 
  at Run.Main () [0x0004e] in <c6d9d0a1394b4a2bbbf5f1d7351b1b11>:0 
```

### Expected Behavior

Correct stack trace

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows

**Version Used**: master

### PR DESCRIPTION
**Pull request by thaystg**
Reset the stack_trace and trace_ips because the type initialization exception is reused.
Fixes #13714

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
Could you add a test case? You can probably add it to some of the tests in `mono/tests/exception*.cs`

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by thaystg** [comment]
@monojenkins build failed.

**Pull request merged**
