### PR TITLE
[2018-08] [llvm] Add support for OP_RCNEQ.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/12131.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins backport 2018-10

**Comment by lewurm** [comment]
@monojenkins backport 2018-12

**Comment by lewurm** [comment]
Change is already in `2018-10` and `2018-12`.

**Pull request merged**
