### PR TITLE
[merp] Produce hashes for unmanaged thread stacks also

### PR DESCRIPTION
**Pull request by alexischr**
Before, this was only done for managed stacks.

Addresses https://github.com/mono/mono/issues/18941

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by lambdageek** [comment]
@monojenkins backport to 2020-02
@monojenkins backport to 2019-12

**Pull request merged**
