### PR TITLE
[wasm] Fix the build plus #7661 and #7864.

### PR DESCRIPTION
**Pull request by kumpera**
Fixes https://github.com/mono/mono/issues/7661
Fixes https://github.com/mono/mono/issues/7864

### CODE REVIEW

**Comment by lewurm** [comment]
I'm not a fan of yet another boolean flag (`mono_interpreter_only`). What parts of the runtime need `mono_aot_only` to be true in order to work on wasm?

**Comment by kumpera** [comment]
wasm interp only works under "FullAOT" so... all of them.

This is a regression from @vargaz recent change to support fixed mode that effectively disables the interpreter under FullAOT.

It's not clear to me why his work needs things this way and I didn't want to break him, so this new far was introduced to address the behavior.

As I mentioned, the right fix is to remove all of the mode flags and replace them with feature flags. Things will make more sense and we'll actually be able to reason on specific checks.

**Comment by vargaz** [comment]
Those changes don't break the interpreter, they just prioritize full-aot-ed code when running with both --full-aot and --interp.

**Comment by kumpera** [comment]
all failures are due to github going offline for a bit.

**Comment by kumpera** [comment]
@monojenkins build

**Comment by luhenry** [comment]
The git error is because it can't find the proper commit on external/corert.

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Coop GC

**Comment by kumpera** [comment]
Superseded by https://github.com/mono/mono/pull/7946

**Pull request closed without merging**
