### PR TITLE
[socket] Add test for SocketOptionName.MulticastTimeToLive

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
How does this fix the bug if you're just adding a test?

**Comment by ludovic-henry** [comment]
It doesn't... It's an oversight on my end, will fix tomorrow

**Comment by ludovic-henry** [comment]
@akoeplinger I amended the commit

**Comment by ludovic-henry** [comment]
@monojenkins merge

**Pull request merged**
