### PR TITLE
Release the mutex in mono_cond_[timed]wait on Windows.

### PR DESCRIPTION
**Pull request by madewokherd**
Like the pthread_cond_wait functions, this needs to release the mutex while waiting on the condition. Otherwise, nothing can set the condition during the wait call.

This commit is licensed as MIT/X11.

### CODE REVIEW

**Comment by kumpera** [comment]
This change is wrong, the mutex and the wait must be atomic for a reason. 

Since the minimum version of windows we support now is Vista, we should use windows cond vars instead of this hack.

**Comment by madewokherd** [comment]
The build files all have _WIN32_WINNT set to 0x502 (Windows XP SP2), are you sure Windows XP isn't supported?

**Comment by vargaz** [comment]
I think we deprecated win2k support, not xp.

**Comment by madewokherd** [comment]
Can you explain the semantics we need but can't get by releasing the mutex during the wait?

**Comment by kumpera** [comment]
We need the exact same semantics of a unix conditional variable, which is that the unlocking and the wait happen atomically when you start the way and that when the wait has ended that the lock is atomically acquired.

This is required to avoid race conditions with situations like lost notifications.

**Comment by kumpera** [comment]
It's ok if we drop XP support, MS dropped it more than a year ago.

**Comment by madewokherd** [comment]
With mono_cond_signal, at least, we're guaranteed to unblock at least one thread. It doesn't matter if the event is set before the other thread begins to wait on the event, the wait will still end. So I don't think we can lose a notification in that way.

**Comment by madewokherd** [comment]
mono_cond_broadcast is obviously broken though.

**Comment by madewokherd** [comment]
I think I see what you mean now - if we call mono_cond_signal twice we won't necessarily unblock 2 threads even if 2 threads are waiting.

There are hacks in debugger-agent.c using WaitForSingleObject which we'll have to remove if we fix this.

**Pull request merged**
