### PR TITLE
Bump corefx to pick up #370

### PR DESCRIPTION
**Pull request by steveisok**
Added HAVE_LCHFLAGS & HAVE_STAT_FLAGS to configure

### CODE REVIEW

**Comment by steveisok** [comment]
Testing against https://github.com/mono/corefx/pull/370 to see if this builds on CI.  Will need to switch back once corefx PR goes through.

/cc @alexischr

**Comment by alexischr** [comment]
@steveisok corefx PR is merged, you can re-target this PR to https://github.com/mono/corefx/commit/1cdb9c20946c74a88a7fa507215556fadc2c2b27

I think I should have squashed, sorry :/

**Comment by steveisok** [comment]
This should be ready to go now.

**Comment by akoeplinger** [comment]
@monojenkins commit csproj

**Comment by steveisok** [comment]
@monojenkins backport 2019-10

**Pull request merged**
