### PR TITLE
LLVM: use fneg instead of fsub for `-x`

### PR DESCRIPTION
**Pull request by EgorBo**
Use actual `-x` instead of `0-x` for NEG
Fixes https://github.com/mono/mono/issues/18052

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build OS X x64 C++

**Pull request merged**
