### PR TITLE
Use eglib win32 helper functions without MAX_PATH limit

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Update to use Jay's helper functions introduced in #16562

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
Oops, forgot we were using the mono_w32process stuff for cross-platform compat. Will update the signatures for the relevant functions.

**Comment by CoffeeFlux** [comment]
Okay, less small than I'd hoped for, but still should be pretty quick to review.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
I'm not sure careful maintenance of declarations is worth the tedium and noise, vs.  deferring the check to be a link error. At least on Windows it is always a static link error. Maybe Unix allows the unresolved external when building .so files.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Pull request merged**
