### PR TITLE
[interp][wasm] Disable inlining, it is recursive, exhausts stack.

### PR DESCRIPTION
**Pull request by jaykrell**
This fixes https://github.com/mono/mono/issues/18646.
Stack usage and/or recursion needs to be further reduced.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 C++

**Comment by jaykrell** [comment]
While I am guessing some, fundamentally, thousands of lines of mutually recursive functions, and a non-optimizing compiler, is going to exhaust the stack with temporaries.

**Comment by jaykrell** [comment]
1. It is overkill agreed, and indicated.
There are other ways to improve it, a lot, or even as much.
a lot: The split technique
as much: use a heap allocated queue or heap allocated stack instead of the machine stack.
(e.g. std::queue, std::stack)

2. I don't know, or the implications.

**Comment by jaykrell** [comment]
Not sure if this is what you mean, but it didn't seem to help:

```
diff --git a/mono/metadata/class-init.c b/mono/metadata/class-init.c
index 71eaf37447c..a26ee1dc8c2 100644
--- a/mono/metadata/class-init.c
+++ b/mono/metadata/class-init.c
@@ -4335,6 +4335,13 @@ mono_get_unique_iid (MonoClass *klass)
 	return iid;
 }
 
+gboolean
+mono_method_is_cctor (MonoMethod *method)
+{
+	return (method->flags & METHOD_ATTRIBUTE_SPECIAL_NAME) &&
+		strcmp (".cctor", method->name) == 0;
+}
+
 /**
  * mono_class_init_internal:
  * \param klass the class to initialize
diff --git a/mono/metadata/class-internals.h b/mono/metadata/class-internals.h
index 21d0e4b0881..b03500a76e0 100644
--- a/mono/metadata/class-internals.h
+++ b/mono/metadata/class-internals.h
@@ -1518,6 +1518,9 @@ mono_method_is_constructor (MonoMethod *method);
 gboolean
 mono_class_has_default_constructor (MonoClass *klass, gboolean public_only);
 
+gboolean
+mono_method_is_cctor (MonoMethod *method);
+
 // There are many ways to do on-demand initialization.
 //   Some allow multiple concurrent initializations. Some do not.
 //   Some allow multiple concurrent writes to the global. Some do not.
diff --git a/mono/mini/interp/transform.c b/mono/mini/interp/transform.c
index f3907b7c9cf..e892b165695 100644
--- a/mono/mini/interp/transform.c
+++ b/mono/mini/interp/transform.c
@@ -2055,6 +2055,9 @@ interp_method_check_inlining (TransformData *td, MonoMethod *method)
 	if (header.code_size >= INLINE_LENGTH_LIMIT && !(method->iflags & METHOD_IMPL_ATTRIBUTE_AGGRESSIVE_INLINING))
 		return FALSE;
 
+	if (mono_method_is_cctor (td->method))
+			return FALSE;
+
 	if (mono_class_needs_cctor_run (method->klass, NULL)) {
 		MonoVTable *vtable;
 		ERROR_DECL (error);
```

**Comment by jaykrell** [comment]
Actually this PR maybe isn't effective even.
This is this PR, combined with others that mostly conserve stack, but at times add stack.

```
"<?>.wasm-function[MonoInterpGenerateCode::mono_generate_code_2()]@[wasm code]
<?>.wasm-function[MonoInterpGenerateCode::mono_generate_code()]@[wasm code]
<?>.wasm-function[generate_code(TransformData*, _MonoMethod*, _MonoMethodHeader*, _MonoGenericContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[generate(_MonoMethod*, _MonoMethodHeader*, _InterpMethod*, _MonoGenericContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_interp_transform_method_2(_InterpMethod*, ThreadContext*, _MonoMethod*, _MonoMethodSignature*, _MonoDomain*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_interp_transform_method(_InterpMethod*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_transform_method(_InterpFrame*, ThreadContext*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke]@[wasm code]
<?>.wasm-function[mono_runtime_class_init_full(MonoVTable*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_interp_transform_method(_InterpMethod*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_transform_method(_InterpFrame*, ThreadContext*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_newobj_fast(_InterpFrame*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_newobj_fast(_InterpFrame*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke]@[wasm code]
<?>.wasm-function[mono_runtime_class_init_full(MonoVTable*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke]@[wasm code]
<?>.wasm-function[mono_runtime_class_init_full(MonoVTable*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_interp_transform_method(_InterpMethod*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_transform_method(_InterpFrame*, ThreadContext*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke]@[wasm code]
<?>.wasm-function[mono_runtime_class_init_full(MonoVTable*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_newobj_fast(_InterpFrame*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke]@[wasm code]
<?>.wasm-function[mono_runtime_class_init_full(MonoVTable*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_interp_transform_method(_InterpMethod*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_transform_method(_InterpFrame*, ThreadContext*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_newobj_fast(_InterpFrame*, ThreadContext*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_invoke_checked(_MonoMethod*, void*, void**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke_array(_MonoMethod*, void*, _MonoArray*, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[ves_icall_InternalInvoke(MonoReflectionMethodHandle, MonoObjectHandle, MonoArrayHandle, MonoExceptionHandle, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[ves_icall_InternalInvoke_raw]@[wasm code]
<?>.wasm-function[do_icall(_MonoMethodSignature*, int, stackval*, void*, int)]@[wasm code]
<?>.wasm-function[do_icall_wrapper(_InterpFrame*, _MonoMethodSignature*, int, stackval*, void*, int)]@[wasm code]
<?>.wasm-function[interp_exec_method_full(_InterpFrame*, ThreadContext*, FrameClauseArgs*, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[interp_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_jit_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[do_runtime_invoke(_MonoMethod*, void*, void**, _MonoObject**, _MonoErrorInternal*)]@[wasm code]
<?>.wasm-function[mono_runtime_try_invoke]@[wasm code]
<?>.wasm-function[mono_runtime_invoke]@[wasm code]
<?>.wasm-function[mono_wasm_invoke_method]@[wasm code]
wasm-stub@[wasm code]
Eb@[native code]
http://192.168.0.20:8000/_framework/wasm/dotnet.js:1:189640
call_method@http://192.168.0.20:8000/_framework/wasm/dotnet.js:1:153837
http://192.168.0.20:8000/_framework/wasm/dotnet.js:1:156177
callEntryPoint@http://192.168.0.20:8000/_framework/blazor.webassembly.js:1:37229
http://192.168.0.20:8000/_framework/blazor.webassembly.js:1:33889
http://192.168.0.20:8000/_framework/blazor.webassembly.js:1:32396
i@http://192.168.0.20:8000/_framework/blazor.webassembly.js:1:31247
promiseReactionJob@[native code]"
```

**Comment by BrzVlad** [comment]
This doesn't look like the way to go, and has extreme perf implications.

**Comment by jaykrell** [comment]
I was desparate. I'm feeling less desparate now, but still, the interpreter remains very recursive and not easily dealt with thoroughly.

**Pull request closed without merging**
