### PR TITLE
[wasm] Fix CI target and npm install to be local.

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build wasm

**Comment by kumpera** [comment]
@monojenkins build wasm

**Comment by kumpera** [comment]
WASM failure is due to a Chakra crash.

**Comment by akoeplinger** [comment]
Can we disable the test that makes Chakra crash for now?

**Comment by akoeplinger** [comment]
@monojenkins build wasm

**Comment by akoeplinger** [comment]
"Linux WebAssembly" is green so let's get this in :)

**Pull request merged**
