### PR TITLE
[profiler] disable inlining when coverage profiler is used and fix allocation sizes

### PR DESCRIPTION
**Pull request by lewurm**
Fixes https://github.com/mono/mono/issues/17774

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2019-10

**Comment by alexrp** [comment]
Is this check not enough? https://github.com/mono/mono/blob/aa2fbc56c8a898e361db13fb1c78031dd02e2308/mono/mini/method-to-ir.c#L3958

**Comment by lewurm** [comment]
> Is this check not enough?
> 
> https://github.com/mono/mono/blob/aa2fbc56c8a898e361db13fb1c78031dd02e2308/mono/mini/method-to-ir.c#L3958

This check is about the _inlinee_. Let's assume that the caller has coverage instrumentation enabled and the callee (inlinee) has not, then, when inlining the callee, `cfg->prof_coverage` is still in the context of the caller.

We probably could make it work by storing/restoring `cfg->prof_coverage`/`cfg->coverage_info` before inlining, too.

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-12

**Pull request merged**
