### PR TITLE
[runtime] Use a HOST_OSX define instead of PLATFORM_MACOSX, pass it i…

### PR DESCRIPTION
**Pull request by vargaz**
…n config.h instead of the command line.

### CODE REVIEW

**Comment by lewurm** [comment]
looks good, but why?

**Comment by vargaz** [comment]
PLATFORM_ defines don't specify whenever its the host or the target, so we are trying to move away from them.

**Comment by luhenry** [comment]
`HOST_OSX` is semantically wrong, as `$host` contains `*-*-darwin*` for any darwin OS (OS X, macOS, iOS, tvOS and watchOS), so it should be `HOST_DARWIN`.

**Comment by luhenry** [comment]
Otherwise I love this change, and we should do the same with all other `PLATFORM_*` defines.

**Pull request merged**
