### PR TITLE
Sync some HttpClient tests with .NET Core 3.1.

### PR DESCRIPTION
**Pull request by baulig**
Requires https://github.com/mono/corefx/pull/380.

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build Linux x64 All Profiles Build

**Comment by baulig** [comment]
This was essentially a failed experiment.  Just don't feel like closing it just yet.

**Comment by baulig** [comment]
Well, in hindsight, this is actually causing far more trouble than good.  Goodbye.

**Pull request closed without merging**
