### PR TITLE
[profiler] Use a semaphore to signal the writer thread.

### PR DESCRIPTION
**Pull request by alexrp**
We would previously constantly try to dequeue from the writer queue which would
result in extremely high CPU usage, making many apps (e.g. Xamarin Studio)
nearly unusable.

### CODE REVIEW

**Comment by alexrp** [comment]
@kumpera this is a revived (and revised) version of #2425. I just realized I forgot to reopen a new PR at the time, so the commit had been sitting in my git stash for months...

OTOH, this was a good chance to have another look at the issue. It turns out that what I was trying to do with a condition variable was incredibly straightforward to do with a simple semaphore. It also performs *way* better and maintains the lock-free nature of the buffer queue.

For the record, the specific test I used to monitor the performance of this change was this program: https://gist.github.com/alexrp/beffb94692520700e54d7e9e2f70ccbe

I ran it with `mono --profile=log:sample,sampling-real wtest.exe 16` (so 16 threads and sampling all threads 1000 times per second) on Linux amd64. Observing in `htop`, the CPU usage of the writer thread sits at a fairly stable ~2-3%. I also did some measurements of peak resident memory usage of this test and it hovers around ~15-16mb. Prior to the patch, CPU usage by the writer thread was more like 100-110% and peak memory usage around ~14-15mb.

So it seems we use some more memory as a result of having *any* kind of wait in the writer thread loop, but that's to be expected, I think, regardless of how we do it. I'd certainly say it's a small sacrifice to not completely slow apps to a crawl.

**Comment by alexrp** [comment]
build

**Comment by kumpera** [comment]
LGTM

**Comment by alexrp** [comment]
@monojenkins merge

**Comment by alexrp** [comment]
build

**Pull request merged**
