### PR TITLE
Ignore GetAttributes_ReadOnly and Create_Path_ReadOnly when running as root, as LLVM CI does.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
Workaround for https://github.com/mono/mono/issues/8903

**Comment by lewurm** [comment]
I think the proper fix is to avoid running those tests as root.

**Comment by jaykrell** [comment]
That's kinda what this is doing. Is there another way?

**Comment by jaykrell** [comment]
Oh, you mean, fix Jenkins? Well, seeing if things work as root -- the rest does -- seems kinda reasonable.

**Comment by akoeplinger** [comment]
Jenkins was fixed to no longer run these tests as root but I still think we should merge this since it makes sense.

**Pull request merged**
