### PR TITLE
Added DataProtector and DpapiDataProtector classes. fixes #22336

### PR DESCRIPTION
**Pull request by rjvdboon**
These were introduced in .Net 4.5 and are used by Owin 3 security components.
Also changed CryptoConfig.CreateFromName to not swallow exceptions.

This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=22336

### CODE REVIEW

**Comment by migueldeicaza** [comment]
@jonpryor @spouliot Considering bringing this in, but I suspect this might require changes to the linker and non-default profiles.

**Comment by jonpryor** [comment]
@radekdoulik: Could you please chime in on any need for linker changes here?

**Comment by spouliot** [comment]
1. There should not be any change to CryptoConfig without corresponding unit tests, nor without ensuring all existing unit tests, for all assemblies, are fine too (this is used in many places);

2. This needs to be modified for the MOBILE profile, at least for FULL_AOT_RUNTIME. But as long as it's not enabled on mobile then it is not a problem;

3. I have not checked MS RS lately but, if it was open sourced, then we should adopt MS version (which would use Mono's DPAPI _emulation_).

**Comment by radekdoulik** [comment]
@jonpryor: yes. I think we will need to extend mcs/tools/tuner/Mono.Tuner/PreserveCrypto.cs with the new types.

And do it in XA as well if it happens before the Mono.Tuner unification is complete.

**Comment by rjvdboon** [comment]
@spouliot to answer on your comments:
1. This new behaviour is tested in the DataProtector tests. This new class is apparently the first crypt class that takes parameters in the Create(). The reason I changed CryptoConfig is that the RS CryptoConfig doesn't swallow the exception either. (All new unittests were first written against .Net4.5. I created the mono class afterwards, hat's where I found out). All current unittest succeeded, afaict.
2. Not my territory, don't know. Would need direction if I should fix that.
3. The DpapiDataProtector and DataProtector were not in RS when I checked last week.

There was one difference between ms.net and mono which I didn't/couldn't fix, and that was that .net ProtectedData.Decrypt detects the scope to use, while Mono's emulation doesn't and thus needs the scope to be set correctly. This is captured in an Ignored unittest.

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by rjvdboon** [comment]
A bit of rework is needed to comply with the comments. And I still haven't
got the green light from my employer :-(
I could as well make a new PR when I finally get my approval...

**Comment by migueldeicaza** [comment]
Closing due to lack of employer approval.   We will have to bring this from reference source.

**Pull request closed without merging**
