### PR TITLE
 [sgen] Fix unified suspend bad stack crash

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by vargaz** [comment]
This is an optimization to avoid scanning the native stack above the thread start function. Can it be fixed instead of removed ?

**Comment by ludovic-henry** [comment]
@vargaz the only place where it has an effect is in start_wrapper, which only parent native stack frame is inner_start_thread (https://github.com/mono/mono/blob/master/mono/utils/mono-threads.c#L1135). So the optimization avoid scanning only a tiny number of bytes, and fixing it would involve largely modifying `sgen_unified_suspend_stop_world` (https://github.com/mono/mono/blob/master/mono/metadata/sgen-stw.c#L249)

**Comment by vargaz** [comment]
Its also called for the main thread.

**Comment by vargaz** [comment]
So this was added by:
e78b0b96bf105a47e6d53367c99eb0b2b2088726
and
72b8bf64028ce73ff4a9e6c6c8678dc628da145f

which was done to fix/improve this:
https://bugzilla.xamarin.com/show_bug.cgi?id=2619

**Comment by ludovic-henry** [comment]
I followed your advice and simply remove the call to `mono_gc_set_stack_end` in `start_wrapper`

**Comment by vargaz** [comment]
Looks ok. Maybe we could fix it by resetting it at the end of start_wrapper (), but that is more complicated. The new startup code doesn't touch any objects I think, so keeping it would not save us much.

**Pull request merged**
