### PR TITLE
[reflection] Use mono_module_get_object_handle everywhere

### PR DESCRIPTION
**Pull request by lambdageek**
- Refactor how reflection object caching is implemented

  Split all the `mono_XXX_get_object_checked` functions into a generic cache checking portion and a specific object creation portion.

- Reimplement the `MonoReflectionAssembly` and `MonoReflectionModule` creation functions using handles.
- Switch out all uses of `mono_module_get_object_checked` (raw ptr) by `mono_module_get_object_handle` (handles) everywhere.  Reimplemented the following icalls:
  - `System.RuntimeTypeHandle`: `GetModule`
  - `System.Reflection.Assembly`:
    - `GetManifestModuleInternal`
    - `GetManifestResourceInfoInternal`
    - `GetManifestResourceInternal`
    - `GetModulesInternal`

### CODE REVIEW

**Comment by vargaz** [comment]
It might make sense to move the image->Module cache to managed code, the runtime doesn't really use it.

**Comment by lambdageek** [comment]
I thought about moving all the caches to managed, actually, but that seemed like a big change to do in one go.  But yea the Module cache might be a good candidate. I'll update the PR.

**Comment by lambdageek** [comment]
Ugh. I'm less enthusiastic about rewriting this in managed.
So let's say I do the most naive thing and put a `Dictionary<IntPtr,S.R.Module>` per-domain.

Problem is `mono_module_get_object` is MONO_API and it takes a domain argument. So to do a lookup I'll have to find the right hash table (annoying but doable by poking around in the `MonoAppDomain`), but then I have to switch to that domain and then run the lookup and insert functions for that dictionary in that domain.  That seems kind of tricky.

**Comment by vargaz** [comment]
We should leave it in native then.

**Pull request merged**
