### PR TITLE
[cxx] Remove extern "C" in dlmalloc as alternative to previous.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by lambdageek** [comment]
I guess I weak-prefer NO_MALLINFO - if we are not using it, no point in compiling it.

**Comment by jaykrell** [comment]
I conflicted here too. 
There are multiple other motivations for 
& against, nothing super strong, agreed.

 - minimize externC, maximize typesafe linkage
 - minimize changes to third party 
 - define in makefile is less edit,
 but more build system sensitivity
 & I dislike build system sensitivity 
 - you can do both, 
define out the code & remove externC
 - not much extra code but true
 - the extra code was fine as C

**Comment by lambdageek** [comment]
let's keep extern C and NO_MALLINFO for now

**Pull request closed without merging**
