### PR TITLE
[tuner/linker] Update code to fix build errors after cecil update.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
CC @marek-safar

**Comment by akoeplinger** [comment]
@marek-safar why did this not break in CI ?

**Comment by rolfbjarne** [comment]
CecilRocks.cs doesn't seem to be built in mono, and the changes in other files are warnings, not errors.

**Comment by marek-safar** [comment]
@akoeplinger we are not building/using/testing linker. It's TODO to do it when we have it fully in mono repo

**Comment by spouliot** [comment]
@marek-safar the original `monolinker` [1] is already (and always was) fully part of the mono repo and can be used to ensure the basic steps works.

[1] it is (or was, pre-open source) used on `mmp` before mkbundl'ing it

**Comment by ludovic-henry** [comment]
This seems to break Windows build : https://jenkins.mono-project.com/job/x/774/parsed_console/log_content.html#ERROR1

**Pull request merged**
