### PR TITLE
[netcore] Bump CoreFX, core-setup dependencies

### PR DESCRIPTION
**Pull request by filipnavara**
Should fix some of the flaky tests by picking up dotnet/corefx@a192823.

### CODE REVIEW

**Comment by filipnavara** [comment]
Looks like couple of regressions popped up, most likely due to some packaging errors:
- `System.Json` and `System.Data.SqlClient` libraries are not found. The should come from the `Microsoft.Private.CoreFx.OOB` package but it looks broken.
- Tests added in https://github.com/dotnet/corefx/pull/40365 are not properly guarded for multiple platforms. It is not obvious whether that is intentional and whether they are supposed to be distributed.

**Comment by filipnavara** [comment]
The failures to load assemblies are happening for tests run through `Microsoft.DotNet.RemoteExecutor`. Looks like something with runtimeconfig.json may be broken again.

**Comment by filipnavara** [comment]
Apparently the downloaded `System.Data.SqlClient.Tests.deps.json` file has no reference to `System.Data.SqlClient` library. It may be loaded dynamically but since we don't use `CoreRun` the runtime doesn't have a way to locate these dependencies.

**Comment by filipnavara** [comment]
Deps are sorted out (to be pushed), looking into the few remaining failures.

**Comment by marek-safar** [comment]
Thank you!

**Pull request merged**
