### PR TITLE
[mini] Don't verify types if you store to a pointer byref.

### PR DESCRIPTION
**Pull request by kumpera**
Workarounds #8403.

### CODE REVIEW

**Comment by luhenry** [comment]
@kumpera we should absolutely add a test case for that.

**Comment by kumpera** [comment]
@luhenry added. Thanks for keeping me honest. :)

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Comment by kumpera** [comment]
@jaykrell fixed the variable name on this PR, that will land into master. I think it's ok if that bit doesn't land on the backports.

**Comment by jaykrell** [comment]
Definitely. I half just want to be sure I understand what is going on.

**Pull request merged**
