### PR TITLE
[tests] Remove manual for loop to run sgen tests and use different make targets

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
:+1: to the first commit, makes it much more readable!

:-1: to the second, I like having the summary at the bottom of the tests even if all passed.

**Comment by ludovic-henry** [comment]
The raison for https://github.com/mono/mono/commit/8599581b34179bb2ffb7c65665c06497b113524b is so when looking at the console output, we can spot failed or timedout commit faster: simply `grep -e '(failed|timed out)'`

**Comment by akoeplinger** [comment]
LGTM now!

**Comment by akoeplinger** [comment]
Most of the tests need a larger timeout. In the perl-based testrunner, we used 15minutes (via a really ugly hack: https://github.com/mono/mono/blob/master/mono/tests/test-driver#L28-L30).

Looking at the output on Jenkins, it'd also be great if the runner printed the timeout value when a test times out as it's not clear what the value is.

**Comment by ludovic-henry** [comment]
I updated the timeout for these tests to 15 minutes now

**Pull request merged**
