### PR TITLE
CoreFX import for AlgorithmIdentifier type

### PR DESCRIPTION
**Pull request by MaximLipnin**
- imports CoreFX AlgorithmIdentifier type and related xunit tests;
- removes obsolete AlgorithmIdentifier file;
- removes existing AlgorithmIdentifierTests because they were ported to CoreFX as part of https://github.com/dotnet/corefx/pull/30489.

As part of #7589

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by MaximLipnin** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by MaximLipnin** [comment]
@monojenkins build Linux x64 Hybrid Suspend

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Comment by MaximLipnin** [comment]
Thanks for the review!

**Pull request merged**
