### PR TITLE
Bugfix DateTime in Sqlite: https://bugzilla.xamarin.com/show_bug.cgi?id=40603

### PR DESCRIPTION
**Pull request by jogibear9988**
Fixes that dates written from System.Data.Sqlite could not be read on Mono!

### CODE REVIEW

**Comment by jogibear9988** [comment]
One more question: Is Mono.Data.Sqlite at any time synced to System.Data.Sqlite? Is see more missing parts here!

**Comment by marek-safar** [comment]
approve

**Comment by Andrejf** [comment]
The default value set in the last commit is wrong for non-UTC times and it has corrupted a couple of our databases. Up to the original commit, the default time was for example:
2016-11-24 14:08:46.761686

From now on it is 
2016-11-24 14:08:46.761686+01:00

Timezone should not be stored for non-UTC times. This is how System.Data.SQLite works.

Test case in Bugzilla
https://bugzilla.xamarin.com/show_bug.cgi?id=46929

**Comment by jogibear9988** [comment]
I'm sory that I broke some Code. I changed the array order, cause I copied the Parse Formats directly from System.Data.Sqlite.

**Pull request merged**
