### PR TITLE
[Microsoft.Build.Evaluation] Fix Project.DirectoryPath

### PR DESCRIPTION
**Pull request by tcptr**
Project.DirectoryPath should return the root directory for the related project.

### CODE REVIEW

**Comment by alexrp** [comment]
build

**Comment by atsushieno** [comment]
Please add tests and verify that your changes are valid on .NET.

**Comment by radical** [comment]
Fix looks fine. Could you please add some tests for this like:

1. xml file loaded from a path!=current_dir
2. xml loaded from a string
3. xml loaded and ProjectRootElement.DirectoryPath set explicitly

And change the commit message to be a little descriptive.

**Comment by lewurm** [comment]
@tcptr is there still interest to merge this or should it be closed?

**Comment by radical** [comment]
Don't close this, I'll add the tests.

**Comment by lewurm** [comment]
hey @radical, what's the status of this PR?

**Pull request closed without merging**
