### PR TITLE
[llvm] Use CoreCLR GC interop configuration

### PR DESCRIPTION
**Pull request by alexanderkyte**
Since they're identical right now, we can use the coreclr configuration
to make our IR more easily analyzed by tools built around LLVM.

```
class CoreCLRGC : public GCStrategy {
public:
  CoreCLRGC() {
    UseStatepoints = true;
    // These options are all gc.root specific, we specify them so that the
    // gc.root lowering code doesn't run.
    InitRoots = false;
    NeededSafePoints = 0;
    UsesMetadata = false;
    CustomRoots = false;
  }

  Optional<bool> isGCManagedPointer(const Type *Ty) const override {
    // Method is only valid on pointer typed values.
    const PointerType *PT = cast<PointerType>(Ty);
    // We pick addrspace(1) as our GC managed heap.
    return (1 == PT->getAddressSpace());
  }
};

/// A GCStrategy for the Mono Runtime.
class MonoGC : public GCStrategy {
public:
  MonoGC() {
    UseStatepoints = true;
    // These options are all gc.root specific, we specify them so that the
    // gc.root lowering code doesn't run.
    InitRoots = false;
    NeededSafePoints = 0;
    UsesMetadata = false;
    CustomRoots = false;
  }
};
```

Source: https://github.com/mono/llvm/blob/64c0343537016c153894dc60316bd7b316b812c8/lib/CodeGen/BuiltinGCs.cpp#L105-L137

### CODE REVIEW

**Comment by jaykrell** [comment]
So much for not having statics with constructors? :(

**Comment by alexanderkyte** [comment]
@jaykrell I'm not sure I follow. This is a configuration change that results in no functional change in the emitted IR, but simplifies our configuration a bit and makes our IR back into legal LLVM IR for vanilla LLVM.

**Comment by alexanderkyte** [comment]
We forked LLVM and added a new configuration "based on" the coreclr one. In practice, our configuration is identical. This change takes advantage of it being identical.

**Comment by jaykrell** [comment]
Sorry, I was referring to the nearby code, not you change. Hypothetically LLVM has no static constructors, and is cheap to load, but we have loaded LLVM because this isn't true. So looking at your change got me to see some static constructors.

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
