### PR TITLE
[bockbuild] Detect HTTP errors  when using curl

### PR DESCRIPTION
**Pull request by alexischr**
https://github.com/mono/mono/issues/6994

Amendment to https://github.com/mono/mono/pull/7181

Prevents some HTTP failures from still resulting in a downloaded file (usually an HTML error page)

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins backport to 2018-02

**Comment by alexischr** [comment]
@monojenkins backport to 2017-12

**Comment by akoeplinger** [comment]
This was already backported to 2017-12/2018-02

**Pull request merged**
