### PR TITLE
[Coop] Remove handles from Mono.Interop.ComInteropProxy.

### PR DESCRIPTION
**Pull request by jaykrell**
Used to depend on https://github.com/mono/mono/pull/16987 but no longer.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build deb with monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build deb with monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@monojenkins build deb with monolite

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by lambdageek** [comment]
@monojenkins build deb with monolite

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by lambdageek** [comment]
@monojenkins build failed

**Pull request merged**
