### PR TITLE
HttpListenerRequest to ignore bad cookies and keep request alive

### PR DESCRIPTION
**Pull request by yurigorokhov**
HttpRequestListener throws on incorrect cookie name. It throws CookieException ("Name contains invalid characters"). There are many cookies out there that unfortunately do not conform to the guidelines and HttpRequestListener will kill the request in such a case. The .Net framework under windows lets the request through however.

Included is a patch HttpListenerRequest as well as a test with a bad cookie name.

I have tested this under linux(master branch) and .net (4.0), they now both have the same behavior.

### CODE REVIEW

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by yurigorokhov** [comment]
@lewurm @grendello yes, definitely still interest. We have been running with the patched version in production for many years now.

**Comment by migueldeicaza** [comment]
I have read the rationale for the exception handling, and I am ok with the change, and on the plus side, it includes a test that shows the problem.

This looks good to me.

**Comment by yurigorokhov** [comment]
@migueldeicaza thanks! Looking forward to seeing this merged!

**Comment by bjorg** [comment]
Woohoo!!

**Comment by akoeplinger** [comment]
I've rebased the PR against master because it got stale, please head over to https://github.com/mono/mono/pull/5657 :)

**Pull request closed without merging**
