### PR TITLE
[interp] Split newobj into newobj{,string}, remove unused enum, vt.

### PR DESCRIPTION
**Pull request by jaykrell**
They have a common prefix, make a macro for that NEWOBJ_COMMON. Maybe a function?
And common tail -- goto.

This refactoring was requested (https://github.com/mono/mono/pull/18903#issuecomment-588086898)

There is a lot of code movement here.
From interp.c to transform.c
newobj_class => klass
hopefully all the data is initialized

And splitting up the case, and moving much into a multi-line macro.

### CODE REVIEW

**Comment by BrzVlad** [comment]
these newobj opcodes are not common, so I would rather have the macro a function instead, but I don't care too much.

did you check if all these opcodes are reachable (the newobj_vt one )? maybe add a g_assert in that method and run some suites locally, even a full PR run maybe

**Comment by jaykrell** [comment]
Oops, two look dead -- csc.exe itself doesn't use them. Removed and we'll see.
Also structs cannot have weak references or finalizes it looks like, so vt is always fast?

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Maybe a smaller change -- add two asserts and remove some code?
I'll PR that separately and compare.

**Pull request closed without merging**
