### PR TITLE
[jit] Fix the prev_bb quick lookup in mono_merge_basic_blocks().

### PR DESCRIPTION
**Pull request by vkargov**
This PR is meant to fix the prev_bb quick lookup from mono_merge_basic_blocks(). For some reason it always tried the first predecessor instead of iterating through all of them.

### CODE REVIEW

**Comment by kumpera** [comment]
How do I test this change?

Why nothing breaks with the existing code?

**Comment by kumpera** [comment]
LGTM

**Comment by vargaz** [comment]
This broke llvm:
./mono --llvm hello.exe

* Assertion at branch-opts.c:977, condition `bb->out_count == 1 && bbn->in_count == 1 && bb->out_bb [0] == bbn && bbn->in_bb [0] == bb' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at System.IO.FileStream..ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool,System.IO.FileOptions) <0x00210>

**Comment by vkargov** [comment]
Sorry about that!
Could you please specify what branch/revision of Mono and LLVM you were using? I just tried it on the last month's mono+ llvm master and didn't hit that assertion. I then tried the fresh mono master and it did crash, but for some other reason.

**Comment by vargaz** [comment]
Fixed it in 38983b6b1bfddaad132f9defea168e810f537e98. The commit was ok.

**Pull request merged**
