### PR TITLE
Bump msbuild to track xplat-master

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
hm build aborted for some reason?

@monojenkins build OS X Extended

**Comment by radical** [comment]
```
10:06:22 CSC     [net_4_x-macos] net_4_x_corlib_test.dll
10:33:04 Scheduled restart of the build (up to 1 times).
10:33:04 Build timed out (after 420 minutes). Marking the build as aborted.
10:33:04 make: *** [do-run-test] Terminated: 15
10:33:04 make[1]: *** [../../class/lib/net_4_x/tests/net_4_x_corlib_test.dll] Terminated: 15
10:33:04 Build was aborted
```

**Comment by marek-safar** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Multiple runtime crashes in the logs. But all the msbuild tests passed. Can we merge this @akoeplinger? Um though maybe pop off that top debug commit. I'm not pushing so that you can verify the results.

**Comment by akoeplinger** [comment]
The runtime test failures in the LLVM-based BCL tests are expected, see https://github.com/mono/mono/issues/9198.

I think we can keep the debugging commit, it can't hurt :)

**Pull request merged**
