### PR TITLE
Fix warnings.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Wonky build failures in wasm and windows.
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Pull request merged**
