### PR TITLE
Detect additional invalid assembly names when parsing

### LINKED ISSUE #15021: [netcore] Make System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid Pass
The test currently fails with:

```
System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid(assemblyName: "/a", exceptionType: typeof(System.IO.FileLoadException)) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.FileLoadException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid(String assemblyName, Type exceptionType)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid(assemblyName: "           ", exceptionType: typeof(System.IO.FileLoadException)) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.FileLoadException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid(String assemblyName, Type exceptionType)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid(assemblyName: "  \t \r \n ", exceptionType: typeof(System.IO.FileLoadException)) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.FileLoadException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.Ctor_String_Invalid(String assemblyName, Type exceptionType)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Find out why we're not throwing and make the test pass.

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes #15021

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 Coop Suspend

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 mcs

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 - prefix sanity checks

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
