### PR TITLE
Timezoneinfo rewrite

### PR DESCRIPTION
**Pull request by TautvydasZilys**
This PR replaces Mono implementation of TimeZoneInfo with a fusion of CoreCLR and CoreRT implementations. This enables it to work on Windows Store and Xbox One.

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hey, a few things upfront:

- please don't change referencesource code inline, it'll be a nightmare to merge upstream changes. Make your changes inside `#if MONO ... #else ... #endif` blocks
- you don't need to modify the .csproj, we have a bot that autogenerates it
- for win32native.cs which you replaced with referencesource please only ifdef in the parts that we actually use on Mono, it's easier to keep track that way

**Comment by marek-safar** [comment]
This is large change and it'd be easier to merge if you could split it up, e.g. the registry changes could be separate PR.

Any CoreRT changes should be done in our fork instead of copying files directly https://github.com/mono/corert. I'll add corert submodule to mono meantime.

**Comment by TautvydasZilys** [comment]
@marek-safar there aren't any CoreRT changes: I just took some code from CoreRT TimeZoneInfo implementation.

**Comment by TautvydasZilys** [comment]
I'll fix up the other things tomorrow.

**Comment by marek-safar** [comment]
CoreRT submodule has been added you can now fix you PR to reference sources from there

**Comment by TautvydasZilys** [comment]
I will fix up history once I'm done with all the changes and everyone's happy with the diff.

**Comment by TautvydasZilys** [comment]
I think I fixed all the mentioned issues - with the exception of history editing. I'll do that once everyone is happy with the diff.

You can see the changes I made to TimeZoneInfo.cs in respect to original CoreCLR implementation by diffing these:

https://raw.githubusercontent.com/dotnet/coreclr/0a3506ec958d920096e8f544d5b19100a5969e75/src/mscorlib/src/System/TimeZoneInfo.cs
https://raw.githubusercontent.com/Unity-Technologies/mono/7ea38ef45f904cbe4b5277fd33661cd349eeba06/mcs/class/corlib/System/TimeZoneInfo.cs

**Comment by ntherning** [comment]
@monojenkins build

**Comment by ntherning** [comment]
@TautvydasZilys It looks like this doesn't build against the current Mono HEAD. corlib fails to build with:

```
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/microsoft/win32/unsafenativemethods.cs(29,32): error CS0117: 'Win32Native' does not contain a definition for 'KERNEL32'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/microsoft/win32/unsafenativemethods.cs(33,32): error CS0117: 'Win32Native' does not contain a definition for 'KERNEL32'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/microsoft/win32/unsafenativemethods.cs(55,32): error CS0117: 'Win32Native' does not contain a definition for 'KERNEL32'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/microsoft/win32/unsafenativemethods.cs(71,32): error CS0117: 'Win32Native' does not contain a definition for 'USER32'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/microsoft/win32/unsafenativemethods.cs(75,32): error CS0117: 'Win32Native' does not contain a definition for 'KERNEL32'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/mcs/class/referencesource/mscorlib/microsoft/win32/unsafenativemethods.cs(79,32): error CS0117: 'Win32Native' does not contain a definition for 'KERNEL32'
```

Please look into it. I wanna help you get this one merged.

**Comment by TautvydasZilys** [comment]
Will do! Looks like I messed up with my finishing touches to win32native.

**Comment by ntherning** [comment]
@monojenkins approve

**Comment by ntherning** [comment]
monojenkins will now build this PR automatically whenever you push to it.

**Comment by TautvydasZilys** [comment]
The build succeeds now but there are some tests failing on your CI. I'm in the process of investigating the failures.

**Comment by marek-safar** [comment]
TimeZoneInfo has been merged to CoreRT so we can now use it instead of the file copy

**Comment by TautvydasZilys** [comment]
Looks like you're not taking this...

**Pull request closed without merging**
