### PR TITLE
[metadata] Fix crash related to custom attributes

### LINKED ISSUE #10737: Crash in QueryInterface in unmanaged code if object doesn't implement requested interface
If unmanaged code calls QueryInterface on a CCW and that doesn't implement the requested interface we get a SIGSEGV when trying to get the GuidAttribute.

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**:
5.12/5.14

This is  a regression from Mono 4.

### PR DESCRIPTION
**Pull request by ermshiperete**
Fixes #10737 

When a class doesn't contain the desired custom attribute we used
to return the last available attribute. This prevented
`cominterop_ccw_queryinterface()` to detect that the interface
isn't implemented and lead to a crash.

Change includes a unit test that demonstrates the problem.

Also renumber some of the return values of unit tests that were duplicated.

### CODE REVIEW

**Comment by marek-safar** [comment]
@lambdageek @kumpera could you please review this

**Comment by ermshiperete** [comment]
@kumpera Done. The line damage slipped in when I  cherry-picked the change from a different branch, and I didn't notice it. Shame on me.

**Comment by luhenry** [comment]
@monojenkins squash

**Comment by luhenry** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
There is a related failure on the x64 coop lane:
```
#6  0x00007f6666c2142a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x000055c7fe4ef004 in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=0x55c7ff5ea9c0 "Assertion failure in thread 0x7f6667ce5740 due to: object.c:6696: Expected GC Unsafe mode but was in STATE_BLOCKING state\nLast 2 state transitions: (most recent first)\n[ABORT_BLOCKING] RUNNING -> RUNN"...) at mono-log-common.c:135
#8  0x000055c7fe50725e in monoeg_g_logstr (msg=<optimized out>, log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:117
#9  monoeg_g_logv_nofree (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=<optimized out>) at goutput.c:128
#10 0x000055c7fe507519 in monoeg_g_logv (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>, args=<optimized out>) at goutput.c:135
#11 0x000055c7fe5075b2 in monoeg_g_log (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=<optimized out>) at goutput.c:144
#12 0x000055c7fe502e9b in mono_fatal_with_history (msg=msg@entry=0x55c7fe5ceae0 "%s:%d: Expected GC Unsafe mode but was in %s state") at checked-build.c:348
#13 0x000055c7fe5031a9 in assert_gc_unsafe_mode (file=file@entry=0x55c7fe5597ef "object.c", lineno=lineno@entry=6696) at checked-build.c:394
#14 0x000055c7fe41d0f6 in mono_string_new_wtf8_len_checked (domain=0x55c7ff48fd10, text=0x7f6664bc70a1 "00000000-0000-0000-C000-000000000046", length=length@entry=36, error=error@entry=0x7ffea9d6ed30) at object.c:6696
#15 0x000055c7fe471a73 in load_cattr_value (image=image@entry=0x55c7ff4948a0, t=<optimized out>, out_obj=out_obj@entry=0x7ffea9d6eb88, p=<optimized out>, p@entry=0x7f6664bc70a0 "$00000000-0000-0000-C000-000000000046", boundp=boundp@entry=0x7f6664bc70c7 "\005\006\035\021\200\330\b\a\004\b\022\205\320\b\b\016", end=end@entry=0x7ffea9d6eb70, error=0x7ffea9d6ed30) at custom-attrs.c:388
#16 0x000055c7fe47279b in create_custom_attr (image=0x55c7ff4948a0, method=0x55c7ff4a1a58, data=<optimized out>, len=<optimized out>, error=error@entry=0x7ffea9d6ed30) at custom-attrs.c:862
#17 0x000055c7fe47554b in mono_custom_attrs_get_attr_checked (ainfo=ainfo@entry=0x55c7ff5e9300, attr_klass=<optimized out>, error=error@entry=0x7ffea9d6ed30) at custom-attrs.c:1985
#18 0x000055c7fe3ba84c in cominterop_class_guid (klass=<optimized out>, guid=guid@entry=0x7ffea9d6ede0 "\330\356\326\251\376\177") at cominterop.c:500
#19 0x000055c7fe3ba984 in cominterop_class_guid_equal (guid=guid@entry=0x7f6663d2b660 <IID_INotImplemented> "xV4\022", klass=<optimized out>) at cominterop.c:2457
#20 0x000055c7fe3bcdb0 in cominterop_ccw_queryinterface (ccwe=<optimized out>, riid=0x7f6663d2b660 <IID_INotImplemented> "xV4\022", ppv=0x7ffea9d6eed8) at cominterop.c:2535
#21 0x00007f6663b05815 in mono_test_cominterop_ccw_queryinterface (pUnk=<optimized out>) at libtest.c:7716
#22 0x00000000408e3aa1 in ?? ()
```

**Comment by lambdageek** [comment]
Good catch @lewurm.  @ermshiperete - I pushed some changes to COM to this PR that should fix the Linux x64 coop failure.  Make sure to pull before you do more work on this PR.

**Comment by luhenry** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by luhenry** [comment]
@lambdageek the failure on [OS X i386](https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/15613/testReport/junit/(root)/ResolveAssemblyReferenceTest/TestHintPath1/) looks suspicious, would you mind confirming if it's related?

**Comment by lewurm** [comment]
@monojenkins build failed

**Pull request merged**
