### PR TITLE
[2018-06] Replace mono_object_get_class with mono_object_class to avoid gc transitions.

### PR DESCRIPTION
**Pull request by lambdageek**
Backport #11077 to `2018-06`

### CODE REVIEW

**Comment by jaykrell** [comment]
Should we, maybe, revert “all”of this in master, and then combine the changes and put them back? I mean, to avoid the merge conflicts in backports? Or just manually port when they occur?

**Comment by lambdageek** [comment]
So the interesting thing that happened here is that 2018-06 had more instances of `mono_object_get_class` than master - I had to actively write some code.  So I suspect no matter what we do, we will have to manually intervene every now and then.

Fortunately since we're marking the symbols with "external only", we'll get compile problems in the backport PRs if there's anything missing.

**Comment by luhenry** [comment]
Why is that required in that branch?

**Comment by luhenry** [comment]
@lambdageek not even that, more that it's a release branch so backporting something to it carries quite some risk. Is the risk worth it in this case? If it's only a performance problem which is very limited in scope and impact, I would say it isn't, but I'll let you be the judge of that.

**Comment by lambdageek** [comment]
Good point.

Not worth it.

**Pull request closed without merging**
