### PR TITLE
[System] System.Net.* tests from corefx (+RemoteExecutorTestBase)

### PR DESCRIPTION
**Pull request by EgorBo**
WIP, this PR adds RemoteExecutorTestBase (lots of tests in corefx in different assemblies use it in order to spawn a process and execute code there. I ported it to mono preserving corefx behavior (it also redirects to RemoteExecutorConsoleApp.exe to executed a method provided via command line in the same format).

Also I am porting System.Net.* tests - more to come (already have more but lots of them have platform-specific files). Tests are added but mostly ignored (#) - they all compile but have lots of failures (I hope most of those failures will be fixed with the new-webstack PR by Martin).

Status (when all System.Net tests are uncommented):
**Total: 2382, Errors: 0, Failed: 301, Skipped: 10, Time: 81.175s**

### CODE REVIEW

**Comment by EgorBo** [comment]
@monojenkins build

**Comment by EgorBo** [comment]
Tests status (as of 12/16/2017): Total: 2382, Errors: 0, Failed: 317, Skipped: 10, Time: 80.341s

**Comment by marek-safar** [comment]
So we regressed 16 tests with Martin change?

**Comment by EgorBo** [comment]
@marek-safar I guess yes, the PR can be merged (all failing tests are ignored and can be safely uncommented to work with them later)

**Pull request merged**
