### PR TITLE
[marshal] Ensure marshal code emit the right indirect store when dealing with ref types.

### PR DESCRIPTION
**Pull request by kumpera**
The marshal code was using CEE_STIND_I for a lot of ref stores. This would not
generate a WB and is a heap corruption vector.

### CODE REVIEW

**Comment by kumpera** [comment]
@vargaz please review

**Comment by vargaz** [comment]
LGTM

**Comment by kumpera** [comment]
@monojenkins merge

**Comment by akoeplinger** [comment]
build

**Pull request merged**
