### PR TITLE
Fixes TimeZoneInfo.Local on Windows

### PR DESCRIPTION
**Pull request by AxlPr**
Fixes bug #11817. There is a problem with the build where Linux code is
compiled for the Windows build due to the LIBC flag being set.

### CODE REVIEW

**Comment by tritao** [comment]
Is this still a problem?

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by tritao** [comment]
approve

**Comment by lewurm** [comment]
@AxlPr can you rebase your changes?

**Comment by steveisok** [comment]
@marek-safar Can we close this PR?

**Comment by steveisok** [comment]
Closing this PR.  See https://github.com/mono/mono/wiki/Pull-Request-Guide#old-pull-request-policy for more info.

**Pull request closed without merging**
