### PR TITLE
[netcore] Convert netcore/Makefile.am to a normal makefile, get the configure variables from config.make.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
```
cd /home/vsts/work/1/s/mcs && make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='             netcore' CC='gcc' all-profiles
make[7]: *** No rule to make target 'all'.  Stop.
```

from the build on VSTS

**Comment by vargaz** [comment]
Did that work before ? Its a non-required lane.

**Comment by directhex** [comment]
It worked before, yes. It's the job ./scripts/ci/pipeline-netcore-runtime.yml which will be used to build artifacts for consumption by core-setup

**Comment by directhex** [comment]
```
nuget pack runtime.nuspec -properties VERSION=\;RID=linux-x64\;PLATFORM_AOT_SUFFIX=.so\;COREARCH=x64
Attempting to build package from 'runtime.nuspec'.
Value cannot be null or an empty string.
Parameter name: value
```

Looks like the version parameter isn't getting filled in? That comes from the AC_INIT line (i.e. it populates `@VERSION@` in .am files, or `$VERSION` within configure.ac - I'd like to push in something like https://github.com/mono/mono/pull/14011 though, to get 4-part version numbers instead of 3.

**Comment by directhex** [comment]
Oh, you force-pushed while I was writing my message :sweat_smile:

**Comment by directhex** [comment]
OK, that passed. Do you want an immediate merge? Other lanes aren't really relevant or affected

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
