### PR TITLE
[ci] Skip jenkins lanes for PRs which only contain changes to the netcore/ subdir.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Was tested on this lane:
https://github.com/mono/mono/pull/15978

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
Can we do the same for the `eng` directory (ie. Maestro version updates)?

**Comment by akoeplinger** [comment]
@filipnavara we're just about to start consuming Roslyn via arcade (https://github.com/mono/mono/pull/15944) so I don't think we can do that...

**Pull request merged**
