### PR TITLE
Remove static from mingw tools.

### PR DESCRIPTION
**Pull request by jaykrell**
It doesn't work asis for me, or @MaximLipnin.

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build OS X WebAssembly

**Comment by jaykrell** [comment]
I this is required by some configuration, but for me it only breaks things, and sound weird.
Static linking is to be minimize for performance.
But dynamic linking does breed dll hell, granted.

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
For OSX, applying this change was the only way I could move forward.

**Comment by jaykrell** [comment]
Closing.

**Pull request closed without merging**
