### PR TITLE
[io-layer] Remove remaining pieces for cross-process mutex, semaphore and event

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by mfilippov** [comment]
@ludovic-henry this changes fixed: https://bugzilla.xamarin.com/show_bug.cgi?id=41914 ?

**Comment by ludovic-henry** [comment]
@mfilippov no these changes are not related to that bug, but I will take a look at it.

**Comment by ludovic-henry** [comment]
@mfilippov after verification, I can't reproduce your bug with these changes. I didn't investigate what's the root cause of your bug, so that might just be that the probability of hitting the bug is way lower. If you could confirm that you don't hit the crash anymore, that would be amazing.

**Comment by mfilippov** [comment]
@ludovic-henry Bug not reproduce on your changes, great thanks for fix. Whether these changes in the next SR release?

**Pull request merged**
