### PR TITLE
[System]: WebRequestStream now throws correct exception on cancellation.

### PR DESCRIPTION
**Pull request by baulig**
Fixes https://github.com/mono/mono/issues/7094.

### CODE REVIEW

**Comment by marek-safar** [comment]
@baulig could you also include the test as a nunit test in https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/Test/System.Net.Http/HttpClientTest.cs

**Comment by baulig** [comment]
No, there won't be any nunit test for this as it just wouldn't make any sense.  There are things that you just can't test with that kind of test.

**Comment by baulig** [comment]
Seach for `HttpClientTestType.CancelPost and CancelPostWhileWriting` in [here](https://github.com/xamarin/web-tests/blob/master/Xamarin.WebTests.Framework/Xamarin.WebTests.TestRunners/HttpClientTestRunner.cs)

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Pull request merged**
