### PR TITLE
Free or destroy, of any type, should do nothing, silently, given a null pointer.

### PR DESCRIPTION
**Pull request by jaykrell**
Remove excess null checks.

### CODE REVIEW

**Comment by akoeplinger** [comment]
doesn't this deviate from the original glib contract? or do we not care?

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
This goes against what was discussed in https://github.com/mono/mono/pull/8226, and this is just resubmitting in a different form what was already refused.

**Comment by jaykrell** [comment]
This is the approved subset. That one also skipped iteration, and in that one free & destory were both approved.

**Comment by jaykrell** [comment]
It doesn’t break assumptions that matter. It changes the interface slightly in a way that is reasonable to all callers & cleans things up a little.

**Comment by luhenry** [comment]
@jaykrell I disagree, it breaks a big assumption that matters: when passing an incorrect argument, it would previously break, and not it would just silently succeed. This is the same kind of problem where you print a warning instead of an assertion: it's most likely you are just going to ignore the error, and even more importantly, it might mask a bigger/worse bug. A not-so-old case that we hit in Mono: we would previously silently ignore any error returned from any `pthread_mutex_*` call, and when not silently ignoring these errors anymore, we discovered a whole set of bugs which we wouldn't previously hit (use-after-destroy, non-initialized, etc.).

Keeping the conditions of execution tight greatly help us in reasoning about the code, and what possible cases are possible. Your change break these assumptions and just make the code harder to follow in general.

**Comment by jaykrell** [comment]
@lambdageek's assertion here:
  https://github.com/mono/mono/pull/8226#issuecomment-381161580
is what this PR specifically does.

**Comment by kumpera** [comment]
NULL ignoring free/destroy is a common pattern in C. It does help a lot dealing with optional data. We gain nothing by forcing callees to check for those.

Worse than that, probably a lot of the callees are missing NULL checks because we never ran into the error condition that triggers it.

I don't think the comparison between pthread_* return values and ignoring NULLs is fair. In the former, we're in an unknown state, while the later we're just handling one valid form of input.

**Comment by jaykrell** [comment]
Good point about the potential missing null checks that this fixes/covers-up.
Overly strict assertion failures lying dormant, about harmless conditions.

**Pull request merged**
