### PR TITLE
Shutdown profiler before runtime since debugger profiler hooks make u…

### PR DESCRIPTION
**Pull request by joncham**
…se of current thread object

### CODE REVIEW

**Comment by joncham** [comment]
I was hitting an assert in `mono_thread_current` when the debugger agent handled the profiler shutdown event: https://github.com/mono/mono/blob/master/mono/mini/debugger-agent.c#L3795

**Comment by vargaz** [comment]
LGTM.

**Comment by alexrp** [comment]
Note that this is effectively a revert of 8e6b87f97ab115b7baeb81169839981aa2f8a205. Could you use `git revert` instead so that's clear?

**Comment by vargaz** [comment]
A possible problem is that this will cause the profiler to not report some events like assembly unload which happens during shutdown. Perhaps we should split mono_profiler_shutdown () into two parts, one which is called before shutdown, and the one which sets the event mask to 0.

**Comment by joncham** [comment]
I could look at splitting shutdown into two pieces, but I assume the important part is the call to `process_profiler_event (EVENT_KIND_VM_DEATH, mono_thread_current ());` which seems like it would need to occur after the assembly unload and thread exit events happening during runtime shutdown. But then this is the call that needs the thread object which is cleared during runtime shutdown...

**Comment by vargaz** [comment]
Probably the debugger needs to be fixed then to not require that object.

**Comment by vargaz** [comment]
Should be fixed by ee6c7cf06595f03f9ee3bda578f174f328135a85.

**Comment by joncham** [comment]
Thanks. Closing this then.

**Pull request closed without merging**
