### PR TITLE
[Mono.Debugger.Soft] Properly close connections 

### LINKED ISSUE #7377: [Mono.Debugger.Soft] Connections are not properly closed
For a Mono process with the soft debugger on, running on port 4567:

```csharp
static void Main(string[] args)
{
	var vm = VirtualMachineManager.Connect(new IPEndPoint(IPAddress.Loopback, 4567));
	vm.Detach();

	vm = VirtualMachineManager.Connect(new IPEndPoint(IPAddress.Loopback, 4567));
	vm.Detach();

	Console.ReadLine();
}
```

We're seeing two threads that are still running and waiting:

threads

Both threads are waiting on `Receive` with this stacktrace:

```
Not Flagged		21928	6	Worker Thread	SDB Receiver

System.dll!System.Net.Sockets.Socket.Receive
[Managed to Native Transition]	 
System.dll!System.Net.Sockets.Socket.Receive(byte[] buffer, int offset, int size, System.Net.Sockets.SocketFlags socketFlags)	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.TcpConnection.TransportReceive(byte[] buf, int buf_offset, int len)	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.Receive(byte[] buf, int buf_offset, int len)	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.ReadPacket()	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.ReceivePacket()	 
Mono.Debugger.Soft.dll!Mono.Debugger.Soft.Connection.receiver_thread_main()	 
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	 
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	 
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	 
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	 
mscorlib.dll!System.Threading.ThreadHelper.ThreadStart()	 
```

The way I look at it in `VirtualMachine.Detach`

```csharp
public void Detach () {
	conn.VM_Dispose ();
	conn.Close ();
	notify_vm_event (EventType.VMDisconnect, SuspendPolicy.None, 0, 0, null, 0);
}
```

VM_Dispose tells the debuggee that we're disposing, and then `Connection.Close` sets the `closed` flag to true. Nothing interrupts the `receiver_thread_main` loop which is waiting.

We've fixed it by switching the calls:

```csharp
conn.Close ()
conn.VM_Dispose()
```

This way we're setting the closed flag to true, sending and reading the reply to `VM_Dispose`, and exiting the `receiver_thread_main`.

@vargaz, what do you think?

### PR DESCRIPTION
**Pull request by thaystg**
Trying to unrevert https://github.com/mono/mono/pull/7390.
Couldn't reproduce the same side effect as that caused before.

This PR fixes #7377

### CODE REVIEW

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@vargaz , I discussed with @lambdageek, and we decided to try to "unrevert" the fix because I couldn't reproduce the side effect, do you agree with this?

**Comment by vargaz** [comment]
Sure, we can try it. As far as I remember, the issue was that the debugger thread somehow got restarted or something.

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by thaystg** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by thaystg** [comment]
@monojenkins backport 2019-06

**Pull request merged**
