### PR TITLE
[msbuild] Update to track upstream vs16.0 branch

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
Opened this and closing the earlier PR (https://github.com/mono/mono/pull/12502) as this should be ready now.

This is using bockbuild from https://github.com/mono/bockbuild/pull/85 and msbuild from https://github.com/mono/msbuild/tree/update-msbuild-16-tmp .
Both have been cleaned up. And once this PR can be merged, the other two need to be merged too.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Build was breaking for gtk-sharp:

```
mcs -out:WidgetViewer.exe -r:../../glib/glib-sharp.dll -r:../../pango/pango-sharp.dll -r:../../atk/atk-sharp.dll -r:../../gdk/gdk-sharp.dll -r:../../gtk/gtk-sharp.dll ./TestCheckButton.cs ./TestColorSelection.cs ./TestRadioButton.cs ./TestRange.cs ./TestStatusbar.cs ./TestDialog.cs ./TestFlipping.cs ./TestSizeGroup.cs ./TestCombo.cs ./TestComboBox.cs ./WidgetViewer.cs
./TestCombo.cs(17,14): warning CS0612: `Gtk.Combo' is obsolete
./TestRange.cs(35,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
@/external/bockbuild/stage/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
@/external/bockbuild/builds/gtk-sharp-None/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
./TestRange.cs(35,13): error CS0030: Cannot convert type `Gtk.HScale' to `System.Range'
./TestRange.cs(42,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
@/external/bockbuild/stage/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
@/external/bockbuild/builds/gtk-sharp-None/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
./TestRange.cs(42,13): error CS0030: Cannot convert type `Gtk.HScrollbar' to `System.Range'
./TestRange.cs(62,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
@/external/bockbuild/stage/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
@/external/bockbuild/builds/gtk-sharp-None/sample/test/../../gtk/gtk-sharp.dll (Location of the symbol related to previous error)
./TestRange.cs(62,13): error CS0030: Cannot convert type `Gtk.VScale' to `System.Range'
./TestCombo.cs(31,20): warning CS0612: `Gtk.Combo' is obsolete
Compilation failed: 6 error(s), 2 warnings
make[3]: *** [WidgetViewer.exe] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

This was based on mono's https://github.com/mono/mono/commit/66092e05712f6b44bd26f147db577f231626f400 which built fine on jenkins !? Rebasing to latest HEAD (https://github.com/mono/mono/commit/187711df20b96cce02458446f28891733610628e).

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
Mono runtime test failures like : https://gist.github.com/radical/5aa7a090ee7af254a0f50df13c898f9e

I can't reproduce it locally, so debugging on https://github.com/mono/mono/pull/13076 .
Rest of the build went fine, so the generated package can still be used for verification. But it doesn't seem to have triggered properly, so, I will do that again.

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@akoeplinger Any idea why the `os x package` build is not getting triggered? It's stuck like this on multiple PRs and I tried invoking it again too.

**Comment by akoeplinger** [comment]
It seems to be triggered now, I assume most bots were just busy.

**Comment by radical** [comment]
@alexischr The package was successfully generated - https://jenkins.mono-project.com/job/build-package-osx-mono-pullrequest/303/ . The symlinks are there. And I tested the package by building VSMac.

If this looks good to you too, then let me know and I will rebase the PR (https://github.com/mono/bockbuild/pull/85) and merge it.

**Comment by radical** [comment]
Just FYI, the package works but the extended build breaks but is being fixed in https://github.com/mono/mono/pull/13076 .

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Blocked on https://github.com/mono/mono/pull/13109 .

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
OSX builds are failing with:

```
18:04:33 [ 89%] Building C object CMakeFiles/mono-btls-shared.dir/btls-x509-chain.c.o
18:04:33 Scanning dependencies of target ssl
18:04:33 
@/external/bockbuild/builds/mono-x86/mono/btls/btls-ssl-ctx.c:324:29: error: incompatible pointer types passing 'SSL_CTX *' (aka 'struct ssl_ctx_st *') to parameter of type 'const SSL *' (aka 'const struct ssl_st *') [-Werror,-Wincompatible-pointer-types]
18:04:33  return SSL_get_servername (ptr->ctx, 0);
18:04:33                             ^~~~~~~~
18:04:33 @/external/bockbuild/builds/mono-x86/external/boringssl/include/openssl/ssl.h:2213:58: note: passing argument to parameter 'ssl' here
18:04:33                const char *SSL_get_servername(const SSL *ssl, const int type);
18:04:33                                                          ^
18:04:33 1 error generated.
18:04:33 [ 89%] Building C object boringssl/ssl/CMakeFiles/ssl.dir/custom_e
```

**Comment by radical** [comment]
AFAICS, this is the commit causing the issue - https://github.com/mono/mono/commit/7277e3bb5ee3dbec669ca70634291fcc186e25cc .
cc @baulig

**Comment by marek-safar** [comment]
@baulig could you please look into fixing the osx build

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
`OSX Extended`, `linux wasm`: everything passed, but it says that `msbuild-tests` are unstable.
`Windows x64 c++`: `RandomNumberGeneratorTest.Runs`
`linux aarch64 coop suspend`: `Test collection for System.Threading.ThreadPools.Tests.ThreadPoolTests.System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest`

**Comment by radical** [comment]
I'm testing the osx package now.

**Comment by radical** [comment]
@akoeplinger @marek-safar Could you please merge this?

**Pull request merged**
