### PR TITLE
[mini] Make sure mkbundle executables work if they are run from a path on the PATH environment variable.

### PR DESCRIPTION
**Pull request by ramin-zaghi**
This is a patch to enable mkbundle executable files to work when they are run from a path that is on the PATH environment variable.

Mono mini has a function probe_embedded() which looks for the program's file (using argv[0]). If the program is run from a path on the PATH environment variable then the open() fails and only a single parameter is sent to the mono_main() which in turn causes an "if" condition to print the help and exit.

This patch searches through the directories specified in the current environment's PATH variable and tries to open() then first file found.

### CODE REVIEW

**Comment by fredrikmarcus** [comment]
I had the same problem some weeks ago. I added an issue to https://bugzilla.xamarin.com/show_bug.cgi?id=60892
Looking at the patch I think it can end up in an unknown state if the file exist i current director and in path.
File in current directory will be probed, file in path will be run.

**Comment by luhenry** [comment]
@monojenkins build

**Comment by ramin-zaghi** [comment]
Hi @fredrikmarcus 

> Looking at the patch I think it can end up in an unknown state
> if the file exist i current director and in path.
> File in current directory will be probed, file in path will be run.

How do you suggest we fix that?
I can check for a "./" in the command line for example (not sure what is best on Windows) or somehow compare the content of the current executable's image with the matched file.
Any suggestions?
The other option might be checking if there are multiple files and just refusing to run until the user clarifies which one with a command line argument.

**Comment by fredrikmarcus** [comment]
Hi @ramin-zaghi 

Looking at the original code, I think must cases (or all) are already covered for windows.
I don't know if you have looked at the patch file attached in the bug-link. But I only added fixes within the ifdef at end of file. (And 1 define)
Just like in the windows ifdef, I altered the code so argv[0] is not the parameter sent to probe_embedded. Instead full path is sent to probe_embedded.
So my suggestion would be to move the directory finding out from probe_embedded into the ifdef, sending full file path to function.
Does this make sense?

**Comment by ramin-zaghi** [comment]
Hi

So yes I did look at your patch but I have not tested getauxval() on different platforms to know exactly how it works.

Just so I am clear, are you saying
1- We can ignore Windows because this is not an issue in the original code anyway.
2- Your patch does work on both Windows and POSIX platforms (assuming we are still using glibc which has getauxval() on cygwin too)

If I misunderstood anything please clarify.

Thanks

**Comment by fredrikmarcus** [comment]
Hi

From the windows people at work I have not heard they have a problem. I'm only linux (ubuntu) user I have the problem. That's why I think windows is working.
Also in the windows part of the file the code of finding the file before calling probe_embedded is more complex that the linux code. That's also an indicator for me that the windows part is better tested.

My patch is only tested on linux because only linux part of the file is changed. I can see if I can get a windows person to test it tomorrow.
Also, I did not create a pull request of my own because I'm very new to this community and very unsure of the POSIX compatibility.
So I think your code is more compatible, but should be move to give the full path to probe_embedded in linux ifdef.
Moving it into the ifdef, I think it can be more easy to cover the ./ case also.

**Comment by luhenry** [comment]
Hi @ramin-zaghi and @fredrikmarcus , thank you very much for your contributions. If the issue doesn't arise on win32, would it be ok for you to have the added code block between `#if !HOST_WIN32`, so it would only be compiled on non-win32 platforms?

**Comment by ramin-zaghi** [comment]
Ok, I will move this out of the Windows builds.

**Comment by luhenry** [comment]
build

**Comment by ramin-zaghi** [comment]
Hi Ludovic
I see you sent the change, built and already commited.
I was stuck looking at the build+test results and there seemed to be a few failed builds and failed tests.

I am new on this project. Can you explain what kind of results are expected for a patch like this please?

**Comment by ramin-zaghi** [comment]
And has this now been merged or do you have to wait for the results of your "build" message? I am assuming this is automatically merged if the build results are all green, right?

**Comment by luhenry** [comment]
@monojenkins build OS X x64

**Comment by luhenry** [comment]
@monojenkins build Windows i386

**Comment by luhenry** [comment]
@monojenkins build Windows x64

**Comment by luhenry** [comment]
@ramin-zaghi not all the status check have to be green to be merged and it's not automatic - I check it regularly and merge it accordingly. Our CI is pretty brittle at times, so we expect most of them to be green, even if some of the targets are still red for unrelated reasons.

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT

**Comment by luhenry** [comment]
whitelist

**Comment by luhenry** [comment]
build

**Pull request merged**
