### PR TITLE
[llvm] Fix passing vtypes received by value as arguments, they need to be copied

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/11378

### CODE REVIEW

**Comment by marek-safar** [comment]
@vargaz this looks like something worth backporting

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins backport 2018-10

**Comment by lewurm** [comment]
@monojenkins backport 2018-08

**Pull request merged**
