### PR TITLE
Prevent failed look ups by not swapping tables until copy is performed

### PR DESCRIPTION
**Pull request by nealef**
Fixes #30551.

### CODE REVIEW

**Comment by alexrp** [comment]
There's some bad indentation in the patch.

**Comment by nealef** [comment]
Fixed indentation.

**Comment by kumpera** [comment]
This change is for mono-hash, which doesn't support unsynchronized access to it.

How are he hitting this in the first place?

**Comment by nealef** [comment]
One thread is adding to the hash, it triggers the rehash process, another thread is doing a lookup in the table. If do_rehash is running and the table is being copied then the hash->table value retrieved for the lookup is the new table which is only partially copied. The lookup was coming from mono_reflection_lookup_dynamic_token. I added messages to both rehash and lookup and verified that this is happening. I also added code to mono_reflection_lookup_dynamic_token to (a) dump the content of the table and (b) retry the operation. The retry would always work. A client runs a 12 hour long test suite that crashed every time. After adding this patch the test suite continues past the point of failure. Here's some debug messages that show the start of the rehash process, the dump of the table when the lookup fails, and the rehash complete message after the table is copied:

do_rehash:199 Rehashing 0x2a97d60 - in_use: 2446 threshold: 0 old_size: 823                
image: __MetadataTypes assembly: __MetadataTypes module: __MetadataTypesModule version: v4.0.30319 guid: ??? <-- lookup has failed
key: 0x5 value: (nil) hash: 0x00625170 <-- dump table contents via foreach
                  :
key: 0x29 value: (nil) hash: 0x00625170
key: 0x2000065 value: 0x7fa740f7c238 hash: 0x00625170
key: 0x2000066 value: 0x7fa740f7c9f8 hash: 0x00625170
                   :
                   :
key: 0x200007d value: 0x7fa719bc5f48 hash: 0x00625170                
do_rehash:220 Rehashed 0x2a97d60 - in_use: 2446 threshold: 0 new_size: 2777 <-- rehash complete/table copied

**Comment by vargaz** [comment]
The mono-hash code was never intended to be thread safe, the particular non-safe access to assembly->tokens was fixed in 54e8010aadb4fe69d216a5835c7b01f6187f745e.

**Comment by kumpera** [comment]
Closing this PR as a better fix was applied.

**Pull request closed without merging**
