### PR TITLE
Bump roslyn to 2.3 beta 2

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by nealef** [comment]
Any sign of big ending support in this one?

**Comment by marek-safar** [comment]
@nealef no, roslyn team still made no progress on updating corefx dependencies

**Comment by nealef** [comment]
Interestingly the symptoms have changed since this was pushed. I am not getting the Little Endian Message anymore but it appears to be hanging forever within System.Threading.Tasks.Task:RunSynchronously – the last method I see it leave is System.Threading.ManualResetEventSlim:set_Waiters which had been invoked by System.Threading.ManualResetEventSlim:Wait. It may not be getting to the endian check yet so something else appears to be happening.

**Comment by nealef** [comment]
Just for completeness:

Microsoft (R) Visual C# Compiler version 2.3.0.61801 (3722bb71)
Copyright (C) Microsoft Corporation. All rights reserved.

**Pull request merged**
