### PR TITLE
[configure.ac] Do not always enable ninja

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by jaykrell** [comment]
I do have ninja installed btw (brew install ninja).
Ninja is kinda everyone's favorate cmake generator. It is the fastest.

**Comment by luhenry** [comment]
@vargaz it breaks on certain systems.

**Comment by jaykrell** [comment]
Yes this seem to be helping me.

**Comment by jaykrell** [comment]
I'm guessing I should mv /usr/local/bin/ninja /usr/bin.

**Comment by vargaz** [comment]
Apparently, cmake 3.10 has trouble locating the ninja executable even through its in the PATH.

**Comment by vargaz** [comment]
We should probably just disable ninja altogether until this can be fixed.

**Comment by vargaz** [comment]
This is caused by:
https://github.com/mono/boringssl/blob/mono/util/android-cmake/android.toolchain.cmake#L1529
which seems to disable searching the PATH for executables.

**Pull request merged**
