### PR TITLE
[2018-02] Add pipeline to convert managed exception into telemetry format 

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins build deb with tarball

**Comment by alexanderkyte** [comment]
https://github.com/mono/mono/pull/10133

**Comment by alexanderkyte** [comment]
@monojenkins build Failed

**Comment by alexanderkyte** [comment]
Windows builds taking a while to retry

**Comment by alexanderkyte** [comment]
@monojenkins build Failed

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
@luhenry I still need a review for this backport

**Comment by marek-safar** [comment]
Why do you need it in closed branch?

**Comment by alexanderkyte** [comment]
I was asked to have this backported to 2018-02 by VS4M. Maybe @slluis and @sgmunn can clarify a bit.

**Pull request merged**
