### PR TITLE
[2019-02] [monodroid] Introduce 'win32 host' BCL build

### PR DESCRIPTION
**Pull request by alexischr**
Backport of https://github.com/mono/mono/pull/14424

cc @lambdageek

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by alexischr** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by alexischr** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by alexischr** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Pull request merged**
