### PR TITLE
[github] add note about env in issue template

### PR DESCRIPTION
**Pull request by lewurm**
would have been helpful for https://github.com/mono/mono/issues/6205

### CODE REVIEW

**Comment by akoeplinger** [comment]
hmm, I'm not convinced we need this for each an every issue (it'll bloat the issue a lot), if we suspect an environment related problem we can just ask for the `env` details?

**Comment by marek-safar** [comment]
I agree that having this information on every Mono issue is counterproductive

**Comment by lewurm** [comment]
I agree, that's too verbose. maybe we should have a document that collects tips & tricks for debugging issues. I'm sure the next time I'm gonna forget about it 🙂

**Comment by marek-safar** [comment]
Yeah, I am certainly more in favour of wiki page about tips for debugging

**Pull request closed without merging**
