### PR TITLE
Bump msbuild to track xplat-master

### PR DESCRIPTION
**Pull request by radical**
Pickup the fix for https://github.com/mono/mono/issues/8495

### CODE REVIEW

**Comment by marek-safar** [comment]
Please update also 2018-06 branch

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Unrelated test failures:
```
MonoTests.test-sgen-regular-ms-conc-simple.sgen-new-threads-dont-join-stw.exe_timedout
MonoTests.test-sgen-regular-ms-conc-simple.sgen-new-threads-dont-join-stw-2.exe_timedout
MonoTests.test-sgen-regular-ms-simple.sgen-new-threads-dont-join-stw.exe_timedout
MonoTests.test-sgen-regular-ms-simple.sgen-new-threads-dont-join-stw-2.exe_timedout
MonoTests.runtime.bug-60862.exe
```

Interestingly, when I download the `msbuild-test-results.zip` from https://jenkins.mono-project.com/job/test-mono-pull-request-mac-sdk/79/Azure/ , Chrome blocks it claiming "may be dangerous"!
@akoeplinger any ideas?

**Comment by akoeplinger** [comment]
> Chrome blocks it claiming "may be dangerous"!

Yeah that's interesting, but if you click "Show all" to open the Chrome Download page there's an option to keep the file.

**Pull request merged**
