### PR TITLE
Revert linker change of 5a65a97

### PR DESCRIPTION
**Pull request by fanyang-mono**

### CODE REVIEW

**Comment by vargaz** [comment]
This is needed because  the required='false' field in
```
<type fullname="System.Reflection.Emit.TypeBuilder" required='false' preserve="fields" feature="sre">
			<method name="SetCharSet" feature="sre" />
			<!-- reflection.c mono_reflection_call_is_assignable_to () -->
			<method name="IsAssignableTo" feature="sre" />
```
Fails to preserve the IsAssignableTo method.

**Comment by fanyang-mono** [comment]
@monojenkins backport 2020-02

**Comment by lambdageek** [comment]
Is there a bug report open in mono/linker?

**Comment by vargaz** [comment]
https://github.com/mono/linker/issues/965

**Comment by jaykrell** [comment]
Title should mention linker?

**Comment by steveisok** [comment]
@monojenkins build failed

**Pull request merged**
