### PR TITLE
[jit] Add support for widening of Array.UnsafeMov intrisic. Fixes #35310

### PR DESCRIPTION
**Pull request by kumpera**
This enables usage of JitHelper.UnsafeEnumCast<> with enums smaller than int.

### CODE REVIEW

**Comment by kumpera** [comment]
Hey Zoltan, could you review this one?

**Comment by kumpera** [comment]
I force pushed this on my end, so Zoltan's comments were lost. :/

**Comment by akoeplinger** [comment]
That happens when you don't comment on the "files changed" tab :smile: comments are still available on the earlier commit itself: https://github.com/kumpera/mono/commit/abb6316206bfccfe6a68c9033dd40e829fd523f3#commitcomment-14292996

**Comment by kumpera** [comment]
The problem is that the files change tab is worthless if you have a PR made out of multiple commits and you are reviewing each one of them.

**Comment by akoeplinger** [comment]
Yeah, fully agree. GitHub lacks in this regards...

**Pull request merged**
