### PR TITLE
Enable disabled DIM test

### PR DESCRIPTION
**Pull request by kg**
cc @marek-safar are there other DIM tests that are still disabled? I couldn't find any

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@kg there were more added by @thaystg but I think they are all enabled. The remaining disabled ones are in Roslyn acceptance tests

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@lambdageek @thaystg the test is still failing for AOT

**Comment by lewing** [comment]
@thaystg what is the status here?

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
We still have a problem on AOT, and I didn't have time to investigate.

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
Locally on OSX with 709ba3faa52f5881ebd4cada2488b86a2b169960, if I do this the test passes:

```
./autogen.sh --enable-checked-build-mode=all --disable-btls --disable-btls-lib --disable-nls  --with-runtime-preset=fullaot
make -j12
make -C mono/tests test
MONO_PATH=mcs/class/lib/testing_aot_full runtime/mono-wrapper mono/tests/dim-cons
trainedcall.exe
```
And prints:
```
Constrained calls that require runtime lookup are OK
Runtime supports lookups with runtime determined boxing
Compile time constraint resolution to default interface method OK
```

Will try on Linux, too.

**Comment by lambdageek** [comment]
Stack trace:
```
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffffffffffd0)
  * frame #0: 0x0000000100695d87 dim-constrainedcall.exe.dylib`IAdder_1_T_REF_PlusPlus(this=0x00007ffeefbfeeb8) + 71
    frame #1: 0x0000000100696161 dim-constrainedcall.exe.dylib`_Module_Check_T_INST_U_REF_T_INST(t=0) + 49
    frame #2: 0x0000000100695c82 dim-constrainedcall.exe.dylib`_Module_Main + 194
    frame #3: 0x0000000103c83a12 mscorlib.dll.dylib`wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 290
    frame #4: 0x00000001000105ca mono`mono_jit_runtime_invoke(method=<unavailable>, obj=<unavailable>, params=0x00007ffeefbff208, exc=0x0000000000000000, error=<unavailable>) at mini-runtime.c:3152 [opt]
    frame #5: 0x0000000100212868 mono`mono_runtime_invoke_checked [inlined] do_runtime_invoke(method=0x0000000100709e68, obj=0x0000000000000000, params=0x00007ffeefbff208, exc=<unavailable>, error=0x00007ffeefbff248) at object.c:3016 [opt]
    frame #6: 0x0000000100212832 mono`mono_runtime_invoke_checked(method=0x0000000100709e68, obj=0x0000000000000000, params=0x00007ffeefbff208, error=0x00007ffeefbff248) at object.c:3184 [opt]
    frame #7: 0x0000000100218d7e mono`mono_runtime_exec_main_checked at object.c:5118 [opt]
    frame #8: 0x0000000100218d4a mono`mono_runtime_exec_main_checked(method=0x0000000100709e68, args=<unavailable>, error=0x00007ffeefbff248) at object.c:5221 [opt]
    frame #9: 0x000000010006c90d mono`mono_jit_exec at driver.c:1322 [opt]
    frame #10: 0x000000010006c8ff mono`mono_jit_exec(domain=<unavailable>, assembly=<unavailable>, argc=1, argv=0x00007ffeefbff5c0) at driver.c:1267 [opt]
    frame #11: 0x000000010006f994 mono`mono_main [inlined] main_thread_handler at driver.c:1404 [opt]
    frame #12: 0x000000010006f95a mono`mono_main(argc=3, argv=<unavailable>) at driver.c:2622 [opt]
    frame #13: 0x0000000100000a0a mono`main [inlined] mono_main_with_options(argc=<unavailable>, argv=<unavailable>) at main.c:50 [opt]
    frame #14: 0x00000001000009f6 mono`main(argc=3, argv=<unavailable>) at main.c:410 [opt]
    frame #15: 0x00007fff7d8bf3d5 libdyld.dylib`start + 1
```

**Comment by lambdageek** [comment]
Superseded by #15729 (master) and #15730 (2019-06) which re-enable the test and also fix the AOT issue.

**Pull request closed without merging**
