### PR TITLE
[tests] Remove flaky AsyncLocalCapture test

### PR DESCRIPTION
**Pull request by alexischr**

### CODE REVIEW

**Comment by vargaz** [comment]
We should report a bug for it, and just disable it, not remove it, unless the test is completely wrong.

**Comment by marek-safar** [comment]
I agree the timeout looks low, could not we first bump it to e.g. 10000 before removing the test?

**Comment by akoeplinger** [comment]
@luhenry here are some of the failures:

```
                                                MESSAGE:
                                                  cw_wait
  Expected: True
  But was:  False

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                  at MonoTests.System.Threading.ThreadPoolTests.AsyncLocalCapture () [0x000a3] in D:\j\workspace\z\label\w64\mcs\class\corlib\Test\System.Threading\ThreadPoolTest.cs:250 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in D:\j\workspace\z\label\w64\mcs\class\corlib\System.Reflection\MonoMethod.cs:305 

--

                                                MESSAGE:
                                                  var_3
  Expected: 0
  But was:  99

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                  at MonoTests.System.Threading.ThreadPoolTests.AsyncLocalCapture () [0x000f0] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/corlib/Test/System.Threading/ThreadPoolTest.cs:255 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 

--

                                                MESSAGE:
                                                  var_2
  Expected: 1
  But was:  99

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                  at MonoTests.System.Threading.ThreadPoolTests.AsyncLocalCapture () [0x000df] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/corlib/Test/System.Threading/ThreadPoolTest.cs:254 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/builder/jenkins/workspace/test-mono-mainline/label/osx-i386/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 

--



```

**Comment by vargaz** [comment]
I get different failures when running on the ios simulator:

exception inside UnhandledException handler: Object reference not set to an instance of an object

exception inside UnhandledException handler: Object reference not set to an instance of an object

exception inside UnhandledException handler: Object reference not set to an instance of an object

exception inside UnhandledException handler: Object reference not set to an instance of an object

exception inside UnhandledException handler: Object reference not set to an instance of an object

exception inside UnhandledException handler: Object reference not set to an instance of an object

2017-11-24 12:25:52.736 test-corlib[55223:2024140] Unhandled managed exception:
Invalid attempt made to decrement the event's count below zero. (System.InvalidOperationException)
  at System.Threading.CountdownEvent.Signal () [0x0001b] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at MonoTests.System.Threading.ThreadPoolTests+<>c__DisplayClass18_0.<AsyncLocalCapture>b__3 (System.Object state, System.Boolean to) [0x00011] in <3f563485594a4bff8f4184e0602768ba>:0 
  at System.Threading.RegisteredWaitHandle.DoCallBack (System.Object timedOut) [0x00008] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x0001c] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
2017-11-24 12:25:52.736 test-corlib[55223:2023936] Unhandled managed exception:
Invalid attempt made to decrement the event's count below zero. (System.InvalidOperationException)
  at System.Threading.CountdownEvent.Signal () [0x0001b] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at MonoTests.System.Threading.ThreadPoolTests+<>c__DisplayClass18_0.<AsyncLocalCapture>b__2 (System.Object state, System.Boolean to) [0x00011] in <3f563485594a4bff8f4184e0602768ba>:0 
  at System.Threading.RegisteredWaitHandle.DoCallBack (System.Object timedOut) [0x00008] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <2dfd2afa17844a5f9f0083dd285821d6>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x0001c] in <2dfd2afa17844a5f9f0083dd285821d6>:0

**Comment by akoeplinger** [comment]
https://github.com/mono/mono/pull/6099 should be the real fix

**Pull request closed without merging**
