### PR TITLE
[threads] Use MonoOSEvent for Thread.Suspend/Resume

### PR DESCRIPTION
**Pull request by ludovic-henry**
By using a MonoOSEvent we avoid relying on the utils/threads suspend
mechanism to suspend a metadata/threads. This reduce coupling between both
mechanism, and that would allow us to remove a bunch of code from
utils/threads when switching to coop.

This only works with coop suspend, as we need the ability to return from an
async call, and that's not possible with preemptive suspend.

### CODE REVIEW

**Comment by JustArchi** [comment]
It looks like clean process exit via ```Environment.Exit()``` is no longer possible after this commit, due to SIGABRT on each exit.

Take a look if you'd like to: http://hastebin.com/daqatiwibu.vbs

**Comment by nealef** [comment]
There are a number of issues with Environment.Exit() that we+IBk-ve encountered:

https://bugzilla.xamarin.com/show+AF8-bug.cgi?id+AD0-33020

It looks like clean process exit via Environment.Exit() is no longer possible after this commit, due to SIGABRT on each exit.

Take a look if you'd like to: http://hastebin.com/daqatiwibu.vbs

**Comment by ludovic-henry** [comment]
@JustArchi which platform are you on? And do you explicitly enable cooperative GC suspend? Also, could you please provide us with a repro so we can look into it more easily? Thank you!

**Comment by JustArchi** [comment]
I'm on Linux, running Mono compiled ```--with-cooperative-gc=yes```, I'll try to make some repro if you need it and post on bugzilla. I thought I'm not alone with this 😄

**Comment by JustArchi** [comment]
@ludovic-henry Done, please take a look at https://bugzilla.xamarin.com/show_bug.cgi?id=46536

**Pull request merged**
