### PR TITLE
[wasm][sdk] Fix warning NU1604, does not contain an inclusive lower b…

### PR DESCRIPTION
**Pull request by kjpou1**
…ound

- Set explicit version in `Sdk.props`

### CODE REVIEW

**Comment by kg** [comment]
Are we sure setting an explicit version isn't what we want, regardless of warning? It's not clear to me

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@kg comments addressed in recent commit.

**Comment by kjpou1** [comment]
@monojenkins build failed

**Pull request merged**
