### PR TITLE
Add Windows x64 Full AOT Interpreter support on CI.

### PR DESCRIPTION
**Pull request by lateralusX**
Add support to run full interpreter test suite on CI for Windows x64 Full AOT. Since Windows x64 Full AOT uses a different full AOT profile WinAOT a separate testing profile was setup for the interpreter testing on Windows Full AOT. NOTE, this profile is for testing, inline with the other testing profiles. It is also reusing most of its sources from other sources files (mainly WinAOT) to reduce maintenance of the profile.

Commit also includes some smaller adjustments needed in order to get full pass rate for Windows x64 Full AOT + Interpreter on CI.

Commit fixes a recent problem with WinAOT profile getting Unix versions of CoreFx sources included. That problem didn't show up on tests, but issued warning in logs due to missing icalls (Unix specific) in runtime build.

### CODE REVIEW

**Comment by lewurm** [comment]
looks good to me, but I would like to have it stamped by someone of the BCL team.

**Comment by lambdageek** [comment]
@alexischr I think the .sources changes are similar to what you had to do for the win32 monodroid profile, could you look over the work here.

**Comment by lateralusX** [comment]
@monojenkins commit csproj

**Comment by lateralusX** [comment]
@monojenkins rebuild failed

**Comment by lateralusX** [comment]
@monojenkins rebuild failed

**Pull request merged**
