### PR TITLE
Use /mnt/scratch for Android SDK, to match https://github.com/xamarin/xamarin-android/pull/3125

### PR DESCRIPTION
**Pull request by directhex**
Ought to cause fewer failures during archive job.

### CODE REVIEW

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
Bear in mind we don't CI what this changes - there's no CI lane for "do the same thing as the SDK archive job"

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-06

**Comment by directhex** [comment]
`13:52:41  2019-06-28 17:52:41 URL:https://dl.google.com/android/repository/cmake-3.6.4111459-linux-x86_64.zip [13980243/13980243] -> "/home/builder/android-archives/cmake-3.6.4111459-linux-x86_64.zip" [1]`

That means it didn't work properly, since it's not using `AndroidToolchainCacheDirectory`

**Pull request merged**
