### PR TITLE
sockets: Add C types so that `mono_class_get_field_from_name_full` can be avoided.

### PR DESCRIPTION
**Pull request by jaykrell**
which is inefficient and uses of it have to be careful to on-demand initialize w/o race (or be slower).

This is extracted from https://github.com/mono/mono/pull/17978.
Part of this is now in https://github.com/mono/corefx/pull/377.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Agreed to first two, torn on the last, because of the possible goal of compiling of both configurations in one.

Also, while I agree and will comment about keep in sync, the larger PR might do a runtime check also, like under verify..so much for #if-removal.

**Comment by lambdageek** [comment]
`#if` removal is not a goal.

**Comment by jaykrell** [comment]
Configuration explosion should be imho.
Increased coverage from fewer builds should be imho.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Something is wrong with IPAddress actually. I haven't figured out what yet.

**Comment by akoeplinger** [comment]
The mono/mono repository is focused on stability and limiting code churn now so I don't think this change is worth doing here. If you think the change is important please reopen it in dotnet/runtime, thank you!

**Pull request closed without merging**
