### PR TITLE
[merp] Output native library module name when 'whitelist all' mode is…

### PR DESCRIPTION
**Pull request by alexischr**
… enabled

Partially fixes https://github.com/mono/mono/issues/16689

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by marek-safar** [comment]
@lambdageek could you please reivew

**Comment by alexischr** [comment]
@monojenkins backport to 2019-08

**Comment by alexischr** [comment]
@monojenkins build failed

**Pull request merged**
