### PR TITLE
config.in: fixing wrong MonoPosixHelper location

### PR DESCRIPTION
**Pull request by angeloc**
FIxing a typo in MonoPosixHelper location.

### CODE REVIEW

**Comment by tritao** [comment]
build

**Comment by lewurm** [comment]
that's not a typo.   what problem does that fix?

**Comment by cmp-** [comment]
I build in Cygwin and that line gets copied 1:1 into the final config file (not sure if that's intended) crashing Mono unless removed.

**Comment by lewurm** [comment]
That's intended. https://github.com/mono/mono/blob/master/mono/metadata/mono-config.c#L281 replaces `$mono_libdir` with the correct value;  maybe not on cygwin.  can you post the crash?

**Comment by cmp-** [comment]
Looks like I was mistaken, it seems to work just fine. Last time I tried was several months ago, though.

**Comment by angeloc** [comment]
Without this fix, /etc/mono/config reports:

`<dllmap dll="MonoPosixHelper" target="/home/userX/buildroot/output/host/usr/lib/libMonoPosixHelper.so" os="!windows" />`

With a crosscompiled build from Buildroot.

With this fix that becomes:

`<dllmap dll="MonoPosixHelper" target="libMonoPosixHelper.so" os="!windows" />`

And my application stopped crashing.

**Comment by alexrp** [comment]
This sounds like we're somehow leaking the `$mono_libdir` variable used throughout the build system into the generated `config` file. That's pretty insanely broken if that's actually the case.

@angeloc could you try adjusting Mono to replace, say, `$mono_testlibdir` instead of `$mono_libdir` in `mono-config.c` and also modify `config.in` to use that variable, and see if that fixes it?

**Comment by angeloc** [comment]
@alexrp : As far as I can tell, this is not un unknown problem, it was reported here:

https://bugzilla.xamarin.com/show_bug.cgi?id=24131

Regarding `$mono_testlibdir` I'll try it as soon aspossible.

**Comment by akoeplinger** [comment]
@angeloc The bug report you linked shouldn't apply anymore since we changed the lookup of the path from compile time to runtime in https://github.com/mono/mono/pull/1937.

**Comment by angeloc** [comment]
@akoeplinger : For the signalled bug, ok, it shouldn't apply.

In my case, it applies and produces what described at a previous comment.

**Comment by angeloc** [comment]
Sorry for the noise, my problem was with 4.2.2.30, seems now fixed.

**Pull request closed without merging**
