### PR TITLE
Clean up some C symbols polluting the global namespace

### PR DESCRIPTION
**Pull request by alexrp**
For reference, these were obtained with:

    nm -D --defined-only libmonosgen-2.0.so | cut -d ' ' -f 3 | grep -v '^eg_\|mono_\|monoeg_\|wapi_\|ves_icall_\|sgen_\|mini_.*$'

There are still some functions and variables here and there, but this takes care of the major offenders.

### CODE REVIEW

**Comment by tritao** [comment]
LGTM

**Comment by alexrp** [comment]
@schani is the binary protocol symbol rename going to interfere with #1648? If so, we can wait with merging this.

**Comment by kumpera** [comment]
The SHA change looks fishy, it might impact external usage. @vargaz you're the one that added it. Where is it used?

**Comment by vargaz** [comment]
It only used internally.

**Comment by schani** [comment]
This will definitely interfere with #1648.

**Comment by alexrp** [comment]
OK, will wait for #1648 to be merged.

**Comment by vargaz** [comment]
This can probably be merged now.

**Comment by alexrp** [comment]
I'll rebase this after #1766 is merged.

**Comment by vargaz** [comment]
This can probably be merged now.

**Pull request merged**
