### PR TITLE
[runtime] Integrate BenchmarkDotNet for in-tree microbenchmarks (reapply of #9833)

### PR DESCRIPTION
**Pull request by alexanderkyte**
Includes undo of revert

I decided to add a new Automake variable so as not to conflate the defaulting behavior.

### CODE REVIEW

**Comment by alexanderkyte** [comment]
The csproj diff issues seen here: https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-all-profiles-build/352/Project_20Files_20Diff/ seems related to me adding NS2.0 to the testing_aot_full profile. 

I think that if I'm reading this right, all of these changes are desirable.

**Comment by alexanderkyte** [comment]
@akoeplinger with respect to the helix failures seen on Linux x64:

```make: Entering directory '/mnt/jenkins/workspace/test-mono-pull-request-amd64/mcs/tools/mono-helix-client'
MONO_HELIX_XUNIT_REPORTER_PATH="/mnt/jenkins/workspace/test-mono-pull-request-amd64/external/helix-binaries/xunit-reporter.py" MONO_PATH="./../../../external/helix-binaries:./../../class/lib/build" /mnt/jenkins/workspace/test-mono-pull-request-amd64/runtime/mono-wrapper  ./../../class/lib/build/mono-helix-client.exe --tests="mainline" --correlationIdFile="/mnt/jenkins/workspace/test-mono-pull-request-amd64/test-correlation-id.txt"
Sending job to Helix...

Unhandled Exception:
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
  at Microsoft.DotNet.Helix.Client.Job.NewOperationWithHttpMessagesAsync (Microsoft.DotNet.Helix.Client.Models.JobCreationRequest newJob, System.Collections.Generic.Dictionary`2[TKey,TValue] customHeaders, System.Threading.CancellationToken cancellationToken) [0x004ce] in &lt;c0de49fed3554422a46297a22d24f94d&gt;:0 
  at Microsoft.DotNet.Helix.Client.JobExtensions.NewOperationAsync (Microsoft.DotNet.Helix.Client.IJob operations, Microsoft.DotNet.Helix.Client.Models.JobCreationRequest newJob, System.Threading.CancellationToken cancellationToken) [0x0007a] in &lt;c0de49fed3554422a46297a22d24f94d&gt;:0 
  at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync () [0x003b5] in &lt;e28d745330de49a58f1b605e0fdcb664&gt;:0 
  at HelixTestBase.SendJob () [0x00074] in &lt;abf0a20031d04010a89142be67a137c7&gt;:0 
  at Program.MainAsync (System.String[] args) [0x00168] in &lt;abf0a20031d04010a89142be67a137c7&gt;:0 
  at Program.Main (System.String[] args) [0x0000c] in &lt;abf0a20031d04010a89142be67a137c7&gt;:0 
[ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
  at Microsoft.DotNet.Helix.Client.Job.NewOperationWithHttpMessagesAsync (Microsoft.DotNet.Helix.Client.Models.JobCreationRequest newJob, System.Collections.Generic.Dictionary`2[TKey,TValue] customHeaders, System.Threading.CancellationToken cancellationToken) [0x004ce] in &lt;c0de49fed3554422a46297a22d24f94d&gt;:0 
  at Microsoft.DotNet.Helix.Client.JobExtensions.NewOperationAsync (Microsoft.DotNet.Helix.Client.IJob operations, Microsoft.DotNet.Helix.Client.Models.JobCreationRequest newJob, System.Threading.CancellationToken cancellationToken) [0x0007a] in &lt;c0de49fed3554422a46297a22d24f94d&gt;:0 
  at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync () [0x003b5] in &lt;e28d745330de49a58f1b605e0fdcb664&gt;:0 
  at HelixTestBase.SendJob () [0x00074] in &lt;abf0a20031d04010a89142be67a137c7&gt;:0 
  at Program.MainAsync (System.String[] args) [0x00168] in &lt;abf0a20031d04010a89142be67a137c7&gt;:0 
  at Program.Main (System.String[] args) [0x0000c] in &lt;abf0a20031d04010a89142be67a137c7&gt;:0 
Makefile:15: recipe for target 'upload-to-helix' failed
make: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-amd64/mcs/tools/mono-helix-client'
make: *** [upload-to-helix] Error 1
/mnt/jenkins/workspace/test-mono-pull-request-amd64/scripts/ci/babysitter: Test suite terminated with code 2, and suite cannot report test case data. Halting.
<a name="ERROR1"></a><span style="color:red">*** end(23): upload-helix-tests: Failed</span>
I: Copying back the cached apt archive contents
I: unmounting /mnt/jenkins/workspace/test-mono-pull-request-amd64 filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: cleaning the build env 
```

This doesn't seem to use the TEST_PROFILE I modify at all, and I'm not seeing any failures earlier in the log. Is there a way to do basic correctness checks offline?

**Comment by akoeplinger** [comment]
@alexanderkyte I've seen this on a couple PRs in that timeframe so probably a temporary glitch from the Helix API

**Comment by akoeplinger** [comment]
@monojenkins commit csproj

**Comment by alexanderkyte** [comment]
@akoeplinger yeah I'm planning on incorporating that feedback, along with some other changes, next sprint. This sprint my focus is all on crash reporting stability.

**Pull request merged**
