### PR TITLE
MSVC fixes for Cycle 6 branch

### PR DESCRIPTION
**Pull request by directhex**
These changes (all except 599d21e) were needed to build the 4.2.1 .msi on mono-project.com, and should be included on the mainline C6 branch for SR1

### CODE REVIEW

**Comment by kumpera** [comment]
What's the trello card for this one?

**Comment by directhex** [comment]
Um... good question. I can attach a card, though it's a bit late. Which board - SR1?

**Comment by kumpera** [comment]
yes. let's add there. I'll mark it with a tech lead exemption since it doesn't need QA.

**Comment by directhex** [comment]
Okay, I've added a card to the inbox at https://trello.com/c/o2gPFl9x/166-mono-build-fixes-for-win32-msvc-compilation - please manipulate as you see fit, and sorry for not doing it in advance.

**Pull request merged**
