### PR TITLE
[DO NOT MERGE] [MSBuild] Optimize build time by caching build results

### PR DESCRIPTION
**Pull request by slluis**
xbuild uses MSBuild tasks to resolve project references and
for getting the list of files to copy from referenced projects
(by invoking the targets GetTargetPath and
GetCopyToOutputDirectoryItems).

In solutions with many projects and many references, this may be
very slow, since those targets have to be invoked recursively
through all references.

This patch adds a cache for the results of those targets, so that
the target is invoked only once per build session.

### CODE REVIEW

**Comment by migueldeicaza** [comment]
The above patch makes one of the projects that we are working with (Stephen Shaw's project) goes from six minutes to one minute.   

According to Lluis sometimes builds fail, perhaps the caching is not exactly right.

There might be some work needed to make this better.

@radical Can you take a look at this?   I wonder if MSBuild addresses this.

**Comment by decriptor** [comment]
@migueldeicaza @radical has already been looking at this. He chatted with me on Monday about it. I believe he has a variation of the patch?

**Comment by radical** [comment]
Yes, I have a variation of the patch.

We already have the caching that @slluis' patch implements, but it gets looked up very late. So, I have moved it up the call stack. But it is still a little slower than Llluis' patch. I am doing a bit more work for correctness, but it should not cause the slowdown. So, trying to investigate and fix that. Then maybe Lluis can test it out :)

**Comment by slluis** [comment]
@radical I can try the patch, let me know when it is ready.

**Comment by radical** [comment]
@slluis My patch doesn't help very much. And I figured out the reason for that - XS seems to be invoking the build with `BuildSettings.None`, effectively clearing the cache before every project build! Your patch worked because it was effectively ignoring that request and *always* using the cache, which is also incorrect.

In `main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.cs`, I found:

```
 86  // We are using this BuildProject overload and the BuildSettings.None argument as a workaround to
 87  // an xbuild bug which causes references to not be resolved after the project has been built once.
 88  buildEngine.Engine.BuildProject (project, runTargets, new Hashtable (), BuildSettings.None);
```

Do you remember the details of the bug mentioned here? If we can change this to use `BuildSettings.DoNotResetPreviouslyBuiltTargets`, then it will utilise the existing caching and that should definitely improve build times. Once that works, we can make do the cache lookups earlier, like I was trying to, to get some additional performance.

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by radical** [comment]
This PR can probably be closed. @slluis, do you want a bug for this? I could cleanup and commit the patch that I had, if that is still required or was the change in XS enough? My patch essentially moved the cache lookup to be a little earlier in the code path, but relied on the existing caching. I am not sure how much *more* it would help on top of the XS change.

**Pull request closed without merging**
