### PR TITLE
[Coop]  Conversion of CreateProcess and ShellExecute.

### PR DESCRIPTION
**Pull request by jaykrell**
… native/managed interface.

Replace them with long parameter lists.
This will ease 1. Using "fixed" 2. Trimming the native/managed interface.
Presently the managed/native interface is inflated by essentially the managed/managed interface.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build deb with monolite

**Comment by vargaz** [comment]
This looks kinda ugly, we put parameters in structures to avoid these long parameter lists.

**Comment by jaykrell** [comment]
It is ugly either way. Parameters in struct have 3 disadvantages: 1 native/managed must be slightly more councident (similar to parameters though), 2 can’t “fixed” the fields 3 can’t trim unused ones

**Comment by jaykrell** [comment]
Specifically this enabled “fixing” the strings & it will allow trimming.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
This is also incomplete (do not merge). The trimming isn’t done. The parameter list also eliminates the managedness/handle of the first parameter. 

The code is not performance sensitive, but I’d like to get it simpler. Maybe move the env var handling to managed (can’t fixed array of strings).

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Will try more conventional conversion.

**Comment by jaykrell** [comment]
Will probably do this differently (almost done).

**Pull request closed without merging**
