### PR TITLE
[mini] iltests.exe depends on TestDriver.dll

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by lewurm** [comment]
@monojenkins build Linux ARMv7
@monojenkins build OS X x64

**Comment by lewurm** [comment]
@monojenkins build Linux ARMv7

**Comment by lewurm** [comment]
@monojenkins build OS X x64

**Pull request merged**
