### PR TITLE
[msvc] Remove the use of module definition files.

### PR DESCRIPTION
**Pull request by alexrp**
This is a resurrection of @joncham's PR #4435. I'm doing this blindly as I don't have a Windows build environment. Let's see what Jenkins thinks.

### CODE REVIEW

**Comment by joncham** [comment]
One of the important parts in my PR was adding 
```
<UseLibraryDependencyInputs>true</UseLibraryDependencyInputs>
```
to the vcxproj's. That allows exported functions linked in static libraries to be exported. This links the obj files from dependencies directly, rather than static libs. If not, symbols get lost due to weird behavior of linker on Windows. 

See initial comment in original PR.

**Comment by joncham** [comment]
I can clean up my PR if needed, I just didn't get around to setting up and testing on a Cygwin environment since we don't use that.

**Comment by alexrp** [comment]
Oh, I wasn't aware of that. I just read the documentation for `UseLibraryDependencyInputs` and assumed it was largely unrelated.

If you want to update your PR, that would be great too. I'd just like to see these files gone as they're a source of pain when changing Mono's public API.

**Comment by joncham** [comment]
I have rebased my PR: https://github.com/mono/mono/pull/4435

Can I download the cygwin built binaries to check exported symbols from the build server?

**Comment by akoeplinger** [comment]
I sent the files to @joncham, should we close this and continue in #4435?

**Comment by joncham** [comment]
I am not sure either PR is fully correct. It looks like the magic we need is this linker flag https://msdn.microsoft.com/en-us/library/mt732963.aspx

When I add it the linker crashes. Known issue with a hotfix it seems, but we can't require everyone to have the hotfix.

**Comment by vargaz** [comment]
Do we really need these libraries ? On unix, we use them since we have one makefile per directory, but they are not needed with the msvc build model.

**Comment by joncham** [comment]
I am happy to restructure the project setup to avoid some of the current pitfalls. Only thing in the past was that Windows devs may break non-Windows platform builds since our build structure was slightly different. But that is not a very big deal.

**Comment by alexrp** [comment]
I'll close this then.

**Comment by jaykrell** [comment]
The linker behavior is not wierd at all.
.libs are not looked at, or the .objs within them, unless needed to resolve symbols.
And only then are directives seen.
This not-eager behavior is critical to the linker's behavior, as otherwise it will discover duplicate symbols all over the place and fail.

I understand .def files require porting to each linker but I do encourage their use.
They have the following advantages:
 - You regain the not-eager linker behavior; which also leads to other linker optimizations.
 - The source code is left clean and portable.
 - Function names for GetProcAddress become portable,  i.e. x86 is just "Foo" and not "_Foo@N".
 - People can stop worrying about declspec(dllimport) and dllexport and getting them right, and building twice for dll vs. lib. They aren't needed and you need only build one way.

One caveat: Only export functions, not data.
Dllimport is needed for data.
But still dllexport is not needed for data; mark it as data in the .def file.

Two caveat: When not using LTCG, imported functions that aren't marked dllimport, incur one extra instruction. I don't think that matters.

**Comment by akoeplinger** [comment]
@jaykrell please note that we did drop the .def files in https://github.com/mono/mono/pull/5656

**Comment by vargaz** [comment]
Def files might have some advantages, but updating them was a pain, so we transitioned to using attributes in code.

**Pull request closed without merging**
