### PR TITLE
Remove a few braces that are contrary to our prescribed style.

### PR DESCRIPTION
**Pull request by jaykrell**
I notice this stuff working on larger changes but should either leave it alone or separate it.

### CODE REVIEW

**Comment by jaykrell** [comment]
build

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv5 soft float

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float

**Pull request merged**
