### PR TITLE
fix specfile

### PR DESCRIPTION
**Pull request by echampet**
also need to be backported to 3.12 branch

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by akoeplinger** [comment]
Is this specfile even used anymore? I think @directhex has new files for his packages.

**Comment by directhex** [comment]
Yeah, I switched to my own spec files during development of the new packages, to avoid too much churn on the main mono repository. I haven't merged those back in (I'm not sure keeping packaging metadata in the main repo is helpful, it's not the norm in Debian land). Is that something we should be doing?

The spec files for the mono-project.com packages are in the centos branch of repos under github.com/directhex starting with xamarin- e.g. https://github.com/directhex/xamarin-mono/blob/centos/mono-core.spec

**Comment by echampet** [comment]
ok, i'll use you spec.
do you want a PR to drop mono-core.spec.in ?

**Comment by echampet** [comment]
see https://github.com/directhex/xamarin-mono/pull/1

**Comment by directhex** [comment]
I think it's worth a discussion on the mailing list about where/how people feel the spec files should be maintained. I'll still need to keep the Debian packaging metadata elsewhere (it's more complicated than spec file metadata, and isn't well suited to being stored upstream on complex projects) - and the Debian version will continue to be the primary dev target

**Comment by akoeplinger** [comment]
I'd say the packaging files should be hosted in the [mono/release](https://github.com/mono/release) repo where the Windows installer files are.

**Comment by echampet** [comment]
@knocte, i've updated the random name
also my "new" version is already merged in @directhex repo

**Comment by migueldeicaza** [comment]
We should maintain the spec files, and the deb files, but let us put them in a central location.

I do not think they need to be on each module.  So I would remove the file from here, and update the documentation to point to the new location.

**Comment by alexrp** [comment]
@directhex what's the status of this?

**Comment by alexrp** [comment]
Closing this as we're removing this spec file.

**Pull request closed without merging**
