### PR TITLE
[2019-12] Bump msbuild to track mono-2019-10

### PR DESCRIPTION
**Pull request by radical**
- and update nuget.exe to 5.5.0-preview1 to match

### CODE REVIEW

**Comment by lewing** [comment]
Do we need to ship the preview NuGet.exe for things to work or can we stick with the release version for the branches?

**Comment by radical** [comment]
I think the release version should be fine too. It became available for download, so I thought we could stay close to the version in msbuild.

**Comment by radical** [comment]
I can test it out with the package.

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by radical** [comment]
`Linux AArch64 FullAOT`: `MonoTests.test-unhandled-exception-2-255-with-managed-handler.unhandled-exception-4.exe_timedout`

`Linux x64 - prefix sanity checks`:
```
09:03:02 E: debootstrap failed
09:03:02 E: Tail of debootstrap.log:
09:03:02 E: End of debootstrap.log
09:03:02 W: Aborting with an error
09:03:03 $ sudo /usr/sbin/pbuilder --create --basetgz /mnt/jenkins/pbuilder/debian-9-amd64-nightly.tgz --extrapackages "python-software-properties sudo gnupg wget" --mirror http://ftp.debian.org/debian/ --architecture amd64 --distribution stretch --components "main contrib non-free" --debootstrapopts --keyring=/usr/share/keyrings/debian-archive-keyring.gpg
09:03:03 W: /home/builder/.pbuilderrc does not exist
09:03:03 W: cgroups are not available on the host, not using them.
09:05:40 W: No local /etc/mailname to copy, relying on /mnt/jenkins/buildplace/3763/etc/mailname to be correct
09:06:38 E: Package 'python-software-properties' has no installation candidate
09:06:40 FATAL: Could not setup chroot environment
09:06:40 FATAL: Installation of tool debian-9-amd64-nightly on node az-ubuntu-generaldb7bd0 failed.
09:06:40 java.io.IOException: Installation of tool debian-9-amd64-nightly on node az-ubuntu-generaldb7bd0 failed.
09:06:40 	at org.jenkinsci.plugins.chroot.tools.ChrootCreator.performInstallation(ChrootCreator.java:55)
```

**Pull request merged**
