### PR TITLE
closedir missed in recent change.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by luhenry** [comment]
Where did you miss it? What change is it related to? The commit message gives 0 indication as to why this change is happening

**Comment by jaykrell** [comment]
Commits on Jan 18, 2018 
 
[mini] Make sure mkbundle executables work if they are run from a pat… … 
ramin-zaghi committed with luhenry a day ago

**Comment by luhenry** [comment]
Well, that should go in the commit message, not a comment on the PR.

**Comment by alexischr** [comment]
Usefully for these cases, Github generates commit links if you reference the SHA1 in the commit message.

**Comment by jaykrell** [comment]
You can just look at the history of the file.

**Pull request merged**
