### PR TITLE
Bump msbuild to track xplat-master

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by akoeplinger** [comment]
please backport to 2018-08 too once we're good with this

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Fixed build script.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by akoeplinger** [comment]
There's `XUnit : error : Tests failed on platforms: net471|x86 [/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/msbuild-15/src/Build.UnitTests/Microsoft.Build.Engine.UnitTests.csproj]` on the msbuild tests.

**Comment by radical** [comment]
second issue: https://github.com/mono/mono/issues/10555

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
```
03:20:29 /Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/ci/babysitter: Command `make` timed out
03:20:29 /Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/ci/babysitter: Saw timeout in test case None (never allowed). Will halt testing.
03:20:29 *** end(14401): runtime-tests-llvm: \e[43mUnstable\e[0m
```

@akoeplinger mono crashes and timeouts, is this a known issue?

**Comment by radical** [comment]
Rebased on master again!

@monojenkins build OS X Extended

**Comment by radical** [comment]
```
21:13:16 msbuild->do_build:
21:13:16 	Building (arch: darwin-64)
00:35:11 /Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/ci/babysitter: Command `/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/mac-sdk-package.sh` timed out
00:35:11 /Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/ci/babysitter: Saw timeout in test case None (never allowed). Will halt testing.
00:35:11 *** end(18000): bockbuild: \e[41mFailed\e[0m
```

**Comment by akoeplinger** [comment]
> @akoeplinger mono crashes and timeouts, is this a known issue?

Nothing I'm aware of.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Comment by radical** [comment]
Waiting on https://github.com/mono/mono/issues/10863 .

**Comment by akoeplinger** [comment]
@radical hmm I merged https://github.com/mono/mono/pull/10668#issuecomment-425306516 before I saw #10863, do you think it'll cause frequent hangs in the 2018-08 branch?

**Comment by radical** [comment]
@akoeplinger @lambdageek [confirmed](https://github.com/mono/mono/issues/10863#issuecomment-425467536) that the GC issue affects 2018-08 too, so yeah, I think it might cause occasional hangs :/

**Comment by akoeplinger** [comment]
The PR which fixes the hang was merged so let's try another build.

@monojenkins build OS X Extended

**Comment by radical** [comment]
Rebased the branch to get the fix.

@monojenkins build OS X Extended

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
5 test failures, but those should have been fixed on mono/master. Investigating.

**Comment by radical** [comment]
Tests are failing due to https://github.com/mono/mono/issues/10951 .

**Comment by radical** [comment]
Rebased to get the fix for #10951 .

@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Finally, all the msbuild tests pass! @akoeplinger could you please merge this?

**Comment by akoeplinger** [comment]
yay 🎉

**Pull request merged**
