### PR TITLE
[interp] Make calli non recursive as well.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Fixes https://github.com/mono/mono/issues/17938

**Comment by vargaz** [comment]
This is needed to fix blazor on ios13. Long term, we need to clean up the code duplication in the call opcodes.

**Comment by lewing** [comment]
Verified the fix

**Comment by lewing** [comment]
Failures with mixed more look relevant

**Comment by vargaz** [comment]
Reverted part of it, ios still seems to work with the reduced changes.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
