### PR TITLE
[System*] Disable tests that require working networking stack on watchOS.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by akoeplinger** [comment]
LGTM 👍

**Comment by marek-safar** [comment]
I'd much prefer something like `[Category ("RequiresBSDSocket")]` instead of general category with comment copied everywhere

**Comment by rolfbjarne** [comment]
I'll update the PR, changing the category to `RequiresBSDSocket`

**Comment by rolfbjarne** [comment]
I've now changed the category to `RequiresBSDSockets`.

**Pull request merged**
