### PR TITLE
GC debug and params command line options

### PR DESCRIPTION
**Pull request by joncham**
Exposes the same functionality as the MONO_GC_DEBUG and MONO_GC_PARAMS environment variables as command line arguments --gc-debug and --gc-params. This allows specifying these options without setting environment variables, which may affect child processes.

These command line arguments are also processed in the separate parsing logic within mono_jit_parse_options.

### CODE REVIEW

**Comment by BrzVlad** [comment]
LGTM, although it might we worth documenting that, at least in the case of gc params, we are giving precedence to environment params over command line params

**Comment by joncham** [comment]
@BrzVlad both values give precedence to env vars, or at least append those options and they will be processed later. Is that behavior acceptable to you?

I am attempting to merge the values currently but we could also allow one setting to take complete precedence over the other.

**Comment by migueldeicaza** [comment]
I think the precedence of the environment variable will be fine.

Once the patch is in, I can take care of updating the man page.

**Comment by BrzVlad** [comment]
@joncham I also think it is best as is right now. When I pass an option through the env, I'd expect not to affect the rest of the options, so merging them is the best option. Also, given it's easier to change the env rather than the args, it's best to have complete flexibility over the params through the env, which means they should have precedence when specified also in the args.

**Pull request merged**
