### PR TITLE
[sdks] Add more targets for XA

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by vargaz** [comment]
Made a jenkins lane to build mxe here:
https://jenkins.mono-project.com/job/build-package-osx-mxe/
Its not working yet.

**Comment by vargaz** [comment]
Its working now, the binaries are at:
https://jenkins.mono-project.com/job/build-package-osx-mxe/3/label=osx-amd64/Azure/
They need to be extracted to /, so they will be at /tmp/mxe-<GIT REV>/.

**Comment by vargaz** [comment]
The direct link should be:
wget http://xamjenkinsartifact.blob.core.windows.net/build-package-osx-mxe/mxe-osx-<GIT REV>.tar.gz, but its not working for some reason.

**Comment by luhenry** [comment]
There are quite a few things left to do:
 - upload/download `llvm` and `mxe`
 - fix the build for `cross-{arm,arm64,x86,x86_64}`
 - build `cross-{arm,arm64,x86,x86_64}-win`.
 - add support for building on Linux

**Pull request merged**
