### PR TITLE
[interp] initial infrastructure for whitebox testing of optimization passes

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by BrzVlad** [comment]
I'm 50-50 on this. I'm not convinced about the usefulness of it. How do you see us expanding on it ? Simply writing IL test cases doesn't sound like something that we might do. Include tests as we detect cases where the passes miss a potential optimization ? What about when we change the optimizations to emit different code ? Sounds like we would need to iterate over lots of tests and completely change the entire generated code. Sounds a little painful for the benefits that it would provide.

**Comment by lewurm** [comment]
> Include tests as we detect cases where the passes miss a potential optimization ?

**Comment by lewurm** [comment]
> How do you see us expanding on it ? Simply writing IL test cases doesn't sound like something that we might do

Yeah, I don't think we should do that.

> Include tests as we detect cases where the passes miss a potential optimization ?

Yes, for example I would like to add a test for this case: https://github.com/mono/mono/pull/18129#discussion_r359615779

There is no good way to test it otherwise.


> What about when we change the optimizations to emit different code ?

I don't expect a specific optimization to behave too differently over time. Also, in the test you can specify what optimizations you wanna apply to your snippet. So, while the "transformation pipeline" gets more sophisticated, I hope a single optimization doesn't change that dramatically. But even then, it might be good to have such tests; I don't except we won't have hundreds of them.

**Comment by BrzVlad** [comment]
@vargaz What do you think about this ?

**Comment by vargaz** [comment]
It might be easier to emit some kind of logging every time some optimization in performed and check that.

**Comment by lewurm** [comment]
Logging sounds even more fragile to be honest.

How strong do you guys feel about it?  I would love to land it, and rather let us see if it's useful or not in the future. We can always remove it easily, it isn't too disruptive imho. The only downside is that we have to export some more symbols.

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@BrzVlad @vargaz ping

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
