### PR TITLE
[2019-02] Bump roslyn to 3.1.0

### PR DESCRIPTION
**Pull request by kg**

### CODE REVIEW

**Comment by kg** [comment]
@monojenkins build deb with monolite

**Comment by kg** [comment]
@monojenkins build deb with monolite

**Comment by kg** [comment]
@monojenkins build

**Comment by kg** [comment]
@monojenkins commit apidiff and csproj

**Comment by kg** [comment]
@monojenkins build failed

**Comment by kg** [comment]
@monojenkins build failed

**Comment by kg** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
Is this ready to merge?

**Comment by lewurm** [comment]
Given that there are problems in the `2019-06` XI integration ( https://github.com/mono/mono/pull/14757#event-2385292170 ) we might should not bump roslyn on 2019-02 this late?

**Comment by kg** [comment]
I personally don't think we should bump it, but this is mergeable. The risk factor is that many things depend on roslyn and we don't have test coverage for them. (I was hoping to backport the msbuild CI lane onto this and run the tests there locally + on CI to see if I could flush out any issues).

**Comment by lewing** [comment]
We'll definitely pause this until #14762 is resolved

**Comment by lewing** [comment]
roslyn 3.1 appears likely to resolve #14762 can we update to a known good version here as well.

**Comment by kg** [comment]
I will be backporting once -06 is confirmed working.

**Comment by lewing** [comment]
Should we close this in favor of https://github.com/mono/mono/pull/14781 ?

**Comment by kg** [comment]
I don't think so, I was expecting to see lane failures on that but I guess the relevant automated tests aren't running on PRs. I think I probably want to change this one to point to the new revision instead so we keep the fixes (list of DLLs, etc)

**Comment by lewing** [comment]
Ok, then please make sure this is pointing at the right versions

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Pull request merged**
