### PR TITLE
[netcore] Disable socket support to fix warnings.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by jaykrell** [comment]
Something is messed up with CI. These 132 errors, I see on other PRs. Maybe time or timezone.

**Comment by filipnavara** [comment]
@jaykrell Yes, it is globally messed up. The code for testing Hebrew date/time parsing uses `DateTime.Today` and something got triggered on September 1, 2019.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
@vargaz All the rebuilds will fail now until #16624 or other fix is merged. We hit a unit test time bomb because of Hebrew calendar leap year.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
azp /run

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
