### PR TITLE
Use domain->empty_string more.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
This changes behavior i.e. if you lock on strings, it could lead to a deadlock.

**Comment by jaykrell** [comment]
Oh, because each separately allocated object, each string, etc. is implicitly another available lock?

That, makes sense, given the underlying imho bad but unchangable Java-inspired, programming model, so I guess, sorry, nevermind, closing. Thank you for the explanation.

**Comment by jaykrell** [comment]
Notice that CI largely succeeds, so, missing tests.

**Pull request closed without merging**
