### PR TITLE
Get build of merp speedup

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
The OSX package job repeatedly fails to pick up on 
 
https://github.com/mono/mono/pull/9986/files#diff-f1a9287559d3aa620b058619f47f00c9R5694

It wil complain that the line that was removed / the old version of the line is the one that is breaking.

I'm building this locally now. This is really buggy.

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
@akoeplinger @directhex you can see that here:  https://jenkins.mono-project.com/job/build-package-osx-mono-pullrequest/207/console

**Comment by alexanderkyte** [comment]
```
21:52:11   CC       libmonoruntime_la-sysmath.lo
21:52:11   CC       libmonoruntime_la-threads.lo
21:52:11   CC       libmonoruntime_la-threadpool.lo
21:52:11   CC       libmonoruntime_la-threadpool-io.lo
21:52:11   CC       libmonoruntime_la-verify.lo
21:52:11 
threads.c:5694:63: error: member reference type 'guint32' (aka 'unsigned int') is not a pointer
21:52:11                         MonoThreadInfo *info = (MonoThreadInfo*) thread_array [i]->thread_info;
21:52:11                                                                  ~~~~~~~~~~~~~~~~  ^
21:52:11 threads.c:5730:17: warning: unused variable 'timeout_abort_success' [-Wunused-variable]
21:52:11                                 MonoBoolean timeout_abort_success;
21:52:11                                             ^
21:52:11 1 warning and 1 error generated.
21:52:11 
make[3]: *** [libmonoruntime_la-threads.lo] Error 1
21:52:11 make[3]: *** Waiting for unfinished jobs....
21:52:11 make[2]: *** [all-recursive] Error 1
21:52:11 make[1]: *** [all-recursive] Error 1
21:52:11 make: *** [all] Error 2
21:52:11 
21:52:11 mono->build_sh:```

**Comment by alexanderkyte** [comment]
And yet 
```
			// Request every other thread dumps themselves before us
			MonoThreadInfo *info = (MonoThreadInfo*) thread_array [i]->thread_info;
			MonoThreadInfo *info = (MonoThreadInfo*) thread->thread_info;
```

**Comment by alexanderkyte** [comment]
If jenkins is getting stale commits from github's API, maybe we need to escalate with Github Support.

**Comment by akoeplinger** [comment]
Reposting what I said on Slack, just so everyone is on the same page:

> aha! the previous build built https://github.com/mono/mono/commit/a50fd76
> which is indeed missing that line you mentioned

The new build seems to have generated a correct package: https://jenkins.mono-project.com/job/build-package-osx-mono-pullrequest/208/

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

timeout in llvm?

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@alexanderkyte a package is available now on https://jenkins.mono-project.com/job/build-package-osx-mono-pullrequest/212/

**Comment by akoeplinger** [comment]
Closing since this is most likely not needed anymore.

**Pull request closed without merging**
