### PR TITLE
[Facades] Add missing Facades that exist in .NET 4.7.1

### PR DESCRIPTION
**Pull request by akoeplinger**
Some of them we had on mobile only, others were missing completely.

Fixes https://github.com/mono/mono/issues/7536

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
Review:

- System.Net.Http.Rtc.dll -- remove completely I don't think it's worth the pain as it's windows only
- System.Resources.Reader/System.Resources.Writer we need to report CoreFX issue to update the package to include our mobile version TFMs

**Comment by akoeplinger** [comment]
> System.Net.Http.Rtc.dll -- remove completely I don't think it's worth the pain as it's windows only

I'd like to keep System.Net.Http.Rtc.dll since it's a bigger pain to exclude it from all the compares I do with .NET Fx. It's not really a pain since we need to edit some files for  https://github.com/mono/mono/issues/7573 anyway and it's just one more line.

> System.Resources.Reader/System.Resources.Writer we need to report CoreFX issue to update the package to include our mobile version TFMs

https://github.com/dotnet/corefx/issues/27995

**Comment by marek-safar** [comment]
`System.Net.Http.Rtc.dll` I am fine to keep it on desktop even if it's useless as it cannot be referenced but don't want this in any mobile/modern profile

**Comment by marek-safar** [comment]
We should also update `api` Facades

**Comment by akoeplinger** [comment]
@marek-safar what do you mean by that?

**Comment by marek-safar** [comment]
Should we add them also to https://github.com/mono/reference-assemblies/tree/master/v4.7.1/Facades ?

**Comment by akoeplinger** [comment]
@marek-safar they are there, that's why we noticed them missing from mono in the first place :)

**Comment by marek-safar** [comment]
oh (used wrong search pattern). We are good then

**Pull request merged**
