### PR TITLE
[corlib] Allow copying/moving/replacing broken symlinks

### PR DESCRIPTION
**Pull request by alexischr**
Fixes https://github.com/mono/mono/issues/14971

Upstream CoreFX PR:https://github.com/dotnet/corefx/pull/39306

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by lambdageek** [comment]
@EgorBo, @akoeplinger could one of you review this PR

**Comment by marek-safar** [comment]
@steveisok could you please handle landing this change

**Comment by steveisok** [comment]
@alexischr There are a few nits in the upstream corefx PR.  Once that lands we can get it into mono/corefx and move this PR forward.

**Comment by alexischr** [comment]
@steveisok though it may be okay to wait for an upstream approval, this is a regression only for Mono, and should probably not wait for a merge upstream (especially since the master is blocked on merging: https://github.com/dotnet/corefx/pull/39306#issuecomment-509470828)

**Comment by steveisok** [comment]
I'm ok w/ pushing to our fork now.

**Comment by akoeplinger** [comment]
The corefx PR isn't blocked, the master branch takes PRs again (if there's no movement please ping them).

We can land the changes to our corefx fork now

**Comment by steveisok** [comment]
@alexischr do you have any update?

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by alexischr** [comment]
@steveisok this PR should be ready, and I pinged reviewers again to get an approval upstream. I can merge once csproj diff is ready.

**Comment by akoeplinger** [comment]
We still need to first land the changes to master in our corefx fork, this PR currently points to a branch.

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by steveisok** [comment]
@monojenkins backport 2019-06

**Pull request merged**
