### PR TITLE
Switch Android GC bridge default from new-bridge to tarjan-bridge

### PR DESCRIPTION
**Pull request by xmcclure**

### CODE REVIEW

**Comment by xmcclure** [comment]
If this goes through I will backport it to 4.5.1.

**Comment by kumpera** [comment]
LGTM

**Comment by xmcclure** [comment]
@monojenkins merge

**Comment by xmcclure** [comment]
Linux x64 and ARMv5 soft float failures are unrelated. Armv7 hard float and aarch64 are failures in the bridge test, so that's actually quite worrisome.

**Comment by xmcclure** [comment]
This has already been merged into 4.5.1 btw.

**Comment by xmcclure** [comment]
Armv7 and aarch64 failures both look like:

    sgen-scan-object.h:90

Armv7 hard float failure is explicitly requesting new-bridge and therefore it is not related to this PR.

Aarch64 test seems to be the same failure. Running manually on aarch64 however I do not reproduce it even on repeated tests.

Since I cannot reproduce and the error appears to occur with both new-bridge and tarjan-bridge I am going to go ahead and merge. We should watch for the failure in future though.

**Pull request merged**
