### PR TITLE
Rename glib.h to mono-glib.h, to avoid conflict with actual GLib.

### PR DESCRIPTION
**Pull request by jaykrell**
And gmodule.h to mono-gmodule.h.
https://github.com/mono/mono/issues/18528#issuecomment-599125004

### CODE REVIEW

**Comment by vargaz** [comment]
This is not neccessary unless somebody installs glib.h into a system header directory which shouldn't be done, the canonical location is <prefix>/glib-2.0/glib.h.

**Comment by jaykrell** [comment]
The FreeBSD port apparently benefits from it.
And even if it is not definitely necessary it is still reasonable and makes things a little clearer.

**Comment by jaykrell** [comment]
This was motivated by the FreeBSD port, and seems reasonable.
https://github.com/mono/mono/issues/18528

**Comment by CoffeeFlux** [comment]
As far as I can tell the FreeBSD port is not blocked by this, so I'm opposed to otherwise pointless file renaming.

**Comment by lambdageek** [comment]
Not doing this. FreeBSD has another way around the issue

**Pull request closed without merging**
