### PR TITLE
[sdks] Disable the interpreter on ios device builds.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by luhenry** [comment]
This is going to trigger building the interpreter as a separate library, right?

**Comment by vargaz** [comment]
This is just needed to sync up with the old makefiles in xamarin-macios.

**Comment by vargaz** [comment]
@monojenkins backport 2018-02

**Comment by vargaz** [comment]
@monojenkins 2017-12

**Comment by vargaz** [comment]
@monojenkins bacport 2017-12

**Comment by vargaz** [comment]
@monojenkins backport 2017-12

**Pull request merged**
