### PR TITLE
System.Core: Use ECCurve & friends from CoreFX.

### PR DESCRIPTION
**Pull request by filipnavara**
Part of #9463

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
The ARM builds are currently universally broken (seems like it was nailed down to the "fast Span" commit). Otherwise it only seems to need "commit csproj" and "commit apidiff" from Jenkins bot. I didn't feel like doing the apidiff without previous approval by some of the maintainers.

**Comment by filipnavara** [comment]
@monojenkins commit csproj

**Comment by filipnavara** [comment]
@monojenkins commit apidiff

**Comment by baulig** [comment]
@filipnavara There is no point in doing the csproj/api-diff thing when the build is not green as it won't be able to get in anyways and I also can't merge it while required steps are failing.  This situation is generally handled by somebody with special privileges like @akoeplinger doing the csproj/api-diff and then merge bypassing the checks.

**Comment by filipnavara** [comment]
Oh well, let's wait then till the ARM situation is sorted out.

**Comment by baulig** [comment]
We are currently working on the ARM issue.

**Comment by filipnavara** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff

**Comment by akoeplinger** [comment]
The ARM64 issue was fixed in master, merging.

**Pull request merged**
