### PR TITLE
[bcl] Deduplicate the SocketResponder test helper class.

### PR DESCRIPTION
**Pull request by alexrp**
A number of fixes were made to the version in System but these fixes were never applied to the System.Web.Services version. Merge the two and place the class in the test-helpers directory to avoid this sort of maintenance problem.

### CODE REVIEW

**Comment by alexrp** [comment]
@ludovic-henry can you review this?

**Comment by ludovic-henry** [comment]
@monojenkins merge

**Comment by ludovic-henry** [comment]
Build

**Comment by ludovic-henry** [comment]
build

**Pull request merged**
