### PR TITLE
Enable the wasm targets even if ENABLE_WASM is not defined.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
shouldn't we do that for `ENABLE_ANDROID`, `ENABLE_IOS` etc. too?

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Pull request merged**
