### PR TITLE
[profiler] Housecleaning

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by alexrp** [comment]
build profiler stress

**Comment by alexrp** [comment]
build coop

**Comment by alexrp** [comment]
Need to figure out why this is breaking heapshot on 32-bit platforms...

**Comment by akoeplinger** [comment]
build

**Comment by alexrp** [comment]
build profiler stress

**Comment by alexrp** [comment]
build profiler stress

**Comment by alexrp** [comment]
build profiler stress

**Pull request merged**
