### PR TITLE
[crash] Add more detailed reporting for exceptions

### PR DESCRIPTION
**Pull request by alexanderkyte**
This bumps the crash reporting file format to version 0.0.3.

### CODE REVIEW

**Comment by alexanderkyte** [comment]
Want to double-check the Sentry stuff, it might be broken by this. I confirmed it parses the JSON right but I haven't confirmed that the server-side rendering hasn't been garbled. 

I planned to make some changes to Sentry / get it more integrated into our CI workflow, so I'm not sure where that UI fixup should live.

**Comment by alexanderkyte** [comment]
@leculver can you give this a 👍 or 👎 for the new JSON schema: 

```
{
	"protocol_version": "0.0.3",
	"configuration": {
		"version": "(6.1.0) (managed_exc_reformat/f804ffdd2cd)",
		"tlc": "normal",
		"sigsgev": "altstack",
		"notifications": "kqueue",
		"architecture": "amd64",
		"disabled_features": "none",
		"smallconfig": "disabled",
		"bigarrays": "disabled",
		"softdebug": "enabled",
		"interpreter": "enabled",
		"llvm_support": "disabled",
		"suspend": "hybrid"
	},
	"memory": {
		"Resident Size": "43741184",
		"Virtual Size": "4534960128",
		"minor_gc_time": "252830",
		"major_gc_time": "0",
		"minor_gc_count": "7",
		"major_gc_count": "0",
		"major_gc_time_concurrent": "0"
	},
	"threads": [{
		"is_managed": false,
		"offset_free_hash": "0x13ae36b4bd",
		"offset_rich_hash": "0x13ae36bba7",
		"crashed": true,
		"native_thread_id": "0x0",
		"thread_info_addr": "0x0",
		"exceptions": [{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e5",
						"native_offset": "0x82",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00000"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			},
			{
				"type": "System.Exception",
				"managed_frames": [{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x2aa",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x00068"
					},
					{
						"is_managed": "true",
						"guid": "F9A5B429-BF6D-4068-8163-D74D1FD89AA2",
						"token": "0x60008e4",
						"native_offset": "0x7a",
						"filename": "net_4_x_corlib_test.dll",
						"sizeofimage": "0x4b7200",
						"timestamp": "0x9ce3a364",
						"il_offset": "0x0000f"
					}

				]
			}
		]
	}]
}
```

**Comment by leculver** [comment]
Requesting some additional testing on this offline, please hold on merging.  Here is my offline comments:

Maybe, but I’m a little confused by the output.  Can you try with something a little different?  Take a look at the attached, which is a good example of the real-world scenario we are trying to hit.

I would expect this to generate the threads[0].managed_frames callstack similar to this (I did this on CLR, will be different on mono):

`05aef378 720e4885 System.Runtime.CompilerServices.AsyncMethodBuilderCore+c.b__6_1(System.Object)
05aef380 7177a412 System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
05aef388 717d2ea5 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
05aef3f4 717d2db6 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
05aef408 7177d410 System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
05aef41c 7177cb72 System.Threading.ThreadPoolWorkQueue.Dispatch()
05aef46c 7177c9da System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

Then I would expect two exceptions.  The first listed as threads[0].exceptions[0]:

       type == “System.InvalidOperationException”
       managed_frames:
    05AEEDE0 01341013 TestNestedAsync!Program+<Bar>d__2.MoveNext()+0x14b
    05AEEBB8 717B8AB8 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    05AEEBC8 717B4767 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    05AEEBD4 72064807 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.GetResult()+0x1b
    05AEEBD8 01340D75 TestNestedAsync!Program+<Foo>d__1.MoveNext()+0xe5
    05AEF12C 717B8AB8 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x64
    05AEF13C 717B4767 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
    05AEF148 72064807 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.GetResult()+0x1b
    05AEF14C 01340B3C TestNestedAsync!Program+<ThrowAnUncatchableException>d__4.MoveNext()+0x1b4
    05AEF378 720E4885 mscorlib_ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)+0x35
    05AEF380 7177A412 mscorlib_ni!System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)+0x42
    05AEF388 717D2EA5 mscorlib_ni!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+0xe5
    05AEF3F4 717D2DB6 mscorlib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)+0x16
    05AEF408 7177D410 mscorlib_ni!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()+0x60
    05AEF41C 7177CB72 mscorlib_ni!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x192
    05AEF46C 7177C9DA mscorlib_ni!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()+0xa

And then I would expect another as threads[0].exceptions[1]:

                type == “System.OperationCanceledException”
       managed_frames:
        05AEF15C 0134126F TestNestedAsync!Program+<Baz>d__3.MoveNext()+0x107
        05AEEE88 717B8AE0 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0x8c
        05AEEE98 717B4767 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x3b
        05AEEEA4 72064807 mscorlib_ni!System.Runtime.CompilerServices.TaskAwaiter.GetResult()+0x1b
        05AEEEA8 01340FBE TestNestedAsync!Program+<Bar>d__2.MoveNext()+0xf6

Obviously with the mono runtime, this will look somewhat different.  The key takeaways though is that with the attached repo, we should still see:
1.	The “faulting” callstack of the thread that crashed (this is the Threadpool goo up top)
2.	A callstack for System.InvalidOperationException that contains “ThrowAnUncatchableException”, “Foo”, and “Bar”.
3.	A callstack for System.OperationCanceledException that contains “Bar” and “Baz”.

With these three combined, I am able to stitch together that a threadpool thread hit an InvalidOperationException in ThrowUncatchableException => Foo => Bar, and that Bar caught/nested OperationCanceledException in Bar => Baz.

What does this program look like with your change?

[async.txt](https://github.com/mono/mono/files/2853024/async.txt)

**Comment by alexanderkyte** [comment]
Sentry fixed: 	

```
-- HTTP POST Success {"id":"73bd8c3e59304640a45175f426a99a68"}
```

**Comment by luhenry** [comment]
@leculver could you please approve/request changes around the json format?

**Comment by leculver** [comment]
Yes, the updated changes from today are good.  As long as these changes reflect what Alexander had this afternoon, we are good to go.

**Comment by alexanderkyte** [comment]
Just had to add a missing NULL-check. mono_array_length_internal isn't forgiving of NULL arguments.

**Comment by alexanderkyte** [comment]
@monojenkins build failed

OSX x64:

```
Unhandled Exception:
System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/external/boringssl/ssl/handshake_client.c:1132
  at Mono.Btls.MonoBtlsContext.ProcessHandshake () [0x00048] in <0fefc3aa790d43deae7606c7f3a13e54>:0 
  at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000a1] in <0fefc3aa790d43deae7606c7f3a13e54>:0 
  at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
  at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <0fefc3aa790d43deae7606c7f3a13e54>:0 
  at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000ff] in <0fefc3aa790d43deae7606c7f3a13e54>:0 
  at Mono.Net.Security.AsyncProtocolRequest.StartOperation (System.Threading.CancellationTo
```

**Comment by luhenry** [comment]
@monojenkins backport to 2019-02
@monojenkins backport to 2018-12
@monojenkins backport to 2018-10
@monojenkins backport to 2018-08

**Pull request merged**
