### PR TITLE
[mini] don't do regular store if it's already handled by the unaligned case

### PR DESCRIPTION
**Pull request by lewurm**
fixes (for the runtime part): https://bugzilla.xamarin.com/show_bug.cgi?id=60865

now at least the runtime doesn't crash anymore:

``` 
Starting:    net_4_x_System.Runtime.CompilerServices.Unsafe_xunit-test
    System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Double [FAIL]
      Assert.Equal() Failure
      Expected: 3.42
      Actual:   -1.78354552337557E+259
      Stack Trace:
          at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Double () [0x0002e] in /Users/bernhardu/work/mono/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:701
          at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/bernhardu/work/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
    System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Double [FAIL]
      Assert.Equal() Failure
      Expected: 3.42
      Actual:   5.30866773685859E-315
      Stack Trace:
          at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Double () [0x00034] in /Users/bernhardu/work/mono/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:664
          at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/bernhardu/work/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
    System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Double [FAIL]
      Assert.Equal() Failure
      Expected: 3.42
      Actual:   5.30866773685859E-315
      Stack Trace:
          at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Double () [0x00020] in /Users/bernhardu/work/mono/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:628
          at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/bernhardu/work/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
    System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Double [FAIL]
      Assert.Equal() Failure
      Expected: 3.42
      Actual:   -1.78354552337557E+259
      Stack Trace:
          at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Double () [0x00044] in /Users/bernhardu/work/mono/external/corefx/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs:741
          at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/bernhardu/work/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
  Finished:    net_4_x_System.Runtime.CompilerServices.Unsafe_xunit-test
=== TEST EXECUTION SUMMARY ===
   net_4_x_System.Runtime.CompilerServices.Unsafe_xunit-test  Total: 116, Errors: 0, Failed: 4, Skipped: 0, Time: 0.904s
```

imho the corefx tests are wrong, because they assume a certain layout. For 32bit it should look like this:
```patch
diff --git a/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs b/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs
index 4a71020ae3..9a899c4f5f 100644
--- a/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs
+++ b/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs
@@ -623,7 +623,7 @@ namespace System.Runtime.CompilerServices
         {
             byte[] unaligned = Int32Double.Unaligned(123456789, 3.42);

-            double actual = Unsafe.ReadUnaligned<double>(ref unaligned[9]);
+            double actual = Unsafe.ReadUnaligned<double>(ref unaligned[5]);

             Assert.Equal(3.42, actual);
         }
@@ -659,7 +659,7 @@ namespace System.Runtime.CompilerServices

             fixed (byte* p = unaligned)
             {
-                double actual = Unsafe.ReadUnaligned<double>(p + 9);
+                double actual = Unsafe.ReadUnaligned<double>(p + 5);

                 Assert.Equal(3.42, actual);
             }
@@ -695,7 +695,7 @@ namespace System.Runtime.CompilerServices
         {
             byte[] unaligned = new byte[sizeof(Int32Double) + 1];

-            Unsafe.WriteUnaligned(ref unaligned[9], 3.42);
+            Unsafe.WriteUnaligned(ref unaligned[5], 3.42);

             double actual = Int32Double.Aligned(unaligned).Double;
             Assert.Equal(3.42, actual);
@@ -734,7 +734,7 @@ namespace System.Runtime.CompilerServices

             fixed (byte* p = unaligned)
             {
-                Unsafe.WriteUnaligned(p + 9, 3.42);
+                Unsafe.WriteUnaligned(p + 5, 3.42);
             }

             double actual = Int32Double.Aligned(unaligned).Double;
```

before I get in touch with the corefx team, can someone confirm I'm on the right track?

### CODE REVIEW

**Comment by vargaz** [comment]
This shouldn't be needed, the x86 backend should be able to handle this.

**Comment by lewurm** [comment]
the generated code looks like this (log output from this code: https://github.com/mono/mono/blob/c5d3bf2428e042bc848bde3b64cb203c8b4538e5/mono/mini/mini-codegen.c#L2170-L2315 )

without the patch:
```
processing:     0  r8const %fr0 <- [3.420000]
        [%fr0]
processing:     0  storer8_membase_reg [%ebp + 0xffffffe4] <- %fr0
        []
processing:     0  loadr8_membase %fr0 <- [%ebp + 0xffffffe4]
        [%fr0]
processing:     0  storer8_membase_reg [%ebp + 0xffffffdc] <- %fr0
        []
processing:     0  loadi1_membase %edx <- [%ebp + 0xffffffdc]
        []
processing:     0  storei1_membase_reg [%ecx] <- %edx
        []
processing:     0  loadi1_membase %edx <- [%ebp + 0xffffffdd]
        []
processing:     0  storei1_membase_reg [%ecx + 0x1] <- %edx
        []
[...]
processing:     0  loadi1_membase %edx <- [%ebp + 0xffffffe3]
        []
processing:     0  storei1_membase_reg [%ecx + 0x7] <- %edx
        []
processing:     0  storer8_membase_reg [%ecx] <- %fr0
* Assertion at mini-codegen.c:2264, condition `sp > 0' not met
```

with the patch:
```
processing:     0  r8const %fr0 <- [3.420000]
        [%fr0]
processing:     0  storer8_membase_reg [%ebp + 0xffffffe4] <- %fr0
        []
processing:     0  loadr8_membase %fr0 <- [%ebp + 0xffffffe4]
        [%fr0]
processing:     0  storer8_membase_reg [%ebp + 0xffffffdc] <- %fr0
        []
processing:     0  loadr8_membase %fr0 <- [%ebp + 0xffffffdc]
        [%fr0]
processing:     0  loadi1_membase %edx <- [%ebp + 0xffffffdc]
        [%fr0]
processing:     0  storei1_membase_reg [%ecx] <- %edx
        [%fr0]
processing:     0  loadi1_membase %edx <- [%ebp + 0xffffffdd]
        [%fr0]
processing:     0  storei1_membase_reg [%ecx + 0x1] <- %edx
        [%fr0]
[...]
processing:     0  loadi1_membase %edx <- [%ebp + 0xffffffe3]
        [%fr0]
processing:     0  storei1_membase_reg [%ecx + 0x7] <- %edx
        [%fr0]
processing:     0  storer8_membase_reg [%ecx] <- %fr0
        []
processing:     0  il_seq_point il: 0x22, nonempty-stack
```

@vargaz where in the x86 backend would this be handled?

**Comment by vargaz** [comment]
Its handled in that code mini-codegen.c, but thats only enabled on x86. We should have gotten rid of the whole fp stack code a long time ago.

**Comment by lewurm** [comment]
@vargaz it looks like this case isn't handled by the fpstack code, how do you suggest to fix it instead?

**Comment by vargaz** [comment]
The best would be to fix that code, but its very complicated. So if this fixes the issue, and doesn't introduce too much overhead, I guess we can do it this way.

**Comment by lewurm** [comment]
@vargaz okay. I don't see how this could be done with the current code without major code changes.

I'm suggesting this fix for the test in `corefx`: https://github.com/lewurm/corefx/commit/9f756e866a9ff9aab6fc24cbc6341611222943fd

Let's see what CI says. If it looks okay, I'll submit a PR to the `corefx` repo.

**Comment by kumpera** [comment]
This is quite odd. They align double to 8 even on 32bits osx?

**Comment by marek-safar** [comment]
@lewurm could you rebase the PR

**Comment by lewurm** [comment]
the workaround for FP stack isn't needed, the generated code was wrong anyway. the new patch also fixes the NRE problem on arm

**Comment by lewurm** [comment]
CI looks good. In order to land this PR, we need this https://github.com/dotnet/corefx/pull/25594 in our corefx fork. /cc @marek-safar (not urgent, just keeping it here as a note).

**Comment by marek-safar** [comment]
@lewurm could you remove the test change. I'll land it separately after corefx bump

**Comment by lewurm** [comment]
@marek-safar sounds good, done.

**Pull request merged**
