### PR TITLE
A basic Doxyfile.

### PR DESCRIPTION
**Pull request by evincarofautumn**
Bare minimum Doxygen configuration with dependency graphs.

### CODE REVIEW

**Comment by tritao** [comment]
This would be interesting to merge, but ideally we'd also do some integration of the generated docs somewhere. Can you modify Mono's Wrench lane to have a `doxygen` step before/after `monodoc` and generate the docs?

**Comment by kumpera** [comment]
whitelist

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by akoeplinger** [comment]
Squashed this into master with https://github.com/mono/mono/commit/980fc8d8cd3bc9e97c9755fcc6c745e9b0a3d2b4. I also switched to SVG instead of PNG images as it was **much** faster to generate. Thanks!

**Pull request closed without merging**
