### PR TITLE
Fix unknown-length requests being treated as if they are fully preloaded.

### LINKED ISSUE #6821: Unknown-length request bodies are treated as fully loaded request bodies
## Steps to Reproduce

1. Compile and run this program. The program must be in a directory named `bin`.

```cs
using System;
using System.IO;
using System.Text;
using System.Web;
using System.Web.Hosting;

namespace MonoWebInputRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var host = (Host)ApplicationHost.CreateApplicationHost(typeof(Host), "/", Path.GetDirectoryName(Environment.CurrentDirectory));
            host.Run();
        }
    }

    internal class Host : MarshalByRefObject
    {
        public void Run()
        {
            HttpApplication.RegisterModule(typeof(Module));
            HttpRuntime.ProcessRequest(new Request());
        }
    }

    internal class Module : IHttpModule
    {
        public void Dispose()
        {
        }

        public void Init(HttpApplication app)
        {
            app.BeginRequest += App_BeginRequest; 
        }

        private void App_BeginRequest(object sender, EventArgs e)
        {
            var app = (HttpApplication)sender;
            app.Context.RemapHandler(new Handler());
        }
    }

    internal class Handler : IHttpHandler
    {
        public bool IsReusable => true;

        public void ProcessRequest(HttpContext context)
        {
            using (var reader = new StreamReader(context.Request.InputStream))
            {
                Console.WriteLine(reader.ReadToEnd());
            }
            Console.WriteLine("Done");
        }
    }

    internal class Request : HttpWorkerRequest
    {
        public override void EndOfRequest() { }
        public override void FlushResponse(bool finalFlush) { }
        public override string GetHttpVerbName() { return "POST"; }
        public override string GetHttpVersion() { return "HTTP/1.1"; }
        public override string GetLocalAddress() { return "127.0.0.1"; }
        public override int GetLocalPort() { return 80; }
        public override string GetQueryString() { return string.Empty; }
        public override string GetRawUrl() { return "/"; }
        public override string GetRemoteAddress() { return "127.0.0.1"; }
        public override int GetRemotePort() { return 12345; }
        public override string GetUriPath() { return "/"; }
        public override void SendKnownResponseHeader(int index, string value) { }
        public override void SendResponseFromFile(string filename, long offset, long length) { }
        public override void SendResponseFromFile(IntPtr handle, long offset, long length) { }
        public override void SendResponseFromMemory(byte[] data, int length) { Console.WriteLine(Encoding.UTF8.GetString(data, 0, length)); }
        public override void SendStatus(int statusCode, string statusDescription) { }
        public override void SendUnknownResponseHeader(string name, string value) { }
        public override string GetFilePath() { return "/"; }

        private readonly MemoryStream stream = new MemoryStream(Encoding.UTF8.GetBytes("Hello, World!"));
        public override int ReadEntityBody(byte[] buffer, int size)
        {
            return stream.Read(buffer, 0, size);
        }
    }
}
```

## Current Behavior

Mono result:

```

Done
```

## Expected Behavior

Microsoft .NET result:

```
Hello, World!
Done
```

### On which platforms did you notice this

[ ] macOS
[x] Linux
[x] Windows

**Version Used**:

Linux:
```
Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:19:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

Windows:
```
Mono JIT compiler version 5.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

### Diagnosis

The problem is this line:

https://github.com/mono/mono/blob/4b8e0bea1980f0725f4f48b8cf30d06785ba304c/mcs/class/System.Web/System.Web/HttpRequest.cs#L844

The content length is -1 because no content-length header is present in the request (as is the case for a chunked request).

This regression was introduced 11 years ago in 5604a5d3b4719c667cf35c04082c3fa290b96c95.

### PR DESCRIPTION
**Pull request by BenLubar**
Fixes #6821

### CODE REVIEW

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
Thanks for your suggested fix. In your github issue, you provided a repro for your issue. Do you think it's possible to add it as part of the test suite?

For the code parts, I think @baulig would be the right person to review. Martin, can you have a look please?

**Comment by marek-safar** [comment]
approve

**Comment by luhenry** [comment]
@monojenkins build Windows x64

**Comment by luhenry** [comment]
@monojenkins build Windows i386

**Comment by luhenry** [comment]
@monojenkins build OS X x64

**Comment by luhenry** [comment]
@monojenkins build OS X i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Coop GC

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by luhenry** [comment]
@monojenkins build Linux i386 Coop GC

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv5

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Pull request merged**
