### PR TITLE
[System.Windows.Forms] Fix custom test targets in makefile.

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by filipnavara** [comment]
Broken since https://github.com/mono/mono/commit/e6de24c2d196b064e64aeea6e45350e985a1bb23.

**Comment by akoeplinger** [comment]
Hmm, looks like due to e6de24c the WinForms tests got skipped (since simple-test.exe failed) and in the meantime we had some regression as they hang now...

**Comment by filipnavara** [comment]
I am running the unit tests on OS X w/ X11 backend just fine, but I haven't recompiled the runtime in quite a while.

**Comment by akoeplinger** [comment]
It seems to hang in `***** MonoTests.System.Windows.Forms.PrintPreviewControlTest.StartPage` so I assume it is caused by https://github.com/mono/mono/pull/7493, could you try disabling the test for now?

**Comment by filipnavara** [comment]
It hangs because there are no printers on the machine. I will add check to the test and skip it.

**Pull request merged**
