### PR TITLE
[GTK] Bump bockbuild for GtkViewport autoscrolling patch.

### PR DESCRIPTION
**Pull request by bratsche**
Need to get a package to test with first. Don't merge please.

### CODE REVIEW

**Comment by bratsche** [comment]
@monojenkins build OS X Package

**Comment by bratsche** [comment]
Need to merge https://github.com/mono/bockbuild/pull/126 first, then re-bump this one.

**Comment by akoeplinger** [comment]
@bratsche I merged the bockbuild PR and can do a manual bump in all the required branches so we don't need to waste CI resources building again. Which branches should it be backported to?

**Comment by bratsche** [comment]
@akoeplinger I talked to @sevoku and he said we need this in Mono 6.6, whatever branch that is.

**Comment by bratsche** [comment]
@akoeplinger 2019-08 and 2019-10

**Comment by akoeplinger** [comment]
Manually backport to 2019-08 and 2019-10.

**Pull request merged**
