### PR TITLE
Fix a bug in registry API implementation where had wrong assumptions about possible registry size.

### PR DESCRIPTION
**Pull request by TautvydasZilys**
I used reference source as inspiration for the changes.

### CODE REVIEW

**Comment by marek-safar** [comment]
approve

**Comment by marek-safar** [comment]
@ntherning could you guys review the change

**Comment by ntherning** [comment]
The changes don't follow the Mono coding guidelines concerning spaces and braces:

[Where to put spaces](http://www.mono-project.com/community/contributing/coding-guidelines/#where-to-put-spaces)
[Where to put braces](http://www.mono-project.com/community/contributing/coding-guidelines/#where-to-put-braces)

Not sure it matters too much but there's potentially a race between counting the number of values/subkeys and retrieving them. If another process, thread deletes a key in between the returned arrays might end up containing `null`s. Maybe we should filter them out or append to a temp list only after a successful call into the native API for enumerating keys/values?

**Comment by TautvydasZilys** [comment]
They do this in reference source, so I'm not sure whether that is a problem.

I'll fix up the code convention.

**Comment by TautvydasZilys** [comment]
I **think** I got the code convention right. Let me know if you find any inconsistencies there.

**Comment by ntherning** [comment]
LGTM!

**Pull request merged**
