### PR TITLE
[System]: Make `MobileAuthenticatedStream's read buffer large enough to hold a full TLS record.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins backport 2018-08

**Comment by baulig** [comment]
This is the fix for that.

**Comment by nealef** [comment]
Ah, I thought you'd built it on the code base after you'd backed out the original PR. Great news. Thanks!

**Comment by akoeplinger** [comment]
We'd still need to revert the revert that we did in 2018-06 if we want it there :)

**Comment by nealef** [comment]
Please!!

**Comment by nealef** [comment]
Do you want me to generate a PR for 2018-06?

**Comment by nealef** [comment]
For 2018-06 is it simpler just to revert #10393 reapply #10254 then reapply #10393?

**Comment by nealef** [comment]
Created PR #10469

**Pull request merged**
