### PR TITLE
Bump msbuild to track xplat-master

### PR DESCRIPTION
**Pull request by radical**
.. to run msbuild with `--assembly-loader=strict`.

### CODE REVIEW

**Comment by radical** [comment]
This needs https://github.com/mono/mono/pull/15266 to be merged first.

**Comment by lewing** [comment]
#15266 has merged

**Comment by radical** [comment]
`linux x64 interpreter`: unrelated failure: `Test collection for System.Threading.ThreadPools.Tests.ThreadPoolTests.System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest`

`linux ARMv5` failed with:
```
17:33:02 $ sudo /usr/sbin/pbuilder --update --basetgz /home/builder/jenkins/workspace/test-mono-pull-request-armel/debian-9-armel-stable/debian-9-armel-stable.tgz --extrapackages "xvfb xauth mono-devel git python wget bc build-essential libtool autoconf automake gettext iputils-ping cmake lsof libkrb5-dev linux-perf linux-tools zip perl"
17:33:02 W: /home/builder/.pbuilderrc does not exist
17:33:10 W: No local /etc/mailname to copy, relying on /var/cache/pbuilder/build/17521/etc/mailname to be correct
17:33:16 E: Could not open file /var/lib/apt/lists/ftp.debian.org_debian_dists_stretch-backports_main_binary-armel_Packages.diff_Index - open (2: No such file or directory)
17:33:17 FATAL: Installing additional packages in chroot environment failed.
17:33:17 FATAL: Failure
```

**Comment by radical** [comment]
Bumped again to get the shared compiler change in msbuild.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by radical** [comment]
Unrelated test failure: `DebuggerTests.IsDynamicAssembly`

**Comment by lewing** [comment]
@monojenkins Linux x64 Interpreter

**Comment by lewing** [comment]
@monojenkins build Linux x64 Interpreter

**Pull request merged**
