### PR TITLE
[amd64] Fix a check in mono_emit_stack_alloc ().

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by lewurm** [comment]
ouch.  does that fix some specific issue you have seen, or was this discovered by browsing through code?

**Comment by vargaz** [comment]
Somebody reported it.

**Comment by lewurm** [comment]
from https://jenkins.mono-project.com/job/test-mono-pull-request-i386-osx/3620/parsed_console/log_content.html#WARNING1, it's new to me, but happens on i386, so it can't be related:

```
=============== EOF ===============
=============== finalizer-wait.exe.stderr ===============

Unhandled Exception:
System.ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.
  at (wrapper managed-to-native) System.Globalization.CultureInfo:get_current_locale_name ()
  at System.Globalization.CultureInfo.ConstructCurrentCulture () [0x0000d] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Globalization.CultureInfo.get_UserDefaultCulture () [0x00000] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Threading.Thread.GetCurrentCultureNoAppX () [0x00010] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Threading.Thread.get_CurrentCulture () [0x00000] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Globalization.NumberFormatInfo.get_CurrentInfo () [0x00005] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Globalization.NumberFormatInfo.GetInstance (System.IFormatProvider formatProvider) [0x00051] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Int32.ToString (System.String format, System.IFormatProvider provider) [0x00000] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x0029f] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00023] in <0151c410a3d3437ab2411f20565192d6>:0 
  at System.String.Format (System.String format, System.Object arg0) [0x00008] in <0151c410a3d3437ab2411f20565192d6>:0 
  at P.Finalize () [0x0000e] in <3460576f4c0a4368a8505915ab78588a>:0 
```

**Comment by akoeplinger** [comment]
I guess this should be backported to 2017-06 and -04 ?

**Comment by vargaz** [comment]
Its not a real problem.

**Pull request merged**
