### PR TITLE
[WIP/DON'T MERGE] Import MS CoreCLR runtime tests 

### PR DESCRIPTION
**Pull request by akoeplinger**
Sooo, I took a look at the tests in https://github.com/dotnet/coreclr to see whether Mono passes them.

Here's the result from running `make runtest` in `./mono/tests`:

```
2539 test(s) passed. 83 test(s) did not pass.

Failed tests:

ms-coreclr-tests/src/JIT/CodeGenBringUpTests/Localloc.exe
ms-coreclr-tests/src/JIT/Directed/coverage/importer/badendfinally.exe
ms-coreclr-tests/src/JIT/Directed/coverage/importer/byrefsubbyref1.exe
ms-coreclr-tests/src/JIT/Directed/coverage/oldtests/lcliimpl.exe
ms-coreclr-tests/src/JIT/Directed/coverage/oldtests/subbyref.exe
ms-coreclr-tests/src/JIT/Directed/intrinsic/pow/pow1.exe
ms-coreclr-tests/src/JIT/Directed/leave/filter3.exe
ms-coreclr-tests/src/JIT/Directed/lifetime/lifetime2.exe
ms-coreclr-tests/src/JIT/Directed/newarr/newarr.exe
ms-coreclr-tests/src/JIT/Directed/PREFIX/unaligned/1/arglist64.exe
ms-coreclr-tests/src/JIT/Directed/PREFIX/unaligned/2/arglist64.exe
ms-coreclr-tests/src/JIT/Directed/PREFIX/unaligned/4/arglist64.exe
ms-coreclr-tests/src/JIT/Directed/PREFIX/volatile/1/arglist64.exe
ms-coreclr-tests/src/JIT/Directed/refbyref/byrefconvert.exe
ms-coreclr-tests/src/JIT/Directed/zeroinit/init_byte.exe
ms-coreclr-tests/src/JIT/IL_Conformance/Old/Conformance_Base/ldc_conv_ovf_r8_i4.exe
ms-coreclr-tests/src/JIT/IL_Conformance/Old/Conformance_Base/ldc_conv_ovf_r8_i8.exe
ms-coreclr-tests/src/JIT/IL_Conformance/Old/Conformance_Base/ldc_conv_ovf_r8_i.exe
ms-coreclr-tests/src/JIT/jit64/opt/osr/osr015.exe
ms-coreclr-tests/src/JIT/jit64/opt/rngchk/ArrayWithFunc.exe
ms-coreclr-tests/src/JIT/jit64/opt/rngchk/RngchkStress2.exe
ms-coreclr-tests/src/JIT/jit64/regress/phoenix/62322/test.exe
ms-coreclr-tests/src/JIT/Methodical/Arrays/huge_struct.exe
ms-coreclr-tests/src/JIT/Methodical/Boxing/misc/enum.exe
ms-coreclr-tests/src/JIT/Methodical/Boxing/misc/enum.exe
ms-coreclr-tests/src/JIT/Methodical/cctor/simple/Desktop/prefldinit3.exe
ms-coreclr-tests/src/JIT/Methodical/int64/arrays/hugedim.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/25params/25param1b.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/25params/25param3b.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/25params/25paramMixed.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/implicit/i4u2.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/implicit/ii1.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/implicit/ii2.exe
ms-coreclr-tests/src/JIT/Methodical/Invoke/implicit/iu2.exe
ms-coreclr-tests/src/JIT/Methodical/refany/array2.exe
ms-coreclr-tests/src/JIT/Methodical/refany/array2.exe
ms-coreclr-tests/src/JIT/Methodical/refany/array3.exe
ms-coreclr-tests/src/JIT/Methodical/tailcall/deep_array_nz.exe
ms-coreclr-tests/src/JIT/Methodical/varargs/callconv/gc_ctor.exe
ms-coreclr-tests/src/JIT/Methodical/varargs/callconv/val_ctor.exe
ms-coreclr-tests/src/JIT/Methodical/varargs/misc/Dev10_615402.exe
ms-coreclr-tests/src/JIT/Methodical/VT/callconv/jumper4.exe
ms-coreclr-tests/src/JIT/Methodical/VT/callconv/jumper5.exe
ms-coreclr-tests/src/JIT/Methodical/xxblk/cpblk3.exe
ms-coreclr-tests/src/JIT/opt/JitMinOpts/Perf/CodeSize0.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-EJIT/V1-M11-Beta1/b44018/b44018.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-EJIT/V1-M12-Beta2/b26323/b26323.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-Beta1/b178119/hugemthfrm.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-Beta1/b178128/hugestruct.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-M01/b13452/b13452.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-M02/b102962/t2.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-M02/b102962/t.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/t1.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/t.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b16241/b16241.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b16895/b16895.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b25459/b25459.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b27883/b27883.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b27917/b27917.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b28597/b28597.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b30125/b30125.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b30864/b30864.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b06595/b06595.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M10/b08107/b08107.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M11-Beta1/b35784/b35784.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b31283/b31283.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b50027/b50027.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b59857/b59857.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b59858/b59858.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b70354/b70354.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b91223/b91223.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b091942/nullref.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b353858/b353858.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V2.0-RTM/b471305/b471305.exe
ms-coreclr-tests/src/JIT/Regression/CLR-x86-JIT/V2.0-RTM/b475589/b475589.exe
ms-coreclr-tests/src/JIT/Regression/Dev11/Dev11_468598/Test_HndIndex_10_Reordered.exe
ms-coreclr-tests/src/JIT/Regression/Dev11/Dev11_b473131/b473131_struct.exe
ms-coreclr-tests/src/JIT/Regression/Dev11/DevDiv2_11321/DevDiv2_11321.exe
ms-coreclr-tests/src/JIT/Regression/JitBlue/DevDiv_816617/DevDiv_816617.exe
ms-coreclr-tests/src/JIT/Regression/v4/dev10_804810/dev10_804810.exe
ms-coreclr-tests/src/JIT/Regression/VS-ia64-JIT/M00/b108366/bug.exe
ms-coreclr-tests/src/JIT/Regression/VS-ia64-JIT/V1.2-M02/b10828/redundant.exe
ms-coreclr-tests/src/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/test.exe
make: *** [runtest] Error 1
```

This PR isn't intended to be merged as-is, I just wanted to get the discussion started. Rather than me filing 80 tickets on bugzillla, I think it's much easier if someone from the runtime team pulls down my [branch](https://github.com/akoeplinger/mono/tree/coreclr-tests) and takes a look at the failures :smile:

Notes:
- the CoreCLR tests are very similar to the Mono runtime tests, except that they return exit code == 100 on success (I hacked this into the test drivers for now)
- the IL tests should be used completely, except for the ones ilasm isn't able to process (likely due to ilasm bugs)
- the C# tests should be used almost completely. I left those out that aren't simple "start process, read exit code" (i.e. referencing another library etc.), there are only a handful of those.
- there's an interesting GC stress test framework which I also haven't tried yet as it needs some changes to work
- I just copied the test sources as a) the whole coreclr repo is quite large and b) I didn't want to mess around with submodules yet. I'm impartial as to whether a submodule is the better option in the future.

### CODE REVIEW

**Comment by alexrp** [comment]
How long does it take to execute all these on a modern amd64 machine?

**Comment by akoeplinger** [comment]
On my ~2011 quadcore Core i5 it takes about 12 minutes, but there are a couple of tests that hang and are aborted after 120secs, so that may dilute the timing. We can always move them to a separate make target and e.g. only run on CI.

**Comment by kumpera** [comment]
I asked an internal team to figure out a way to setup a partial fork of the CoreCLR repo.

@akoeplinger can you share a gist of the failures so we can figure out how bad are they?

**Comment by Therzok** [comment]
Wouldn't a git subtree splitting into its own repo and manually syncing it from time to time work?

http://stackoverflow.com/a/17864475

**Comment by akoeplinger** [comment]
@kumpera https://gist.github.com/akoeplinger/c1b8009299f2fd3486bc
From what I see, there are mainly two errors: a) runtime asserts b) invalid IL code errors. The asserts do sound more bad to me, but I haven't looked closer.

@Therzok yeah, I played with git subtree, looks like that should work. Otherwise, simply Ctrl+C, Ctrl+V doesn't seem too bad to me as well, given that we'll likely never see any updates to the upstream test sources.

**Comment by jasonwilliams200OK** [comment]
@akoeplinger, once the assertion failures are sorted out, will it make sense to have a submodule to dotnet/coreclr tests directory so CI can also test the future PRs. Probably with a thin wrapper to translate error codes.

**Comment by akoeplinger** [comment]
@jasonwilliams200OK yeah, I think a submodule will make the most sense.

**Comment by akoeplinger** [comment]
Superseded by #2129.

**Pull request closed without merging**
