### PR TITLE
Restore checking in mono_find_jit_icall_info esp. but not only for PowerPC.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@NattyNarwhal

**Comment by NattyNarwhal** [comment]
Continuing from #14622, this trips the assert now. My changes from then left in for the extra printf:

```
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64-ibm-aix6.1.0.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/calvin/mono-build/mono/mono/mini/.libs/lt-mono-sgen...done.
(gdb) break marshal.c:2914
No source file named marshal.c.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (marshal.c:2914) pending.
(gdb) run
Starting program: /home/calvin/mono-build/mono/mono/mini/.libs/lt-mono-sgen --trace=all --config /home/calvin/mono-build/mono/runtime/etc/mono/config .//class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mcs.exe /warn:0 /noconfig /langversion:latest /r:System.dll /r:mscorlib.dll /out:build/deps/basic-profile-check.exe build/common/basic-profile-check.cs
[New Thread 1]
Mono: Config attempting to parse: '/home/calvin/mono-build/mono/runtime/etc/mono/config'.
Mono: process_set_name: using [.//class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mcs.exe] as prog name
Mono: mono_w32handle_new: create Process handle 110015578
Mono: Assembly Loader probing location: '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll'.
Mono: Image addref mscorlib[110066730] (asmctx DEFAULT) -> /home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll[1100651b0]: 2
Mono: Prepared to set up assembly 'mscorlib' (/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll)
[New Thread 258]
Mono: AOT: image '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll.so' not found:     0509-022 Cannot load module /home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll.so.
        0509-026 System error: A file or directory in the path name does not exist.
Mono: AOT: image '/usr/local/lib/mono/aot-cache/ppc/mscorlib.dll.so' not found:         0509-022 Cannot load module /usr/local/lib/mono/aot-cache/ppc/mscorlib.dll.so.
        0509-026 System error: A file or directory in the path name does not exist.
Mono: Assembly Loader loaded assembly from location: '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll'.
Mono: Config attempting to parse: '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll.config'.
Mono: Config attempting to parse: '/home/calvin/mono-build/mono/runtime/etc/mono/assemblies/mscorlib/mscorlib.config'.
 ** mono_resolve_patch_target ** patch_info 1100dd8a0 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 268
 ** mono_resolve_patch_target ** patch_info 1100dd868 patch_info->type 3
 ** mono_resolve_patch_target ** patch_info 1100dd830 patch_info->type 3
 ** mono_resolve_patch_target ** patch_info 1100dd7f8 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 267
 ** mono_resolve_patch_target ** patch_info fffffffffffdd88 patch_info->type 32
[Switching to Thread 1]

Thread 2 hit Breakpoint 1, mono_marshal_get_icall_wrapper (
    callinfo=0x9001000b4c48fd0 <mono_jit_icall_info+14000>,
    check_exceptions=268468920) at marshal.c:2914
2914    marshal.c: A file or directory in the path name does not exist..
(gdb) continue
Continuing.
 ** mono_resolve_patch_target ** patch_info fffffffffffdcc8 patch_info->type 38
 ** mono_resolve_patch_target ** patch_info fffffffffffdd88 patch_info->type 32
 ** mono_resolve_patch_target ** patch_info 1100ea3e8 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 268
 ** mono_resolve_patch_target ** patch_info 1100ea3a0 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 0
* Assertion at ../../mono/metadata/jit-icall-reg.h:411, condition `id != MONO_JIT_ICALL_ZeroIsReserved' not met, function:mono_find_jit_icall_info_internal, mono_resolve_patch_target:1375


Thread 2 received signal SIGABRT, Aborted.
0x0900000000531ed4 in pthread_kill () from /usr/lib/libpthread.a(shr_xpg5_64.o)
(gdb)
```

**Comment by jaykrell** [comment]
@NattyNarwhal stack? :(

**Comment by jaykrell** [comment]
I’ll try to place more asserts & rerereview code

**Comment by NattyNarwhal** [comment]
Reran:

```
* Assertion at ../../mono/metadata/jit-icall-reg.h:411, condition `id != MONO_JIT_ICALL_ZeroIsReserved' not met, function:mono_find_jit_icall_info_internal, mono_resolve_patch_target:1375


Thread 2 received signal SIGABRT, Aborted.
0x0900000000531ed4 in pthread_kill () from /usr/lib/libpthread.a(shr_xpg5_64.o)
(gdb) bt
#0  0x0900000000531ed4 in pthread_kill () from /usr/lib/libpthread.a(shr_xpg5_64.o)
#1  0x090000000053170c in _p_raise () from /usr/lib/libpthread.a(shr_xpg5_64.o)
#2  0x090000000002bb50 in raise () from /usr/lib/libc.a(shr_64.o)
#3  0x09000000000825e8 in abort () from /usr/lib/libc.a(shr_64.o)
#4  0x0900000111e81608 in monoeg_assert_abort () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#5  0x0900000112118e18 in mono_log_write_logfile () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#6  0x0900000111eac87c in structured_log_adapter () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#7  0x0900000111e81420 in monoeg_g_logv_nofree.part () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#8  0x0900000111e81b84 in monoeg_assertion_message () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#9  0x0900000111e897d8 in mono_resolve_patch_target () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#10 0x0900000111e7c43c in mono_codegen () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#11 0x0900000111e7d4dc in mini_method_compile () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#12 0x0900000111e7f780 in mono_jit_compile_method_inner () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#13 0x0900000111e8aaac in mono_jit_compile_method_with_opt () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#14 0x0900000111e8c9d0 in mono_jit_runtime_invoke () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#15 0x0900000111f0186c in do_runtime_invoke () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#16 0x0900000111f83af0 in create_exception_two_strings () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#17 0x0900000111f84488 in mono_exception_from_name_two_strings_checked () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#18 0x0900000111f470e0 in create_domain_objects () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#19 0x0900000111f4a434 in mono_runtime_init_checked () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#20 0x0900000111e91030 in mini_init () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#21 0x090000011222bf2c in mono_main () from /home/calvin/mono-build/mono/mono/mini/.libs/libmonosgen-2.0.a(libmonosgen-2.0.so.1)
#22 0x0000000100000634 in main (argc=12, argv=0xffffffffffff288) at main-sgen.c:453

```

Sorry for delay, was busy IRL. I don't show any variables because getting a fatal signal like that trashes information like that :/

**Comment by jaykrell** [comment]
Maybe a memory corruptor???

**Comment by jaykrell** [comment]
We can walk this data every so often & validate it, i guess.

**Comment by NattyNarwhal** [comment]
put some more printf in myself:

```
(gdb) break marshal.c:2914
No source file named marshal.c.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (marshal.c:2914) pending.
(gdb) run
Starting program: /home/calvin/mono-build/mono/mono/mini/.libs/lt-mono-sgen --trace=all --config /home/calvin/mono-build/mono/runtime/etc/mono/config .//class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mcs.exe /warn:0 /noconfig /langversion:latest /r:System.dll /r:mscorlib.dll /out:build/deps/basic-profile-check.exe build/common/basic-profile-check.cs
[New Thread 1]
Mono: Config attempting to parse: '/home/calvin/mono-build/mono/runtime/etc/mono/config'.
Mono: process_set_name: using [.//class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mcs.exe] as prog name
Mono: mono_w32handle_new: create Process handle 110015578
Mono: Assembly Loader probing location: '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll'.
Mono: Image addref mscorlib[110067710] (asmctx DEFAULT) -> /home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll[110066190]: 2
Mono: Prepared to set up assembly 'mscorlib' (/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll)
[New Thread 258]
Mono: AOT: image '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll.so' not found:     0509-022 Cannot load module /home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll.so.
        0509-026 System error: A file or directory in the path name does not exist.
Mono: AOT: image '/usr/local/lib/mono/aot-cache/ppc/mscorlib.dll.so' not found:         0509-022 Cannot load module /usr/local/lib/mono/aot-cache/ppc/mscorlib.dll.so.
        0509-026 System error: A file or directory in the path name does not exist.
Mono: Assembly Loader loaded assembly from location: '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll'.
Mono: Config attempting to parse: '/home/calvin/mono-build/mono/mcs/class/lib/monolite-unix/62731146-81CF-4D61-826D-9A8DDED14432/mscorlib.dll.config'.
Mono: Config attempting to parse: '/home/calvin/mono-build/mono/runtime/etc/mono/assemblies/mscorlib/mscorlib.config'.
 ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type 7 next 1100de848 data (8 bytes selected from target member) 10cb4f14a28
 ** mono_resolve_patch_target ** patch_info 1100de880 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 268
 ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type 3 next 1100de810 data (8 bytes selected from target member) 1100d6c90
 ** mono_resolve_patch_target ** patch_info 1100de848 patch_info->type 3
 ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type 3 next 1100de7d8 data (8 bytes selected from target member) 1100d6968
 ** mono_resolve_patch_target ** patch_info 1100de810 patch_info->type 3
 ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type 7 next 0 data (8 bytes selected from target member) 10bb4f14a10
 ** mono_resolve_patch_target ** patch_info 1100de7d8 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 267
 ** mono_resolve_patch_target ** patch_info fffffffffffddb8 patch_info->type 32
[Switching to Thread 1]

Thread 2 hit Breakpoint 1, mono_marshal_get_icall_wrapper (callinfo=0x9001000b4f4b050 <mono_jit_icall_info+14000>, check_exceptions=268468920) at marshal.c:2914
2914    marshal.c: A file or directory in the path name does not exist..
(gdb) continue
Continuing.
 ** mono_resolve_patch_target ** patch_info fffffffffffdcf8 patch_info->type 38
 ** mono_resolve_patch_target ** patch_info fffffffffffddb8 patch_info->type 32
 ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type 7 next 1100eb380 data (8 bytes selected from target member) 10cb4f14a28
 ** mono_resolve_patch_target ** patch_info 1100eb3c8 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 268
 ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type 7 next 1100eb358 data (8 bytes selected from target member) 65
 ** mono_resolve_patch_target ** patch_info 1100eb380 patch_info->type 7
 ** MONO_PATCH_INFO_JIT_ICALL_ID ** 0
* Assertion at ../../mono/metadata/jit-icall-reg.h:411, condition `id != MONO_JIT_ICALL_ZeroIsReserved' not met, function:mono_find_jit_icall_info_internal, mono_resolve_patch_target:1375
```

```diff
diff --git a/external/linker b/external/linker
--- a/external/linker
+++ b/external/linker
@@ -1 +1 @@
-Subproject commit 4507ce9c5d5bbae9e39dc1af1f77a1edb2f24164
+Subproject commit 4507ce9c5d5bbae9e39dc1af1f77a1edb2f24164-dirty
diff --git a/mono/metadata/marshal.c b/mono/metadata/marshal.c
index 1df30ef..17779ca 100644
--- a/mono/metadata/marshal.c
+++ b/mono/metadata/marshal.c
@@ -2903,12 +2903,15 @@ mono_marshal_get_icall_wrapper (MonoJitICallInfo *callinfo, gboolean check_excep
        MonoMethod *res;
        WrapperInfo *info;

+       g_assertf (callinfo, "%s %d", callinfo->name ? callinfo->name : "null", (int)mono_jit_icall_info_index (callinfo));
+
        gconstpointer const func = callinfo->func;

        GHashTable *cache = get_cache (& m_class_get_image (mono_defaults.object_class)->icall_wrapper_cache, mono_aligned_addr_hash, NULL);
        if ((res = mono_marshal_find_in_cache (cache, (gpointer) func)))
                return res;

+       g_assertf (callinfo->sig, "is NULL");
        MonoMethodSignature *const sig = callinfo->sig;
        g_assertf (sig->pinvoke, "%s %d", callinfo->name ? callinfo->name : "null", (int)mono_jit_icall_info_index (callinfo));

diff --git a/mono/mini/mini-runtime.c b/mono/mini/mini-runtime.c
index 2790c63..ffa7828 100644
--- a/mono/mini/mini-runtime.c
+++ b/mono/mini/mini-runtime.c
@@ -1347,6 +1347,8 @@ mono_resolve_patch_target (MonoMethod *method, MonoDomain *domain, guint8 *code,

        error_init (error);

+       g_print (" ** mono_resolve_patch_target ** patch_info %p patch_info->type %d\n", patch_info, patch_info->type);
+
        switch (patch_info->type) {
        case MONO_PATCH_INFO_BB:
                /*
@@ -1369,6 +1371,7 @@ mono_resolve_patch_target (MonoMethod *method, MonoDomain *domain, guint8 *code,
                target = code + patch_info->data.offset;
                break;
        case MONO_PATCH_INFO_JIT_ICALL_ID: {
+               g_print (" ** MONO_PATCH_INFO_JIT_ICALL_ID ** %d\n", (int)patch_info->data.jit_icall_id);
                MonoJitICallInfo * const mi = mono_find_jit_icall_info (patch_info->data.jit_icall_id);
                g_assertf (mi, "unknown MONO_PATCH_INFO_JIT_ICALL_ID %d", (int)patch_info->data.jit_icall_id);
                target = mono_icall_get_wrapper (mi);
@@ -1376,6 +1379,7 @@ mono_resolve_patch_target (MonoMethod *method, MonoDomain *domain, guint8 *code,
        }
        case MONO_PATCH_INFO_JIT_ICALL_ADDR:
        case MONO_PATCH_INFO_JIT_ICALL_ADDR_NOCALL: {
+               g_print (" ** MONO_PATCH_INFO_JIT_ICALL_ADDR or MONO_PATCH_INFO_JIT_ICALL_ADDR_NOCALL ** %s\n", patch_info->data.name);
                MonoJitICallInfo *mi = mono_find_jit_icall_by_name (patch_info->data.name);
                g_assertf (mi, "unknown MONO_PATCH_INFO_JIT_ICALL_ADDR %s", patch_info->data.name);
                target = mi->func;
@@ -1552,6 +1556,7 @@ mono_resolve_patch_target (MonoMethod *method, MonoDomain *domain, guint8 *code,
                break;
        case MONO_PATCH_INFO_ICALL_ADDR:
        case MONO_PATCH_INFO_ICALL_ADDR_CALL:
+               g_print (" ** MONO_PATCH_INFO_ICALL_ADDR or MONO_PATCH_INFO_ICALL_ADDR_CALL **\n");
                /* run_cctors == 0 -> AOT */
                if (patch_info->data.method->flags & METHOD_ATTRIBUTE_PINVOKE_IMPL) {
                        if (run_cctors) {
diff --git a/mono/mini/mini.c b/mono/mini/mini.c
index a0c083c..94af66f 100644
--- a/mono/mini/mini.c
+++ b/mono/mini/mini.c
@@ -2297,6 +2297,7 @@ mono_codegen (MonoCompile *cfg)
                gpointer target;

                for (ji = cfg->patch_info; ji; ji = ji->next) {
+g_print (" ** MONO_ARCH_HAVE_PATCH_CODE_NEW ** ji: type %d next %p data (8 bytes selected from target member) %llx\n", ji->type, ji->next, ji->data.target);
                        if (cfg->compile_aot) {
                                switch (ji->type) {
                                case MONO_PATCH_INFO_BB:
```

**Comment by NattyNarwhal** [comment]
I guess it isn't just if the values are being corrupted, but even if they're being set in the first place. Where do these get filled in? Walking back codegen from the first use of patch_info didn't give any obvious hints.

**Comment by jaykrell** [comment]
The bug is understood now.
We can take the asserts, or not.

**Comment by NattyNarwhal** [comment]
It makes sense to fix the asserts, if something like this happens again?

**Comment by BrzVlad** [comment]
I don't think it is necessary to have the __LINE__, __FILE__ arguments. It doesn't really bring anything new. Attaching or checking the crash stack frame would very easily tell what the issue is. I don't mind the asserts for the correctness of data, if you wish to reopen.

**Pull request closed without merging**
