### PR TITLE
Remove mono_arch_free_jit_tls_data.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux WebAssembly

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 Checked Private Types Build

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 FullAOT

**Pull request merged**
