### PR TITLE
fix bug 31209, prevent infinite loop in HttpConnection.cs

### PR DESCRIPTION
**Pull request by bretternst**
This patch fixes an infinite loop in HttpConnection.cs causing 100% CPU utilization when the first line of an HTTP request is empty. This bug has been triggered randomly by some browsers, especially when using HTTP Keepalive. This change simply ignores a blank first line and continues reading the request, instead of hanging. This behavior is consistent with other web servers (e.g., http://www.google.com).

I release this patch under the MIT license.

### CODE REVIEW

**Comment by knocte** [comment]
Please add the explanation of the PR in the commit message too.

**Comment by knocte** [comment]
Also, you need to use tabs, not spaces.

**Comment by migueldeicaza** [comment]
Hello,

Would you mind providing a test case, so we can make sure we do not reintroduce this bug in the future?

**Comment by akoeplinger** [comment]
The fix for this was merged in https://github.com/mono/mono/pull/2102, closing.

**Pull request closed without merging**
