### PR TITLE
Upstreaming changes from mono/debugger-libs to Mono.Debugger.Soft

### PR DESCRIPTION
**Pull request by DavidKarlas**
https://github.com/mono/debugger-libs is keeping it's own version of Mono.Debugger.Soft which sometimes get some improvements and diverges... This PR is upstreaming changes done over time...

If any of changes is questionable I will investigate in debugger-libs and explain why it's done this way...

### CODE REVIEW

**Comment by vargaz** [comment]
It would be nice to include the relevant commit messages.

**Comment by akoeplinger** [comment]
any reason why we don't replace the copy in mono with a submodule of debugger-libs?

**Comment by vargaz** [comment]
Because Mono.Debugger.Soft is a part of mono, not debugger-libs.

**Comment by Therzok** [comment]
Then, Mono.Debugger.Soft decoupled and submoduled in both mono and debugger-libs?

**Comment by DavidKarlas** [comment]
I pushed each changes as separate commit with copied message from original commit and added link to original commit

**Comment by vargaz** [comment]
Looks ok. Would be nice to have tests for some of the changes.

**Pull request merged**
