### PR TITLE
Threadpool appdomain unload cleanup

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@ludovic-henry

**Comment by vargaz** [comment]
This fixes the cleanup_semaphore assertion along with the occasional hang in appdomain-threadpool-unload.exe.

**Comment by ludovic-henry** [comment]
Regarding https://github.com/mono/mono/pull/3996/commits/f5258617ceff8cb12c8aafc7621a39d1594e2552: how are threadpool threads aborted in a certain domain with this commit?
Nowhere in the threadpool do we abort the threads for domain unload, and the way they are aborted is via `mono_threads_abort_appdomain_threads` (at https://github.com/mono/mono/blob/master/mono/metadata/threads.c#L3737) which looks at the threads which have an appdomain ref to the domain to abort.

**Comment by vargaz** [comment]
Will look at that.

**Comment by ludovic-henry** [comment]
Out of https://github.com/mono/mono/pull/3996/commits/f5258617ceff8cb12c8aafc7621a39d1594e2552 it LGTM, so feel free to merge the first 2 commits if you want to get it done quicker.

**Pull request merged**
