### PR TITLE
[runtime] Fix crash caused by signatures in caches referring to freed MonoTypes

### PR DESCRIPTION
**Pull request by alexanderkyte**
We were caching some things at the Image level rather than the ImageSet, which is wrong if the types they refer to are generic and thus in the ImageSet. We also were not copying the return type, which is wrong because signatures are supposed to own the memory of the types they refer to.

### CODE REVIEW

**Comment by borgdylan** [comment]
Was this causing the assert failure in class.c whenever I used generics across libraries?

**Comment by alexanderkyte** [comment]
I'm not sure, but the crash was noticed when running the serialization tests on linux/amd64 on jenkins. The crash was happening when a domain was unloaded under very specific circumstances.

**Comment by borgdylan** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=29842

**Comment by borgdylan** [comment]
The exact error I see is "Assertion at class.c:4811, condition `method->klass->generic_class' not met"

**Comment by akoeplinger** [comment]
@borgdylan please attach a small repro sample to the bug report.

**Comment by borgdylan** [comment]
If I step back to the latest commit before the last one that change mono/metadata/class.c, the crash no longer happens. (This commit is in May 5th)

**Comment by borgdylan** [comment]
@akoeplinger This happens when I run my compiler which is several dlls large. I am not sure if it is reducible to small cases.

**Comment by alexanderkyte** [comment]
@akoeplinger This failing assertion can be seen on public jenkins. 

https://jenkins.mono-project.com/job/test-mono-mainline/label=debian-amd64/1664/consoleFull#29169736de733c27-8bf9-43f1-b986-604599a42e3b

**Comment by borgdylan** [comment]
Its a carbon copy of what I get.

**Comment by akoeplinger** [comment]
Looks like the same issue to me. @borgdylan can you try with this PR and see if that fixes it?

**Comment by borgdylan** [comment]
I was going to propose something involving trying you PR out.

**Comment by borgdylan** [comment]
The PR does not fix teh bug

**Comment by borgdylan** [comment]
In fact jenkins still reports the assertion.

**Comment by vargaz** [comment]
Currently, these problems are handled in mono_marshal_free_inflated_wrappers (), perhaps that function can be extended instead of moving things to MonoImageSet.

**Comment by kumpera** [comment]
Hey Zoltan, ideally we would not have mono_marshal_free_inflated_wrappers and have everything allocated in mempools and have no scan unloading.

This commit unfortunately doesn't explain the exact scenario that is triggering this, so it makes harder to argue about.

@alexanderkyte can you describe the situation you're addressing. The commit message is vague on what's been addressed.

I'm looking for a step-by-step example that shows the problem it fixes. Something along the lines:

Given assemblies A, B and C.

C has method Foo<T>(T)

We insert in delegate_invoke_generic_cache Foo<KVP <A,B>>. The signature will be allocated in C's mempool and have a reference to the generic class KVP<A,B> in the (A,B) mempool.

We unload A.
...
...
We crash because the signature in the cache was not purged and referenced unloaded memory from XXX.

**Comment by alexanderkyte** [comment]
@borgdylan I am tracking down your bug currently. I'll give you a mention when I make a PR about it.

**Comment by borgdylan** [comment]
@alexanderkyte the bug wasn't there a few days ago. I will try out the PR when you make it.

**Comment by vargaz** [comment]
The assertion should be fixed by
https://github.com/mono/mono/commit/a11d525098614e230f9ed7310b702f77baeea455
It has nothing to do with this pull request.

**Comment by alexanderkyte** [comment]
@borgdylan I can confirm that @vargaz 's commit fixes the observed crash.

**Comment by borgdylan** [comment]
@alexanderkyte I confirm that as well

**Comment by alexanderkyte** [comment]
build

**Comment by alexanderkyte** [comment]
That was fixed in https://github.com/alexanderkyte/mono/commit/1a65141d41b6ec868ab9ab7ded5e577f61d3c2a8. 

I'll squash the commits though since this will be a landmine for bisecting.

**Comment by akoeplinger** [comment]
@alexanderkyte what's the status of this? This fixes the segfault I'm seeing on Linux when running the System.Runtime.Serialization testsuite, so it'd be great to have this merged :)

**Comment by kumpera** [comment]
@akoeplinger I've been reviewing this patchset. I'm was on the 4th patch Friday. I need probably another full day of work to get it done. So, with some luck by the end of next week.

**Comment by akoeplinger** [comment]
@kumpera thanks, sounds great!

**Comment by kumpera** [comment]
Manually merged it after some changes.

**Pull request closed without merging**
