### PR TITLE
Integration of Bockbuild's Mac SDK profile

### PR DESCRIPTION
**Pull request by alexischr**
`external/bockbuild/bockbuild.py mac-sdk`

This is one out of two PRs that:
- Decommissions the internal version of bockbuild
- Separates the Mono Mac Framework resources (the profiles, package recipes, patches, the manifests, some nice utility functions) to the Mono repository
- Refactored a new loader (bockbuild.py) that is not blended with the Profile class. Simpler command line, directory structure, resource resolution in multiple paths (toolchain packages are still in the bockbuild repo). Packages are shared between profiles but duplicates are not allowed. Both profile and packages can add options to the command line (e.g. the 'mono' package can use a 'checked' mode and other customizations) 
- Can build custom packages straight from your personal Mono checkout (no more copying or double checkouts).
- No more custom wrench script - 1 environment variable left :)
- Reformatted with autopep8, removed all stale patches and lots of dead code. so now git grep, static checkers and refactoring IDEs can be more useful.

This is ready for test use and non-hazardous to merge. It is up to date with internal bockbuild. The command line and location of the cache/intermediate dirs will probably change, but the internals will not.

Offline viewers might be better for this diff

Doesn't look very "reviewable" from here, but we can discuss issues, directory structure etc. 

TODO:
- Fix mac-sdk-xamarin
- Using local repo might be wonky (I'm not sure how well we handle failure of the Mono build itself, moving). Test custom build & add asserts on git operations in the mono repo
- Test PRs
- Documentation

### CODE REVIEW

**Comment by vargaz** [comment]
+1 !

**Comment by akoeplinger** [comment]
How attached are you to the bockbuild naming of the folder in the repo? I think I'd rather see that stuff in a folder called `packaging` or something like that which actually makes sense for users not familiar with the bockbuild history :)

**Comment by vargaz** [comment]
That folder does contain bockbuild :).

**Comment by akoeplinger** [comment]
@vargaz nope the actual bockbuild is in a submodule in external/, which is fine :) I'm talking about the scripts in the bockbuild/ folder at the top of the mono repo.

**Comment by vargaz** [comment]
Ok.

**Comment by alexischr** [comment]
@akoeplinger The directory has special significance (we look inside a repo's ./bockbuild directory for build profiles to load) Like 'Makefile', '.git' etc. this can be named however we want (e.g '.bockbuild'), but needs to be reserved and not have foreign files inside of it.

**Pull request merged**
