### PR TITLE
[interp] Restore 16 bytes of frame due to change to leave.

### PR DESCRIPTION
**Pull request by jaykrell**
Outline more of leave, as one piece.
Hypothetically this is easier to maintain, but it still kinda on the edge.
Just putting in a memset pushes it over.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by BrzVlad** [comment]
While I'm not particularly against this PR, I don't like big changes, especially if the alternative is a one line revert. https://github.com/mono/mono/pull/16887

**Comment by jaykrell** [comment]
It is a little noisy but conceptually simple and small -- union + outline.

**Comment by jaykrell** [comment]
This form also more easily affords more changes in leave, which is hypothetical. If such changes materialize, can still do this, easily enough.

**Pull request closed without merging**
