### PR TITLE
[threadpool] Use mono-poll instead of hacking our wait around it.

### PR DESCRIPTION
**Pull request by kumpera**
The main reason for this is that we have the same abstraction implemented in two places for no good reason at all.

### CODE REVIEW

**Comment by kumpera** [comment]
CC @ludovic-henry

**Comment by ludovic-henry** [comment]
The issue with mono_poll is that it can potentially use select under the
hood, so we loose the error-per-socket property of poll, as opposed to
error-per-call property of select (for EBADF error). This forces us to then
call mono_poll for each socket to know which one has an error. That was the
way it was done before, so it should be pretty easy to switch back to it.

On Tuesday, August 25, 2015, Rodrigo Kumpera <notifications@github.com>
wrote:

> CC @ludovic-henry <https://github.com/ludovic-henry>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/mono/pull/1995#issuecomment-134397230>.
>


-- 
Ludovic Henry
Runtime Software Engineer
Xamarin, Inc.

**Comment by kumpera** [comment]
My concern are with the limitations and errors on OSX that mono-poll mentions. We should research what those are. Maybe they refer to old versions of OSX?

Another problem that this tries to address is the inconsistent use of poll and mono_poll types and constants.

**Comment by ludovic-henry** [comment]
Poll limitations only applies to device fd, so not socket and pipes (for
the process stdout and stderr)

On Tuesday, August 25, 2015, Rodrigo Kumpera <notifications@github.com>
wrote:

> My concern are with the limitations and errors on OSX that mono-poll
> mentions. We should research what those are. Maybe they refer to old
> versions of OSX?
>
> Another problem that this tries to address is the inconsistent use of poll
> and mono_poll types and constants.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/mono/pull/1995#issuecomment-134743027>.
>


-- 
Ludovic Henry
Runtime Software Engineer
Xamarin, Inc.

**Comment by ludovic-henry** [comment]
master uses mono_poll now (since quite a bit actually)

**Pull request closed without merging**
