### PR TITLE
Test LLVM 9

### PR DESCRIPTION
**Pull request by imhameed**

### CODE REVIEW

**Comment by filipnavara** [comment]
@imhameed is there a reason why the fix on release_90 branch (https://github.com/mono/llvm/commit/265488abb0efb90112c45a20ab248b898fa6458a) is any better than the one on release_90-2 branch (https://github.com/mono/llvm/commit/69997c65e9d039b458ffc0059768e2fa6d47f03c)? Also, the release_90-2 branch seems to have more fixes backported.

**Comment by filipnavara** [comment]
Related: https://github.com/mono/mono/pull/17144

**Comment by imhameed** [comment]
> 
> 
> @imhameed is there a reason why the fix on release_90 branch ([mono/llvm@265488a](https://github.com/mono/llvm/commit/265488abb0efb90112c45a20ab248b898fa6458a)) is any better than the one on release_90-2 branch ([mono/llvm@69997c6](https://github.com/mono/llvm/commit/69997c65e9d039b458ffc0059768e2fa6d47f03c))? 

The call frame instructions emitted by https://github.com/mono/llvm/commit/69997c65e9d039b458ffc0059768e2fa6d47f03c never advance instruction addresses and are not necessarily ordered in the same order as the machine instructions they're associated with, so the resulting canonical frame address computations are wrong. This happens because `MCCFIInstruction::getLabel` applied to the entries returned by `MachineFunction::getFrameInstructions` will always return `nullptr`; these `MCCFIInstruction`s are all created by code that does not generate labels at all [1]. LLVM's own CFI emission code will just create a new buffer of `MCCFIInstruction`s with associated labels [2] [3].

[1] https://github.com/mono/llvm/blob/265488abb0efb90112c45a20ab248b898fa6458a/lib/Target/X86/X86FrameLowering.cpp#L1153
[2] https://github.com/mono/llvm/blob/265488abb0efb90112c45a20ab248b898fa6458a/lib/CodeGen/AsmPrinter/AsmPrinterDwarf.cpp#L213
[3] https://github.com/mono/llvm/blob/265488abb0efb90112c45a20ab248b898fa6458a/lib/MC/MCStreamer.cpp#L428


Here's the disassembled code for `System.Diagnostics.Stopwatch:get_ElapsedTicks`, extracted from a run of https://github.com/imhameed/ToyPathTracer.
```asm
*** ASM for System.Diagnostics.Stopwatch:get_ElapsedTicks () ***

/tmp/.PhwcVn:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <tem_Diagnostics_Stopwatch_get_ElapsedTicks___>:
<BB>:1
   0:	53                   	push   %rbx
   1:	48 89 fb             	mov    %rdi,%rbx
   4:	80 7f 20 00          	cmpb   $0x0,0x20(%rdi)
   8:	74 16                	je     20 <tem_Diagnostics_Stopwatch_get_ElapsedTicks___+0x20>
   a:	48 b8 38 ca 2a 7b 07 	movabs $0x56077b2aca38,%rax
  11:	56 00 00 
  14:	ff 10                	callq  *(%rax)
  16:	48 2b 43 18          	sub    0x18(%rbx),%rax
  1a:	48 03 43 10          	add    0x10(%rbx),%rax
  1e:	5b                   	pop    %rbx
  1f:	c3                   	retq   
  20:	48 8b 43 10          	mov    0x10(%rbx),%rax
  24:	5b                   	pop    %rbx
  25:	c3                   	retq   
***
```

Here's the CIE/FDE emitted with https://github.com/mono/llvm/commit/265488abb0efb90112c45a20ab248b898fa6458a:
```
CFA: [0] def_cfa: %rsp+0x8
CFA: [0] offset: pc at cfa-0x8
CFA: [1] def_cfa_offset: 0x10
CFA: [1] offset: %rbx at cfa-0x10
CFA: [1f] def_cfa_offset: 0x8
CFA: [20] def_cfa_offset: 0x10
CFA: [25] def_cfa_offset: 0x8
```

And here's the CIE/FDE emitted with https://github.com/mono/llvm/commit/69997c65e9d039b458ffc0059768e2fa6d47f03c:
```
CFA: [0] def_cfa: %rsp+0x8
CFA: [0] offset: pc at cfa-0x8
CFA: [0] def_cfa_offset: 0x10
CFA: [0] offset: %rbx at cfa-0x10
CFA: [0] def_cfa_offset: 0x8
CFA: [0] def_cfa_offset: 0x10
```

> Also, the release_90-2 branch seems to have more fixes backported.

Yes. I'm not yet sure how to best deal with this. See also: https://github.com/mono/mono/issues/16893#issuecomment-536912820

**Comment by vargaz** [comment]
The release_90 branch only contains a minimal amount of commits to make things work, the release_90_2 branch should contain all commits from release_60 in a cleaned up version, i.e. multiple commits are merged together.

**Comment by filipnavara** [comment]
Thanks for the detailed explanation with examples. I really appreciate it!

**Comment by vargaz** [comment]
I think we should rename the release_90_2 branch to release_90 and add this eh fix.

**Comment by vargaz** [comment]
Replaced the release_90 branch with release_90-2, saved the original one at release_90-orig.

**Comment by vargaz** [comment]
This needs to be rebased on top of the new llvm repo.

**Comment by imhameed** [comment]
Closing for now.

**Pull request closed without merging**
