### PR TITLE
[runtime] Implement tombstone scrubbing for our concurrent hashtables.

### PR DESCRIPTION
**Pull request by kumpera**
Tombstones must be scrubbed as they can end up taking up all space of a hashtable and make lookup fail.

### CODE REVIEW

**Comment by alexanderkyte** [comment]
What happens if someone tries a lookup while the mutator threads are between ```set_key_to_tombstone``` and ```check_table_size``` in mono_conc_g_hash_table_remove? 

Won't they still get a hazard pointer to a hash table that lacks NULL or the current key? 

And then the table resize will happen on the mutator thread while the lookup code circles indefinitely in that while loop.

**Comment by marek-safar** [comment]
@kumpera please backport down to 2018-02 or is the fix too risky?

**Comment by kumpera** [comment]
@alexanderkyte search will work just fine because `mono_conc_g_hash_table_remove` doesn't increase the number of non-null elements in the hashtable.

The only function that increases the number of non-null elements is `mono_conc_g_hash_table_insert`, which checks before insert. This means that a removal right after the insert that sets `element_count` to `element_count` would trigger an expansion rehash.

This means that this patch reduces the effective load factor by 7% in the worst case (which the initial size of 16) but exponentially less as the table grows - it's .1% smaller at 32k size.

**Comment by kumpera** [comment]
@marek-safar this part of the code base is really tricky, I'd wait at least a week in master before considering backporting.

**Comment by kumpera** [comment]
failures look unrelated.

**Comment by kumpera** [comment]
@monojenkins build failed

**Comment by luhenry** [comment]
Is this a fix for a particular issue/bug? If not, I wouldn't want to backport it further than `2018-06` as it has a high chance of silently breaking things.

**Comment by kumpera** [comment]
@luhenry it's a better fix for #9158
I spend some time today trying to write a test case

**Comment by kumpera** [comment]
Disabled test under full-aot as it requires SRE.

**Pull request merged**
