### PR TITLE
Avoid race condition between domain unload and threadpool.

### PR DESCRIPTION
**Pull request by joncham**
Previous logic only ensured that domain->threadpool_jobs was 0.
There was a race condition as follows:
* worker jobs are queued into ThreadPoolDomain outstanding_request's
* domain unload starts
* domain->threadpool_jobs is 0 so unload proceeds
* queued jobs are processed from the ThreadPoolDomain outstanding_request's
* the domain can be set/entered by worker threads since
  mono_domain_set only fails for domains with state of MONO_APPDOMAIN_UNLOADED,
  while our domain is in the MONO_APPDOMAIN_UNLOADING state
* jobs are now being unexpectedly run in domain that is being shutdown

### CODE REVIEW

**Comment by alexrp** [comment]
Since you are modifying all the code related to that semaphore anyway, perhaps you could switch it to a `MonoSemType` from `mono/utils/mono-os-semaphore.h`?

/cc @ludovic-henry for review

**Comment by joncham** [comment]
@alexrp I will do that assuming this general approach makes sense.

**Comment by ludovic-henry** [comment]
I like this approach, but as @alexrp said, it would be better to switch from a `HANDLE` to a `MonoCoopSem`. I did it already here https://github.com/ludovic-henry/mono/commit/3d480eb775927303051ca37d54f5e3dde3db2da7, so if you can rebase your work on top of it, that would be great.
Thank you! :)

**Comment by joncham** [comment]
@ludovic-henry I see that commit you reference is not merged to master. I confused what you mean by "rebase your work on top of it"?

**Comment by ludovic-henry** [comment]
@joncham after trying to merge my change on switching from win32 semaphore to MonoCoopSem, I think it's easier to merge your change, and do the switch after.

The only problem now is that your change introduces a hang when unloading the domain, but you can find the fix here : https://gist.github.com/ludovic-henry/6c8a4bc8951091c0ef36df2e52d5e32e
The hang would be because we would try to wait on domains that wouldn't have any outstanding request, but as the domain was not unloading (yet) when decrementing the outstanding request, we didn't signal the semaphore.

**Comment by joncham** [comment]
@ludovic-henry thanks, I'll apply your gist to my PR.

**Comment by joshpeterson** [comment]
@ludovic-henry I've pushed a commit to apply your diff to this branch.

**Pull request merged**
