### PR TITLE
[cil-strip] Upgrade to latest Mono.Cecil API

### PR DESCRIPTION
**Pull request by akoeplinger**
This greatly simplifies the code and as a bonus also shaves off about 300ms when stripping mscorlib.dll.

### CODE REVIEW

**Comment by spouliot** [comment]
This is incorrect. There was a reason why Cecil was never updated. Using a new version means all metadata tokens will be different which break aot compilation.

**Comment by spouliot** [comment]
Cc @jbevain @vargaz

**Comment by vargaz** [comment]
The new cecil version doesn't support keeping metadata tokens identical, so it cannot be used by mono-cil-strip.

**Comment by akoeplinger** [comment]
That's quite unfortunate 😢 I reverted the commits.

@jbevain How hard would it be to add an option to Cecil to keep metadata tokens identical?

**Comment by spouliot** [comment]
@akoeplinger it's been discussed but it's not trivial, other options might be better (e.g. rewrite to use system.reflection.metadata). Even the original cecil / strip needed some special care to make that work.

**Pull request merged**
