### PR TITLE
Building on openBSD - 5.5

### PR DESCRIPTION
**Pull request by dohnuts**
* fixing libtool path detection
 * exit on error
It is diifcult to find error with the large output, stop if the script detect one
 * do not hide automake/conf errors
Auto(tools) need environement variable to be set to choose the right version, the auto tool message is very precise.

### CODE REVIEW

**Comment by alexrp** [comment]
So is this actually an issue?

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by dohnuts** [comment]
On Mon, Mar 16, 2015 at 8:41 AM, Alex Rønne Petersen <
notifications@github.com> wrote:

> So is this actually an issue?
>

i didny check recently , but openBSD build was not functionnal, wihtout
modification i wont see it correcting by himself


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/mono/pull/1027#issuecomment-81630163>.
>



-- 
---------------------------------------------------------------------------------------------------------------------
() ascii ribbon campaign - against html e-mail
/\

**Comment by sethjackson** [comment]
@alexrp IMO no it is not an issue. See my previous comments but basically you need to:

a) Install libtool from packages
b) export LIBTOOL=/usr/local/bin/libtool
b) Install Bash and run the build scripts with it

I have not tried recently from master but that did allow me to get pretty far in building.
I'm not sure if all the OpenBSD specific patches have been upstreamed or not but again I could get the build going in the past doing the above.

**Comment by dohnuts** [comment]
On Mon, Mar 16, 2015 at 5:16 PM, Seth Jackson <notifications@github.com>
wrote:

> @alexrp <https://github.com/alexrp> IMO no it is not an issue. See my
> previous comments but basically you need to:
>
> a) Install libtool from packages
> b) export LIBTOOL=/usr/local/bin/libtool
> b) Install Bash and run the build scripts with it
>
> I have not tried recently from master but that did allow me to get pretty
> far in building.
> I'm not sure if all the OpenBSD specific patches have been upstreamed or
> not but again I could get the build going in the past doing the above.
>
>
I agree to this



-- 
---------------------------------------------------------------------------------------------------------------------
() ascii ribbon campaign - against html e-mail
/\

**Comment by lewurm** [comment]
closing this. please open another PR if this is still an issue with rebased changes.

**Pull request closed without merging**
