### PR TITLE
[2018-02] [runtime] Add MS telemetry reporter for unmanaged exceptions

### PR DESCRIPTION
**Pull request by luhenry**
Backport of #7451.

/cc @luhenry

https://github.com/mono/mono/issues/7072

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build deb with monolite

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Comment by luhenry** [comment]
@marek we very certainly don't want to backport that to 2017-12.

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build Linux x64 mcs

**Pull request merged**
