### PR TITLE
[llvm] Fix patching of calls from LLVM JITted code.

### PR DESCRIPTION
**Pull request by vargaz**
Previously, some calls were not patched, so the trampolines were repeatedly called.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Missing `MONO_LLVM_INTERNAL`?

```
*** start: check-prefix-llvmjit
mono: symbol lookup error: /mnt/jenkins/workspace/test-mono-pull-request-amd64-prefix/tmp/monoprefix/lib/libmono-llvm.so: undefined symbol: mono_icall_get_wrapper_full
nmounting /mnt/jenkins/workspace/test-mono-pull-request-amd64-prefix filesystem
I```

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
