### PR TITLE
Update FormsAuthentication.cs

### PR DESCRIPTION
**Pull request by sawachika-kenji**
The FormsAuthentication.SetAuthCookie not use time out from web.config , fix it.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@sawachika-kenji please add some explanation to the commit message about why this is needed. Also revert the whitespace changes (we use tabs, not spaces).

**Comment by sawachika-kenji** [comment]
The FormsAuthentication.SetAuthCookie not use time out from web.config <forms>, fix it.

**Comment by knocte** [comment]
You need to put that description in the commit message.

**Comment by migueldeicaza** [comment]
build

**Pull request merged**
