### PR TITLE
mono_field_get_type to mono_field_get_type_internal to skip GC mode machinery

### PR DESCRIPTION
**Pull request by jaykrell**
But also optimize mono_field_get_type in the common case, to "short circuit"
and skip ditto.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
The optimization is ok right? I unclear just when you have to transition GC mode, run just a bit more code.

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 C++

**Comment by akoeplinger** [comment]
@monojenkins build Linux WebAssembly
@monojenkins build Windows i386

**Comment by akoeplinger** [comment]
@monojenkins build Windows i386

**Comment by akoeplinger** [comment]
@monojenkins build Linux WebAssembly

**Pull request merged**
