### PR TITLE
[Coop] Convert System.ArgIterator

### PR DESCRIPTION
**Pull request by jaykrell**
Trivial.

### CODE REVIEW

**Comment by vargaz** [comment]
Since the HANDLES () code has a certain amount of overhead, it would be better to add a NOHANDLES () macro or something, and don't convert these icalls to handles.

**Comment by jaykrell** [comment]
This stuff is frequently used?
Isn't the overhead just:
  1. stack space for MonoError
  2. one instruction to initialize the MonoError
  3. check the monoerror upon exist -- instead of or in addition to thread's pending exception?

Too much?

**Comment by jaykrell** [comment]
I suggest this overhead is affordable for the vast majority of icalls, that don't traffic in pointers.
But identifying the exact set is not scientific, granted.
Perhaps a scientific policy would be to exclude ones that have no pointers and no errors?

**Comment by vargaz** [comment]
There are two calls made to c functions as well, i.e. mono_icall_begin () and mono_icall_end ().

**Comment by jaykrell** [comment]
Fails miserably, come back to it later..

**Pull request closed without merging**
