### PR TITLE
[System] ComponentModel and System.Net from corefx

### PR DESCRIPTION
**Pull request by EgorBo**
Part of #8124

### CODE REVIEW

**Comment by marek-safar** [comment]
The test failures are related

**Comment by marek-safar** [comment]
The DesignerAttribute is still present

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Pull request merged**
