### PR TITLE
[do not merge] debug process-test timeout

### PR DESCRIPTION
**Pull request by lewurm**
weren't able to reproduce it locally

### CODE REVIEW

**Comment by lewurm** [comment]
snippet of running `process-test-1.exe` with `--trace` (from https://jenkins.mono-project.com/job/test-mono-pull-request-amd64/10614/):

```
[0x148981e32780: 868.76485 4] ENTER: (wrapper managed-to-native) System.Threading.WaitHandle:Wait_internal (intptr*,int,bool,int)(0x7ffc047a4010, 1, 0, 10000, )
hello 1>/dev/null
[0x14897e048700: 870.35905 4] LEAVE: (wrapper managed-to-native) System.Threading.WaitHandle:Wait_internal (intptr*,int,bool,int)result=0
```

while on my system it looks like this:

```
[0x7000082bd000: 6.26201 9] ENTER: (wrapper managed-to-native) System.Threading.WaitHandle:Wait_internal (intptr*,int,bool,int)(0x7000082bc390, 1, 0, 10000, )
hello 1>/dev/null
[0x7000082bd000: 6.26541 9] LEAVE: (wrapper managed-to-native) System.Threading.WaitHandle:Wait_internal (intptr*,int,bool,int)result=0
```

@luhenry any idea?

**Comment by akoeplinger** [comment]
Here's an strace of process-stress-1.exe (with `time echo hello` as the command): https://gist.github.com/akoeplinger/60b381e9855058abe8e1740cf561f72d

**Comment by akoeplinger** [comment]
and here is one with `MONO_LOG_LEVEL=debug MONO_LOG_MASK=io-layer`: https://gist.github.com/akoeplinger/b4c65f4233aff47c61ef4b45d7533ac5

**Comment by akoeplinger** [comment]
more infos at https://github.com/mono/mono/issues/6555

**Pull request closed without merging**
