### PR TITLE
[2018-06][aot] Fix win32 build

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
```diff --git a/configure.ac b/configure.ac
index c68b8959b1c..cc35f8518f5 100644
--- a/configure.ac
+++ b/configure.ac
@@ -3827,14 +3827,16 @@ if test "x$enable_llvm" = "xyes"; then
        LLVM_CFLAGS="-I$with_llvm/include -DNDEBUG -D__NO_CTYPE_INLINE -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS"
        LLVM_CXXFLAGS="$LLVM_CFLAGS -std=gnu++11 -fvisibility-inlines-hidden -fno-rtti -Woverloaded-virtual -Wcast-qual"
        LLVM_LDFLAGS="-L$with_llvm/lib"
-       LLVM_SYSTEM_LIBS="-lshell32 -lpsapi -limagehlp -ldbghelp -lm"
+       LLVM_SYSTEM_LIBS="-lshell32 -lpsapi -limagehlp -ldbghelp -lm -lz -luuid -lole32"
        LLVM_LIBS="-lLLVMLTO -lLLVMObjCARCOpts -lLLVMLinker -lLLVMipo -lLLVMVectorize -lLLVMBitWriter \
-         -lLLVMTableGen -lLLVMDebugInfo -lLLVMOption -lLLVMSelectionDAG -lLLVMAsmPrinter \
-         -lLLVMMCDisassembler -lLLVMJIT -lLLVMAnalysis -lLLVMTarget \
-         -lLLVMIRReader -lLLVMAsmParser -lLLVMLineEditor -lLLVMMCAnalysis -lLLVMInstrumentation \
-         -lLLVMInterpreter -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils \
-         -lLLVMipa -lLLVMAnalysis -lLLVMProfileData -lLLVMMCJIT -lLLVMTarget -lLLVMRuntimeDyld \
-         -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMExecutionEngine -lLLVMMC -lLLVMCore \
+         -lLLVMTableGen  -lLLVMOption -lLLVMSelectionDAG -lLLVMAsmPrinter \
+         -lLLVMARMAsmPrinter -lLLVMX86AsmParser \
+         -lLLVMMCDisassembler -lLLVMAnalysis -lLLVMTarget \
+         -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF \
+         -lLLVMIRReader -lLLVMAsmParser -lLLVMLineEditor -lLLVMInstrumentation \
+         -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils \
+         -lLLVMBinaryFormat -lLLVMProfileData -lLLVMTarget \
+         -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMMC -lLLVMCore \
          -lLLVMSupport -lstdc++"
        LLVM_LIBS="$LLVM_LIBS $LLVM_ARCH_LIBS $LLVM_SYSTEM_LIBS"
 
``` this gets llvm linking for me

**Comment by alexanderkyte** [comment]
Though it's failing with ```  	
  Copying file from "/Users/akyte/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/cross-x86_64.exe" to "/Users/akyte/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/cross-x86_64.d.exe".
  "/Users/akyte/android-toolchain/mxe-b9cbb53/bin/i686-w64-mingw32.static-strip" -S "/Users/akyte/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/cross-arm.exe"
  "/Users/akyte/android-toolchain/mxe-b9cbb53/bin/x86_64-w64-mingw32.static-strip" -S "/Users/akyte/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/cross-arm64.exe"
  /var/folders/00/v8q_733j1hd8br7nxhxs41d80000gn/T/tmpc4307869057d4f7bba499c3b43d80c67.exec.cmd: line 2: 55509 Segmentation fault: 11  "/Users/akyte/android-toolchain/mxe-b9cbb53/bin/x86_64-w64-mingw32.static-strip" -S "/Users/akyte/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/cross-arm64.exe"
/Users/akyte/xamarin-android/src/mono-runtimes/mono-runtimes.targets(787,5): error MSB3073: The command ""/Users/akyte/android-toolchain/mxe-b9cbb53/bin/x86_64-w64-mingw32.static-strip" -S "/Users/akyte/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/cross-arm64.exe"" exited with code 139. [/Users/akyte/xamarin-android/src/mono-runtimes/mono-runtimes.csproj]
Done Building Project "/Users/akyte/xamarin-android/src/mono-runtimes/mono-runtimes.csproj" (ForceBuild target(s)) -- FAILED.
Done Building Project "/Users/akyte/xamarin-android/src/mono-runtimes/mono-runtimes.csproj" (default targets) -- FAILED.
```

**Comment by alexanderkyte** [comment]
When I examine it:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1ab2354ae0)
  * frame #0: 0x0000000100059833 x86_64-w64-mingw32.static-strip`___lldb_unnamed_symbol794$$x86_64-w64-mingw32.static-strip + 323
    frame #1: 0x000000010006522b x86_64-w64-mingw32.static-strip`___lldb_unnamed_symbol846$$x86_64-w64-mingw32.static-strip + 2459
    frame #2: 0x000000010003caee x86_64-w64-mingw32.static-strip`___lldb_unnamed_symbol541$$x86_64-w64-mingw32.static-strip + 46
    frame #3: 0x00000001000048a4 x86_64-w64-mingw32.static-strip`___lldb_unnamed_symbol5$$x86_64-w64-mingw32.static-strip + 596
    frame #4: 0x00000001000034d9 x86_64-w64-mingw32.static-strip`___lldb_unnamed_symbol1$$x86_64-w64-mingw32.static-strip + 8697
    frame #5: 0x00007fff62de9115 libdyld.dylib`start + 1
    frame #6: 0x00007fff62de9115 libdyld.dylib`start + 1
```

**Comment by luhenry** [comment]
Closed in favour of https://github.com/mono/mono/pull/10402

**Pull request closed without merging**
