### PR TITLE
[jit] Fix using conv.u with string.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by marek-safar** [comment]
What's the motivation for the backport?

**Comment by marek-safar** [comment]
Relevant bug report https://bugzilla.xamarin.com/show_bug.cgi?id=60625

**Comment by mellinoe** [comment]
What is the next stable release that will include this? I'm hitting this in a ton of places in my library.

**Comment by marek-safar** [comment]
It's already included in Mono 5.8

**Pull request merged**
