### PR TITLE
[bcl] add fullaotinterp_llvm preset

### PR DESCRIPTION
**Pull request by lewurm**
That is, the AOT compiler uses the LLVM backend for BCL. AOT+LLVM is
used in the 'Release' configuration on Xamarin.iOS.

### CODE REVIEW

**Comment by lewurm** [comment]
@akoeplinger can we have a lane that is similar to what we have for `fullaotinterp`?

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter+LLVM

**Comment by luhenry** [comment]
@lewurm https://jenkins.mono-project.com/view/Pull%20requests/job/test-mono-pull-request-fullaot+interpreter+llvm/1. Let's see if it works.

**Comment by lewurm** [comment]
```
22:17:14 Not copying any file from skel directory into it.
22:17:14 + cd /mnt/jenkins/workspace/test-mono-pull-request-fullaot+interpreter+llvm
22:17:14 + export CI_TAGS=linux-amd64,retry-flaky-tests,fullaotinterp_llvm,pull-request
22:17:14 + CI_TAGS=linux-amd64,retry-flaky-tests,fullaotinterp_llvm,pull-request
22:17:14 + dpkg-deb -x 'mono-llvm_6.0_*.deb' /tmp/mono-llvm
22:17:14 dpkg-deb: error: failed to read archive 'mono-llvm_6.0_*.deb': No such file or directory
22:17:14 I: Copying back the cached apt archive contents
22:17:18 I: unmounting /mnt/jenkins/workspace/test-mono-pull-request-fullaot+interpreter+llvm filesystem
```
hmm

**Comment by lewurm** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter+LLVM

**Comment by lewurm** [comment]
@monojenkins build Linux x64 FullAOT+Interprete

**Comment by lewurm** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Comment by lewurm** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter

**Pull request merged**
