### PR TITLE
[tests] Re-enable appdomain-thread-abort.exe

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by lambdageek** [comment]
build coop

**Comment by lewurm** [comment]
interpreter fails with:
```
Unhandled Exception:
System.Runtime.Remoting.RemotingException: Cannot resolve method System.AppDomain:StoreRemoteField
```
@BrzVlad any idea?

I think in the meanwhile you should add `appdomain-thread-abort.exe` to the interpreter ignore list.

**Comment by lambdageek** [comment]
@lewurm I can't believe that it would work for the non-interpreter builds either.  It looks like `ves_icall_Remoting_RemotingServices_GetVirtualMethod` (aka `System.Runtime.Remoting.RemotingServices:GetVirtualMethod`) doesn't know anything about transparent proxies (in contrast to `mono_object_handle_get_virtual_method`) so I don't see how it would ever resolve a `StoreRemoteField` `MonoMethod*` correctly.

It's possible that non-interp doesn't end up in the same branch of `S.R.R.RemotingServices:InternalExecuteMessage` but that also seems surprising.

**Comment by BrzVlad** [comment]
@lewurm Yeah, this bug will be fixed on my branch. I guess we can ignore this test for now on interp

**Comment by luhenry** [comment]
Let me disable it for the interpreter

**Comment by luhenry** [comment]
build

**Pull request merged**
