### PR TITLE
[C7][System.ServiceModel] Fixes reflection call to undefined method.

### PR DESCRIPTION
**Pull request by esdrubal**
This fixes an issue while using WCF on android.

Fixes [#36080](https://bugzilla.xamarin.com/show_bug.cgi?id=36080)

### CODE REVIEW

**Comment by brendanzagaeski** [comment]
I have a small question about this that I'm discussing via email with esdrubal. If we could hold off on merging this pull request until that question is resolved, I think that would be best. Thanks!

**Comment by brendanzagaeski** [comment]
All set on my end. My question is answered, and there's no problem for me. Thanks!

**Comment by esdrubal** [comment]
build

**Comment by akoeplinger** [comment]
@esdrubal looks like you're running into an issue with our current Jenkins setup, because we don't have a way to differentiate the build script for each branches so it tries building the monotouch etc libraries which only works on master...

**Comment by esdrubal** [comment]
@akoeplinger thanks for telling me this. Then I will do a pull request against master before I merge this.

**Comment by esdrubal** [comment]
testing this on https://github.com/mono/mono/pull/2787

**Comment by esdrubal** [comment]
merged in master, all tests were passing.

**Comment by alexischr** [comment]
This was merged to mono-4.4.0-branch: https://github.com/mono/mono/commit/aea10b3386820d55caedfe41ab07342c3b9b0cc4

**Pull request closed without merging**
