### PR TITLE
optimize adding unwind info entries by hashtable

### PR DESCRIPTION
**Pull request by DzmitryKN**
Hi this is an alternative approach for problem described in #21108
According to your comment there we implemented similar optimization by using hashtable, while it has bit more memory overhead than original code, it still performs equally fast on same system. However apparently potentially hashtable approach will perform better on larger projects. So please decide which solution is better from your point of view.

### CODE REVIEW

**Comment by vargaz** [comment]
The changes look ok, please use the mono coding conventions, i.e. spaces before '(' etc.

**Review by vargaz — APPROVED** [review]

**Comment by DzmitryKN** [comment]
@monojenkins build

**Comment by DzmitryKN** [comment]
Seems i can't ask your bot to rebuild. However tests fails of my PR are similar to these failures on main from where i've forked off my branch: https://github.com/mono/mono/runs/2907293121

**Comment by DzmitryKN** [comment]
Anything else needed for merging? Also it seems i have to say this:
This change is released under the MIT license.

**Comment by vargaz** [comment]
Needs (mostly) green CI.

**Comment by elfmz** [comment]
All these 'Expected — Waiting for status to be reported' - aren't they just stuck at CI infrastructure level? Is it possible to re-run such tests one-by-one?

**Comment by DzmitryKN** [comment]
Will these 'Expected — Waiting for status to be reported' ever finish? Is it possible to restart them one by one if they stalled due to CI infrastructure issues?

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by DzmitryKN** [comment]
Is it possible to see jenkins tests failure reason? At least for those marked as (Required). Details links appear not responding (jenkins.mono-project.com took too long to respond.).

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by DzmitryKN** [comment]
uh, its all green :)

**Comment by akoeplinger** [comment]
@vargaz @DzmitryKN would one of you mind to port the change to https://github.com/dotnet/runtime? The bot can't do it automatically since there's a conflict.

**Pull request merged**
