### PR TITLE
Make `System.dll` internals visible to `Mono.Android`.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by marek-safar** [comment]
@baulig why? this can cause ambiguity problems

**Comment by baulig** [comment]
> @baulig why? this can cause ambiguity problems

It won't, the `xamarin-android` build worked fine and we're doing the same thing for `xamarin-macios`.

It is required if you want to use any `X509Certificate` on Android.

**Comment by baulig** [comment]
@monojenkins backport 2019-02

**Comment by baulig** [comment]
@monojenkins backport 2018-12

**Comment by baulig** [comment]
@monojenkins backport 2018-10

**Comment by baulig** [comment]
@monojenkins backport 2018-08

**Comment by baulig** [comment]
See https://github.com/xamarin/xamarin-android/issues/2679.

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Comment by alexischr** [comment]
@monojenkins backport to 2018-10

**Comment by alexischr** [comment]
@monojenkins backport to 2019-02

**Pull request merged**
