### PR TITLE
mono_breakpoint_clean_code always returns TRUE.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
Maybe not worth anything and maybe something to fix in the other direction in future, if it really is a thing.

**Comment by jaykrell** [comment]
@monojenkins build

**Comment by marek-safar** [comment]
@thaystg please review

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@vargaz will this ever change? Unfinished work to be finished later? Abandoned idea? Some architectures might be different? I not sure should lock in current pattern, if it is subject to change. Not a big deal either way.

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by SamMonoRT** [comment]
@jaykrell - a couple test failures in x64 Linux

**Comment by jaykrell** [comment]
Hard to read the reports, I'll rebase to master and retry later..

**Comment by lambdageek** [comment]
@jaykrell Going by 0b4533dd5969041db8753ef5854f131c2d8dd920 this looks like leftover dead code (is that right @vargaz) so it looks ok to remove `!can_write` codepaths from the callers.

That said, there is a merge conflict with some prior change of yours.

**Pull request merged**
