### PR TITLE
Add hardened runtime testing to Catalina lane

### PR DESCRIPTION
**Pull request by directhex**
(there is no matching PR lane for Catalina, at time of writing)

### CODE REVIEW

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Pull request merged**
