### PR TITLE
[wasm] Use the functions in emscripten/stack.h to compute stack bounds.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Review by CoffeeFlux — APPROVED** [review]
LGTM. This still calls into JS, right? They just added convenience functions for it?

**Comment by vargaz** [comment]
The JS support got removed in the latest emscripten version.

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
@CoffeeFlux https://github.com/emscripten-core/emscripten/pull/12615

**Comment by CoffeeFlux** [comment]
Oh, even better 😄

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
