### PR TITLE
[runtime] Improve profiler allocation reporting

### PR DESCRIPTION
**Pull request by alexrp**
This PR's primary purpose is to make sure that *all* object allocations are reported to the profiler. This is done by reporting allocations directly in the GC code instead of from the various functions in `object.c`. This significantly reduces the odds of forgotten `mono_profiler_allocation` calls.

Since I was here, I also cleaned up the object allocation code and moved it into each GC implementation where it belongs. I've also dropped external Boehm support as I don't think we've supported this for a long time.

### CODE REVIEW

**Comment by alexrp** [comment]
cc @schani @kumpera

**Comment by schani** [comment]
Why do we only care about disabling the managed allocator in FullAOT?

**Comment by alexrp** [comment]
@schani 2ea3e81549c231a5365694890b3f8e80fdbc67a9 contains an explanation (let me know if it's unclear). It's also generally a better solution than the previous attempt, I think.

**Comment by alexrp** [comment]
I think this is ready to be merged unless there's stuff anyone wants me to change.

**Comment by schani** [comment]
I'm ok with it.

**Comment by alexrp** [comment]
build

**Pull request merged**
