### PR TITLE
Bump corefx to disable two tests.

### PR DESCRIPTION
**Pull request by akoeplinger**
HashTableTests.Ctor_Int_Int_GenerateNewPrime and BitConverterTests.ToString_ByteArrayTooLong_Throws allocate a lot of memory and this causes issues on Windows i386 and other platforms.

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
Should this be backported to older branches so the iOS team can re-enable the other tests?

**Comment by akoeplinger** [comment]
iOS already disabled those tests on their end so it shouldn't matter

**Comment by CoffeeFlux** [comment]
Ah okay, I think I was looking in the wrong location.

**Comment by akoeplinger** [comment]
Tracking issue for the OOM: https://github.com/mono/mono/issues/18474

**Pull request merged**
