### PR TITLE
Bump corefx.

### PR DESCRIPTION
**Pull request by filipnavara**
Testing build... currently all PRs with bumped corefx fail to build, this should fix it.

### CODE REVIEW

**Comment by filipnavara** [comment]
@monojenkins commit csproj

**Comment by baulig** [comment]
I cherry-picked your PR into https://github.com/mono/mono/pull/9468, so if we land the `SafePasswordHandle` changes first, then we won't need this one anymore.

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by filipnavara** [comment]
@directhex Who should I complain to about the broken API/Project diffs on the PR? (csprojdiff_url is empty string)

**Pull request merged**
