### PR TITLE
[draft] Socket handle reduction and cleanup.

### PR DESCRIPTION
**Pull request by jaykrell**
sockets: Significant reduction in handles and MonoError 
 using the patterns of ref/ref and set_pending.

Change errors from out to ref, in order to not trust native to set them.
 When both sides are C#, this is a more trustyworthy statically checked microoptimization.
 When either side is C, there is a loss of static checking, and the microoptimization seems less worthwhile.

Remove dynamic discovery of field offsets.

Rename generally Foo_internal to Foo_icall,
ves_icall_Foo_internal to ves_icall_foo,
and remove signatures from icall resolution.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by jaykrell** [comment]
@monojenkins build monolite

**Comment by akoeplinger** [comment]
The mono/mono repository is focused on stability and limiting code churn now so I don't think this change is worth doing here. If you think the change is important please reopen it in dotnet/runtime, thank you!

**Pull request closed without merging**
