### PR TITLE
Simplify/reduce CEE_MONO_TLS due their being only one live producer.

### PR DESCRIPTION
**Pull request by jaykrell**
There is a dead producer in Boehm. (see https://github.com/mono/mono/pull/15241)
This combined with https://github.com/mono/mono/pull/15226
will leave no remaining uses of `mono_tls_get_tls_getter`.

### CODE REVIEW

**Comment by jaykrell** [comment]
Probably `MINT_MONO_TLS` should be renamed, and if there were multiple keys here, the switch should be in transform, to produce different interpreter opcodes. Maybe I do that now.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by BrzVlad** [comment]
I think this optimizes dead code

**Comment by jaykrell** [comment]
Rare or dead?
I checked that `MANAGED_ALLOCATION` is defined, at least sometimes.
But I don't claim it is a hot path.
It'll be nice imho to remove `mono_tls_get_tls_getter`.
If it is truly dead, then remove it?

**Comment by BrzVlad** [comment]
yes, it's dead. Managed allocator is only used by jit

**Comment by jaykrell** [comment]
Ah, I see.
So ok if I just assert(false)/unreachable around here, and remove some stuff?
I'll PR that separately. You can weigh in.

**Comment by jaykrell** [comment]
Instead https://github.com/mono/mono/pull/15256

**Comment by jaykrell** [comment]
It isn’t dead. Let’s take this instead.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
