### PR TITLE
[Facades] Add System.Memory facade to mobile profiles

### PR DESCRIPTION
**Pull request by akoeplinger**
Contains only the types we have right now.

Fixes https://github.com/mono/mono/issues/7610

### CODE REVIEW

**Comment by marek-safar** [comment]
Please backport to 2017-12 and up

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff

**Comment by akoeplinger** [comment]
@monojenkins backport 2017-12

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-02

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-04

**Pull request merged**
