### PR TITLE
 Get fault_addr in debugger stacks.

### PR DESCRIPTION
**Pull request by jaykrell**
This time w/o breaking WebAssembly and w/ working on Mac.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build Windows i386

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by jaykrell** [comment]
Review?

**Comment by jaykrell** [comment]
Review?

**Comment by jaykrell** [comment]
@kumpera @lewurm want to try this again?

The problem with the previous, that got reverted, was:

 1. Mainly, it passed before WebAssembly was in CI, and then broke WebAssembly build.

 2. Secondary, the placement of some of the implementation, was where relevant defines were not present. This moves the implementation out of .h, into .c, and with those defines. This probably explains the prior not working on Mac. I tested on Windows too, but it is less useful there, since we don't run debuggers-- if you do run under debugger, the parameter is there.

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
