### PR TITLE
[MacSDK] Update Nuget to 4.7.0

### PR DESCRIPTION
**Pull request by alexischr**
Do not merge as it is technically still a release candidate

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by marek-safar** [comment]
This should not be merged before #7413 is resolved

**Comment by alexischr** [comment]
@marek-safar 4.7.0 should include https://github.com/NuGet/NuGet.Client/commit/eca1a8d23a54818c116eef63875de6a554227ea7 which should resolve https://github.com/mono/mono/issues/7413

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by marek-safar** [comment]
@alexischr could you update this to 4.7 and backport down to 2018-02?

**Comment by alexischr** [comment]
@monojenkins backport to 2018-04

**Comment by directhex** [comment]
Thanks for the ping. Will update on Linux.

**Pull request merged**
