### PR TITLE
Do not always zero localalloc.

### PR DESCRIPTION
**Pull request by jaykrell**
Note that we will still touch the pages (mono_emit_stack_alloc).

Should fix https://github.com/mono/mono/issues/16867.

### CODE REVIEW

**Comment by marek-safar** [comment]
Could you think of any test for this?

**Comment by jaykrell** [comment]
Fair point, yes, I think I can. Not totally portable, but portable enough.

**Comment by jaykrell** [comment]
Specifically one should be able to observe the "uninitialized" values by first calling a function that initializes them, and then accessing the stale values on the stack. I can try that.

**Comment by jaykrell** [comment]
I don't really like "writing" IL when it is actually C# + ildasm.
Anyway there is a test there now.

**Comment by jaykrell** [comment]
Note that this an observable behavior change. But one difficult to see in C#. Still spec conformant, and faster (I didn't verify that).

**Comment by jaykrell** [comment]
Fails interpreter, not surprising.

**Comment by jaykrell** [comment]
Follow the links. This seems a thorny matter. Not really sure should change anything here and now. There was supposed to be an attribute for this but GitHub issue still open.

**Comment by jaykrell** [comment]
Then again, if this PR matches coreclr? Also the check for unsafe seemed reasonable and suggested elsewhere but I think it is the wrong unsafe — command line option, not function flag.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Test is very sensitives, fails many configurations.

**Comment by jaykrell** [comment]
The test is much more sensitive than I'd think and rarely works.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build

**Comment by jaykrell** [comment]
I wonder if the conditions should be combined.
I.e. to restore the previous unsafe optimization.
I think it was counter-spec sort
of, but more deterministic in C#.

Basic problem is C# spec is
reasonable, .NET is semi-reasonable
(should be two flags, not one, or per instruction),
and C# implementation is not reasonable,
basically leaving no choice at all,
except corner case.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
