### PR TITLE
Build libmonoruntime under none desktop Windows API family.

### PR DESCRIPTION
**Pull request by lateralusX**
Initial work to build libmonoruntime under none desktop Windows API families.

This PR is a continuation of #3626 and fixing what's needed to get next runtime library to build under none desktop Windows API family. NOTE, this is initial work, so the functionality in none "classic" windows API code paths are still under development.

This PR will also organize Windows specific code into a specialized implementation files (similar to https://github.com/mono/mono/pull/3707) with corresponding header. This way we can isolate the Windows specific changes from other platforms and also layer for different supported Windows API families.

For example, file-io.c includes generic shared code + none Windows platforms (only windows specific code has been moved), Windows specific code goes into file-io-windows.c and UWP specific changes in file-io-windows-uwp.c. Windows specific code share a header, file-io-windows-internals.h. It is possible to extend this pattern by adding additional file-io-windows-XXX.c source files if other adjustments are needed to the original API surface. NOTE, only files that needed initial API Changes have been adjusted to follow this pattern. So the organization looks like this, from generic to specialized:
file-io.c
|
-> file-io-windows.c
|
-> file-io-windows-uwp.c
|
-> file-io-windows-XXX.c

In cases where reimplementation of methods needs to be done in Windows and cannot be shared with other platforms, the none shareable logic has been extracted into a method implemented by all platforms. The none Windows implementation is kept in the original source file and Windows implementation is done into *-windows.c or *-windows-*.c depending on API family support. In order to declare the methods that needs to be implemented by Windows, a new "internal" header has been added *-internals.h, for example file-io-internals.h declaring the function prototypes. So the complete set of files could look like this (file-io as an example):

file-io.h (current header as is)
file-io.c (common code + all none windows platforms)
file-io-internals.h (function prototypes that implemented on Windows platform, but called from file-io.c)
file-io-windows.c (Windows specific implementation, normally whats been under HOST_WIN32).
file-io-windows-internal.h (header shared between Windows source files).
file-io-windows-uwp.c (UWP specific implementation of functions declared in file-io-internals.h or file-io-windows-internals.h)

The classic Windows API have been split into families and partitions in order to support
different subsets off the Windows API on different platforms. In order to build against other Windows targets/platforms, Mono needs to follow these families/partitions in order to successfully build where API’s have been removed/replaced/extended. Since most Mono platforms uses the Windows API signatures, a new defined has been added to all platforms, HAVE_CLASSIC_WINAPI_SUPPORT, used to decide what implementation to include. On none Windows platforms this is always defined and on Windows platforms it follows the winapifamily.h setup in winconfig.h. In order to keep down regressions, the existing API’s are kept for HAVE_CLASSIC_WINAPI_SUPPORT even if there are more modern alternatives and replacements available.

### CODE REVIEW

**Comment by ntherning** [comment]
LGTM!

**Comment by kumpera** [comment]
LGTM

I'm not a fan on keeping the posix variants in the current files, but that's something we can cleanup later.

**Comment by lateralusX** [comment]
Me neither but needed to draw the line somewhere on how far to take it. Since Windows is the main target for this PR it made sense to stop there for now. At least most of the HOST_WIN32 ifdefs are out from affected files leaving them much cleaner and breaking out posix specifics is a natural continuation as well as other files not affected by the none desktop windows API work.

**Comment by lateralusX** [comment]
Test failures after rebase look similar to other PR's and unrelated to changes done in this PR.

**Pull request merged**
