### PR TITLE
[Tests] Skip some of the System.ServiceModel tests when using MOBILE

### PR DESCRIPTION
**Pull request by mandel-macaque**
Mobile does not support all clases found in System.ServiceModel, we skip
those tests of the not supported classes yet run all the others.

This PR is related to https://github.com/xamarin/xamarin-macios/pull/3238 in which we add the System.ServiceModel bcl tests to be ran in the XI test runs.

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by akoeplinger** [comment]
Failures are known/unrelated, merging.

**Comment by akoeplinger** [comment]
@mandel-macaque can you please open PRs for 2017-12 and master as well?

**Comment by mandel-macaque** [comment]
@akoeplinger wil add a PR for master.

**Pull request merged**
