### PR TITLE
fix PackagePart.GetRelationships for readonly files

### PR DESCRIPTION
**Pull request by ash-lshift**
Fixes this bug: https://bugzilla.novell.com/show_bug.cgi?id=675379

'PackagePart.GetRelationships throws an "Operation not valid when package is read-only" exception when package is open with only read presmissions'

### CODE REVIEW

**Comment by alexrp** [comment]
@alanmcgovern can you review this?

**Comment by alanmcgovern** [comment]
It's been a long time since I worked on this code. The change looks reasonable and the contributed test is pretty self explanatory. It looks good to me!

**Comment by alexrp** [comment]
approve

**Comment by akoeplinger** [comment]
Any updates on this? I just found out this causes an issue for the OpenXML SDK: https://github.com/OfficeDev/Open-XML-SDK/issues/39

**Comment by alanmcgovern** [comment]
I'm just going to run the test on windows myself to verify it's green there, then i'm merging

**Comment by knocte** [comment]
Would be nice to squash the 2 commits into 1 first, though.

**Comment by alanmcgovern** [comment]
I squashed and rewrote the commit message. This was merged as https://github.com/mono/mono/commit/71f7cda39a0215ddf05ad332fff995b2bf2421a0 . Thanks and sorry it took so long. I assumed this had been merged a long time ago!

**Comment by akoeplinger** [comment]
Thanks Alan!

**Comment by alanmcgovern** [comment]
If this is something we should get into the next major release let me know and I'll ask

**Comment by akoeplinger** [comment]
Hmm, I guess it'd be nice but given how long this has been open it's not exactly high-priority ;)

**Pull request closed without merging**
