### PR TITLE
Remove unused Windows JIT TLS code.

### PR DESCRIPTION
**Pull request by jaykrell**
It should be replaced with something different.

### CODE REVIEW

**Comment by jaykrell** [comment]
Agreed.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
This code is not dead as we thought.

https://jenkins.mono-project.com/job/xa/1233/parsed_console/log.html

/r:mscorlib.dll /out:build/deps/basic-profile-check.exe build/common/basic-profile-check.cs
* Assertion: should not be reached at /cygdrive/d/j/workspace/xa/mono/mini/mini-amd64.c:3785


I will revise in:

https://github.com/mono/mono/pull/15567

**Comment by lateralusX** [comment]
OK, so should we close this one then in favor of the other PR and do change as part of that instead?

**Comment by jaykrell** [comment]
Yeah I think so. The other one is looking good, but some sequence point test fails.
I don't think this could should be replace per se, but add to it.
With MSVC we should use __declspec(thread), add to this code.
With MinGW, with poor implementation of __thread, continue using TlsAlloc, and this code.

The PR is "close". Maybe look at it. Or maybe it'll change still and wait.
There is some sequence point test failure I don't understand. Should be able to repro locally at least.

Alternatively, but I don't like it, use `TlsAlloc` either way.
For JIT code, the difference is smaller. We can inline either.
For C/C++, `__declspec(thread)` is much better.
For setting, which JITed code never does, `__declspec (thread)` is also much better -- you can't inline TlsSetValue, but `__declspec (thread)` is inlined either way.

**Comment by lateralusX** [comment]
Code still in use.

**Pull request closed without merging**
