### PR TITLE
Remove extra explicit dist.

### PR DESCRIPTION
**Pull request by jaykrell**
Automake sees through the conditionals, right?

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
I'm not sure automake figures it out, let's give it a try.

@monojenkins build deb

**Comment by akoeplinger** [comment]
@monojenkins build deb

**Comment by jaykrell** [comment]
Similar cleanup: https://github.com/mono/mono/pull/15559

**Pull request merged**
