### PR TITLE
SafeHandle Dispose and SetHandleAsInvalid behaves differently from Ms.Net

### PR DESCRIPTION
**Pull request by madrang**
IDisposable design pattern specify that the implementation of Dispose() and Dispose(bool) should allow for the method to be called more than once.

Close should call Dispose or Dispose(bool) Testet under Ms.Net

This change is released under the MIT license.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@madrang can you rebase this PR?

**Comment by madrang** [comment]
Sure, doing this now. I should be able to upload tonight or tomorrow morning.

**Comment by madrang** [comment]
PR is now rebased on master.

**Comment by madrang** [comment]
I don't know where this information is. But i think it would be nice to document SafeHandle a little more.
It should contain,

SafeHandle.IsInvalid refer only to the handle value it self.

SetHandleAsInvalid is used to close the handle without releasing it. Usually used when an error happens outside of managed code and following that error, the handle cannot be released.

IsClosed will be true if the handle is Released or if SetHandleAsInvalid is called.

**Comment by akoeplinger** [comment]
Looks like @marek-safar did some work on this in 28f16c8991f60a4fcb24e43572a164a90ccdab58 that also fixed your tests. Can you try and see if there are still some missing pieces?

Regarding documentation, our [website](http://www.mono-project.com/) is open source at https://github.com/mono/website, I can walk you through a PR if you want to put it up there.

**Comment by madrang** [comment]
https://github.com/mono/mono/commit/28f16c8991f60a4fcb24e43572a164a90ccdab58

Dispose should not throw.
Close should call Dispose(true)
After SetHandleAsInvalid the Finalizer will not run under Ms.Net

**Comment by jonpryor** [comment]
Related: Calling Close() (or Dispose()) multiple times shouldn't result in an ObjectDisposedException: https://bugzilla.xamarin.com/show_bug.cgi?id=25850

**Comment by madrang** [comment]
I can rebase again if needed.....

**Comment by madrang** [comment]
https://github.com/mono/mono/commit/9652f056bc814a641ec326da23a13fb08ef674d1

Added more comments on the commit.

**Comment by madrang** [comment]
Should i do a diff and push again based on that ??

**Comment by madrang** [comment]
Should i do a diff and push again based on that ??

**Comment by madrang** [comment]
Again running my app under Ms.Net works but crash on Mono with the latest SafeHandle version, it now throws mutiple ObjectDisposedException and kill my thread  pool workers... The version i keep pushing works fine and follows Ms.Net behavior....

**Comment by madrang** [comment]
I will add more test to show the part that are broken, it will be more simple.

**Comment by madrang** [comment]
https://github.com/mono/mono/pull/1502

**Comment by madrang** [comment]
https://github.com/mono/mono/pull/1503 Closing a handle or Disposing a handle should not result in an ObjectDisposedException.

**Comment by madrang** [comment]
https://github.com/mono/mono/pull/1504 Allows refs to be released after the handle is set as invalid.

**Comment by madrang** [comment]
Closing this PR. Only 2 changes needed so that Mono SafeHandle behave the same as Ms.Net, https://github.com/mono/mono/pull/1502 and https://github.com/mono/mono/pull/1504

**Pull request closed without merging**
