### PR TITLE
Install mono-api-html

### PR DESCRIPTION
**Pull request by mhutch**
We install its counterpart mono-api-info already

### CODE REVIEW

**Comment by akoeplinger** [comment]
Once this is merged, [mono-devel.install](https://github.com/mono/linux-packaging-mono/blob/master/debian/mono-devel.install) and [whitelist.txt](https://github.com/mono/bockbuild/blob/master/profiles/mono-mac-release/packaging/resources/whitelist.txt) needs to be updated as well.

I think we'll also need a man doc like [mono-api-info.1](https://github.com/mono/mono/blob/master/man/mono-api-info.1).

**Comment by mhutch** [comment]
Yeah, I considered adding a manpage, then I noticed how out of date the the manpage for mono-api-info is -  it hasn't been updated in 6 years. So I don't think that a manpage for mono-api-html should really be a blocker :)

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
LGTM

**Comment by akoeplinger** [comment]
@mhutch looks like this has a merge conflict, can you please rebase? I think it's good to go otherwise.

**Comment by mhutch** [comment]
Done!

**Comment by akoeplinger** [comment]
@monojenkins merge

**Pull request merged**
