### PR TITLE
[runtime] Allocate the temporary vtable array using g_malloc in mono_class_setup_vtable (), alloca can overflow for large vtable sizes. Hopefully fixes #45140.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
QA verified for C8SR2: https://trello.com/c/pZF8JMUe

**Comment by rolfbjarne** [comment]
There's an identical PR for the watchOS branch: PR #4100.

**Comment by rolfbjarne** [comment]
@vargaz does this look good?

**Comment by vargaz** [comment]
Looks ok.

**Comment by rolfbjarne** [comment]
Merging since this is QA-verified.

**Pull request merged**
