### PR TITLE
[arm64] Make OP_CHECK_THIS read only a byte, to prevent unaligned access errors.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Comment by jaykrell** [comment]
Other architectures?

**Comment by lewurm** [comment]
Let me hijack this PR to do a recap of the Slack conversation that lead to this fix.

We started to see ARM64 lanes fail to pretty reliably in `cil-stringreplacer` after the PR https://github.com/mono/mono/pull/9204 for `Span<T>` had been merged into `master`. Actually, this failure already showed up on some CI runs of this PR (e.g. https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter-aarch64/6250/parsed_console/log.html ), but it didn't seem to be reliable enough yet and probably had been falsely identified as a roslyn crash. To be fair, error handling was also broken at this time due to https://github.com/mono/mono/issues/9531 so there was some additional factor that helped the crash to sneak through.

Additionally this crash needed some special conditions in the environment to be true; it wasn't reproducible on our "dev arm64" box. Thanks to @akoeplinger for providing proper steps to reproduce the exact environment that we have on CI.

Once reproduced, it was pretty clear this is a `Span<T>` related issue:
```
Thread 1 "mono" received signal SIGSEGV, Segmentation fault.
0x0000007fac841de4 in ?? ()
(gdb) bt
#0  0x0000007fac841de4 in ?? ()
#1  0x0000007faaa64120 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) p mono_pmip (0x0000007fac841de4)
$1 = 0x5555def000 " System.SpanHelpers:SequenceCompareTo<char> (char&,int,char&,int) {0x5555df0510} + 0x54 (0x7fac841d90 0x7fac841e60) [0x555590ed80 - cil-stringreplacer.exe]"
(gdb) x/10i $pc
=> 0x7fac841de4:        ldr     x30, [x0]
   0x7fac841de8:        ldrh    w0, [x0]
   0x7fac841dec:        sub     w22, w0, w1
(gdb) p/x $x0
$4 = 0x7fae52bffa
```
So what happens is that `ldr` tries to do a word load from an _unaligned_ address (`0x7fae52bffa`) which causes a segfault. This is what this PR fixes: It changes the word load to a byte load which doesn't have this behaviour (side note: `LR` is a alias for `x30`).

**Comment by kumpera** [comment]
@lewurm @vargaz could you explain how come `this` can be an unaligned pointer?
It's counter intuitive to what one would normally assume about managed object pointers.

**Comment by lewurm** [comment]
@kumpera it's unsafe code: https://github.com/mono/corefx/blob/df455a492907085c0bf9dd8c92de161e602251fe/src/Common/src/CoreLib/System/SpanHelpers.Char.cs#L20

**Comment by jaykrell** [comment]
I had the same question, and still do -- do/can we use "this" for arbitrary other things?

**Comment by lewurm** [comment]
it's the guard from inlining a method via `callvirt`: https://gist.github.com/jaykrell/d3fe055780a1be1b7c2bed844b969665#file-arm64-cil-stringreplacer-fast-span-L85-L96

**Comment by kumpera** [comment]
It makes sense. `this` can be the byref to a valuetype. And if that's a `byte` or `char`, it's ok to be unaligned.

**Pull request merged**
