### PR TITLE
IL tests for "Default interface methods" from CoreCLR

### PR DESCRIPTION
**Pull request by EgorBo**
IL tests for "Default Interface methods" feature (runtime support was introduced in https://github.com/mono/mono/pull/4625)
I am not 100% sure in my ILAsm changes (few checks prevented to use DIM).
Tests were copied from [CoreCLR](https://github.com/dotnet/coreclr/tree/dev/defaultintf/tests/src/Loader/classloader/DefaultInterfaceMethods)

- genericmethods.il - PASS
- sharedgenerics.il - PASS
- valuetypes.il - PASS
- constrainedcall.il - FAIL
- diamondshape.il - FAIL
- methodimpl.il - FAIL
- simple.il - FAIL

Failed tests are temporarily ignored in the Makefile.am (see KNOWN_FAILING_TESTS) to be able to merge the PR and take a look on them later.

### CODE REVIEW

**Comment by marek-safar** [comment]
@EgorBo they all fail with exit code: 100

**Comment by akoeplinger** [comment]
> @EgorBo they all fail with exit code: 100

CoreCLR tests actually use 100 as the success exit code. Our runtime test runner supports `--expected-exit-code` for passing this in.

**Comment by EgorBo** [comment]
@akoeplinger @marek-safar I already changed 100 to 0 (0 - success, 101 - failure)
should I use the  `--expected-exit-code` flag instead? (also I added a suffix "dim-" for all of them, it stands for Default Interface Methods).

**Comment by marek-safar** [comment]
I am fine with 100->0 change but we need to disable them on failing platforms with issue filled

**Comment by marek-safar** [comment]
build

**Comment by marek-safar** [comment]
@EgorBo you also need to ignore MonoTests.runtime-interp.dim-valuetypes.exe for interpreter, please fill extra github issue for that

**Comment by EgorBo** [comment]
@marek-safar done

**Pull request merged**
