### PR TITLE
Already successful compiled Mono throws errors what is ".....Default.txt" from Build Directory?

### PR DESCRIPTION
**Pull request by sourceskyboxer**
Hello everyone

PS: Thanks for explanation for successful compilations with Mono from Github = x86 -> Successful with Cygwin x86 = CORRECT! THANKS FOR HELP ME!

And I check my Example.exe with GTK Sharp 2.14x

I don't know how do I write "Microsoft.Clang.Default.txt"?
```

mkbundle --deps --static Example.exe -o Output.exe -v
OS is: Windows
Sources: 1 Auto-dependencies: True
Attempting to load assembly: Example.exe
Assembly Example.exe loaded successfully.
Attempting to load assembly from: .\I18N.West.dll
Attempting to load assembly from: .\I18N.dll
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\gtk-sharp
Attempting to load assembly from: .\glib-sharp
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\Mono.Security
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System
Attempting to load assembly from: .\System.Configuration
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System.Xml
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System
Attempting to load assembly from: .\System.Configuration
Attempting to load assembly from: .\System
Attempting to load assembly from: .\System.Security
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System
Attempting to load assembly from: .\Mono.Security
Attempting to load assembly from: .\System.Xml
Attempting to load assembly from: .\System.Xml
Attempting to load assembly from: .\System.Core
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System
Attempting to load assembly from: .\Mono.Posix
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\System
Attempting to load assembly from: .\atk-sharp
Attempting to load assembly from: .\glib-sharp
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\gdk-sharp
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\glib-sharp
Attempting to load assembly from: .\pango-sharp
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\glib-sharp
Attempting to load assembly from: .\Mono.Cairo
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\Mono.Cairo
Attempting to load assembly from: .\pango-sharp
Attempting to load assembly from: .\Mono.Cairo
Attempting to load assembly from: .\glib-sharp
Attempting to load assembly from: .\mscorlib
Attempting to load assembly from: .\I18N
Attempting to load assembly from: .\mscorlib
   embedding: D:\cygwin\home\Jens\example\Example.exe
 config from: D:\cygwin\home\Jens\example\Example.exe.config
   embedding: D:\cygwin\home\Jens\example\mscorlib.dll
   embedding: D:\cygwin\home\Jens\example\gtk-sharp.dll
   embedding: D:\cygwin\home\Jens\example\glib-sharp.dll
   embedding: D:\cygwin\home\Jens\example\System.dll
   embedding: D:\cygwin\home\Jens\example\Mono.Security.dll
   embedding: D:\cygwin\home\Jens\example\System.Configuration.dll
   embedding: D:\cygwin\home\Jens\example\System.Xml.dll
   embedding: D:\cygwin\home\Jens\example\System.Security.dll
   embedding: D:\cygwin\home\Jens\example\System.Core.dll
   embedding: D:\cygwin\home\Jens\example\Mono.Posix.dll
   embedding: D:\cygwin\home\Jens\example\atk-sharp.dll
   embedding: D:\cygwin\home\Jens\example\gdk-sharp.dll
   embedding: D:\cygwin\home\Jens\example\pango-sharp.dll
   embedding: D:\cygwin\home\Jens\example\Mono.Cairo.dll
   embedding: D:\cygwin\home\Jens\example\I18N.West.dll
   embedding: D:\cygwin\home\Jens\example\I18N.dll
AS =  (default)
VCINSTALLDIR =  (default)
VisualStudioVersion =  (default)

Unhandled Exception:
System.IO.FileNotFoundException: Could not find file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.ClangC2Version.default.txt"
File name: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.ClangC2Version.default.txt'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) [0x00067] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) [0x0000d] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
  at System.IO.File.OpenText (System.String path) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.File.ReadAllLines (System.String path) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at MakeBundle+VC15Clang.FindVCToolchainProgram (MakeBundle+InstalledSDKInfo vcSDK) [0x0003e] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle+VisualStudioSDKToolchainHelper.GetVCToolChainProgram (System.Collections.Generic.List`1[T] programs) [0x00038] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle+VisualStudioSDKToolchainHelper.GetVCClangCompiler () [0x00000] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.GetAssemblerCompiler () [0x00029] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.GetAssemblerCommand (System.String sourceFile, System.String objectFile) [0x00017] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.GenerateBundles (System.Collections.Generic.List`1[T] files) [0x00688] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.Main (System.String[] args) [0x00d8e] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not find file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.ClangC2Version.default.txt"
File name: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.ClangC2Version.default.txt'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options, System.String msgPath, System.Boolean bFromProxy, System.Boolean useLongPath, System.Boolean checkHost) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize, System.Boolean checkHost) [0x00067] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) [0x0000d] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
  at System.IO.File.OpenText (System.String path) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at System.IO.File.ReadAllLines (System.String path) [0x00000] in <46609175c08c4595ac2ea612c7e5657d>:0
  at MakeBundle+VC15Clang.FindVCToolchainProgram (MakeBundle+InstalledSDKInfo vcSDK) [0x0003e] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle+VisualStudioSDKToolchainHelper.GetVCToolChainProgram (System.Collections.Generic.List`1[T] programs) [0x00038] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle+VisualStudioSDKToolchainHelper.GetVCClangCompiler () [0x00000] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.GetAssemblerCompiler () [0x00029] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.GetAssemblerCommand (System.String sourceFile, System.String objectFile) [0x00017] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.GenerateBundles (System.Collections.Generic.List`1[T] files) [0x00688] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
  at MakeBundle.Main (System.String[] args) [0x00d8e] in <bde0173afe0d4ea9ae589929c3bf1b79>:0
```

How do I understand what is ".....Default.txt" I haven't Default.txt in Visual Studio 2017 Community - Build Directory. Can I have to learn my own example?

Thanks!

// EDIT:
It happens now

If I type command: `mkbundle --deps --static Example.exe -o Output.exe -v`
Than it shows information and warning:
```
mkbundle --deps --static Example.exe -o Output.exe -v
Corlib not in sync with this runtime: expected corlib version 1050800000, found 1050900001.
Loaded from: C:\Program Files (x86)\Mono\lib\mono\4.5\mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```

Hello I already compiled with Cygwin x86. Why does it throws common mesage as I need new version? How do I upgrade mono from github?
Sorry I don't have experience about Git Bash. I never use yet with Github....

Please stop take advantage my time! I hate you always make me wrong like @Johan from Xamarin Bugzilla told me Mono ( last version I should compile. And I tried until successful ( Since today morning )
Why now it happens? STOP TO TAKE ADVANTAGE ME! I WILL BE MAD. I feel you bully me. WTF? What's a fuck? I want mono developers are seriously. :(

I already download mono runtime and Cygwin build successful with mono source from Github. Why do I not have monosgen-2.0-static.lib.

GRRRR I AM MAD NOW! BECAUSE I ALREADY TRIED
`./autogen.sh --prefix=/cygdrive/d/monoinstall --host=i686-w64-mingw32 --with-static_mono=yes --with-ikvm-native=yes --with-profile4=yes` It is default generator for me. I want --with-static_mono=yes it means generates into monosgen-2.0-static.lib But where is monosgen-2.0-static.lib????????????????????

STOP LIE ME! I ALWAYS TRIED TRIED TRIED... Since 2 weeks stop bully me!

I will fight you now because you always force my explanation about STATIC VERSION LIKE PORTABLE because I don't need install Mono Runtime if I release bundled apps by Mono Runtime with fucking monos-2.0-sgen.dll. "PLEASE LISTEN ME! I WANT ONLY PORTABLE MONO BUNDLED APPLICATION"

You're idiots

### CODE REVIEW

**Comment by marek-safar** [comment]
Please rebase your changes on top of master

**Comment by lateralusX** [comment]
@sourceskyboxer, mkbundle is picking up VS 2017 and if you have not set a custom AS, then it will try to locate and use Clang for VS codegen as assembler. This is an additional install item in the VS installer that needs to be selected, once installed you will get the needed files in install directories. You still have the option to set an explicit AS to different gcc assembler (if you don't want to use Clang for VS codegen), that it will use. These details are explained here as well, https://github.com/mono/mono/pull/5664.

Is just a question  and no intention to contribute any code or changes? If so (and above information doesn't solve the problem you are experience), please file a bug on https://bugzilla.xamarin.com and we can have the discussion there instead.

**Comment by johan** [comment]
On github, @johan does not notify who you think it does.

**Comment by akoeplinger** [comment]
Let's continue this over email, GitHub PRs are not the best place for general discussion.

**Pull request closed without merging**
