### PR TITLE
[xbuild] Don't show the deprecation notice for minimal or quiet logging

### PR DESCRIPTION
**Pull request by radical**
.. levels. This is useful for scripts that might depend on minimal/quiet
levels, to parse output of a specific target execution, eg.
Xamarin.Android .

### CODE REVIEW

**Comment by xmcclure** [comment]
LGTM

**Comment by marek-safar** [comment]
Why not for minimal? We want this message to be noticed

**Comment by akoeplinger** [comment]
@marek-safar it broke XA, they're parsing the xbuild output.

**Comment by marek-safar** [comment]
XA is using minimal? It also means they will break when they switch to msbuild again

**Comment by akoeplinger** [comment]
@marek-safar yes, e.g.: https://github.com/xamarin/xamarin-android/blob/54a7a0299ef6489ce5cb861b43951f72c5f6a620/Makefile#L32. It should work with msbuild too.

**Comment by marek-safar** [comment]
Wouldn't be /nologo better for suppressing the deprecation message?

**Comment by akoeplinger** [comment]
yep, that'd work too

**Comment by jonpryor** [comment]
@marek-safar: How would using `msbuild` break use of `/v:minimal`?

The xamarin-android repo *does* build with the `msbuild` included in Mono 4.6 (maybe even 4.4?), and that build lane is still running:

<https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-msbuild/>

There is thus not much of a "switch to msbuild again," as my intention is to *keep* it building under *both* msbuild and xbuild until xbuild is dead as a doornail.

**Pull request merged**
