### PR TITLE
Convert thread get name to coop/handle.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
Might want to hold off here, since I'm working on SetName and Ludovic made a suggestion that quite disrupts this if I understand correctly -- SetName shall take and store utf8 only.

**Comment by jaykrell** [comment]
Had to merge with MonoError change.

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by luhenry** [comment]
@monojenkins build Windows i386

**Comment by luhenry** [comment]
@monojenkins build Windows x64

**Pull request merged**
