### PR TITLE
[coop] Synchronization primitive friendliness

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
@lambdageek @kumpera whenever you have time, would you mind reviewing this PR? Thank you! :)

**Comment by ludovic-henry** [comment]
For some numbers: when running `make check -C mcs/class/corlib`, I get a decrease of 10x in blocking state transition.

**Comment by kumpera** [comment]
What's causing the 10x reduction in transitions? This change should, if anything, increased the number of transitions.

**Comment by ludovic-henry** [comment]
https://github.com/ludovic-henry/mono/commit/d435639110caa9a4a199e3a91f9d337f1e7bc699#diff-df675e7de49d2766cf7cbd6956a00699R50 is what reduces the amount of transitions. We could do the same for semaphores, but we would need to add `mono_os_sem_trywait`

**Pull request merged**
