### PR TITLE
[Windows] Windows x64 full AOT native unwind info support.

### PR DESCRIPTION
**Pull request by lateralusX**
Emit needed sections when building Windows x64 full AOT targeting Clang for MS codegen in order for linker to include entries in process unwind tables for full AOT:ed managed functions and trampolines. Implementation also includes a cache used to minimize the number of duplicated unwind data section in each object file, reducing final image size.

PR also includes implementation to emit very basic codeview information into full AOT builds on Windows x64. The codeview information is far from complete and is currently just initial work needed to get function symbol names to appear in native callstack that includes managed functions. Described functions does not include parameters, local variables or line info at the moment, but could be extended in the future.

Fix also make sure linker will emit PDB files including information that can be picked up by debuggers. It is possible to disable codeview info by passing "nodebug" to AOT compiler, this will also disable the generation of PDB files, if a DLL would have been build.

Example of callstack in Visual Studio native debugger running full AOT version of basic.exe test:

```
basic.exe.dll!Tests:test_0_signed_ct_div()	C#
mscorlib.dll.dll!(wrapper runtime-invoke) object:runtime_invoke_dynamic()	C#
mono-2.0-sgen.dll!mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2777	C
mono-2.0-sgen.dll!do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) Line 2851	C
mono-2.0-sgen.dll!mono_runtime_invoke_checked(_MonoMethod * method, void * obj, void * * params, _MonoError * error) Line 3003	C
...
```

### CODE REVIEW

**Comment by tritao** [comment]
Nice 👍

**Comment by luhenry** [comment]
@vargaz or @alexanderkyte  could you please review that one?

**Comment by vargaz** [comment]
LGTM.
It would be nice to avoid all the ifdefs in aot-compiler.c by add functions like emit_unwind_info () and putting the ifdef there.

**Comment by lateralusX** [comment]
Rebased on master + added review feedback.

**Comment by lateralusX** [comment]
build

**Comment by lateralusX** [comment]
Failures looks unrelated to PR changes.

**Pull request merged**
