### PR TITLE
[2019-08] bump msbuild with more p2 packages

### PR DESCRIPTION
**Pull request by lewing**
Fixes https://github.com/mono/mono/issues/17637 as well

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by lewing** [comment]
fixes #17637 as well

**Comment by lewing** [comment]
@monojenkins build Linux AArch64 FullAOT

**Comment by lewing** [comment]
@monojenkins build Linux AArch64 FullAOT

**Comment by lewing** [comment]
OS X Extended

**Comment by radical** [comment]
`OS X Extended` failing with `RemotingServicesTest.Bug46473`, should be unrelated to this.

**Pull request merged**
