### PR TITLE
[TestDriver] merge verbose and quiet flag, and be more verbose per default

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by akoeplinger** [comment]
I like it :+1:

**Comment by lewurm** [comment]
hmm, some other thing in the test pipeline consumes the output anyway, so it wouldn't change the output on the bots anyway.  closing it.

**Comment by lewurm** [comment]
@akoeplinger pointed out to me that the wrapper around calling the tests only shows the output if the test failed or timed out, so it wouldn't spam too much anyway

**Comment by akoeplinger** [comment]
The perl-based test runner actually does the same, so this shouldn't cause any additional output in the happy case.

**Comment by vargaz** [comment]
There is additional output if you run it from the command line or as part of the test suites in mini/Makefile.am.

**Comment by akoeplinger** [comment]
If you run a single test from the command line then I'd argue you actually want to see the more verbose output?

As for the test suites in mini/Makefile.am: I tried them and don't see any additional output because they're run via mono --regression and not via the TestDriver there.

@vargaz do you feel strongly about this? I'd really like to avoid adding yet another env var in our CI systems when this behavior should really be the default.

**Comment by vargaz** [comment]
I do like the unix way of doing things, which means that if nothing goes wrong, nothing or not very much is printed.

**Pull request closed without merging**
