### PR TITLE
[offsets-tool] Make sure to re-clone when the hash for the cpp binaries changes.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
CC @tritao

**Comment by rolfbjarne** [comment]
There's also PR #3954 for the mono-4.8.0-branch.

**Comment by akoeplinger** [comment]
As I mentioned on Slack, I think a better approach would be to download the .zip from github: https://github.com/xamarin/CppSharpBinaries/archive/60f763a9.zip

**Comment by tritao** [comment]
lgtm

**Pull request merged**
