### PR TITLE
[System.IO] Enable more CoreFX tests for FileSystemWatcher

### PR DESCRIPTION
**Pull request by alexischr**
Work PR review failing tests and fix/disable

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build

**Comment by alexischr** [comment]
@monojenkins build

**Comment by marek-safar** [comment]
@alexischr what's the status of this?

**Comment by steveisok** [comment]
Since this is older, I'm closing.  Please see the [old pull request policy](https://github.com/mono/mono/wiki/Pull-Request-Guide#old-pull-request-policy) for more info.

**Pull request closed without merging**
