### PR TITLE
[wasm] Dynamic Release RUNTIME configuration

### PR DESCRIPTION
**Pull request by kjpou1**
Modify configuration flag `ENABLE_WASM_DYNAMIC_RUMTIME` to `ENABLE_WASM_DYNAMIC_RUNTIME`

### CODE REVIEW

**Comment by MaximLipnin** [comment]
This place also needs to be fixed:

https://github.com/mono/mono/blob/11f75e5260600a8cd15bc9a721f3296b94a068ea/sdks/builds/wasm.mk#L156

**Comment by Suchiman** [comment]
But why is the rum gone

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build OS X x64 Android SDK

**Pull request merged**
