### PR TITLE
[System] Add FSEvent FileSystemWatcher to 'monotouch' BCL profile

### PR DESCRIPTION
**Pull request by alexischr**

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@baulig this just for master so it should be safe to land, it won't interfere with existing branches

**Comment by marek-safar** [comment]
@alexischr please rebase it

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by luhenry** [comment]
@alexischr it's not benign on master since we do build and run tests on iOS. Also just postponing the native work until it bits us in a release branch integration is exactly what's already slowing down the `2018-10` integration. So let's not repeat the same mistake, and make sure the native bits are coming right along the managed bits.

**Comment by luhenry** [comment]
Just discussed offline: right now, the FSW throws `PlatformNotSupportedException` on `monotouch`, so this PR is actually going to bring us closer to getting it to work, rather than regressing. So :+1: on my end. Thanks for the clarification @alexischr

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by alexischr** [comment]
Failures are on `upload-to-sentry` step (cc @alexanderkyte)

**Pull request merged**
