### PR TITLE
[aot] Prepend the assembly name to the names of gsharedvt wrappers to avoid duplicate symbol errors during static linking.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/20417.

### CODE REVIEW

**Comment by lambdageek** [comment]
Is the code in the wrappers identical?  Can we make them [`linkonce_odr`](https://llvm.org/docs/LangRef.html#id1243) symbols instead? Although I'm not sure how we would do that with non-LLVM AOT.

**Comment by CoffeeFlux** [comment]
Also, is this going to be a nontrivial size increase if we're doing this for every wrapper?

**Comment by vargaz** [comment]
Making them linkonce is kinda complicated, we have a dedup pass instead which only emits them once into a dummy assembly, but that is not used on ios right now.

**Comment by vargaz** [comment]
This is only done for the gsharedvt wrappers which are only used if the interpreter is enabled. Also, these are just symbol names which presumably get stripped.

**Comment by vargaz** [comment]
It will lead to a size increase, but only if the interpreter is enabled.

**Comment by lambdageek** [comment]
> Making them linkonce is kinda complicated, we have a dedup pass instead which only emits them once into a dummy assembly, but that is not used on ios right now.

Is the naming change going to interfere with the dedup pass on platforms that use it?


> It will lead to a size increase, but only if the interpreter is enabled.

We should make an issue to revisit this if there will be situations where we'll run the interpreter together with AOT on ios

**Comment by vargaz** [comment]
> > Making them linkonce is kinda complicated, we have a dedup pass instead which only emits them once into a dummy assembly, but that is not used on ios right now.
> 
> Is the naming change going to interfere with the dedup pass on platforms that use it?
No.
> 
> > It will lead to a size increase, but only if the interpreter is enabled.
> 
> We should make an issue to revisit this if there will be situations where we'll run the interpreter together with AOT on ios

**Review by lambdageek — APPROVED** [review]

**Review by CoffeeFlux — APPROVED** [review]

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by imhameed** [comment]
@vargaz @lambdageek @marek-safar Any objections to backporting this to 2020-02? I installed a fresh copy of VSMac and Mono recently and https://github.com/mono/mono/issues/20417 still happens.

**Comment by lambdageek** [comment]
@imhameed I think it's ok to backport

**Comment by imhameed** [comment]
@monojenkins backport to 2020-02

**Pull request merged**
