### PR TITLE
Make mono_fmod extern "C and not static, to simplify later

### PR DESCRIPTION
**Pull request by jaykrell**
removal of JIT icall hashing. Making it more consistent with other icalls.
Costing maybe one instruction in some slow paths.

### CODE REVIEW

**Comment by jaykrell** [comment]
The motivation is here:
https://github.com/mono/mono/pull/14277/files#diff-307195a8afdfeac6e3df25eef5aaf9d6R702

**Comment by vargaz** [comment]
The function should be moved to jit-icalls.c then.

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build Linux x64

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
