### PR TITLE
mono-complex cleanup: remove macros and rename

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by luhenry** [comment]
What's the reason for this change?

**Comment by jaykrell** [comment]
When I first ported the complex math to C++, the macros to rename were decided against. 

But the line damage was a bit much. 

This follows through with that decision. Perhaps just do that.

**Comment by jaykrell** [comment]
Otherwise it is to follow mono naming style.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request closed without merging**
