### PR TITLE
[jit] Pass MonoError to resolve_vcall

### PR DESCRIPTION
**Pull request by lambdageek**

### CODE REVIEW

**Comment by lambdageek** [comment]
@vargaz I think I'm doing this correctly.  Does `mono_init_vtable_slot` not have a wrapper because it's on the fast path, because we need it to bootstrap, or because we somehow know that it won't throw?

**Comment by vargaz** [comment]
It does have a wrapper, its registered with:
	/* This needs a wrapper so it can have a preserveall cconv */
	register_icall (mono_init_vtable_slot, "mono_init_vtable_slot", "ptr ptr int", FALSE);

**Comment by vargaz** [comment]
These functions are called only in llvmonly mode, where its ok to raise exceptions, since we raise them using c++. So the mono_raise_exception () calls can stay, or they can be changed to mono_llvm_throw_exception () to make this more explicit.

**Comment by lambdageek** [comment]
Sorry, I meant the other one: `mono_resolve_vcall_gsharedvt`.

But ok, if they're allowed to throw I'll switch them to the llvm throw.

**Pull request closed without merging**
