### PR TITLE
[Backport 2018-02] Add merp parameters

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins build deb with monolite

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
These PR failures are seen on all my other, unrelated PRs. The ones that have not, like Hybrid Suspend, I have been told "probably are okay / expected." 

I find this build output noisy and unclear. Do I have anything left to do for this PR or can we merge?

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
Merging as this is important for VSMac (see our discussion in Slack).

**Pull request merged**
