### PR TITLE
Do not depend on gboolean to have multiple bits.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
The changes are ok but the const changes are not needed, we don't use const on locals in our codebase.

**Comment by jaykrell** [comment]
It is so the human reader can likely skip looking for additional writes.
 Isn't that a good thing?
 Granted, you can cast it away, but that is rare.
Can we ever try to do better than prior practise?

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by BrzVlad** [comment]
For me const doesn't add any benefit. If a local is constant you can pretty easily tell by the context, local name. I consider const everywhere is just adding code bloat.

**Comment by jaykrell** [comment]
"code bloat" we are talking source code bloat, right?

The codegen will be the same. Just with the extra hint in the source for the human.

Being a local doesn't give the information. You have to scan the function -- could be a small function, not much to scan, could be a large function, much to scan.

Some code bases put const very liberally for this reason, like on almost every parameter.

**Comment by baulig** [comment]
I'm pretty much in favor of being `const`-ly correct ;-)

**Pull request merged**
