### PR TITLE
[2018-08] Add more detailed reporting for exceptions 

### PR DESCRIPTION
**Pull request by alexanderkyte**
This bumps the crash reporting file format to version 0.0.3.

Backport of #12946.

/cc @luhenry @alexanderkyte

### CODE REVIEW

**Comment by alexanderkyte** [comment]
Github's showing some commits from the HEAD of 2018-08. Hmm, let me fix that.

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
https://gist.github.com/alexanderkyte/7c60114966d32c4fb9ee250b5ccff1be
The sample of @leculver 's Program.cs async bug which is:
https://gist.github.com/alexanderkyte/f8188ee1922589c504e420d3de49d9c9

**Comment by alexanderkyte** [comment]
iOS SDK error: 

```

***** MonoTests.Runtime.JitTests.Objects

Tests run: 11, Passed: 11, Errors: 0, Failures: 0, Inconclusive: 0
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
Elapsed time: 00:00:00.2510000
make[1]: Leaving directory '/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios'
make[1]: Entering directory '/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios'
mono appbuilder.exe --target ios-sim64 --mono-sdkdir /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios/../out --appdir /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios/bin/ios-sim/test-corlib.app --runtimedir /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios/runtime --builddir obj/ios-sim/test-corlib.app --sysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk --signing-identity - --bundle-executable test-corlib --bundle-identifier com.xamarin.mono.ios.test-corlib --bundle-name test-corlib -r ../../mcs/class/lib/monotouch/mscorlib.dll -r ../../mcs/class/lib/monotouch/System.dll -r ../../mcs/class/lib/monotouch/System.Xml.dll -r ../../mcs/class/lib/monotouch/System.Core.dll -r ../../mcs/class/lib/monotouch/I18N.dll -r ../../mcs/class/lib/monotouch/I18N.West.dll -r ../../mcs/class/lib/monotouch/Mono.Simd.dll -r ../../mcs/class/lib/monotouch/Mono.Security.dll -r ../../mcs/class/lib/monotouch/System.Numerics.dll -r ../../mcs/class/lib/monotouch/System.Numerics.Vectors.dll -r ../../mcs/class/lib/monotouch/nunitlite.dll -r test-runner.exe -r ../../mcs/class/lib/monotouch/tests/monotouch_corlib_test.dll
mkdir -p /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios/bin/ios-sim/test-corlib.app
if test "x../../mcs/class/corlib/{es-ES,nn-NO}" != "x"; then cp -r ../../mcs/class/corlib/{es-ES,nn-NO} /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios/bin/ios-sim/test-corlib.app/; fi
cp: ../../mcs/class/corlib/es-ES: No such file or directory
cp: ../../mcs/class/corlib/nn-NO: No such file or directory
make[1]: *** [Makefile:89: build-ios-sim-corlib] Error 1
make[1]: Leaving directory '/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios'
make: *** [Makefile:150: run-ios-sim-all] Error 1
make: Leaving directory '/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/sdks/ios'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-ios/scripts/ci/babysitter: Test suite terminated with code 2, and suite cannot report test case data. Halting.
*** end(10): run-sim: \e[43mUnstable\e[0m
```

**Comment by leculver** [comment]
@luhenry @alexanderkyte Will this change make it into VS for Mac Preview 3?

Sorry I think you might have pinged me via slack on this but I lost track of the notification.

**Comment by alexanderkyte** [comment]
@leculver it should make it. The deadline is tonight.

**Pull request merged**
