### PR TITLE
Bump to F# 5.0

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes https://github.com/mono/mono/issues/16763

Closes https://github.com/mono/mono/pull/17925
Closes https://github.com/mono/mono/pull/17882

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
Test package is available here: https://xamjenkinsartifact.azureedge.net/build-package-osx-mono-pullrequest/pr/564/2e80b7862efbfc1b65ce2db921e228c99ed15db0/MonoFramework-MDK-pr@2e80b7862ef-dirty-6.12.0.107.macos10.xamarin.universal.pkg

@KirillOsenkov I ran a simple helloworld F# app and that worked fine, do you have more sophisticated tests?

**Comment by KirillOsenkov** [comment]
@cartermp and I will try to take it for a spin today! Thank you so much!

**Comment by KirillOsenkov** [comment]
@nosami @chkn FYI

**Comment by KirillOsenkov** [comment]
@mrward FYI

**Comment by chkn** [comment]
This is amazing! Happy to help test it out as well 💯

**Comment by KirillOsenkov** [comment]
I'm happy to report that VSMac with this build of Mono is able to successfully compile latest F# syntax:
image

Ship it!

**Review by KirillOsenkov — APPROVED** [review]
Works with VSMac and compiles latest F# programs!

**Review by mrward — APPROVED** [review]
Looks good to me :shipit: This allows the ASP.NET Core empty and web api project templates for .NET 5 to be compiled in VS Mac.

**Comment by dsyme** [comment]
I think with [this line](https://github.com/mono/mono/pull/20511/files#diff-237f7df6fa087d1c8b5f561bbb3eefa70f4830f23ee819273553980797b49496R7) we can now officially retire https://github.com/fsharp/fsharp in favour of https://github.com/dotnet/fsharp.

I'll discuss with the F# Software Foundation in that repo

**Comment by dsyme** [comment]
This is amazing work @akoeplinger .

**Comment by dsyme** [comment]
@akoeplinger Do you want to push any of those patches back to dotnet/fsharp?

**Comment by dsyme** [comment]
Also, is the bump of VSMac F# support going ok?  Let me know if you hit any issues

**Comment by nosami** [comment]
@akoeplinger awesome work!

**Comment by akoeplinger** [comment]
> Do you want to push any of those patches back to dotnet/fsharp?

@dsyme we can do that but in https://github.com/dotnet/fsharp/pull/10305#issuecomment-713836446 I read that the plan is to remove the desktop build of fcs so I wasn't sure if you want to take that change.

**Review by marek-safar — APPROVED** [review]

**Comment by akoeplinger** [comment]
Official build of the Mono .pkg can be found here: https://xamjenkinsartifact.azureedge.net/build-package-osx-mono/2020-02/113/970783731fccf269dcc3d2385bfd4adadf172196/MonoFramework-MDK-6.12.0.106.macos10.xamarin.universal.pkg

**Comment by TimLariviere** [comment]
@akoeplinger Do you know when this will be released?
The current stable VSfM (8.8 build 2913) version only ships with Mono 6.12.0.93 which doesn't support F# 5.

Tested with your link and it compiles and runs fine, even though VSfM is not happy about it.

**Comment by mrward** [comment]
@TimLariviere You should be able a later Mono 6.12 with VS Mac 8.8 now. Why is VS Mac not happy about it? I am using Mono 6.12.0.107.

There is a PR pending for Mono 6.12.0.107 to be included with VS Mac 8.8. It should be in a service release at some point for VS Mac.

**Comment by TimLariviere** [comment]
@mrward Indeed. Mono 6.2.0.107 is available on the preview channel.
Installed it and it builds, though VS Mac still complains about the new interpolated string syntax.

image

<details><summary>Versions</summary>
<p>

=== Visual Studio Enterprise 2019 for Mac (Preview) ===

Version 8.9 Preview (8.9 build 265)
Installation UUID: aeba313a-5361-41b8-a3a6-ca88a473acd9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.9.0-1.20507.6+4ed928935ce0e5db4327c168dfdad1c820a6a490

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.403

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.99.168 (Visual Studio Enterprise)
Commit: xamarin-android/master/71dc718
Android SDK: /Users/timothelariviere/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/master@ac914ce
ProGuard: Guardsquare/proguard/v7.0.0@84e8560
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@1878e43

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/timothelariviere/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.11
Hash: 6cd0123
Branch: remotes/origin/HEAD~1
Build date: 2020-10-13 20:43:56 UTC

=== Android Device Manager ===

Version: 16.9.0.8
Hash: 3f57870
Branch: remotes/origin/HEAD
Build date: 2020-10-13 20:45:38 UTC

=== Xamarin Designer ===

Version: 16.9.0.10
Hash: 13c439740
Branch: remotes/origin/fix-hotreload-signing
Build date: 2020-10-16 01:32:54 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 6.22.1.27 (Visual Studio Enterprise)
Hash: 86a329fa1
Branch: d16-8-xm
Build date: 2020-09-25 02:31:19-0400

=== Xamarin.iOS ===

Version: 14.7.0.166 (Visual Studio Enterprise)
Hash: d91932dcd
Branch: main
Build date: 2020-10-21 10:50:26-0400

=== Build Information ===

Release ID: 809000265
Git revision: 67bd2f44000a71ad9505ed487df7b1f4addd9f1d
Build date: 2020-11-05 12:42:55-05
Build branch: release-8.9
Xamarin extensions: 67bd2f44000a71ad9505ed487df7b1f4addd9f1d

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64



</p>
</details>

**Comment by KirillOsenkov** [comment]
Yes, now we need to also update the language service from FSharp.Compiler.Service 34.1.0 to 38.0.0. Unfortunately I doubt we can do this in a service release. But at least this gives you IDE support for features up to 34.1.0 which was 9 months ago.

**Comment by KirillOsenkov** [comment]
@cartermp FYI ^^

**Pull request merged**
