### PR TITLE
[tests] Fix p/invoke test on windows

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by alexrp** [comment]
Why is this needed?

**Comment by ludovic-henry** [comment]
@alexrp the catches are only for p/invoke related exceptions. So that's in case we fail to **call** the function `pthread_exit`. See also https://github.com/mono/mono/pull/3620#issuecomment-251048496

**Comment by alexrp** [comment]
Still, it's not clear to me why we would fail to call `ExitThread`. If we fail to call `pthread_exit`, surely we must be on Windows?

**Comment by ludovic-henry** [comment]
@alexrp yes, that's for the case we are on windows, we are not going to find `pthread_exit` in `libc.so`, so we are trying our luck with `ExitThread` in `kernel32.dll`

**Comment by akoeplinger** [comment]
Wouldn't the following be a lot easier?

```csharp
if (Environment.OSVersion.Platform == PlatformID.Win32NT)
    ExitThread (IntPtr.Zero);
else
    pthread_exit (IntPtr.Zero);
```

**Comment by ludovic-henry** [comment]
@akoeplinger it effectively looks better, but shouldn't we have the followind instead ?
```
if (Environment.OSVersion.Platform == PlatformID.Unix || Environment.OSVersion.Platform == MacOSX)
    pthread_exit (IntPtr.Zero);
else
    ExitThread (IntPtr.Zero);
```

**Pull request merged**
