### PR TITLE
Force Python 3.x from env in shebang lines

### PR DESCRIPTION
**Pull request by NattyNarwhal**
Extracted from #18284

### CODE REVIEW

**Comment by NattyNarwhal** [comment]
FWIW this is useful for FreeBSD  (so ports system can replace shebang lines, but it has to be consistent) per @rootwyrm

**Comment by CoffeeFlux** [comment]
Apparently RHEL6 is Py2.x and supported until Nov. @marek-safar once the build failures are fixed, is this safe to merge given the state of py2 support overall or do we have to hold off?

**Comment by marek-safar** [comment]
Switching to python3 is fine and actually desirable going forward

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
The webassembly failures are unrelated, merging.

**Comment by lewurm** [comment]
@monojenkins backport 2019-12

**Pull request merged**
