### PR TITLE
[runtime] Fix gshared support for BeginInvoke ()/EndInvoke () wrappers.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/14972.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
