### PR TITLE
[llvm] Fix the computation of size of gshared instances in another place.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/13610.

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by marek-safar** [comment]
@vargaz please backport manually

**Pull request merged**
