### PR TITLE
[System]: Fix major AppleTls memory leak.  Bug #56814.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by nberardi** [comment]
Wow you guys have made awesome progress, I only wish we could get this sooner into our production applications.  We are still stuck on Xamarin Studio because of it.  :(

**Comment by marek-safar** [comment]
@nberardi I am wondering why. You can use the latest XS with older versions of Xamarin SDKs

**Comment by nberardi** [comment]
@marek-safer it has to do with Mono Ceceil and Fody. The Mono Ceceil that runs in the latest Visual Studio Mac is incompatible with Xamarin 3.0.

**Comment by marek-safar** [comment]
@nberardi that is quite odd. Are you sure you are running latest Mono and latest Visual Studio for Mac. It'd be nice if you could fill a bug report if you can still reproduce it.

**Comment by nberardi** [comment]
@OneMHz do you have the error handy for @marek-satar?

**Comment by bocciab** [comment]
I think this is the one you're talking about:

```
	Target FodyTarget:
		  Fody: Fody (version 1.29.4.0) Executing
		  Fody: ProjectDirectory: '/.../'.
		  Fody: AssemblyPath: '/...dll'
		  Fody: Found path to weavers file '/.../FodyWeavers.xml'.
		  Fody: SolutionDirectory path is '/.../'
		  Fody: Finding weavers
		  Fody: Adding weaver dlls from '/.../Packages'.
		  Fody: Fody weaver file added '/.../Packages/NullGuard.Fody.1.4.6/NullGuard.Fody.dll'
		  Fody: Fody weaver file added '/.../Packages/NullGuard.Fody.1.5.2/NullGuard.Fody.dll'
		  Fody: Could not find packages dir from nuget config.
		  Fody: SolutionDirectoryPath: /.../
		  Fody: Adding weaver dlls from '/.../packages'.
		  Fody: Fody weaver file added '/.../packages/NullGuard.Fody.1.4.6/NullGuard.Fody.dll'
		  Fody: Fody weaver file added '/.../packages/NullGuard.Fody.1.5.2/NullGuard.Fody.dll'
		  Fody: SolutionDirectoryPath: /Users/bocciab/CloudDriveDesktop/
		  Fody: Adding weaver dlls from '/.../Tools'.
		  Fody: No Weaver project file found.
		  Fody: Finished finding weavers 198ms
		  Fody: Creating a new AppDomain
		  Fody: Reference count=79
		  Fody: Found debug symbols at '/....pdb'.
		  Fody: Found debug symbols at '/....dll.mdb'.
		  Fody: Found mdb and pdb debug symbols. Selected mdb (newer).
		  Fody: Weaver '/.../Packages/NullGuard.Fody.1.5.2/NullGuard.Fody.dll'.
		  Fody:   Initializing weaver
		  Fody:   Loading '/.../Packages/NullGuard.Fody.1.5.2/NullGuard.Fody.dll' from disk.
		    Fody/NullGuard:   Executing Weaver 
: error : Fody: An unhandled exception occurred:
Exception:
Could not resolve field token 0x0400000f
StackTrace:
  at ModuleWeaver.Execute () [0x0002d] in <57b1506e52bb45b995ad0cacc558e4d3>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
  at InnerWeaver.ExecuteWeavers () [0x00087] in <f6f9069078364b4db60945017a527c4a>:0 
  at InnerWeaver.Execute () [0x00030] in <f6f9069078364b4db60945017a527c4a>:0 
Source:
NullGuard.Fody
TargetSite:
Void Execute()

		  Fody:   Finished Fody 776ms.
	Task "Fody.WeavingTask" execution -- FAILED
	Done building target "FodyTarget" in project "/....csproj".-- FAILED

```

**Comment by baulig** [comment]
2017-08 backport: https://github.com/mono/mono/pull/5375

**Comment by baulig** [comment]
2017-06 backport: https://github.com/mono/mono/pull/5376

**Comment by baulig** [comment]
2017-04 backport: https://github.com/mono/mono/pull/5377

**Pull request merged**
