### PR TITLE
Delete monograph. Closes https://github.com/mono/mono/issues/7845

### PR DESCRIPTION
**Pull request by directhex**
As requested, remove monograph.

From the relevant Github Issue:

> monograph (https://github.com/mono/mono/tree/master/tools/monograph) is a utility that dumps a callgraph or type hierarchy information from a given assembly (in graphviz dot format).

> I'm not sure who this is useful for, but this seems like a tool that ought to be built on top of IKVM or Cecil and not by embedding Mono.

> We ship it, but it hasn't worked for a while because we never test it.

Definitely warrants a .msi build before merging, I'm not 100% confident `nano` is a good .sln editor

### CODE REVIEW

**Comment by kg** [comment]
For the record can you briefly describe monograph in the PR so it shows up in the commit comment?

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build msi

**Comment by akoeplinger** [comment]
@monojenkins build pkg and msi

**Pull request merged**
