### PR TITLE
[reflection] Grab bag of MonoError commits

### PR DESCRIPTION
**Pull request by lambdageek**
Depends on #2555

### CODE REVIEW

**Comment by kumpera** [comment]
My object.c comments on invoke are wrong after we figured out the complicated behavior we need.

The only issue that really needs to be addressed is the debugger, which is expected to deal with broken stuff.

**Comment by lambdageek** [comment]
@kumpera Thanks for the detailed review!

What's the right `ErrorCode` for the debugger `get_assembly_object_checked` thing? `ERR_INVALID_OBJECT`?

**Comment by kumpera** [comment]
Hmm, either that or ERR_LOADER_ERROR. We can't bubble the correct one for now, so let's go with ERR_INVALID_OBJECT

**Comment by lambdageek** [comment]
Sounds good.  Did that in 61803ca.  The appdomain unloading fix is in 407b2d3, cleanup of MonoError after try_invoke is in  b8958da and the formatting issues were fixed up when I updated the PR.  I think that's everything.

@monojenkins  merge

**Pull request merged**
