### PR TITLE
Add missing System.Net.EncryptionPolicy enum and SslStream constructor

### PR DESCRIPTION
**Pull request by mythz**
Add implementation of the [missing SslStream constructor](http://msdn.microsoft.com/en-us/library/dd990420(v=vs.110).aspx), e.g:

```csharp
sslStream = new SslStream(networkStream,
    leaveInnerStreamOpen: false,
    userCertificateValidationCallback: null,
    userCertificateSelectionCallback: null,
    encryptionPolicy: EncryptionPolicy.RequireEncryption);
```

which currently fails to build on Mono or run (when built with .NET) with:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.Net.Security.EncryptionPolicy' from assembly 'System.dll, Version=4.0.0.0
```

Currently I'm resorting to this hack to support both .NET and Mono: 

```csharp
if (Env.IsMono)
{
    //Mono doesn't support EncryptionPolicy
    sslStream = new SslStream(networkStream,
        leaveInnerStreamOpen: false,
        userCertificateValidationCallback: CertificateValidationCallback,
        userCertificateSelectionCallback: CertificateSelectionCallback); 
}
else
{
    var ctor = typeof(SslStream).GetConstructors()
        .First(x => x.GetParameters().Length == 5);

    var policyType = AssemblyUtils.FindType("System.Net.Security.EncryptionPolicy");
    var policyValue = Enum.Parse(policyType, "RequireEncryption");

    sslStream = (SslStream)ctor.Invoke(new [] {
            networkStream,
            false,
            CertificateValidationCallback,
            CertificateSelectionCallback,
            policyValue,
        });
}
```

Which I prefer to avoid since the most common path in .NET has to resort to reflection in order to get it running in Mono as well.

## TODO Verify behavior

Currently the default constructor impl only allows `EncryptionPolicy.AllowNoEncryption`, e.g:

```csharp
if (encryptionPolicy != EncryptionPolicy.AllowNoEncryption)
    throw new NotImplementedException();
```

But depending on the behavior of `SslStream` it may also be able to support `EncryptionPolicy. RequireEncryption`, hopefully someone familiar with this will know.

### CODE REVIEW

**Comment by directhex** [comment]
build

**Comment by jpasichnyk** [comment]
I just wanted to check the status of this, and it looks like the merge issues above show a 404. It's been a month since last activity, anything specific blocking this from getting merged that needs attention?

**Comment by alexrp** [comment]
build

**Comment by migueldeicaza** [comment]
I rather not add a constructor that is semi-working, we should add the actual meat to the code and file a bug to get this implemented.

**Comment by baulig** [comment]
This file has been completely reworked in the meantime, so we don't need this anymore.

**Pull request closed without merging**
