### PR TITLE
[Coop] Convert System.Buffer.

### PR DESCRIPTION
**Pull request by jaykrell**
And inline `mono_array_handle_length`.
And remove `inline` in .c files a little -- it only belongs in .h.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build fialed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
