### PR TITLE
Add volatile for cross thread communication in test bug-10127.cs.

### PR DESCRIPTION
**Pull request by jaykrell**
This test is flaky. Maybe this helps. Otherwise I'll dig in later.

### CODE REVIEW

**Comment by jaykrell** [comment]
Could also reduce lock hold times.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Maybe it was Jenkins going down?
Maybe this is a good change anyway?

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
The Windows x64 c++ lane started to fail after this:
https://jenkins.mono-project.com/job/e/

**Comment by jaykrell** [comment]
https://github.com/mono/mono/pull/18731 ?

**Comment by akoeplinger** [comment]
According to Jenkins (https://jenkins.mono-project.com/job/e/label=w64/) the first build with the issue is https://jenkins.mono-project.com/job/e/label=w64/933/, but it can't be the NUnitlite bump (we don't use nunitlite for runtime tests)

**Pull request merged**
