### PR TITLE
[tests] Re-enable bug-45841-fpstack-exceptions.exe

### PR DESCRIPTION
**Pull request by vkargov**
Works on master.

### CODE REVIEW

**Comment by vargaz** [comment]
Did this really got fixed ? Wasn't the original failure random ?

**Comment by akoeplinger** [comment]
> Did this really got fixed ? Wasn't the original failure random ?

It failed in the PR build so I assume this isn't fixed: https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-osx/3513/testReport/junit/MonoTests/runtime/bug_45841_fpstack_exceptions_exe/

**Comment by luhenry** [comment]
It isn't actually fixed on master since it's still failing.

**Comment by vkargov** [comment]
You're right, there was an issue with the IL code of the test passing incorrect arguments to an exception. I'm including a fix for the test and am reopening the PR.

**Pull request merged**
