### PR TITLE
[wasm] Disable interpreter optimizations when debugging.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
This is needed to disable optimizations which interfere with debugging i.e. inlining, dead code elimination etc.

**Comment by lewing** [comment]
@monojenkins build Linux WebAssembly

**Comment by vargaz** [comment]
The failures are related, will investigate.

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Pull request merged**
