### PR TITLE
Import System.Xaml from dotnet/wpf

### PR DESCRIPTION
**Pull request by EgorBo**
Just an attempt (out of curiosity) to import `System.Xaml` from WPF ([dotnet/wpf](https://github.com/dotnet/wpf))

### CODE REVIEW

**Comment by atsushieno** [comment]
The API diff looks almost harmless (surprisingly? even with -d:SILVERLIGHT_XAML).

**Comment by steveisok** [comment]
@EgorBo still want to do this?

**Comment by steveisok** [comment]
Since this is older, I'm closing.  Please see the [old pull request policy](https://github.com/mono/mono/wiki/Pull-Request-Guide#old-pull-request-policy) for more info.

**Comment by atsushieno** [comment]
Is anyone working for the same achievement? If anyone wants to, what was the reason why it was not merged? @steveisok

**Pull request closed without merging**
