### PR TITLE
Save and resume full 128-bits of xmm argument registers in trampoline…

### PR DESCRIPTION
**Pull request by joncham**
…. Add definition of MonoContextSimdReg on amd64 for Windows platform and use for size/offset calculations.

### CODE REVIEW

**Comment by joncham** [comment]
Bump. Also, I can't tell if any failures are due to my changes or if they are okay.

**Comment by vargaz** [comment]
build

**Comment by akoeplinger** [comment]
this seems to break the build on Alpine Linux:

```
tramp-amd64.c: In function 'mono_arch_create_generic_trampoline':
tramp-amd64.c:365:81: error: 'MonoContextSimdReg' undeclared (first use in this function)
    amd64_movdqu_membase_reg (code, AMD64_RBP, saved_fpregs_offset + (i * sizeof(MonoContextSimdReg)), i);
```

**Comment by joncham** [comment]
I will try to fix. Is there no public CI of Alpine Linux @akoeplinger ?

**Comment by akoeplinger** [comment]
@joncham not on PRs since it's not 100% green and not a main focus, but we're testing it nightly here: https://jenkins.mono-project.com/job/test-mono-mainline-docker/label=docker-alpine/

**Comment by akoeplinger** [comment]
@joncham any update on fixing the Alpine build break?

**Comment by joncham** [comment]
@akoeplinger see https://github.com/mono/mono/pull/6007

**Pull request merged**
