### PR TITLE
[debugger][exception] Debugger breaks on handled exceptions

### LINKED ISSUE #17083: Regression: when debugger encounters a not-unhandled exception, it stops and shows "Dns.cs file not found" (Dns being the BCL class used)
I believe this is a regression because I haven't seen this behaviour in previous versions of VisualStudio for Mac (now using 8.2.4; not sure the exact version when this started happening, possibly when Mono 6.0 was bundled).

Steps to reproduce:
1. Open VS4Mac, create new project/solution, Console type, language: C#.
2. Use this simple snippet:

```
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Threading.Tasks;

namespace TestResolveCSharpConsole
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            try
            {
                var results = ResolveAsync().GetAwaiter().GetResult();
            }
            catch (SocketException sockEx)
            {
                Console.WriteLine("correctly handled");
            }
        }

        public static async Task<List<string>> ResolveAsync()
        {
            var addresses = await System.Net.Dns.GetHostAddressesAsync("foo.bar.baz");
            return new List<string>(addresses.Select(addr => addr.ToString()));
        }
    }
}
```

3. Compile it. (If you run it outside VS4Mac, result should just be the printing of the string "correctly handled".)
4. Run it with the debugger inside VS4Mac.

Expected results:
Should just run it and not stop, finish execution at the end like it's the case when being run outside of VS4Mac.

Current results:
Debugger seems to bomb when a `SocketException` is thrown, even if it's properly handled with a try-catch (this is the first bug). Then it tries to open the source code of the BCL where this exception happened (Dns.cs), telling the weird error "Source Not Found" to the user.

See screenshot:
Screenshot 2019-08-28 at 3 56 16 PM

> VS bug [#973786](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/973786), VS bug [#989287](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/989287)

### PR DESCRIPTION
**Pull request by thaystg**
If there is a perform_wait_callback in the stack there will be another catch generated by the method called in the owner thread, so we don't need to throw as unhandled exception, we can continue and find the next catch.

Fixes #17083

### CODE REVIEW

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build OS X x64

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monjenkins build Linux ARMv5

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-08

**Comment by vargaz** [comment]
Is perform_wait_callback a special method so it needs to be special cased in the runtime ?

**Comment by lambdageek** [comment]
@vargaz `PerformWaitCallback` is a little bit special to the runtime.  The threadpool code sets `save_lmf` to TRUE because the worker loop wants to mess with the exception handling.

https://github.com/mono/mono/blob/7f37f76b6d75ed6236f6f33958784180e6f20446/mono/metadata/threadpool.c#L326-L330

**Comment by vargaz** [comment]
I guess this is ok then but it still looks kinda weird.

**Comment by knocte** [comment]
I don't want to delay this fix to be committed (in fact I was the bug reporter), but hardcoding threadpool_perform_wait_callback_method in this bug fix would mean that the bug would still be present when the thread is not a threadpool thread?

**Comment by thaystg** [comment]
It's a side effect of #15234. We should backport to 2019-06 and 2019-02.

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-06

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-08

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
Relevant failures: x64 and arm64 FullAOT+Interpreter lanes consistently failing the abort-cctor test.  Also on the 2019-08 backport.

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins backport 2019-08

**Comment by thaystg** [comment]
@monojenkins backport 2019-06

**Comment by thaystg** [comment]
@monojenkins backport 2019-02

**Pull request merged**
