### PR TITLE
[runtime] Changed the constant backoff for sgen's finalizer hash table to an increasing backoff to avoid livelock.

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexrp** [comment]
Can you rebase this on master so we get more thorough test coverage? (since #1826 is now merged)

**Comment by vargaz** [comment]
Shouldn't there be a limit on the backoff value ?

**Comment by evincarofautumn** [comment]
Strictly speaking, backoff algorithms should be randomized to avoid repeated contention. I’m not sure how much it matters here. You might also benchmark the difference between linear and exponential backoff.

**Comment by alexanderkyte** [comment]
I went with a randomized exponential backoff with a time limit as per the suggestions of @evincarofautumn and @vargaz.

**Comment by lewurm** [comment]
@alexanderkyte can you rebase your changes?

**Pull request closed without merging**
