### PR TITLE
[arm/ios] workaround for faulty vcmp.f64 insn

### PR DESCRIPTION
**Pull request by lewurm**
Fixes https://github.com/mono/mono/issues/11965

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@lewurm this will still need managed side fix as well, right?

**Comment by lewurm** [comment]
@marek-safar yes, https://github.com/mono/corert/pull/30

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins backport 2018-08

**Pull request merged**
