### PR TITLE
This list is almost sorted -- so repair the sorting and add comment.

### PR DESCRIPTION
**Pull request by jaykrell**
This list is almost sorted -- so repair the sorting and add comment.

### CODE REVIEW

**Comment by jaykrell** [comment]
build

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv5 soft float

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Acceptance Tests

**Comment by luhenry** [comment]
@monojenkins build Windows x64

**Pull request merged**
