### PR TITLE
[runtime] Fix locking in mono_get_seq_points ().

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/17737.

### CODE REVIEW

**Comment by lambdageek** [comment]
Probably #17545 is also related

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins backport 2019-10

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-08

**Pull request merged**
