### PR TITLE
[wasm] Compile the wasm runtime using optimization.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
https://github.com/mono/mono/blob/2f794e00b7e7c264488f624b788090e7b3e899bd/sdks/builds/wasm.mk#L62

I assume that `CFLAGs=-Os -g` gets overridden by the latter?  If so, we should remove that one here.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
Will fix that.

**Pull request merged**
