### PR TITLE
Fix assertion in mono_gchandle_get_target.

### PR DESCRIPTION
**Pull request by evincarofautumn**
Haven’t been able to test with XS yet, but this should work.

### CODE REVIEW

**Comment by schani** [comment]
I don't like this.  If we get random GC handles and that's a bug in the GC handle implementation, we need to find that bug and fix it.  If the bug is somewhere else then there's the danger that the random GC handle will actually be valid, in which case we will return an object the caller doesn't expect.  That's also a bug we need to find and fix.

**Comment by kumpera** [comment]
The issue is that there's code in the wild that uses -1 as an invalid handle and assumes that mono_gc_handle_get_target with -1 will return null.

I'm fine with the idea of fixing upstream assuming that there are any bugs in there and not just the -1 behavior.

If would be easier to tell whether the value is just or -1 if g_error was used instead of g_assert.

The former actually helps us troubleshoot field issues, the later just make us look bad.

**Comment by schani** [comment]
Supporting `-1` as a special case is reasonable.

**Comment by kumpera** [comment]
Important thing, I found the -1 thing by sheer luck while git grepping maccore.

**Pull request merged**
