### PR TITLE
[exceptions] introduce suspend-on-native-crash

### PR DESCRIPTION
**Pull request by lewurm**
/cc @BrzVlad @vargaz @ludovic-henry

### CODE REVIEW

**Comment by vargaz** [comment]
Can't we use the existing option ?

**Comment by lewurm** [comment]
we could, but it's kinda misleading because it can also be caused by `SIGILL`, `SIGFPE`, etc.

**Comment by vargaz** [comment]
Its for internal runtime development.

**Comment by lewurm** [comment]
so it can be confusing? 😄  how about removing `suspend-on-sigsegv`?

**Comment by evincarofautumn** [comment]
Could just make the existing option a little more general. E.g., `suspend-on=sigsegv`, `suspend-on=crash`

**Comment by lewurm** [comment]
There is not much value in that imho.  Initially I hesitated to rename/remove `suspend-on-suspend` because it's a known flag for debugging runtime issues, but thinking more about it should be either removed or just do the same as `suspend-on-native-crash`.

**Comment by vargaz** [comment]
Make the two options do the same, and keep the old one as an alias of the new one, or vice versa.

**Pull request merged**
