### PR TITLE
[runtime] Sequential consistency atomics

### PR DESCRIPTION
**Pull request by alexrp**
This is kind of an RFC. I've discussed atomics with @kumpera on multiple occasions and both of us think the world would be a simpler place if runtime code only had to worry about sequential consistency (instead of acquire/release semantics, and load/store barriers).

To that end, this PR moves `mono_memory_barrier` to `atomic.h` and removes `mono-membar.h`. It also removes `mono-memory-model.h` and replaces all uses of that header's macros with functions in `atomic.h`.

What does everyone think about this?

### CODE REVIEW

**Comment by evincarofautumn** [comment]
I guess the question here is whether the benefit of simplicity is worth the cost of always issuing memory fences when only a load or store fence is required. At the very least I would like to see some performance stats.

**Comment by alexrp** [comment]
As far as the functions in `mono-membar.h` go, there will be no perf difference. They always issued full barriers anyway.

If you look at the uses of `mono_atomic_load_acquire` and `mono_atomic_store_release`, you'll see that most are in code paths where this kind of micro-optimization doesn't actually matter.

**Comment by alexrp** [comment]
build

**Comment by kumpera** [comment]
I'm not sure about the perf argument on mono_atomic_load_acquire / mono_atomic_store_release.
Like, not sure if it's true or not.

I'm not a big fan of the windows style, so I'm not sold on killing the acq/release ones.

Killing the read/write membar functions is a good idea as they don't tell what is the actual
constraint that it enforces. And the straightforward understanding don't actually maps well
to most HW.

Let's examine mono_memory_load_barrier. What does it mean? That no loads can be reordered
over it? Or just the ones after? Or just the ones before?

On x86 it requires a full memory fence as a load happening after could reorder with a previous store. Same thing on ARM, which has a weak model. Eg:

int x = bar;
mono_memory_load_barrier ();
foo = bar;


OTOH, had we used acquire/release/sequential load/stores, which are easier to reason about
that fencing, we could generate more hardware optimized fences. Eg:

int x = mono_atomics_load_acquire (&bar);
foo = x;

load_acquire requires no fencing on x86 and on armv8 it has hardware support.

**Comment by alexrp** [comment]
Perhaps we should consider scrapping `atomic.h`/`atomic.c` entirely and making a new interface around the modern GCC atomics: https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html

The problem (as usual) is MSVC: It doesn't have meaningful atomic builtins for all of these. Hell, even in today's `atomic.h` we have to hand-write some of the `Interlocked*` functions around x86 semantics, which is horrible.

**Pull request closed without merging**
