### PR TITLE
Fix comparison of IntPtr with null in Mono

### PR DESCRIPTION
**Pull request by EgorBo**
See https://github.com/dotnet/corefx/pull/31457

### CODE REVIEW

**Comment by danmosemsft** [comment]
Does it make sense to enable Roslyn strict mode for Mono?

**Comment by akoeplinger** [comment]
@EgorBo could you send a PR which enables /strict to see if we get failures?

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-06

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-04

**Comment by akoeplinger** [comment]
@EgorBo could you please do the manual backport, thanks 😄

**Pull request merged**
