### PR TITLE
[ci] Enable llvmonly+mixed tests on CI.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by marek-safar** [comment]
@akoeplinger could you chime in

**Comment by marek-safar** [comment]
Ignore that. I pushed it for other PR before merging

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
This is currently only enabled for osx+llvm, but there is no PR lane which uses that.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
