### PR TITLE
Show thumbnail images in SWF.(Open,Save)FileDialog

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=28025.

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
The CLA process returns a processing error every time I try to submit the form.  If you make it impossible for people to sign the CLA, you shouldn't complain they haven't done so!  I've tried at least 5 or 6 times, so it's not just a one time misreading of the CAPTA nonsense.

**Comment by akoeplinger** [comment]
@StephenMcConnel I think the CLA bot is still experimental, it showed up a few days ago

Can someone from Xamarin shed some light onto this new bot?

**Comment by drasticactions** [comment]
@StephenMcConnel We have had issues for the past few days with Docusign's API for creating envelopes (As in, it would either throw errors or timeout on their end), hence the error. I realize now I could have better exposed that to you rather than you thinking it was the recaptcha ;).

It should now be working. Sorry for any inconvenience.

**Comment by akoeplinger** [comment]
@drasticactions I think the link to the CLA website is wrong, it points to `https://xamarin-cla.azurewebsites.net/`, but when I login there I get an error and notice that I'm at `https://cla.xamarin.com`.

**Comment by drasticactions** [comment]
@akoeplinger You're right, I did forget to change that. It should be https://cla.xamarin.com/. I have now fixed it.

**Comment by StephenMcConnel** [comment]
OK, I think I've gotten registered for the CLA now.

**Comment by knocte** [comment]
Is the CLA Bot smart enough to only act when dealing with a non-MIT codebase?

**Comment by ermshiperete** [comment]
:+1:

**Pull request merged**
