### PR TITLE
Fix timestamp for file copy

### PR DESCRIPTION
**Pull request by lewurm**
4a8d840 introduced that the destination
file of a copy operation has the same modification and access timestamps
as the source file.

With e0e185d this behaviour regresses,
since getting timestamps provides more precise information. Fixing this
by being more accurate when applying timestamps to destination file.

also: convert nano seconds to microseconds properly, by using `TICKS_PER_MILLISECOND` (which has L suffix in its definition)

fixes https://github.com/xamarin/xamarin-macios/issues/3929

needs backporting to `2018-02` and `2018-04`

### CODE REVIEW

**Comment by luhenry** [comment]
For some reasons, this seem to break `FileTest.TestGetCreationTime` on `Linux i386 Coop GC` and `Linux ARMv7 Interpreter`. This might just make the test more flaky and just happen to reproduce on these configurations by accident. Could you please investigate why this test is failing? Thank you

**Comment by lewurm** [comment]
@monojenkins build Linux i386

**Comment by lewurm** [comment]
@monojenkins build OS X i386

**Comment by lewurm** [comment]
potentially 32bit related, gonna look into it

**Comment by lewurm** [comment]
looks like this introduced a regression:
https://jenkins.mono-project.com/job/test-mono-interpreter/1703/label=debian-9-arm64/parsed_console/log.html
```
1) LastWriteTimeSubMs (MonoTests.System.IO.FileTest.LastWriteTimeSubMs)
     Iteration #6 failed, untouched: 22:53:08:4620000 touched: 22:36:37:0850000
  Expected: True
  But was:  False
```
https://jenkins.mono-project.com/job/test-mono-interpreter/1702/label=debian-9-arm64/parsed_console/log.html
```
1) LastWriteTimeSubMs (MonoTests.System.IO.FileTest.LastWriteTimeSubMs)
     Iteration #163 failed, untouched: 22:18:52:9380000 touched: 22:02:29:2100000
  Expected: True
  But was:  False
```
https://jenkins.mono-project.com/job/test-mono-interpreter/1702/label=debian-9-armhf/parsed_console/log.html
```
1) LastWriteTimeSubMs (MonoTests.System.IO.FileTest.LastWriteTimeSubMs)
     Iteration #163 failed, untouched: 22:25:43:9170000 touched: 22:09:08:3450000
  Expected: True
  But was:  False
```

https://jenkins.mono-project.com/job/test-mono-mainline-linux/4348/label=debian-9-armhf/parsed_console/log.html
```
1) LastWriteTimeSubMs (MonoTests.System.IO.FileTest.LastWriteTimeSubMs)
     Iteration #197 failed, untouched: 15:36:50:0250000 touched: 15:20:15:1720000
  Expected: True
  But was:  False
```

**Comment by akoeplinger** [comment]
@lewurm I wouldn't call it a regression since this is a new test introduced with the PR, so it depends on what the behavior before the change was :)

Since it happens at random iterations it points to some sort of flakiness, can you take a look?

**Comment by lewurm** [comment]
this PR introduced a different test. I'm looking into it

**Pull request merged**
