### PR TITLE
WCF process PATCH verb

### LINKED ISSUE #20611: WCF rejects PATCH http verb
I am implementing a Restful API using a WCF bind. However, in mono, the verb PATCH is not being processed.

### PR DESCRIPTION
**Pull request by digocesar**
- Add PATCH verb to be processed in WCF request.
- Validate if ContentType is present. WCF was simply not responding if ContentType is not reported.

Fixes #20611

### CODE REVIEW

**Comment by digocesar** [comment]
Any update about accepting this pull request?

**Review by steveisok — APPROVED** [review]

**Comment by digocesar** [comment]
I don't know so much about github merge process. But there is something pending to this request be accepted?

**Comment by digocesar** [comment]
@akoeplinger Is this Pull Request waiting for your review?

**Comment by digocesar** [comment]
Any update?

**Comment by steveisok** [comment]
@digocesar Can you rebase against master and push?  We altered our CI and I'd like to make sure it's all good

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/mono?pullRequest=20612) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/mono?pullRequest=20612) before we can accept your contribution.<br/><br/>:x: digocesar [sign now](https://cla.dotnetfoundation.org/mono/mono?pullRequest=20612)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/mono?pullRequest=20612) it.</sub>

**Comment by kg** [comment]
Hi, we still need this PR to be rebased against main, we can't merge it with this many commits in it.

**Comment by digocesar** [comment]
> Hi, we still need this PR to be rebased against master, we can't merge it with this many commits in it.

Ok, now I think that it is rebased.

**Review by vargaz — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by digocesar** [comment]
In which version of Mono was this fix released?

**Pull request merged**
