### PR TITLE
[xbuild] Only execute PCL target "ImplicitlyExpandTargetFramework" when corresponding property is true

### PR DESCRIPTION
**Pull request by akoeplinger**
This aligns xbuild with the MS.NET behavior.

/cc @mhutch

### CODE REVIEW

**Comment by directhex** [comment]
build

**Comment by migueldeicaza** [comment]
Comment: this patch is part of a set of patches to build CoreFX with Mono on Unix.

**Comment by kumpera** [comment]
Who can review this? I believe @mhutch or @baulig?

**Comment by mhutch** [comment]
Looks okay to me, though I can't easily test it.

**Comment by baulig** [comment]
Looks good to me.

**Pull request merged**
