### PR TITLE
Fix hashing of strings.

### PR DESCRIPTION
**Pull request by jaykrell**
Something is wrong here but not clear exactly what.
The code does not do what is intended.

### CODE REVIEW

**Comment by lambdageek** [comment]
I don't think the description is correct.  `g_str_hash ("") == 0`, always.

But it's also true that `g_str_hash (s) == 0` for every length 1 string `s`, which is not great.

**Comment by jaykrell** [comment]
Something is amiss here, as the fix breaks things.
Elsewhere the fix fixed things.
And while the fix makes sense as to the intend of the code and reading it locally, it doesn't make sense that it would have these impacts.
More debugging needed.

**Comment by jaykrell** [comment]
`mono_metadata_str_hash` looks much better, doesn't it?
I mean, that would also fix `g_str_hash`?
I'll debug more.

This looks suspicious for example:

```
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = breakpoint 2.2 3.2
    frame #0: 0x00000001002f2044 mono`rehash [inlined] do_rehash(hash=0x000000010100cbd0) at ghashtable.c:196 [opt]
    frame #1: 0x00000001002f2044 mono`rehash(hash=0x000000010100cbd0) at ghashtable.c:227 [opt]
    frame #2: 0x00000001002f1f1d mono`monoeg_g_hash_table_insert_replace(hash=0x000000010100cbd0, key=0x00000001003420f4, value=0x000000010070b290, replace=0) at ghashtable.c:243 [opt]
  * frame #3: 0x00000001001bef93 mono`mono_register_jit_icall_full(func=0x0000000100229200, name="mono_profiler_raise_gc_allocation", sig=<unavailable>, avoid_wrapper=<unavailable>, c_symbol=0x0000000000000000) at icall.c:8730 [opt]
    frame #4: 0x0000000100285a84 mono`mono_gc_get_managed_allocator_by_type [inlined] create_allocator(atype=<unavailable>, variant=<unavailable>) at sgen-mono.c:1012 [opt]
    frame #5: 0x00000001002859de mono`mono_gc_get_managed_allocator_by_type(atype=2, variant=MANAGED_ALLOCATOR_REGULAR) at sgen-mono.c:1144 [opt]
    frame #6: 0x000000010009ff4d mono`decode_method_ref_with_target(module=0x0000000101801200, ref=0x00007ffeefbfe260, target=<unavailable>, buf=<unavailable>, endbuf=<unavailable>, error=0x00007ffeefbfe1f8) at aot-runtime.c:990 [opt]
    frame #7: 0x000000010009b30d mono`decode_patch [inlined] decode_method_ref(module=<unavailable>, ref=0x0000000000000000, buf=<unavailable>, endbuf=0x00000001056804d8, error=0x0000000100000000) at aot-runtime.c:1401 [opt]
    frame #8: 0x000000010009b300 mono`decode_patch(aot_module=<unavailable>, mp=0x000000010080da00, ji=0x00007ffeefbfe2e8, buf="??, endbuf=0x00007ffeefbfe310) at aot-runtime.c:3704 [opt]
    frame #9: 0x000000010009b193 mono`mono_aot_plt_resolve(aot_module=0x0000000101801200, plt_info_offset=<unavailable>, code="H\x8b?I\x8b\x05?G?, error=0x00007ffeefbfe358) at aot-runtime.c:5081 [opt]
    frame #10: 0x00000001000b47e4 mono`mono_aot_plt_trampoline(regs=<unavailable>, code="H\x8b?I\x8b\x05?G?, aot_module=<unavailable>, tramp=<unavailable>) at mini-trampolines.c:1097 [opt]
    frame #11: 0x00000001054f952a mscorlib.dll.dylib`generic_trampoline_aot_plt + 378
    frame #12: 0x0000000104d21a49 mscorlib.dll.dylib`System_Exception__cctor + 41
    frame #13: 0x0000000105482992 mscorlib.dll.dylib`wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 290
    frame #14: 0x0000000100011368 mono`mono_jit_runtime_invoke(method=<unavailable>, obj=<unavailable>, params=0x0000000000000000, exc=0x0000000000000000, error=<unavailable>) at mini-runtime.c:3188 [opt]
    frame #15: 0x0000000100212f74 mono`mono_runtime_try_invoke [inlined] do_runtime_invoke(method=<unavailable>, obj=<unavailable>, params=<unavailable>, exc=<unavailable>, error=<unavailable>) at object.c:2977 [opt]
    frame #16: 0x0000000100212f39 mono`mono_runtime_try_invoke(method=0x0000000100809770, obj=0x0000000000000000, params=0x0000000000000000, exc=0x00007ffeefbfe8f0, error=0x00007ffeefbfea68) at object.c:3086 [opt]
    frame #17: 0x0000000100211c6f mono`mono_runtime_class_init_full(vtable=0x00000001040025c0, error=0x00007ffeefbfea68) at object.c:522 [opt]
    frame #18: 0x000000010000c829 mono`mono_jit_compile_method_with_opt(method=0x0000000100809748, opt=374434303, jit_only=0, error=0x00007ffeefbfea68) at mini-runtime.c:2435 [opt]
    frame #19: 0x00000001000b417e mono`common_call_trampoline(regs=<unavailable>, code="H\x8b\x04$?@`\x01\x15\x13\x80H\x83\U00000098ÐH\x83?H\x89<$H\x89t$\bH\x89T$\x10I\x8b\x05G\x90?", m=0x0000000100809748, vt=0x0000000000000000, vtable_slot=<unavailable>, error=0x00007ffeefbfea68) at mini-trampolines.c:751 [opt]
    frame #20: 0x00000001000b3c49 mono`mono_magic_trampoline(regs=0x00007ffeefbfeb38, code="H\x8b\x04$?@`\x01\x15\x13\x80H\x83\U00000098ÐH\x83?H\x89<$H\x89t$\bH\x89T$\x10I\x8b\x05G\x90?", arg=0x0000000100809748, tramp=<unavailable>) at mini-trampolines.c:891 [opt]
    frame #21: 0x00000001054f8c2a mscorlib.dll.dylib`generic_trampoline_jit + 378
    frame #22: 0x0000000104cda27f mscorlib.dll.dylib`System_SystemException__ctor_string + 47
    frame #23: 0x0000000104d054af mscorlib.dll.dylib`System_OutOfMemoryException__ctor_string + 47
    frame #24: 0x0000000105482992 mscorlib.dll.dylib`wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 290
    frame #25: 0x0000000100011368 mono`mono_jit_runtime_invoke(method=<unavailable>, obj=<unavailable>, params=0x00007ffeefbff090, exc=0x0000000000000000, error=<unavailable>) at mini-runtime.c:3188 [opt]
    frame #26: 0x00000001002114c8 mono`mono_runtime_invoke_checked [inlined] do_runtime_invoke(method=0x0000000100808f28, obj=0x0000000102800048, params=0x00007ffeefbff090, exc=<unavailable>, error=0x00007ffeefbff150) at object.c:2977 [opt]
    frame #27: 0x0000000100211492 mono`mono_runtime_invoke_checked(method=0x0000000100808f28, obj=0x0000000102800048, params=0x00007ffeefbff090, error=0x00007ffeefbff150) at object.c:3145 [opt]
    frame #28: 0x0000000100211555 mono`mono_runtime_invoke_handle(method=<unavailable>, obj=<unavailable>, params=<unavailable>, error=<unavailable>) at object.c:3151 [opt]
    frame #29: 0x00000001001abd8c mono`create_exception_two_strings(klass=0x0000000102006108, a1=MonoStringHandle @ 0x00007ffeefbff068, a2=MonoStringHandle @ 0x00007ffeefbff080, error=0x00007ffeefbff150) at exception.c:204 [opt]
    frame #30: 0x00000001001abbd5 mono`mono_exception_from_name_two_strings_checked(image=<unavailable>, name_space=<unavailable>, name=<unavailable>, a1=<unavailable>, a2=<unavailable>, error=0x00007ffeefbff150) at exception.c:264 [opt]
    frame #31: 0x000000010017fdc4 mono`create_domain_objects(domain=0x0000000101500860) at appdomain.c:219 [opt]
    frame #32: 0x000000010017f336 mono`mono_runtime_init_checked(domain=0x0000000101500860, start_cb=<unavailable>, attach_cb=<unavailable>, error=0x00007ffeefbff268) at appdomain.c:319 [opt]
    frame #33: 0x0000000100010af9 mono`mini_init(filename=<unavailable>, runtime_version=<unavailable>) at mini-runtime.c:4586 [opt]
    frame #34: 0x0000000100071f79 mono`mono_main(argc=10, argv=<unavailable>) at driver.c:2447 [opt]
    frame #35: 0x0000000100000d0a mono`main [inlined] mono_main_with_options(argc=<unavailable>, argv=<unavailable>) at main.c:50 [opt]
    frame #36: 0x0000000100000cf6 mono`main(argc=10, argv=<unavailable>) at main.c:406 [opt]
    frame #37: 0x00007fff50315015 libdyld.dylib`start + 1
(ll
```

Racy?
Do the registration earlier?

**Comment by jaykrell** [comment]
This should be done earlier instead of on-demand right?
It looks kinda racy, but is pretty early anyway.

```
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
  * frame #0: 0x00000001002f2034 mono`rehash [inlined] do_rehash(hash=0x0000000101504a90) at ghashtable.c:196 [opt]
    frame #1: 0x00000001002f2034 mono`rehash(hash=0x0000000101504a90) at ghashtable.c:227 [opt]
    frame #2: 0x00000001002f1f0d mono`monoeg_g_hash_table_insert_replace(hash=0x0000000101504a90, key=0x0000000104d03bc0, value=0x0000000101100ac0, replace=0) at ghashtable.c:243 [opt]
    frame #3: 0x00000001001bee08 mono`mono_register_jit_icall_wrapper(info=0x0000000101100ac0, wrapper=0x0000000104d03bc0) at icall.c:8693 [opt]
    frame #4: 0x000000010000abe7 mono`mono_icall_get_wrapper_full(callinfo=0x0000000101100ac0, do_compile=0) at mini-runtime.c:655 [opt]
    frame #5: 0x000000010000b92d mono`mono_resolve_patch_target [inlined] mono_icall_get_wrapper(callinfo=<unavailable>) at mini-runtime.c:666 [opt]
    frame #6: 0x000000010000b923 mono`mono_resolve_patch_target(method=0x0000000000000000, domain=<unavailable>, code=0x0000000000000000, patch_info=0x0000000100808be8, run_cctors=0, error=<unavailable>) at mini-runtime.c:1416 [opt]
    frame #7: 0x000000010009a387 mono`load_method [inlined] init_amodule_got(amodule=<unavailable>) at aot-runtime.c:1998 [opt]
    frame #8: 0x000000010009a1a8 mono`load_method(domain=0x0000000101000970, amodule=0x0000000106800000, image=0x0000000103804800, method=0x0000000100806f28, token=100667992, method_index=4695, error=0x00007ffeefbff150) at aot-runtime.c:4087 [opt]
    frame #9: 0x0000000100099b97 mono`mono_aot_get_method(domain=0x0000000101000970, method=<unavailable>, error=0x00007ffeefbff150) at aot-runtime.c:4931 [opt]
    frame #10: 0x000000010000c7af mono`mono_jit_compile_method_with_opt(method=0x0000000100806f28, opt=374434303, jit_only=1, error=0x00007ffeefbff150) at mini-runtime.c:2415 [opt]
    frame #11: 0x0000000100010fed mono`mono_jit_runtime_invoke [inlined] mono_jit_compile_method_jit_only(method=<unavailable>, error=<unavailable>) at mini-runtime.c:2539 [opt]
    frame #12: 0x0000000100010fcd mono`mono_jit_runtime_invoke(method=<unavailable>, obj=<unavailable>, params=0x00007ffeefbff090, exc=0x000000000000000a, error=0x00007ffeefbff150) at mini-runtime.c:3079 [opt]
    frame #13: 0x00000001002114b8 mono`mono_runtime_invoke_checked [inlined] do_runtime_invoke(method=0x0000000100806f28, obj=0x0000000102000048, params=0x00007ffeefbff090, exc=<unavailable>, error=0x00007ffeefbff150) at object.c:2977 [opt]
    frame #14: 0x0000000100211482 mono`mono_runtime_invoke_checked(method=0x0000000100806f28, obj=0x0000000102000048, params=0x00007ffeefbff090, error=0x00007ffeefbff150) at object.c:3145 [opt]
    frame #15: 0x0000000100211545 mono`mono_runtime_invoke_handle(method=<unavailable>, obj=<unavailable>, params=<unavailable>, error=<unavailable>) at object.c:3151 [opt]
    frame #16: 0x00000001001abd7c mono`create_exception_two_strings(klass=0x0000000107009708, a1=MonoStringHandle @ 0x00007ffeefbff068, a2=MonoStringHandle @ 0x00007ffeefbff080, error=0x00007ffeefbff150) at exception.c:204 [opt]
    frame #17: 0x00000001001abbc5 mono`mono_exception_from_name_two_strings_checked(image=<unavailable>, name_space=<unavailable>, name=<unavailable>, a1=<unavailable>, a2=<unavailable>, error=0x00007ffeefbff150) at exception.c:264 [opt]
    frame #18: 0x000000010017fdb4 mono`create_domain_objects(domain=0x0000000101000970) at appdomain.c:219 [opt]
    frame #19: 0x000000010017f326 mono`mono_runtime_init_checked(domain=0x0000000101000970, start_cb=<unavailable>, attach_cb=<unavailable>, error=0x00007ffeefbff268) at appdomain.c:319 [opt]
    frame #20: 0x0000000100010ae9 mono`mini_init(filename=<unavailable>, runtime_version=<unavailable>) at mini-runtime.c:4586 [opt]
    frame #21: 0x0000000100071f69 mono`mono_main(argc=10, argv=<unavailable>) at driver.c:2447 [opt]
    frame #22: 0x0000000100000cfa mono`main [inlined] mono_main_with_options(argc=<unavailable>, argv=<unavailable>) at main.c:50 [opt]
    frame #23: 0x0000000100000ce6 mono`main(argc=10, argv=<unavailable>) at main.c:406 [opt]
    frame #24: 0x00007fff50315015 libdyld.dylib`start + 1
```

**Comment by jaykrell** [comment]
I don't think it is a dependency on exact hash values per se, but something is wrong. Adding "too many" JIT icalls breaks things.

**Comment by jaykrell** [comment]
Not quite understood but big clues:

When it doesn't work:

nm mscorlib.dll.dylib:

00000000008754d0 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u4_double
0000000000877b90 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u_double


When it works:

000000000087e670 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u4_double
00000000008753b0 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u8_double


and we have both:


	register_opcode_emulation (OP_FCONV_TO_U8, "__emul_fconv_to_u8", "ulong double", mono_fconv_u8, "mono_fconv_u8", FALSE);

and later:
	register_opcode_emulation (OP_FCONV_TO_U, "__emul_fconv_to_u", "ulong double", mono_fconv_u8, "mono_fconv_u8", TRUE);


which are equivalent in terms of jit_icall_hash_addr.

i.e. the same function is registered with two different names, sometimes
avoiding wrapper, sometimes not.

Not a great construct, should probably register different functions.

It should still be deterministic from what I see.
The last insert should win, and upon rehash, it should be the only
present data.

And the opcode emulation should always have the last one.

One of these assertions must be wrong.

Surely the fix is not register the same function more than once (under multiple names) but I'd like to understand why.

**Comment by jaykrell** [comment]
With some printing, after rehash, fails:

dump_hash_table __emul_fconv_to_u->{name:__emul_fconv_to_u func:0x10242dfa0 wrapper:0x10242dfa0} (avoid wrapper)
dump_hash_table __emul_fconv_to_u8->{name:__emul_fconv_to_u8 func:0x10242dfa0 wrapper:0x0}


works, does not rehash:

dump_hash_table __emul_fconv_to_u8->{name:__emul_fconv_to_u8 func:0x10cc23f80 wrapper:0x0}
dump_hash_table __emul_fconv_to_u->{name:__emul_fconv_to_u func:0x10cc23f80 wrapper:0x10cc23f80}

So the different is the hash order.
This probably then

```

		/* JIT icall wrappers */
		/* FIXME: locking - this is "safe" as full-AOT threads don't mutate the icall hash*/
		g_hash_table_foreach (mono_get_jit_icall_info (), add_jit_icall_wrapper, acfg);
.
.
.
static void
add_jit_icall_wrapper (gpointer key, gpointer value, gpointer user_data)
{
	name = g_strdup_printf ("__icall_wrapper_%s", callinfo->name);
	wrapper = mono_marshal_get_icall_wrapper (callinfo->sig, name, callinfo->func, TRUE);
	add_method (acfg, wrapper);
}
.
.
.
mono_marshal_get_icall_wrapper (MonoMethodSignature *sig, const char *name, gconstpointer func, gboolean check_exceptions)
{
...
	if ((res = mono_marshal_find_in_cache (cache, (gpointer) func)))
		return res;
```

so either `mono_marshal_get_icall_wrapper` should be sensitive to name,
or we should never register the same function with multiple names.
or, only do that if both avoid wrapper?

This isn't the only collision that I know of. 

There is also `mono_tls_get_lmf_addr and mono_get_lmf_addr`.

**Comment by jaykrell** [comment]
So I  suggest `mono_register_jit_icall_full` disallow duplicates in `jit_icall_hash_addr` and fix the collisions. That will add two one line functions at least.

Single instancing based on address in `mono_marshal_get_icall_wrapper` can remain.

`g_str_hash` function can change or not.

Alternatively `mono_marshal_get_icall_wrapper` could single instance based on name, not address. Duplicates based on name are already disallowed by `mono_register_jit_icall_full`. *Perhaps* that is better. The hashing is more expensive though, is a reason why not.

I not sure why the single instancing is hashtable based.
The data could probably live in MonoJitICallInfo and be directly looked for.
That might also be a good fix that allows the right number of duplicates and is more efficient than current form.

For example, `method-to-ir.c` does this:
```
		if (!info->wrapper_method) {
			info->wrapper_method = mono_marshal_get_icall_wrapper (info->sig, name, info->func, TRUE);
		}
```

but `mono_icall_get_wrapper_method` does not.

**Comment by jaykrell** [comment]
Hah. The problem is a little larger than that.

```
4) Testctor (MonoTests.System.DecimalTestMicrosoft.Testctor)
   System.ExecutionEngineException : Attempting to JIT compile method '(wrapper managed-to-native) ulong object:__icall_wrapper___emul_fconv_to_u8 (double)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

  at System.Decimal+DecCalc.VarDecFromR8 (System.Double input, System.Decimal& pdecOut) [0x000a2] in <cde8d80b77cf4b978b4cffa7c1db6ef6>:0 
  at System.Decimal..ctor (System.Double value) [0x00000] in <cde8d80b77cf4b978b4cffa7c1db6ef6>:0 
  at MonoTests.System.DecimalTestMicrosoft.Testctor () [0x00000] in /s/mono4/mcs/class/corlib/Test/System/DecimalTest-Microsoft.cs:833 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <cde8d80b77cf4b978b4cffa7c1db6ef6>:0 


Results saved as /s/mono4/mcs/class/corlib/TestResult-testing_aot_full.xml.
make[1]: *** [run-test-lib] Error 1
make: *** [do-run-test] Error 1
HB30-VM-Eklavya:corlib jay$  nm ./../../class/lib/testing_aot_full/mscorlib.dll | grep fconv_to_u
HB30-VM-Eklavya:corlib jay$  nm ./../../class/lib/testing_aot_full/mscorlib.dll.dylib | grep fconv_to_u
000000000093789e t plt__jit_icall___emul_fconv_to_u4
000000000093fc38 t plt__jit_icall___emul_fconv_to_u8
000000000097a4e6 t plt__jit_icall_native___emul_fconv_to_u
000000000097a90a t plt__jit_icall_native___emul_fconv_to_u4
000000000087ad40 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u4_double
0000000000874ea0 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u8_double
000000000087be70 t wrapper_managed_to_native_object___icall_wrapper___emul_fconv_to_u_double
```

Will poke a bit more.

**Comment by jaykrell** [comment]
Giving up and trying with duplicate functions. Setting avoid_wrapper consistently to true should also work, if that is the correct value.

**Pull request closed without merging**
