### PR TITLE
remove XML declaration line

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
fix for the bug
https://bugzilla.xamarin.com/show_bug.cgi?id=36388

full story https://github.com/gitextensions/gitextensions/issues/2710

### CODE REVIEW

**Comment by tritao** [comment]
Do you mind adding a test case for this change?

**Comment by ArsenShnurkov** [comment]
I don't have enough skills yet. Just recently I packaged the NUnit, and didn't learned it in depth yet. May be in 3-5 years i will do.

**Comment by tritao** [comment]
You can learn the basics of NUnit in a couple minutes, you definitely won't need years for that :)

The tests for the code you're changing should be located in https://github.com/mono/mono/blob/master/mcs%2Fclass%2FSystem%2FTest%2FSystem.Configuration%2FSettingsPropertyValueTest.cs.

You will need to add a new method (you can probably base it of one of the existing ones) and check the behaviour that you're changing in this pull request. In this specific case, you should be able to just use one the simple NUnit methods in the `Assert` class.

**Comment by ArsenShnurkov** [comment]
these tests looks strange for me, lines 
https://github.com/mono/mono/blob/746650d1b93114b60feb155c2ee778a9e16ccb6d/mcs/class/System/Test/System.Configuration/SettingsPropertyValueTest.cs#L81
https://github.com/mono/mono/blob/746650d1b93114b60feb155c2ee778a9e16ccb6d/mcs/class/System/Test/System.Configuration/SettingsPropertyValueTest.cs#L220
i would perefer peer review first

**Comment by akoeplinger** [comment]
@ArsenShnurkov I tried those tests on .NET and the xml header is there as well, so that's ok.

The test case from your bugzilla bug showed the problem on Mono for me and worked on .NET, which means we do indeed have a bug in Mono :)

I'd suggest adding your test case and making sure the existing tests still pass after your fix.

**Comment by ArsenShnurkov** [comment]
I don't understand, how to create the full save file in memory for test case (the sample from the bugtracker saves to default location on disk)

**Comment by alexrp** [comment]
build

**Comment by esdrubal** [comment]
While doing a test case for your pull request I noticed that .NET SettingsPropertyValue.SerializedValue returns XML with a XML declaration, you can see it by running the code below.
``` csharp
SettingsProperty p = new SettingsProperty ("property",
								   typeof (WindowPositionList),
								   null,
								   true,
								   10,
								   SettingsSerializeAs.Xml,
								   null,
								   true,
								   false);

SettingsPropertyValue v = new SettingsPropertyValue (p);
v.PropertyValue =  new WindowPositionList ();
Console.WriteLine(v.SerializedValue);
```

While poking into reference source code I found that they do remove the XML declaration from the XML returned by SettingsPropertyValue.SerializedValue in [LocalFileSettingsProvider](http://referencesource.microsoft.com/#System/sys/system/configuration/LocalFileSettingsProvider.cs,482).

In Mono [LocalFileSettingsProvider](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/System/System.Configuration/LocalFileSettingsProvider.cs#L43) uses [CustomizableFileSettingsProvider](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/System/System.Configuration/CustomizableFileSettingsProvider.cs). I think this can be fixed by adding same logic as reference sources uses to remove XML declarations from the value returned [here](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/System/System.Configuration/CustomizableFileSettingsProvider.cs#L626)

**Comment by ArsenShnurkov** [comment]
also i don't understood 2 things:
- this check - https://github.com/mono/mono/blob/347f0a24fb9bd8cc8f16fab848b57fd0362c8ce9/mcs/class/System/System.Configuration/CustomizableFileSettingsProvider.cs#L692-L694
- and why it was removed

**Comment by esdrubal** [comment]
@ArsenShnurkov thanks for your contribution, #2400 contains your fix and test. I also added a message to your commit and fixed a style issue (spaces before parameters parenthesis).

#2400 removed the #if true else dead code, thanks for pointing this out.

It looks like the test you mentioned is expecting the serialized value to use '\n' instead of Environment.NewLine because the serializer is probably using '\n' regardless the value of Environment.NewLine that is "\r\n" in UNIX.

**Pull request closed without merging**
