### PR TITLE
[runtime] Remove most of the contents of MonoDynamicGenericClass, the…

### PR DESCRIPTION
**Pull request by vargaz**
… elements of the 'fields' array are not used anywhere, making all the other fields unneccesary too.

### CODE REVIEW

**Comment by vargaz** [comment]
It might be possible to remove the whole structure, it only has an 'initialized' field now which is used in only one place (fix_partial_generic_class ()).

**Comment by lambdageek** [comment]
👍  nice!

**Comment by kumpera** [comment]
Won't this trigger any different behavior during construction?

**Comment by vargaz** [comment]
I don't think so. Most of the relevant code was inside:

if (f->field >= dgclass->fields && f->field < dgclass->fields + dgclass->count_fields) {

But we never returned the members of dgclass->fields anywhere, so all this code could never be reached, so dgclass->field_objects/field_generic_types was never accessed.

**Pull request merged**
