### PR TITLE
Add embedding API to expose empty string instance

### PR DESCRIPTION
**Pull request by mrvoorhe**
The previous PR was https://github.com/mono/mono/pull/4047 and had build issues on linux due to mono_string_empty_wrapper calling mono_string_empty.

This PR adds a mono_string_empty_checked.

### CODE REVIEW

**Comment by vargaz** [comment]
The previous PR was good, just remove the
MONO_RT_EXTERNAL_ONLY lines from object.h.

**Comment by mrvoorhe** [comment]
@vargaz Thanks, that's easier.  PR updated.

**Comment by vargaz** [comment]
build

**Comment by akoeplinger** [comment]
build

**Pull request merged**
