### PR TITLE
Fix RouteCollection not correctly clearing itself

### PR DESCRIPTION
**Pull request by tastywheattasteslikechicken**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=13909

### CODE REVIEW

**Comment by tritao** [comment]
approve

**Comment by tritao** [comment]
Can you sign the CLA so we can start getting this processed?

**Comment by tastywheattasteslikechicken** [comment]
CLA signed and sent prior to submitting pull request -- waiting on human to process it.

**Comment by akoeplinger** [comment]
We can take small fixes with less than a dozen lines without a CLA, so I went ahead and merged this in to master with the test from the bugzilla report. Thanks!

**Pull request closed without merging**
