### PR TITLE
[CI] Disable omit-fp optimization to produce more meaningful native stacktraces

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Build fails: `Invalid option for the MONO_DEBUG env variable: disable_omit_fp`

**Comment by vargaz** [comment]
On another note, the option should be called 'disable-omit-fp' for consistency.

**Comment by vargaz** [comment]
I think the build fails because the bootstrap mono is too old and doesn't support this option.

**Comment by ludovic-henry** [comment]
@vargaz agreed. 

I will either look into how to pass MONO_DEBUG only to the non-basic profile, or wait for the bootstrap mono to bump version.

**Pull request closed without merging**
