### PR TITLE
[MacSDK] Bump xamarin-gtk-theme.py to latest revision from private bockbuild

### PR DESCRIPTION
**Pull request by sevoku**
This adds some accessibility fixes from https://github.com/mono/xamarin-gtk-theme/pull/35

### CODE REVIEW

**Comment by sevoku** [comment]
@monojenkins backport 2019-08

**Comment by Therzok** [comment]
This bumps to the tip of a PR. Can we merge the PR and bump to master?

**Comment by sevoku** [comment]
Yes, I'll do that once we have verified both

**Comment by sevoku** [comment]
and done! now we need to bump this in VSMac once this gets backported and merged.

@akoeplinger could you help with this?

**Comment by sevoku** [comment]
@monojenkins backport to 2019-08
@monojenkins backport to 2019-10

**Pull request merged**
