### PR TITLE
[sdb] Add property AssemblyMirror.HasDebugInfo

### PR DESCRIPTION
**Pull request by jbevain**
This PR adds a new property to AssemblyMirror. This will allow us to optimize the treatment of assemblies with and without debug information in our debugger client.

### CODE REVIEW

**Comment by jbevain** [comment]
Currently testing scenario, please don't merge.

**Comment by jbevain** [comment]
Testing done and good to go.

**Comment by jbevain** [comment]
Important notice, 21010fa5b5fba252471f22f3b1429f2fb7917576 fixes `mono_debug_image_has_debug_info` to handle portable pdbs. Previously it was only returning true for mdb files.

This impacts:

https://github.com/mono/mono/blob/ea761357f8169a98e8f5246ad082b61264a3bb61/mono/mini/method-to-ir.c#L6003
https://github.com/mono/mono/blob/ea761357f8169a98e8f5246ad082b61264a3bb61/mono/mini/interp/transform.c#L2488

Where this code path will now light up for ppdb, which I think should be expected anyway.

**Comment by jbevain** [comment]
@marek-safar @vargaz good to merge?

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Pull request merged**
