### PR TITLE
[sgen] Don't report gc_resize profiler events from worker threads.

### PR DESCRIPTION
**Pull request by alexrp**
See 4acc3df for why this is problematic. The bug was introduced in d7ac79c.

This fixes an occasional deadlock in the profiler stress tests.

Also some improvements to the profiler stress test runner to make it easier to work with.

### CODE REVIEW

**Comment by alexrp** [comment]
build profiler stress

**Comment by BrzVlad** [comment]
@alexrp  Is it ok to report heap size changes only during GCs ? Is it ok to stop reporting heap resizes for LOS and potential degraded allocs, which are other sources of heap growth outside of collections.

**Comment by alexrp** [comment]
Yes, I'd say this is fine. We never made any guarantees about when exactly this event is raised, or even how accurate the information is. It's only meant to give a rough idea of the heap size at arbitrary intervals, nothing more.

**Comment by alexrp** [comment]
@monojenkins merge

**Comment by alexrp** [comment]
Failures look unrelated to me.

**Comment by akoeplinger** [comment]
Merging as per discussion in Slack.

**Pull request merged**
