### PR TITLE
[master] Bump msbuild to track xplat-master

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
Need to update roslyn and nuget on this. My automated script doesn't handle that.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
`Linux AArch64`: `Test collection for System.Threading.ThreadPools.Tests.ThreadPoolTests.System.Threading.ThreadPools.Tests.ThreadPoolTests.QueueRegisterPositiveAndFlowTest`

`OS X x64 C++`: Not sure why this says failed. Tests seem to have passed, but the status is UNSTABLE. Though I didn't dig into the full logs.

`Windows x64 C++`: `MonoTests.runtime.bug-10127.exe_timedout`

**Comment by radical** [comment]
`OS X Extended`:

```
MonoTests.test-unhandled-exception-2-255-without-managed-handler.unhandled-exception-7.exe
MonoTests.test-unhandled-exception-2-255-with-managed-handler.unhandled-exception-7.exe
MonoTests.runtime.cross-domain.exe
MonoTests.runtime.bug-335131.2.exe
MonoTests.runtime.appdomain-unload-doesnot-raise-pending-events.exe
MonoTests.runtime.appdomain-unload-callback.exe
MonoTests.runtime.bug-80307.exe
MonoTests.runtime.appdomain-unload.exe
MonoTests.runtime.stackframes-async.2.exe
MonoTests.runtime.monitor.exe
MonoTests.runtime.generic-marshalbyref.2.exe
MonoTests.runtime.appdomain-async-invoke.exe
MonoTests.runtime.generic-unloading.2.exe
MonoTests.runtime.bug-415577.exe
MonoTests.runtime.appdomain-exit.exe
MonoTests.runtime.thread6.exe
MonoTests.runtime.threadpool-exceptions7.exe
MonoTests.runtime.appdomain.exe
MonoTests.runtime.unload-appdomain-on-shutdown.exe
MonoTests.runtime.delegate9.exe
MonoTests.runtime.appdomain1.exe
MonoTests.runtime.appdomain-unload-asmload.exe
MonoTests.runtime.appdomain-thread-abort.exe
MonoTests.runtime.pinvoke3.exe
MonoTests.runtime.marshal-valuetypes.exe
MonoTests.runtime.appdomain-serialize-exception.exe
MonoTests.runtime.xdomain-threads.exe
MonoTests.runtime.localloc-noinit.exe
MonoTests.runtime.assemblyresolve_event6.exe
MonoTests.runtime.appdomain2.exe
MonoTests.runtime.remoting4.exe
MonoTests.test-sgen-regular-ms-simple.sgen-domain-unload-2.exe
MonoTests.test-sgen-regular-ms-simple.sgen-domain-unload.exe
MonoTests.gshared.generic-marshalbyref.2.exe
MonoTests.gshared.generic-marshalbyref.2.exe
MonoTests.gshared.generic-marshalbyref.2.exe
MonoTests.gshared.generic-marshalbyref.2.exe
MonoTests.test-sgen-regular-ms-conc-simple.sgen-domain-unload-2.exe
MonoTests.test-sgen-regular-ms-conc-simple.sgen-domain-unload.exe
MonoTests.test-unhandled-exception-2-255-without-managed-handler.unhandled-exception-3.exe
MonoTests.test-unhandled-exception-2-255-with-managed-handler.unhandled-exception-3.exe
```

**Comment by akoeplinger** [comment]
@radical btw. we now have a 2020-02 branch that will probably need to receive these msbuild updates as well.

**Pull request merged**
