### PR TITLE
[interp] Inline newobj.

### PR DESCRIPTION
**Pull request by jaykrell**
The real goal is to make it not recursive.
This is just a step along the way.
Note that the actual not-recursive change has *not* yet been developed,
so this *might* amount to nothing useful.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Again note that:
1. This does not contribute to known WebAssembly failures.
2. Apple does have fixes in the pipeline.

So it is "ok" to leave this alone.

**Comment by BrzVlad** [comment]
This opcode should probably be checked for refactoring before making it nonrecursive. I'm not sure but the value type case might be dead. The string case could be extracted in a separate opcode.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
