### PR TITLE
[appletls]: Use SecIdentityCreate() to avoid using the Mac keychain. (#4671)

### PR DESCRIPTION
**Pull request by baulig**
Cherry-picking PR #4671.

Reading Certificates from the Mac Keychain
==========================================

Reading the private key from the keychain is a new feature introduced with
AppleTls on XamMac and iOS. On Desktop Mono, this new feature has several
known issues and it also did not received any testing yet. We go back to the old
way of doing things, which is to explicitly provide an X509Certificate2 with a
private key.

Keychain Dialog Popups
======================

When using Xamarin.Mac or Xamarin.iOS, we try to search the keychain
for the certificate and private key.

On Xamarin.iOS, this is easy because each app has its own keychain.

On Xamarin.Mac, the .app package needs to be trusted via code-sign
to get permission to access the user's keychain. [FIXME: I still have to
research how to actually do that.] Without this, you will get a popup
message each time, asking you whether you want to allow the app to access
the keychain, but you can make these go away by selecting "Trust always".

On Desktop Mono, this is problematic because selecting "Trust always"
give the 'mono' binary (and thus everything you'll ever run with Mono)
permission to retrieve the private key from the keychain.

This code would also trigger constant keychain popup messages,
which could only be suppressed by granting full trust. It also makes it
impossible to run Mono in headless mode.

SecIdentityCreate
=================

To avoid these problems, we are currently using an undocumented API
called SecIdentityRef() to avoid using the Mac keychain whenever a
X509Certificate2 with a private key is used.

On iOS and XamMac, you can still provide the X509Certificate without
a private key - in this case, a keychain search will be performed (and you
may get a popup message on XamMac).

(cherry picked from commit 1eb27c1df8ed29d84ca935496ffd6c230447895a)

### CODE REVIEW

**Comment by baulig** [comment]
Prior to merging this, I would like to first build https://github.com/xamarin/xamarin-macios/pull/2001, then run the web-tests against the wrench lane created from it.

I will remove the "DON'T MERGE" label after I have confirmed that the tests work.

**Comment by marek-safar** [comment]
Please don't forget to update 2017-04 branch too

**Comment by baulig** [comment]
Sure, I'll do that once we have landed this in stable - want to make sure this actually works before creating too many integration PR's.

**Comment by baulig** [comment]
Read to merge once the bots finish building this.

**Pull request merged**
