### PR TITLE
[System] Import System.Diagnostics.Process

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
build

**Comment by ludovic-henry** [comment]
@kumpera could you pease confirm that you do not see the `_wapi_handle_...` error message anymore?

**Comment by akoeplinger** [comment]
This seems to break the Windows build:

```
"c:\j\workspace\w\msvc\mono.sln" (default target) (1) ->
"c:\j\workspace\w\msvc\libmono.vcxproj.metaproj" (default target) (6) ->
"c:\j\workspace\w\msvc\libmonoruntime.vcxproj" (default target) (7) ->
(ClCompile target) -> 
  ..\mono\metadata\icall.c(7854): error C2065: 'WapiFileTime' : undeclared identifier [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]
  ..\mono\metadata\icall.c(7854): error C2059: syntax error : ')' [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]
  ..\mono\metadata\icall.c(7858): error C2061: syntax error : identifier 'ves_icall_Microsoft_Win32_NativeMethods_GetCurrentProcessId' [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]
  ..\mono\metadata\icall.c(7858): error C2059: syntax error : ';' [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]
  ..\mono\metadata\icall.c(7858): error C2059: syntax error : 'type' [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]
  c:\j\workspace\w\mono\metadata/icall-def.h(44): error C2065: 'ves_icall_Microsoft_Win32_NativeMethods_GetCurrentProcessId' : undeclared identifier [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]
  ..\mono\metadata\icall.c(7989): error C2099: initializer is not a constant [c:\j\workspace\w\msvc\libmonoruntime.vcxproj]

    620 Warning(s)
    7 Error(s)
```

**Comment by ludovic-henry** [comment]
@akoeplinger the compilation is now fixed on windows

**Comment by akoeplinger** [comment]
@ludovic-henry I ran the runtime tests and new process stress tests in a loop for an hour on my Ubuntu box and didn't see any crashes/failures :)

Looks like it needs a rebase though.

**Pull request closed without merging**
