### PR TITLE
Bump bockbuild for Pango patch

### PR DESCRIPTION
**Pull request by bratsche**
Fixes bug #1048838, correct SF font not loading in VSMac

### CODE REVIEW

**Comment by bratsche** [comment]
@akoeplinger I can't set do-not-merge tags on this repo anymore, so please don't review/merge this, I just want to make a build.

**Comment by bratsche** [comment]
@monojenkins build pkg

**Comment by bratsche** [comment]
@monojenkins build pkg

**Comment by bratsche** [comment]
@monojenkins build pkg

**Comment by bratsche** [comment]
@monojenkins build pkg

**Comment by bratsche** [comment]
@monojenkins build pkg

**Comment by sevoku** [comment]
@bratsche awesome, thanks! Verified and it works.

@akoeplinger we'd need this backported to 6.8 (2019-10) for MonoDevelop 8.5 and if possible also to 6.6 (2019-08) for MonoDevelop 8.4 servicing.

**Comment by akoeplinger** [comment]
I got approval from Marek Safar on Slack to backport to 2019-08+, I manually did the backport.

**Pull request merged**
