### PR TITLE
[2019-08] bump msbuild+roslyn to track mono-2019-08

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
`OSX Extended`:
```
MonoTests.test-unhandled-exception-2-255-without-managed-handler.unhandled-exception-3.exe
MonoTests.test-unhandled-exception-2-255-with-managed-handler.unhandled-exception-3.exe
```

`OX x64 iOS Sdk`:
```
22:32:17 + brew install wget ninja ios-deploy p7zip
22:32:21 Updating Homebrew...
22:49:39 FATAL: command execution failed
```

**Comment by radical** [comment]
@monojenkins build failed

**Comment by radical** [comment]
`OS X Extended` failed with:

```
make: *** No rule to make target `test-wrench'.
16:20:06 /Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/scripts/ci/babysitter: Test suite terminated with code 2, and suite cannot report test case data. Halting.
16:20:06 *** end(0): runtime-tests-llvm: \e[43mUnstable\e[0m
16:20:06 *** start: corlib-tests-llvm
16:20:06 ../../build/rules.make:98: ../../build/platforms/.make: No such file or directory
16:20:06 il/il.make:3: *** Unknown platform "" for profile "net_4_x".  Stop.
```

This is not related to this PR, AFAICS. @akoeplinger OK to merge this?

**Comment by akoeplinger** [comment]
Yeah looks good.

**Pull request merged**
