### PR TITLE
[corlib] Don't load the machine config file if it's missing. Fixes #44707

### PR DESCRIPTION
**Pull request by kumpera**
I need someone to review whether this fix makes sense or not.

Will remoting work if the machine config is not loaded?

### CODE REVIEW

**Comment by kumpera** [comment]
@marek-safar I need you to review this one, I have no clue on whether the fix makes sense or not

**Comment by marek-safar** [comment]
That should work

**Comment by kumpera** [comment]
I don't think this will work, we ignore the bundled machine config and XM doesn't add one too.

**Comment by kumpera** [comment]
Errors are due to the async process dispose bug I'm working on other PRs

**Pull request merged**
