### PR TITLE
[wasm] Preserve MonoPInvokeCallback using a linker xml descriptor.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/19594.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Comment by lewing** [comment]
I need to land #19608 first

**Comment by lewing** [comment]
We can backport this but I think it only impacts AOT senarios

**Comment by vargaz** [comment]
Yes, it doesn't need a backport.

**Pull request merged**
