### PR TITLE
[netcore] Fix the tests.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by filipnavara** [comment]
Would not there be the same issue with `Monitor.cs`? Both `GC.cs` and `Monitor.cs` have no partial-class counter-parts in the shared CoreLib partition. Thus `Monitor` is missing the proper `public` modifier too.

**Comment by EgorBo** [comment]
@filipnavara actually Monitor has two files in System.Private.CorLib: https://github.com/mono/mono/blob/master/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj#L256 and https://github.com/mono/mono/blob/master/mcs/class/System.Private.CoreLib/System.Private.CoreLib.csproj#L200 (one of them has `public`)

**Comment by filipnavara** [comment]
@EgorBo Oh, I looked only in the `netcore/System.Private.CoreLib/shared` folder. Nevertheless I think it's a bit dangerous to leave the modifiers out here because it's possible that the other one will go away.

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
