### PR TITLE
[runtime] Always use MONO_ARCH_IMT_REG

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
Let's see if this breaks any tests

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
Sorry for making a bit of a mess with your PR test statuses, Alex. It should be better in the future.

**Comment by akoeplinger** [comment]
build

**Comment by vargaz** [comment]
Merged the first commit by hand, so the second can be commited. It should also remove the definition of mono_arch_emit_imt_argument () from mini.h.

**Comment by vargaz** [comment]
Merged by hand.

**Pull request closed without merging**
