### PR TITLE
"Code Ultramarine": sync `X509Certificate2` with CoreFX and introduce `X509Certificate2ImplUnix`

### PR DESCRIPTION
**Pull request by baulig**
Sync `X509Certificate2` implementation with CoreFX, similar to how we did for `X509Certificate` in "Blue" (#9650).

* Introducing `X509Certificate2ImplUnix` as new common base class for `X509CertificateImplApple`, `X509CertificateImplBtls` and `X509Certificate2ImplMono`.  This uses the internal `CertificateData` class from CoreFX instead of the old "fallback" implementation from "Mono.Security".

* `MonoBtlsProvider`, `X509CertificateImplBtls`: the "fallback" option has been removed since we now always provide this functionality via the managed `CertificateData`.

* `X509CertificateImplMono`: This has been largely stripped down to use the new `X509CertificateImplUnix`.

### CODE REVIEW

**Comment by baulig** [comment]
Overnight CI test results:

- `OptionContextTest.Exceptions` and `OptionTest.Exceptions` are the result of incorrect / partial merge of "Aquamarine".  They will go away after rebasing on top of current master.
- Same for `MonoTests.coreclr-coremanglib.external/coreclr/tests/src/CoreMangLib/cti/system/argumentoutofrangeexception/argumentoutofrangeexceptionctor2.exe` and
`MonoTests.coreclr-coremanglib.external/coreclr/tests/src/CoreMangLib/cti/system/argumentoutofrangeexception/argumentoutofrangeexceptionmessage.exe`
- `X509Certificate2ExtensionsTests.PublicKeyIsReusable` - this seems to be a regression.

I'm going to rebase on top of current master, cherry-pick "Blue" on top of it, then apply all the other changes.

**Comment by baulig** [comment]
@marek-safar This is an old PR that was left over from July.  I rebased it on top of current master and cleaned it up a little bit.

**Comment by baulig** [comment]
@monojenkins commit csproj

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Pull request merged**
