### PR TITLE
Bump to release roslyn 3.1.0

### PR DESCRIPTION
**Pull request by kg**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, this should've already be done with https://github.com/mono/mono/pull/14778

**Comment by kg** [comment]
I thought that one was 06. I must have picked the wrong base branch... shouldn't we merge this to 06 then?

**Comment by lewing** [comment]
He opened one against master from your 06 bump, this should be safe to close

**Comment by kg** [comment]
> 
> 
> ~He opened one against master from your 06 bump, this should be safe to close~ you successfully opened one from 06 to master using monojenkins
That explains it, thanks. I saw two backport failures so i assumed both of them failed.

**Pull request closed without merging**
