### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by jeffschwMSFT**
Updating the readme with an announcement about stewardship of the upstream of mono/mono

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by Neustradamus** [comment]
Dear old @mono team, @jeffschwMSFT, etc.,

It is possible to add ownership of the @mono organization to Wine HQ team? -> @julliard
It is important to have a continuous update of the code on GitHub, a mirror of https://gitlab.winehq.org/mono.

It is important to have a official mirrors like the main Wine sourcecode:
- https://github.com/wine-mirror/wine (mirror of https://gitlab.winehq.org/wine/wine)

Can you give all informations of hosting servers, domain names to the new team for the continuous service?
The new team must have all to the future.

Thanks in advance.

Regards.

Linked to:
- https://github.com/mono/mono/issues/21796#issuecomment-2335189368
- https://github.com/mono/mono/issues/20931#issuecomment-2335190653
- https://github.com/mono/website/issues/633#issuecomment-2335192110
- https://github.com/mono/mono/issues/21798

**Comment by Kreijstal** [comment]
true, when looking at mono, prs are all in github not in wine. Also CI

**Comment by madewokherd** [comment]
I'm still keeping an eye on activity here (hi), and trying to address things when I see interest. There is CI but at the moment it's limited to Linux amd64 (implementing the rest of it is on my todo list but I've paused it because doing all that work with no feedback and no real improvement in Mono to show for it was not good for my mental health - help would still be appreciated). My understanding is that the original team doesn't plan to maintain the CI that's here, so I can't rely on it.

In theory, I could set up code mirroring from Winehq GitLab (I know how it works now that I've done it on my personal GitHub fork) to here if I had push access, or I could give someone with push access the privileges they'd need on Winehq GitLab.

**Comment by Kreijstal** [comment]
> I'm still keeping an eye on activity here (hi), and trying to address things when I see interest. There is CI but at the moment it's limited to Linux amd64 (implementing the rest of it is on my todo list but I've paused it because doing all that work with no feedback and no real improvement in Mono to show for it was not good for my mental health - help would still be appreciated). My understanding is that the original team doesn't plan to maintain the CI that's here, so I can't rely on it.
> 
> In theory, I could set up code mirroring from Winehq GitLab (I know how it works now that I've done it on my personal GitHub fork) to here if I had push access, or I could give someone with push access the privileges they'd need on Winehq GitLab.

your fork doesn't have issues or discussions, but maybe that's okay.. However, I think this place will be archived one day so it'd be nice to allow interaction to github outsiders (true not everyone will want to create a wine gitlab account if they are forced to use their real names)

**Comment by madewokherd** [comment]
Issues are enabled now on GitLab fwiw, and I haven't been enforcing any naming policy. But yes, I would rather meet people where they are and not require them to be on Winehq GitLab.

**Pull request merged**
