### PR TITLE
[msbuild] Bump to get workaround for bxc #55697 .

### PR DESCRIPTION
**Pull request by radical**
https://github.com/mono/msbuild/commit/f296e67b6004dd39c3f43b177bcf45dfbe931341

### CODE REVIEW

**Comment by marek-safar** [comment]
Don't forget to update -08 and master

**Comment by migueldeicaza** [comment]
I am ok with this change.

Can we get this backported to the 15.4 SDKs for Android/iOS?

**Comment by radical** [comment]
@migueldeicaza This is a global change that disables it for all projects. Though XA already has it disabled. This PR is for 2017-06 branch, meant for 15.4 mono. So, QA just needs to cherry pick this.

**Comment by marek-safar** [comment]
@radical why you didn't choose the same approach as XA. We need to disable it really only for mobile setups only

**Comment by radical** [comment]
My thinking was that this `sgen` code path hasn't really been tested in msbuild/mono and considering that it wasn't available at all in xbuild, it suggests that maybe nobody was depending on it. And were getting tripped because suddenly msbuild enabled it. This makes it opt-in, till we fix `sgen`. The user can still override the property and use this.

**Pull request merged**
