### PR TITLE
Unity 5.0 staging

### PR DESCRIPTION
**Pull request by zanezhang**

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by kumpera** [comment]
Hey Guys,

We'll this to be licensed under the MIT license before we start processing it.

**Comment by tritao** [comment]
Thanks for the contribution but this pull request is a big dump of code and unworkable as it is. Please send small pull requests for each individual issues.

**Comment by migueldeicaza** [comment]
This looks like an operator mistake, likely not intended to be submitted upstream

**Pull request closed without merging**
