### PR TITLE
[System]: Use HttpListener from CoreFX.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by baulig** [comment]
Depends on merging https://github.com/mono/mono/pull/4849 first and I'd also like to run some test before this gets in.

I'll remove the "DON'T MERGE" label once the other PR has landed and I'm done testing.

**Comment by kumpera** [comment]
That won't stop everyone from being SUPER EXCITED by this. :)

**Comment by baulig** [comment]
Unfortunately, we are blocked on https://github.com/dotnet/corefx/issues/19827.

**Comment by filipnavara** [comment]
Seems like the corefx issue was fixed. Time to reevaluate this PR?

**Comment by baulig** [comment]
I will make a new PR next week.

**Pull request closed without merging**
