### PR TITLE
[debugger] Debugger doesn't break on unhandled exceptions 

### LINKED ISSUE #15203: Debugger doesn't break on unhandled exceptions
## Steps to Reproduce

1. Write simple console application throwing unhandled exception
```
using System;

namespace ConsoleApplication1
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            throw new ArgumentException("test");
        }
    }
}
```
2. Run debug: `mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55555 Program.exe`

### Current Behavior

No `UnhandledException` event sent, so a debugger doesn't break on unhandled exceptions. 

### Expected Behavior

A debugger breaks on unhandled exceptions

## On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Mono 5.20.1.19**:
```
Mono JIT compiler version 5.20.1.19 (2018-10/886c4901747 Tue Apr  9 12:37:29 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           
        SIGSEGV:       altstack
        Notification:  kqueue
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

Also reproduces on **Mono 6.0.0.299**.
Works as expected when using **Mono 5.18.1.3**.

I tried it with JetBrains Rider and VS Code and both don't break on unhandled exceptions.

I also tried to reproduce the scenario on Windows with Mono **5.20.1.19** and everything works as expected.

### PR DESCRIPTION
**Pull request by thaystg**
When the try catch found is in a MONO_WRAPPER_RUNTIME_INVOKE method (in this case in "runtime_invoke_void_object" method) the exception should be treated as an UNHANDLED by the debugger.

Fixes #15203

### CODE REVIEW

**Comment by vargaz** [comment]
Can you add a test for this ? We have a bunch of unhandled exception tests already in dtest.cs.

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@vargaz any objections?

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Pull request merged**
