### PR TITLE
warning: mono-threads-wasm.c no previous prototype for function mono_background_exec

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
This looks good to me but can not approve it.

**Comment by jaykrell** [comment]
Why not?

**Comment by kjpou1** [comment]
Not one of the reviewers so do not have a button to approve.

**Comment by jaykrell** [comment]
Ah. I thought anyone in org could. That seemed to be my previous experience.

**Pull request merged**
