### PR TITLE
Add reflected type to event methods

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes https://github.com/mono/mono/issues/13350
Fixes https://github.com/mono/mono/issues/10277

### CODE REVIEW

**Comment by lambdageek** [comment]
@MaximLipnin Could you add a regression test for this?

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Pull request merged**
