### PR TITLE
F# portable debugging

### PR DESCRIPTION
**Pull request by nosami**
Cherry picked F# portable pdb patches from 2017-06 /cc: @akoeplinger 

Does this need to go into master too?

### CODE REVIEW

**Comment by akoeplinger** [comment]
> Does this need to go into master too?

Yes. The general rule is actually to open a PR against master first, and to the other branches once that one is approved.

**Comment by nosami** [comment]
OK. Will do that in future. Thanks.

**Comment by akoeplinger** [comment]
Oh and we prefer PRs from forks instead of branches in the main mono repo (unless you need a Wrench lane or something).

**Comment by nosami** [comment]
OK

**Pull request merged**
