### PR TITLE
[IGNORE][DO_NOT_MERGE] Test msbuild 16

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@akoeplinger "OS X Extended" is not showing up in the list. Am I missing something?

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by alexischr** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Rebased on master.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
That didn't help with:

```
20:31:32 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
20:31:32 
20:31:32 Mono Warning: llvm support could not be loaded.
20:31:32 runtime-invoke.gen.cs(1,11): error CS1002: ; expected
20:31:32 runtime-invoke.gen.cs(1,11): error CS0116: A namespace cannot directly contain members such as fields or methods
20:31:32 runtime-invoke.gen.cs(1,17): error CS1022: Type or namespace definition, or end-of-file expected
20:31:32 runtime-invoke.gen.cs(1,33): error CS1001: Identifier expected
20:31:32 runtime-invoke.gen.cs(1,33): error CS1003: Syntax error, ',' expected
20:31:32 runtime-invoke.gen.cs(1,34): error CS1003: Syntax error, ',' expected
20:31:32 runtime-invoke.gen.cs(1,45): error CS1001: Identifier expected
20:31:32 runtime-invoke.gen.cs(1,47): error CS1031: Type expected
20:31:32 runtime-invoke.gen.cs(1,47): error CS1001: Identifier expected
20:31:32 runtime-invoke.gen.cs(1,47): error CS1003: Syntax error, ',' expected
20:31:32 runtime-invoke.gen.cs(1,51): error CS1018: Keyword 'this' or 'base' expected
20:31:32 runtime-invoke.gen.cs(1,51): error CS1002: ; expected
20:31:32 runtime-invoke.gen.cs(1,61): error CS1002: ; expected
20:31:32 runtime-invoke.gen.cs(1,61): error CS0116: A namespace cannot directly contain members such as fields or methods
20:31:32 runtime-invoke.gen.cs(3,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations
20:31:32 runtime-invoke.gen.cs(4,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations
```

**Comment by radical** [comment]
Rebased on https://github.com/mono/mono/commit/1b09a26 which is green on jenkins.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Package

**Pull request closed without merging**
