### PR TITLE
[arm] Call the tls get trampoline through a GOT slot instead of direc…

### PR DESCRIPTION
**Pull request by vargaz**
…tly, since a direct call could go through the trampoline code which would fail if the thread is not attached to the runtime. Fixes #45371.

### CODE REVIEW

**Comment by BrzVlad** [comment]
Would it be better to do these calls through the plt, reusing the logic from the aot compiler backend ?

**Comment by vargaz** [comment]
This approach is easier I think, the plt entries are lazily inited at first call, so we would have to add a lot of special cases to that code.

**Comment by vargaz** [comment]
Any other comments ?

**Comment by BrzVlad** [comment]
LGTM

**Pull request merged**
