### PR TITLE
Use functions instead of macros for is_in/is_out.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
And you’ll absorb this there?

**Comment by filipnavara** [comment]
Let's proceed with this one I guess. I'll submit it once this gets merged.

**Comment by lambdageek** [comment]
@filipnavara the more I look at these two predicates, the more I wish that there was a comment that explained that they're meant to treat byref params as both in and out. It looked fine yesterday, but today I keep having to look twice.

**Comment by jaykrell** [comment]
@monojenkins squash

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
