### PR TITLE
More assert information for gdb-less PowerPC.

### PR DESCRIPTION
**Pull request by jaykrell**
CI fails but doesn't run gdb and get stacks.
I haven't yet tried locally on the machine.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux PPC64 little endian

**Comment by jaykrell** [comment]
The asserts aren't wrong, but the PowerPC (big endian) bug has been solved.

**Comment by NattyNarwhal** [comment]
To be honest, I barely how or what I pinned down - it's been a few months...

**Comment by jaykrell** [comment]
Not clearly useful, closing.

**Pull request closed without merging**
