### PR TITLE
[offsets-tool] Use git protocol instead of ssh to allow anonymous access.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by marek-safar** [comment]
Why is it not submodule as everything else?

**Comment by rolfbjarne** [comment]
@tritao do you know answer to Marek's question?

**Comment by tritao** [comment]
When I originally added this to Monodroid, the tool was not run by default as part of the build, so we didn't go with submodule. At this point, a submodule might make more sense.

**Comment by akoeplinger** [comment]
The nice thing about this is that it doesn't bloat your Mono checkout with 60MB of binary blobs if you don't need it. A nuget package with CppSharp would have the same benefit, @tritao is there one?

Let's merge this for now to get the macios anonymous build unblocked, we can submodule it later on if we think it's the better approach.

**Pull request merged**
