### PR TITLE
[WIP] Get mobile-static tests working

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by vargaz** [comment]
Some of the commits could be squashed.

**Comment by marek-safar** [comment]
I agree we should submodule nunit-lite but mainly not 2 years old copy of it.

**Comment by alexanderkyte** [comment]
@marek-safar I am using the version of nunit-lite that we use for building monotouch. If it works and is maintained by us, why chase a newer unit test framework?

**Comment by marek-safar** [comment]
If you just use/submodule it I'd be ok with it but you seem to forked it with yet another local changes which makes us even more incompatible with trunk version of it, so I am not sure not we should still call it nunit-lite.

see https://github.com/nunit/dev/wiki/NUnitLite-Unification

**Comment by kumpera** [comment]
Hey guys,

Can we just submodule the fork based on spouliot's repo and move on?

**Pull request closed without merging**
