### PR TITLE
warning: 'emit_load' defined but not used [-Wunused-function]

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
Would be better to rename emit_load_general () to emit_load () then.

**Comment by jaykrell** [comment]
Sure, will do.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
