### PR TITLE
[runtime] Gracefully handle crashes before mono-state dependencies inited

### PR DESCRIPTION
**Pull request by alexanderkyte**
Fixes @vargaz crash:

https://gist.github.com/vargaz/f4bc5056efcc172b97b548d82192994b

### CODE REVIEW

**Comment by luhenry** [comment]
@alexanderkyte does this affect `2018-02` as well?

**Comment by alexanderkyte** [comment]
@luhenry we will want a full backport after merge. Though this shouldn't have any impact other than making some native crashes contain a few extra frames due to double fault. It won't make a working program break, and it won't prevent lldb from printing a crash.

**Comment by alexanderkyte** [comment]
Related https://github.com/mono/mono/pull/8843 and https://github.com/mono/mono/pull/8842

**Comment by alexanderkyte** [comment]
@luhenry test blocking merge is `MonoTests.Mono.Profiler.Log.ProfilerTests.MonoTests.Mono.Profiler.Log.ProfilerTests.ProcessTimeSamplingWorks`

**Pull request merged**
