### PR TITLE
[profiler] Don't call mono_gc_base_init () before loading profilers.

### PR DESCRIPTION
**Pull request by alexrp**
Just putting this through CI to see what, if anything, breaks.

### CODE REVIEW

**Comment by lambdageek** [comment]
build coop

**Comment by alexrp** [comment]
build profiler stress

**Comment by alexrp** [comment]
Looks like this doesn't break anything anymore. @kumpera thoughts?

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
build coop

**Comment by alexrp** [comment]
build profiler stress

**Pull request merged**
