### PR TITLE
[ci] Switch .pkg PR build to pipeline script as well

### PR DESCRIPTION
**Pull request by akoeplinger**
@monojenkins skip

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build pkg new

**Comment by akoeplinger** [comment]
@monojenkins build pkg new

**Comment by akoeplinger** [comment]
@monojenkins build pkg new

**Comment by akoeplinger** [comment]
@monojenkins build pkg new

**Comment by akoeplinger** [comment]
@monojenkins build pkg new

**Comment by akoeplinger** [comment]
@monojenkins build pkg new

**Comment by luhenry** [comment]
Am i missing something or does the build triggered by `@monojenkins build pkg new` doesn't add a status check to the PR?

**Comment by akoeplinger** [comment]
@luhenry it does but I pushed another commit and didn't comment the trigger word on that last fixup commit so it didn't get shown.

The `build pkg new` was just for testing btw., it's the usual `build pkg` now.

**Pull request merged**
