### PR TITLE
[eglib] Assert in g_strlcpy () if src/dest is NULL, instead of printing a warning.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
Alternatively, don't warn at all and just do early return.

**Comment by jaykrell** [comment]
But what should copying null to non-null do?
Maybe nul terminate as empty?

**Comment by jaykrell** [comment]
Also the behavior should be consistent independent of `#ifdef HAVE_STRLCPY`.

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
