### PR TITLE
mdoc: Multiple performance fixes

### PR DESCRIPTION
**Pull request by rolfbjarne**
Multiple performance fixes that makes processing Xamarin.iOS.dll go from
taking 25 minutes to 26 seconds.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
There's an identical PR for api-doc-tools: https://github.com/mono/api-doc-tools/pull/69

**Comment by marek-safar** [comment]
@rolfbjarne you made this while I am replacing mdoc in mono with https://github.com/mono/api-doc-tools. Please do PR there. I am working on PR for api-doc-tools integration

**Comment by migueldeicaza** [comment]
We can probably still backport this to the Mono branches that are currently in use by Xamarin.iOS?

**Comment by rolfbjarne** [comment]
@marek-safar I already did a PR in api-doc-tools.

**Comment by akoeplinger** [comment]
We switched to api-doc-tools in master so this doesn't apply anymore. If we decide to do backport please send a new PR targeting the relevant branches :)

**Pull request closed without merging**
