### PR TITLE
[wasm][debugger] Evaluate properties and generics.

### PR DESCRIPTION
**Pull request by thaystg**
Evaluate properties and generics.

image

### CODE REVIEW

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
Looks ok, not sure why that function is called decode_value ().

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Pull request merged**
