### PR TITLE
[2020-02] Optimize CopySymbolicHotkeys by adding file stamp heuristics

### PR DESCRIPTION
**Pull request by Therzok**
Fixes dev.azure.com/devdiv/DevDiv/_workitems/edit/1092021

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
Ready for review/merge.

**Comment by marek-safar** [comment]
@akoeplinger could you look into this?

**Comment by akoeplinger** [comment]
Manually bumped in 2020-02 with 4fdfb5b1 to avoid going through another round of CI.

**Pull request closed without merging**
