### PR TITLE
Prioritize gray queue to improve GC locality.

### PR DESCRIPTION
**Pull request by evincarofautumn**
I observed that many references are between objects within the same block. In an effort to improve memory locality during scanning, this splits the gray queue into two sections: high-priority and low-priority. References into the same block are enqueued with high priority; into other blocks, with low priority. High-priority objects are dequeued first.

[Benchmark results](https://drive.google.com/a/xamarin.com/file/d/0B9vUy441CSjgYW9lZUVqQmxKTms/view?usp=sharing) show speedups of 1–39% on ~12 benchmarks and slowdowns of 1–5% on ~6. Notably and unfortunately, Roslyn was one that experienced a slowdown, but F# got faster. :)

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by kumpera** [comment]
Your same block detection logic can be optimized. You don't need to find the boundaries to verify if two objects belongs to the same block.

Given all major blocks are aligned to their size you can check it by doing (a ^ b) > block_bits.

This is cheaper and allow you to verify if prioritizing the whole block is the right granularity of it's good only for, say 512 bytes chunks.

In your approach all objects on other blocks will go unsorted, did you check how bad that is?
Maybe that's something, if fixed could speed up even further.

Something along the lines of once the priority section is drained you pop one object from the regular queue and scan a few cache lines worth of gray queue for same block object, prefetch and move them to the priority queue.

**Comment by evincarofautumn** [comment]
I have been experimenting with this based on your feedback.

I tried refilling the high-priority section in a couple of different ways, but it generally resulted in a large slowdown. I also tried various granularities: ½, 1, 2, and 4 × the size of a block. It made no significant difference for the majority of benchmarks (a couple percent, mostly within error bars). So I tried playing with the block size (`MS_BLOCK_SIZE`).

It turns out that the majority of the speed improvements shown in the graph I posted were made by using a larger block size (64KiB vs. 16KiB). It seems that locality only contributes about 5% to this improvement in the faster cases, and about 5% to the slowdown in the slower cases. Not nothing, but not as dramatic as I thought. I don’t know if that change is acceptable—you did not comment on it before, but I did not call any special attention to it.

**Comment by schani** [comment]
We can definitely consider increasing the block size on desktop, but not on mobile.  We're using too much memory there as is.

I'm curious why Roslyn got slower.  Could you look into this?

**Comment by kumpera** [comment]
Did the fast block check I suggested helped?

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Pull request closed without merging**
