### PR TITLE
[eglib]: Fix memory leak in `g_find_program_in_path()`.  #11615.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by lewurm** [comment]
Also shows up in https://github.com/mono/mono/issues/12404

**Comment by baulig** [comment]
Just wanted to look at that one.

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins backport 2018-12

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Pull request merged**
