### PR TITLE
[CI] ignore appdomain-unload-asmload.exe on interp and full-aot

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by lewurm** [comment]
build interpreter

**Comment by akoeplinger** [comment]
could you please add it to the fullaot ignore list as well since it fails there too?

**Comment by lewurm** [comment]
build interpreter

**Comment by lewurm** [comment]
more failures on the interpreter lanes added up over the last days, will investigate and submit other PRs.

**Pull request merged**
