### PR TITLE
Basic ppc64 LE enablement

### PR DESCRIPTION
**Pull request by BillSeurer**
[ppc] These 3 small changes fix a floating point endian issue, activate some code for ppc64le, and turn off some tests that don't work (and never have worked) properly on ppc64.

### CODE REVIEW

**Comment by alexrp** [comment]
Changes look good to me. Minor point: Can you edit the commit messages to be prefixed with `[ppc]`?

**Comment by BillSeurer** [comment]
Do you want me to use "git rebase -i" because I believe it is too late for using "git commit --amend"?  From reading about it that can be iffy to do.

**Comment by alexrp** [comment]
Yes, rebase please. It's easy: `git rebase -i HEAD~3`, mark each commit as reword, fix them up, and force push to your branch.

**Comment by BillSeurer** [comment]
On 06/11/2015 12:43 AM, Alex Rønne Petersen wrote:
> Yes, rebase please. It's easy: |git rebase -i HEAD~3|, mark each commit
> as reword, fix them up, and force push to your branch.

OK, done.
-- 

-Bill Seurer

**Comment by akoeplinger** [comment]
@BillSeurer looks like you pushed the changes to the `ppc-floats` branch, can you close this PR and open a new one from that?

**Pull request closed without merging**
