### PR TITLE
[msbuild] Bump to pick up updates

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by radical** [comment]
@akoeplinger @alexischr How do I get to the build results from `build pkg`, given the PR# ?

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@radical It seems that it has not triggered, that hasn't happened to me before. I'll try again

**Comment by akoeplinger** [comment]
@radical it's available from the `OS X Package` status here on the PR but for some reason it didn't get triggered when Alexis did the comment.

**Comment by radical** [comment]
@akoeplinger the package build is complete now. Can you please merge this?

**Pull request merged**
