### PR TITLE
[interp] get context refactor

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins build OS X i386

**Comment by lewurm** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by luhenry** [comment]
Is that related to https://github.com/mono/mono/pull/10545?

**Comment by lewurm** [comment]
@luhenry not really. this PR was motivated after looking at the `ThreadContext` code for #10545

**Comment by lewurm** [comment]
@monojenkins backport 2018-08

**Pull request merged**
