### PR TITLE
[wasm][debugger] DebugDirectoryEntryType = Reproducible means that has debug information

### LINKED ISSUE #20075: [wasm][debugger] Cannot step into mscorlib methods
I tried to step into `DateTime.ToString()`, but it fails. The console says:

for `mscorlib.dll`:
```
debug_dir.type - 2
debug_dir.type - 16
```

and in `mono.js`, I get `hasPpdb == false`.  And it returns that from https://github.com/mono/mono/blob/master/mono/metadata/image.c#L1047 .

It fails to find ppdb for `netstandard.dll` too. Turning the `hasPpdb` check off, I can step into the method.

Reproduce with:
```
diff --git a/sdks/wasm/debug.html b/sdks/wasm/debug.html
index f16728b2301..8ee91ab10bd 100644
--- a/sdks/wasm/debug.html
+++ b/sdks/wasm/debug.html
@@ -15,12 +15,13 @@
                var App = {
                        onClick: function () {
                                this.output.value = "...";
-                               var res = this.int_add (10, 20);
+                               var res = this.int_add ();
                                this.output.value = "res is " + res;
                        },

                        init: function () {
-                               this.int_add = Module.mono_bind_static_method ("[sample] SampleMath:IntAdd");
+                               //this.int_add = Module.mono_bind_static_method ("[sample] SampleMath:IntAdd");
+                               this.int_add = Module.mono_bind_static_method ("[sample] DebuggerTests.ValueTypesTest:MethodWithLocalStructs");
                                this.output = document.getElementById ("output");
                                this.button = document.getElementById ("button");
```

.. and set a breakpoint on `tests/debugger/debugger-valuetypes-test.cs:MethodWithLocalStructs`, and try stepping-in when on `Console.WriteLine`.

### PR DESCRIPTION
**Pull request by thaystg**
Considering DebugDirectoryEntryType = Reproducible as an assembly that has debug information.

Fixes #20075

### CODE REVIEW

**Comment by radical** [comment]
@thaystg Could you add the test from https://github.com/mono/mono/issues/20075#issuecomment-654523016 in `sdks/wasm/DebuggerTestSuite/Tests.cs`, to go with this?

**Comment by thaystg** [comment]
> @thaystg Could you add the test from [#20075 (comment)](https://github.com/mono/mono/issues/20075#issuecomment-654523016) in `sdks/wasm/DebuggerTestSuite/Tests.cs`, to go with this?

Yes!

**Comment by thaystg** [comment]
@monojenkins build

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Pull request merged**
