### PR TITLE
Disabled Client certificate request on HttpListener

### PR DESCRIPTION
**Pull request by gusmanb**
Client certificate request was hardcoded, if this functionality has to be implemented must be configurable

Disabled by now.

### CODE REVIEW

**Comment by BrandonLWhite** [comment]
This is aggravating my customers as well.  I agree that ideally it needs to be configurable, but I think the default should be `false`.  I'm serving a simple status and configuration page from my application.
With the hardcoded value for requestClientCertificate being true, it causes an annoying and confounding pop-up whenever users try to access the page.  We've also discovered that on Android phones, it appears that users cannot even access the page if they do not have PIN-based or some other phone lock security enabled.

@migueldeicaza As I understand it, in Windows when you configure the SSL port via netsh, it must be storing additional configuration data (ie clientcertnegotiation=enable) that is later consulted by the SSL code (http.sys?).  Mono does not seem to have anything comparable since httpcfg only stores the SSL cert in /root/.config/.mono/httplistener with no opportunity for storing any additional configuration settings.

I would further argue that a hardcoded value of `false` would be more correct, since that is the behavior under Windows.  As I understand, unless you specifically set clientcertnegotiation=enable when performing netsh, then the default behavior is to **not** request the client's cert.  In lieu of a configurable setting, Mono should do the same.

I can think of 2 approaches Mono could take:

1.  Somehow expose this parameter up the layers to the calling code, which would of course be a Mono-specific interface.  I'm thinking this idea sucks.

2. Add a configuration file to hold this and other settings Mono is lacking vs. netsh.  This file would reside next to the .cer and .pvk files.  So for instance you'd have 443.cer, 443.pvk, and 443.json.  We could then add switches to HttpCfg for this and other missing settings (I'm assuming there's more -- could be wrong).  Then in the mono code, it would consult the config file to determine these options.

@migueldeicaza What do you think about the option 2?  Is there a more appropriate file format for this (XML, etc) that would be more consistent with other parts of Mono?

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by borrrden** [comment]
This is especially aggravating now that I've found out that HttpClient has no way of using client certificates to make its requests in mono (https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http.WebRequest/System.Net.Http.WebRequest/WebRequestHandler.cs#L83-L86).  So I can't set up the P2P scenario that I want to do.

**Comment by lewurm** [comment]
@gusmanb can you rebase (and squash) your changes, so your PR can run through our CI?

**Comment by gusmanb** [comment]
The code changed too much to use this patch.

I've reforked and updated the code to work with the new ssl implementation and created the pull request #2817

**Pull request closed without merging**
