### PR TITLE
fix merp arm64

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Not sure that 'arm64' is the expected string there in the crash log file.

**Review by lambdageek — APPROVED** [review]

**Review by imhameed — APPROVED** [review]

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
