### PR TITLE
[System.Data] Add stubs for Interop.NetSecurityNative

### PR DESCRIPTION
**Pull request by EgorBo**
fixes https://github.com/mono/mono/issues/6766
the real implementation will require additional dependencies on linux machines, see https://github.com/mono/mono/pull/6806 (for example libkrb5-3 on ubuntu or krb5-libs on CentOS)

### CODE REVIEW

**Comment by lewurm** [comment]
needs backport to `2017-12` and `2018-02`

**Comment by EgorBo** [comment]
@lewurm ok, I'll backport once it's merged to master

**Comment by luhenry** [comment]
@monojenkins backport to 2017-12

**Comment by luhenry** [comment]
@monojenkins backport to 2018-02

**Pull request merged**
