### PR TITLE
[wasm] AOT work.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by lewurm** [comment]
looks good? why the `do-not-merge` label?

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by luhenry** [comment]
@monojenkins commit csproj

**Comment by luhenry** [comment]
@vargaz why do we need https://github.com/mono/mono/pull/11444/commits/ed19b6eb6fbae9c5ba5d18b9fbfd2e69b9a5269e?

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
