### PR TITLE
Build BTLS on Windows, cygwin/mingw.

### PR DESCRIPTION
**Pull request by baulig**
Part of #8127

### CODE REVIEW

**Comment by filipnavara** [comment]
@monojenkins build Windows x64

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
Note that even if the build gets fixed it is still missing the Windows x86 changes. It should probably be fixed within one PR.

**Comment by filipnavara** [comment]
The build seems to fail because the non-CygWin CMake is given a CygWin path.

**Comment by marek-safar** [comment]
@lateralusX could you help with this?

**Comment by lateralusX** [comment]
I can take a look at this during the week. Another side note, maybe we should include a msvc build of BTLS since the msvc build is what's actually get's tested on Jenkins, not the cygwin build?

**Comment by directhex** [comment]
@lateralusX hopefully that's not too onerous - we have some understanding of mix-and-match of CMake & MSBuild now, from your work with LLVM

**Comment by lateralusX** [comment]
@baulig, @directhex Did some local experimentation around BTLS cygwin build. I believe the best way is to install cmake as part of the cygwin install and use the cygwin version when doing cygwin build. When doing BTLS VS build we should use Window installed cmake version. Ones cygwin cmake was installed the build completed on x64 Windows:

**Comment by lateralusX** [comment]
Pushed commit fixing btls cygwin x86, x64. NOTE this won't build on CI until build boots have cygwin cmake installed. I have updated the build documentation with that change,

https://github.com/mono/website/commit/bbb27729f216584e69a5cc496c757179360b91df#diff-6ff39b0903ab2de908c0926d1369c0e3

@akoeplinger Could we get cmake onto the jenkins Windows build boots?

**Comment by lateralusX** [comment]
Next step is to look at doing the VS build of BTLS as well, since all tests will run using the Visual Studio build mono and not the cygwin build.

**Comment by lateralusX** [comment]
Rebased on latest master. Build and validated cygwin/mingw build BTLS on both x86 and x64 Windows using simple TLS test. Verified that BTLS shared library gets loaded and that we get failures from BTLS provider when for example getting certificate validation errors.

**Comment by lateralusX** [comment]
Failures looks unrelated and occurs on multiple other builds. Approve/Merge?

**Comment by directhex** [comment]
Adding to the MSI is an assigned task for me & @joewstroman for this sprint.

**Comment by lateralusX** [comment]
@directhex, Right now, BTLS is not default for Windows builds unless you pass --enabled-btls to autogen.sh, so nothing will be build when using default build configs at the moment. Regarding the dllmap, I tried to fix the default naming and use mono-btls-shared in dllimport's since normally the mono loader will prefix module name with lib if it fails to load using regular name, but there where other errors related to the naming on some platforms. One option is to use libmono-btls-shared for Windows build as well, since we only include one build in the msi anyways (just the msvc build and not mingw builds), correct? Since cygwin/mingw build using libmono-btls-shared.dll I believe the best is to use the same naming on Windows build for this module as well to reduce additional complexity.

**Pull request merged**
