### PR TITLE
[runtime] Fix llvm arm autodetection / fix build

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by lewurm** [comment]
superseded by https://github.com/mono/mono/pull/11204 ?

**Comment by alexanderkyte** [comment]
Not quite, but I can merge them.

**Comment by lewurm** [comment]
@alexanderkyte you are right, I was confusing it. was is the status of this?

**Comment by lewurm** [comment]
I updated the PR. @alexanderkyte @vargaz please have another look. It's needed to make AOT with LLVM >=6.0 even work on ARM.

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
