### PR TITLE
[corlib] Make more crypto oids work on mobile profiles when not linke…

### PR DESCRIPTION
**Pull request by marek-safar**
…d out

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by filipnavara** [comment]
Is this fixing the CryptoConfig failures on the 2018-02 Xamarin.Mac branch?

**Comment by marek-safar** [comment]
Yes

**Pull request merged**
