### PR TITLE
[netcore] Enable Vector<T>.get_Item () intrinsics for floats/doubles.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by EgorBo** [comment]
Just for reference, accessing Vector's Item via const index: 
image
(boundexception is not possible here, but I guess LLVM will eliminate the one you emit anyway).

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
LLVM generates about the same code,  because it eliminates the switch we generate.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
