### PR TITLE
[runtime] cleanup around native crash info

### PR DESCRIPTION
**Pull request by lewurm**
Contributes to https://github.com/mono/mono/issues/12404

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by luhenry** [comment]
I understand where that's coming from, but I am doubting the usefulness of it. Isn't the only step afterwards to exit/abort the process?

**Comment by lewurm** [comment]
@luhenry yeah, it doesn't fix any real issue except that it makes leak reports (such as in #12404) less noisy.

**Comment by alexanderkyte** [comment]
```
4 warnings generated.
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini-wasm.c:532:1: error: redefinition of 'mono_init_native_crash_info'
mono_init_native_crash_info (void)
^
/mnt/jenkins/workspace/test-mono-pull-request-wasm/mono/mini/mini-wasm.c:526:1: note: previous definition is here
mono_init_native_crash_info (void)
^
```

@lewurm

**Pull request merged**
