### PR TITLE
Fix the System.String.Replace throwing NotImplementedException

### PR DESCRIPTION
**Pull request by MaximLipnin**
https://github.com/mono/mono/issues/20948

### CODE REVIEW

**Comment by marek-safar** [comment]
Please add/enable tests for this code path

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
@monojenkins build Linux i386

**Comment by akoeplinger** [comment]
@monojenkins whitelist

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
The failures are unrelated, merging.

**Pull request merged**
