### PR TITLE
[sdks] Build Android SDK on Windows

### PR DESCRIPTION
**Pull request by lambdageek**
Part of #14333 - make the `sdks/builds/` make infrastructure produce a Windows Android SDK zip.

**The goal of this PR is**: Produce a `android-release-Windows-nnnnnn.zip` file on the [Windows x64 Android SDK](https://jenkins.mono-project.com/job/xa/) CI lane, containing:
   1. an `android-bcl/monodroid/` directory, containing *something*
   2. an `android-host-mxe-Win64-release/` directory, containing *something*

**Not goals**:
  1. That the monodroid BCL is *reasonable*
  2. That the host-mxe-Win64 `mono.exe` is usable.

The non-goals will be addressed by other PRs.

### CODE REVIEW

**Comment by jaykrell** [comment]
Why not WSL? It is so much faster than Cygwin, if you can depend on Windows 10.
It is actual Linux usermode binaries, including fast fork.
If you need pre-Win10, then yeah.

**Comment by lambdageek** [comment]
Because the end result that we need is a binary archive of the windows Android SDK, not a Linux one.

**Comment by jaykrell** [comment]
Cygwin host or target? Target is just IL or native code or both? As host, WSL should be equivalent or better. 

Can even use make to run msvc tools.

Cygwin target can run on Windows, with runtime dependency.

**Comment by RUSshy** [comment]
You meant MinGW intead of WSL right ?

**Comment by jaykrell** [comment]
MinGW is a third choice of host and target though it is maybe the rarest target of the three, or is often equivalent to Win32 target, unless C runtime dependency extends to C99 or such.

**Comment by RUSshy** [comment]
I always thought MinGW was the most popular and recomanded solution since Cygwin is just emulating instead of doing native calls, even CLion on windows is using MinGW

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
Okay, I think this is ready for review.

**The goal of this PR is**: Produce a `android-release-Windows-nnnnnn.zip` file on the [Windows x64 Android SDK](https://jenkins.mono-project.com/job/xa/) CI lane, containing:
   1. an `android-bcl/monodroid/` directory, containing *something*
   2. an `android-host-mxe-Win64-release/` directory, containing *something*

**Not goals**:
  1. That the monodroid BCL is *reasonable*
  2. That the host-mxe-Win64 `mono.exe` is usable.

The non-goals will be addressed by other PRs.

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Comment by lambdageek** [comment]
@monojenkins build Windows x64 Android SDK

**Pull request merged**
