### PR TITLE
Bump bockbuild for Pango nil check fix.

### PR DESCRIPTION
**Pull request by bratsche**
Pango nil check fix.

### CODE REVIEW

**Comment by bratsche** [comment]
@monojenkins build pkg

**Comment by sevoku** [comment]
@akoeplinger can we backport this all the way down to 2019-10 / 6.8?

**Comment by marek-safar** [comment]
Please backport

**Comment by akoeplinger** [comment]
Backport was OK'd by Marek in Slack, did manual bockbuild backport+bumps in 2019-10 and later.

**Comment by sevoku** [comment]
Thanks!

**Pull request merged**
