### PR TITLE
[DONT MERGE] Moved some core functions to use MonoError.

### PR DESCRIPTION
**Pull request by kumpera**
This PR is just so we can benchmark it.

This PR is built on top of the gc api cleanup.

### CODE REVIEW

**Comment by kumpera** [comment]
WTF, hub just fucked up this PR.
I'll address John's issue and open a new one.

**Comment by kumpera** [comment]
builddeb

**Comment by lewurm** [comment]
looks like jenkins doesn't pick up the `builddeb` command for closed PRs?  @akoeplinger can you confirm that?

**Comment by akoeplinger** [comment]
@lewurm nah, I manually canceled the builds after rodrigo closed the PR to free some backlog

**Comment by lewurm** [comment]
oh, I see. thanks :)

**Pull request closed without merging**
