### PR TITLE
Add concurrent read version of MonoGHashTable and use it with MonoDomain::refobject

### PR DESCRIPTION
**Pull request by kumpera**
This improves reflection scalability, a bottleneck that XS is hitting.

Given this benchmark and my 4 cores laptop:

```
const int T_C = 4;
var list = new List<Thread> ();
bool done = false;
int count = 0;
for (int i = 0; i < T_C; ++i) {
	var t = new Thread(() => {
		while (!done) {
			typeof (Driver)
				.GetMethods (
					BindingFlags.Public | BindingFlags.NonPublic |
					BindingFlags.Instance | BindingFlags.Static);
			Interlocked.Increment (ref count);
		}
	});
	t.Start ();
	list.Add (t);
}

Thread.Sleep (5000);
done = true;
foreach (var t in list)
	t.Join ();
Console.WriteLine ("Got {0} lists done", count);
```

This change makes us go from 166.725 queries/s to 5.140.821 queries/s. Or 30x faster.

### CODE REVIEW

**Comment by Therzok** [comment]
Tentative patch to circumvent one appearance for this in XS https://github.com/mono/monodevelop/commit/5ebb91e93349ad321ef4649ec734ed0344d4512d, another in gtk#. The XamMac case still remains, but wow, this is amazing.

**Comment by vargaz** [comment]
We could get some improvement by splitting the locks among sre types or images.

**Comment by BrzVlad** [comment]
@kumpera Doesn't look sgen is made to account for the presence of the tombstone in the root. I'd assume there are no crashes because the hashtable is used only in the MONO_HASH_VALUE_GC mode.

**Comment by kumpera** [comment]
@vargaz for the workload in question splitting between sre and non-sre would have zero impact are there's virtually no SRE going on.

Splitting the locks means splitting the hashtable as well. Doing it per-image is complicated due to appdomains.

We could have a single hash per image and hash on method, class and domain. The issue with that is during unload we'd have to scrub all images to remove all reflection entries. Not particularly something I look forward doing.

This patch solves the reflection perf issue, which the per-image locking has no guarantee of doing at all.

**Comment by kumpera** [comment]
@BrzVlad we use a marker object as tombstone when the hashtable has object keys.

**Comment by vargaz** [comment]
Another approach, complicated as well, is to move these hashes to managed code.

**Comment by kumpera** [comment]
@vargaz how moving them to managed would help us here?

**Comment by vargaz** [comment]
Thats what .net does i think.

**Comment by kumpera** [comment]
I looked at dotnet, what they have are short lived (using weakrefs) per-type caches for all sorts of reflection queries. It's a lot of code that I'm not 100% sure on importing.

All that caching should help, but we'd still need to have the refobjects hash as you can't have multiple instances of MethodInfo around for the same method AFAICT.

**Comment by kumpera** [comment]
The OSX failures are completely unrelated.

The previous run didn't show them up and the only change after than was merging win32 build support.

**Pull request merged**
