### PR TITLE
[CREDSCAN] Replaced passwords with placeholder.

### PR DESCRIPTION
**Pull request by naricc**
Replacing passwords with placeholders.

I don't think the webassembly failure is related.

### CODE REVIEW

**Comment by SamMonoRT** [comment]
this looks good, open it up for review and merge it.

**Comment by naricc** [comment]
@monojenkins build failed

**Comment by SamMonoRT** [comment]
@naricc - I have seen the Linux WebAssembly name with "Build finished. No test results found" error in a few PRs so far. Don't let that block your PR

**Review by SamMonoRT — APPROVED** [review]

**Comment by SamMonoRT** [comment]
Please add this PR link in the actual issue and then Resolve as Fixed only once this is merged.

**Pull request merged**
