### PR TITLE
Revert mono_runtime_set_main_args in 44ff0597b835d0af62f526169dba3b365c9c3411.

### PR DESCRIPTION
**Pull request by jaykrell**
It breaks Xamarin.Android.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins backport 2019-08

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-10

**Comment by jaykrell** [comment]
I think https://github.com/mono/mono/pull/16149 is more the cause and this will still fail. I didn't confirm, granted.

**Comment by directhex** [comment]
@monojenkins build failed

**Pull request merged**
