### PR TITLE
2018 08 Suggestion for Linux and macOS - End of native executable files from (lib/mono/4.5 into /bin

### PR DESCRIPTION
**Pull request by sourceskyboxer**
Hello everyone, 
May I ask about my idea because I already tested with mkbundle and generates into end of native executable files
Example:
```
cd /lib/mono/4.5
sudo mkbundle --deps --static -z mkbundle.exe -o mkbundle -v
```
and I have tested ./mkbundle than it makes like working binaries
`sudo ./mkbundle --deps --static -z mcs.exe -o mcs -v`
Yay it works fine like real executable files.

Do you like end-of-native executables into /bin and we don't need worry.
If you don't like than you decide that. But I don't command you. Just I imagine about end-of-native executable files

PS: Sorry for Windows Users can't get because mkbundle generates only unix-like console - I think we need to add:
```
Type t = Type.GetType("Mono.Runtime");
if(t != null)
{
   ...
}
```
Is it possible not problematic for Windows executable files?
If it doesn't work than we let like normal version ( without end-of-native executable files )

I am sorry for bad English. If you don't understand.
I hope you have to accept my ideas for linux and macOS because both operating system have not problem and are unix-based.

Thanks and enjoy and next week start...

### CODE REVIEW

**Comment by baulig** [comment]
Accident or Troll?

**Comment by baulig** [comment]
You can preview your PR before submitting them and you should also be able to close your accidents by yourself.

**Comment by sourceskyboxer** [comment]
Hey @baulig oh who is troll? I am not troll. Just I am suggester. Why do you say me bad? What does it happen with you? I feel you fight me. Please do not say bad to me! I am innocent. I really help your development.

**Comment by baulig** [comment]
Well, I didn't want to be offensive to you in any way - and if you felt that anything I may have said or done to you was offensive then I would like to formally apologize to you.

However, you submitted a PR that was very obviously an accident.  It contained like 50 random commits - without even a single change from you.

So I was just wondering what your intentions behind this might have been.  Did you try to submit a question as a GitHub issue and by accident create a PR or did you intend to create a PR and then somehow picked random garbage?  And I tried to be helpful to you by explaining that you can review a PR before submitting it and - should you by accident submit a bad one - also close it yourself and ask for help.

If you have any questions or suggestions, then you are more than welcome to submit them via GitHub Issues or - if you have any actual code changes - Pull Requests.

However, this behavior that you just showed with your title change and that last comment is certainly not going to help you in the long run.  People make mistakes and we should try to have a professional attitude towards that rather than just getting annoyed like this.

**Comment by sourceskyboxer** [comment]
Okay it is ok.. I let that. I don't need give suggestions. I hold back Best regards for your team and develop more until your release. I want respect you. Thanks!

**Pull request closed without merging**
