### PR TITLE
[reflection] Divide reflection.c into multiple files. NFC

### PR DESCRIPTION
**Pull request by lambdageek**
Split up `reflection.c` (15 kLOC) into separate files.

1. `reflection.c` (3000 LOC): This retains `System.Type` and the interrogative `System.Reflection` APIs.
2. `sre.c` (5800 LOC): This contains the `System.Reflection.Emit` APIs to support running assemblies.
3. `sre-save.c` (3000 LOC): Support for saving assemblies to disk.
4. `sre-encode.c` (1200 LOC): common code for `sre.c` and `sre-save.c` for encoding builders into dynamic images, and token creation.
5. `custom-attrs.c` (1700 LOC): All about dealing with (encoding/decoding/loading/saving) custom attributes.
6. `dynamic-image.c` (500 LOC) low-level operations on a `MonoDymamicImage`
7. `dynamic-stream.c` (100 LOC) low-level operations on a `MonoDynamicStream`

### CODE REVIEW

**Comment by vargaz** [comment]
I think it would be better naming wise to leave the reflection stuff in reflection.c, and move the ref.emit stuff into a refemit.c or sre.c file.
Also, reflection-custom-attrs.c could be simply custom-attrs.c.

**Comment by lambdageek** [comment]
Yes, I agree.  But my first two tries at it weren't very successful.  They share a bit too many static helper functions to cleanly split.

**Comment by vargaz** [comment]
Without that, splitting out the dynamic image stuff is not very useful, its only used by sre.c.

**Comment by lambdageek** [comment]
This is better.  Only 5800 LOC in sre.c and 3000 LOC for sre-save.c

The only wart that I'm unsatisfied with is that I had to promote `alloc_table` to `mono_dynimage_alloc_table` because it's used by both sre and sre-save, but it's a really low-level function that really shouldn't be exposed.

Unfortunately all the code that writes to the `MonoDynamicImage` tables just accesses the arrays directly and is very very imperative without any helper functions, so I was afraid to accidentally change behavior - so I left it all alone.

**Comment by vargaz** [comment]
Looks ok. In theory, the encoding stuff is only needed for saving, but the current code does it for !save as well.

**Comment by lambdageek** [comment]
All the failed tests are the same as master.

**Comment by kumpera** [comment]
:tears-of-joy:

**Comment by akoeplinger** [comment]
@lambdageek this broke s390x: https://jenkins.mono-project.com/job/z/label=centos-s390x/3479/parsed_console/log_content.html#ERROR1:

```
sre-encode.c: In function ‘mono_dynimage_encode_constant’:
sre-encode.c:510:4: error: implicit declaration of function ‘swap_with_size’ [-Werror=implicit-function-declaration]
sre-encode.c:510:4: warning: nested extern declaration of ‘swap_with_size’ [-Wnested-externs]
sre-encode.c:531:2: error: implicit declaration of function ‘mono_image_add_stream_data’ [-Werror=implicit-function-declaration]
sre-encode.c:531:2: warning: nested extern declaration of ‘mono_image_add_stream_data’ [-Wnested-externs]
sre-encode.c: At top level:
cc1: warning: unrecognized command line option "-Wno-zero-length-array" [enabled by default]
cc1: some warnings being treated as errors
make[3]: *** [libmonoruntime_la-sre-encode.lo] Error 1
```

**Pull request merged**
