### PR TITLE
[sdks] Disable btls and support/ on the bcl build, they are not needed.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by marek-safar** [comment]
I believe this is not the case for Android. It'd be better to do it on per sdk level

**Comment by lewurm** [comment]
@marek-safar there is a separate target for android runtime build, btls should be covered by that I think

**Comment by marek-safar** [comment]
@luhenry how do you build monodroid profile then and why do we need https://github.com/mono/mono/blob/master/sdks/builds/bcl.mk#L13 ?

I think this change is wrong because it misconfigures monodroid profile

**Comment by vargaz** [comment]
This is wrong, it does change the bcl assemblies as well.

**Comment by luhenry** [comment]
@marek-safar Android have a `host-{Linux,Darwin}` which builds the BCL and they pick it from there.

**Pull request merged**
