### PR TITLE
[runtime] Don't add mono-dl.h to loader.h. Move the internal function to an internal header.

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Comment by kumpera** [comment]
@monojenkins merge

**Comment by vargaz** [comment]
mkbundle uses it, will that continue to work ?

**Comment by kumpera** [comment]
It's not the mkbundle that generates code that uses it.
The new call to mono_dl_open happens in mini/main.c

**Comment by ntherning** [comment]
Looks like this PR broke the Windows builds (https://jenkins.mono-project.com/job/x/1625/):

```
18:49:56   main.obj : error LNK2019: unresolved external symbol mono_dl_open referenced in function save_library [c:\j\workspace\x\msvc\mono.vcxproj]
18:49:56   main.obj : error LNK2019: unresolved external symbol mono_loader_register_module referenced in function save_library [c:\j\workspace\x\msvc\mono.vcxproj]
18:49:56   c:\j\workspace\x\msvc/./build/sgen/x64\bin\Release\mono-sgen.exe : fatal error LNK1120: 2 unresolved externals [c:\j\workspace\x\msvc\mono.vcxproj]
```

Please check the results of the PR builds before merging.

**Comment by ntherning** [comment]
I have pushed a temporary fix for this in #3964, just to get the Windows build working again.

**Pull request merged**
