### PR TITLE
[wasm][bcl] Handle correctly backslash in file name

### PR DESCRIPTION
**Pull request by kjpou1**
- Modify IO file to assign backslash to alternate directory separator by default
- Add tests for issue https://github.com/mono/mono/issues/18933

closes: https://github.com/mono/mono/issues/18933

### CODE REVIEW

**Comment by lewing** [comment]
I like that the scope of this is much more limited.

**Comment by kjpou1** [comment]
Current tests failing:

1) GetDirectories_Backslash (MonoTests.System.IO.DirectoryTest.GetDirectories_Backslash)
WASM:      #B2
WASM:   Expected string length 38 but was 34. Strings differ at index 34.
WASM:   Expected: "/tmp/MonoTests.System.IO.Tests/sub\\dir"
WASM:   But was:  "/tmp/MonoTests.System.IO.Tests/sub"
WASM:   ---------------------------------------------^
WASM: 
WASM:   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2b5e620 + 0x000ce> in <filename unknown>:0 
WASM: 
WASM: 
WASM: 2) GetFiles_Backslash (MonoTests.System.IO.DirectoryTest.GetFiles_Backslash)
WASM:    System.IO.DirectoryNotFoundException : Could not find a part of the path "/tmp/MonoTests.System.IO.Tests/doc/temp1.file".
WASM:   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2b5e620 + 0x000ce> in <filename unknown>:0 
WASM: 
WASM: 
WASM: 3) IsPathRooted (MonoTests.System.IO.PathTest.IsPathRooted)
WASM:      IsPathRooted #09
WASM:   Expected: True
WASM:   But was:  False
WASM: 
WASM:   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
WASM:   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2b5e620 + 0x000ce> in <filename unknown>:0

**Comment by kjpou1** [comment]
@monojenkins build OS X x64

**Comment by kjpou1** [comment]
@monojenkins build Linux ARMv7 Interpreter

**Comment by kjpou1** [comment]
@monojenkins build Windows x64 FullAOT

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Pull request merged**
