### PR TITLE
[runtime] Remove support for NaCl

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by ludovic-henry** [comment]
cc @kumpera @vargaz

**Comment by vargaz** [comment]
I'm not sure we want to completely remove support for nacl, somebody could resurrect the port. If that happens, the port should be bitcode based targeting pnacl.

**Comment by ludovic-henry** [comment]
@vargaz ok, so can we at least remove all the code which is architecture specific:
 - (amd64|x86|arm)-codegen.h
 - cpu-(amd64|x86|arm).md
 - exceptions-(amd64|x86|arm)
 - mini-(amd64|x86|arm).(c|h)
 - tramp-(amd64|x86|arm).c

**Comment by vargaz** [comment]
Probably, that code is probably bitrotten anyway.

**Comment by kumpera** [comment]
Yeah, lets remove only the code gen parts, as those are the more annoying ones.

**Comment by ludovic-henry** [comment]
@kumpera @vargaz: updated to only removed amd64/x86/arm specific code

**Comment by kumpera** [comment]
LGTM.

Could you look into removing the code from codeman as well? Since we're dropping codegen, we might as well do it on the platform independent parts of it.

**Comment by vargaz** [comment]
LGTM

**Comment by ludovic-henry** [comment]
@kumpera @vargaz: updated to also remove codeman code.

**Comment by vargaz** [comment]
LGTM

**Pull request merged**
