### PR TITLE
Fix mono_marshal_alloc to accept gsize instead of gulong(unsigned long)

### PR DESCRIPTION
**Pull request by mderoy**

### CODE REVIEW

**Comment by vargaz** [comment]
Need to modify marshal.h as well.

**Comment by mderoy** [comment]
@vargaz oops can't believe I forgot that 0_o fixed now

**Comment by vargaz** [comment]
build

**Comment by joncham** [comment]
Can you fix ves_icall_marshal_alloc as well?

**Comment by mderoy** [comment]
@joncham This was updated in a separate PR that has been merged :)

@vargaz could we rerun these tests?
looks like there was an issue with the Linux test system at the time these were run.

**Comment by vargaz** [comment]
build

**Pull request merged**
