### PR TITLE
Add missing switch and functionality to al.

### PR DESCRIPTION
**Pull request by david-mitchell**
When running msbuild on mono against an architecture-specific
project that also defines satellite assemblies, the /platform
switch will be passed to al.exe. Mono's implementation of al.exe
does not support this switch, which results in a failed build.

This commit adds the /platform switch, which also required
changing the implementation from System.Reflection to
IKVM.Reflection because Mono's implementation of AssemblyBuilder
does not support the necessary options.

While testing this change, I also noticed a few attributes that
the MS version of al.exe will copy from "template" assemblies,
so I added support for those, as well.

### CODE REVIEW

**Comment by marek-safar** [comment]
approve

**Comment by marek-safar** [comment]
There is still at least one Type ambiguity

**Comment by david-mitchell** [comment]
@marek-safar Fixed.

**Comment by david-mitchell** [comment]
The Windows x64 build failed because of a failed git operation, while Linux x64 FulAOT appears to be failing because of unrelated tests.

**Comment by david-mitchell** [comment]
@marek-safar thanks for merging it!

Do you have any notion of how long it might take for this to find its way into an official release?

**Comment by marek-safar** [comment]
I'll show up in the next release after mono 4.6 (probably 4.8)

**Comment by DavidACL** [comment]
@david-mitchell does this PR address this bug https://bugzilla.xamarin.com/show_bug.cgi?id=12671, and possibly the main issue outlined in this example repo:  https://github.com/DavidACL/SatelliteAssemblyCustomAttributesIssue/tree/master

Seems like it would. Thanks.

**Comment by david-mitchell** [comment]
@DavidACL, the PR does not affect any xbuild behavior; it only adds functionality to al that was necessary as I attempted to use msbuild on Mono/Mac to build a project that was originally created in Windows.

**Pull request merged**
