### PR TITLE
Fixing on WriteContentType when extension is empty.

### PR DESCRIPTION
**Pull request by hharyono**
When I create package the result should be like Windows result. Linux Result is not correct.
So to correct it, I added a condition in the code.

xml result

### CODE REVIEW

**Comment by marek-safar** [comment]
Could you add a test for the fix?

**Comment by marek-safar** [comment]
build

**Comment by marek-safar** [comment]
@monojenkins build

**Comment by luhenry** [comment]
@monojenkins build

**Comment by luhenry** [comment]
@marek-safar could you check if the failures are related and relevant?

**Comment by akoeplinger** [comment]
The original fix commit is the same and the added test is mine so we should be fine with the original cla-not-required.

**Comment by akoeplinger** [comment]
@monojenkins build

**Pull request merged**
