### PR TITLE
Initial CMAKE build system support.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Currently, only netcore on osx works.
cmake -DENABLE_NETCORE=1 -G Ninja . -> 18secs.
ninja -> 11 secs.
In debug mode.

**Comment by akoeplinger** [comment]
We're gonna hold off on this experiment until we're in dotnet/runtime.

**Comment by vargaz** [comment]
https://github.com/dotnet/runtime/pull/2108

**Pull request closed without merging**
