### PR TITLE
[System]: Fix another `SocketAsyncEventArgs` issue for #8871.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build Linux AArch64

**Comment by akoeplinger** [comment]
@baulig to which branches do we need to backport this?

**Comment by baulig** [comment]
Hmm, so far nobody has complained about this - it's mostly for the upcoming HttpClient import.

**Comment by akoeplinger** [comment]
well if we know it fixes an issue then we should backport it, at least to the recent branches ;)

@monojenkins backport to 2018-06

**Comment by akoeplinger** [comment]
@monojenkins backport to 2018-04

**Pull request merged**
