### PR TITLE
[msbuild] Bump for building Razor projects w/ dotnet 3.0x preview4

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X package

**Comment by radical** [comment]
```
15:34:18  Making install in libtiff
15:34:18   ../config/install-sh -c -d '@/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/5.18.1/lib'
15:34:18   /bin/sh ../libtool   --mode=install /usr/bin/install -c   libtiff.la libtiffxx.la '@/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/5.18.1/lib'
15:34:18  libtool: install: /usr/bin/install -c .libs/libtiff.5.dylib @/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/libtiff.5.dylib
15:34:18  libtool: install: (cd @/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/5.18.1/lib && { ln -s -f libtiff.5.dylib libtiff.dylib || { rm -f libtiff.dylib && ln -s libtiff.5.dylib libtiff.dylib; }; })
15:34:18  libtool: install: /usr/bin/install -c .libs/libtiff.lai @/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/libtiff.la
15:34:18  install: .libs/libtiff.lai: No such file or directory
```

**Comment by radical** [comment]
@monojenkins build OS X package

**Comment by radical** [comment]
Unrelated failing tests:
```
RemotingServicesTest.Bug46473
MonoTests.runtime.stackframes-async.2.exe
MonoTests.test-unhandled-exception-2-255-without-managed-handler.unhandled-exception-3.exe
MonoTests.runtime.threadpool-exceptions7.exe
```

**Comment by rodrmoya** [comment]
Just for the record, tested this build and indeed fixes the issue for me

**Comment by radical** [comment]
@akoeplinger Could you please review+approve this?

**Pull request merged**
