### PR TITLE
[jit] Fix is_reference checks for intrinsics with byref parameters.

### PR DESCRIPTION
**Pull request by vargaz**
Found by https://github.com/mono/mono/issues/17335.

### CODE REVIEW

**Comment by lambdageek** [comment]
@vargaz, can you change the commit message to say "Found in #17335". I don't want to auto-close the issue. Better to keep it open until we get an updated benchmark run.

**Comment by lambdageek** [comment]
Assert on `intrinsics.c:1241` needs to handle byref args, too:
`g_assert (mini_type_is_reference (fsig->params [0]));`

**Comment by vargaz** [comment]
Fixed.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-10

Given the perf improvements from this intrinsic, I wonder if it's worth backporting to 2019-08, too

**Comment by marek-safar** [comment]
@monojenkins backport to 2019-08

**Pull request merged**
