### PR TITLE
Add gitter badge.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, I don't like the placement of the badge, we should move it somewhere else. Maybe right after the first paragraph, before the TOC?

**Comment by Therzok** [comment]
Yeah, I didn't like the placement either, but I couldn't find a nice place to place it.

**Comment by Therzok** [comment]
How's it now?

**Comment by akoeplinger** [comment]
That looks much better :+1:

**Pull request merged**
