### PR TITLE
configure/makefile To support updating zlib to 1.2.11.

### PR DESCRIPTION
**Pull request by jaykrell**
Extracted from https://github.com/mono/mono/pull/15480 for perhaps more readable history.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux WebAssembly
@monojenkins build Linux x64 - prefix sanity checks
@monojenkins build Linux x64 All Profiles Build
@monojenkins build Linux x64 Checked Private Types Build
@monojenkins build Linux x64 FullAOT
@monojenkins build Linux x64 FullAOT+Interpreter
@monojenkins build Linux x64 FullAOT+Interpreter+LLVM

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux WebAssembly
@monojenkins build Linux x64 - prefix sanity checks
@monojenkins build Linux x64 All Profiles Build
@monojenkins build Linux x64 Checked Private Types Build
@monojenkins build Linux x64 FullAOT
@monojenkins build Linux x64 FullAOT+Interpreter
@monojenkins build Linux x64 FullAOT+Interpreter+LLVM

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux WebAssembly

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 - prefix sanity checks

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 All Profiles Build

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 Checked Private Types Build

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 FullAOT

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter

**Comment by CoffeeFlux** [comment]
@monojenkins build Linux x64 FullAOT+Interpreter+LLVM

**Pull request merged**
