### PR TITLE
[corlib]: Bring SafePasswordHandle from CoreFX.

### PR DESCRIPTION
**Pull request by baulig**
Part of #9416

### CODE REVIEW

**Comment by filipnavara** [comment]
The build failure is because of the CoreFX bump. Fix here:
https://github.com/mono/mono/pull/9250/commits/5aa106c957a8b075c952d29194147e20c0b959a8

**Comment by filipnavara** [comment]
Spoke too soon, the fix is not that easy. Anyway, it is caused by unrelated change in CoreFX :-/

**Comment by filipnavara** [comment]
Rebase should fix it now :-)

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by baulig** [comment]
I rebased on latest master to solve the merge conflicts.

**Comment by baulig** [comment]
@monojenkins build failed

**Pull request merged**
