### PR TITLE
Add System.Buffers facade to framework assemblies list

### PR DESCRIPTION
**Pull request by akoeplinger**
It's a new facade added in https://github.com/mono/mono/pull/10571

### CODE REVIEW

**Comment by marek-safar** [comment]
I am not sure we should do it, it required non-facade handling for !MOBILE

**Comment by akoeplinger** [comment]
It won't have an effect if said assembly isn't part of the shipped framework facades, I checked this with @lambdageek when I did https://github.com/mono/mono/pull/10214.

**Comment by marek-safar** [comment]
Why do we need it then? Mobile does not have GAC so it's no-op there as well

**Comment by akoeplinger** [comment]
Because we'll forget to add it to this list once we enable it for !MOBILE in a few months down the road :)

**Pull request closed without merging**
