### PR TITLE
[corlib] Two small fixes for GCHandle

### PR DESCRIPTION
**Pull request by akoeplinger**
1) Free() throws on MS.NET when the handle was already freed, copied and adapted the referencesource implementation.

2) Explicit conversion from IntPtr to GCHandle throws InvalidOperationException when value is IntPtr.Zero on MS.NET, not ArgumentException.

This fixes two failing CoreCLR test cases.

### CODE REVIEW

**Comment by kumpera** [comment]
LGTM

How hard would it be for us to move to the RS implementation here?

**Comment by kumpera** [comment]
@monojenkins  merge

**Comment by marek-safar** [comment]
We should switch to RS code. It looks quite easy in this case

**Comment by akoeplinger** [comment]
Yeah, this was just a low-hanging fruit I saw when looking at the failing CoreCLR tests.

**Pull request merged**
