### PR TITLE
 [llvm] emit call to mini_llvmonly_throw_nullref_exception without exceptions in mind

### PR DESCRIPTION
**Pull request by lewurm**
Fixes https://github.com/mono/mono/issues/14243

### CODE REVIEW

**Comment by jeromelaban** [comment]
This change is going to be a problem, as it will prevent the compilation of AOT modules for wasm. Can that be configurable ? The BCL contains a lot of those.

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-06

**Comment by lewurm** [comment]
Some background on why this is happening now:
```
(lldb) mbt
* thread #1
  * frame #0: 0x001ad5b1 armv7k-unknown-darwin-mono-sgen`emit_call(ctx=0x06b2d8b0, bb=0x05208938, builder_ref=0xbfffe1ac, callee=0x033c1d00, args=0x00000000, pindex=0) at mini-llvm.c:2115:18
    frame #1: 0x001aaa5e armv7k-unknown-darwin-mono-sgen`mono_llvm_emit_method(cfg=0x05204600) at mini-llvm.c:7601:5
    frame #2: 0x0000bec8 armv7k-unknown-darwin-mono-sgen`mini_method_compile(method=0x01051ae8, opts=391195135, domain=0x00c0aa20, flags=238, parts=0, aot_method_index=3326) at mini.c:3821:4
    frame #3: 0x00107d9f armv7k-unknown-darwin-mono-sgen`compile_method(acfg=0x01013200, method=0x01051ae8) at aot-compiler.c:8481:8
    frame #4: 0x000fb244 armv7k-unknown-darwin-mono-sgen`compile_methods(acfg=0x01013200) at aot-compiler.c:11863:3
    frame #5: 0x000f6da6 armv7k-unknown-darwin-mono-sgen`mono_compile_assembly(ass=0x00c1c3f0, opts=374417919, aot_options="mtriple=armv7k-ios,data-outfile=System.aotdata.armv7k,static,asmonly,direct-icalls,llvmonly,nodebug,dwarfdebug,direct-pinvoke,msym-dir=System.mSYM,llvm-path=llvm,llvm-outfile=System.dll.bc", global_aot_state=0xbfffe96c) at aot-compiler.c:13567:2
    frame #6: 0x000ec8e4 armv7k-unknown-darwin-mono-sgen`main_thread_handler(user_data=0xbfffed20) at driver.c:1371:10
    frame #7: 0x000e26ec armv7k-unknown-darwin-mono-sgen`mono_main(argc=6, argv=0xbfffedd4) at driver.c:2616:3
    frame #8: 0x00002937 armv7k-unknown-darwin-mono-sgen`mono_main_with_options(argc=6, argv=0xbfffedd4) at main.c:50:9
    frame #9: 0x00001d40 armv7k-unknown-darwin-mono-sgen`main(argc=6, argv=0xbfffedd4) at main.c:408:9
    frame #10: 0xa7abb051 libdyld.dylib`start + 1
```
Although we check for filter clauses here:
https://github.com/mono/mono/blob/2e4b6b34ac1ac51a10410067af9761fff09a11b6/mono/mini/mini-llvm.c#L7754-L7761
We end up here _specifically_ because compilation failed:
https://github.com/mono/mono/blob/2e4b6b34ac1ac51a10410067af9761fff09a11b6/mono/mini/mini-llvm.c#L7596-L7599
which was added by 605ea1555cef

**Comment by vargaz** [comment]
Should probably be be changed to a LLVMBuildCall (builder, callee, args, pindex, "");

**Comment by lewurm** [comment]
@vargaz thanks, updated PR

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
@monojenkins backport 2019-06

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
I can confirm this fixes the issue in xamarin-macios 👍

**Pull request merged**
