### PR TITLE
Remove ChangeLog files from the repo

### PR DESCRIPTION
**Pull request by akoeplinger**
They weren't updated in the last 6 years and aren't helpful anymore (e.g. by causing unrelated matches during git grep searches). We already have the history in git.

RFC: mainly opening this to see if anyone objects :smile: Thoughts?

### CODE REVIEW

**Comment by vargaz** [comment]
We kept them for sentimental value.

**Comment by akoeplinger** [comment]
At some point, you just have to let go :wink:

**Comment by tritao** [comment]
LGTM, they usually get in the way when doing global searches.

**Comment by kumpera** [comment]
Think of all the :heart: spent writing those ChangeLogs.

**Comment by akoeplinger** [comment]
It's all preserved in `git log` :sparkling_heart:

**Comment by alexrp** [comment]
+1, they are kinda annoying when grepping the repo.

**Comment by akoeplinger** [comment]
Given that no one objected, I'm merging this. Farewell ChangeLogs :wave:

**Pull request merged**
