### PR TITLE
[llvm] Avoid decomposing OP_STOREV_MEMBASE early for types which contains no references.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Fixes something? Is faster?

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins backport 2019-12

**Pull request merged**
