### PR TITLE
[WIP][build] Skip sgen stress tests unless requested

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@akoeplinger @duncanmak 
Let's see how long this build takes

**Comment by vargaz** [comment]
LGTM

**Comment by akoeplinger** [comment]
@kumpera trying to see how much time spinning off those tests into a separate lane saves us, to make PR builds faster.

**Comment by akoeplinger** [comment]
@alexanderkyte this one is another long running test:

```
sgen-new-threads-dont-join-stw.exe passed, time: 03:05.152
```

**Comment by vargaz** [comment]
These tests take 50% of the total build time, i.e. more than the whole bcl testsuite.

**Comment by akoeplinger** [comment]
Ok so this shaves off about 50mins on arm64 and 30mins on amd64, so this does seem valuable.

Instead of creating another lane (and all the complications that brings) we could also make the stress tests opt-out and turn them off only on PR builds. What do you think?

**Comment by vargaz** [comment]
I think we should just disable them. We can't have tests which take the same time as the rest of the build/test suite.

**Comment by kumpera** [comment]
How about making them do less work instead of disabling?

GC tests are slow by nature and just simply not having them is shooting
ourselves in our feet.

**Comment by akoeplinger** [comment]
I'm definitely against simply disabling them everywhere. Personally I don't care if the mainline tests on Wrench/Jenkins take an hour longer (we can just throw more machines at them), but for PRs the reality is that most won't impact the GC so opting out of the stress tests there seems the most sensible solution to me.

I don't know how much work it is to make the tests faster without impacting their validity, but from my POV this doesn't seem like a good use of time when we can get the same benefits by just moving these four tests into an opt-out mechanism we use for PRs.

**Comment by alexanderkyte** [comment]
I'm not sure it makes sense to make a stress test do less work. Creating excessive memory traffic will be slow no matter what you do. I think it might be better to run the tests less frequently than to make them less valuable. Anything that a 1-minute sgen stress test can catch can probably be caught by the rest of the test harness.

**Comment by BrzVlad** [comment]
As a middle solution, we could also just run fewer configs for those tests. I think running the plain (which btw should be converted to serial) and conc configs should be enough. That would reduce the time for sgen tests by 4.

**Comment by akoeplinger** [comment]
Closing, we pretty much did this with https://github.com/mono/mono/pull/4653.

**Pull request closed without merging**
