### PR TITLE
Support more oids: aes128, aes256, sha256, sha512

### PR DESCRIPTION
**Pull request by knguyen0928**

### CODE REVIEW

**Comment by tritao** [comment]
Do you mind extending/adding a test that covers these?

**Comment by tritao** [comment]
build

**Comment by akoeplinger** [comment]
@tritao you didn't make your membership in the Mono org public on GitHub, so the Jenkins plugin doesn't recognize you.

**Comment by tritao** [comment]
How do I make it public? I was searching through Github settings but could not find anything.

**Comment by akoeplinger** [comment]
@tritao Go to https://github.com/orgs/mono/people and search for yourself, then use the dropdown.

**Comment by knguyen0928** [comment]
@tritao tests are added. The original tests are missing parsing oid from default ctor and setting FriendlyName. Without these tests, you can change code in "private string GetValue (string name)" to return bogus in the switch statement. For example:

			switch (name) {
				case nameRSA:
					return "a";

and the tests won't catch it.

**Comment by akoeplinger** [comment]
build

**Pull request merged**
