### PR TITLE
[2018-02] Finalize merp integration

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@sgmunn the package on this lane should be the one to test for integration for VS4Mac I believe

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by alexanderkyte** [comment]
https://jenkins.mono-project.com/job/build-package-osx-mono-pullrequest/134/

**Comment by luhenry** [comment]
Is this backport of https://github.com/mono/mono/pull/8694 really required?

**Pull request merged**
