### PR TITLE
Remove C5.

### PR DESCRIPTION
**Pull request by txdv**
The C5 library is not used internally in the mono repository.
No build step depends on this library. It is more feasible to
let the user download the library via nuget or get the source
code from the official github repository https://github.com/sestoft/C5/

### CODE REVIEW

**Comment by txdv** [comment]
I already signed it once?

**Comment by alexrp** [comment]
@marek-safar are you OK with this?

**Comment by marek-safar** [comment]
I am ok bit @migueldeicaza was the one who wanted to keep it in the past

**Comment by migueldeicaza** [comment]
I am not ok with this.

This code is a great test bed for generics code.

**Comment by migueldeicaza** [comment]
I am open to not installing the library though.

**Comment by akoeplinger** [comment]
@migueldeicaza if we keep it for testing, I'd prefer if we pull in the official C5 repo via a submodule rather than keeping our fork.

**Comment by txdv** [comment]
@migueldeicaza I can try to do what @akoeplinger suggested, if that is ok with you.

There are no tests being run with C5, so I guess the testing happens when the library is being compiled?

**Comment by akoeplinger** [comment]
@txdv Running "make check" in mcs/class/Mono.C5 runs the unit tests just like for every other assembly.

**Pull request closed without merging**
