### PR TITLE
Make PR package with jemalloc enabled

### PR DESCRIPTION
**Pull request by alexanderkyte**
@monojenkins skip

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins skip

**Comment by alexanderkyte** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
```

src/prof.c:2135:10: error: returning 'const char [1]' from a function with result type 'char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
23:44:54                 return "";
23:44:54                        ^~
23:44:54 1 error generated.
23:44:54 
make[6]: *** [src/prof.sym.o] Error 1
23:44:54 make[6]: *** Waiting for unfinished jobs....
23:44:54 5 warnings generated.
23:44:54 src/stats.c:106:22: error: initializing 'char *' with an expression of type 'const char [15]' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
23:44:54         char *fmt_str[2] = {"%s\t\"%s\": %"FMTu32"%s\n",
23:44:54                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
23:44:54 src/stats.c:107:6: error: initializing 'char *' with an expression of type 'const char [17]' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
23:44:54             "%s\t\"%s\": %"FMTu64"%s\n"};
23:44:54             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
23:44:54 src/stats.c:133:9: error: initializing 'char *' with an expression of type 'const char [69]' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
23:44:54                 char *mutex_counters = "   n_lock_ops    n_waiting"
23:44:54                       ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
23:44:54 src/stats.c:360:22: error: initializing 'char *' with an expression of type 'const char [5]' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
23:44:54         char *fmt_str[2] = {"%12"FMTu32, "%16"FMTu64};
23:44:54                             ^~~~~~~~~~~
23:44:54 src/stats.c:360:35: error: initializing 'char *' with an expression of type 'const char [7]' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
23:44:54         char *fmt_str[2] = {"%12"FMTu32, "%16"FMTu64};
23:44:54                                          ^~~~~~~~~~~
```

failed?

**Comment by alexanderkyte** [comment]
Hmm, that shouldn't be running with `-Werror`

**Comment by Therzok** [comment]
Can we rebase this and get a pkg so I can test it out?

**Pull request closed without merging**
