### PR TITLE
Update denied assemblies list

### PR DESCRIPTION
**Pull request by radical**
Updating the denied lists for:

- `System.Text.Encoding.CodePages` versions `4.5.0` and `4.5.1`
- `System.Net.Http` versions `4.3.4`

Other packages are already up-to-date.

Fixes https://github.com/mono/mono/issues/12603 .

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Comment by radical** [comment]
bockbuild is breaking for gtk-sharp and needs this https://github.com/mono/bockbuild/pull/87 .

**Comment by radical** [comment]
Waiting for the bump in bockbuild instead - https://github.com/mono/bockbuild/pull/88 .

**Comment by radical** [comment]
Waiting on bockbuild bump to get the fixes - https://github.com/mono/mono/pull/13108 .

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
Blocked on https://github.com/mono/mono/pull/13109 .

**Comment by radical** [comment]
All the failing tests have nothing to do with this PR. Details below. @akoeplinger @marek-safar Could you please merge this PR?

`Linux ARMv7`, `Linux AArch64 Coop Suspend`, `Linux ARMv7`:
```
HttpWebRequestTest.Sync
WebClientTest.DownloadTwice
```

`Linux AArch64 FullAOT`:
`/../../class/lib/testing_aot_full/tests/testing_aot_full_System_test.dll.testing_aot_full_System_test.dll.crash`

`Linux AArch64 Interpreter:
```
10:33:22 Errors and Failures:
10:33:22 
10:33:22 1) DownloadTwice (MonoTests.System.Net.WebClientTest.DownloadTwice)
10:33:22    System.Net.WebException : The remote server returned an error: (503) Service Unavailable.
10:33:22   at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/mcs/class/System/System.Net/HttpWebRequest.cs:1101 
10:33:22   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000e8] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/mcs/class/System/System.Net/HttpWebRequest.cs:956 
10:33:22   at System.Net.HttpWebRequest.GetResponse () [0x0000f] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/mcs/class/System/System.Net/HttpWebRequest.cs:1218 
10:33:22   at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:249 
10:33:22   at System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream) [0x000e6] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:850 
10:33:22   at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x00088] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:329 
10:33:22   at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00000] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:308 
10:33:22   at MonoTests.System.Net.WebClientTest.DownloadTwice () [0x0000b] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/mcs/class/System/Test/System.Net/WebClientTest.cs:38 
10:33:22   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
10:33:22   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in /home/builder/jenkins/workspace/test-mono-pull-request-interpreter-aarch64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:391 
10:33:22 
10:33:22 
10:33:22 Flaky Test Retries:
10:33:22 
10:33:22 FAIL (0 passes/5 fails): DownloadTwice (MonoTests.System.Net.WebClientTest.DownloadTwice)
```

**Comment by radical** [comment]
@marek-safar Does this need to be backported to any other branches?

**Comment by marek-safar** [comment]
@radical no

**Pull request merged**
