### PR TITLE
[debugger] Update client thread frames after SetIP.

### LINKED ISSUE #13408: [sdb] SetIP requires a resume/suspend to update client thread frames
See attached repro:

[reprosdb3.zip](https://github.com/mono/mono/files/2954674/reprosdb3.zip)

`build.sh && mono debugger.exe`

After a SetIP, we'd like to have the thread frames invalidated and the top frame pointing to the newly set IP where the execution will resume. This will avoid either storing the next IL offset or using a hidden breakpoint and resume to it to properly display the new location in the IDE.

### PR DESCRIPTION
**Pull request by thaystg**
PR of draft https://github.com/mono/mono/pull/14667

Fixes #13408

### CODE REVIEW

**Comment by vargaz** [comment]
Looks ok, but wondering whenever this is a good idea. The ip will point to one location, but the locals etc. will correspond to another location.

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by jbevain** [comment]
@vargaz isn't it the desired behavior here? For our scenario:

1) You stop at a breakpoint at offset `A`
2) The variables you see are at the time of `A`
3) You tell the IDE that you'll resume from offset `B`
4) The IDE shows you that the thread is now positioned at offset B with variables having values as set at `A`.

It feels like it works for our use case.

The problem right now is that we have to handle the «set next statement» by either creating a fake breakpoint and doing a resume, another possibility would be to special case the current IP for a thread which is what MD does, but is annoying to implement.

**Comment by jbevain** [comment]
@thaystg as far as I'm concerned, I'm OK with this.

**Comment by thaystg** [comment]
@monojenkins build failed

**Pull request merged**
