### PR TITLE
Optimize `box+isinst+brtrue`

### PR DESCRIPTION
**Pull request by EgorBo**
This pattern shows up here is there (and it's optimized in CoreCLR too, see [here](https://github.com/dotnet/runtime/blob/5c9338e09ad0a2f282c3dd14b0cc06aab37887a0/src/coreclr/src/jit/importer.cpp#L5905))

```csharp
bool Test<T>(T obj)
{
    if (obj is int)
        return 42;
    return 0;
}
```
Was:
```asm
   0:   53                      push   %rbx
   1:   89 fb                   mov    %edi,%ebx
   3:   48 b8 e0 dd a8 01 00    movabs $0x1a8dde0,%rax
   a:   00 00 00
   d:   bf 90 0a ce 01          mov    $0x1ce0a90,%edi
  12:   be 14 00 00 00          mov    $0x14,%esi
  17:   ff 10                   callq  *(%rax)
  19:   89 58 10                mov    %ebx,0x10(%rax)
  1c:   48 8b 00                mov    (%rax),%rax
  1f:   31 c9                   xor    %ecx,%ecx
  21:   48 81 38 08 f9 8a 01    cmpq   $0x18af908,(%rax)
  28:   b8 2a 00 00 00          mov    $0x2a,%eax
  2d:   0f 45 c1                cmovne %ecx,%eax
  30:   5b                      pop    %rbx
  31:   c3                      retq
```
Now:
```asm
   0:   b8 2a 00 00 00          mov    $0x2a,%eax  ;; return 42;
   5:   c3                      retq
```
TODO: There are more patterns to optimize involved in C# 6-8 pattern matching, e.g.:
see [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAGAAgGUALAQygAcAZa4AOgCUBXAOw2wFsYAbgCwAKDGEAjElKEATLMkB2MQG8xpTaQDaAKWwYA4jC4wo2MAAoMATzowIAM0vYeASjcBdDVqkzXGKQAKjAAzhiSADxBAHyWQaQQwABWbj6a6qJa2aTYjqSWScm5obnu6TnZhEqkKHIiWZWyNcQN2QC+YhV6Bsam5la29k4u7l4VfmWBIeFy0XEJRWmNGRXZeQVFJVOkCMtNOdW7bU1HrRWdou1AA===)

### CODE REVIEW

**Comment by EgorBo** [comment]
Accidentally pressed `Create PR`, still WIP, need to figure out the edge cases (generics, gsharedvt, optimize `brfalse/brtrue)

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
Is the compiled code for `T = int`? Otherwise it doesn't make sense to me

**Comment by EgorBo** [comment]
@lewurm yes `Test<int>`, forgot to mention.

**Comment by EgorBo** [comment]
will open in dotnet/runtime with changes

**Pull request closed without merging**
