### PR TITLE
[Test] Reenable HttpRequestIgnoreBadCookies in monotouch.

### PR DESCRIPTION
**Pull request by mandel-macaque**
The test was ran in the current xamarin-macions and works as expected. Closes bug https://bugzilla.xamarin.com/show_bug.cgi?id=60542

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@mandel-macaque do you need a backport for this?

**Comment by mandel-macaque** [comment]
yes! is there a bot that does this, right?

**Comment by akoeplinger** [comment]
yep. which branches do you need it in? 2017-12 and up ?

**Comment by akoeplinger** [comment]
@monojenkins backport to 2017-02

**Comment by akoeplinger** [comment]
@monojenkins backport to 2018-02

**Comment by akoeplinger** [comment]
@monojenkins backport 2017-12

**Pull request merged**
