### PR TITLE
[System] Disable few tests which blocks when run on main loop

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Comment by akoeplinger** [comment]
fyi I've marked Jenkins for shutdown to reboot it so it will take some time for builds (and backport) to show up.

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Pull request merged**
