### PR TITLE
Native code frequently fails to honor the definitely-write semantics of out parameters, so use ref instead.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build OS X i386

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64

**Comment by jaykrell** [comment]
@monojenkins buid Linux AArch64

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64

**Comment by lewurm** [comment]
does that fix a specific failure?

**Comment by jaykrell** [comment]
We should just never have this incorrectness or fragility. It is kinda a safety violation.

**Comment by akoeplinger** [comment]
shouldn't we rather fix the native code to make sure it always writes a value into the parameters?

**Comment by jaykrell** [comment]
Fixing native side is ok. Resulting efficiency is essentially identical. I’d prefer to discourage out parameters as generally error-prone.

**Comment by jaykrell** [comment]
Out parameters are an optimization of ref, with good static checking, but only checked if you stay in C#. Not so good with unchecked C.

**Comment by akoeplinger** [comment]
A quick grep shows we have about 800 other instances in mcs/class where we use `out` in a p/invoke so it'd take quite a while to clean them all up (and using `out` does document the intended data flow better).

I'm inclined to still take this however given you already invested the work, unless others object?

**Comment by vargaz** [comment]
Note that c# locals are are zero initialized, so not setting them in native code is not very dangerous.

**Comment by jaykrell** [comment]
I see your point— the “in” part of the “ref” is either “useful” or “initialized”. There is also disagreement as to if uninitialized integers are unsafe— they are still valid integers within the type system.

**Comment by jaykrell** [comment]
@vargaz really?

**Comment by vargaz** [comment]
I mean .net IL variables are zero initialized if the method has the initlocals flag set, which all c# methods do.

**Comment by jaykrell** [comment]
That surprises me & all but moots this. I thought there was a more efficient thing where the C# compiler enforces definite assignment. Perhaps it comes to not trusting the IL & not being able to efficiently analyze at run time.
Corner case remains native should write for bad IL callers.

**Pull request closed without merging**
