### PR TITLE
Brew zip stuff redundant with building source?

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@grendello

**Comment by grendello** [comment]
Mono requires `zlib` and the MinGW distribution that comes with `brew` does not come with it (unlike on Linux) and so we need to get it from somewhere - brew seemed to be the best place for it. Alternatively, Mono could be changed to build its own `zlib`, but would that really be better?

**Comment by jaykrell** [comment]
Don't we already build our own?

**Comment by grendello** [comment]
it wasn't the case when I implemented code to switch to mingw instead of using MXE - at least not when cross-building for Windows.

**Comment by jaykrell** [comment]
Understood, but now it is. With the compressed/portable pdb support.

**Comment by grendello** [comment]
If it works for mingw builds, then by all means the brew code is no longer needed.

**Comment by jaykrell** [comment]
CI suggests yes? Or unclear, since autoconf could just be falling back to degraded functionality?
Oh, it is not clear.

We do unconditionally build and use zlib, in places, but it could be some code is disabled.
Needs more investigation I guess, or configure.ac/Makefile.am tweaks.

Where was it needed?

**Comment by jaykrell** [comment]
Close for now as it is likely incomplete.
Configure.ac/ifded changes later maybe.

**Pull request closed without merging**
