### PR TITLE
Add acceptance tests directory

### PR DESCRIPTION
**Pull request by akoeplinger**
This uses a custom submodule system that doesn't rely on git submodules (which are annoying when the repo is large and we only need them for tests). Instead we can fetch repositories on demand.

This PR integrates the CoreCLR, Roslyn and ms-test-suite (which is Xamarin-internal, but should just print a warning for someone without access).
Running the tests suites can be done with `make check-coreclr`, `make check-roslyn` and `make check-ms-test-suite`, or all of them with `make check` in the `acceptance-tests` folder. They won't run on a top-level `make check` though, which is intended until every test suite is fixed.

**Note**: the CoreCLR test suite throws about ~80 test errors that I plan on categorizing shortly. The Roslyn testsuite works fine on Mac (thanks to @esdrubal for the help there), but throws a NullReferenceException inside in System.Threading.Tasks.RangeWorker when compiling on Linux, not sure what's going on there yet.

Let me know if there are too many commits and I should squash it down :smile:

### CODE REVIEW

**Comment by vargaz** [comment]
Looks ok to me.

**Comment by kumpera** [comment]
@tritao could review/merge this one?

**Comment by tritao** [comment]
Looks good to me but I think it might be worth to consider the scripting language we go with.

So at the moment we have scripts in Perl, Python and Ruby. Perl seems to be on the way out nowadays and from my fairly limited exposure to it a couple months ago while trying to fix bugs in Perl code in Mono it's a pain in the ass to work with for people not already familiar with its ways.

We only have 2 very small Ruby scripts at the moment, located in https://github.com/mono/mono/tree/master/mcs/tools/corcompare, while we do have a couple more Python scripts (https://github.com/mono/mono/search?l=python).

So I'd suggest we just go with Python for all future scripting needs. We already use it in tree for a couple of stuff (GDB, LLDB integration), some of our dependencies like LLVM also use it. It's also more popular than Ruby and from my limited experience has a more solid Windows implementation.

What do you guys think?

**Comment by tritao** [comment]
Oh, also please squash this down for the final merge.

**Comment by esdrubal** [comment]
Looks good :+1:

**Comment by akoeplinger** [comment]
Thanks. I squashed and merged this in to master.

**Pull request closed without merging**
