### PR TITLE
[coop] Make sure suspend_count is positive in suspend request states

### PR DESCRIPTION
**Pull request by lambdageek**
* Fix bug in `pulse` transition - the suspend count was lost and incorrectly
  swapped to 0.
* `finish_async_suspend` transition - add assertions that the suspend count is
  positive. Try to catch incorrect states sooner.

Fixes https://github.com/mono/mono/issues/12235

### CODE REVIEW

**Comment by lambdageek** [comment]
@monojenkins backport to 2018-12

**Comment by lambdageek** [comment]
@monojenkins backport to 2018-10

**Comment by lewurm** [comment]
@monojenkins build Linux x64 Acceptance Tests

**Comment by lambdageek** [comment]
Acceptance test failure is known: #12242

**Pull request merged**
