### PR TITLE
[System]: Fix race condition in `SystemDependencyProvider.Initialize()`.  #12538.

### LINKED ISSUE #12538: InvalidOperationException in DependencyInjector
## Steps to Reproduce

1. Built a recent copy of monodevelop and md-addins
2. make run from md-addins

### Current Behavior

Running monodevelop crashed on startup once.
Only seen this once. Running again and it was OK.

### Expected Behavior

Mono runs without a crash.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.18.0.219 (2018-08/f919fb58c4e Tue Dec  4 12:36:55 EST 2018)

Xamarin.Mac:

Version: 5.6.0.1 (Visual Studio Enterprise)
Hash: 2e9867a4
Branch: d16-0
Build date: 2018-12-12 02:19:18-0500

## Stacktrace

```
FATAL ERROR [2019-01-21 14:32:31Z]: Visual Studio failed to start. Some of the assemblies required to run Visual Studio (for example gtk-sharp)may not be properly installed in the GAC.
System.Exception: Toolkit could not be loaded ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Mono.DependencyInjector.Register (Mono.ISystemDependencyProvider provider) [0x0001f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/corlib/Mono/DependencyInjector.cs:65 
  at Mono.SystemDependencyProvider..ctor () [0x00011] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/System/Mono/SystemDependencyProvider.cs:66 
  at Mono.SystemDependencyProvider.Initialize () [0x00007] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/mcs/class/System/Mono/SystemDependencyProvider.cs:48 
  at ObjCRuntime.Runtime.Initialize (ObjCRuntime.Runtime+InitializationOptions* options) [0x00290] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.6.0.1/src/Xamarin.Mac/ObjCRuntime/Runtime.cs:262 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) System.Object.wrapper_native_0x109305470()
  at ObjCRuntime.Runtime.EnsureInitialized () [0x00041] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.6.0.1/src/Xamarin.Mac/ObjCRuntime/Runtime.mac.cs:118 
  at AppKit.NSApplication.Init () [0x00016] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.6.0.1/src/Xamarin.Mac/AppKit/NSApplication.cs:56 
  at Xwt.Mac.NSApplicationInitializer.Initialize () [0x00051] in monodevelop/main/external/xwt/Xwt.XamMac/Xwt.Mac/NSApplicationInitializer.cs:44 
  at Xwt.Mac.MacEngine.InitializeApplication () [0x00001] in monodevelop/main/external/xwt/Xwt.XamMac/Xwt.Mac/MacEngine.cs:48 
  at Xwt.Backends.ToolkitEngineBackend.Initialize (Xwt.Toolkit toolkit, System.Boolean isGuest) [0x0003b] in monodevelop/main/external/xwt/Xwt/Xwt.Backends/ToolkitEngineBackend.cs:58 
  at Xwt.Toolkit.Initialize (System.Boolean isGuest) [0x00018] in /Volumes/SeagateMac/projects/monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:305 
  at Xwt.Toolkit.LoadBackend (System.String type, System.Boolean isGuest, System.Boolean throwIfFails) [0x00066] in /Volumes/SeagateMac/projects/monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:288 
   --- End of inner exception stack trace ---
  at Xwt.Toolkit.LoadBackend (System.String type, System.Boolean isGuest, System.Boolean throwIfFails) [0x00081] in monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:295 
  at Xwt.Toolkit.Load (Xwt.ToolkitType type) [0x00049] in monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:235 
  at MonoDevelop.Components.IdeTheme.InitializeGtk (System.String progname, System.String[]& args) [0x00057] in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs:76 
  at MonoDevelop.Ide.IdeStartup.Run (MonoDevelop.Ide.MonoDevelopOptions options) [0x001de] in /Volumes/SeagateMac/projects/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:142 
  at MonoDevelop.Ide.IdeStartup.Main (System.String[] args, MonoDevelop.Ide.Extensions.IdeCustomizer customizer) [0x000f4] in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs:843 
```

### PR DESCRIPTION
**Pull request by baulig**
Fix race condition in `SystemDependencyProvider.Initialize()`.

Fixes #12538.

### CODE REVIEW

**Comment by marek-safar** [comment]
Please backport to 2018-08

**Comment by baulig** [comment]
@monojenkins backport 2018-10

**Comment by baulig** [comment]
@monojenkins backport 2018-12

**Comment by baulig** [comment]
@monojenkins build failed

**Pull request merged**
