### PR TITLE
[io-layer] Cleanup thread support

### PR DESCRIPTION
**Pull request by ludovic-henry**
Depends on https://github.com/mono/mono/pull/1840

### CODE REVIEW

**Comment by kumpera** [comment]
What happened with all the previous comments?

**Comment by ludovic-henry** [comment]
You left them on a commit, and not a the "Files changed" tab, so when I updated the commits, the reference was lost. The old commit is here though : https://github.com/ludovic-henry/mono/commit/319f15a9846b698e39cfdd7629fed377e339e4e0

**Comment by ludovic-henry** [comment]
And you actually left the comments on the PR 1840

**Comment by kumpera** [comment]
I squashed the fixup! commit, fixed the merge conflict and pushed.

**Pull request closed without merging**
