### PR TITLE
[timezone] ignore LocalId test on XAMMAC_4_5 too

### PR DESCRIPTION
**Pull request by lewurm**
https://github.com/xamarin/maccore/issues/628

### CODE REVIEW

**Comment by lewurm** [comment]
should be backported to `2017-12` and `2018-02`. /cc @rolfbjarne

**Comment by lewurm** [comment]
as a reference: https://github.com/mono/mono/commit/a0da4f621de034e11a30bfe889059e3e7b9e8cd3

**Comment by akoeplinger** [comment]
I wonder why this is only showing up now?

**Comment by lewurm** [comment]
It showed up earlier already I think: https://github.com/xamarin/xamarin-macios/commit/bd3938f86363b9b749c649a1e849a55f371ac940

**Comment by lewurm** [comment]
@monojenkins backport to 2017-12

**Comment by lewurm** [comment]
@monojenkins backport to 2018-02

**Pull request merged**
