### PR TITLE
XML-DSIG transforms from .NET Core.

### PR DESCRIPTION
**Pull request by vladimir-kazakov**
* The `DigestMethod` of a `Reference` was changed from SHA-1 to SHA-256. This is, potentially, a breaking change, but it seems that it's okay: https://github.com/dotnet/corefx/pull/18685.
* The `XmlDsigC14NTransformTest.PrefixlessNamespaceOutput` test was removed, because it was failing on .NET Framework (4.6.2) as well, which means that the new implementation from .NET Core behaves the same way as the .NET Framework's one. Although there's an open issue in .NET Core about this test - https://github.com/dotnet/corefx/issues/16780, I guess that the problem here is not in the implementation, but in the test itself, since it's unclear what it tests and why.

### CODE REVIEW

**Comment by luhenry** [comment]
build

**Comment by vladimir-kazakov** [comment]
I guess I'll need some help to understand this build failure, because I cannot reproduce it locally.

The build log says: `error CS0006: Metadata file './../../class/lib/basic/System.Core.dll' could not be found`.

The following things got my attention:

* The `basic` profile. I've seen also `bare` and `secxml`. It's not clear what these profiles are. Building locally with `make PROFILE=basic` succeeds. I'm confused.
* The `System.Core.dll` assembly, which I added to the `LIB_REFS` in the `Makefile` for `System.Security`. I added it without specifying a profile. Other "refs" had profiles.

Maybe I had to specify the profile too? But which one? Perhaps `System.Core` should be available everywhere? Changed this "ref" to `$(PARENT_PROFILE)/System.Core`. The local build still succeeds. I'm not sure whether this is a proper solution, because I don't have any knowledge about profiles. Can anybody explain them?

So, the questions are:

1. What are profiles?
1. How to decide which profile should be used when adding an assembly to `LIB_REFS`?
1. In which cases there's no need to specify a profile when adding an assembly to `LIB_REFS`?
1. How to reproduce this issue locally? I'm using a 64-bit Ubuntu 16.04, so I would expect that it should be similar to `Linux x64`.

**Comment by akoeplinger** [comment]
First of all: I guess you still have the `basic` profile from some earlier build, try `rm -rf mcs/class/lib` to start fresh.

About the profiles:

We have the `basic` profile which is basically the minimum set of BCL libs required to run the mcs or roslyn/csc compiler for compiling the `build` profile. The `build` profile is the profile we use to compile everything else, it includes tools like resgen.exe, ilasm.exe etc.

`bare` and `secxml` are not profiles in themselves, but configurations. They are used to solve the problem of System.dll having a circular dependency chain: System.dll depends on System.Xml.dll and Mono.Security.dll which depend on System.dll.

The `bare` configuration builds System.dll without those dependencies (by #ifdef-ing out the code which relies on it). With the bare/System.dll we can compile System.Xml.dll and so on...

System.Security.dll can't depend on System.Core.dll for that reasons, what do you need it for?

**Comment by vladimir-kazakov** [comment]
Okay... Removing the `mcs/class/lib` directory and building with `make PROFILE=basic` reproduced the error locally.

If I try building without `System.Core.dll`, I get following errors:

```
make[6]: Entering directory '/mono/mcs/class/System.Security'
CSC     [basic] System.Security.dll
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/DSASignatureDescription.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAPKCS1SHA1SignatureDescription.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAPKCS1SHA256SignatureDescription.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAPKCS1SHA384SignatureDescription.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAPKCS1SHA512SignatureDescription.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAPKCS1SignatureDescription.cs(7,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
../../build/library.make:311: recipe for target '../../class/lib/basic/System.Security.dll' failed
make[6]: *** [../../class/lib/basic/System.Security.dll] Error 1
make[6]: Leaving directory '/mono/mcs/class/System.Security'
```

These classes from .NET Core have unused `using System.Linq;`. When I remove them, the following error occurs:

```
make[6]: Entering directory '/mono/mcs/class/System.Security'
CSC     [basic] System.Security.dll
/mono/external/corefx/src/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Utils.cs(760,53): error CS1061: 'X509Certificate2' does not contain a definition for 'GetRSAPublicKey' and no extension method 'GetRSAPublicKey' accepting a first argument of type 'X509Certificate2' could be found (are you missing a using directive or an assembly reference?)
../../build/library.make:311: recipe for target '../../class/lib/basic/System.Security.dll' failed
make[6]: *** [../../class/lib/basic/System.Security.dll] Error 1
make[6]: Leaving directory '/mono/mcs/class/System.Security'
```

This one is more complex. When I remove the dependency on the missing method (https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions.getrsapublickey(v=vs.110).aspx), providing a fake implementation, then the build succeeds.

But it seems like removing dependencies on `System.Core.dll` from `System.Security.dll` is the wrong thing to do, because .NET Core may potentially add new dependencies, which will break Mono. What would be the correct way to solve such problems?

**Comment by akoeplinger** [comment]
@vkargov removing the unused usings is the right thing to do. Can you please make a PR to corefx with that?

The `GetRSAPublicKey()` is expected, it's an extension method that lives in System.Core in .NET 4.6: https://github.com/mono/mono/blob/master/mcs/class/System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs

.NET Core has a different layering so their dependency chain might be different. The GetRSAPublicKey() implementation is quite simple so you can just add that under `#if MONO` instead in the corefx code.

**Comment by vladimir-kazakov** [comment]
```
The GetRSAPublicKey() implementation is quite simple...
```
It doesn't really seem so: [.NET Framework](https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/X509Certificates/RSACertificateExtensions.cs,a186c5049cb62ad4), [.NET Core](https://github.com/dotnet/corefx/blob/264615a238cbc7d4dc593568f2505a9316657095/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/CertificateExtensionsCommon.cs#L15).

So, it's not just a matter of returning `X509Certificate2.PublicKey.Key`. Moreover, the behavior of [X509Certificate2.PublicKey.Key](https://referencesource.microsoft.com/#System/security/system/security/cryptography/x509/x509certificate2.cs,336c1951e9125830) ([MSDN](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.publickey.key(v=vs.110).aspx)) doesn't match the behavior of [RSACertificateExtensions.GetRSAPublicKey()](https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/X509Certificates/RSACertificateExtensions.cs,a186c5049cb62ad4) ([MSDN](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.rsacertificateextensions.getrsapublickey(v=vs.110).aspx)). The `X509Certificate2.PublicKey.Key` throws if the key is not RSA or DSA. The `RSACertificateExtensions.GetRSAPublicKey()` never throws, returning `null` if the key is not RSA.

Also, I found that there was already [an attempt](https://github.com/dotnet/corefx/pull/14662) to use `X509Certificate2.PublicKey.Key` in .NET Core, when `System.Security.Cryptography.Xml` was being ported from .NET Framework. One of the maintainers explicitly asked to not use it, because it's not the same as `GetAnyPublicKey()`. And [this commit](https://github.com/dotnet/corefx/pull/14662/commits/f17cc3bdaf22187f22124e84f7a533bc8d0a899b) further clarifies the intended behavior of `GetAnyPublicKey()`, which is "return either an RSA or a DSA key, or `null` in any other case".

Given all that, it seems like the Mono's implementation is not quite correct, so touching this code in .NET Core would be a wrong thing to do.

But what if I would just add this method to the Mono's `System.Security.dll` by adding `../System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs` to `System.Security.dll.sources`? I tried it, and it works as expected. It seems to me that it's a better solution, because .NET Core will stay the same, without unneeded complications like `#if MONO`. @akoeplinger, what do you think?

**Comment by vladimir-kazakov** [comment]
The build should succeed now. But before running it, the `corefx` submodule should be updated to the latest version. Should I do it myself (how?) or such changes are being done by maintainers only?

**Comment by akoeplinger** [comment]
whitelist

**Comment by akoeplinger** [comment]
Hey @vladimir-kazakov, sorry for the late answer, I seem to have missed your last message.

> But what if I would just add this method to the Mono's System.Security.dll by adding ../System.Core/System.Security.Cryptography.X509Certificates/RSACertificateExtensions.cs to System.Security.dll.sources?

Unfortunately we can't do that since it'd expose e.g. the public `RSACertificateExtensions.GetRSAPrivateKey()` method from both System.Security.dll and System.Core.dll since the class is public.

There are basically two options: a) copy the RSACertificateExtensions.cs to System.Security and make the class `internal` or b) do the same but via an #ifdef in the original file and adding that define to the System.Security Makefile so that it is public in System.Core.dll but internal in System.Security.dll. I'd prefer the latter 😄 

> But before running it, the corefx submodule should be updated to the latest version. Should I do it myself (how?) or such changes are being done by maintainers only?

Theoretically you could do it too by sending a PR to https://github.com/mono/corefx but usually there are merge conflicts etc so it's better if one of us does it. I bumped corefx in 68ba6c145672e0e9bf29bb2afa98ab5e43187885.

**Comment by marek-safar** [comment]
We cannot duplicate System.Core public API, it's breaking change as the API signature is same. We'll have to do some build trick to build System.Security with System.Core dependency but that's probably something what you are not interested in so I am inclined to merge it and do the build clean up ourselves

**Comment by vladimir-kazakov** [comment]
```that's probably something what you are not interested in so I am inclined to merge it and do the build clean up ourselves```

Last commits fixed all problems, I guess. Speaking of changes in the public API, I assume they have to be committed by a maintainer, right?

**Comment by marek-safar** [comment]
commit apidiff

**Comment by marek-safar** [comment]
@vladimir-kazakov could you please rebase the PR on top of mono master

**Pull request merged**
