### PR TITLE
[mono-api-info] Allow following type forwarders

### PR DESCRIPTION
**Pull request by mhutch**

### CODE REVIEW

**Comment by kumpera** [comment]
This doesn't compile:

15:49:01 mono-api-info.cs(37,27): error CS0234: The type or namespace name `Options' does not exist in the namespace `Mono'. Are you missing an assembly reference?

**Comment by mhutch** [comment]
Ah, I was using the project file not the Makefile.

**Comment by directhex** [comment]
make[8]: *** No rule to make target `..\..\class\Mono.Options\Mono.Options\Options.cs', needed by `mono-api-info.exe'.  Stop.

**Comment by mhutch** [comment]
Ugh. That'll teach me to try to fix it on a WIndows machine.

**Pull request merged**
