### PR TITLE
[wasm] Bump emscripten to 1.39.17.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
The wasm failures are relevant.

**Comment by vargaz** [comment]
Testcase:
```
	public static void Main (String[] args) {
		long l1 = args.Length;
		long l2 = long.MinValue;
		Console.WriteLine (l1 / l2);
         }
```

**Comment by vargaz** [comment]
Looks like an llvm optimization problem in interp.c, the MINT_DIV_I8 case.

**Comment by BrzVlad** [comment]
This emscripten version contains the previously mentioned llvm fix for switch dispatch, which seems to improve perf by about 4-7%.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
So with the interp.c changes, tests pass now. It would be nice to track down the cause of the llvm problem, but its in the interpreter main loop which is huge.

**Comment by BrzVlad** [comment]
I'm comfortable looking at generated wasm/native code for any piece of code in the runtime. I can take a look for that testcase and report to llvm guys if I figure anything out.

**Comment by vargaz** [comment]
The problem seem to be in the DIV/REM cases:
		MINT_IN_CASE(MINT_DIV_I8)
			if (sp [-1].data.l == 0)
				goto div_zero_label;
			if (sp [-1].data.l == (-1) && sp [-2].data.l == G_MININT64)
				goto overflow_label;
			BINOP(l, /);
			MINT_IN_BREAK;

The sp[-1].data.l == 0 case gets hit even through the value is not 0.

**Pull request merged**
