### PR TITLE
Turned the compiler server off on Windows because Named Pipes aren't fully working

### PR DESCRIPTION
**Pull request by steveisok**

### CODE REVIEW

**Comment by steveisok** [comment]
I don't think this saves us a thing time wise, but technically it should be off on windows.

**Comment by jaykrell** [comment]
Surely named pipes are easy to get working on Windows?
Granted that doesn't mean the server is fast.

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
Hmm, the named pipe code is from CoreFX and I am pretty damn sure it works there for the compiler server. In fact, that was one of the motivations for adapting the code. Is there some issue filed for the problem?

**Comment by steveisok** [comment]
@filipnavara The main issue is mono's WindowsIdentity is incomplete. 

https://github.com/mono/corefx/blob/ee3acec16b37bec5016da129e1e3840097ca629b/src/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Windows.cs#L51-L72

And even if you comment that block out, it still throws. 

I haven't created an issue for it yet.

**Comment by steveisok** [comment]
Additionally, the compiler server is never actually started because MONO_PATH is passed as cygwin paths.

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins build failed

**Pull request merged**
