### PR TITLE
fix warning: threadpool-worker-default.c: function 'worker_try_create': 'now' may be used uninitialized

### PR DESCRIPTION
**Pull request by jaykrell**
https://jenkins.mono-project.com/job/build-source-tarball-mono-pullrequest/854/console

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@CoffeeFlux Yes, but/and you are assuming the compilers do equal analysis.
We have tons more warnings on Linux than OSX.

And -Wmissing-prototypes is overkill.

It should only warn/error for functions called, not functions implemented, imho.
I think C++ is that way per standard, not merely compiler discretion -- you cannot even call something undeclared, but you can implement something undeclared.

**Comment by lambdageek** [comment]
> It should only warn/error for functions called, not functions implemented, imho.

It's a warning/error for a common problem: declaring a function in a header and defining it in a .c file with a typo in the name.   And it's good style (and should be in the Mono coding guidelines, IMO): if you have a non-static function, it needs a declaration.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
