### PR TITLE
Reduce some stack use and cleanup.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@akoeplinger did this go in with some failures? WebAssembly, Windows i386, Windows i386 Cooperative Suspend. Are those known? I was going to do a double check. The earlier approved version did have a mistake.

**Comment by akoeplinger** [comment]
@jaykrell yep I did and they were known issues.

**Pull request merged**
