### PR TITLE
[corlib] Fix String.Replace (..., StringComparison.InvariantCultureIgnoreCase).

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/18978.

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by vargaz** [comment]
The newly added test fails on wasm because of nonexistent collation.

**Comment by lewing** [comment]
Should we skip the test on wasm and land this now?

**Comment by vargaz** [comment]
We could but it means the code will misbehave on wasm instead of throwing a not implemented exception.

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
This is still failing because we are linking the collation out by default on wasm

**Comment by vargaz** [comment]
Closing for https://github.com/mono/mono/pull/19624

**Pull request closed without merging**
