### PR TITLE
Mini h cleanup

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by luhenry** [comment]
What's left in `mini.h`? If it's only related to compiling IL to native, should it be renamed `mini-compiler.h`?

**Comment by vargaz** [comment]
It still has all kinds of stuff left which is very hard to remove due to circular dependencies. Also, it can be though as the header file for mini.c which is the JIT compiler main file.

**Comment by luhenry** [comment]
ok, makes sense

**Comment by kumpera** [comment]
Small headers. ❤️

**Comment by vargaz** [comment]
build

**Comment by vargaz** [comment]
build linux i386

**Comment by vargaz** [comment]
build Linux i386

**Comment by vargaz** [comment]
build

**Comment by akoeplinger** [comment]
@vargaz FYI the individual trigger words need to be prefixed with @monojenkins

**Comment by vargaz** [comment]
Failures are unrelated.

**Pull request merged**
