### PR TITLE
[aot] Add a DisableProfiler icall to Mono.Runtime, enabling apps to d…

### PR DESCRIPTION
**Pull request by vargaz**
…isable profile data collection after startup is finished for example.

### CODE REVIEW

**Comment by alexrp** [comment]
In general, I'm not a big fan of essentially exposing the profiler API directly to the managed world like this. Letting managed code disable all events for any arbitrary profiler can break things left and right. For example, the log profiler relies on GC events to *always* be enabled to actually function (see [this code](https://github.com/mono/mono/blob/master/mono/profiler/mono-profiler-log.c#L1483)). If a user called `Mono.Runtime.DisableProfiler ("log")`, it might work half of the time, but we'd get bug reports for the other half, even though it's technically a user error.

I think a better design would be to introduce a new static class in the `Mono.Profiler.Aot` assembly (#4305) called something like `AotProfiler` and have icalls on it that are registered from the AOT profiler module. From there, you can do whatever is actually appropriate for the AOT profiler. This is what I'm doing for the `Mono.Profiler.Log` library I'm working on, and also what I believe @kumpera is doing in his malloc profiler.

That said, we're currently missing a good API for changing the event flags on a specific `MonoProfiler` after it has been registered. I have an overhaul of the profiler API in the works that lets the user pass the `MonoProfiler` to all functions in the API, but until I get that merged, you could just add a temporary function that isn't declared in the public header, and use that from the AOT profiler.

**Comment by kumpera** [comment]
Hey @alexrp, let me explain the scenario Zoltan is trying to cover here to help this conversation.

We want to simplify the reduced startup time scenario[1] of the AOT profiler for Android users of Xamarin.Forms and this means removing the "build, profile, rebuild" cycle of an profile guided system.

Our idea is to enable the AOT profiler by default during debug builds and use that data when AOT'ing release builds.


[1] In that scenario, the AOT profiler is used to figure out what to AOT for startup

**Comment by vargaz** [comment]
So does this look ok ?

**Comment by alexrp** [comment]
Is this PR still something we want? Or could we go with something more specific, similar to what the log profiler does for its icalls [here](https://github.com/mono/mono/blob/master/mono/profiler/log.c#L3969)?

**Comment by vargaz** [comment]
Doesn't seem to be needed anymore.

**Pull request closed without merging**
