### PR TITLE
Bump msbuild to track mono-2019-08

### PR DESCRIPTION
**Pull request by radical**
.. picking up changes from https://github.com/mono/msbuild/pull/145 .

### CODE REVIEW

**Comment by lewing** [comment]
Do we need to bump roslyn as well?

**Comment by radical** [comment]
re:roslyn, yes, bumping that in msbuild now. It would be good to update msbuild itself too, but the branch `vs16.4` hasn't been updated yet.

**Comment by radical** [comment]
https://github.com/mono/msbuild/pull/146
https://github.com/mono/roslyn-binaries/pull/20

**Comment by radical** [comment]
Bumped again to get changes in https://github.com/mono/msbuild/pull/147 which includes Roslyn update.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by lewing** [comment]
merging this now since the package built on msbuild and we are doing an md-addins bump soon

**Pull request merged**
