### PR TITLE
More thread name improvements

### PR DESCRIPTION
**Pull request by alexrp**

### CODE REVIEW

**Comment by alexrp** [comment]
Failures are unrelated.

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
build

**Comment by migueldeicaza** [comment]
I love this patch, what are the next steps for it?

**Comment by alexrp** [comment]
It just needs a review from @kumpera next week (esp. 02d2e4bf4dbde7adf6b08b18c3c8b0403fab4e00 since he filed the bug mentioned in it).

**Comment by alexrp** [comment]
OK'd by @kumpera and was green prior to rebase, so merging.

**Pull request merged**
