### PR TITLE
[aot] Add clangxx option to --aot

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Comment by kumpera** [comment]
This is meant to fix the `missing clang++` issue on the `Linux ARMv7 Bitcode` lane.

**Comment by kumpera** [comment]
@vargaz it would make sense to be part of the `--aot` invocation, but that would require some makefile surgery to be used by our CI setup.

Otherwise, I can add a `--mono-aot-cxx` argument to mono for which we can then use `MONO_ENV_OPTIONS`

**Comment by vargaz** [comment]
Yeah, its a bit problematic, but I think its better to add a command line flag than a new env variable.

**Comment by directhex** [comment]
```
17:33:50 MONO_PATH=".//class/lib/testing_aot_full" /home/builder/jenkins/workspace/test-mono-pull-request-armhf-bitcode/runtime/mono-wrapper  --runtime=mobile --aot=llvmonly,nimt-trampolines=2000,ntrampolines=10000,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4000,temp-path=class/lib/testing_aot_full/I18N.dll_bitcode_tmp --verbose class/lib/testing_aot_full/I18N.dll > class/lib/testing_aot_full/I18N.dll.so.aot-log
17:33:51 clang: error: the clang compiler does not support '-march=x86-64'
```

Are we passing the most wrong possible parameters for the armhf bitcode builds?

**Comment by kumpera** [comment]
Changed the PR to be a --aot option.
Now, someone needs to figure out how to get this from an env option passed by CI to this argument for the failing tests.

**Comment by directhex** [comment]
@kumpera like this? https://github.com/mono/mono/blob/master/scripts/ci/run-jenkins.sh#L62

**Comment by kumpera** [comment]
@directhex passing an extra `--aot` args will not be addictive AFAICT

**Comment by luhenry** [comment]
@kumpera maybe having additive `--aot` could be the solution you are looking for.

**Comment by luhenry** [comment]
@kumpera could you also please update https://github.com/mono/mono/blob/master/scripts/ci/run-jenkins.sh#L67 so we pass the proper `--aot=clangxx=...` to actually fix the build?

**Comment by luhenry** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
`00:37:21.148 AOT : Unknown argument 'clangxx=clang++-6.0'.` :thinking: https://jenkins.mono-project.com/job/test-mono-pull-request-armhf-bitcode/1042/console

**Comment by kumpera** [comment]
@monojenkins build failed

**Pull request merged**
