### PR TITLE
fixes problem with synchronous AcceptAcync

### PR DESCRIPTION
**Pull request by gregoryyoung**
Affects all HttpListener usages.

A connect flood will break the async loop and take down the entire HttpListener instance (will stop accepting connections).

To reproduce. Take a HttpListener run say 2 wrk test instances against it (1000 connections each works here). After the run the HttpListener has broken its async loop and will no longer accept any connections after. The reason for this is that it was not previously handling the case that AcceptAsync can return synchronously. In this case event will not be called with args.

Patch handles this case and the above issue is not reproducible with.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@gregoryyoung please fix the merge conflicts.

**Comment by gregoryyoung** [comment]
https://github.com/mono/mono/pull/2712

thought I had just forked but it had silently taken me to one 15k commits behind.

**Comment by akoeplinger** [comment]
@gregoryyoung likely because you already had it forked so it just took you to the existing one.

Btw. working from a separate branch instead of master makes it much easier to update with upstream commits.

**Comment by gregoryyoung** [comment]
I would have made and built my changes off of master if the build wasn't broken (I had to work off of a sourceball to make these changes (is a mail on the mono-dev list in this regard))

**Comment by akoeplinger** [comment]
@gregoryyoung replied on the list, this is likely caused by your outdated fork too.

**Comment by gregoryyoung** [comment]
Normally I don't worry about staying current with upstream when I am
forking making a change over the course of an hour and deleting the fork :)

On Wed, Mar 2, 2016 at 11:12 PM, Alexander Köplinger <
notifications@github.com> wrote:

> @gregoryyoung <https://github.com/gregoryyoung> replied on the list, this
> is likely caused by your outdated fork too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/mono/pull/2711#issuecomment-191432355>.
>



-- 
Studying for the Turing test

**Pull request closed without merging**
