### PR TITLE
[marshal] Emit GC Safe transitions around foreign internal calls.

### PR DESCRIPTION
**Pull request by lambdageek**
* Mark `mono_add_internal_call` external only.  Add `mono_add_internal_call_internal` and `mono_add_internal_call_with_flags` for the runtime.
   - icalls added using the external-only API are "foreign".
 
* Add coop transitions around `mono_gc_toggleref_add` (and mark it external only  - it's unused in the runtime).
* Change icall wrappers to call foreign icalls in GC Safe mode.
   - foreign icalls are not coop-aware, so if they perform a blocking operation under hybrid suspend they will hang indefinitely - this is bug #11138. With this change, we run them in GC Safe mode and rely on the runtime API to transition back to GC Unsafe (same as other embedder code).
   - this will require changes to watchOS support in xamarin-macios.

----

This is the `master` version.  `2018-08` backport is #11180

### CODE REVIEW

**Comment by lambdageek** [comment]
@kumpera thanks. Added `mono_dangerous_add_raw_internal_call`

**Comment by lambdageek** [comment]
The C++ builds have been failing pretty consistently here.  Not sure why.  Locally, OS X x64 C++ builds fine.

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@lambdageek is this the version which should go to 2018-10?

**Pull request merged**
