### PR TITLE
[IO] Remove read-only logic in mono_w32_get_disk_free_space

### LINKED ISSUE #17151: DriveInfo return empty space for system volume on MacOS 10.15 Catalina
## Steps to Reproduce

1. Create instance of DriveInfo class with path "/". 
2. Check .AvailableFreeSpace property (as well as all other disk space related properties)

Test.cs with test case attached

### Current Behavior

available space is set to 0.
Test.exe output:

/: 0
/dev: 0
/System/Volumes/Data: 54000906240
/private/var/vm: 54000906240
/System/Volumes/Data/home: 0

### Expected Behavior

appropriate available size should be returned

### Additional Info

Please note, that in macOS Catalina, Apple introduced new filesystem security feature, called volume replication. It means that System volume now mounts with read only permissions. And real system volume with write permissions is mounted as mirror volume at /System/Volumes/Data location (amd it shows real ).

I've also tried to run simple C programm to figure out if statfs and statvfs system calls are working fine. This test code attached as test.c

and output:

54006734848, 54006734848

so POSIX calls are working just fine

### Attachment

[Tests.zip](https://github.com/mono/mono/files/3681222/Tests.zip)

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
6.4.0.198
macOS 10.15 beta 10

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Fixes #17151

This brings us in line with GetDiskFreeSpaceExW on Windows as well as .NET Core.

I checked with the Android folks and it seems like this won't fail their test - all they check is that the returned value isn't `long.MaxValue`.

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
Linux i386 failure is unrelated, opened an issue: https://github.com/mono/mono/issues/17180

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-10

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-08

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06

**Pull request merged**
