### PR TITLE
Change test suite to use nunit-lite.

### PR DESCRIPTION
**Pull request by esdrubal**
Reasons for changing our test suite from nunit24 to nunit-lite are:
- Use same testing runners as other products, avoids problems of using methods not valid in other product test suite.
- nunit-lite is faster to start than nunit24.
- nunit-lite has better handlers for unhandled exceptions, it was noticed before that nunit24 swallows unhandled exceptions.

[Work in progress]

### CODE REVIEW

**Comment by akoeplinger** [comment]
Did we reach agreement yet about whether we can stop shipping nunit? or would we still need to ship it, but not use it for testing mono itself?

This will also have an effect on the babysitter<->nunit communication @xmcclure did, as afaik those were monkeypatched into the nunit source we had here.

**Comment by marek-safar** [comment]
We cannot suddenly stop shipping nunit so this patch is wrong and I don't think we need to copy nunitlite sources either

**Comment by akoeplinger** [comment]
@marek-safar we already have nunit-lite in the repo from back when Kyte added it for mobile_static testing.

As you said we can't stop shipping NUnit, but can we at least move it to be a packaging concern (bockbuild etc), so we don't have it in the Mono repo anymore?

**Comment by esdrubal** [comment]
Removed the commit that was removing the unused nunit24 libs. If it is possible to ship it somewhere else we can do it in another patch. 

@marek-safar I didn't copy anything from nunit-lite, but I had to had helpers and assert methods for nunit24 API that our tests were using but that nunit-lite does not have.

**Comment by marek-safar** [comment]
I don't see any benefit in trying to replicate exactly what we have now in bockbuild.

Yeah, I missed the integration in the large delete commit. I'll have a look once that is out

**Comment by akoeplinger** [comment]
> I don't see any benefit in trying to replicate exactly what we have now in bockbuild.

Separation of concerns mainly, but I'm happy if nunit24 stays in the Mono for shipping repo as well. The important part is getting off of ancient nunit 😄

**Comment by decriptor** [comment]
Why move to nunit-lite? It is dead. It'd make far more sense to move to nunit 3.x. Nunit 2.x and Nunit-lite were merged together into nunit 3.x.

And just to complicate the discussion... Why not consider moving to xunit since a lot of the .NET upstream world is moving to it.

**Comment by marek-safar** [comment]
I agree moving to xUnit would be nice but we are not yet ready for that and AFAIK support for xUnit for all our platforms is still work in progress. Primary reason for the move is to have same test framework as XA/XI as they use same tests and decouple from nunit we install so we can customise our test running settings more easily.

**Comment by decriptor** [comment]
I believe with xunit 2.x there is support for Xamarin - https://xunit.github.io/

I see you point though, but it might make more sense to move to nunit 3.x across the board at some point since nunit 2.x and nunit-lite are really dead or in maintenance now.

**Comment by akoeplinger** [comment]
This was done some time ago.

**Pull request closed without merging**
