### PR TITLE
[sdks] Bump min iOS version to 7.0.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Because that's the min iOS version in all current versions of Xamarin.iOS.

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
@monojenkins build Linux AArch64

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-08

**Comment by akoeplinger** [comment]
@monojenkins backport master

**Pull request merged**
