### PR TITLE
[sgen] Remove sgen specific suspend code

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by evincarofautumn** [comment]
I like this a lot.

**Comment by alexrp** [comment]
This looks really great!

**Comment by schani** [comment]
I'm all for deleting code.

**Comment by ludovic-henry** [comment]
build

**Comment by kumpera** [comment]
Hey @ludovic-henry, I think we should merge this. Now it's a good time for it.

**Pull request merged**
