### PR TITLE
[merp] Synchronize (serialize) calls to MERP API

### PR DESCRIPTION
**Pull request by alexischr**
Should fix https://github.com/mono/mono/issues/19406

### CODE REVIEW

**Comment by alexischr** [comment]
@mdh1418 The runtime internals of the dumping process are not thread-safe, and entering "dump mode" multiple times from the runtime is also guarded. We want the managed API to not necessitate taking a lock before using, so that test is still sound; but internally it's very okay if the multiple 'calls to dump' happen one after another.

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@alexischr remember to backport this to 2020-02 if it should be usable in a future VSMac.

**Comment by alexischr** [comment]
@akoeplinger probably not necessary; the ‘DumpState*’ methods seem to be dead-end entry-points, not even used by VSMac. I am likely to remove them soon, after confirming they have no use.

**Pull request merged**
