### PR TITLE
[Coop] Remove bug-producing double evaluating macros in checked builds.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build Linux x64

**Comment by jaykrell** [comment]
@monojenkins build Linux i386

**Comment by jaykrell** [comment]
@monojenkins build OS X i386

**Comment by jaykrell** [comment]
The double evaluation caused actual grief in a PR at least -- Thread.Abort conversion uses return_obj(function_call_with_side_effects()).

I'm not sure if I should know better than to trust macros.

I was trained not to in the first place, and I do not forget, but it hasn't mattered for decades in C++.

**Comment by akoeplinger** [comment]
Failed builds are unrelated.

**Pull request merged**
