### PR TITLE
[sdks] Use @loader_path for mono and libmonosgen

### PR DESCRIPTION
**Pull request by radekdoulik**
This way we are able to dynamically load libmonosgen and also use host
mono binary.

The library dependencies look like this after the change:
```
otool -L /Users/rodo/git/mono/sdks/out/android-host-Darwin-release/bin/mono
/Users/rodo/git/mono/sdks/out/android-host-Darwin-release/bin/mono:
	@loader_path/libmonosgen-2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	...

otool -L /Users/rodo/git/mono/sdks/out/android-host-Darwin-release/lib/libmonosgen-2.0.dylib
/Users/rodo/git/mono/sdks/out/android-host-Darwin-release/lib/libmonosgen-2.0.dylib:
	@loader_path/libmonosgen-2.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	...
```

### CODE REVIEW

**Comment by jaykrell** [comment]
It'd be nice to also use $ORIGIN on Linux/BSD, and the similar Apple construct.
This is a good start.

This way, you can xcopy stuff around and it still works, without a $PATH, $LD_LIBRARY_PATH search, etc.

**Comment by radekdoulik** [comment]
I don't have a linux build at hand. @grendello could you take a look at it?

Meanwhile I would like to get this merged as xa/mono-2019-06 integration depends on that.

**Comment by jaykrell** [comment]
Certainly proceed with whatever you have.
Don't wait for more.
These forms are unused in the larger world and it is nice to see Mono doing its part.

**Comment by jaykrell** [comment]
Also maybe we can do this stuff in the "normal" makefiles, not only in SDKs? ("What is normal?", understood)

**Comment by akoeplinger** [comment]
`OS X x64 iOS SDK` passed, merging.

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-06

**Pull request merged**
