### PR TITLE
Move monolite URL to Jenkins, not Boston NAS

### PR DESCRIPTION
**Pull request by directhex**
This is the first step for replacing public Wrench with Jenkins, since it's the only part of public Wrench which is used in important places

### CODE REVIEW

**Comment by akoeplinger** [comment]
Why don't we let Jenkins push the monolite package to download.mono-project.com? Seems like a more future proof solution to me (in case the Jenkins url changes/goes away/whatever).

**Comment by vargaz** [comment]
Does that directory contain the older monolite's as well ?

**Comment by directhex** [comment]
No, only newer ones. But we can't retroactively change Makefile.am for older versions anyway

**Comment by directhex** [comment]
Okay, I take @akoeplinger's point, it's more dependable if we depend purely on Apache being up. I've set up http://download.mono-project.com/monolite/ and am syncing all existing old monolites that we have (109 onwards) from Wrench. In theory Jenkins will push updates to that location - want to see it working before updating the PR with the new URL.

**Comment by kumpera** [comment]
Can we merge this puppy?

**Pull request merged**
