### PR TITLE
Use __declspec(thread) with Visual C++, and __thread with Win32/gcc,

### PR DESCRIPTION
**Pull request by jaykrell**
instead of slower TlsGetValue / TlsSetValue

Alternative proposal would be use fiber locals, which we do sometimes.

### CODE REVIEW

**Comment by jaykrell** [comment]
Passed on Windows/amd64. Windows/x86 still pending. Please review.

**Comment by jaykrell** [comment]
Review?

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64

**Comment by jaykrell** [comment]
MONO_DECLSPEC_THREAD?
MONO_KW_THREAD?
KW_THREAD?
THREAD_KEYWORD?
DECLSPEC_THREAD?
Rename existing one?

**Comment by jaykrell** [comment]
Introducing new symbol retains the diff size. I find “kw” obscure.
Would rather spell out “keyword” or “declspec” or find another term.

**Comment by kumpera** [comment]
👍

**Comment by kumpera** [comment]
Is this PR ready? Can we merge it?

**Pull request merged**
