### PR TITLE
[mobile_static] Disable JIT by default

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by vargaz** [comment]
This won't work, the aot compiler needs a jit.

**Comment by alexanderkyte** [comment]
@akoeplinger informed me that iOS passed `--enable-minimal=jit`, and asked that fullaot have it enabled.

**Comment by vargaz** [comment]
ios has two builds, a cross compiler build and a device build with different configure flags.

**Comment by akoeplinger** [comment]
Yeah, not sure what I was thinking, of course we need the jit for aoting in this case.

Testung the DISABLE_JIT case would be good, but I guess for that we'll need a separate Jenkins job that just builds the runtime with different configurations.

**Comment by alexanderkyte** [comment]
That sounds pretty complex to test from within the runtime.

**Pull request closed without merging**
