### PR TITLE
 [wasm] Add normal GC support.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
With this, 'normal' GC seems to be work both with the interpreter and AOT in single-threaded mode.

**Comment by vargaz** [comment]
corlib tests fail after this.

**Comment by BrzVlad** [comment]
so, does wasm have a stack that can be scanned ?  update_current_thread_stack says no ?

**Comment by vargaz** [comment]
There is a C stack, and a wasm stack. The C stack can be scanned.

**Comment by kjpou1** [comment]
@monojenkins build Linux WebAssembly

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by radical** [comment]
@monojenkins build Linux WebAssembly

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
