### PR TITLE
Try looking in ./mono/mini/mono.exe for Windows Mono

### PR DESCRIPTION
**Pull request by directhex**
This adds a path which makes sense on Jenkins.

### CODE REVIEW

**Comment by alexrp** [comment]
Looks ok to me.

**Comment by akoeplinger** [comment]
:+1: 

I wonder whether the `mono\\mono\\mini\\mono.exe` path is just a leftover from the past and we can change that one instead of adding a new entry?

**Comment by alexrp** [comment]
@marek-safar can you sign off on this?

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by directhex** [comment]
Yes, this is still needed, as a precursor to being able to run lots of our test suite on Windows

Random example as-is: https://jenkins.mono-project.com/job/z/label=w64/2825/testReport/junit/MonoTests.System.Web.Compilation/AppResourcesCompilerTest/GlobalResourcesLocalization/

**Comment by lewurm** [comment]
build

**Comment by directhex** [comment]
Thinking about it, this needs to honour the MONO_EXECUTABLE environment var - otherwise it'll use Cygwin Mono, not MSVC Mono

**Comment by directhex** [comment]
build

**Comment by migueldeicaza** [comment]
Jo, let us get this in when you are ready.

**Comment by akoeplinger** [comment]
Replaced by https://github.com/mono/mono/pull/3522.

**Pull request closed without merging**
