### PR TITLE
[llvm] Finish JIT support for llvm 3.9.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins merge

**Comment by lewurm** [comment]
this change breaks `mono-master-monodroid`:

```
[2:59:57]   CXX      llvm-jit.lo
[2:59:57]   CXX      llvm-runtime.lo
[2:59:57] /Users/builder/data/lanes/1845/3d44b341/source/mono/mono/mini/llvm-jit.cpp:22:10: fatal error: 'mono/utils/mono-dl.h' file not found
[2:59:57] #include <mono/utils/mono-dl.h>
[2:59:57]          ^
[2:59:57] 1 error generated.
```

**Comment by vargaz** [comment]
Should be fixed.

**Comment by lewurm** [comment]
yes, thank you.

**Pull request merged**
