### PR TITLE
Added Mono.Tasklets test

### PR DESCRIPTION
**Pull request by Dunati**
Follow up to pull request https://github.com/mono/mono/pull/3258

### CODE REVIEW

**Comment by akoeplinger** [comment]
build

**Comment by vargaz** [comment]
These tests fail on arm/arm64 etc.

**Comment by Dunati** [comment]
can I wrap the test in a `if [[ ${label} == arm* ]]` block or something similar? Do you know what the appropriate check would be?

**Comment by vargaz** [comment]
One solution would be to throw a NotImplementedException somewhere if the platform doesn't support it, and catching that in the test suite.

**Comment by akoeplinger** [comment]
Why would this be platform dependent? Is there something wrong with the `alloc()` here: https://github.com/mono/mono/blob/master/mcs/class/Mono.Tasklets/Mono.Tasklets/Continuation.cs#L38 ?

**Comment by Dunati** [comment]
`MONO_ARCH_SUPPORT_TASKLETS` is only defined for amd64 and x86. Among other things that controls the initialization of the internal methods, including `alloc`.

**Comment by Dunati** [comment]
I can probably update the code and the tests to throw an exception for non-supported platforms.

**Comment by akoeplinger** [comment]
@Dunati that would be awesome

**Comment by Dunati** [comment]
I have the runtime side of the changes, but I an not sure about the test. Is there a reasonable way to check the processor architecture in the test?

**Comment by vargaz** [comment]
The api functions the test calls should throw a NotImplementedException on platforms which are not supported, or it should have a property which can be checked whenever its supported. The tests can either catch the NotImplementedException and treat is as pass, or check the property.

**Comment by akoeplinger** [comment]
`mono_error_set_not_supported` is a utility function you can use in the runtime to do that.

**Comment by Dunati** [comment]
Okay, I can use that instead of `mono_set_pending_exception (mono_get_exception_not_implemented ("Tasklets are not supported on this platform."));`

**Comment by vargaz** [comment]
mono_set_pending_exception (mono_get_exception_not_implemented ("Tasklets are not supported on this platform.")); is okay.

**Comment by Dunati** [comment]
to be clear, is 'not supported' or 'not implemented' more appropriate for this case?

**Comment by vargaz** [comment]
Doesn't matter, probably not supported.

**Comment by vargaz** [comment]
Looks ok.

**Comment by akoeplinger** [comment]
@Dunati sorry for being picky but all the tabs in ContinuationsTest.cs were replaced by spaces, can you please change that back?

**Comment by Dunati** [comment]
Ug, that is what I get for only looking at one other test to see what kind of whitespace I should use.

**Comment by vargaz** [comment]
Looks ok. It would be nice to squash all the commits into one.

**Comment by akoeplinger** [comment]
Thank you!

**Pull request merged**
