### PR TITLE
[msbuild] Bump to track mono-2019-02 HEAD

### PR DESCRIPTION
**Pull request by radical**
- this updates to upstream vs16.1 branch
- updates to nuget 5.1

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
```
14:05:03  libtool: install: /usr/bin/install -c .libs/libtiff.lai @/external/bockbuild/scratch/tiff-x64.install/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/libtiff.la
14:05:03  install: .libs/libtiff.lai: No such file or directory
```

IIUC, this can be intermittent. So, triggering the build again.

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
`OS X Extended`: Unrelated runtime test failures.

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
Same llvm related test failures again:

```
18:07:59 MONO_PATH=/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/build ../../runtime/mono-wrapper --aot-path=/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/build /Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.8.2/tools/csc.exe -debug:portable -noconfig -nologo -nowarn:0162 -nowarn:0168 -nowarn:0219 -nowarn:0414 -nowarn:0618 -nowarn:0169 -nowarn:1690 -nowarn:0649 -nowarn:0612 -nowarn:3021 -nowarn:0197 -langversion:latest  -unsafe -r:/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/net_4_x/System.dll -r:/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/net_4_x/System.Xml.dll -r:/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/net_4_x/System.Core.dll -r:TestDriver.dll -r:/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/net_4_x/Mono.Posix.dll -out:imt_big_iface_test.exe imt_big_iface_test.cs
18:07:59 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
18:07:59 
18:07:59 Mono Warning: llvm support could not be loaded.
18:07:59 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
18:07:59 
18:07:59 Mono Warning: llvm support could not be loaded.
18:08:00 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
18:08:00 
18:08:00 Mono Warning: llvm support could not be loaded.
18:08:00 runtime-invoke.gen.cs(1,11): error CS1002: ; expected
18:08:00 runtime-invoke.gen.cs(1,11): error CS0116: A namespace cannot directly contain members such as fields or methods
18:08:00 runtime-invoke.gen.cs(1,17): error CS1022: Type or namespace definition, or end-of-file expected
18:08:00 runtime-invoke.gen.cs(1,33): error CS1001: Identifier expected
18:08:00 runtime-invoke.gen.cs(1,33): error CS1003: Syntax error, ',' expected
18:08:00 runtime-invoke.gen.cs(1,34): error CS1003: Syntax error, ',' expected
18:08:00 runtime-invoke.gen.cs(1,45): error CS1001: Identifier expected
18:08:00 runtime-invoke.gen.cs(1,47): error CS1031: Type expected
18:08:00 runtime-invoke.gen.cs(1,47): error CS1001: Identifier expected
18:08:00 runtime-invoke.gen.cs(1,47): error CS1003: Syntax error, ',' expected
18:08:00 runtime-invoke.gen.cs(1,51): error CS1018: Keyword 'this' or 'base' expected
18:08:00 runtime-invoke.gen.cs(1,51): error CS1002: ; expected
18:08:00 runtime-invoke.gen.cs(1,61): error CS1002: ; expected
18:08:00 runtime-invoke.gen.cs(1,61): error CS0116: A namespace cannot directly contain members such as fields or methods
18:08:00 runtime-invoke.gen.cs(3,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations
18:08:00 runtime-invoke.gen.cs(4,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations
18:08:00 
make[3]: *** [runtime-invoke.gen.exe] Error 1
```

Last when I had looked at this issue, it was the file `runtime-invoke.gen.cs` was generated earlier:

`MONO_PATH=/Users/builder/jenkins/workspace/test-mono-pull-request-mac-sdk/external/bockbuild/builds/mono/mcs/class/lib/net_4_x ../../runtime/mono-wrapper gen-runtime-invoke.exe > runtime-invoke.gen.cs`

.. but the file got the error string `llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found` written to the file too. And it had disappeared after a couple of builds.
This shouldn't block this PR though.

**Comment by marek-safar** [comment]
@monojenkins build pkg

**Pull request merged**
