### PR TITLE
HttpClient for Android.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins commit csproj

**Comment by baulig** [comment]
I pressed "Ready for review" too early - please hold off merging for a bit.

**Comment by baulig** [comment]
This will require work on the Android side in their https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs, but it is good from the Mono side of things.

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Pull request merged**
