### PR TITLE
Bump msbuild to track mono-2018-04

### PR DESCRIPTION
**Pull request by radical**
Pick up fix for https://github.com/xamarin/xamarin-android/issues/1845 .

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Updated to fix the test command line also, which was causing failure to run the tests.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by akoeplinger** [comment]
MSBuild tests passed but the result file is missing like in #9846

**Pull request merged**
