### PR TITLE
 Fixes #issue-14234

### PR DESCRIPTION
**Pull request by musikhin**
Dear team Mono,

Please find below the fix of issue #14234 .  On the stage of the initialization of the SqliteMembershipProvider the existed code always produced an error "Failed to map path '/'" in case if the ASP.NET application is placed not at the root path. Detailed step by step description of the problem is provided in the issue description.

The bug was that was implemented the call of the function with wrong parameters list. So the fix was in changing the function call. The same function call is also used in SqlMembershipProvider.cs.

Thanks for your job.

Regards,
Alex

### CODE REVIEW

**Comment by musikhin** [comment]
Dear @marek-safari, could you please explain what should I do to start code review? This fix is business critical for us. 

Currently, we make these changes manually and rebuild Mono for each version.

**Comment by marek-safar** [comment]
build

**Comment by steveisok** [comment]
I have no idea why the original code tried to map path anything.  LGTM

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
