### PR TITLE
several fixes for PowerPC

### PR DESCRIPTION
**Pull request by lewurm**
@directhex reported some issues on `ppc64le` for the upcoming Ubuntu release. These are the backports to `mono/master`.

- say goodbye to `__thread` and fix `--with-tls=pthread` for `ppc64le`
- fix a calling convention problem on `ppc64le` in the signal handler
- fix `SIGCTX_TO_MONOCTX` and friends on `ppc32`

status:
- `ppc64le` works mostly¹ work on Ubuntu, with the mono-debian branch.  I tried `mono/master` as well, and ran into linker issues. Alas, gcc/ld are quite broken on `ppc64le`. Maybe another day.
- `ppc32` works mostly¹ on Ubuntu, `mono/master` looks good too :-)
- I don't have a `ppc64` (big endian) available, I hope I didn't make things worse there.

@directhex here are the patches for the debian fork: https://github.com/lewurm/mono/commits/debian-ppc64le-fix

cc @ludovic-henry @BrzVlad @vargaz @BillSeurer @susematz 

¹ it builds, bootstraps and runs all the regression tests. However, `make check` isn't successful.

### CODE REVIEW

**Comment by vargaz** [comment]
Looks ok afaiks.

**Comment by directhex** [comment]
So what's missing for a merge here?

**Comment by lewurm** [comment]
An ACK by the IBM folks would be nice, but we can merge in the meanwhile.

**Comment by directhex** [comment]
What's the worst that could happen?  ¯\_(ツ)_/¯

**Pull request merged**
