### PR TITLE
Synchronous execution of asynchronous web api stack.

### PR DESCRIPTION
**Pull request by olegbelousov77**
It covers including the following questions:

http://stackoverflow.com/questions/33026799/mono-net-support-for-async-await
http://stackoverflow.com/questions/37012143/mono-with-owin-authentication
http://stackoverflow.com/questions/34834346/404-response-appended-to-webapi-response
http://stackoverflow.com/questions/34629192/mono-the-view-index-or-its-master-was-not-found

### CODE REVIEW

**Comment by pruiz** [comment]
Any news on this pr? It looks fine, did anyone actually tried this? @olegbelousov77  Are u using this on production?

**Comment by olegbelousov77** [comment]
@pruiz I have make a startup. The startup had no success, but the site was working properly.

**Comment by pruiz** [comment]
@olegbelousov77 sorry about the startup, but we are glad to hear this patch was working.. We will give it a try. Thnks ;)

**Comment by gabriel-amaral** [comment]
Any news on this pr?

**Comment by steveisok** [comment]
First off, I want to thank you for your PR and I'm sorry it's hung out for a long time.  We are starting to review old PR's as part of our [old pull request policy](https://github.com/mono/mono/wiki/Pull-Request-Guide#old-pull-request-policy) and have flagged this one to close.  

I encourage you to continue to support mono by making PR's, tracking the issues, and being part of the discussion on our gitter channel at https://gitter.im/mono/mono.

**Comment by ArtruneTranspara** [comment]
Is this PR compiled anywhere?

If this issue was closed, what is the suggested alternative?

**Pull request closed without merging**
