### PR TITLE
DO NOT MERGE! PR for a build with lock tracker enabled

### PR DESCRIPTION
**Pull request by Therzok**
To investigate 2s of lock contention on domain lock on VSMac with hybrid AOT

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins buildpkg

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by Therzok** [comment]
Is there any way to stop other builds from happening? Only need the osx pkg

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
> Is there any way to stop other builds from happening? Only need the osx pkg

Yes, add `@monojenkins skip` to the PR description and the default builds won't be triggered.

**Pull request closed without merging**
