### PR TITLE
[interp] Optimize do_jit_call ().

### PR DESCRIPTION
**Pull request by vargaz**
* Move the JIT call related fields to a separate JitCallInfo structure.
* Compute calling convention information and store it into JitCallInfo
  to avoid most type processing at call time.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by BrzVlad** [comment]
Across the interpreter we use the check `mint_type (type) == MINT_TYPE_VT` to represent whether the specific type is stored on the vt stack or directly in a stackval. I would prefer to make use of this method for consistency, instead of doing other checks (like `MONO_TYPE_IS_STRUCT`). I think this makes clear the intention that it is about where the interpreter stores this type and not about the type itself. In the future we could have optimizations like structs smaller than 16 bytes to be stored directly on the normal stack.

I'm not sure why in your PR you don't remove the big switch for the return value which could be handled the same as the arguments

**Comment by vargaz** [comment]
The return type has too many cases since it needs to do a different type of load for every type.

**Comment by BrzVlad** [comment]
I don't follow. We could have a `stackval res` local and initialize the return address to `&res->data.p`, in the scalar case. At the end we would just do sp [0] = res. I don't see why this wouldn't work. Isn't the wrapper writing the scalars exactly how we we expect them ?

**Comment by vargaz** [comment]
Will look at trying to simplify the return code more.

**Comment by BrzVlad** [comment]
I think I see now what you meant. For types smaller than i32 we need to extend them to i32 because that's how we store it in the stackval. We might be limited with what we can do there.

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
