### PR TITLE
[runtime] Support AppleTLS on fullaot, and disable on non-mac net4x

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@alexanderkyte could you please rebase this? it has conflicts.

**Comment by akoeplinger** [comment]
tbh I think this would be cleaner if we kept what we have and just do the following in net_4_x.make and testing_aot_full.make

```
ifneq (darwin,$(PROFILE_PLATFORM))
MONO_FEATURE_APPLETLS=
endif
```

**Comment by marek-safar** [comment]
I don't like it much either as it only introduces yet another way to set MONO_FEATURE_APPLETLS which is already not the easiest setting to understand

**Comment by alexanderkyte** [comment]
This was done to fix the build, as it otherwise tries to use btls on OSX when doing fullaot. It was necessary to test dedup with mkbundle. I don't think that the change that you suggested @akoeplinger would fix this use case.

**Comment by alexanderkyte** [comment]
Looking at the merge conflict, I think that the exact change I made may have been made independently using ONLY_APPLETLS and PROFILE_DISABLE_BTLS

**Comment by baulig** [comment]
Well, I actually like the idea of defining it in the `*.make` files instead of having the magic in the main `Makefile`.   However, instead of using `#undef` - we already have `PROFILE_DISABLE_BTLS=1`.  We could also add `PROFILE_DISABLE_APPLETLS`.

**Comment by alexanderkyte** [comment]
I agree, I like that.

**Pull request closed without merging**
