### PR TITLE
Ensure the finalization in DeflateStream is performed in the correct order.

### LINKED ISSUE #9142: Finalizer crash in process from zstream
## Steps to Reproduce

1.  Use an [MSBuild binary logger](http://source.dot.net/#Microsoft.Build/Logging/BinaryLogger/BinaryLogger.cs,121) (can possibly be just some zstream)
2. Do some work in a thread
3. Abort the thread and reset abort

### Current Behavior

Cannot reliably repro locally, but on VSTS there is:
```
2018-06-14T13:33:51.6259490Z Stacktrace:
2018-06-14T13:33:51.6272310Z 
2018-06-14T13:33:51.6295710Z   at <unknown> <0xffffffff>
2018-06-14T13:33:51.6323130Z   at (wrapper managed-to-native) System.Runtime.InteropServices.GCHandle.CheckCurrentDomain (int) [0x00007] in <17f5177733084096b17badd9e32426e5>:0
2018-06-14T13:33:51.6356420Z   at System.Runtime.InteropServices.GCHandle.op_Explicit (intptr) [0x00018] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Runtime.InteropServices/GCHandle.cs:134
2018-06-14T13:33:51.6390970Z   at System.Runtime.InteropServices.GCHandle.FromIntPtr (intptr) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Runtime.InteropServices/GCHandle.cs:176
2018-06-14T13:33:51.6425930Z   at System.IO.Compression.DeflateStreamNative.UnmanagedWrite (intptr,int,intptr) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/System/System.IO.Compression/DeflateStream.cs:437
2018-06-14T13:33:51.6459010Z   at (wrapper native-to-managed) System.IO.Compression.DeflateStreamNative.UnmanagedWrite (intptr,int,intptr) [0x00023] in <b762fb6af6d3489f9f0e73ba76fbdced>:0
2018-06-14T13:33:51.6486360Z   at <unknown> <0xffffffff>
2018-06-14T13:33:51.6513940Z   at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CloseZStream (intptr) [0x00009] in <b762fb6af6d3489f9f0e73ba76fbdced>:0
2018-06-14T13:33:51.6547260Z   at System.IO.Compression.DeflateStreamNative/SafeDeflateStreamHandle.ReleaseHandle () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/System/System.IO.Compression/DeflateStream.cs:563
2018-06-14T13:33:51.6581740Z   at System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (bool) [0x000a3] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:227
2018-06-14T13:33:51.6615990Z   at System.Runtime.InteropServices.SafeHandle.InternalFinalize () [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:163
2018-06-14T13:33:51.6650430Z   at System.Runtime.InteropServices.SafeHandle.Dispose (bool) [0x0000a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/interopservices/safehandle.cs:262
2018-06-14T13:33:51.6684550Z   at System.Runtime.InteropServices.SafeHandle.Finalize () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/interopservices/safehandle.cs:199
2018-06-14T13:33:51.6717480Z   at (wrapper runtime-invoke) object.runtime_invoke_virtual_void__this__ (object,intptr,intptr,intptr) [0x0001f] in <17f5177733084096b17badd9e32426e5>:0
2018-06-14T13:33:51.6733220Z 

2018-06-14T13:33:51.6793780Z     0   mono64                              0x0000000109a668d8 mono_handle_native_crash + 264
2018-06-14T13:33:51.6818770Z     1   mono64                              0x0000000109ad0dd6 altstack_handle_and_restore + 70
2018-06-14T13:33:51.6843580Z     2   mono64                              0x0000000109c2f3a6 mono_gchandle_is_in_domain + 22
2018-06-14T13:33:51.6868150Z     3   mono64                              0x0000000109c1d907 mono_gc_GCHandle_CheckCurrentDomain + 23
2018-06-14T13:33:51.6892980Z     4   ???                                 0x000000010e604596 0x0 + 4536157590
2018-06-14T13:33:51.6919230Z     5   ???                                 0x000000010e60408d 0x0 + 4536156301
2018-06-14T13:33:51.6947260Z     6   mscorlib.dll.dylib                  0x000000010bed7a21 System_Runtime_InteropServices_SafeHandle_InternalFinalize + 33
2018-06-14T13:33:51.6977950Z     7   ???                                 0x000000010e0b546c 0x0 + 4530590828
2018-06-14T13:33:51.7005720Z     8   mono64                              0x0000000109c1cab2 mono_gc_run_finalize + 706
2018-06-14T13:33:51.7031190Z     9   mono64                              0x0000000109c3b49c sgen_gc_invoke_finalizers + 236
2018-06-14T13:33:51.7056200Z     10  mono64                              0x0000000109c1e5f8 finalizer_thread + 728
2018-06-14T13:33:51.7080980Z     11  mono64                              0x0000000109bcbee3 start_wrapper + 707
2018-06-14T13:33:51.7106560Z     12  libsystem_pthread.dylib             0x00007fff57576661 _pthread_body + 340
2018-06-14T13:33:51.7132640Z     13  libsystem_pthread.dylib             0x00007fff5757650d _pthread_body + 0
2018-06-14T13:33:51.7158310Z     14  libsystem_pthread.dylib             0x00007fff57575bf9 thread_start + 13
```

### Expected Behavior

It shouldn't hard crash mono

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.14.0.105 (2018-04/6d28c8f9621 Fri May 25 04:53:26 EDT 2018)

## Stacktrace

```
Please paste the stack trace here if available.
```

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #9142.

### CODE REVIEW

**Comment by Therzok** [comment]
@monojenkins build OS X package

**Comment by Therzok** [comment]
@monojenkins build pkg

**Comment by filipnavara** [comment]
@Therzok I would appreciate any feedback on whether it solved the problem for your use case.

**Comment by filipnavara** [comment]
@monojenkins backport 2018-04

**Comment by Therzok** [comment]
I can't test with 5.19. I can't build xamarin.forms due to https://github.com/mono/mono/issues/10352 and I can't keep the IDE reliable due to https://github.com/mono/mono/issues/10350

**Comment by Therzok** [comment]
@monojenkins backport 2018-04

**Comment by akoeplinger** [comment]
@filipnavara FYI the backport bot only works for Microsoft/Xamarin/mono github org members now for security reasons.

**Comment by filipnavara** [comment]
@akoeplinger Thanks for the info! It was confusing since it worked couple of days ago, but I don't really mind. I practically never had a need for it anyway :)

**Comment by akoeplinger** [comment]
I tried the test case from https://github.com/mono/mono/issues/9142#issuecomment-404172904 and this PR doesn't completely fix it, I get this exception now:

```
Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Stream has been closed'.
  at System.IO.FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x00099] in /Users/alexander/dev/mono/mcs/class/corlib/System.IO/FileStream.cs:615
  at System.IO.Compression.DeflateStreamNative.UnmanagedWrite (System.IntPtr buffer, System.Int32 length) [0x00039] in /Users/alexander/dev/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:455
  at System.IO.Compression.DeflateStreamNative.UnmanagedWrite (System.IntPtr buffer, System.Int32 length, System.IntPtr data) [0x00019] in /Users/alexander/dev/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:443
  at (wrapper native-to-managed) System.IO.Compression.DeflateStreamNative.UnmanagedWrite(intptr,int,intptr)
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CloseZStream(intptr)
  at System.IO.Compression.DeflateStreamNative+SafeDeflateStreamHandle.ReleaseHandle () [0x00000] in /Users/alexander/dev/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:565
  at System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (System.Boolean dispose) [0x000a3] in /Users/alexander/dev/mono/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:227
  at System.Runtime.InteropServices.SafeHandle.InternalDispose () [0x0000e] in /Users/alexander/dev/mono/mcs/class/corlib/System.Runtime.InteropServices/SafeHandle.cs:156
  at System.Runtime.InteropServices.SafeHandle.Dispose (System.Boolean disposing) [0x00003] in /Users/alexander/dev/mono/mcs/class/referencesource/mscorlib/system/runtime/interopservices/safehandle.cs:260
  at System.Runtime.InteropServices.SafeHandle.Dispose () [0x00000] in /Users/alexander/dev/mono/mcs/class/referencesource/mscorlib/system/runtime/interopservices/safehandle.cs:252
  at System.IO.Compression.DeflateStreamNative.Dispose (System.Boolean disposing) [0x00027] in /Users/alexander/dev/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:386
  at System.IO.Compression.DeflateStreamNative.Finalize () [0x00000] in /Users/alexander/dev/mono/mcs/class/System/System.IO.Compression/DeflateStream.cs:373
```

**Comment by filipnavara** [comment]
Makes sense, I can fix that.

**Comment by filipnavara** [comment]
Thanks for testing. I fixed the error you pointed out. I wrongly assumed that if you don't actually dispose the underlying stream then Read/Write on it will be harmless. Apparently that's not the case and on second thought it definitely makes more sense to avoid any side effects in the finalizer.

**Comment by Therzok** [comment]
@monojenkins backport 2018-04

**Comment by Therzok** [comment]
I don't see the builder crash anymore with the latest build from here: https://github.com/mono/mono/pull/10354

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by marek-safar** [comment]
@monojenkins build failed

**Pull request merged**
