### PR TITLE
Visual Studio project/solution upgrade and enhancement.

### PR DESCRIPTION
**Pull request by lateralusX**
Changes done to Visual Studio projects and solution to enhance build functionality and dependecy management.

Prerequisite to build from Visual Studio, a full cygwin build done once on the system. The current Visual Studio projects for native libraries have been upgraded to Visual Studio 2015 and can be build in x86/x64 Debug/Release. The projects and solution has also been refactored to include correct dependencies and build order + a lot of changes into how and where things are build, distributed etc. The old projects included separate build configurations for Boehm and SGEN GC. This has been removed and is now controlled by a user macro and default GC is SGEN since that is the only supported on Windows platform. The builds will also be prefixed for libraries and binaries build using the different GC so it will be easier to detect used GC in final build (default suffix is -sgen or -boehm depending on which GC in use). It is possible to remove the prefix if needed and all output will have the same name regardless of used GC implementation. It is also possible to completely separate the different GC builds into different folders under the same build folder.

Most of the customizations of the Visual Studio builds can be done in a property sheet, mono.props that is added to all projects in mono solution. The most commonly changed properties can be changed using user macros. Go to property manager, and open up the mono.props (doesn’t matter what build configuration actually opened, it is the same mono.props modified underneath). Go to “User Macros” and there will be a list of six macros:

----

MONO_BUILD_DIR_PREFIX
 
$(MSBuildProjectDirectory)/./build/
 
Folder to include all build and intermediate files. If this is not set the default build directory will be the location of the solution file.

MONO_INSTALL_DIR_PREFIX
 
$(MSBuildProjectDirectory)/./dist/
 
Installation directory used by build-install project.

MONO_TARGET_GC
 
sgen
 
GC to use, default sgen. Alternatives, boehm.

MONO_USE_TARGET_SUFFIX
 
true
 
When true, use target suffix in build. When false no suffix will be used.

MONO_USE_SEPARATE_BUILD_DIR
 
true
 
When true, use separate build dir based on GC.

MONO_USE_STATIC_C_RUNTIME

false

When true, all binaries and libraries will link using static c-runtime. When false, all binaries and libraries will link using dynamic c-runtime (default).

---

Once the macros are set, do a full clean/rebuild of the solution using requested configuration.

There are also a couple of projects that can be used to do special operations, they are called build-all, build-package and build-install. These are not part of the standard solution build, but can be triggered directly and they have dependencies on each other, build-install->build-package->build-all. In order to build and install mono into MONO_INSTALL_DIR_PREFIX, goto build-package and make a full build, this should build all needed projects for selected configuration, when done build build-package and then build-install in order to  install them into MONO_INSTALL_DIR_PREFIX. In order to do this as part of standard build, enable the build-all, build-package and build-install in the build configuration.

Upgraded Visual Studio solution has been validated on VS 2015 Professional and Community Edition.

Changed Visual Studio solution can be build using msbuild.exe. The following different command lines will do different builds.

32-bit Release using sgen GC:

msbuild /p:Platform=Win32 /p:Configuration=Release /p:MONO_TARGET_GC=sgen msvc\mono.sln

64-bit Release using sgen GC:

msbuild /p:Platform=x64 /p:Configuration=Release /p:MONO_TARGET_GC=sgen msvc\mono.sln

32-bit Release using boehm GC:

msbuild /p:Platform=Win32 /p:Configuration=Release /p:MONO_TARGET_GC=boehm msvc\mono.sln

64-bit Release using boehm GC:

msbuild /p:Platform=x64 /p:Configuration=Release /p:MONO_TARGET_GC=boehm msvc\mono.sln

It is possible to exclude MONO_TARGET_GC to default to sgen GC.

In order to change other user macros defined in mono-props, use the /p:[User Macro] argument when calling msbuild.exe. For example, change default build dir, /p:MONO_BUILD_DIR_PREFIX=”c:/mono-build/” to build outside the source tree.

Build artifacts will end up under the selected MONO_BUILD_DIR_PREFIX, default .\build\sgen\x64\bin\Release for x64 Release SGEN build.

NOTE, changes done in this PR will slightly change what is default build for all configurations (sgen instead of boehm) and where its located compared to current solution.

NOTE, since projects have been upgraded to VS 2015 build, .exe's and DLL's will have dependencies on VS 2015 c-runtime. If distributed using an installer that today uses VS 2013 c-runtime redist this needs to be updated once this is merge to use VS 2015 c-runtime redist.

### CODE REVIEW

**Comment by tritao** [comment]
Looks good, just a couple minor remarks.

I wonder if keeping the Boehm configuration justifies the added complexity to the build scripts.
As far as I know we're supposed to be dropping the Boehm GC in the near future and go SGen-only, so I'd be in favor of going that way in the MSVC build scripts. This can be done at a later date, though.

What sort of linking conflicts did you have due to the .pdb having the same name as the .libs? This might break a few scripts that use file globbing to copy the lib/pdb together (I might have a few of these myself) and breaks the usual Windows convention of them following the same naming pattern.

**Comment by lateralusX** [comment]
Regarding GC comment, for new x64 sgen will be the only supported GC, but I assume that for x86 bohem is still at least available for backward compability. I kept both for now, but build defaults to sgen for both Windows x86 and x64. There is also another upside with the current build scripts, it will be easier to add a new GC with current infrastructure, so I don't think there will be any problem keeping it as is.

Regarding name change of intermediate .pdb files, the change was needed during the change history due to conflicts in intermediate build folders. I can try to revert back to default intermediate .pdb files and see if we still have clean and incremental builds on all configurations debug/release x86/x64 and if we do keep default names for intermediate .pdb files.

**Comment by kumpera** [comment]
It's fine to drop boehm from Windows if that makes your life easier.

We'll be removing it from the runtime at some point in the future anyways.

**Comment by lateralusX** [comment]
Investigate why the different naming was introduced for intermediate pdb files. There is a problem in Visual Studio if the same name is used for both intermediate pdb files and final pdb files for exe and dll's. In that case the final pdb file will be incorrect and won't be loaded by the debugger. This problem does however not affect libraries since libraries only have the intermediate pdf as its final output.

I revisited the fix and change the pattern to use default naming for intermediate pdb files for exe and dll's. This will make sure that the intermediate name is not the same as the final pdb file name, mitigating the problem with invalid pdb files. I also changed so libraries use their target name as the name of the pdb file. With these changes all generated pdb files will match their library/dll/exe target name. The package/install build projects will also pick upp all final pdb files and place them together with their corresponding library (in ./lib) or dll/exe (in ./bin).

**Pull request merged**
