### PR TITLE
[System] Guard against attempting to creating out-of-range spans in m…

### PR DESCRIPTION
**Pull request by alexischr**
…acOS FileSystemWatcher

Should fix https://github.com/mono/mono/issues/15575

### CODE REVIEW

**Comment by marek-safar** [comment]
Should we upstream the fix?

**Comment by steveisok** [comment]
@marek-safar Since this is intended to fix a crash in VSM, can we move this through and consider upstreaming separate?

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
Yes but I am not sure it's the right fix if CoreFX is not experiencing the same crash

**Comment by alexischr** [comment]
@marek-safar @steveisok I brought this to upstream attention here: https://github.com/dotnet/corefx/issues/40054 - they don't have an issue reported of this same problem. There is no opinion so far.

I should add a check that these event paths start with `_fullDirectory` (not just that the lengths are okay), but it would be nice to get a nod that this is an expected problem since I have not been able to reproduce the issue yet.

**Comment by steveisok** [comment]
Is CoreFX actively testing against Catalina?  All but a few cases of the crash are happening there.

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins backport 2019-06

**Comment by steveisok** [comment]
@monojenkins backport 2019-08

**Comment by alexischr** [comment]
Failures in `System.ComponentModel.Composition.Tests` are unrelated

**Pull request merged**
