### PR TITLE
Fix memory leak during data registration

### LINKED ISSUE #21035: Memory leak in mini_get_rgctx_entry_slot -> lookup_or_register
## Steps to Reproduce

1. https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mono/mini/mini-generic-sharing.c#L2843
2. if the data is found in the lookup aka it is registered, the does nothing to ensure it frees `data`.
3. `data` is always newly allocated before passed to the method

### Current Behavior

Leak

### Expected Behavior

No leak

## On which platforms did you notice this

[*] macOS
[ ] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 6.12.0.125 (2020-02/8c552e98bd6 Mon Mar  8 13:06:52 EST 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

## Stacktrace

```
Please paste the stack trace here if available.
```

image

### PR DESCRIPTION
**Pull request by fanyang-mono**
Fixes #21035

### CODE REVIEW

**Review by Therzok — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]

**Comment by fanyang-mono** [comment]
@monojenkins build failed

**Comment by fanyang-mono** [comment]
@monojenkins build failed

**Comment by fanyang-mono** [comment]
`mono-ci (Linux x64 All Profiles Build)` was unrelated to this PR and has been fixed on main by https://github.com/mono/mono/commit/165d8666e19a89304eb0c993063b876899f36f82

**Comment by fanyang-mono** [comment]
@monojenkins build failed

**Comment by fanyang-mono** [comment]
@monojenkins build failed

**Pull request merged**
