### PR TITLE
[WinForms] fix EditingCellFormattedValue getter and setter for bool value

### PR DESCRIPTION
**Pull request by sancheolz**
If DataGridViewCheckBoxCell not in threeState mode EditingCellFormattedValue must return true or false, instead of value of CheckState type

### CODE REVIEW

**Comment by marek-safar** [comment]
Could you please add a test for the change?

**Comment by sancheolz** [comment]
@marek-safar Test added

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by sancheolz** [comment]
@marek-safar, Is any changes needed?

**Comment by marek-safar** [comment]
Thank you!

**Comment by sancheolz** [comment]
Please backport it to stable branches.

**Comment by marek-safar** [comment]
@monojenkins backport 2019-04

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Pull request merged**
