### PR TITLE
Bump build requirement to 10.9 mavericks

### LINKED ISSUE #9581: Update macOS minimal version
Due to limitations in the TLS stack on 10.7, we are updating the minimum macOS development target from 10.7 to 10.9. Mono will be supported only on 10.9 or newer versions.

We need to update configure checks and documentation at least at https://www.mono-project.com/docs/about-mono/supported-platforms/macos/

### PR DESCRIPTION
**Pull request by kg**
Fixes #9581

How do I check that I have the right llvm triple for 10.9? As far as I can tell they aren't documented anywhere and the recommended approach is 'run llvm on a machine that matches the desired triple', which is not really an option I have. There were at least two darwin releases for 10.9.

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by baulig** [comment]
Once this has landed, we need to back port to `2018-08` and then also do some changes in `xamarin-macios`.

**Comment by kg** [comment]
@marek-safar @alexischr does that mean I need to adjust this so it only changes the minimum?

**Comment by alexischr** [comment]
No I think it’s fine, just clarifying against the title that the intent was to raise the target version

________________________________

**Comment by akoeplinger** [comment]
@monojenkins backport 2018-08

**Pull request merged**
