### PR TITLE
[DO NOT MERGE] [jit] Simplified implementation of generic sharing.

### PR DESCRIPTION
**Pull request by vargaz**
These changes aim to simplify the generic sharing code in the JIT. The design is the following:
- Every shared method receives a MonoMethodRgctxArg pointer in the rgctx register.
- The 'mrgctx' field of this structure points to the runtime generic context for that method.
- The method lazily initializes the mrgctx on the first call.
- Each piece of data is stored in the mrgctx, at an offset
  known at compile time. No data is stored in the vtable.

Advantages:
- Greatly simplifies the generic sharing code.
- The rgctx trampolines are no longer needed.
- Every piece of data can be loaded from the mrgctx
  using two loads without a call which clobbers registers.

Disadvantages:
- Every shared method requires an rgctx argument/rgctx trampoline.
- Need to lazily initialize the mrgctx in the method prolog, which
  in the best case is a load and a non taken branch.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build

**Comment by vargaz** [comment]
builddeb

**Comment by vargaz** [comment]
builddeb

**Comment by vargaz** [comment]
builddeb

**Comment by vargaz** [comment]
builddeb

**Comment by lewurm** [comment]
@vargaz what's the deal with this PR?

**Comment by vargaz** [comment]
Performance problems prevented merging, it can be closed.

**Pull request closed without merging**
