### PR TITLE
When basic.exe isn't in DISTFILES, it gets excluded from `make dist`

### PR DESCRIPTION
**Pull request by directhex**
We can't just add basic.exe to `monolite_files`, as it's named mcs.exe in the build system, so work around it by adding it to `DISTFILES`

### CODE REVIEW

**Comment by lewurm** [comment]
builddeb

**Comment by lewurm** [comment]
the tarball build failed... with:
```
21:13:55 checking for cmake... no
21:13:55 configure: error: "cmake not found"
```
meh.

**Comment by directhex** [comment]
@lewurm I fixed that build lane to include cmake

It then failed later, due to `make dist` missing another folder entirely - I've now patched that in this PR, so `make dist` should be good. a builddeb will confirm (but Jenkins needs a restart first)

**Comment by directhex** [comment]
builddeb

**Comment by directhex** [comment]
OK, added cmake to the mono-snapshot build-deps

**Comment by directhex** [comment]
builddeb

**Comment by akoeplinger** [comment]
builddeb

**Pull request merged**
