### PR TITLE
Fix Bug #40969

### PR DESCRIPTION
**Pull request by adriancwp**
Fix Bug #40969
https://bugzilla.xamarin.com/show_bug.cgi?id=40969

### CODE REVIEW

**Comment by akoeplinger** [comment]
Please revert all the whitespace changes you did. We use tabs for indentation, not spaces.

**Comment by adriancwp** [comment]
Hi, I have reverted the whitespaces as requested, please check it again, thank you

**Comment by akoeplinger** [comment]
@adriancwp there are still a lot of unrelated code style changes (curly brace moved to separate line etc). I'd suggest you switch off auto formatting in your editor.

**Comment by adriancwp** [comment]
@akoeplinger I think it is finally clean enough. I am new to community, and thanks for your help.

**Comment by JustArchi** [comment]
This PR looks good now to me, anything stopping it from checking tests and merging?

**Comment by akoeplinger** [comment]
build

**Pull request merged**
