### PR TITLE
Fix Japan's new era fallback isn't reflected in Mono

### PR DESCRIPTION
**Pull request by acid-chicken**
refs: <https://github.com/dotnet/coreclr/pull/23614>

mcs side of the hard coded tables seems referenced from Blazor (client-side), but it's not updated yet.

FYI: <https://qiita.com/jsakamoto/items/da68cee22bbca187f389> (an article which describes this problem, written in Japanese)

### CODE REVIEW

**Comment by marek-safar** [comment]
@MaximLipnin please review

**Comment by marek-safar** [comment]
approve

**Comment by MaximLipnin** [comment]
LGTM. 
CoreCRL changes reflected here had been done after https://github.com/mono/mono/pull/12556 (IIRC there was no era name at that moment). 
Related point - should we update CLDR link in https://github.com/mono/mono/tree/master/tools/locale-builder?

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06

**Comment by marek-safar** [comment]
Thank you for your contribution!

**Pull request merged**
