### PR TITLE
[sdks] Cleanup wasm targets

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by luhenry** [comment]
I am trying to find a way to have the custom `build-wasm-interp` without removing the static pattern rules at https://github.com/luhenry/mono/blob/96c6efbd153b746fec77166f67f54d4a7a55e659/sdks/builds/Makefile#L48 with the objecting of removing `CUSTOM_BUILD_TARGETS`. That might take me way to far in the Makefile rabbit hole so I am submitting this PR for now with some simpler changes.

**Comment by kumpera** [comment]
If this technique works, can't we do that directly with the build-% pattern itself?

**Comment by luhenry** [comment]
@kumpera static pattern rules (`build-android-arm build-android-arm64: build-%: ...`) and implicit target rules (`build-%: ...`) do not behave the same when invoked directly (see https://www.gnu.org/software/make/manual/html_node/Static-versus-Implicit.html#Static-versus-Implicit).

**Comment by luhenry** [comment]
Note to self (I don't have my laptop on me), we need the following:

```
# static rule, needed because of prerequisite that might need to be built
build-android-arm: build-%: .stamp-%-configure
    make build-custom-$*

# implicit rule, cannot have a prerequisite that need to be but
build-custom-%:
    make -C $*
```

**Pull request merged**
