### PR TITLE
[runtime] Fix jay path in Microsoft.Build

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by vargaz** [comment]
LGTM if $(topdir) refers to the mcs topdir.

**Comment by alexanderkyte** [comment]
It does. In autoconf, it's $(mcs_topdir) but in all of the makefiles in /mcs, it's $(topdir)

**Comment by akoeplinger** [comment]
> LGTM if $(topdir) refers to the mcs topdir.

It does. I'm just startled how this ever worked? Is this not run normally?

**Comment by alexanderkyte** [comment]
I don't think it is actually. I think it's cached. 

dd0b8f31d90a9303eece3522d3e3ad5f8332b0bc

**Comment by akoeplinger** [comment]
Doesn't look like the generated .cs file is included anywhere. Out of curiosity, how did you come across this?

**Comment by alexanderkyte** [comment]
After rebasing my mobile_static PR that has some cosmetic changes and skipped tests, I was seeing intermittent failures on the bots related to this.

**Pull request merged**
