### PR TITLE
Fix decoding of WRAPPER_SUBTYPE_ICALL_WRAPPER and WRAPPER_SUBTYPE_INTERP_LMF.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
hmm, not sure what it fixes. Also what about `WRAPPER_SUBTYPE_INTERP_LMF`?

**Comment by jaykrell** [comment]
Just reading through the code, it looked wrong. Didn't debug to see why it ends up working or what it fixes.
I'll check others.

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by jaykrell** [comment]
Maybe remove the parameter.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
