### PR TITLE
[ci] Run "make" in parallel in run-jenkins.sh

### PR DESCRIPTION
**Pull request by akoeplinger**
To speed up the build.

### CODE REVIEW

**Comment by JustArchi** [comment]
Why ```-j4```? ```-j "$(grep -c processor /proc/cpuinfo)"``` :smile:

**Comment by alexrp** [comment]
Can we also run with `-Orecurse` to maintain some semblance of readability?

**Comment by akoeplinger** [comment]
@JustArchi because OSX/Windows don't have `/proc/cpuinfo` 😄. We could probably do some cross-plat code but I think -j4 should be enough for the bots we have on Jenkins for now. If you want to send a PR we can check how much it improves.

@alexrp the only problem with that is it requires Make v4.0+, which a couple of our targets don't have. I could add some version detection magic though.

Here are the results so far:

|	|before|	after|	improvement|
|----|-------|-------|--------------|
|Linux AArch64|	01:07:58|	00:29:10|	57%|
|Linux x64 FullAOT|	00:12:56|	00:10:01|	23%|
|Linux ARMv5 soft float|	01:19:08|	00:27:27|	65%|
|Linux ARMv7 hard float|	01:11:29|	00:31:57|	55%|
|Linux i386|	00:26:04|	00:15:58|	39%|
|Linux x64|	00:25:58|	00:24:19|	6%|
|OS X i386|	00:41:54|	00:31:52|	24%|
|OS X x64|	00:40:40|	00:31:24|	23%|
|Windows i386|	01:06:24|	00:37:10|	44%|
|Windows x64|	00:57:59|	00:35:40|	38%|

**Comment by alexrp** [comment]
For the targets with an older Make, couldn't we just upgrade?

**Comment by akoeplinger** [comment]
@alexrp maybe @directhex can shed more light on this but I think it would involve adding some backports repo or compiling a newer make ourselves.

I'm not sure it's worth the complexity just to get a better log on those targets. Make failures should be consistent so rerunning a job with -j1 in the rare event that we can't figure something out sounds good enough for me.

**Comment by directhex** [comment]
Make 4.0+ is available on Linux if we shift our targets to at least Debian 8 and Ubuntu 16.04 (from 7 and 14.04)

**Comment by akoeplinger** [comment]
I merged the first commit to master. We're still hitting issues when --output-sync=recurse is used e.g. on the Linux AArch64 lane where the parser script doesn't see the end marker because it is mixed in the line like this:

```
/media/ssd/jenkins/workspace/test-mono-pull-request-arm64/mcs/class/Mono.Security.Providers.NewSystemSource/./../../class/lib/xammac_net_4_5/System.dll (L*** end(1423): make: Passed
ocation of the symbol related to previous warning)
```

I'll figure out what we need to change in the parser, but in the meantime let's enjoy the faster builds 😄

**Pull request closed without merging**
