### PR TITLE
Replace two element hash table with two element array and cheap linear search.

### PR DESCRIPTION
**Pull request by jaykrell**
Maybe I misunderstand the code?
Or significant expansion is expected?

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux i386

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
