### PR TITLE
Cherry-pick alexanderkyte PRs #2781 #2783 #2785 #2786

### PR DESCRIPTION
**Pull request by xmcclure**
All memory leak related

### CODE REVIEW

**Comment by xmcclure** [comment]
Make failures appear spurious. However in a local make check there appears to be a consistent crash when verifying Commons.Xml.Relaxng.dll not present without these patches

**Comment by akoeplinger** [comment]
build

**Comment by xmcclure** [comment]
Additional fix fixes the crash we were seeing in the tests. I also ported the fix to master as PR #2834.

**Comment by xmcclure** [comment]
Updated my added commit based on feedback in #2834

**Comment by kumpera** [comment]
LGTM

**Comment by xmcclure** [comment]
Hard float Linux failure is due to timeouts. Going to assume this is unrelated to the PR.

**Pull request merged**
