### PR TITLE
[profiles] Fix MOBILE assemblies and tests compilation

### PR DESCRIPTION
**Pull request by ludovic-henry**
This only fixes the compilation of the assemblies and the tests. This doesn't fix the failing tests or the crashes.

### CODE REVIEW

**Comment by ludovic-henry** [comment]
Depends on https://github.com/mono/mono/pull/3993

**Comment by marek-safar** [comment]
What are you using this profile for?

**Comment by ludovic-henry** [comment]
@marek-safar I am using this profile for the same purpose we use `mobile_static` for: testing it in CI. I made sure to not change the `monodroid` and `xammac` profile which depended on `mobile_dynamic_dir`.
The end goal is to test hybrid AOT in CI, and `mobile` is the closest to `monodroid` and it's the only one which is not used by any product (same as `mobile_static`)

**Comment by marek-safar** [comment]
Then please create another profile called `aot_hybrid` we are renaming mobile_static to `aot_full`

**Comment by ludovic-henry** [comment]
if you are renaming mobile_static to aot_full, can we also rename mobile to aot_hybrid? it is the only use of it

**Comment by akoeplinger** [comment]
Marek asked me to do the rename, so we should coordinate on it. I'm 👍 on renaming mobile -> aot_hybrid if no one else is using it.

**Comment by marek-safar** [comment]
Ideally I'd like to see "correct" patch to land instead of 2 commits where the second one changes most of the first one but will leave it to @akoeplinger to sort this out

**Comment by ludovic-henry** [comment]
build

**Pull request merged**
