### PR TITLE
[amd64] Fix mingw-w64 build.

### PR DESCRIPTION
**Pull request by madewokherd**
It lacks _In_reads_ and _Inout_.

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, the Windows CI build is green before your change and that builds with mingw-w64. Which version are you using?

**Comment by madewokherd** [comment]
x86_64-w64-mingw32-gcc (GCC) 5.3.1 20160211

**Comment by akoeplinger** [comment]
We're using 5.4.0. Maybe we're just missing include for sal.h: https://msdn.microsoft.com/en-us/library/hh916383.aspx ?

I wonder why it builds on Jenkins us though.

**Comment by madewokherd** [comment]
Adding the sal.h include does not fix it for me.

**Comment by madewokherd** [comment]
Apparently the mingw compiler and headers on Ubuntu 16.04 are not the same version.

Compiler: 5.3.1-8ubuntu3+17 http://packages.ubuntu.com/xenial/devel/gcc-mingw-w64-x86-64
Headers: 4.0.4-2 http://packages.ubuntu.com/xenial/devel/mingw-w64-common

**Comment by madewokherd** [comment]
Huh, seems that's normal for mingw-w64.

Jenkins is still slightly newer, maybe it has more SAL things defined.

**Comment by madewokherd** [comment]
Tried that already, it did not help.

**Comment by akoeplinger** [comment]
@madewokherd I talked to @lateralusX who added these typedefs and he said we can just remove the `_In`, `_Out_` etc markers, they're not used anywhere else. Can you please make that change?

**Comment by madewokherd** [comment]
Updated to remove SAL annotations.

**Pull request merged**
