### PR TITLE
Avoid using GNU make $shell to get monolite version

### PR DESCRIPTION
**Pull request by saper**
Avoid using $(shell) - it silently
fails on some make programs other
than GNU make.

For example, FreeBSD gets empty value here
and the URL is malformed.

### CODE REVIEW

**Comment by marek-safar** [comment]
I don't think this will work for those who do only incremental checkouts/builds

**Comment by alexrp** [comment]
We have always required GNU `make` for the build process. I don't think it's worth it to try to make the makefiles work with other `make` implementations since GNU `make` exists virtually everywhere anyway.

**Comment by saper** [comment]
You are right. Pulling autoconf is a bad idea for this. The reason I wanted to change this is because BSD make actually works for the whole build process and this is the only incompatibility I could fine.
Second reason is that it fails silently i.e. it tries to fetch the incorrect URL instead of failing with an error message or something like that.

The followup change https://github.com/saper/mono/commit/598968224000bc482e0b450619c55846d473122a seems to work on both `make`s well, with `wget` as well as with `curl`.

**Comment by jasonwilliams200OK** [comment]
@alexrp, will this patch be available in mono v.next tagged release code? FreeBSD support is varying between 99-100% with current master. These small but tricky patches stick it to 100% and above. :)

**Comment by saper** [comment]
@jasonwilliams200OK It does not impact FreeBSD really, as we are using GNU make to build mono as well. I think I'll close this for now.

**Pull request closed without merging**
