### PR TITLE
Pull 1281 test only

### PR DESCRIPTION
**Pull request by madrang**
Test add and changes of https://github.com/mono/mono/pull/1281

```
Tests run: 10018, Failures: 32, Not run: 99, Time: 130.704 seconds

Test Case Failures:
1) MonoTests.System.Security.Cryptography.HashAlgorithmTest.Hash_DisposedException : An unexpected exception type was thrown
Expected: System.ObjectDisposedException
 but was: System.Security.Cryptography.CryptographicUnexpectedOperationException : No hash value computed.
at System.Security.Cryptography.HashAlgorithm.get_Hash () [0x0001b] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/System.Security.Cryptography/HashAlgorithm.cs:133
at MonoTests.System.Security.Cryptography.HashAlgorithmTest.Hash_DisposedException () [0x0000b] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/Test/System.Security.Cryptography/HashAlgorithmTest.cs:518
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

2) MonoTests.System.Security.Cryptography.HashAlgorithmTest.Hash_NoExternalChanges :   ExternalChanges
  Expected: not < 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 >
  But was:  < 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 >

at MonoTests.System.Security.Cryptography.HashAlgorithmTest.Hash_NoExternalChanges () [0x00051] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/Test/System.Security.Cryptography/HashAlgorithmTest.cs:509
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

3) MonoTests.System.Security.Cryptography.HMACMD5Test.Hash_DisposedException : An unexpected exception type was thrown
Expected: System.ObjectDisposedException
 but was: System.Security.Cryptography.CryptographicUnexpectedOperationException : No hash value computed.
at System.Security.Cryptography.HashAlgorithm.get_Hash () [0x0001b] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/System.Security.Cryptography/HashAlgorithm.cs:133
at MonoTests.System.Security.Cryptography.HashAlgorithmTest.Hash_DisposedException () [0x0000b] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/Test/System.Security.Cryptography/HashAlgorithmTest.cs:518
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

4) MonoTests.System.Security.Cryptography.HMACMD5Test.Hash_NoExternalChanges :   ExternalChanges
  Expected: not < 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 >
  But was:  < 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 >

at MonoTests.System.Security.Cryptography.HashAlgorithmTest.Hash_NoExternalChanges () [0x00051] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/Test/System.Security.Cryptography/HashAlgorithmTest.cs:509
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /home/madrang/WorkSpace/CSharp/Online/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230
```

### CODE REVIEW

**Comment by alexrp** [comment]
@spouliot can you review this?

**Comment by madrang** [comment]
One day maybe ?

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by madrang** [comment]
I have a dll that throws an exception without this. All this time i had to rebuild from src with my changes. But now i'm getting used to it....

**Pull request closed without merging**
