### PR TITLE
[merp] Fix return value handling of posix_spawn

### PR DESCRIPTION
**Pull request by alexanderkyte**
@slluis requested this change be merged by tomorrow to make a release window

### CODE REVIEW

**Comment by alexanderkyte** [comment]
It seems the 2018-02 backport was merged. I'm not going to revert that. I will close and update my updated error formatting to the 2018-04 and 2018-06 PRs.

**Comment by alexanderkyte** [comment]
@monojenkins backport 2018-06

**Comment by alexanderkyte** [comment]
@monojenkins backport 2018-04

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Pull request merged**
