### PR TITLE
[wasm][debugger] Add support for invoking getters on valuetypes

### PR DESCRIPTION
**Pull request by radical**
- This includes bunch of other fixes, and improvements made along the way

### CODE REVIEW

**Comment by radical** [comment]
This is based on the pointers PR (https://github.com/mono/mono/pull/19760).

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
This is split into smaller logical commits that build upon the previous ones, which should help reviewing. I have rebased it on `master`.
@kg I would appreciate a review, especially of the js bits.

**Comment by radical** [comment]
Rebased

**Comment by radical** [comment]
Closing in favor of: https://github.com/dotnet/runtime/pull/40548

**Pull request closed without merging**
