### PR TITLE
update to Android P final API.

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by atsushieno** [comment]
Now everything is complicated; mono sdks build requires this change, and xamarin-android requires changes for the duplicate purpose...

**Comment by luhenry** [comment]
@monojenkins backport to 2018-02

**Comment by luhenry** [comment]
@monojenkins backport to 2018-04

**Comment by luhenry** [comment]
@monojenkins backport to 2018-06

**Pull request merged**
