### PR TITLE
[cxx] ARM_EMIT w/o address-taken

### PR DESCRIPTION
**Pull request by jaykrell**
Alternative to https://github.com/mono/mono/pull/9954#discussion-diff-208670369R24.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
What exactly is the problem with the original version ?

**Comment by jaykrell** [comment]
Assignment from void* to non-void*, where p is updated at the end.

**Comment by jaykrell** [comment]
Temporarily closing, trying another approach.

**Comment by jaykrell** [comment]
This is a fine approach.
Or we can use `g_cast` from https://github.com/mono/mono/pull/10027.

**Pull request closed without merging**
