### PR TITLE
Default powerpc to build with mcs

### PR DESCRIPTION
**Pull request by akoeplinger**
It crashes during build with roslyn on Jenkins.

### CODE REVIEW

**Comment by marek-safar** [comment]
Is that recent change? Do we know why (existing bug number) ?

**Comment by akoeplinger** [comment]
No, it's not recent, it started with the roslyn merge. I don't know how much we care about PPC so I opted for the quick fix.

**Comment by akoeplinger** [comment]
@monojenkins build powerpc

**Comment by akoeplinger** [comment]
It fixes the PPC build, so I'll merge. Let me know if I should file a bug for the roslyn crash on PPC.

**Comment by marek-safar** [comment]
Please fill a bug report, I think @BrzVlad has some pending fixes which could address that

**Comment by BrzVlad** [comment]
I've seen occasional rare crashes, but overall I was able to build ppc with roslyn with https://github.com/mono/mono/pull/4306. After merging it most of the crashes should go away and we can move on from there.

**Comment by akoeplinger** [comment]
@BrzVlad awesome, thanks. Once your PR is in I'll open a PR reverting this one and kick off a few builds to make sure we're good.

**Comment by marek-safar** [comment]
Great, could you revert this in your PR then

**Comment by BrzVlad** [comment]
@akoeplinger I've included the revert in my PR. Can you actually trigger a ppc build with it to see where we are ?

**Pull request merged**
