### PR TITLE
nuget-hash-extractor: Add msbuild extensions nuget version from vs15.…  …

### PR DESCRIPTION
**Pull request by radical**
…6 msbuild branch

Version `2.1.100-preview-62617-01` from:

https://github.com/dotnet/cli/blob/b9e74c65201ef39c74b6d75cedbb605a88cd26ec/build/DependencyVersions.props

Also, update the list in the runtime and deniedAssembliesList.txt
installed for use by msbuild.

### CODE REVIEW

**Comment by marek-safar** [comment]
Is this some random preview version or is distributed widely?

**Comment by radical** [comment]
This is being used with VS15.6 . It is taken from the cli repo's `release/2.1.1xx` branch which is used for vs15.6, and it's HEAD has this version. And we'll have this version used in our 2018-02 branch.

**Comment by radical** [comment]
backport to 2018-02 PR #7379

**Comment by radical** [comment]
Mono build was broken, so rebased on latest master.

**Comment by radical** [comment]
`Linux AArch64` is failing because mono runtime crashed while running a socket test (https://jenkins.mono-project.com/job/test-mono-pull-request-arm64/8534/consoleFull#-2001780300c04ca618-a109-447b-99e0-481aaedae630), unrelated to this PR. Can somebody please merge this?

```22:58:14   at (wrapper managed-to-native) System.Net.Sockets.Socket.Connect_internal (intptr,System.Net.SocketAddress,int&,bool) <0x00007>
22:58:14   at System.Net.Sockets.Socket.Connect_internal (System.Net.Sockets.SafeSocketHandle,System.Net.SocketAddress,int&,bool) [0x00006] in /home/builder/jenkins/workspace/test-mono-pull-request-arm64/mcs/class/System/System.Net.Sockets/Socket.cs:1148```

**Comment by radical** [comment]
@marek-safar @akoeplinger ^

**Pull request merged**
