### PR TITLE
Define getters for MonoClass fields

### PR DESCRIPTION
**Pull request by lambdageek**
The goal is, in combination with #6611, to make the definition of `MonoClass` private and to access all fields via getter methods.

This PR moves the field definitions for MonoClass out to a separate file and uses it to automatically define getters of the form `FooType* m_class_get_foo (MonoClass *)`

### Collected feedback

1. The use of macros for field definition and getter declarations makes the code less discoverable.
    We don't expect new fields to be added frequently enough that the macros are helping us.
    Also the longer-term goal for the getters is to add checked build assertions to them to ensure
    that a field is accessed only after the `MonoClass` has been initialized sufficiently to setup that
    field.  So getters for various fields would still need to be tweaked individually.

    My response: I basically agree with this.  I still want some helper macros for the getter bodies, I think, but having a readable `MonoClass` definition, and a readable list of getter declarations is pretty important.
2. One cute trick we could do is to make a vtable of getter functions so field accesses could look like: `mono_class_table.field (klass)`.  Longer term we could dispatch different classes to different getter implementations.

    My response: the cute pun doesn't look so cute anymore once we allow dynamic dispatch - `class_table (klass)->field (klass)` might as well be wrapped in a `m_class_get_field (klass)` call.  Plus I'm really not sold on the near-term need for dynamic dispatch.

3. Make it so that in non-checked builds the `MonoClass` definition is visible and all the getters are `static inline`.  In checked builds, hide the definition everywhere except the initialization code and the getter implementations.

   My response: 👍 

4. The boolean flag getters should have names like `m_class_is_unicode` or `m_class_has_finalizers` rather than `m_class_get_unicode` or `m_class_get_has_finalizers`, respectively.

   Response: okay, done.

### TODO

- [x] ~Hang the `MonoClass` definition hiding on a separate define.  Just `ENABLE_CHECKED_BUILD` is too broad and breaks, for example, the coop jenkins job (which is configured with `--enable-checked-build=thread,gc`)~

### CODE REVIEW

**Comment by joncham** [comment]
Very much appreciate work in this direction 👍

**Comment by luhenry** [comment]
I would prefer to keep the `MonoClass` struct fields more explicit. This macro based declaration of the struct make it quite hard to discover which fields it contains, making it harder to understand and safely evolve. The getters/setters could also be declared manually, as they shouldn't change very often (only when adding/removing a field, and even adding a field doesn't mandate a getter/setter). For the shorter name of `m_class_*` I am also ok with it (even if I would personally prefer `mono_class_*`).

As to having the `MonoClass` struct in a different file, I am definitely ok with that, as it would allow for the struct to be declared (via a `#include`) in `class-internals.h` with the getters/setters marked as `static inline` in non-checked-builds to allow for fast access by default, and for the struct to be declared in `class-init.c` with the getters/setters marked as `extern` in checked-build to ensure the fields are accessed via the getters/setters consistently.

**Comment by luhenry** [comment]
And for the dynamic dispatch, I don't understand what application we could make of it, and it seems like a overengineered solution for a problem we don't have.

**Comment by joncham** [comment]
I personally prefer `mono_class_*` naming.

As for dynamic dispatch, we (unity) don't need that. However, the use of accessor functions is very nice and allows us to change behavior without drastic changes to the code base. In general, the more opaques types the easier integration/migration for us is.

**Comment by vargaz** [comment]
We will have external functions named mono_class_..., the question is the internal naming, mono_class_get_ is too verbose since MonoClass is used very frequently in runtime code.

**Comment by joncham** [comment]
Is there any reason for the `m_` prefix then? Why not just `class_get_*`?

**Comment by lambdageek** [comment]
Updated.

1. `struct _MonoClass` kept as a normal struct definition.  Now lives in `class-private-definition.h`
2. Getters are still named `m_class_get_fieldname` (I think there's still ongoing debate about what they should be called)
3. Getters are explicitly declared so you can  grep for `m_class_get_whatever` and find its declaration and definition sites.
4. In checked build mode, the getters are declared in `class-internals.h` but defined in `class-accessors.c`.  In a normal build, they are `static inline` in the header.

**Comment by vargaz** [comment]
- Maybe we should drop the _get_ part as well, to make it even less verbose.
- The getters returning flags should probably like m_class_is_marshalbyref or something.

**Comment by luhenry** [comment]
@vargaz I don't like dropping the `get` part, it just make it harder to understand it's a getter without looking at the code, and without the background knowledge you already have; it can't be that bad to write these 3 characters 😉 For the `is` part for flags, sounds like a good idea to me.

**Comment by lambdageek** [comment]
So I tried changing from `m_class_get_foo` to `m_class_is_foo` for flags... I don't like it.  Here are some flag names:

* `size_inited` -> `m_class_is_size_inited`: GREAT
* `unicode` -> `m_class_is_unicode`: GOOD
* `wastypebuilder` -> `m_class_is_wastypebuilder`: UH OH
* `is_array_special_interface` -> `m_class_is_is_array_special_interface`: 👎 
* `has_finalize` -> `m_class_is_has_finalize`: 😢

The advantage of `m_class_get_is_array_special_interface` is that:
1. It's consistent with all the other getters: there is just one pattern - `m_class_get_FIELDNAME`. 
2. It's such bad english that there's no temptation to try to read it as good english.

**Comment by vargaz** [comment]
We should make the is_ getters have sensible names, not auto generate them, i.e.
m_class_has_finalizer (), m_class_was_typebuilder (), etc.

**Comment by vargaz** [comment]
Not that these accessors are used _very_ frequently, so they have as short names as possible.

**Comment by lambdageek** [comment]
@vargaz I worry that if the `_is_` getters have too many different names it would be difficult to discover them.  But alright, I'll try it with handwritten names and update the PR.

**Comment by lambdageek** [comment]
Latest iteration:
- boolean flag getters have names like `m_class_is_unicode` and `m_class_has_finalizers` instead of `m_class_get_unicode` or `m_class_get_has_finalizers`, respectively.  See 611fed85951 for the full list.
- I moved the getter definitions to `class-getters.h` but the full getter function names are in there without token pasting.  This is, I think, an okay compromise between having to write everything twice but also keeping the getters discoverable.

I think at this point this isn't a request for comments anymore, but a PR for review.

**Comment by vargaz** [comment]
Would it be possible to merge the getters and slowly convert the runtime code to use them ? If we want to have a giant merge which changes all call sites, it will conflict with all the active PRs etc.

**Comment by lambdageek** [comment]
Yes! Right now in a normal build it is okay to keep using `klass->field`.

But if you use `./autogen.sh --enable-checked-build=private_types` you will get compile errors unless you use a getter.

**Pull request merged**
