### PR TITLE
[msbuild] Bump to the d15.4 branch HEAD

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@akoeplinger yeah, I need to figure out how to get that version from `msbuild.py` at that step! Or since the version here is not of any real consequence, AFAIK, we just use a fixed value. Or we manually clone the script and fix the path whenever that changes.

**Comment by akoeplinger** [comment]
@radical some grep magic like `grep -oh "15.\d" packaging/MacSDK/msbuild.py` would do the job :)

**Comment by radical** [comment]
heh yeah, I was hoping for something cleaner! But yeah, sure.

**Comment by radical** [comment]
I will check with @alexischr anyway!

**Pull request merged**
