### PR TITLE
[runtime] Overwrite stacktrace for exception on re-throw. Fixes #1856.

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
This fixes a bug where we did not completely mimic .NET's exception handling.

We previously held onto the stacktrace when an exception was thrown if it already had one. This differs from how .NET behaves, which is to always set the stacktrace to the place that it was last thrown.

Ex:
```
using System;

class C
{
    static Exception e;

    static void Throw ()
    {
        try {
            int.Parse (null);
        } catch (Exception ex) {
            e = ex;
        }
    }

    public static void Main ()
    {
        Throw ();

        try {
            throw e;
        } catch (Exception ex) {
            Console.WriteLine (ex.StackTrace);
        }
    }
}
```

Would previously output:
```
  at System.Int32.Parse (System.String s) [0x00000] in <filename unknown>:0 
  at C.Throw () [0x00000] in <filename unknown>:0
```

when 
```
   at C.Main()
```
is what .NET output. After this commit we output the same stacktrace as .NET.

**Comment by marek-safar** [comment]
The test needs to be added to test suite

**Comment by knocte** [comment]
It's recommended that you put that description of what the commit fixes, also, in the commit message, not just the PR.

**Comment by alexanderkyte** [comment]
@knocte: The commit message seemed fairly clear to me. We weren't overwriting the stacktrace for an exception when we re-threw it.

**Comment by alexanderkyte** [comment]
@marek-safar The tests were force-pushed. The test added seemed like the best way to do it to me, given the fact that most fields of Exception are private.

**Comment by directhex** [comment]
build

**Comment by alexanderkyte** [comment]
The builds failed for an unrelated reason. 
``` FATAL: Could not checkout null with start point 5124a7f1c17252fe6366c8e79a056f28760b593d ```

Can someone kick it back off for me?

**Comment by akoeplinger** [comment]
build

**Comment by akoeplinger** [comment]
@alexanderkyte you're whitelisted on Jenkins, so you should be able to kick off the build yourself (though I've seen on your other PR it didn't work, maybe a temporary glitch?)

**Comment by akoeplinger** [comment]
@alexanderkyte looks like the commit failed to checkout on jenkins (this is a bug on github's end afaik), I'd suggest rebasing and force-pushing to get a new build started.

**Comment by alexanderkyte** [comment]
It's the force push bug with jenkins.

**Comment by alexanderkyte** [comment]
Rebuild last

**Comment by akoeplinger** [comment]
build

**Comment by alexrp** [comment]
build

**Comment by alexanderkyte** [comment]
So I'm seeing pinvoke code break on arm, while this works fine on x86/amd64. After a glance at the arm changes in context, I don't see how this could break pinvoke. Are these tests green on master for arm?

**Comment by vargaz** [comment]
A lot of tests are not green on arm.

**Pull request merged**
