### PR TITLE
Fix Mono Windows cross compiler using mono LLVM release_60 branch.

### PR DESCRIPTION
**Pull request by lateralusX**
Fix Mono Windows cross compiler using mono LLVM release_60 branch.

For scenario where llvm-config.exe can't be run (none WSL/CygWin build target) build will fallback to hard coded libraries not working with mono LLVM release_60 branch.

Added an exact mirror of what llvm-config.exe is returning for different components on mono LLVM master and mono LLVM release_60 branch.

The selected codegen libraries (passed in as extra_libs) was not handled in any cases so added them into the build script as well.

Above successfully builds using mono LLVM master and mono LLVM release_60 branches and links into Windows mono cross compiler build on Linux.

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by luhenry** [comment]
@lateralusX let’s see how it builds for the Android builds. It should be building all of them now.

**Comment by lateralusX** [comment]
@luhenry Looks like the checks are successful. The failure seen on OS X x64 iOS SDK occurs on other PR's as well and looks unrelated. The Android SDK builds looks fine. One question, looks like the Android SDK builds mono cross compilers builds for macos as it's host OS but I couldn't find any build step of mono cross compiler targeting windows as host os of build cross compiler? Should those steps be done as well as part of the Android SDK build?

**Comment by luhenry** [comment]
@lateralusX you should uncomment https://github.com/mono/mono/blob/master/scripts/ci/run-jenkins.sh#L144 and remove https://github.com/mono/mono/blob/master/scripts/ci/run-jenkins.sh#L145. This will enable building the cross compilers with "host Win32 + target Android".

**Comment by lateralusX** [comment]
Build failure in OS X x64 Android SDK seems to be caused by different problem. Build includes Unix sources when building Windows cross compiler, https://github.com/mono/mono/blob/bfc35fc6e65307290c75d7a14742c1ca036c912a/mono/metadata/Makefile.am#L186.

I guess these source files should only be included when building !HOST_WIN32 instead of !TARGET_WIN32 to support Windows cross compiler targeting none windows platform build scenarios?

**Comment by lateralusX** [comment]
@monojenkins backport to 2018-08

**Pull request merged**
