### PR TITLE
[wasm][sdk] Fix issue with WasmLinkAssemblies task wrongly using refe…

### PR DESCRIPTION
**Pull request by kjpou1**
…rence assemblies

The [issue](https://github.com/mono/mono/issues/15823) is that when executing the `WasmLinkAssemblies` task the reference assemblies are currently used as input to the linker step and output in the published application instead of the actual framework library file.

My findings so far on this is that the package references are resolved in the MSBuild [ResolvePackageAssets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs#L205.)

Those are then remapped from [here](https://github.com/dotnet/sdk/blob/ec9f5fc673f798dd6a89c7d11a4e62727837757c/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets#L270) to the `RuntimeCopyLocalItems`.

What I did was pass the `RuntimeCopyLocalItems` to the `WasmLinkAssemblies` task and do a remap to the runtime versions.  This works against everything I have thrown at it so far.

Of course this could fail if the nuget has somehow set `copy to local` false maybe but I do not see anything in the code referenced above checking for that.

Fixes https://github.com/mono/mono/issues/15824
Fixes https://github.com/mono/mono/issues/15823

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@radical does the above seem reasonable?

**Comment by mhutch** [comment]
This seems reasonable to me, but runtime asset copying is an area of MSBuild I'm not super familiar with

**Pull request merged**
