### PR TITLE
Remove nunit24 from mono build and tree

### PR DESCRIPTION
**Pull request by MaximLipnin**
Fixes https://github.com/mono/mono/issues/12845

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
The All Profiles & Project FIles Diff jobs both track changes to the csproj files, which I would expect this job to reflect

**Comment by MaximLipnin** [comment]
@directhex Could you please clarify what you mean?

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Comment by directhex** [comment]
I mean what Marek just did :grin:

**Pull request merged**
