### PR TITLE
[Facades] Adds System.Threading.Tasks.Extensions for mobile profiles

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by marek-safar** [comment]
@akoeplinger why? that table is used by desktop loader only and the facade is mobile only

**Comment by akoeplinger** [comment]
Ok, I found a few of the other mobile-only facades in there but e.g. System.Memory.dll and System.Drawing.Common.dll is missing. Would be nice to have everything in there even if it's not needed just for consistency :)

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Comment by marek-safar** [comment]
@monojenkins backport 2018-08

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff and csproj

**Comment by onovotny** [comment]
This is causing active pain with users today. Getting these facades out cannot wait until the next VS release, IMO, as 15.8 just shipped. It's too long to wait.

I really think this has to be in a 15.8.x servicing release.

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by ahmedalejo** [comment]
> @monojenkins backport 2018-04

Hi @marek-safar how could we try out this backport?
currently using Xamarin.Android.SDK v9.0.0.19

**Comment by marek-safar** [comment]
@ahmedalejo I don't we have any available build with the fix for Xamarin.Android because the issue was not reported

@jonpryor can give you better estimate when this is going to be fixed for XA

**Comment by ahmedalejo** [comment]
> @ahmedalejo I don't we have any available build with the fix for Xamarin.Android because the issue was not reported
> 
> @jonpryor can give you better estimate when this is going to be fixed for XA

Thanks for this quick feedback much appreciated

**Pull request merged**
