### PR TITLE
[wasm][http] Fix premature disposal of object causing crash in HttpClient

### PR DESCRIPTION
**Pull request by kjpou1**
Fix problem with fetch response header iteration prematurely disposing of headers object.

- Modify `WasmHttpMessageHandler.cs` to use the `Headers` iterator instead of it's `forEach` method to iterate over the header values returned.
- Add regression tests.

Fixes: https://github.com/mono/mono/issues/14940

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
> From looking at this, I also don't understand why this is needed - how was the old code previously disposing objects and why do we need this private class instead of some more simple approach?

Will change this to simpler approach.

**Comment by kjpou1** [comment]
@baulig 

Simplified the code.  Ready to take another look when you want.

**Comment by baulig** [comment]
> @baulig
> 
> Simplified the code. Ready to take another look when you want.

Looks good :-)

**Comment by lewing** [comment]
@monojenkins build failed

**Pull request merged**
