### PR TITLE
Support native-to-managed thiscall wrappers

### PR DESCRIPTION
**Pull request by madewokherd**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Not sure why the bot didn't post a comment, but can you please sign the CLA at https://cla2.dotnetfoundation.org ?

**Comment by akoeplinger** [comment]
@madewokherd I don't think we have any forms for that, that's something you need to arrange between your employer and you :)

**Comment by vargaz** [comment]
Looks ok, please use the mono coding conventions (K&R indentation, spaces before (, etc.).

**Comment by luhenry** [comment]
@monojenkins build Windows i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Interpreter

**Pull request merged**
