### PR TITLE
[msbuild] Bump to latest xplat-master

### PR DESCRIPTION
**Pull request by radical**
.. which is now on the netcore2.x based build. Update build and test
scripts accordingly.

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by luhenry** [comment]
@radical feel free to remove the `do-not-merge` label as soon as you think it's good to merge.

**Comment by radical** [comment]
Waiting on https://github.com/mono/msbuild/pull/51 .

**Comment by radical** [comment]
Ready for merge, @akoeplinger .

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by akoeplinger** [comment]
The OS X Extended build failed while trying to build msbuild:

```
01:57:32 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/NuGet.targets(104,5): error : Failed to download package 'XliffTasks.0.2.0-beta-000081' from 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/xlifftasks/0.2.0-beta-000081/xlifftasks.0.2.0-beta-000081.nupkg'. [@/external/bockbuild/builds/msbuild-15/src/Build/Microsoft.Build.csproj]
01:57:32 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/NuGet.targets(104,5): error : The HTTP request to 'GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/xlifftasks/0.2.0-beta-000081/xlifftasks.0.2.0-beta-000081.nupkg' has timed out after 100000ms. [@/external/bockbuild/builds/msbuild-15/src/Build/Microsoft.Build.csproj]
01:57:32 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/NuGet.targets(104,5): error : The feed 'dotnet.myget.org dotnet-core v3 [https://dotnet.myget.org/F/dotnet-core/api/v3/index.json]' lists package 'XliffTasks.0.2.0-beta-000081' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [@/external/bockbuild/builds/msbuild-15/src/Build/Microsoft.Build.csproj]
01:57:32 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/NuGet.targets(104,5): error :   Unable to find package 'XliffTasks.0.2.0-beta-000081'. [@/external/bockbuild/builds/msbuild-15/src/Build/Microsoft.Build.csproj]
```

I've rescheduled it but are we sure these artifacts will stay on that Azure container?

**Comment by akoeplinger** [comment]
New build looks good (runtime-tests-llvm failed because of #8462).

**Pull request merged**
