### PR TITLE
[sdb] Add reference counting for single step requests, they can be accessed concurrently by the single step processing code and the event request clearing code.

### LINKED ISSUE #7137: Step in crashes debugger
## Steps to Reproduce

1. Checkout https://github.com/xamarin/xamarin-macios (5788a9fa9ba08fea34e0e28d7810d5f4637229d8) and all its submodules. It's **not** necessary to build xamarin-macios.
2. Run the following commands in the root xamarin-macios directory:

```shell
make -C tests test.config
make -C tools/mtouch SdkVersions.cs
```

3. Open tests/xharness/xharness.sln

4. Open `Jenkins.cs` and put a breakpoint on line 243:

screenshot 2018-02-20 12 45 04

5. Run the project. When the breakpoint is hit, step into (sometimes I have to step into twice, sometimes it crashes immediately).

## Current Behavior

Crash. Complete output: https://gist.github.com/rolfbjarne/d5d540ed5a8c61de85902c685e5fad37

## Expected Behavior

No crash.

### On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

```
Visual Studio Community 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 985)
Installation UUID: 3de793cc-1bea-4b7e-9e90-bb6747c5ca7e
Runtime:
	Mono 5.10.0.15 (2017-12/907075a5f01) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 510000015

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.5.5
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Version: 4.4.0.0 (Visual Studio Community)

Xamarin.iOS
Version: 11.10.0.1 (Visual Studio Community)
Hash: 61e589640
Branch: maccore-issue-641-d15-7
Build date: 2018-02-20 11:43:43+0100

Xamarin.Android
Version: 7.0.99.113 (Visual Studio Community)
Android SDK: Not found

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704000985
Git revision: 0bed5a3380dbe82009f80c895623208d6c0df152
Build date: 2018-02-02 20:00:14-05
Xamarin addins: 612453baa9a0faea49aa554be49c01c2e0542bf3
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jan 11 22:59:40 PST 2018
    root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

```

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/7137

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Pull request merged**
