### PR TITLE
[sdks] dynamically link libmonosgen to mono-sgen for monodroid host builds

### PR DESCRIPTION
**Pull request by lambdageek**

### CODE REVIEW

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@grendello @radekdoulik would a 2019-06 backport of this be good enough - I don't think I want to land this on 2019-02 right now

**Comment by jaykrell** [comment]
Imho all the platforms should do this, use $ORIGIN on Linux etc., Apple equivalent, and on Windows put .dll and .exe in same directory if not already.

**Comment by radekdoulik** [comment]
I think 2019-06 backport would be enough (and great) for us.

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-06

**Pull request merged**
