### PR TITLE
[threadpool-ms] Switch Monitor thread to a MonoThreadInfo

### PR DESCRIPTION
**Pull request by ludovic-henry**

### CODE REVIEW

**Comment by vargaz** [comment]
How does the runtime wait for this thread to terminate on shutdown ?

**Comment by ludovic-henry** [comment]
@vargaz: it's waiting cooperatively for it to shutdown, in `threadpool-ms.c:cleanup`

**Comment by vargaz** [comment]
Looks ok.

**Comment by ludovic-henry** [comment]
build

**Pull request merged**
