### PR TITLE
[sdb] Add back the mono_debugger_agent_parse_options () API function …

### PR DESCRIPTION
**Pull request by vargaz**
…which was mistakenly removed by #7673.

### CODE REVIEW

**Comment by vargaz** [comment]
Only to -06.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2018-06

**Pull request merged**
