### PR TITLE
Bump bockbuild for https://github.com/mono/bockbuild/pull/62

### PR DESCRIPTION
**Pull request by alexischr**
Do not merge as it still points to branch/PR commit

https://github.com/mono/mono/issues/6994

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
We should add `-L` to curl so it follows redirects (see e.g. https://github.com/mono/mono/pull/7202)

**Comment by lewurm** [comment]
I think we have to backport this to the release branches, right?

**Comment by alexischr** [comment]
yup, backport PRs are open, will be merged after master package build

**Comment by akoeplinger** [comment]
I did already merge them since the master build got past the package download stage :)

**Comment by akoeplinger** [comment]
#7206, #7207, #7208

**Pull request merged**
