### PR TITLE
Recognize OS X file "locked" state (fixes #37834)

### PR DESCRIPTION
**Pull request by xmcclure**
Quick fix for https://bugzilla.xamarin.com/show_bug.cgi?id=37834

IOLayer is_file_writable/System.IO.File.GetAttributes on posix systems looks only at the unix file permissions and does not consider special OS flags. This leads to an easily end-user-triggered bug on OS X if a mono app (the bug was observed in Xamarin Studio) uses GetAttribute on a file which has been "Locked" using the checkbox in Finder Get Info. This patch recognizes the "uchg" flag for non-writability which Finder uses.

### CODE REVIEW

**Comment by kumpera** [comment]
LGTM.

@monojenkins merge

**Comment by akoeplinger** [comment]
build

(GitHub had webhook issues a few hours ago, so this build didn't get scheduled)

**Comment by akoeplinger** [comment]
build

**Comment by marek-safar** [comment]
This should have test included

**Comment by xmcclure** [comment]
@marek-safar: I do have a test, where in the test suite would be the appropriate place to put it?

**Comment by marek-safar** [comment]
If you can make it nunit style add it to mcs/class/corlib/Test/ otherwise classic runtime test file

**Pull request merged**
