### PR TITLE
Fix for heap_use_after_free flagged by sanitizer

### PR DESCRIPTION
**Pull request by dseshadri**
This change is released under the MIT license.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/mono?pullRequest=21120) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/mono?pullRequest=21120) before we can accept your contribution.<br/><br/>:x: dseshadri [sign now](https://cla.dotnetfoundation.org/mono/mono?pullRequest=21120)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/mono?pullRequest=21120) it.</sub>

**Comment by dseshadri** [comment]
The issue that is being fixed was flagged by the address sanitizer. I was able to write a simple program to demonstrate the issue and was able to reproduce the sanitizer heap_use_after_free error. The root cause is that when the get_saved_signal_handler is called with a "True" boolean to delete the value in the hash table, the returned pointer is a pointer to the "value", which has been deleted. 
Note that, when a key-value pair is removed from the hash table, the deallocation function is also called on the "value" pointer, whieh means that the memory pointed to by the "value pointer" is no longer valid. When this pointer is returned by get_saved_signal_handler(), the pointer is no longer guaranteed to have memory allocated to it. 

This fix solves the problem by seperating the function into two:
get_saved_signal_handler(int signo)
remove_saved_signal_handler(int signo)

Thanks

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build failed

**Pull request merged**
