### PR TITLE
[netcore] Allow different enums as return type in CreateDelegate

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/mono/mono/issues/15008

Test case:
```csharp
using System;

public enum Enum1 : long
{
    A,
    B,
    C
}

public enum Enum2 : long
{
    A,
    B,
    C
}

public sealed class Program
{
    public Enum1 Test => Enum1.A;

    static void Main(string[] args)
    {
        var del1 = typeof(Program).GetProperty("Test").GetGetMethod().CreateDelegate(typeof(Func<Program, Enum1>));
        
        // the Test property is of Enum1 type but we can use Enum2 too
        var del2 = typeof(Program).GetProperty("Test").GetGetMethod().CreateDelegate(typeof(Func<Program, Enum2>));
    }
}
```

Also, ignore `System.Transactions.Tests` - extremely slow on our CI (slow hardware?) and even timeouts sometimes

### CODE REVIEW

**Comment by EgorBo** [comment]
ARM64 lane is broken on CI everywhere.

**Comment by marek-safar** [comment]
@EgorBo this seems to break quite a few existing tests

**Comment by EgorBo** [comment]
@marek-safar yeah, will push a fix.

**Comment by EgorBo** [comment]
@marek-safar fixed.

**Pull request merged**
