### PR TITLE
nuget-hash-extractor: Add msbuild extensions nuget version from vs15.…

### PR DESCRIPTION
**Pull request by radical**
…6 msbuild branch

Version `2.1.100-preview-62721-01` from:

https://github.com/dotnet/cli/blob/60218cecb52235ca0e42ba630979384900202cf2/build/DependencyVersions.props

Also, update the list in the runtime and deniedAssembliesList.txt
installed for use by msbuild.

### CODE REVIEW

**Comment by akoeplinger** [comment]
It seems this was already done as part of https://github.com/mono/mono/pull/7379 ?

**Comment by luhenry** [comment]
@monojenkins build OS X x64 iOS SDK

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by marek-safar** [comment]
Alexander is right, this is a duplicate of that commit

**Pull request closed without merging**
