### PR TITLE
Lower min/max SSE operations on x64

### PR DESCRIPTION
**Pull request by filipnavara**
Follow up on #17511. /cc @vargaz

### CODE REVIEW

**Comment by filipnavara** [comment]
@monojenkins build Linux x64 C++

**Comment by filipnavara** [comment]
@monojenkins build Linux AArch64

**Comment by filipnavara** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Comment by filipnavara** [comment]
@monojenkins build Linux ARMv7 Interpreter

**Comment by EgorBo** [comment]
Awesome as usual!.
Not sure what happened to `Project Files Diff` job

**Comment by filipnavara** [comment]
@vargaz Ping. Can we merge this? Thanks!

**Pull request merged**
