### PR TITLE
[Ignore][MSBuild] Update to latest vs16.9 branch

### PR DESCRIPTION
**Pull request by mrward**

### CODE REVIEW

**Comment by mrward** [comment]
@monojenkins build pkg

**Review by Therzok — APPROVED** [review]

**Comment by mrward** [comment]
Not planning on including this in mono. Was just trying to get a mono pkg build but that seems to be failing and I cannot see the error since jenkins.mono-project.com is not responding.

**Comment by mrward** [comment]
@monojenkins build pkg

**Comment by mrward** [comment]
The only problem with the msbuild vs16.9 code was it needed some extra NuGet package sources for the mono build. The binding redirects were OK. However the packaging step is still failing here for some reason. For VS Mac we are building msbuild from source so we can ship later msbuild binaries with the IDE.

**Comment by mrward** [comment]
Superceded by https://github.com/mono/mono/pull/20979

**Pull request closed without merging**
