### PR TITLE
[threads] Remove unused mono_thread_internal_stop

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by luhenry** [comment]
build

**Comment by luhenry** [comment]
whitelist

**Comment by kumpera** [comment]
How about we remove the flag from threads.c now that it can't be requested?

**Comment by luhenry** [comment]
@kumpera it still can be requested via `mono_thread_stop` which is part of the public API.

**Comment by kumpera** [comment]
@luhenry let's switch that to be an abort then. :) The expected behavior is kinda identical to abort.


The odds of stop working is huge - now that we no longer used it as part of shutdown.

**Comment by luhenry** [comment]
@kumpera I love the idea! Let me submit a PR for that.

**Pull request merged**
