### PR TITLE
[wasm][sdk] Turn on SDK tests

### PR DESCRIPTION
**Pull request by kjpou1**

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build Linux WebAssembly

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@radical Could you lend us a hand here.  Not sure what else to do to get rid of this message.

```

Starting test execution, please wait...
[xUnit.net 00:00:00.52]     Mono.WebAssembly.SdkTests.BuildTests.IsWasmProject [FAIL]
  X Mono.WebAssembly.SdkTests.BuildTests.IsWasmProject [6ms]
  Error Message:
   System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
  Stack Trace:
    at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <18af29f2fe084ba499692166376171ee>:0 

```

**Comment by akoeplinger** [comment]
I don't think we need this anymore in mono/mono, closing.

**Pull request closed without merging**
