### PR TITLE
Refactor the AppleTls Certificate code into a PAL-based approach.

### PR DESCRIPTION
**Pull request by baulig**
* Added the internal `SafeHandle` based classes from CoreFX's PAL:
  `SafeSecCertificateHandle`, `SafeSecIdentityHandle`, `SafeKeychainItemHandle`
  and `SafeSecKeyRefHandle`.

* Added a new static internal class `MonoCertificatePal`:

  - `Mono.AppleTls/MonoCertificatePal.cs` is shared between OS X and Mobile.
  - `Mono.AppleTls/MonoCertificatePal.OSX.cs` contains the OS X specific parts.
  - `Mono.AppleTls/MonoCertificatePal.Mobile.cs` contains the Mobile specific parts.

  This split allows us to avoid all the `MONOTOUCH` conditionals in the code.

* In the `Mono.AppleTls` directory, all code from `Certificate.cs`, `Items.cs` and
  `ImportExport.cs` have all been merged into the new `MonoCertificatePal` class.

* The entire AppleTls code is now using these safe handles instead of the old
  Mono-specific types.  This allows us to swap out the implementation of the certificate
  code with CoreFX's PAL code.

* Cleaned up and removed some ancient dead code.

* `build/profiles/build.make`: Don't set `MONO_FEATURE_APPLETLS` here.

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@baulig it fails to build on linux

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by baulig** [comment]
@monojenkins build Linux AArch64

**Pull request merged**
