### PR TITLE
[runtime] Disable XDEBUG on OSX

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by knocte** [comment]
Shouldn't the commit message state the *why* besides the *what*? Also, I guess this limitation should be noted in the docs? (Like http://www.mono-project.com/docs/advanced/runtime/docs/xdebug/ ) Thanks

**Comment by tritao** [comment]
@knocte That's a good point, I also had the same thought when first checking out this pull.

**Comment by alexrp** [comment]
I wonder if this would be better handled in `configure.ac` rather than sprinkling more macros in arch headers. Does this really depend on arch as much as it does OS?

**Comment by vargaz** [comment]
This is disabled because it doesn't work.

**Comment by alexanderkyte** [comment]
I had the same thought as @alexrp. I'm going to make it a configure.ac flag and add -DXDEBUG_SUPPORTED. Otherwise it will be just copy-pasted between most platforms.

**Comment by vargaz** [comment]
configure.in is about detecting things, and this cannot be detected, this is why its much easier to define it in mini-<ARCH>.h.

**Comment by alexrp** [comment]
@vargaz: I mean we could place it here: https://github.com/mono/mono/blob/master/configure.ac#L300

**Comment by vargaz** [comment]
xdebug doesn't have to be disabled on darwin, it has to be enabled on linux, since its not guaranteed to work on anywhere else.

**Pull request merged**
