### PR TITLE
[netcore] Fix the exception thrown by the Vector<T>.CopyTo() intrinsic.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/16616.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@lewurm could you please review

**Pull request merged**
