### PR TITLE
Fix internal allocator header size

### PR DESCRIPTION
**Pull request by schani**
The header is always just a pointer.

### CODE REVIEW

**Comment by kumpera** [comment]
I can't say whether this fix a correctness or a space waste issue.

**Comment by schani** [comment]
It fixes a tiny space wastage, but the old code would also break if `MonoLockFreeAllocator` ever got smaller than a pointer.

**Comment by alexrp** [comment]
What does the header point to, though? I feel like just `sizeof (gpointer)` is a bit too puzzling.

**Comment by schani** [comment]
I was lazy.  It's a `Descriptor*`, but `Descriptor` is defined in `lock-free-alloc.c`.  I added a comment.

**Comment by alexrp** [comment]
LGTM

**Comment by schani** [comment]
@monojenkins automerge

**Pull request closed without merging**
