### PR TITLE
Update roslyn tests

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build acceptance tests

**Comment by marek-safar** [comment]
I am only testing this to see if netcore can even run but it looks like we use it on linux only which does not tell me much

**Comment by marek-safar** [comment]
build acceptance tests

**Comment by marek-safar** [comment]
build acceptance tests

**Comment by marek-safar** [comment]
build acceptance tests

**Comment by akoeplinger** [comment]
build acceptance tests

**Comment by marek-safar** [comment]
build acceptance tests

**Comment by marek-safar** [comment]
build acceptance tests

**Comment by marek-safar** [comment]
build acceptance tests

**Pull request merged**
