### PR TITLE
Fix callstacks through aot-runtime.c. i.e. avoid file-level static on functions.

### PR DESCRIPTION
**Pull request by jaykrell**
i.e. Improve diagnostics for https://github.com/mono/mono/issues/19009.
If this helps as I think it does, more to do.

Note that file-level static no longer has the efficient call implication on most systems, as we link -Bsymbolic anyway. (It never did on Windows.)

### CODE REVIEW

**Comment by vargaz** [comment]
We are not going to get rid of static functions just to improve stack traces.

**Comment by jaykrell** [comment]
Losing stack traces is a high cost for shorter function names.

**Comment by jaykrell** [comment]
Other larger code bases do exactly this -- avoid file-level static in order to ensure better symbols.
I've been bitten by file-level static similarly before.

**Comment by jaykrell** [comment]
Good callstacks seem far much valuable than removing `mono_` from the starts of function names.

I understand there is scoping for human comprehension of the code, but correct callstacks still seem relatively important.

For the sake of human comprehension, you could build 2x, where `mono_static` is empty or `static`. As long as it builds w/ `#define mono_static static`, that means human does not have to read past the file to find the references.

Another project I work on, file-level static recently won this debate, but 1. We haven't seen the broken stacks as a counterpoint, just broken link /dump /disasm 2. The actual gradual conversion to C++ makes it moot -- the file-level statics are replaced by extern private: anyway.

Another thing imho against file-level static is the possibility of later wanting to use the function cross-module. Avoid the later rename.

Also some build systems `#include` everything to achieve like-link-time-codegen. That breaks file-level static -- you still need unique names.

**Comment by lambdageek** [comment]
Whether a function appears in a stack trace doesn't have to do with whether it is `static` or not.  Inlining and constant folding are more likely to have an affect. 

You could try applying `MONO_NEVER_INLINE` to some functions if you really want to see them in stack traces, but it's really not guaranteed to work.  (Inlining isn't the only optimization that will have an effect - https://stackoverflow.com/a/54482070/570682)

example with `-fvisibility=hidden` and `static` and `__attribute__((noinling))`: https://gist.github.com/lambdageek/f98b0a09eb185af941468aca4d31dd58

**Comment by jaykrell** [comment]
“Whether a function appears in a stack trace doesn't have to do with whether it is static or not.”

I strongly suspect the opposite.
Some tools do not see or use static symbols.

Inlining has similar characteristics that is true but is not the likely culprit here, because as @vargaz said, these functions do not form this call graph.

Whatever is reporting the stack is just showing nearest extern symbol.

**Comment by jaykrell** [comment]
It could also be dynamic/visible symbols.
But really historically at least, and maybe currently, file-level static is anti-debugging. They are banned from some  code bases for this reason.

**Comment by lewurm** [comment]
That used to be better a couple months ago. For example, that's how a crash log used to look like 8 months ago from the release branch integration (not sure anymore if it was 2019-02 or 2019-06 😕  ): https://gist.github.com/mandel-macaque/b7eff3cd497a063fa5cfee6f78fd0386

Being a bit sassy here: _Maybe_ it could be caused by those [random](https://github.com/mono/mono/pull/14511#issuecomment-533637157) native linker [changes](https://github.com/mono/mono/pull/14298#issuecomment-488962543) that [nobody really understood](https://github.com/mono/mono/pull/14562#pullrequestreview-254240070)?

**Comment by jaykrell** [comment]
-z now causes imports to be processed at load time instead of as functions are called.
-Bsymbolic causes mono_x calling mono_y to actually call mono_y and not random user-supplied symbol.

Neither affects visibility and neither affect file level static, and -Bsymbolic likely does nothing on Apple platforms -- it is just how Apple would likely work always. I'd have to check though.

These provide faster more predictable and safer semantics (fewer dynamic loader calls outs at random points).

But almost anything is possible, granted.

How can we/I see this?

Need a watch and developer account?
Emulator?

Can you confirm missing symbols in current stacks? And that removing static fixes?
Or undoing the linker change fixes?

**Comment by jaykrell** [comment]
https://gist.github.com/mandel-macaque/b7eff3cd497a063fa5cfee6f78fd0386
is inconclusive to me.

1. It has source paths and line numbers, good.
2. All the functions start `mono_`. Are they all extern? Are file-level statics missing?
Need to read the code..

What produced the stack with missing symbols anyway?
Newer compiler? Newer OS? Newer linker? Newer emulator? etc.?
Or, ignore the history, repro it currently, and experiment to fix it?

**Comment by jaykrell** [comment]
Ok, here is semi-conclusive:

`mono_handle_exception_internal` appears in
https://gist.github.com/mandel-macaque/b7eff3cd497a063fa5cfee6f78fd0386, and in current tree is `static` (and `mono_` prefix, which I think is fine to always include).

Still don't know what produced that stack, that also lacks files/lines.

And again, as I said, file-level static is missed historically by some tools, and definitely not today missed by all tools. Current Windows debuggers do show them. link /dump /disasm does not. I don't know the full list.

**Comment by jaykrell** [comment]
How about this:
1. Confirm the crash is reproable in CI.
2. Make a small part of this change and see if it helps the stack?

**Comment by jaykrell** [comment]
How about take a small part of this and see if it helps? Just one or two functions? One is obvious.

**Comment by jaykrell** [comment]
Specifically ‘load_aot_module’, I will PR that later.
It that helps then do more.

**Comment by jaykrell** [comment]
https://github.com/mono/mono/pull/19023

**Pull request closed without merging**
