### PR TITLE
[debugger][wasm] Local vars

### PR DESCRIPTION
**Pull request by thaystg**
Fixing side effect of #15357.

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kg** [comment]
I don't understand what this commit is doing. The old typed array is still there but there's an additional allocation and some copies now

**Comment by thaystg** [comment]
> I don't understand what this commit is doing. The old typed array is still there but there's an additional allocation and some copies now

As I could read in a lot of places this is the right way to pass parameters between Javascript and C functions.
Here is an example:
https://github.com/Planeshifter/emscripten-examples/tree/master/01_PassingArrays
Another:
https://becominghuman.ai/passing-and-returning-webassembly-array-parameters-a0f572c65d97

Please, if you know any other way to do this, please let me know...

**Comment by kg** [comment]
From how I understand it, can you remove the initial scratch typed array and instead just malloc a block of space in the wasm heap for your data, then copy the data directly there? the bits where you fill typedArray[i] from your source would instead write directly into the wasm heap. Then there's no temporary typed array and no need to copy from your temp array into the wasm heap.

**Comment by thaystg** [comment]
> From how I understand it, can you remove the initial scratch typed array and instead just malloc a block of space in the wasm heap for your data, then copy the data directly there? the bits where you fill typedArray[i] from your source would instead write directly into the wasm heap. Then there's no temporary typed array and no need to copy from your temp array into the wasm heap.

Done...

**Comment by thaystg** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Pull request merged**
