### PR TITLE
[runtime] Fix the blittable flag and the instance size for pointer ty…

### PR DESCRIPTION
**Pull request by vargaz**
…pes. Fixes #45131.

### CODE REVIEW

**Comment by nealef** [comment]
My test case now works but the app which first had this problem now reports:

1) Test Error : Drms.Server.Api.Services.Tests.ServiceTest.TestGetDiscretizedModel
   System.Runtime.InteropServices.MarshalDirectiveException : Type double* which is passed to unmanaged code must have a StructLayout attribute.
  at (wrapper managed-to-native) Drms.Server.DomainModel.Geometry.GriddingScaling.CppUtil.Interop.UpscalingCatalog:CreatePropertyScalingManager (int[],int[],int[],single[],single[],int[],double*[],int*[],byte*[],double*[],int*[],double*[],int*[],byte*[],int[],int[],int[],int,int,int,int,int,int,double)

**Comment by vargaz** [comment]
Could you paste the pinvoke method signature which has the problem ?

**Comment by nealef** [comment]
CreatePropertyScalingManager - signature:intptr(int+AFsAXQ-,int+AFsAXQ-,int+AFsAXQ-,single+AFsAXQ-,single+AFsAXQ-,int+AFsAXQ-,double+ACoAWwBd-,int+ACoAWwBd-,byte+ACoAWwBd-,double+ACoAWwBd-,int+ACoAWwBd-,double+ACoAWwBd-,int+ACoAWwBd-,byte+ACoAWwBd-,int+AFsAXQ-,int+AFsAXQ-,int+AFsAXQ-,int,int,int,int,int,int,double)

I created a test case with this signature and it worked on another system. I am checking if the build on the original system is correct.

**Comment by nealef** [comment]
Rebuilt from master and all is well. Apologies for the false alarm. Thanks for the fix.

**Pull request merged**
