### PR TITLE
Bump msbuild, roslyn and nuget

### PR DESCRIPTION
**Pull request by akoeplinger**
Bump to MSBuild vs16.9, Roslyn 3.9.0 and NuGet 5.9.0

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
Tested a few projects, seems to look good :)

**Comment by MichaelVoelkel** [comment]
Where can I get, it's been over a month? I installed the latest mono release for Mac but it is still on 16.6?

**Comment by akien-mga** [comment]
@MichaelVoelkel Not a Mono contributor, but I was looking into this too. I'm not sure what's included in the Mac packages, but for the Linux repositories (CentOS/Ubuntu), it seems like MSBuild 16.9 is provided in the *Preview* repos, but not in *Nightly*.

This PR is for `main` (which I assume matches *Nightly*), but apparently there hasn't been packaging work done for Nightly yet. On the other hand the PR was backported to `2020-02` (the tip of which is current *Preview*, 6.12.0.144) and MSBuild 16.9 is in the repos.

**Comment by MichaelVoelkel** [comment]
@akien-mga hm, I looked for a newer, potentially unstable version, but I only found this page: https://www.mono-project.com/download/stable/
NOW I see that there is "Nightly" written small at the top of the page... so, yeah, apparently I just need to use a non-stable package. Maybe I will go that way, thank you (y)

**Comment by akien-mga** [comment]
Yes, though specifically here you should use [Preview](https://www.mono-project.com/download/preview/) if you want MSBuild 16.9 (and a version which is still fairly close to stable, since stable is 6.12.0.122 and preview is 6.12.0.144, i.e. 22 commits ahead).

**Comment by MichaelVoelkel** [comment]
Thanks for the hint :)

**Pull request merged**
