### PR TITLE
[merp] Capture Environment.FailFast message in crash report

### PR DESCRIPTION
**Pull request by lambdageek**
If the process calls `System.Environment.FailFast (message, exception)` we should capture the message in the crash report log.

### CODE REVIEW

**Comment by Therzok** [comment]
LGTM!

**Comment by alexischr** [comment]
TIL you can free NULL :)

**Comment by lambdageek** [comment]
Really am working on a test.  Current status: writing a thing to traverse a json blob

**Comment by lambdageek** [comment]
@alexischr Please take another look. I added some json validation stuff to merp-crash-test.cs and used it to check that the payload includes the FailFast message

**Comment by alexischr** [comment]
Looks good! I will follow up with a similar test for assertions/`assertion_msg`

**Comment by lambdageek** [comment]
@monojenkins backport to 2020-02
@monojenkins backport to 2019-12

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
Backported to 2020-02 and 2019-12 by hand.

**Comment by lambdageek** [comment]
@monojenkins backport to 2019-10

**Pull request merged**
