### PR TITLE
mono_thread_set_name_internal change boolean parameters to enum flags.

### PR DESCRIPTION
**Pull request by jaykrell**
Extracted from https://github.com/mono/mono/pull/15859.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
Looks ok but why is this needed, are we adding more flags ?

**Comment by jaykrell** [comment]
I want to add another flag called `constant`.
And I want to retain UTF8 instead of UTF16.
So, given UTF8, it will just store it.
Given "constant", when it is set again, it will not free it. The flag will be remembered as a boolean.
@CoffeeFlux was a little reluctant to review the larger PR.

https://github.com/mono/mono/pull/15859/files#diff-f1a9287559d3aa620b058619f47f00c9R1874
etc.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
