### PR TITLE
[sdks] remove 32bit llvm

### PR DESCRIPTION
**Pull request by lewurm**
Also switches the MXE cross compilers for Android and WebAssembly to 64bit host.

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@imhameed - purely FYI, this removes the 32bit llvm

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins backport 2019-06

**Pull request merged**
