### PR TITLE
[cxx] Enable C++.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 C++

**Comment by jaykrell** [comment]
Windows x64 two successes.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 C++

**Comment by akoeplinger** [comment]
Closing this test PR due to no activity in the last month, you can reopen if you want a new run.

**Pull request closed without merging**
