### PR TITLE
[wasm][debugger] Handle multi-doc methods and multiple results for breakpoints

### PR DESCRIPTION
**Pull request by lewing**
Add logic to support embedded sources and
add all the documents from multi-doc methods

Add logic to check source hashes against
pdb hash.

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build Linux WebAssembly

**Comment by lewing** [comment]
This fixes breakpoint setting on delegates now

**Comment by lewing** [comment]
@monojenkins build Linux WebAssembly

**Comment by lewing** [comment]
fixes https://github.com/mono/mono/issues/19550

**Comment by lewing** [comment]
Could use a little work to handle missing sources better

**Comment by kjpou1** [comment]
The code looks good but have not been able to recreate in a test.

**Comment by lewing** [comment]
image

The fix is for the second breakpoints on those lines.  You can recreate by debugging the debugger test app

**Comment by lewing** [comment]
@monojenkins backport 3.2-wasm

**Pull request merged**
