### PR TITLE
Enable GSS on Linux

### PR DESCRIPTION
**Pull request by EgorBo**
test on ci

### CODE REVIEW

**Comment by EgorBo** [comment]
Was blocked by https://github.com/mono/mono/issues/17327
Now it can be merged

**Comment by steveisok** [comment]
@monojenkins commit csproj

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins commit csproj

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins build OS X x64 Hardened Runtime

**Comment by steveisok** [comment]
@monojenkins backport 2019-10

**Comment by steveisok** [comment]
@monojenkins backport 2019-08

**Comment by aliegeni** [comment]
How to know in which version of Xamarin or Visual Studio 2019 will be include this fix?

**Pull request merged**
