### PR TITLE
[corlib] CompareInfo from CoreFX

### PR DESCRIPTION
**Pull request by marek-safar**
#7264

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Comment by kumpera** [comment]
Hey Marek,

This PR includes commented code and nobody reviewed it. Don't do it.

**Comment by marek-safar** [comment]
The comment only commented code which was already commented out

**Pull request merged**
