### PR TITLE
Fix inserting null ints and datetimes.

### PR DESCRIPTION
**Pull request by jbraswell**
Resolves https://bugzilla.xamarin.com/show_bug.cgi?id=26546.

### CODE REVIEW

**Comment by tritao** [comment]
Can you add a test that covers this to the test suite?

**Comment by jbraswell** [comment]
Okay. Will you point me to some documentation on adding tests?

**Comment by tritao** [comment]
Sure.

For a general overview of the test suite you can check out http://www.mono-project.com/community/contributing/test-suite/.

In this case you can add a new test source file to https://github.com/mono/mono/blob/master/mcs/class/Mono.Data.Tds/Mono.Data.Tds_test.dll.sources.

**Comment by alexrp** [comment]
Ping?

**Comment by alexrp** [comment]
By the way, this PR should probably be made against master, not mono-4.0.0-branch.

**Comment by lewurm** [comment]
apparently this was merged with #1664, closing this therefore.

**Comment by lewurm** [comment]
apparently this was merged with #1664, closing this therefore.

**Pull request closed without merging**
