### PR TITLE
[interp] Add some missing netcore intrinsics.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by jaykrell** [comment]
`get_IsDynamicCodeSupported` is maybe always true, because it can be interpreted?

**Comment by vargaz** [comment]
The failures are relevant.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
is that only needed for netcore? if yes, please guard with `#ifdef ENABLE_NETCORE`

**Comment by vargaz** [comment]
Its actually not netcore only.

**Pull request merged**
