### PR TITLE
Workaround broken AIX toolset (libtool).

### PR DESCRIPTION
**Pull request by jaykrell**
These programs work if you just compile them with g++ and most of the automake/autoconf/libtool
flags, but not if you use all of automake/autoconf/libtool switches. Something to do with library search paths perhaps?

### CODE REVIEW

**Comment by NattyNarwhal** [comment]
Yes, it appears to be a corner case where:

* libtool is in charge of building and adds a bunch of shit to the linker search paths (which get baked into the executable) - it's fine if you just use g++ directly

* pthread is compiled into it

* as a result of those, the program looks into `/opt/freeware/lib/libstdc++.a` instead of `/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/pthread/ppc64/libstdc++.a`, which when compiled with pthread, dies in C++ stream I/O?

But??? (Why SHOULD these be different? I checked their imports/exports.... and it's subtly different)

```
aix$ rpm -q --whatprovides /opt/freeware/lib/libstdc++.a
libstdc++-6.3.0-1
aix$ rpm -q --whatprovides /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/pthread/ppc64/libstdc++.a
libstdc++-6.3.0-1
```

I need to try this with a different toolchain to reproduce with; either Bull's (this is AIX Toolbox) or use the IBM i packages. (Or the one I've been assembling due to my continuing disappointment at AIX Toolbox/Perzl/Bull, but I lack sufficient dependencies to build with....)

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 FullAOT

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by NattyNarwhal** [comment]
I believe this has been tested to work; could this be merged before CI just becomes nothing but "test failed" for AIX?

**Pull request merged**
