### PR TITLE
[2018-06][sdks] Install the llvm36 versions of opt/llc as well.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by lewurm** [comment]
please forwardport to master and 2018-08 once merged

**Comment by vargaz** [comment]
@monojenkins build Linux x64

**Comment by lewurm** [comment]
@monojenkins backport 2018-08

**Comment by lewurm** [comment]
@monojenkins backport master

**Comment by lewurm** [comment]
@vargaz could you propagate this change to `master`/`2018-08`? I'm not sure what is needed there. Thanks!

**Pull request merged**
