### PR TITLE
[runtime] Coverage profiler fixes

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by alexrp** [comment]
This change is good, but I think if we're going to do this, we should also make sure that wrappers are not exposed through the profiler API at all, i.e. do what you suggested a while back and expose the 'real' method instead of the wrapper in these events:

https://github.com/alexrp/mono/blob/master/mono/metadata/profiler-events.h#L35-L37

https://github.com/alexrp/mono/blob/master/mono/metadata/profiler-events.h#L57-L63

And also when invoking these filter callbacks:

https://github.com/alexrp/mono/blob/master/mono/metadata/profiler-private.h#L109

https://github.com/alexrp/mono/blob/master/mono/metadata/profiler-private.h#L129

I don't know how exactly we'd go about doing that though. Is there a general way to get the 'real' method that a wrapper is wrapping?

**Comment by vargaz** [comment]
In a lot of cases, there is no real method, also the real method is usually called by the wrapper, so it gets processed.

**Comment by marek-safar** [comment]
@monojenkins build OS X x64

**Comment by marek-safar** [comment]
@monojenkins build OS X i386

**Pull request merged**
