### PR TITLE
[reflection] Throw TLE for Type.GetType("", ...) (Fixes #59664)

### PR DESCRIPTION
**Pull request by lambdageek**
The throwing versions of `System.Type.GetType()` apparently must throw a `TypeLoadException` when passed the empty string as an input.

Fixes [#59664](https://bugzilla.xamarin.com/show_bug.cgi?id=59664)

### CODE REVIEW

**Comment by marek-safar** [comment]
Why not have the check at managed side only?

**Comment by lambdageek** [comment]
@marek-safar There are several different managed endpoints that all end up in `mono_reflection_parse_type_checked` - it seemed cleanest to check in the runtime.

**Comment by marek-safar** [comment]
I am not sure we need to check other entry points than Type.GetType. What are they? Do they fail same way on .net?

**Comment by lambdageek** [comment]
I'll move the check to managed.
The other place is `Assembly.GetType` - which throws `ArgumentException: 'String cannot have zero length'`

**Comment by lambdageek** [comment]
build OSX i386

**Comment by lambdageek** [comment]
build OS X i386

**Pull request merged**
