### PR TITLE
[corlib]: Move sre dependency into their own method in `System.RuntimeType`.

### PR DESCRIPTION
**Pull request by baulig**
Move call to `TypeBuilderInstantiation.MakeGenericType` into a new
`System.RuntimeType.MakeTypeBuilderInstantiation` method to allow the
linker to remove it.

Requires linker PR https://github.com/mono/linker/pull/590.

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by baulig** [comment]
@monojenkins build Linux AArch64

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Pull request merged**
