### PR TITLE
Fix locating Python interpreter when it isn't "python"

### PR DESCRIPTION
**Pull request by NattyNarwhal**
The "python" interpreter is specified by PEP-394. In it, an OS
can decide not to ship a "python" executable, and instead only
ship python2/3, providing some ambiguity for scripts that are
version-neutral, like the one Mono uses.

This uses an automake macro to locate a suitable Python, and
changes the makefile to use the located Python, whatever it may be.

### CODE REVIEW

**Comment by jaykrell** [comment]
Python2 or 3?
Does env work?

**Comment by NattyNarwhal** [comment]
It will look for any Python it can, which is fine for the one script that needs it. (You could specify a minimum version as an argument, AFAIK.)

**Comment by jaykrell** [comment]
Another choice is usr/bin/env.
I suppose an advantage of automake is it can find any of python, python2, or python3.
Though python3 will be correct long term.
Also your approach saves a fork/exec, like on slow Cygwin.

**Comment by NattyNarwhal** [comment]
env won't save you when the system lacks `python` and just has `python2`/`python3`. (IIRC, CentOS 6/7 lack Python3, and some distros stopped including Python2.)

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
