### PR TITLE
[metadata] If a static field fails while computing size, fail the class

### PR DESCRIPTION
**Pull request by lambdageek**
Fixes https://github.com/mono/mono/issues/20650

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Static and instance field layouts are unrelated - throwing TypeLoadException is actually a bug, but I guess it's nice that it matches the same bug in the CLR: https://github.com/dotnet/runtime/issues/5479

**Comment by lambdageek** [comment]
Interp failures are related

**Comment by lambdageek** [comment]
> Static and instance field layouts are unrelated - throwing TypeLoadException is actually a bug, but I guess it's nice that it matches the same bug in the CLR: [dotnet/runtime#5479](https://github.com/dotnet/runtime/issues/5479)

I'll trace through the layout code again in Mono, but I suspect it will be difficult to find a nice solution for the same reason as CoreCLR.

This PR is still a good idea because we'll trade a crash for a runtime exception (that will match CLR)

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@monojenkins build failed

**Pull request merged**
