### PR TITLE
[RFC] [ci] Allow skipping runtime/classlib test suites via GitHub label

### PR DESCRIPTION
**Pull request by akoeplinger**
**RFC: please let me know what you think about it**

---

Inspired by the xamarin-macios team, they use GitHub labels for telling Jenkins to run specific tests on PRs.

For us it probably makes more sense to do it the other way round and exclude either the runtime tests or the class library tests from running.

When I'm making a bugfix in the class libs the chances of it breaking the runtime tests are quite low, yet I still have to wait ~1hr before Jenkins even starts running the class lib tests.

The label check happens before the test suites, so with this I'd have about 30mins to decide whether I want to skip and add the label on GitHub.

### CODE REVIEW

**Comment by akoeplinger** [comment]
build

**Comment by alexrp** [comment]
I like having this feature, though I'm not sure I agree with the notion that disabling specific suites is what makes the most sense for us. If I make a change to the profiler, there is rarely a good reason to run anything other than the profiler test suite. So I wonder if there's a way we could support both ways.

**Comment by akoeplinger** [comment]
Hmm. We could have a `skip-everything` and then `enable-<step>` labels, but maybe that's overkill. Which other steps/scenarios do you think would make sense to run individually?

**Comment by akoeplinger** [comment]
Closing, we moved the long running runtime stress tests to a separate job so the runtime tests just take minutes in PRs now. Since you pretty much always want to run class lib tests when making a runtime change this doesn't seem worth the complexity anymore.

**Pull request closed without merging**
