### PR TITLE
[mcs] Loosing properties in CallTarget 

### PR DESCRIPTION
**Pull request by harcher81**
Exemple :
- Target A
  - Print property X
- Target B
  - Set property X to "123"
  - Call Target A
    We call target B, in msbuild this display "123". In xbuild, before this fix "", after this fix "123".

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed? if so, can you rebase your changes @harcher81 ?

**Comment by marek-safar** [comment]
This needs test to be included before merging

**Comment by lewurm** [comment]
I'm closing this PR, feel free to reopen this PR if you have some time to work on it. Thank you!

**Pull request closed without merging**
