### PR TITLE
Added restart of http keep-alive connection

### PR DESCRIPTION
**Pull request by igorshmukler**
This PR adds restart of http keep-alive connection read, when socket has been closed - stream::ReadDone returned 0. Specifically, according to RFC 2616 section 8.1 dealing with persistent connections, and in further detail the section 8.1.4 "Practical Considerations," closed connections got to be restarted, so long as the request sequence is idempotent.

This PR solves a bug that we are experiencing, whenever there is a latency on the network Mono often throwing an exception on HttpClient::GetASync while the same "executable" correctly works on MS .NET with no exceptions.

### CODE REVIEW

**Comment by Therzok** [comment]
approve

**Comment by igorshmukler** [comment]
Hello,
Jenkins built my patch with "Build finished. No test results found."
What needs to be done about this?
Thank you

**Comment by akoeplinger** [comment]
@igorshmukler test results are in now, looks fine (apart from a few flaky tests we're still tracking down, you can ignore those).

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by igorshmukler** [comment]
yes, please

**Comment by lewurm** [comment]
build

**Comment by igorshmukler** [comment]
@akoeplinger and @lewurm - this PR has been open for over five (5) months. Is there a reason that it has not merged, rejected or otherwise reviewed? What's the policy on PRs? Are they even needed?

**Comment by migueldeicaza** [comment]
Apologies, we sometimes drop the ball on these things, and we are now reviewing these issues.

I am a little afraid that we do not have a test case showcasing the issue and would love to have one, so we make sure that future developers touching this code do not accidentally regress the feature.

**Comment by migueldeicaza** [comment]
I have one open issue with this patch, you mention that:

```
Specifically, according to RFC 2616 section 8.1 dealing with persistent connections, and in further detail the section 8.1.4 "Practical Considerations," closed connections got to be restarted, so long as the request sequence is idempotent.
```

Shouldn't we be testing that the verb that we are using is idempotent?

**Comment by migueldeicaza** [comment]
Looking at the reference source, there are too many places where retrying takes place with different degrees of retrying and different ways of doing it.

I suspect we might be better off completing the work to bring HttpWebRequest from .NET to Mono

**Comment by igorshmukler** [comment]
@migueldeicaza 
it has been over six months since i fixed the bug and submitted the patch for review. in addition to not being a networking expert, i simply don't remember every detail. still, as far as I understand only POST method is not idempotent, while PUT, DELETE, GET, HEAD, OPTIONS and TRACE are idempotent. since my patch fixes ReadDone, think that extra check, which you mentioned is not really needed.

obviously, if you believe that fixing a long-outstanding bug by integrating a patch is not the best way to go, after the contribution has been ignored for about seven or eight months, you got to go with your gut. you are the experts on building vibrant open source communities and encouraging independent developers to contribute.

i did the patch at work, to address an issue with a commercial product built on Mono. we are now switching to CoreCLR etc, because our team felt that Mono people are unable or unwilling to support Mono. the story of this patch, is the best illustration.

congratulation on getting acquired.

**Comment by lewurm** [comment]
@baulig with the new web stack, is this PR still going to be relevant?

**Comment by baulig** [comment]
Old / new web stack is irrelevant - this cannot go in without a detailed analysis of when this is needed, when it should _not_ happen, which HTTP Verbs this should affect / not affect, what the semantics are regarding rewrite / ntlm resends, etc.
We can consider this as a feature request at a later time, but this will require me spending a couple of days doing research and writing tests.

**Pull request closed without merging**
