### PR TITLE
[interp] Small fixes.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by jaykrell** [comment]
The new callback?

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-bitcode+interpreter/7521/parsed_console/log.html

```
***** MonoTests.I18N.Other.EncodingTest.TestZero(Codepage 28595)
***** MonoTests.I18N.Other.EncodingTest.TestZero(Codepage 57002)
Tests run: 207, Passed: 206, Errors: 0, Failures: 0, Inconclusive: 0
  Not run: 1, Invalid: 0, Ignored: 1, Skipped: 0
Elapsed time: 00:00:00.0970000

Results saved as /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mcs/class/I18N/Other/TestResult-testing_aot_full_interp.xml.
*** Error in `/mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono': double free or corruption (fasttop): 0x0000563f48913340 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f3498178bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f349817efc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f349817f80e]
/mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono(+0x32b5cc)[0x563f44f0d5cc]
/mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono(+0x3335fa)[0x563f44f155fa]
/mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono(mono_main+0xf64)[0x563f44f1bf14]
/mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono(+0x2f0707)[0x563f44ed2707]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f34981282e1]
/mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono(_start+0x2a)[0x563f44f0c63a]
======= Memory map: ========
563f44be2000-563f46920000 r-xp 00000000 08:11 6168682                    /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono-sgen
563f46b1f000-563f46c4f000 r--p 01d3d000 08:11 6168682                    /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono-sgen
563f46c4f000-563f46c57000 rw-p 01e6d000 08:11 6168682                    /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mono/mini/mono-sgen
563f46c57000-563f46c96000 rw-p 00000000 00:00 0 
563f48639000-563f48be9000 rw-p 00000000 00:00 0                          [heap]
7f348c7dc000-7f348c7e9000 r-xp 00000000 08:11 10749448                   /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mcs/class/lib/testing_aot_full_interp/I18N.Other.dll.so
7f348c7e9000-7f348c9e8000 ---p 0000d000 08:11 10749448                   /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mcs/class/lib/testing_aot_full_interp/I18N.Other.dll.so
7f348c9e8000-7f348c9e9000 r--p 0000c000 08:11 10749448                   /mnt/jenkins/workspace/test-mono-pull-request-amd64-bitcode+interpreter/mcs/class/lib/testing_aot_full_interp/I18N.Other.dll.so
7f348

```

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
