### PR TITLE
[linker-analyzer] Added to the scripts

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by marek-safar** [comment]
Alternatively use illinker name which is what coreclr team is using for a same tool

**Comment by marek-safar** [comment]
Most of the tools which are ambiguous have mono prefix but as we are moving the tool to linker repo it'd better to call it illinker-analyzer from beginning

**Comment by radekdoulik** [comment]
I think the desktop tool is called illink, so maybe we might use illink-analyzer then? That would be at least a bit shorter.

**Comment by marek-safar** [comment]
ok, sounds good

**Comment by radekdoulik** [comment]
ok, updated. please do not squish commits together

**Pull request merged**
