### PR TITLE
[jit] Fix the Activator.CreateInstance () intrinsic for primitive types.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/xamarin/xamarin-android/issues/4817.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
We need to backport this to 2020-02 if the mono/mono-based Xamarin.Android wants to pick it up.

@monojenkins backport 2020-02

**Comment by akoeplinger** [comment]
@vargaz please do a manual backport, thanks :)

**Pull request merged**
