### PR TITLE
[runtime] Do not set flag to skip initialization of generic classes. Lea...

### PR DESCRIPTION
**Pull request by alexanderkyte**
...ds to reporting instance size as 0.

### CODE REVIEW

**Comment by marek-safar** [comment]
This change should come with a test

**Comment by kumpera** [comment]
This needs tests and is potentially wrong as the SRE code is supposed to inflate them.

**Comment by alexanderkyte** [comment]
build

**Comment by vargaz** [comment]
build

**Comment by kumpera** [comment]
build

**Comment by kumpera** [comment]
whitelist

**Comment by alexanderkyte** [comment]
``` make: *** No rule to make target `check'. ``` :-(

**Comment by akoeplinger** [comment]
build

**Comment by akoeplinger** [comment]
@alexanderkyte that was a temporary error on jenkins, I've scheduled a new build

**Pull request merged**
