### PR TITLE
[2019-10] Bump msbuild to track mono-2019-10

### PR DESCRIPTION
**Pull request by radical**
- update nuget.exe to 5.5.0-preview1 to match

### CODE REVIEW

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
`Windows x64 FullAOT`: failing test - `MonoTests.runtime.abort-cctor.exe_timedout`

**Comment by radical** [comment]
@monojenkins build failed

**Comment by radical** [comment]
Rebased on `2019-10`.

**Pull request merged**
