### PR TITLE
[mini] Implement mono_arch_get_delegate_virtual_invoke_impl () on ARM

### PR DESCRIPTION
**Pull request by alexrp**
This is just a quick translation of the x86 version of this code. I don't know if this is actually enough to enable the optimization, or if using `IP` as a scratch register here is OK.

### CODE REVIEW

**Comment by vargaz** [comment]
Looks good to me.

**Comment by alexrp** [comment]
Looks like this is crashing consistently with a `SIGILL` on armel/armhf:

* https://jenkins.mono-project.com/job/test-mono-pull-request-armel/188/consoleFull#-64297831ae1da302-70c8-400e-9aed-bc1cd416a1c7
* https://jenkins.mono-project.com/job/test-mono-pull-request-armhf/188/consoleFull#-64297831ae1da302-70c8-400e-9aed-bc1cd416a1c7

Will look into it later.

**Comment by alexrp** [comment]
build

**Comment by alexrp** [comment]
Still getting a `SIGILL`, will try to revive one of my ARM devices and look into it soon-ish.

**Comment by kumpera** [comment]
Hey guys,

Any progress here? This still has not landed.

**Comment by alexrp** [comment]
I'll get to this eventually, I just have a metric ton of profiler changes in the works that I want done first.

**Pull request closed without merging**
