### PR TITLE
[threads] Import mono_thread_info_set_priority

### PR DESCRIPTION
**Pull request by ludovic-henry**
cc @kumpera

### CODE REVIEW

**Comment by nealef** [comment]
Will this still allow the setting of a thread priority before it is started and having that value used at creation time?

From: Ludovic Henry +ADw-notifications+AEA-github.com+ADw-mailto:notifications+AEA-github.com+AD4APg-
Reply-To: mono/mono +ADw-reply++0004b6fae5ab3e890fa1d8acc6e7856c92f53331fd3d2a1a92cf0000000113ea750492a169ce0a7d9YAQA-reply.github.com+ADw-mailto:reply++0004b6fae5ab3e890fa1d8acc6e7856c92f53331fd3d2a1a92cf0000000113ea750492a169ce0a7d9YAQA-reply.github.com+AD4APg-
Date: Friday, September 9, 2016 at 9:03 AM
To: mono/mono +ADw-mono+AEA-noreply.github.com+ADw-mailto:mono+AEA-noreply.github.com+AD4APg-
Subject: +AFs-mono/mono+AF0- +AFs-threads+AF0- Import mono+AF8-thread+AF8-info+AF8-set+AF8-priority (+ACM-3543)


cc +AEA-kumpera+ADw-https://github.com/kumpera+AD4-

+AF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXwBfAF8AXw-
You can view, comment on, or merge this pull request online at:

  https://github.com/mono/mono/pull/3543

Commit Summary

  +ACo-   +AFs-mono-threads+AF0- Remove MonoThreadParm.creation+AF8-flags
  +ACo-   +AFs-mono-threads+AF0- Remove MonoThreadParm.priority and set to MONO+AF8-THREAD+AF8-PRIORITY+AF8-NORMAL by default
  +ACo-   +AFs-threads+AF0- Wrap use of mono+AF8-thread+AF8-info+AF8-(get+AHw-set)+AF8-priority
  +ACo-   +AFs-threads+AF0- Store priority on MonoInternalThread
  +ACo-   +AFs-threads+AF0- Import mono+AF8-thread+AF8-info+AF8-set+AF8-priority
  +ACo-   +AFs-mono-threads+AF0- Remove MonoThreadParm

File Changes

  +ACo-   M mcs/class/corlib/System.Threading/Thread.cs+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-0+AD4- (2)
  +ACo-   M mcs/class/corlib/System/Environment.cs+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-1+AD4- (2)
  +ACo-   M mono/metadata/appdomain.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-2+AD4- (8)
  +ACo-   M mono/metadata/attach.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-3+AD4- (7)
  +ACo-   M mono/metadata/object-internals.h+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-4+AD4- (2)
  +ACo-   M mono/metadata/threads-types.h+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-5+AD4- (8)
  +ACo-   M mono/metadata/threads.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-6+AD4- (98)
  +ACo-   M mono/mini/aot-compiler.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-7+AD4- (6)
  +ACo-   M mono/mini/debugger-agent.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-8+AD4- (7)
  +ACo-   M mono/utils/mono-threads-posix.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-9+AD4- (112)
  +ACo-   M mono/utils/mono-threads-windows.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-10+AD4- (19)
  +ACo-   M mono/utils/mono-threads.c+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-11+AD4- (22)
  +ACo-   M mono/utils/mono-threads.h+ADw-https://github.com/mono/mono/pull/3543/files+ACM-diff-12+AD4- (28)

Patch Links:

  +ACo-   https://github.com/mono/mono/pull/3543.patch
  +ACo-   https://github.com/mono/mono/pull/3543.diff

+IBQ-

**Comment by ludovic-henry** [comment]
@nealef yes it keeps that working

**Comment by nealef** [comment]
Thanks+ACE-

From: Ludovic Henry +ADw-notifications+AEA-github.com+ADw-mailto:notifications+AEA-github.com+AD4APg-
Reply-To: mono/mono +ADw-reply++0004b6fa96a1e0ad1261b299c1cae0036fb3ef17eaa0b24292cf0000000113eaef9f92a169ce0a7d9YAQA-reply.github.com+ADw-mailto:reply++0004b6fa96a1e0ad1261b299c1cae0036fb3ef17eaa0b24292cf0000000113eaef9f92a169ce0a7d9YAQA-reply.github.com+AD4APg-
Date: Friday, September 9, 2016 at 5:46 PM
To: mono/mono +ADw-mono+AEA-noreply.github.com+ADw-mailto:mono+AEA-noreply.github.com+AD4APg-
Cc: Neale Ferguson +ADw-neale+AEA-sinenomine.net+ADw-mailto:neale+AEA-sinenomine.net+AD4APg-, Mention +ADw-mention+AEA-noreply.github.com+ADw-mailto:mention+AEA-noreply.github.com+AD4APg-
Subject: Re: +AFs-mono/mono+AF0- +AFs-threads+AF0- Import mono+AF8-thread+AF8-info+AF8-set+AF8-priority (+ACM-3543)


+AEA-nealef+ADw-https://github.com/nealef+AD4- yes it keeps that working

+IBQ-

**Comment by ludovic-henry** [comment]
@kumpera could you please review, as it's changing a bit how we do cross platform : we have platform specific code in `threads.c` and do not rely on `mono-threads.c` to do the abstraction

The rational is that we neither use nor want (IMO) priority for MonoThreadInfo.

**Pull request merged**
