### PR TITLE
Make a bunch of classes optional to the runtime.

### PR DESCRIPTION
**Pull request by kumpera**
The majes the following classes optional to the runtime:

System.Reflection.CustomAttributeData
System.Text.StringBuilder
System.Math
System.Console
System.Diagnostics.StackTrace

This doesn't change the linker scripts so it's not ready to be merged.

Those are all types that can be clearly made optional. There are a lot of other types
we could, but there are deeper dependencies in places as threadpool or marshal.

### CODE REVIEW

**Comment by kumpera** [comment]
cc @lambdageek @jaykrell could you review the custom attributes changes as they deal with handles.
@akoeplinger can you point me to the right place to update the linker scripts?

**Comment by kumpera** [comment]
corlib linker xml updates.

Classes that could be further made lazy:

System.Runtime.Remoting.Activation.ActivationServices - conditionally with remoting

Classes that look bogus/wrong:

System.Threading.WaitHandle

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by kumpera** [comment]
The OSX failure might be related. Investigating.

**Comment by kumpera** [comment]
OSX64 failure is fixed by https://github.com/mono/mono/pull/10793

**Comment by kumpera** [comment]
arm64-fullaot+llvm is due to the pinvoke3 issue (has an open PR) and tailcall timeout issue (has an open PR as well)

armhf-bitcode is due to the missing clang++ and has no fix on sight.

osx-products-sdks-ios failure is actually relevant.

**Comment by kumpera** [comment]
@monojenkins build failed

**Pull request merged**
