### PR TITLE
Only null check target for delegate if method is not static.

### PR DESCRIPTION
**Pull request by joncham**
Fixes regression introduced by https://github.com/mono/mono/pull/5404

### CODE REVIEW

**Comment by joncham** [comment]
build

**Comment by akoeplinger** [comment]
it looks like the test fails on the interpreter, @lewurm ?

**Comment by lewurm** [comment]
it's a bug in the interpreter. pushed a fix, thanks @joncham for the test case 🙂

**Comment by luhenry** [comment]
@monojenkins backport to 2017-10

**Pull request merged**
