### PR TITLE
[corlib] Add xunit tests for BitConverter, Convert, etc

### PR DESCRIPTION
**Pull request by EgorBo**
Adds 2528 xunit tests from System.Runtime.Extensions (CoreFX).
See https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Extensions/tests/System

Part of  #8131

### CODE REVIEW

**Comment by marek-safar** [comment]
@EgorBo could you adjust the test?

**Comment by EgorBo** [comment]
oh sure!

**Comment by marek-safar** [comment]
@EgorBo please resolve the conflict

**Comment by EgorBo** [comment]
@monojenkins build failed

**Pull request merged**
