### PR TITLE
WIP: [checked-build] Assert if we safepoint while an OS mutex is locked

### PR DESCRIPTION
**Pull request by lambdageek**
Suppose two threads both try to lock an OS mutex while in GC Unsafe mode.  If one of them locks the mutex and then hits a safepoint and suspends, the other thread will block and wait for the mutex while in GC Unsafe (cooperative) mode. As a result, the suspend initiator (the GC) will deadlock and wait for the thread forever.

This PR adds a "no safepoints" state machine transition when we lock an OS mutex in checked builds (set `MONO_CHECK_MODE=thread`). That will cause an assertion if a thread attempt to safepoint while holding an OS mutex.

---

If the runtime is still starting up (and the main thread isn't attached yet), ignore the no safepoints transitions, as we don't expect to interact with suspension at all yet.

---

With recursive mutexes, we need to switch to no safepoints mode only once at the outermost mutex lock.  Add a counter cookie to the mutex struct to keep track of whether we need a transition.

The cookie logic is:
* initialize the cookie to 0 when we create the OS mutex.
* When locking:
   * if the cookie is 0 when we lock the mutex:
      *  if we did a transition - set the cookie to 1 - this lock will be responsible for doing the exit transition.
      * if we did not do a transition (because another os mutex higher up the call stack did it) - leave the cookie at 0 - this lock will not be responsible for doing the exit transition.
   * if the cookie is positive when we lock the mutex: increment the cookie.
* on unlock:
   *  if the cookie is positive: decrement the cookie, if it is now 0 do the exit transition.
   *  if the cookie is zero: do nothing

Suppose we have OS recursive mutexes m1 and m2 and we do:

```
// m1.cookie == m2.cookie == 0
lock (m1); // enter no safepoints mode; m1.cookie == 1
lock (m2); // already in safepoints mode; m2.cookie == 0
lock (m1); // cookie is positive; increment; m1.cookie == 2

unlock (m1); // decrement cookie; m1.cookie == 1
unlock (m2); // do nothing; m2.cookie == 0
unlock (m1); // decrement cookie; do exit transition ; m1.cookie == 0
```

---

If we call unlock from a coop mutex, don't do the exit no safepoints transition.

If we call `trylock` from a coop mutex (which doesn't do cookie management), don't do the no safepoints transition, since `unlock` for a coop mutex won't do the reverse transition.

`mono_coop_mutex_lock` slowpath calls `mono_os_mutex_lock` from inside a GC Safe region, so it already won't do the "no safepoints" transition, so there's no `_from_coop` version.

---

Condition variables:

save/restore cookie in `mono_os_cond_wait` and `mono_os_cond_timedwait`

When the mutex is unlocked and the thread waits on the condition variable, the cookie will belong to another thread.  When the current thread reacquires the mutex, it will restore the cookie state

### CODE REVIEW

**Comment by lambdageek** [comment]
This PR depends on #18994 and #18992 and #18990. 

It is based on the discussion https://github.com/mono/mono/pull/18860#issuecomment-586445270

**Comment by lambdageek** [comment]
@CoffeeFlux @vargaz I wonder if this is ok to have in the default build.

The cost is:
1. several state machine transitions (some atomic CAS operations) after we successfully take a lock and before we unlock it. (We don't do `copy_stack_data` or context capturing stuff - it's just manipulating the state)
2. An extra 32-bits per mutex.

**Comment by vargaz** [comment]
I think these situations can be avoided by only using a very limited set of coop mutexes as 'high level'  locks, i.e. locks around a large body of code. These are the loader and domain locks.
os mutex-es should be used to lock around very small pieces of code like hashtable lookups etc.

For the specific case in https://github.com/dotnet/runtime/issues/32177,
the problem is that assemblies_lock which is supposed to protect some field in MonoDomain is used to protect a huge bunch of code.

**Comment by lambdageek** [comment]
I'm not so sure that os mutexes are used around small pieces of code today.  if there are calls to `g_hash_table_foreach`  it's not so easy to tell that the iterating code is only doing small amounts of work.  And if there's a `mono_class_from_mono_type` hiding in there, that deadlock will be missed.

I'd prefer to have this at least in checked mode.

**Comment by lambdageek** [comment]
Don't think this will be going in. I still think it's a good idea to have something like this, and it was a useful exercise to do some test runs with it just to verify that it didn't find anything.  But it's a bit too intrusive-looking.

**Comment by CoffeeFlux** [comment]
Did you actually have it on while running the test suite? Or just in a hello world?

**Comment by lambdageek** [comment]
Just the coop lanes on CI.  They hit some profiler failures, but I think that's because I didn't add a check to ignore utility threads that never get suspended.

**Pull request closed without merging**
