### PR TITLE
Allowing sockets to be created with icmpv6

### PR DESCRIPTION
**Pull request by bholmes**
Also adding the missing types in C found in the C# enum to MonoProtocolType

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by Therzok** [comment]
Out of curiosity, because I had an issue while integrating some bits in VSMac. Would you get connection refused as a result code without this patch?

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by bholmes** [comment]
> Out of curiosity, because I had an issue while integrating some bits in VSMac. Would you get connection refused as a result code without this patch?

I do not think so. I was seeing `SocketException: The operation completed successfully.`

**Comment by JimmyCushnie** [comment]
With icmpv6 support, we should also be able to add IPv6 support to `System.Net.NetworkInformation.Ping`: https://github.com/mono/mono/blob/79b6e3f256a59ede74596ce82547f320bf1e9a99/mcs/class/System/System.Net.NetworkInformation/Ping.cs#L235

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
