### PR TITLE
[interp] add System tests to CI

### PR DESCRIPTION
**Pull request by lewurm**
https://github.com/mono/mono/issues/7053

LSWCIS (let's see what CI says 😛 )

### CODE REVIEW

**Comment by marek-safar** [comment]
I am not very keen on this one. I think we should run full mscorlib tests instead

**Comment by luhenry** [comment]
@marek-safar this is in complement to mscorlib, not a replacement, so what do you mean in https://github.com/mono/mono/pull/8370#issuecomment-383228514?

**Comment by marek-safar** [comment]
Sure, it's complement of other dlls but there is not that much interesting stuff in System.dll for the interpreter. We should add the interesting assemblies first and only if the run is not too long add System.dll.

Right now we run only about 10k of mscorlib tests and ignore remaining 40k+ in there.

**Comment by lewurm** [comment]
> Right now we run only about 10k of mscorlib tests and ignore remaining 40k+ in there.

oh, how would I run the remaining 40k+?

**Comment by lewurm** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Pull request merged**
