### PR TITLE
Support asynchronous handlers of HttpApplication.EndRequest event.

### LINKED ISSUE #12103: HttpApplication does not wait for completion of asynchronous EndRequest handler
I've been investigating cause for web application (made with Owin and Microsoft.Owin.Host.SystemWeb) crashing during load testing with errors such as:
```
System.InvalidOperationException: No owin.Environment item was found in the context.
  at System.Web.HttpContextBaseExtensions.GetOwinContext (System.Web.HttpContextBase context) [0x0000f] in <d9e6b6f255bf4301a4e54f7b988a8be6>:0
```

Apparently, the root cause of this error is this:
1. Microsoft.Owin.Host.SystemWeb uses asynchronous handler of HttpApplication.EndRequest event
2. HttpApplication invokes EndRequest event handler but does not wait for its completion
3. Next HTTP request comes; HttpApplication instance is reused for its processing. This causes race condition with still running handler of EndRequest event.

I've been able to produce a minimal reproducible demonstration of this issue.

## Steps to Reproduce

1. Download and unpack [WebApplication2.zip](https://github.com/mono/mono/files/2690053/WebApplication2.zip). The relevant code is in Global.asax.cs is also on [https://gist.github.com/dmitryvk/0e8f03e30f29f9525378d0f0f56b8f7a](https://gist.github.com/dmitryvk/0e8f03e30f29f9525378d0f0f56b8f7a)
2. Build and run project
```
cd WebApplication2/WebApplication2
msbuild
xsp4 --nonstop --port 5000
```
3. Run 2 consecutive requests:
```
curl http://localhost:5000; sleep 0.1; curl http://localhost:5000
```

### Current Behavior

First request returns `<p>Hello, world</p>`

Second request throws error:

```
[System.Exception]: OnAuthenticateRequest: isEnding: expected false, got true
  at WebApplication2.MvcApplication.OnAuthenticateRequest (System.Object sender, System.EventArgs e) [0x0000e] in <234564addd6c443a807883b5050c4c74>:0 
  at System.Web.HttpApplication+<RunHooks>d__217.MoveNext () [0x00144] in <979c6d3c1df54a4b9abbd8b5ecbe7cbb>:0 
  at System.Web.HttpApplication+<Pipeline>d__225.MoveNext () [0x001ab] in <979c6d3c1df54a4b9abbd8b5ecbe7cbb>:0 
  at System.Web.HttpApplication.Tick () [0x00000] in <979c6d3c1df54a4b9abbd8b5ecbe7cbb>:0
```

### Expected Behavior

Both requests return `<p>Hello, world</p>`

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.16.0.220 (tarball Mon Nov 26 17:05:57 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
```

### PR DESCRIPTION
**Pull request by dmitryvk**
Mono used to invoke the handler but not wait for it to finish.

Microsoft.Owin.Host.SystemWeb relies on async EndRequest event handler in order to manage Owin Context's lifecycle. Failure to await handler completion causes race conditions.

Fixes #12103

### CODE REVIEW

**Comment by dmitryvk** [comment]
Microsoft.Owin.Host.SystemWeb code that uses async EndRequest handler:
https://github.com/aspnet/AspNetKatana/blob/1e6aacff317f93f77dacb89c799e0bf1083fb1e9/src/Microsoft.Owin.Host.SystemWeb/IntegratedPipeline/IntegratedPipelineContext.cs#L94

**Comment by marek-safar** [comment]
approve

**Comment by dmitryvk** [comment]
Some tests are broken. Looking into it

**Comment by dmitryvk** [comment]
I still see some test failures but I'm not sure that they are related to this PR. E.g., some tests for System.Net failed, but tests for System.Web pass

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by dmitryvk** [comment]
Any news on this? We are using own patched version of Mono in production because of this.
If there are any issues with this patch, I'd be happy to do whatever is needed to fix this issue.

**Comment by wolfmanfx** [comment]
Hi,

Yes this really a must have to support OWIN - adding support for it would be great.

**Comment by steveisok** [comment]
@marek-safar If we're going to merge https://github.com/mono/mono/pull/12619, then this PR can be closed since it's fixed there.

**Comment by marek-safar** [comment]
I'd prefer landing #12619 instead

**Comment by steveisok** [comment]
Since the other PR essentially supersedes this one, I'm going to close.

**Pull request closed without merging**
