### PR TITLE
Toggle the turbo button

### PR DESCRIPTION
**Pull request by migueldeicaza**
:-)

### CODE REVIEW

**Comment by marek-safar** [comment]
I'd update man page too

**Comment by lambdageek** [comment]
Please bump the version number... `Turbo C# 6` just sounds better

**Comment by migueldeicaza** [comment]
Well we now support C# 7-ish (some things missing)

**Comment by migueldeicaza** [comment]
Updated man page.

**Comment by lewurm** [comment]
shouldn't it be `tcs` then? 😛

**Comment by baulig** [comment]
@lewurm Did you just volunteer to update every single script, program or tool that's using `mcs` ...?

**Comment by baulig** [comment]
Since most people are using VSMac these days, is there some way of toggling this for `msbuild`?  If there is, could we possibly document that somewhere?

**Comment by akoeplinger** [comment]
how about `Megafast C# Compiler` given that we can't change the `mcs` command 🚀 😄

**Comment by lewurm** [comment]
@baulig an alias would be good enough I guess 🙂

**Comment by akoeplinger** [comment]
@lewurm Typescript already has `tsc`, using `tcs` would be too confusing ;)

**Comment by benaadams** [comment]
🚀 

Hit the turbo!

🚀 🚀 🚀 🚀 🚀 🚀

**Comment by mhutch** [comment]
@baulig `<CscToolExe>mcs</CscToolExe>`

**Comment by directhex** [comment]
Can someone fix monop while we're at it? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754259

**Comment by baulig** [comment]
What's monop - tried a google search and what it came up with was some grocery store in Paris.

**Comment by txdv** [comment]
O my god, this sped up compilation significantly, please add all the new c# features asap into mcs! :rocket: :rocket: :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:  :rocket: :rocket:

**Comment by migueldeicaza** [comment]
Martin, monop is a legendary tool in Mono, inspired by "javap" it prints out on stdout the public API of a specified type.

**Comment by sailro** [comment]
I hope Turbo Compiler is not a registered trademark anymore ... (Borland?)

**Pull request merged**
