### PR TITLE
Bump version to 6.7

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by marek-safar** [comment]
I don't think bumping linker should be included here. There is pending PR for that already because it's not trivial

**Comment by directhex** [comment]
I don't really understand the WebAssembly build system, but `FileNotFoundError: [Errno 2] No such file or directory: '/home/builder/.local/lib/python3.6/site-packages/clang-6.0.0.2.dist-info/RECORD.pip' -> '/home/builder/.local/lib/python3.6/site-packages/clang-6.0.0.2.dist-info/RECORD'`
 looks related?

**Comment by directhex** [comment]
osx android failure is:

```
System.Runtime.Serialization.SerializationException: End of Stream encountered before parsing was completed.
  at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run () [0x0027e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryparser.cs:257 
  at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Runtime.Serialization.Formatters.Binary.__BinaryParser serParser, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00069] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryobjectreader.cs:174 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Boolean isCrossAppDomain, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00099] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:197 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck, System.Runtime.Remoting.Messaging.IMethodCallMessage methodCallMessage) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:173 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler, System.Boolean fCheck) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:118 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream, System.Runtime.Remoting.Messaging.HeaderHandler handler) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:149 
  at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize (System.IO.Stream serializationStream) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-04/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs:111 
  at Xamarin.AndroidTestAssemblyRunner.Run (NUnit.Framework.Api.ITestListener listener, NUnit.Framework.Api.ITestFilter filter) [0x00013] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mcs/tools/nunit-lite/NUnitLite/AndroidTestAssemblyRunner.cs:67 
  at NUnitLite.Runner.TextUI.RunTests (NUnit.Framework.Api.ITestFilter filter) [0x0001e] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/external/nunit-lite/NUnitLite-1.0.0/src/framework/Runner/TextUI.cs:359 
  at NUnitLite.Runner.TextUI.Execute (System.String[] args) [0x00352] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/external/nunit-lite/NUnitLite-1.0.0/src/framework/Runner/TextUI.cs:259 
```

Will see if it's flakey.

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build failed

**Pull request merged**
