### PR TITLE
[Mono.Debugger.Soft] Make exposing Cecil metadata an option

### PR DESCRIPTION
**Pull request by jbevain**
Not all downstream users of the Mono.Debugger.Soft library are using the feature where mirrors provide direct access to the Cecil metadata if the `AssemblyMirror` has been fed a Cecil `AssemblyDefinition`.

This PR introduces a define to opt-in to use the Cecil metadata, otherwise falls back to exposing System.Reflection.Emit opcodes in the Instruction API.

### CODE REVIEW

**Comment by vargaz** [comment]
Why does this have to be behind an ifdef ?

**Comment by marek-safar** [comment]
@jbevain what is the intention with the define? why you want a version which has no Cecil dependency?

**Comment by jbevain** [comment]
@marek-safar yes that is correct, we're not using this feature and would like to avoid taking a dependency we don't use.

**Comment by jbevain** [comment]
@vargaz would you rather remove the feature completely? That would be a big API break, and some downstreams like `mono/debugger-libs` may be using it.

I figured this way people can choose to take the dependency or not.

@marek-safar , @vargaz , would you prefer to have the Cecil dependency opt-out instead of opt-in?

**Comment by vargaz** [comment]
What problem having this dependency causes ? Its just an assembly which has to be present, its a desktop assembly, it shouldn't be a problem.

**Comment by jbevain** [comment]
@vargaz we're just trying to cut down on our dependencies. Inside Visual Studio, everything has to run in one app domain, and we've seen conflicts of assemblies like Cecil between plugins.

To address this we have our own Cecil with its own strong name, but we're not using anywhere and would like to not have to ship it. Shipping assemblies as part of VS means a bunch of bookkeeping for each assembly, so we'd gladly remove one that we're not using.

**Comment by vargaz** [comment]
Its ok, it just looks a bit ugly. Also, the define could simpler like ENABLE_CECIL or something.

**Comment by jbevain** [comment]
@vargaz here you go :)

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Pull request merged**
