### PR TITLE
[wasm] [sdk] Build and package the sdk nugets.

### PR DESCRIPTION
**Pull request by kjpou1**
Build and Package the sdk nugets with the WebAssembly SDK available from jenkins

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
@monojenkins build failed

**Pull request merged**
