### PR TITLE
Bump msbuild to track mono-2019-02

### PR DESCRIPTION
**Pull request by radical**
.. to pick up an update for the NuGetSdkResolver.

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Depends on https://github.com/mono/mono/pull/14061 .

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
`OS X Extended` some generated tests failing to compile, which should be because of the string
`llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found` ending up in the generated source
file, same as https://github.com/mono/mono/pull/14061#issuecomment-483505877 .
Unrelated to this PR:

```
19:54:06 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
19:54:06 
19:54:06 Mono Warning: llvm support could not be loaded.
19:54:06 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
19:54:06 
19:54:06 Mono Warning: llvm support could not be loaded.
19:54:06 llvm load failed: dlopen(libmono-llvm.bundle, 9): image not found
19:54:06 
19:54:06 Mono Warning: llvm support could not be loaded.
19:54:07 runtime-invoke.gen.cs(1,11): error CS1002: ; expected
19:54:07 runtime-invoke.gen.cs(1,11): error CS0116: A namespace cannot directly contain members such as fields or methods
19:54:07 runtime-invoke.gen.cs(1,17): error CS1022: Type or namespace definition, or end-of-file expected
19:54:07 runtime-invoke.gen.cs(1,33): error CS1001: Identifier expected
19:54:07 runtime-invoke.gen.cs(1,33): error CS1003: Syntax error, ',' expected
19:54:07 runtime-invoke.gen.cs(1,34): error CS1003: Syntax error, ',' expected
19:54:07 runtime-invoke.gen.cs(1,45): error CS1001: Identifier expected
19:54:07 runtime-invoke.gen.cs(1,47): error CS1031: Type expected
19:54:07 runtime-invoke.gen.cs(1,47): error CS1001: Identifier expected
19:54:07 runtime-invoke.gen.cs(1,47): error CS1003: Syntax error, ',' expected
19:54:07 runtime-invoke.gen.cs(1,51): error CS1018: Keyword 'this' or 'base' expected
19:54:07 runtime-invoke.gen.cs(1,51): error CS1002: ; expected
19:54:07 runtime-invoke.gen.cs(1,61): error CS1002: ; expected
19:54:07 runtime-invoke.gen.cs(1,61): error CS0116: A namespace cannot directly contain members such as fields or methods
19:54:07 runtime-invoke.gen.cs(3,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations
19:54:07 runtime-invoke.gen.cs(4,1): error CS1529: A using clause must precede all other elements defined in the namespace except extern alias declarations
```

**Comment by lewing** [comment]
What is the status of this?

**Comment by radical** [comment]
@lewing This has been ready for merge waiting for approvals. But a recent F# commit caused merge conflicts here, just updated to fix that.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
2 failing msbuild tests, will fix this tomorrow.

**Comment by radical** [comment]
Fix for the tests - https://github.com/mono/msbuild/pull/99

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Fix for one failing test - https://github.com/mono/msbuild/pull/103 .

**Comment by radical** [comment]
Unrelated `sgen` test failures on Linux.

**Comment by lewing** [comment]
does this need another bump or are we waiting on something else?

**Comment by radical** [comment]
I want to bump this to include the recent fixes in msbuild, but I hit some test failures on linux that I'm fixing.

**Comment by radical** [comment]
Hmm running into a very weird bug. Still debugging it :/

**Comment by lewing** [comment]
Any progress here?

**Comment by lewing** [comment]
@monojenkins build Linux ARMv7

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Unrelated failures. msbuild bits look fine.

**Pull request merged**
