### PR TITLE
Fix transition offset logic

### PR DESCRIPTION
**Pull request by MaximLipnin**
I'm not sure about the correctness of this workaround but it works on macOS for the repro from https://github.com/mono/mono/issues/9664#issuecomment-472260968

Transition bounds used by time zone info represent some local date-time but actually they are of Unspecified date-time kind. 
When we try to get transition offset we compare some current date-time converted to UTC with appropriate transition bounds.
The fix is to use UTC for both current date-time and transition bounds during comparing.

Fixes https://github.com/mono/mono/issues/9664

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
Should it be closed due to merging the fix to master and 2019-02?

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Pull request merged**
