### PR TITLE
Bugs/hmac wrong keysizes

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by alexrp** [comment]
Please add tests for this.

**Comment by haf** [comment]
What sort of tests are you thinking about?

**Comment by alexrp** [comment]
Well, unit tests that would be broken before this change but work after it.

**Comment by haf** [comment]
That's not specific enough.

I'm changing the key-size, and there are [already unit tests that test for different key sizes](https://github.com/mono/mono/blob/master/mcs/class/corlib/Test/System.Security.Cryptography/HMACSHA256Test.cs#L168), including sizes larger than the block size. According to RFC 2104:

```
   The definition of HMAC requires a cryptographic hash function, which
   we denote by H, and a secret key K. We assume H to be a cryptographic
   hash function where data is hashed by iterating a basic compression
   function on blocks of data.   We denote by B the byte-length of such
   blocks (B=64 for all the above mentioned examples of hash functions),
   and by L the byte-length of hash outputs (L=16 for MD5, L=20 for
   SHA-1).  The authentication key K can be of any length up to B, the
   block length of the hash function.  Applications that use keys longer
   than B bytes will first hash the key using H and then use the
   resultant L byte string as the actual key to HMAC.
```

It works with any key-size, and I can't write unit tests that would disallow users, like those of mono, to shoot themselves in the foot by using extremely weak key sizes.

**Comment by alexrp** [comment]
That's ok then.

I notice f3d2c41b26af42fde13889ff9c7870ed8916aa3c in particular doesn't cite an MSDN source. Does .NET use a key size of 64?

**Comment by haf** [comment]
I can write a test that asserts the key length, perhaps.

**Comment by akoeplinger** [comment]
> I notice  f3d2c41  in particular doesn't cite an MSDN source. Does .NET use a key size of 64?

According to [hmacsha1.cs#L20](https://github.com/mono/referencesource/blob/mono/mscorlib/system/security/cryptography/hmacsha1.cs#L20) from MS referencesource it does :)

**Comment by haf** [comment]
Added tests, but they are broken for two of the five algos

```
Test Case Failures:
1) MonoTests.System.Security.Cryptography.HMACRIPEMD160Test.Invariants :   HMACRIPEMD160.Key.Length
  Expected: 64
  But was:  8

at MonoTests.System.Security.Cryptography.HMACRIPEMD160Test.Invariants () [0x0008a] in /Users/henrik.feldt/dev/haf/mono/mcs/class/corlib/Test/System.Security.Cryptography/HMACRIPEMD160Test.cs:425
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /Users/henrik.feldt/dev/haf/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230

2) MonoTests.System.Security.Cryptography.HMACSHA256Test.Invariants :   HMACSHA256.Key.Length
  Expected: 64
  But was:  8

at MonoTests.System.Security.Cryptography.HMACSHA256Test.Invariants () [0x0008a] in /Users/henrik.feldt/dev/haf/mono/mcs/class/corlib/Test/System.Security.Cryptography/HMACSHA256Test.cs:77
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in /Users/henrik.feldt/dev/haf/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:230
```

**Comment by akoeplinger** [comment]
@haf I guess that's because of the `algo.Key = new byte [8];` in the Setup() method.

**Comment by akoeplinger** [comment]
whitelist

**Comment by haf** [comment]
Merge??

**Pull request merged**
