### PR TITLE
Fix SQL Server 2012 bulk insert issues

### PR DESCRIPTION
**Pull request by ztzg**
These patches enable the bulk insertion of the following types, and their null values, in an instance of SQL Server 2012.

    string           "@@@"
    int              0x40
    long             0x40deadbeef
    byte             (byte)0x40
    double           0.3333
    float            10.5f
    boolean          true
    guid             Guid.NewGuid()
    datetime2        DateTime.Now
    datetimeoffset   DateTimeOffset.Now

(Full processing of datetime2/datetimeoffset require additional patches, cf. PR https://github.com/mono/mono/pull/1773.)

### CODE REVIEW

**Comment by ztzg** [comment]
Please note that the bot is lagging; I *have* signed the Xamarin CLA.

**Comment by tritao** [comment]
Can you provide a test case?

**Comment by atsushieno** [comment]
Having tests is ideal, but it's not easy to verify that without working SQL Server. We don't have nunit tests that we regularly run. I'd rather approve that. They "look" good to me.

**Comment by ztzg** [comment]
Hi @tritao,

The tests I have at hand do indeed require a working SQL server, and I did not see any obvious & reasonably cheap way to ship them with Mono.  But please feel free to point me to any test infrastructure and/or documentation I may have missed, so that I can take it into account for any future updates.

**Comment by atsushieno** [comment]
When I was testing SqlClient + referencesource integration, I verified it using this isolated tests.
https://github.com/mono/mono/tree/master/mcs/class/System.Data/Test/DataProviderTests

We don't run it regularly so it's not very assuring, but you might find it useful to add new tests.

**Comment by ztzg** [comment]
Hi Atsushi,

Thank you!  I have been busy with unrelated stuff, but will have a look
at integrating tests into that framework when I circle back to this
topic.

Cheers, -D

**Comment by EvK** [comment]
Hi, in your d7a417a commit, in mcs/class/System.Data/System.Data.SqlClient/SqlParameter.cs
file, in ConvertToFrameworkType (object value, Type frameworkType), you convert any DateTime to a string using high precision. However, this causes problems when Entity Framework generates sql commands with dates. Namely, if I try to insert any column of "datetime" (not "datetime2" type), I get "Conversion failed when converting date and/or time from character string.", because "datetime" type has less precision (3 digits of second fraction vs 7 in your code).

**Comment by ztzg** [comment]
Hi EvK,

Thank you for the notification!

Does the attached patch (compiles, but untested) help?  It uses 3 digits
for every date *but* DateTime2 and DateTimeOffset.  (Also: should it use
0 for SmallDateTime?  To be investigated later.)

Cheers, -D

**Comment by ztzg** [comment]
Dammit, Github—trimming email attachments.

@EvK: I have pushed the commit there: https://github.com/ztzg/mono/commit/3383aa972540e54a658c980eda2d22ba98a848c0

**Comment by EvK** [comment]
Unfortunately, this issue is not limited (or maybe even not related) to the function above. For some reason, my "datetime" columns are treated as "datetime2" columns, hence the problem. I verified this by temporary changing TdsMetaParameter.GetDateTimePrecision function to return 3 precision max instead of 7, then it works. Maybe you have some idea why datetime is always treated as datetime2. My code works without problems under .NET, but fails on mono.

**Comment by EvK** [comment]
More on this issue: if you create EF model which targets sql server 2012, and then will try to select something from table with date column, it will fail with the following exception: The specified cast from a materialized 'System.String' type to the 'System.DateTime' type is not valid. So it seems when targeting sql server 2012, EF works with all dates using "datetime2" type, and for some reason Tds treats that as String. So support of datetime2 type for selects seems does not work at all.

**Comment by ztzg** [comment]
Wait…  The failure may not be related to these patches at all.  This PR is part of a series which add rudimentary `datetime2` support to Mono's TDS, which did not support `datetime2` *at all* before (Cf. https://github.com/mono/mono/pull/1773).

I know that it's not complete, and the proper solution is probably to switch MS' "referencesource" implementation.

Can you tell us if your EF model works with Mono as of commit 12a41c8d50132?

Thanks, -D

**Comment by atsushieno** [comment]
To make sure, we cannot simply switch to referencesource because it's basically PInvokes to Windows-only native libraries.

**Comment by EvK** [comment]
Well if use version before that rudimentary support was added, it just throws exception about missing mapping to SqlDbType.DateTime2. Shouldn't we move discussion to #1773 thread then? Seems problem indeed is related there, didn't notice that issue before.

**Comment by ztzg** [comment]
@atsushieno: Right.  I actually had a look at MS' referencesource before submitting the hackish `datetime2` solution, but untangling these P/Invokes seemed far from trivial.

@EvK: Commit 12a41c8, which I mentioned above, predates my complete set of (three) pull requests.  Mono's TDS driver has never been 100% complete; I *may* be able contribute some more features and/or give another try to referencesource frankeinsteinization at some point, but don't hold your breath.

**Pull request merged**
