### PR TITLE
[mini] Allow stind.ref only on object references.

### PR DESCRIPTION
**Pull request by lewurm**
rebased https://github.com/mono/mono/pull/1630

### CODE REVIEW

**Comment by marek-safar** [comment]
build

**Comment by luhenry** [comment]
@monojenkins build

**Comment by alexischr** [comment]
```
Failed test(s):

pinvoke3.exe
=============== pinvoke3.exe.stdout ===============

=============== EOF ===============
=============== pinvoke3.exe.stderr ===============

Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: Invalid IL code in (wrapper native-to-managed) Tests:delegate_test_class_byref (Tests/SimpleClass&): IL_00d1: stind.ref 


  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_delegate_to_ftnptr(object)
  at (wrapper managed-to-native) Tests.mono_test_marshal_delegate5(Tests/SimpleDelegate5)
  at Tests.test_0_marshal_byref_class_delegate () [0x0000e] in <4b73be9e01024d0196d6c12f6de96e0c>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7a283bd59d12435f8252165909034bac>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <7a283bd59d12435f8252165909034bac>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <7a283bd59d12435f8252165909034bac>:0 
  at TestDriver.RunTests (System.Type type, System.String[] args, TestDriverReporter reporter) [0x003b9] in <b414a5ec21b74c57a436a8e730952818>:0 
  at TestDriver.RunTests (System.Type type) [0x00001] in <b414a5ec21b74c57a436a8e730952818>:0 
  at Tests.Main () [0x00001] in <4b73be9e01024d0196d6c12f6de96e0c>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: Invalid IL code in (wrapper native-to-managed) Tests:delegate_test_class_byref (Tests/SimpleClass&): IL_00d1: stind.ref 


  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_delegate_to_ftnptr(object)
  at (wrapper managed-to-native) Tests.mono_test_marshal_delegate5(Tests/SimpleDelegate5)
  at Tests.test_0_marshal_byref_class_delegate () [0x0000e] in <4b73be9e01024d0196d6c12f6de96e0c>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7a283bd59d12435f8252165909034bac>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <7a283bd59d12435f8252165909034bac>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <7a283bd59d12435f8252165909034bac>:0 
  at TestDriver.RunTests (System.Type type, System.String[] args, TestDriverReporter reporter) [0x003b9] in <b414a5ec21b74c57a436a8e730952818>:0 
  at TestDriver.RunTests (System.Type type) [0x00001] in <b414a5ec21b74c57a436a8e730952818>:0 
  at Tests.Main () [0x00001] in <4b73be9e01024d0196d6c12f6de96e0c>:0 

=============== EOF ===============

pinvoke2.exe
=============== pinvoke2.exe.stdout ===============

=============== EOF ===============
=============== pinvoke2.exe.stderr ===============

Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: Invalid IL code in (wrapper managed-to-native) Tests:mono_test_marshal_empty_string_array (string[]): IL_004e: stind.ref 


  at Tests.test_0_marshal_empty_string_array () [0x00001] in <9a3b25b83e874dc5b1aa69728c9b972b>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7a283bd59d12435f8252165909034bac>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <7a283bd59d12435f8252165909034bac>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <7a283bd59d12435f8252165909034bac>:0 
  at TestDriver.RunTests (System.Type type, System.String[] args, TestDriverReporter reporter) [0x003b9] in <b414a5ec21b74c57a436a8e730952818>:0 
  at TestDriver.RunTests (System.Type type, System.String[] args) [0x00001] in <b414a5ec21b74c57a436a8e730952818>:0 
  at Tests.Main (System.String[] args) [0x00001] in <9a3b25b83e874dc5b1aa69728c9b972b>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: Invalid IL code in (wrapper managed-to-native) Tests:mono_test_marshal_empty_string_array (string[]): IL_004e: stind.ref 


  at Tests.test_0_marshal_empty_string_array () [0x00001] in <9a3b25b83e874dc5b1aa69728c9b972b>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7a283bd59d12435f8252165909034bac>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <7a283bd59d12435f8252165909034bac>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <7a283bd59d12435f8252165909034bac>:0 
  at TestDriver.RunTests (System.Type type, System.String[] args, TestDriverReporter reporter) [0x003b9] in <b414a5ec21b74c57a436a8e730952818>:0 
  at TestDriver.RunTests (System.Type type, System.String[] args) [0x00001] in <b414a5ec21b74c57a436a8e730952818>:0 
  at Tests.Main (System.String[] args) [0x00001] in <9a3b25b83e874dc5b1aa69728c9b972b>:0
```

**Comment by lewurm** [comment]
@alexischr thanks, should be fixed now.

@kumpera I'll dismiss your review, this puppy needs another round of reviewing

**Pull request merged**
