### PR TITLE
[CI] Update Clang's ThreadSanitizer blacklist

### PR DESCRIPTION
**Pull request by cherusker**
I ran an extended test on https://github.com/mono/mono/commit/20bbf3208687b3f12582a35103bd6a6c9bb8a32e since there were a few commits recently that targeted data races. A few functions are expectedly "clean" now (in the sense of data races) but a lot of new racy functions turned up.

Anyways - as an interim result: races of global variables are mostly dealt with by now (classic reporting counters and similar things). There are only a few of these races left that I will work on within the next weeks.

### CODE REVIEW

**Comment by cherusker** [comment]
@monojenkins build clang sanitizer

**Comment by cherusker** [comment]
@monojenkins build clang sanitizer

**Comment by cherusker** [comment]
@monojenkins build clang sanitizer

**Comment by cherusker** [comment]
@monojenkins build clang sanitizer

**Comment by cherusker** [comment]
@monojenkins build clang sanitizer

**Comment by akoeplinger** [comment]
@cherusker is this ready to be merged now?

**Comment by cherusker** [comment]
@akoeplinger Yes, it is, thanks for asking! :)

**Pull request merged**
