### PR TITLE
Update CMake version for BTLS

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by akoeplinger** [comment]
what's the reason for this change?

**Comment by luhenry** [comment]
@akoeplinger no reason in particular, I was just going over the cmake version BTLS was using and it turns out we can use a later one.

**Comment by akoeplinger** [comment]
hm that doesn't sound like a compelling reason to take this patch :)

**Comment by luhenry** [comment]
@akoeplinger fair enough 😄

**Pull request closed without merging**
