### PR TITLE
Cross32 changes.

### PR DESCRIPTION
**Pull request by vargaz**
Part of #9621

### CODE REVIEW

**Comment by kumpera** [comment]
Hey Zoltan, can you update the man page and —AOT-help?

And can you start a page on the website explaining the dos and donts to make this work?

**Comment by migueldeicaza** [comment]
Folks, before we embark on these disruptive changes to the runtime, I want to consider cheaper alternatives to this.   For example, using QEmu/Userland to run the 32-bit binaries in 64-bit mode or using the WebAssembly work to run inside WebAssembly.

**Comment by jaykrell** [comment]
Suggest to put the name "target" in somewhere. target_sizeof, target_offsetof, target_mono_foo maybe.

Many but not all compilers are structured this way and "fixing" would enable many other scenarios, that may or may not be interesting. I.e. arbitrary cross AOT. Like people get from all their C and C++ compilers.

Lack of distinction between host and target in a compiler is kinda a short term hack.

**Comment by vargaz** [comment]
Was merged in other PRs.

**Pull request closed without merging**
