### PR TITLE
[bockbuild] Re-enable validate_symlinks processing step

### PR DESCRIPTION
**Pull request by alexischr**
Fixes https://github.com/mono/mono/issues/15521

Do not merge, points to open bockbuild PR

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by akoeplinger** [comment]
6794b80 doesn't seem to fix the issue, there are still the .release symlinks in the .pkg.

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
@monojenkins build pkg

**Comment by alexischr** [comment]
I still don't know why `match_symlinks` wasn't apparently working, but it was replaced with `match_all`. Also another mistake was fixed with the use of the "harness function".

It looks like the `.release` dangling symlinks are finally gone. @akoeplinger can you confirm and approve, and then I will rebase/remove the `--trace` argument.

**Comment by akoeplinger** [comment]
I confirmed the .release symlinks are finally gone and merged the bockbuild PR :)

**Comment by akoeplinger** [comment]
This was included in the bockbuild bump from https://github.com/mono/mono/commit/a19aaa31da9257280ee4ef7a83652c9d90f042f0 so this PR is no longer needed, closing.

**Pull request closed without merging**
