### PR TITLE
Make Random use multiplication-free xorshift algorithm

### PR DESCRIPTION
**Pull request by kasthack**
Performance gain:
random.Next() — 1.9X
random.NextDouble() — 3.4X
random.NextBytes() — 4.5X

### CODE REVIEW

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by tritao** [comment]
For reference, the same pull was rejected on CoreCLR on the basis of compatibility: https://github.com/dotnet/coreclr/pull/118

**Comment by akoeplinger** [comment]
On top of that, this has unacceptable whitespace changes (tabs vs. spaces).

Just so I understand: the compatibility concern was around different values generated when a seed is specified, correct?

**Comment by kasthack** [comment]
>On top of that, this has unacceptable whitespace changes (tabs vs. spaces).
Fxd.
>Just so I understand: the compatibility concern was around different values generated when a seed is specified, correct?
Generated values are different from current System.Random's implementation output due to different algorithm but equal between two instances with same seed.
https://gist.github.com/kasthack/68e647576824d2eff599

**Comment by akoeplinger** [comment]
The problem is that the seed is often used in test data / when reproducibility is needed so changing the algorithm breaks those scenarios.

Let's see what the maintainers say :)

**Comment by tritao** [comment]
Thanks for the contribution but we'll soon be moving this class to .NET's reference source code so there's no point in merging this at the moment.

**Comment by kasthack** [comment]
OK

**Pull request closed without merging**
