### PR TITLE
[runtime] Remove all NACL support. It was unmaintained for a long time.

### PR DESCRIPTION
**Pull request by vargaz**
https://blog.chromium.org/2017/05/goodbye-pnacl-hello-webassembly.html

### CODE REVIEW

**Comment by vargaz** [comment]
build

**Comment by luhenry** [comment]
You can also remove DISABLE_SOCKETS

**Comment by kumpera** [comment]
Isn't DISABLE_SOCKETS used by the products?

**Comment by luhenry** [comment]
@kumpera doesn't seem like it. They would have no way of defining it, and none of our products contain DISABLE_SOCKETS

**Comment by akoeplinger** [comment]
nacl-stub.c needs to be removed from the MSVC projects as well.

**Comment by kumpera** [comment]
@luhenry you're right DISABLE_SOCKETS can go

**Comment by vargaz** [comment]
Is DISABLE_SOCKETS useful for the future ?

**Comment by luhenry** [comment]
@vargaz we do it differently on all other platforms that do not support socket (ie watchOS), so I wouldn't say it will be useful in the future.

**Comment by joncham** [comment]
We are interested in building the runtime on WebGL/emscripten in the near future where `DISABLE_SOCKETS` might be available, but that may not be a reason to keep this.

**Pull request merged**
