### PR TITLE
[corlib] TimeZoneInfo from corefx

### PR DESCRIPTION
**Pull request by EgorBo**
Not yet enabled for mobile, build and basic profiles.
Doesn't require ICU dependency, also I created a small PR for dotnet/coreclr to improve TimeZoneInfo.DisplayName on unix: https://github.com/dotnet/coreclr/pull/20728

Part of #7737

### CODE REVIEW

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@EgorBo could you resolve the conflict?

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@EgorBo the interpreter failures are related to this change

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Pull request merged**
