### PR TITLE
[Mono.Posix] Fix the SocketTest.ControlMsg() test on OSX

### PR DESCRIPTION
**Pull request by steffen-kiess**
See https://github.com/mono/mono/pull/2514 for context.

Unlike Linux, OSX does not allow multiple SCM_RIGHTS control messages in
sendmsg().
The SocketTest.ControlMsg() test is split into two tests, one which sends
only a single control message (containing two FDs), and another one which
sends two control messages (each containing one FD). The second test is not
executed on OSX.

I'm not sure whether the OSX behaviour is correct, as POSIX doesn't say much about how SCM_RIGHTS works. Anyway, the old test case is something which is rather unlikely to appear in a real program (normally you would use one control message containing multiple FDs), but I'd like to keep it on Linux because it also tests having multiple control messages at all, so I've split the test into two tests, where one isn't executed on OSX.

### CODE REVIEW

**Comment by akoeplinger** [comment]
It fails on OSX on line 824 now (msghdr2.msg_flags is 0 at that point):

```
Assert.IsTrue ((msghdr2.msg_flags & MessageFlags.MSG_CTRUNC) != 0); // Control message has been truncated
```

If I comment out the assert the test works, so maybe just something that doesn't take useMultipleControlMessages into account?

**Comment by steffen-kiess** [comment]
> If I comment out the assert the test works, so maybe just something that doesn't take useMultipleControlMessages into account?

I don't think so, this looks more like a OSX bug (because the control message *is* truncated here), but I've updated the PR to ignore this assert when use `useMultipleControlMessages` is not set (i.e. on OSX).

**Comment by akoeplinger** [comment]
LGTM, it passes now.

@monojenkins build
@monojenkins merge

**Comment by akoeplinger** [comment]
build

**Comment by akoeplinger** [comment]
Failures are unrelated (and know flaky tests). Merging.

**Pull request merged**
