### PR TITLE
Bump corefx

### PR DESCRIPTION
**Pull request by MaximLipnin**
This PR brings changes from https://github.com/mono/corefx/pull/313.
Fixes https://github.com/mono/mono/issues/15887.

### CODE REVIEW

**Comment by steveisok** [comment]
If possible, please add a test.

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
I used this PR as the guinea pig for getting in https://github.com/mono/corefx/pull/315 as this one had conflicts on corefx anyway.

**Comment by MaximLipnin** [comment]
@akoeplinger thanks

**Comment by steveisok** [comment]
@monojenkins backport 2019-06

**Pull request merged**
