### PR TITLE
[gc] add stop-the-world api

### PR DESCRIPTION
**Pull request by lambdageek**
It's sometimes useful to have a way for the runtime to stop the world.  Only works on SGen.

### CODE REVIEW

**Comment by lambdageek** [comment]
Cherrypicking reusable stuff from some WIP

**Review by CoffeeFlux — APPROVED** [review]
Do we need an implementation for null GC? Otherwise looks fine.

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
FYI this was taken from @migueldeicaza's branch https://github.com/migueldeicaza/mono/commit/4f4934f00b959911e7879216d4664b7b54184a74

**Pull request merged**
