### PR TITLE
[interp] Implement runtime invokes by executing the runtime-invoke wr…

### PR DESCRIPTION
**Pull request by vargaz**
…appers using the interpreter. This saves some code and allows better interop with JIT exceptions.

### CODE REVIEW

**Comment by vargaz** [comment]
build interpreter

**Comment by lewurm** [comment]
nice!  there's a failure in `context-static.exe` though which I'm not sure what this is about.

**Comment by vargaz** [comment]
It fails with master as well.

**Comment by lewurm** [comment]
not on CI: https://jenkins.mono-project.com/job/test-mono-interpreter/

it seems to be a stack issue again, I'm fine with disabling this test.

**Pull request merged**
