### PR TITLE
[libgc] Fix broken AC_TRY_COMPILE() invocation in configure.ac.

### PR DESCRIPTION
**Pull request by alexrp**
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=40144

Tested on PowerPC by `Mathieu Malaterre <malat@debian.org>`.

### CODE REVIEW

**Comment by akoeplinger** [comment]
LGTM. Let's try getting this into C7 too.

**Comment by alexrp** [comment]
Not sure what's up with the OS X failures, but they look unrelated.

**Comment by kumpera** [comment]
LGTM

**Comment by alexrp** [comment]
@monojenkins merge

**Pull request merged**
