### PR TITLE
[runtime] Package merp params in 3 ways needed

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@monojenkins backport 2018-02

**Comment by alexanderkyte** [comment]
@monojenkins backport 2018-04

**Comment by alexanderkyte** [comment]
Responded after heard back from the GDPR folks

**Comment by alexanderkyte** [comment]
@monojenkins backport 2018-04

**Comment by luhenry** [comment]
@monojenkins backport 2018-06

**Comment by alexanderkyte** [comment]
@monojenkins backport 2018-02 

by request

**Pull request merged**
