### PR TITLE
Bump msbuild to track mono-2018-08-test

### PR DESCRIPTION
**Pull request by radical**
Bump to get the msbuild 16 update

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins OS X Extended

**Comment by radical** [comment]
@monojenkins OS X Package

**Comment by radical** [comment]
@monojenkins OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X package

**Comment by radical** [comment]
Testing this with bockbuild bumped using a temporary branch. I will update the reference once https://github.com/mono/bockbuild/pull/95 is merged.

**Comment by radical** [comment]
Testing this with bockbuild bumped using a temporary branch. I will update the reference once https://github.com/mono/bockbuild/pull/95 is merged.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Failed tests on OSX:
```
MonoTests.runtime.threadpool-exceptions7.exe
RemotingServicesTest.Bug46473
```

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build OS X Package

**Comment by marek-safar** [comment]
@radical we'll need similar thing for 2018-10 and 2019-02

**Pull request merged**
