### PR TITLE
[netcore] Do not crash the runtime in System.Reflection.Emit.ILGeneration tests

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by vargaz** [comment]
I think we should exclude the crashing tests instead.

**Comment by filipnavara** [comment]
> I think we should exclude the crashing tests instead.

They are excluded at the moment, but it's quite hard to debug them. Some of the inputs work properly, but not all.

The two functions on `MonoDomain` are called by the runtime. A proper fix would be to implement the callbacks on `AssemblyLoadContext`, but having something non-crashing makes it easier to estimate what is still missing/broken.

I prefer not to crash the runtime if the error can be communicated back through reasonable means. This is user input, not some internal inconsistency.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by filipnavara** [comment]
@monojenkins build Linux ARMv7

**Comment by filipnavara** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Pull request merged**
