### PR TITLE
[llvm] Bump llvm to release_60/fc854b8ec5873d294b80afa3e6cf6a88c5c48886.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/9750.

### CODE REVIEW

**Comment by jaykrell** [comment]
Maybe mention what it fixes in the commit.

**Comment by lewurm** [comment]
https://github.com/mono/llvm/commit/fc854b8ec5873d294b80afa3e6cf6a88c5c48886

**Comment by lewurm** [comment]
`Linux x64 FullAOT+LLVM` is a known failure.

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by vargaz** [comment]
@monojenkins backport 2018-06

**Pull request merged**
