### PR TITLE
[corlib] Don't include time of day in adjustment rule dates.

### PR DESCRIPTION
**Pull request by madewokherd**
This fixes creation of TimeZoneInfo for some time zones on Wine (such
as Israel Standard Time) and probably also Windows.

### CODE REVIEW

**Comment by marek-safar** [comment]
It'd be great if you could also add a unit test for this

**Comment by madewokherd** [comment]
A test case would require hard-coding the name of a time zone that fails, and I don't think I can rely on that on non-Windows systems.

I'd have expected enumerating timezones to fail, but it seems the exception is caught somewhere.

**Comment by madewokherd** [comment]
If we check for a specific value in Windows timezone keys instead of catching exceptions, that should make the tests fail when there's a problem reading one of them. I see we reference other timezone id's in the tests, so we could do that here, but I can't be sure they'll exist on all supported platforms.

**Comment by madewokherd** [comment]
Update: I removed the try/catch around reading timezone info on Windows. That revealed more problems, and I concluded that the right way to do this was to always use January 1 and December 31 for the date range. That seems consistent with the timezone information reported by .NET. I also added a test for a specific timezone that failed.

**Pull request merged**
