### PR TITLE
[llvm] Add a mono wrapper method for the gc poll cold cconv wrapper so the EH code can unwind through it.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by lewurm** [comment]
tested locally, fixes the issue with `block_guard_restore_aligment_on_exit.exe` on Linux/AMD64 FullAOT+LLVM.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
