### PR TITLE
Fix DateTime.Now and CurrentTimeToUtc during DST transition time

### PR DESCRIPTION
**Pull request by nealef**
During the ambiguous hour .NET will return the DST version of the time whereas mono is returning the base time. Rather than use the transitions array we look up the Adjustment rules (which are created from the transition rules in the first place).

In addition, CurrentTimeToUtc() also has problems around the transition time.

Added test and fixed another.

Fixes #43805.

### CODE REVIEW

**Comment by marek-safar** [comment]
There are 2 test failures caused by this change

**Comment by nealef** [comment]
For the GetUtcOffset failure, this is related to the way .NET treats the ambiguous hour. In the doc it says you default to standard time, but .NET defaults to DST. So the failing test has the following:

DST Start: 5/16/2014 12:00:00 AM 
DST End: 6/29/2014 12:00:00 AM 
baseUtcOffset: 02:00:00 
dstOffset: 01:00:00 
dstUtcOffset: 03:00:00

The test checks the hour before the transition:

d: 6/28/2014 11:00:00 PM 

GetUtcOffset used to return 02:00:00 but will now return 03:00:00 so we fail.

Similarly, the DSTTransisions test (which I will change to DSTTransitions) also needs to use the .NET interpretation of the ambiguous hour.

**Comment by nealef** [comment]
Ping?

**Comment by marek-safar** [comment]
build

**Pull request merged**
