### PR TITLE
[arm] respect I1 and I2 on gsharedvt out transition

### PR DESCRIPTION
**Pull request by lewurm**
In order to trigger the problem, we must call into gsharedvt code ("in" transition) and then escape the gsharedvt world ("out" transition). The bug happens in the latter. Also some other stars need to align (I haven't fully understood it), thus the repro is quite long.

The provided repro only triggers with LLVM, which we don't have enabled on CI yet: https://github.com/mono/mono/issues/15999

Fixes https://github.com/mono/mono/issues/15261
Fixes https://github.com/mono/mono/issues/15262
Fixes https://github.com/mono/mono/issues/15263
Fixes https://github.com/mono/mono/issues/15307

### CODE REVIEW

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by lewurm** [comment]
@monojenkins backport 2019-06

**Comment by filipnavara** [comment]
I am a bit puzzled about the "Windows x64 FullAOT+LLVM" failure:

```
MyEqualException: expected = -100 vs. actual = -100
test_0_out_sbyte failed: got 1, expected 0
MyEqualException: expected = -100 vs. actual = -100
test_0_out_int16 failed: got 1, expected 0
```

Perhaps the values are correct but they type is not? Why does it not affect "Linux x64 FullAOT+LLVM" ?

**Comment by lewurm** [comment]
Thanks @filipnavara. I was clicking rebuild via mobile without looking at the logs. Will fix when I have a better internet connection/when I'm back from vacation.

**Comment by filipnavara** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by filipnavara** [comment]
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at System.IO.Compression.DeflateStream.Dispose (System.Boolean disposing) [0x00009] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mcs/class/System/System.IO.Compression/DeflateStream.cs:114 
  at System.IO.Compression.DeflateStream.Finalize () [0x00000] in /Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx-products-sdks-android/mcs/class/System/System.IO.Compression/DeflateStream.cs:107 
```
/cc @EgorBo

**Comment by EgorBo** [comment]
@filipnavara ouch

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by akoeplinger** [comment]
@monojenkins backport to 2019-08

**Pull request merged**
