### PR TITLE
Bump Windows requirement to Vista.

### PR DESCRIPTION
**Pull request by madewokherd**
According to @kumpera on https://github.com/mono/mono/pull/1714, we can drop support for Windows XP, so I'm checking whether that's true.

Winsock gained an inet_pton implementation in Vista that we have to start using (or the build fails due to conflicting declarations), so this really will break on XP.

### CODE REVIEW

**Comment by tritao** [comment]
Looks good, but I'm thinking we could also just query for the Vista features we need at runtime and still keep XP support for a while.

**Comment by madewokherd** [comment]
The features we need are condition variables, which are currently broken. We could implement them based on other threading primitives that are available on XP, if that's really preferable.

**Comment by alexrp** [comment]
I don't see why we should support a Windows version that Microsoft doesn't.

**Comment by tritao** [comment]
Yep, I changed my mind and I don't think its preferable emulating condition variables in XP after all. Unless someone which actually depends on Mono on XP speaks up I'm in for bumping the minimum supported version to Vista.

**Comment by kumpera** [comment]
Someone using XP might as well stay with mono 4.0 and not use more recent versions.

**Comment by kumpera** [comment]
build

**Comment by ddobrev** [comment]
The problem I see is that XP is still widely deployed and cutting it off means that it won't have an up-to-date version of .NET. That means that many applications or their new versions won't work on a vast number of machines.

**Comment by kumpera** [comment]
XP already doesn't have .net 4.5, so I fail to see the point into keeping mono working on it when it will be an extra maintenance burden on us.

**Comment by ddobrev** [comment]
That's my point, actually. Because .NET 4.5 does not work there, Mono not working there would mean no alternative.

**Comment by kumpera** [comment]
Unless there's an alternative to the Vista conditional var APIs, we won't pay the extra complexity.

**Comment by alexrp** [comment]
But why should we be enabling people to not upgrade from a ~15 year old OS?

**Comment by ddobrev** [comment]
@alexrp XP works on much weaker computers that Windows 7 does, and many people cannot or will not upgrade their hardware. That is, the world does not end with Western Europe and the US, we have Eastern Europe, Russia, India, China, etc.

**Comment by ddobrev** [comment]
@kumpera I am afraid I am not that well familiar with the Windows primitives to think of something myself but wouldn't something like http://stackoverflow.com/questions/6316286/condition-variable-alternatives-c-c-on-windows-xp work?

**Comment by alexrp** [comment]
@ddobrev I could say the same thing about Windows 2000. Or Windows 98. We must draw the line somewhere one way or the other.

**Comment by ddobrev** [comment]
@alexrp I couldn't agree more but in my opinion the line should be drawn before XP because it was Microsoft's first stable operating system and is therefore (still) widely used.

**Comment by akoeplinger** [comment]
I'm :+1: for dropping XP support, even though I recently had [some fun](https://twitter.com/akoeplinger/status/586997742846640130) playing with it :)

@ddobrev I know there's (unfortunately) still a good chunk of PCs stuck on XP, but do you have any numbers indicating someone is actually using Mono on those? I can't imagine a decent use case that doesn't involve hobbyists/hackers.

@madewokherd 577482e3361159e0c4c4b0232a07195ba91335dd should be reverted as well if this goes through.

**Comment by migueldeicaza** [comment]
Mono support in Windows is weak.   

Let us not make it weaker by spreading ourselves too thin by trying to support and find workarounds for an operating system that is no longer supported by Microsoft.

**Comment by madewokherd** [comment]
Oh come on, give me an excuse push my untested code that implements a threading construct I'd never heard of until last week to support an unsupported OS no one should be using. It'll be fun.

**Comment by kumpera** [comment]
I think it's time to move on. Let's do it.

**Comment by ggrnd0** [comment]
Is winxp will supported? 
If yes is win2003sp2 will supported too?

**Comment by alexrp** [comment]
No. We require Vista.

**Comment by yyjdelete** [comment]
Why there is still an fix for TimeZoneInfo.Local on xp, only release on 4.2+, but never release in 4.0.x channel, which break `DateTime.Now`.
9abf43e02aea7c59e8a979cf3c575f419d671753
48bf9b6d296fe477d0fa40aadaf6bb0055352af7
2e90ab901d15f4891a306be1c6d30d0d9efcfb7f

---
By the way, in my case, `StandardName` in 9abf43e02aea7c59e8a979cf3c575f419d671753  is not really works, for it seems be an display name and format as user's language.
What really works in an old comment shown in d7d456d93198d299a77af934b816be12bc38ab3a

**Pull request merged**
