### PR TITLE
[llvm] Avoid looking up intrinsics by name in most cases.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@lewurm could you please review

**Comment by vargaz** [comment]
Note that this only drops the JIT support for 3.6, aot support should still work.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins squash

**Comment by vargaz** [comment]
@monojenkins build

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@vargaz This broke the Windows FullAOT+LLVM nightly lane (https://jenkins.mono-project.com/job/zy2/:
```
"D:\j\workspace\zy2\label\w64\msvc\libmono-dynamic.vcxproj" (default target) (13) ->
(ClCompile target) -> 
  ..\mono\mini\mini-llvm.c(9970): error C2065: 'bzero': undeclared identifier [D:\j\workspace\zy2\label\w64\msvc\libmono-dynamic.vcxproj]
```

@lateralusX Should we run Windows FullAOT+LLVM on PRs?

**Comment by vargaz** [comment]
Will fix.

**Comment by vargaz** [comment]
https://github.com/mono/mono/pull/14164

**Comment by lateralusX** [comment]
@lambdageek We need to setup build/packaging step first so we don't need to build LLVM on every PR. Once that is working we could add a PR lane for Windows x64 Full AOT + LLVM as well.

**Pull request merged**
