### PR TITLE
[xbuild] Add Microsoft.NuGet.Build.Tasks.dll MSBuild task

### PR DESCRIPTION
**Pull request by akoeplinger**
This is required for interoperating with project.json-based NuGet package configuration files
(not to be confused with DNX or AspNet Core which use it as a project file too) from MSBuild/xbuild.

The task hooks into the build process, resolves assembly references from the nuget package cache
and injects them into the compilation process so the csproj doesn't need to be modified when
adding new references/packages.

It is the first step on our road to PCL5/NuGet3.

### CODE REVIEW

**Comment by kumpera** [comment]
Hey @marek-safar could you review this puppy and get it merged?

It would be nice to get this on C7 this week.

**Comment by akoeplinger** [comment]
I thought we target the pcl5 etc work for C8? There's no end-to-end scenario for this in C7 and I'd rather have everything working together.

**Comment by kumpera** [comment]
Yes, sorry, C8. Ignore my C7 comment.

**Comment by mhutch** [comment]
I've merged this into https://github.com/mono/mono/pull/3282

**Pull request closed without merging**
