### PR TITLE
Use `MultipleConnectAsync` from CoreFX.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins commit csproj

**Comment by baulig** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@monojenkins build Linux AArch64

**Comment by steveisok** [comment]
@baulig do you think there would be any value in running this on the designer bot?  I'm wondering if some kind of periodic stress test would be worth it?

**Comment by baulig** [comment]
> @baulig do you think there would be any value in running this on the designer bot? I'm wondering if some kind of periodic stress test would be worth it?

I actually thought about periodically running some stress tests myself, but we probably shouldn't use `nuget restore` for that and instead come up with a better solution.  Let's also have a look at CoreFX to see whether they might have any kind of stress tests for the socket code.

As for this particular PR, all I did was committing the work I did earlier on comparing the two implementations, to make it more obvious that they are.

**Comment by steveisok** [comment]
Yeah, I don't think nuget restore is ideal either.  Stress tests in general would be a good idea, so let's look at corefx and see 👍 .

**Pull request merged**
