### PR TITLE
Fsharp47

### PR DESCRIPTION
**Pull request by nosami**
Continuation of https://github.com/mono/mono/pull/17882

### CODE REVIEW

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
rebased on master

@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins rebase

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by nosami** [comment]
@monojenkins build pkg

**Comment by vshapenko** [comment]
any hope this PR will be merged?

**Comment by steveisok** [comment]
@nosami Do you recall what's left on this PR?

**Comment by nosami** [comment]
@steveisok The problem was that the F# repo removed support for the Mono installation script. I tried to reintroduce the packaging scripts in my fork at nosami/visualfsharp . As far as I recall, I was able to install F# 4.7 from source code using the SHA referenced in this PR.

I had many issues trying to get this build to go green but can't quite remember the reasons why unfortunately.

**Comment by KirillOsenkov** [comment]
@cartermp FYI

**Comment by cartermp** [comment]
Hmm, the mono makefile was removed only in the past few months from `dotnet/fsharp`, I don't know if it's accurate to say that was the issue. The mono-specific stuff we had when we had a "build the compilere against the mono runtime" CI leg was here:

makefile:
https://github.com/dotnet/fsharp/blob/c05f9745f6ebe9231a03c45facd118bd3c5899e3/Makefile

`mono/` folder:
https://github.com/dotnet/fsharp/tree/ae9cbd9009e63ff08ed19ef08fa3afef7867394a/mono

Building Mono itself with the F# compiler codebase was never done in any F# repo.

**Comment by akoeplinger** [comment]
Yeah I got the normal dotnet based build.sh to work by multi-targeting to net472, trying it out now (compiling a hello world F# with `mono fsc.exe` seems to work at least).

**Pull request closed without merging**
