### PR TITLE
[marshal] Rethrow in native-to-managed wrapper to keep exception stacktrace

### PR DESCRIPTION
**Pull request by luhenry**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=58782

### CODE REVIEW

**Comment by luhenry** [comment]
cc @rolfbjarne

**Comment by rolfbjarne** [comment]
LGTM. This might fix bug #[58780](https://bugzilla.xamarin.com/show_bug.cgi?id=58780) too.

**Comment by lewurm** [comment]
build interpreter

**Comment by lewurm** [comment]
build interpreter

**Comment by lewurm** [comment]
build interpreter

**Pull request merged**
