### PR TITLE
[Tailcall] Remove OP_JMP support. Require OP_TAILCALL.

### PR DESCRIPTION
**Pull request by jaykrell**
Per @vargaz and what I was considering myself.
This only hurts mips and sparc -- it breaks them.
Remove front end support for OP_JMP and conditionalality of OP_TAILCALL.

In place of `tailcall` (backend) and `supported_tailcall` (portable), now just `tailcall`.
Though perhaps that is too short and `supported_tailcall` would be preferred, perhaps.

We might be able to keep mips/sparc working by using OP_CALL instead.

### CODE REVIEW

**Comment by jaykrell** [comment]
mips/sparc C# will probably still work, but F# will hit assertion failures due to lack of switch/case op_tailcall.
A tiny restoration could keep that hobbling along -- retain advertisement of the op_tailcall and when not present, ignore tail. prefix. If anyone complains we can do that.

**Comment by vargaz** [comment]
Neither sparc nor mips is supported, and both are probably broken, this is just going to break them a bit more.

**Comment by vargaz** [comment]
MONO_ARCH_HAVE_OP_TAILCALL should also be removed.

**Comment by jaykrell** [comment]
And I thought I was thorough, oops, agreed.

**Comment by alexrp** [comment]
Pretty sure Debian still builds Mono on MIPS? cc @directhex

**Comment by jaykrell** [comment]
Do they include F#? C# will probably work.
The way to keep this working is pretty easy.
Provide mono_arch_tailcall_supported that always returns false.

**Comment by vargaz** [comment]
We don't build on mips which means there is a  90% change its broken.

**Comment by lewurm** [comment]
@monojenkins build Linux PPC64 little endian

**Comment by directhex** [comment]
Debian has removed SPARC.

MIPS packages are provided by Debian, but we don't CI them in Xamarin, which as @vargaz points out means it's likely perma-broken. Miguel indicated that there wasn't sufficient justification for MIPS work due to removal of MIPS from Android SDK, so I guess breaking MIPS is fine.

**Comment by jaykrell** [comment]
"Shrink or eliminate small local arrays." went to wrong branch.

**Comment by jaykrell** [comment]
OpenBSD and probably NetBSD and maybe FreeBSD support MIPS and SPARC. I would like to see them continue to work, but I don't have much "community time" to offer these days.

But I'd prefer a pure C++ + autoconf option, along the lines of interpreter/il2cpp/llvmonly/wasm, pushing the backend off to other projects..

**Comment by barracuda156** [comment]
@jaykrell For `ppc` this change is okay, right? Just to make sure.

**Pull request merged**
