### PR TITLE
[runtime] Expose blocking call registration to runtime when not using cooperative suspend [WIP/Don'tMerge]

### PR DESCRIPTION
**Pull request by alexanderkyte**
This is a fix for the case where a thread is waiting on a syscall with a timeout and sgen is thrashing the nursery.

The POSIX signal api dictates that system calls with timeouts which are interrupted by a signal return with
EINT, and must be restarted by us. The problem with this is that when sgen is under a lot of load due to rapidly
created garbage, we will signal the system call into starvation and the timeout will never happen.

Running the ExitedEvent test in mcs/System, followed by the Network ReadTimeout test in mcs/System exhibits this bug.

This fix moves, exposes, and uses the new unified suspend code to ensure that blocking recv and recvfrom syscalls are not
interrupted by sgen.

This fix requires that uniform_suspend is enabled.

### CODE REVIEW

**Comment by lewurm** [comment]
what's the status of this? should it be merged or is the PR ready to be closed?

**Comment by kumpera** [comment]
This might not be needed now that we're transitioning the runtime to coop.

**Comment by kumpera** [comment]
What do you think @ludovic-henry

**Comment by ludovic-henry** [comment]
I made an attempt to use the `blocking` state even in non-coop mode, but that would have meant switching to the unified suspend code only. And IIRC using unified suspend led to a bug when suspending with SGen that was specific to how unified suspend was implemented (I would have to try to repro it to remember exactly what).
Also using this blocking state means that we need to support safepoints (not necessarily generating them for managed code), as we need to poll and potentially suspend when getting out of the blocking section (switching to `blocking and suspended` state).
But in the end, I like the idea of this hybrid model, as it would make it easier to switch from one model to the other. It would also let us test more independently the complicated/unknown part of this coop mode:  the integration between this `blocking` state, the rest of the runtime (trampolines, etc.) and the outer world (iOS, Android, external libs via p/invoke, delegate to function pointers, etc.).

The code is available here: https://github.com/ludovic-henry/mono/commits/coop-unified-suspend

**Pull request closed without merging**
