### PR TITLE
[DON'T MERGE] test PR benchmarking feature

### PR DESCRIPTION
**Pull request by lewurm**

### CODE REVIEW

**Comment by lewurm** [comment]
builddeb

**Comment by lewurm** [comment]
`<botmode>`
Benchmark results: http://xamarin.github.io/benchmarker/front-end/pullrequest.html#id=67
buildbot logs: https://performancebot.mono-project.com/builders/debian-amd64_benchmarker_pullrequest_auto-sgen-conc-noturbo-binary/builds/19
`</botmode>`

**Comment by lewurm** [comment]
`<botmode>`
Benchmark results: http://xamarin.github.io/benchmarker/front-end/pullrequest.html#id=69
buildbot logs: https://performancebot.mono-project.com/builders/debian-amd64_benchmarker_pullrequest_auto-sgen-conc-noturbo-binary/builds/20
`</botmode>`

**Comment by lewurm** [comment]
`<botmode>`
Benchmark results: http://xamarin.github.io/benchmarker/front-end/pullrequest.html#id=70
buildbot logs: https://performancebot.mono-project.com/builders/debian-amd64_benchmarker_pullrequest_auto-sgen-noturbo-binary/builds/19
`</botmode>`

**Comment by lewurm** [comment]
`<botmode>`
Benchmark results: http://xamarin.github.io/benchmarker/front-end/pullrequest.html#id=65
buildbot logs: https://performancebot.mono-project.com/builders/debian-armhf_utilite-desktop_pullrequest_auto-sgen/builds/11
`</botmode>`

**Comment by akoeplinger** [comment]
Nice :) Though looks like we need to shorten the descriptions, they are way too long to fit into the status checks panel.

**Comment by lewurm** [comment]
builddeb

**Comment by lewurm** [comment]
`<botmode>`
Benchmark results: http://xamarin.github.io/benchmarker/front-end/pullrequest.html#id=74
buildbot logs: https://performancebot.mono-project.com/builders/debian-amd64_benchmarker_pullrequest_auto-sgen-conc-noturbo-binary/builds/21
`</botmode>`

**Pull request closed without merging**
