### PR TITLE
[netcore] Fix build.sh

### PR DESCRIPTION
**Pull request by CoffeeFlux**
It appears to have accidentally been changed in #15215, and the script no longer works correctly as a result, so revert

### CODE REVIEW

**Comment by EgorBo** [comment]
@CoffeeFlux it's fixed in https://github.com/mono/mono/pull/15373 🙂

**Comment by CoffeeFlux** [comment]
I'd personally rather have this fix be explicit and merged quickly than squashed in with an only tangentially related PR - mixing in unrelated build system changes is how this happened in the first place. Maybe merge this and then make the changes in a separate PR? I have questions/feedback related to them that I'd rather not hold your xunit PR up for, notably:
1. Is there a reason we're moving the `.configured` file up a level? If it's not being used outside of netcore scripts it seems most appropriate to leave it there.
2. If we are moving it up a level, the `.gitignore` and `/netcore/Makefile` need to be updated accordingly.

**Comment by EgorBo** [comment]
If you want to merge this you need to fix the gitignore, I have no preferences on where it should be (initially it was inside netcore but was moved to the root by Marek's clean up PR afair).

**Comment by CoffeeFlux** [comment]
If you mean https://github.com/mono/mono/commit/9010d2f290d28dc97ac276e0c0d32a2932b7550f#diff-38868e38d9f6469767765e84ab10b1e4, it doesn't look like the `.configured` file got moved. I initially noticed this issue because the gitignore doesn't currently work. I thiiiink I can just merge this.

**Comment by EgorBo** [comment]
@CoffeeFlux oh, indeed, but please remove `make -j` from there - it builds runtime and mscorlib separately

**Comment by CoffeeFlux** [comment]
Ooh I see. I've imitated what you did in #15373 then but left the .configured file in the netcore directory. If you're good with this @EgorBo then I'll merge.

**Comment by CoffeeFlux** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@monojenkins build Linux AArch64 FullAOT

**Pull request merged**
