### PR TITLE
[FileSystemWatcher] Fix wrong behaviour when move multiple files out …

### PR DESCRIPTION
**Pull request by alexischr**
…of watched folder on mac (#41963)

Backport of https://github.com/dotnet/corefx/pull/41963

Fixes https://github.com/mono/mono/issues/16778

### CODE REVIEW

**Comment by lambdageek** [comment]
Build failures on OSX are relevant:

```
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/external/corefx/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs(391,102): error CS1503: Argument 1: cannot convert from 'Interop.EventStream.FSEventStreamEventFlags[]' to 'void*'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/external/corefx/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs(391,167): error CS1503: Argument 1: cannot convert from 'ulong[]' to 'void*'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/external/corefx/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs(397,141): error CS1503: Argument 1: cannot convert from 'Interop.EventStream.FSEventStreamEventFlags[]' to 'void*'
/Users/builder/jenkins/workspace/test-mono-pull-request-amd64-osx/external/corefx/src/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs(397,206): error CS1503: Argument 1: cannot convert from 'ulong[]' to 'void*'
```

**Comment by lambdageek** [comment]
The FileSystemEventCallback in upstream CoreFX is
```
            private unsafe void FileSystemEventCallback(
                FSEventStreamRef streamRef,
                IntPtr clientCallBackInfo,
                size_t numEvents,
                byte** eventPaths,
                FSEventStreamEventFlags* eventFlags,
                FSEventStreamEventId* eventIds)
```

but in mono eventFlags is an array, not a ptr

**Comment by marek-safar** [comment]
What is needed here?

**Comment by alexischr** [comment]
@marek-safar A proper review of https://github.com/mono/corefx/pull/373 ,it was a nontrivial backport

**Comment by alexischr** [comment]
Closing, the change was included by another PR bumping mono/corefx

**Pull request closed without merging**
