### PR TITLE
[threads] Ensure we remove the thread only once

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by luhenry** [comment]
Build

**Comment by lateralusX** [comment]
Will investigate Windows x64 failure.

**Comment by lateralusX** [comment]
Could not reproduce locally with the failing commands. There is at least an error case that could be hit when starting a new thread and attaching (mono_thread_attach_internal) while setting the runtime in shutdown mode (theirs is also a second one related to domain unload). Then the attach call will fail, but start_wrapper will still call detach on the thread. Then the thread won't be in the threads list and it seems like the original code in mono_thread_detach_internal does the cleanup matching what's been done in the failing call to mono_thread_attach_internal at that point. Looking at that error case we either need to either handle the error cleanup in mono_thread_attach_internal (and not call mono_thread_detach_internal) or keep the code as is.

One of the driver of this PR was https://github.com/mono/mono/pull/5964, but I will try a different alternative in that one, just reusing the existing joinable_threads_mutex mutex lock for handling the list of pending joinable threads.

**Comment by luhenry** [comment]
I can reproduce on macOS 64bits with the following code:

```

using System;
using System.Threading;

class Driver
{
	public static void Main ()
	{
		Thread t1 = new Thread(() => {
			for (int i = 0; i < 10; ++i) {
				Thread t2 = new Thread(() => {
					while (true) {
						Thread t3 = new Thread(() => {});
						t3.IsBackground = true;
						t3.Start();
						t3.Join();
					}
				});

				t2.IsBackground = true;
				t2.Start ();
			}
		});

		t1.IsBackground = true;
		t1.Start ();

		Thread.Sleep (100);
	}
}
```

**Comment by lateralusX** [comment]
Great! Looks like your repro hits the error case described above. Moving the cleanup in error cases should fix the issue.

**Comment by lateralusX** [comment]
@luhenry Error in makefile.am causing errors. Tried to push commit to your PR branch but didn't have access:

From 12af21965331ffe9a5fc521940753425020c35e1 Mon Sep 17 00:00:00 2001
From: lateralusX <lateralusx.github@gmail.com>
Date: Thu, 14 Dec 2017 08:54:21 +0100
Subject: [PATCH] Fix make file error.

---
 mono/tests/Makefile.am | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/mono/tests/Makefile.am b/mono/tests/Makefile.am
index 27d7d65d00f..a82a6a4faca 100755
--- a/mono/tests/Makefile.am
+++ b/mono/tests/Makefile.am
@@ -530,7 +530,7 @@ TESTS_CS_SRC=               \
        bug-59281.cs    \
        init_array_with_lazy_type.cs \
        weak-fields.cs  \
-       threads-init.s
+       threads-init.cs

 if AMD64
 TESTS_CS_SRC += async-exc-compilation.cs finally_guard.cs finally_block_ending_in_dead_bb.cs
--
2.14.1.windows.1

**Comment by luhenry** [comment]
@monojenkins build

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT

**Comment by lateralusX** [comment]
Windows i386 failures are unrelated.

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv5 soft float

**Comment by luhenry** [comment]
@monojenkins build Windows i386

**Pull request merged**
