### PR TITLE
[jit] Move a few DISABLE_JIT stubs to arch-stubs.c.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by jaykrell** [comment]
@vargaz 

https://jenkins.mono-project.com/job/test-mono-pull-request-wasm/5557/parsed_console/log.html

```
error: Linking globals named 'mono_arch_get_call_filter': symbol multiply defined!
WARNING:root:Note: Input file "@/tmp/tmpeNowHG.response" did not exist.
ERROR:root:Failed to run llvm optimizations: 
Makefile:82: recipe for target 'debug/.stamp-build' failed
make: *** [debug/.stamp-build] Error 1
make: Leaving directory '/mnt/jenkins/workspace/test-mono-pull-request-wasm/sdks/wasm'
```

**Comment by lewurm** [comment]
needs a rebase with master

**Comment by luhenry** [comment]
@monojenkins squash

**Comment by luhenry** [comment]
@monojenkins build

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
```
hudson.plugins.git.GitException: Command "git submodule update --init --recursive external/corert" returned status code 1:
12:29:33 stdout: 
12:29:33 stderr: Cloning into 'D:/j/workspace/x/external/corert'...
12:29:33 Fetched in submodule path 'external/corert', but it did not contain 1117c4aa36d035ca64fe37f2f3dd19155f33ad98. Direct fetching of that commit failed.
12:29:33 
```
hmmm

**Comment by lewurm** [comment]
@monojenkins build failed

**Pull request merged**
