### PR TITLE
Fix build warning in full AOT build.

### PR DESCRIPTION
**Pull request by lateralusX**

### CODE REVIEW

**Comment by lateralusX** [comment]
Looks like this introduce an interesting issue in sgen, that I also identified in local build. When removing the cache_add_event the abstract class lost is member, and then we start to get this assert in sgen:

#0  0x00007f68a1972b5a in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00005611749dcf7a in dump_native_stacktrace (ctx=ctx@entry=0x7fffcf7964c0, signal=0x561174bd43d8 "SIGABRT") at mini-posix.c:1115
#2  0x00005611749dd071 in mono_dump_native_crash_info (signal=signal@entry=0x561174bd43d8 "SIGABRT", ctx=ctx@entry=0x7fffcf7964c0, info=info@entry=0x7fffcf7965f0) at mini-posix.c:1157
#3  0x000056117496dfb9 in mono_handle_native_crash (signal=0x561174bd43d8 "SIGABRT", ctx=0x7fffcf7964c0, info=0x7fffcf7965f0) at mini-exceptions.c:3336
#4  <signal handler called>
#5  0x00007f68a13defff in raise () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f68a13e042a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000561174baf697 in monoeg_assert_abort () at goutput.c:57
#8  0x0000561174b96339 in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=0x561176900480 "* Assertion at sgen-alloc.c:379, condition `*p == NULL' not met\n") at mono-log-common.c:136
#9  0x0000561174baf5be in monoeg_g_logstr (msg=<optimized out>, log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:134
#10 monoeg_g_logv_nofree (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x561174bb8730 "* Assertion at %s:%d, condition `%s' not met\n", args=args@entry=0x7fffcf796d38) at goutput.c:149
#11 0x0000561174bafa90 in monoeg_g_logv_nofree (args=0x7fffcf796d38, format=0x561174bb8730 "* Assertion at %s:%d, condition `%s' not met\n", log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:142
#12 monoeg_assertion_message (format=format@entry=0x561174bb8730 "* Assertion at %s:%d, condition `%s' not met\n") at goutput.c:184
#13 0x0000561174b54bd1 in sgen_try_alloc_obj_nolock (vtable=vtable@entry=0x5611768ffa60, size=<optimized out>, size@entry=30) at sgen-alloc.c:379
#14 0x0000561174b39d3b in mono_gc_alloc_string (vtable=0x5611768ffa60, size=size@entry=30, len=len@entry=4) at sgen-mono.c:1394
#15 0x0000561174b32760 in mono_gc_alloc_handle_string (vtable=<optimized out>, size=size@entry=30, len=len@entry=4) at gc.c:1386
#16 0x0000561174adb425 in mono_string_new_size_handle (domain=domain@entry=0x5611768fde40, len=len@entry=4, error=error@entry=0x7fffcf797060) at object.c:6673
#17 0x0000561174adb4d0 in mono_string_new_size_checked (domain=domain@entry=0x5611768fde40, length=length@entry=4, error=error@entry=0x7fffcf797060) at object.c:6685
#18 0x0000561174adb599 in mono_string_new_utf16_checked (domain=domain@entry=0x5611768fde40, text=text@entry=0x5611769004f0, len=4, error=error@entry=0x7fffcf797060) at object.c:6566
#19 0x0000561174adbb6a in mono_string_new_checked (domain=domain@entry=0x5611768fde40, text=<optimized out>, error=error@entry=0x7fffcf797060) at object.c:6808
#20 0x0000561174b0de89 in mono_string_new_handle (domain=domain@entry=0x5611768fde40, data=<optimized out>, error=error@entry=0x7fffcf797060) at handle.c:387
#21 0x0000561174a7ec9a in ves_icall_RuntimeEventInfo_get_event_info (ref_event=..., ref_event@entry=..., info=info@entry=0x7fffcf797148, error=error@entry=0x7fffcf797060) at icall.c:2455
#22 0x0000561174a913b6 in ves_icall_RuntimeEventInfo_get_event_info_raw (a0=0x7fffcf7970e8, a1=0x7fffcf797148, error=0x7fffcf797060) at ../../mono/metadata/icall-def.h:708
#23 0x00007f689e44e333 in wrapper_managed_to_native_System_Reflection_RuntimeEventInfo_get_event_info_System_Reflection_RuntimeEventInfo_System_Reflection_MonoEventInfo_ () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#24 0x00007f689e44e406 in System_Reflection_RuntimeEventInfo_GetEventInfo_System_Reflection_RuntimeEventInfo () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#25 0x00007f689e44e6f0 in System_Reflection_RuntimeEventInfo_GetBindingFlags () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#26 0x00007f689e44e4d5 in System_Reflection_RuntimeEventInfo_get_BindingFlags () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#27 0x00007f689e23a30c in System_RuntimeType_GetEvent_string_System_Reflection_BindingFlags () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#28 0x00007f689e204efc in System_Type_GetEvent_string () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#29 0x00007f689df114dc in Test_Main () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mono/tests/event-get.2.exe.so
#30 0x00007f689e9b6712 in wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#31 0x00005611748f3351 in mono_jit_runtime_invoke (method=<optimized out>, obj=<optimized out>, params=<optimized out>, exc=<optimized out>, error=<optimized out>) at mini-runtime.c:3191
#32 0x0000561174ad37b0 in do_runtime_invoke (method=0x56117693c1c8, obj=<optimized out>, params=<optimized out>, exc=<optimized out>, error=0x7fffcf797640) at object.c:3010
#33 0x0000561174ad59ad in do_exec_main_checked (method=0x56117693c1c8, args=<optimized out>, error=0x7fffcf797640) at object.c:5104
#34 0x00005611749398aa in mono_jit_exec_internal (argv=0x7fffcf797a90, argc=1, assembly=0x0, domain=0x5611768fde40) at driver.c:1313
#35 mono_jit_exec (domain=domain@entry=0x5611768fde40, assembly=assembly@entry=0x56117693ced0, argc=argc@entry=1, argv=argv@entry=0x7fffcf797a90) at driver.c:1258
#36 0x000056117493b02b in main_thread_handler (user_data=<synthetic pointer>) at driver.c:1390
#37 mono_main (argc=<optimized out>, argv=<optimized out>) at driver.c:2606
#38 0x00005611748ee2a7 in mono_main_with_options (argv=<optimized out>, argc=<optimized out>) at main.c:50
#39 main (argc=<optimized out>, argv=<optimized out>) at main.c:408

So looks like the member might still be needed in full AOT builds.

**Comment by vargaz** [comment]
Those classes have a layout which the runtime depend on.

**Comment by lateralusX** [comment]
Yes noticed that, will convert to a pragma warning disable/restore instead.

**Comment by lateralusX** [comment]
@monojenkins rebuild failed

**Comment by lateralusX** [comment]
@vargaz, approve/merge?

**Pull request merged**
