### PR TITLE
Eglib integrate

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by alexrp** [comment]
What do you think about moving `eglib` into `mono/eglib` and giving it a similar directory structure to the other directories there?

**Comment by joncham** [comment]
Is the long term plan to keep a glib style API, or just migrate everything to a mono specific OS layer ala `utils`?

**Comment by vargaz** [comment]
The plan is to move it to mono/eglib if this works out. We don't have plans to change the api right now, although removing some stuff like file io would be helpful.

**Comment by kumpera** [comment]
LGTM
🎉 🎉

**Comment by vargaz** [comment]
build

**Pull request merged**
