### PR TITLE
[icalls] Change get_bundled_machine_config to ICALL_EXPORT so maccore can link it.

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Comment by kumpera** [comment]
must be backported to C9

**Comment by lambdageek** [comment]
That's not the icall function anymore on master.  the icall is `ves_icall_System_Configuration_DefaultConfig_get_bundled_machine_config`

**Comment by lambdageek** [comment]
On C9, it's still called get_bundled_machine_config, however.

Also it uses handles, is maccore able to deal with that?

**Comment by kumpera** [comment]
@lambdageek 
Fixed icall function naming.
Moved the ICALL_EXPORT to the right places.
WRT C9, maccore should be able to deal with handles no differently that desktop.

ICALL_EXPORT just give it a change to link those out when needed.

**Pull request merged**
