### PR TITLE
Bump version to 6.9

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Yay, mcs is throwing a fit again. @marek-safar should we modify linker to get rid of the pattern matching?

```
../../../external/linker/src/linker/Linker.Steps/SweepStep.cs(402,25): error CS0589: Internal compiler error during parsingSystem.NotImplementedException: type pattern matching
  at Mono.CSharp.CSharpParser.case_963 () [0x0002a] in <93005d576ca243f6aba3c4dc75f656d0>:0 
  at Mono.CSharp.CSharpParser.yyparse (Mono.CSharp.yyParser.yyInput yyLex) [0x0414b] in <93005d576ca243f6aba3c4dc75f656d0>:0 
  at Mono.CSharp.CSharpParser.parse () [0x00028] in <93005d576ca243f6aba3c4dc75f656d0>:0 
../../../external/linker/src/linker/Linker.Steps/MarkStep.cs(1146,38): error CS1525: Unexpected symbol `when'
../../../external/linker/src/linker/Linker.Steps/MarkStep.cs(1149,36): error CS1525: Unexpected symbol `when'
../../../external/linker/src/linker/Linker.Steps/MarkStep.cs(1152,38): error CS1525: Unexpected symbol `when'
../../../external/linker/src/linker/Linker.Steps/MarkStep.cs(1155,30): error CS1525: Unexpected symbol `when'
../../../external/linker/src/linker/Linker.Steps/MarkStep.cs(1158,34): error CS1525: Unexpected symbol `when'
../../../external/linker/src/linker/Linker.Steps/MarkStep.cs(1197,17): error CS0589: Internal compiler error during parsingSystem.NotImplementedException: type pattern matching
  at Mono.CSharp.CSharpParser.case_963 () [0x0002a] in <93005d576ca243f6aba3c4dc75f656d0>:0 
  at Mono.CSharp.CSharpParser.yyparse (Mono.CSharp.yyParser.yyInput yyLex) [0x0414b] in <93005d576ca243f6aba3c4dc75f656d0>:0 
  at Mono.CSharp.CSharpParser.parse () [0x00028] in <93005d576ca243f6aba3c4dc75f656d0>:0 
```

**Comment by directhex** [comment]
@monojenkins commit csproj

**Comment by directhex** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by directhex** [comment]
@monojenkins build failed

**Pull request merged**
