### PR TITLE
[runtime] Avoid building a separate static library, use the shared ob…

### PR DESCRIPTION
**Pull request by vargaz**
…ject files for the static library as well. (#5233)

### CODE REVIEW

**Comment by migueldeicaza** [comment]
When we do this, do we not generate slower code for the runtime?

**Comment by vargaz** [comment]
PIC code is only slightly bigger/slower. Also, some platforms like IOS already require pic code even in static apps.

**Comment by migueldeicaza** [comment]
Before we merge, could we determine what the impact would be for something like Visual Studio for Mac?

**Comment by vargaz** [comment]
This causes test failures in the mini tests on arm64.

**Comment by jaykrell** [comment]
I don't believe Mac (or Windows) will be affected at all, but Linux/Android will be slightly -- they'll be more Mac-like. :) I believe Mac/iOS default to PIC. Though arm32/x86 do appear to have "PIC-less" -static flag that affects data references but not function references -- doesn't do anything for amd64/arm64. Actually probably x86 functions are affected if you target old OS. They made the dynamic link stubs linker generated in later versions or somesuch.

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by luhenry** [comment]
@monojenkins build pkg

**Comment by vargaz** [comment]
@monojenkins build

**Comment by vargaz** [comment]
So does this look good ?

**Comment by alexrp** [comment]
LGTM assuming failures aren't related (can't load those Jenkins links for some reason).

**Comment by lewurm** [comment]
@monojenkins build pkg

**Comment by lewurm** [comment]
needs another rebase due to https://github.com/mono/mono/pull/6671 and will also conflict with https://github.com/mono/mono/pull/6667

**Comment by lewurm** [comment]
@monojenkins rebase

**Pull request merged**
