### PR TITLE
[msbuild] Empty commit to trigger wrench build and pick up msbuild ch…

### PR DESCRIPTION
**Pull request by radical**
…anges

Specifically to get
https://github.com/mono/msbuild/commit/985f169ccd08008a52f2550373eebaafa90fc48f

[mono] Update bundled sdks: .NET Core SDK 1.1.0 Preview 1 (#17)
.. to match what is bundled with VS 15.3

Ref: dotnet/announcements#19

### CODE REVIEW

**Comment by luhenry** [comment]
2017-04 is closed for commits. What are these changes for?

**Comment by luhenry** [comment]
Also, how does this commit pick up msbuild changes?

**Comment by radical** [comment]
It would pick up because of this bump in bockbuild - https://github.com/xamarin/bockbuild/pull/94/commits/c7b3331940d3e3fb52e87e0b6ec5cb4afa87a0c6 .

**Comment by radical** [comment]
@akoeplinger @mrward ^

**Comment by radical** [comment]
@akoeplinger opened a request with QA for this. They will decide whether or not to merge, I guess!

**Comment by radical** [comment]
I will apply the update to 2017-06 instead since it is too late for QA to accept this.

**Pull request closed without merging**
