### PR TITLE
Use explicit arithmetic checks in the amd64 watchOS simulator.

### PR DESCRIPTION
**Pull request by imhameed**
Fixes https://github.com/mono/mono/issues/20632.

### CODE REVIEW

**Comment by dalexsoto** [comment]
Thanks a lot @imhameed! Can we get this back ported to 2020-02?

**Comment by imhameed** [comment]
Yeah; I'll do that once this makes it through. (I haven't actually reproduced the failure or verified that the fix actually works yet, so I'll need a little time to roll my iDevice setup forward.)

**Comment by dalexsoto** [comment]
Gotcha, thanks! Let me know if I can help somehow

**Comment by SamMonoRT** [comment]
Any idea why we didn't catch this earlier ?  @dalexsoto

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@SamMonoRT for the 32-bit simulator it didn't happen because `MONO_ARCH_NEED_DIV_CHECK` is defined unconditionally https://github.com/mono/mono/blob/0e3d75d6d6d6b6c404a6d02f22137262f0107d6b/mono/mini/mini-x86.h#L194

**Review by vargaz — APPROVED** [review]

**Comment by dalexsoto** [comment]
@SamMonoRT Because this is new for WatchOS 7.0+ and I did not catch it here https://github.com/mono/mono/pull/20553 because this was merged in xamarin-macios in a way that the bcl test triggered for a previous commit that did not contain this fix so we caught it on a subsequent commit

**Comment by imhameed** [comment]
@monojenkins build failed

**Comment by dalexsoto** [comment]
@imhameed any chance we can have this change pushed into a no shipping branch inside mono repo so the CI generates the binaries? this way I can help to test the change

**Comment by imhameed** [comment]
@monojenkins backport to 2020-02

**Pull request merged**
