### PR TITLE
[Process] Fix Process.Start handle leak

### PR DESCRIPTION
**Pull request by ludovic-henry**
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=40643

### CODE REVIEW

**Comment by ethanhann-ensembleads** [comment]
@dnfclas @ludovic-henry Which release contains this fix? It doesn't appear to be in 4.4.0.182 which is listed as the latest stable version on the Mono download page.

**Comment by markfinal** [comment]
Also interested to know which release this fix will be in, so I can test.

I have been seeing the "Too many open files" issue on Linux (Ubuntu 14) with mono 4.4.0.

**Comment by akoeplinger** [comment]
It will be in the next release which is Mono 4.6, you can try the `mono-4.5.1-branch` (it'll turn into `mono-4.6.0-branch` when the release is ready).

I don't know if it's easy to backport this fix to a 4.4 service release but given where we are in the release cycle it'd likely need to be a high impact issue to qualify.

**Comment by markfinal** [comment]
@akoeplinger I'm more than happy to move to 4.6 when it is available. I have no specific need to stay on Mono 4.4, I'd just need to advise anyone using my software to upgrade too.
Thanks for the information!

**Pull request merged**
