### PR TITLE
MARTINS PLAYGROUND

### PR DESCRIPTION
**Pull request by baulig**
@monojenkins skip

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins build OS X x64 iOS SDK

**Comment by baulig** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Android SDK

**Comment by akoeplinger** [comment]
@monojenkins build OS X x64 Android SDK

**Pull request closed without merging**
