### PR TITLE
Fix/mitigate 5-60 second hang at shutdown (mono/tests/thread6.exe).

### LINKED ISSUE #9000: untime-interp/thread6.exe test is flaky
## Steps to Reproduce

1.  Submit a PR.

### Current Behavior

Tests fail.
For example:

Flaky test.

MonoTests.runtime-interp.thread6.exe_timedout

https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter-armhf/5285/testReport/junit/MonoTests/runtime-interp/thread6_exe_timedout/

                                                MESSAGE:
                                                Thread 1 started
Count: 0
cought exception level 3 
cought exception level 2 STATETEST
System.Threading.ThreadAbortException: Thread was being aborted.
  at Tests.ThreadStart1 () <0xf5307510 + 0x000aa> in <b5e56f684da84c808720a8b25d32b5e6>:0 
cought exception level 1 
System.Threading.ThreadAbortException: Thread was being aborted.
  at Tests.ThreadStart1 () <0xf5307510 + 0x00118> in <b5e56f684da84c808720a8b25d32b5e6>:0 
end
Working thread abort
Retained thread abort exception
[New LWP 2428]
[New LWP 2434]
[New LWP 2813]
[New LWP 2847]
[New LWP 5130]
[New LWP 8997]
[N

### Expected Behavior

Tests pass.

## On which platforms did you notice this

[x] macOS
[x] Linux
[x] Windows

### PR DESCRIPTION
**Pull request by jaykrell**
Don't wait 5-60 seconds for work in threadpool on aborted threads.
This fixes #9000 and likely #7167.

Aborting already aborted threads is skipped, but interrupts on aborted threads are not.
This regressed with change 5f5c5e9 [threadpool] Replace parked_threads condition variable by a semaphore (#6222)

The skipping of syscall abort in aborted threads is circa here:
```
request_thread_abort:
	if (thread->state & (ThreadState_AbortRequested | ThreadState_Stopped))
	{
		UNLOCK_THREAD (thread);
		return FALSE;
	}
```

Otherwise there is a wait for a random duration between 5 and 60 seconds in mono/tests/thread6.cs,
which aborts a threadpool worker thread -- probably an inappropriate thing to do,
threadpool threads being a shared resource, however with the right amount of synchronization,
one can probably be sure to only abort one's own work, and the threadpool will survive by
spinning up additional threads, or in this case, shutting down in the expected rapid way.

Possibly there should be a notion of canceling a threadpool work item or task, instead
of the entire thread. Even if it is safe, it is defeating the efficiency of a threadpool.

There might be another fix involving doing more of the abort processing of aborted threads.

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
4 instead of expected 3 failures on FullAOT+LLVM, let's see if flake or not.
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by jaykrell** [comment]
And then might have regressed  MonoTests.runtime.appdomain-unload.exe_timedout -- two failures of that. A compromise might be to shorten the wait if the thread is aborted.

**Comment by jaykrell** [comment]
Or to interrupt the syscall as suggested. That'd handle other kinds of waits w/o having to check for abort everywhere and reason about it.

**Comment by jaykrell** [comment]
Or check MONO_THREAD_FLAG_APPDOMAIN_ABORT.

**Comment by jaykrell** [comment]
Notice that threadpool threads are treated as a special case here. They are "background" threads. So analogs to arbitrary syscalls are not clear.

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by jaykrell** [comment]
`mono_thread_interruption_checkpoint_bool`?

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 Interpreter

**Comment by jaykrell** [comment]
Locally, without a fix, JIT and interp hang the same.
Locally, with a fix, JIT and interp are both fixed.
In CI the fix still leaves interp failing.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
superseded by https://github.com/mono/mono/pull/9163

**Pull request closed without merging**
