### PR TITLE
extern "C" reduction.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 Bitcode

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 Coop Suspend

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
The legacy profiler functions have to be `extern "C"` - they're still used by some Xamarin products, and possibly by unity.

**Comment by jaykrell** [comment]
This does not change that. They are also exported and that is externC. Mono-state.h is not public as far as I know.

**Comment by jaykrell** [comment]
`#define MONO_DEPRECATED MONO_API MONO_RT_EXTERNAL_ONLY _MONO_DEPRECATED`

**Comment by jaykrell** [comment]
GitHub won't let reopen.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Pull request merged**
