### PR TITLE
[debugger] Fix debugging on Mac and iOS

### PR DESCRIPTION
**Pull request by thaystg**
Backport https://github.com/dotnet/runtime/pull/71436

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by thaystg** [comment]
@akoeplinger , can I merge this one, I'm not sure if the CI errors are blocker.

**Review by rolfbjarne — APPROVED** [review]

**Comment by rolfbjarne** [comment]
We'll need this in the 2020-02 branch.

**Comment by akoeplinger** [comment]
Test failures are unrelated.

**Pull request merged**
