### PR TITLE
[bcl] Avoid ObjectDisposedException in EndPointListener.

### PR DESCRIPTION
**Pull request by alexrp**
This fixes a regression introduced in 123aaa5db07fe464d12ea178ecc3f27990cc1a72. We would sometimes see an ObjectDisposedException when calling AcceptAsync () because that patch removed the try-catch around it.

### CODE REVIEW

**Comment by alexrp** [comment]
@esdrubal @ludovic-henry @gregoryyoung review?

**Comment by akoeplinger** [comment]
I can confirm that this fixes the crash in the iOS tests as well.

**Comment by gregoryyoung** [comment]
Seems reasonable.

**Comment by ludovic-henry** [comment]
LGTM

**Comment by alexrp** [comment]
@monojenkins merge

**Comment by alexrp** [comment]
amd64 failure is unrelated, merging.

**Comment by akoeplinger** [comment]
@alexrp should we put this back into 4.5.1 now?

**Comment by alexrp** [comment]
Yep, should be safe to do so.

**Pull request merged**
