### PR TITLE
[mscorlib] System.IO.Path, add support for systems that use volume paths (under NDA)

### PR DESCRIPTION
**Pull request by migueldeicaza**
Workbooks test:

```
(IsVolumePrefix (""), IsVolumePrefix ("fo"), IsVolumePrefix ("a"), IsVolumePrefix ("a:"), IsVolumePrefix ("delta?"))
=> (false, false, false, false, false)

(IsVolumePrefix ("a:/"), IsVolumePrefix ("a:/aasd"), IsVolumePrefix ("mount:/etc"))
=>
(true, true, true)
```

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Good catch, will check on device.

**Comment by migueldeicaza** [comment]
Confirmed, this is how this OS behaves.

**Comment by jspohr-ubi** [comment]
I think there's another issue with these kinds of paths in Path.GetDirectoryName().

- `Path.GetDirectoryName("foo:/bar")` returns `"foo:"` (but should return `"foo:/"`)
- `Path.GetDirectoryName("foo:/")` returns `"foo:"` (but should probably return `null` (?))

It should never return `"foo:"`, because without the trailing slash that's not a valid path.

**Comment by lewing** [comment]
@migueldeicaza is this something we still want/need?

**Comment by lewing** [comment]
Closing due to conflicts and lack of response.  Please reopen if this is premature.

**Pull request closed without merging**
