### PR TITLE
[CI] Add a lane for Clang's ThreadSanitizer

### PR DESCRIPTION
**Pull request by cherusker**
The goal of this PR is to provide an extra lane for running the ThreadSanitizer incl. a blacklist. However, as I cannot test this offline, I need a PR to play around with Jenkins.

### CODE REVIEW

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by cherusker** [comment]
build clang sanitizer

**Comment by akoeplinger** [comment]
@monojenkins build clang sanitizer

**Comment by cherusker** [comment]
@monojenkins build OS X i386

**Pull request merged**
