### PR TITLE
Enable tests System.ComponentModel.Composition.*

### LINKED ISSUE #15353: [netcore] Make System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform Pass
The test currently fails with:

```
System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(inputType: Reader, readerType: XmlValidatingReader, transformType: Reader, docType: XPathDocument) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Xml.Tests.XsltApiTestCaseBase.VerifyResult(String expectedValue)
           at System.Xml.Tests.CXmlResolverTest.<>c__DisplayClass5_0.<TC_AbsolutePath_Transform>b__0()
           at System.Xml.Tests.XsltApiTestCaseBase.TestUsingTemporaryCopyOfResolverDocument(Action testAction)
           at System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform(InputType inputType, ReaderType readerType, TransformType transformType, DocType docType)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Output:
        Loading style sheet as XmlValidatingReader TestFiles/TestData/XsltApi/xmlResolver_document_function_absolute_uri.xsl
        Loading XML TestFiles/TestData/XsltApi/fruits.xml
        Executing transform
        Expected : <?xml version="1.0" encoding="utf-8"?><result>123</result>
        Actual : <?xml version="1.0" encoding="utf-8"?><result></result>
```

Determine why and make the test pass.

### LINKED ISSUE #16417: [netcore] Could not load type _proxy_System.ComponentModel.Composition.*
A lot of tests under `System.ComponentModel.Composition` fail time to time (flaky) with:
```
System.NotSupportedException : Interface 
'System.ComponentModel.Composition.ScopeExportFactoryTests+IFooMetadata' is not a valid 
MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain 
members that are not properties.\n---- System.TypeLoadException : Could not load type 
'_proxy_System.ComponentModel.Composition.ScopeExportFactoryTests+IFooMetadata_c9015c58-24c6-46dc-969a-d1740364c90d' from assembly ''.

at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IMetadataView](IDictionary`2 metadata)
   at System.ComponentModel.Composition.AttributedModelServices.GetMetadataView[IMetadataView](IDictionary`2 metadata)
   at System.ComponentModel.Composition.ExportServices.CreateStronglyTypedLazyOfTM[OptionalFooIsInt,IMetadataView](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore[OptionalFooIsInt,IMetadataView](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports[OptionalFooIsInt,IMetadataView](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports[OptionalFooIsInt,IMetadataView]()
   at System.ComponentModel.Composition.MetadataTests.TestOptionalMetadataValueTypeMismatch()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
----- Inner Stack Trace -----
   at System.RuntimeType.GetMethodsByName(String name, BindingFlags bindingAttr, MemberListType listType, RuntimeType reflectedType)
   at System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Int32 genericParamCount, Boolean allowPrefixLookup)
   at System.RuntimeType.GetMethodImpl(String name, Int32 genericParamCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at System.ComponentModel.Composition.MetadataViewGenerator.GetMetadataViewFactory(Type viewType)
   at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IMetadataView](IDictionary`2 metadata)
```
Or e.g.
```
System.NotSupportedException : Interface 'System.ComponentModel.Composition.IMetadataView' is not a valid MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain members that are not properties.\n---- System.TypeLoadException : Could not load type '_proxy_System.ComponentModel.Composition.IMetadataView_a4b5585e-64c3-444d-9181-04a8d1ef7bf1' from assembly ''.
```

### PR DESCRIPTION
**Pull request by fanyang-mono**
Enable tests System.ComponentModel.Composition.*

### CODE REVIEW

**Comment by EgorBo** [comment]
let's re-run them few times to make sure

**Comment by filipnavara** [comment]
@EgorBo 👍 ... note that the reason for their flakiness was fixed few months ago.

**Comment by fanyang-mono** [comment]
> @EgorBo 👍 ... note that the reason for their flakiness was fixed few months ago.

Do you happen to remember which change fixed this issue?

**Comment by filipnavara** [comment]
#15803 iirc

**Comment by EgorBo** [comment]
Yes I meant this one, I think it didn't fix the issue so I'll re-run the jobs few times

**Comment by filipnavara** [comment]
Doh. Looks like it still fails (https://dev.azure.com/dnceng/public/_build/results?buildId=395708&view=ms.vss-test-web.build-test-results-tab&runId=12341748&resultId=174179&paneView=debug) :-/

**Comment by fanyang-mono** [comment]
Looks like the tests are still failing. Thus, the issue tracking by #16417 is valid. I am going to close this pull request now.

**Pull request closed without merging**
