### PR TITLE
[corlib] Move Stack and Queue to mscorlib as we want to used them by

### PR DESCRIPTION
**Pull request by marek-safar**
implementation code in mscorlib

/cc @alexischr

### CODE REVIEW

**Comment by akoeplinger** [comment]
There's an issue on the webassembly lanes though I'm not sure why it only shows there:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'Mono.Linker.Driver:_queue' (1) due to:
Could not resolve type with token 01000044 from typeref (expected class 'System.Collections.Generic.Queue`1' in assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') assembly:System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:System.Collections.Generic.Queue`1 member:(null)
```

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff and csproj

**Pull request merged**
