### PR TITLE
[Profiler] Keep a reference to assemblies while coverage is running

### PR DESCRIPTION
**Pull request by iainx**
In certain circumstances, for example when running under nunit-console, assemblies could be unloaded while the profiler still had a reference to them in order to generate the coverage data. In these cases, the memory referred to by the profiler would be invalid and would crash.

Fix this by incrementing the reference count of the assemblies preventing them from being unloaded while coverage is being collected.

Fixes BXC #39325

### CODE REVIEW

**Comment by alexrp** [comment]
You can use `mono_assembly_addref (assembly)`.

**Comment by alexrp** [comment]
Can't we decrement the ref count when we shut down? Otherwise we'll leak the assemblies.

**Comment by iainx** [comment]
I can't use mono_assembly_addref as it's not an exported symbol and errors with

dyld: Symbol not found: _mono_assembly_addref
  Referenced from: /opt/mono/lib/libmono-profiler-log.0.dylib
  Expected in: flat namespace

The reason I hadn't done the unref was that I assumed that mono_assembly_close wouldn't be exported either like mono_assemby_addref isn't, but I've just tested it and it is, so I've updated the PR with that fix

**Comment by alexrp** [comment]
Regarding `mono_assembly_addref`, just put a `MONO_API` in front of it in `metadata-internals.h`. This'll export it so we can use it in the profiler, but without making it part of the public API.

**Comment by alexrp** [comment]
@iainx ping?

**Comment by iainx** [comment]
@alexrp sorry, I missed your comment on it. I'll do that now

**Comment by alexrp** [comment]
LGTM

@monojenkins merge

**Comment by alexrp** [comment]
build

**Pull request merged**
