### PR TITLE
[wasm][bindings] Use generics

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by kjpou1** [comment]
Agree with the change

**Comment by marek-safar** [comment]
I'm not sure this has any benefits for wasm
	- it does not save anything on the callee side
	- it increases the size by generating different generic implementations

/cc @vargaz

**Comment by jaykrell** [comment]
Aren't those the normal tradeoffs of generics always?
Static type safety vs. code size?
Is Wasm different?

**Comment by vargaz** [comment]
Generics are ok in small quantities. The main cause of generic size issues is using structures like KeyValuePair, etc.

**Comment by kjpou1** [comment]
It is with the public bindings used by developers so could be seen as beneficial and has been requested in the past.  The only problem I would have with it is that this all changes in the dotnet runtime source code.

**Comment by lewing** [comment]
if we think this is worth doing I can forward port it to dotnet/runtime once kenneth's pr lands

**Pull request closed without merging**
