### PR TITLE
[bcl] Tests for Span libraries

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by marek-safar** [comment]
@kumpera the failures are in Unaligned tests on all non amd64 platforms, and general failure on Windows

**Comment by kumpera** [comment]
@marek-safar those are expected, unaligned access requires JIT support.

**Comment by migueldeicaza** [comment]
This is downloading binaries and using those to provide the implementation, any reason why we can not do a source code compilation?

I do not want to go down the path of binary blobs for a few reasons:

* It a step backwards generally
* It prevents the code from being distributed in OSS distributions

Please make it so that these new libraries are compiled as part of Mono.

**Comment by marek-safar** [comment]
> This is downloading binaries and using those to provide the implementation
Not true, it's downloading binaries to run tests on Mono we don't intend to distribute the binaries (there is no reason to do that).

**Comment by migueldeicaza** [comment]
I am confused, this does look like the target does download a binary as the target for build-lib:
```
+$(build_lib):
 +	curl $(NUGET) -L -o nuget.zip || wget $(NUGET) --local-encoding=utf-8 -O nuget.zip
 +	MONO_PATH="$(topdir)/class/lib/$(BUILD_TOOLS_PROFILE)$(PLATFORM_PATH_SEPARATOR)$$MONO_PATH" $(RUNTIME) $(RUNTIME_FLAGS) $(topdir)/class/lib/net_4_x/csharp.exe -r:$(topdir)/class/lib/$(PROFILE)/System.IO.Compression.FileSystem.dll -e ' System.IO.Compression.ZipFile.ExtractToDirectory("nuget.zip", "tmp/");' && cp tmp/lib/netstandard2.0/$(LIBRARY) $(topdir)/class/lib/$(PROFILE)/
```

And then copies the resulting `$(LIBRARY)` from the uncompressed file into the target.

**Comment by marek-safar** [comment]
Closing, this has been superseded by different PR

**Pull request closed without merging**
