### PR TITLE
Bump msbuild to track mono-2019-04

### PR DESCRIPTION
**Pull request by radical**
.. to pick up nuget updates.

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@lewing Oops, thanks for the catch! Fixed now.

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by radical** [comment]
Fix for two failing tests: https://github.com/mono/msbuild/pull/100 . I will update this PR once that is merged. Same for https://github.com/mono/mono/pull/14069 .

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
Fix for one failing test - https://github.com/mono/msbuild/pull/103 .

**Comment by lewing** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
Should we merge this or are we waiting on a bump?

**Comment by radical** [comment]
No, we should merge this.

**Pull request merged**
