### PR TITLE
[build] Fixes wasm tools to run on desktop .net as well

### LINKED ISSUE #11326: [wasm] [packager] Regression in packager from build .zip
When downloading the wasm sdk from the build system the packager.exe when run generates the following error:

```
Unhandled Exception:
System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
  at Mono.Options.OptionSet+ActionOption..ctor (System.String prototype, System.String description, System.Int32 count, System.Action`1[T] action, System.Boolean hidden) [0x00000] in <4df345d4a7f14a68ada799369e617e33>:0
  at Mono.Options.OptionSet.Add (System.String prototype, System.String description, System.Action`1[T] action, System.Boolean hidden) [0x00026] in <4df345d4a7f14a68ada799369e617e33>:0
  at Mono.Options.OptionSet.Add (System.String prototype, System.String description, System.Action`1[T] action) [0x00001] in <4df345d4a7f14a68ada799369e617e33>:0
  at Mono.Options.OptionSet.Add (System.String prototype, System.Action`1[T] action) [0x00001] in <4df345d4a7f14a68ada799369e617e33>:0
  at Driver.Run (System.String[] args) [0x000a3] in <4df345d4a7f14a68ada799369e617e33>:0
  at Driver.Main (System.String[] args) [0x00006] in <4df345d4a7f14a68ada799369e617e33>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: string[] string.Split(char,System.StringSplitOptions)
  at Mono.Options.OptionSet+ActionOption..ctor (System.String prototype, System.String description, System.Int32 count, System.Action`1[T] action, System.Boolean hidden) [0x00000] in <4df345d4a7f14a68ada799369e617e33>:0
  at Mono.Options.OptionSet.Add (System.String prototype, System.String description, System.Action`1[T] action, System.Boolean hidden) [0x00026] in <4df345d4a7f14a68ada799369e617e33>:0
  at Mono.Options.OptionSet.Add (System.String prototype, System.String description, System.Action`1[T] action) [0x00001] in <4df345d4a7f14a68ada799369e617e33>:0
  at Mono.Options.OptionSet.Add (System.String prototype, System.Action`1[T] action) [0x00001] in <4df345d4a7f14a68ada799369e617e33>:0
  at Driver.Run (System.String[] args) [0x000a3] in <4df345d4a7f14a68ada799369e617e33>:0
  at Driver.Main (System.String[] args) [0x00006] in <4df345d4a7f14a68ada799369e617e33>:0
```

When packaged up from a mono build it runs as expected.

_update_

o	Found the following references: https://github.com/xamarin/xamarin-macios/issues/4384  and https://github.com/xamarin/xamarin-macios/issues/4609

### PR DESCRIPTION
**Pull request by marek-safar**
Fixes #11326

### CODE REVIEW

**Comment by akoeplinger** [comment]
Fails with: 

```
make: *** No rule to make target '/mnt/jenkins/workspace/test-mono-pull-request-wasm/mcs/class/lib/wasm_tools/Mono.Cecil.dll', needed by 'Mono.Cecil.dll'.  Stop.
make: *** Waiting for unfinished jobs....
```

**Comment by kjpou1** [comment]
Marek

Will this address: https://github.com/mono/mono/issues/11326  ?

**Comment by marek-safar** [comment]
@kjpou1 yes a few others (just need to find them all)

**Comment by marek-safar** [comment]
@monojenkins commit csproj

**Pull request merged**
