### PR TITLE
[LoongArch64] Part-1: Add `codegen.h` and `mini-loongarch64.h`.

### PR DESCRIPTION
**Pull request by shushanhf**
Add a new archecture LoongArch64, this is the first patch about the `codegen.h` and `mini-loongarch64.h`.

This PR is part of #21381

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by shushanhf** [comment]
Hi, @vargaz @lambdageek 
https://github.com/mono/mono/issues/21381#issuecomment-2103793833
We have pushed all the PRs to support the LoongArch64.

Could you please review and merge these PRs.
Thanks

**Comment by shushanhf** [comment]
> Moved this PR to #21772

Sorry, should not moved to the #21772.
Just reopen this PR.

**Review by akoeplinger — APPROVED** [review]

**Comment by shushanhf** [comment]
@akoeplinger 
Thanks very much!

**Pull request merged**
