### PR TITLE
[interp] [wasm] Fix iOS13 "Maximum call stack size exceeded."

### PR DESCRIPTION
**Pull request by jaykrell**
Again the recurse/norecurse split.
Reopened because of the observed objdump of wasm, far more locals than native code, looks like this will save well over 100 bytes (assuming all locals are nonvolatile and spilled to some stack, without overlap).

This fixes iOS13 out of stack problem, on a small repro and on Blazor.

So, let's note some more details about wasm and non-wasm.
In non-wasm, when a local doesn't fit in registers, or isn't needed for a range of code, but needs to be preserved, it goes to stack.
However, stack locations can be reused, for multiple locals, multiple types, given traditional compiler lifetime analysis, often obvious via scopes. CPU can write one type, read another. Or if lifetimes are disjoint, write one type, then write another. It doesn't take code to change the type/identity of variables on the stack.

However, in wasm, locals have types. Perhaps part of being safe. Or to aid enregistration by JIT?
"reinterpret" is an actual instruction.
I gather therefore, that stack packing is much less aggressive in wasm -- integers and floats will remain distinct.
That is why this sort of change is more effective for wasm than for non-wasm.
Guessing.

See https://github.com/mono/mono/pull/17254#issuecomment-540036352.

Thanks to @kjpou1 for relentlessly pursuing and providing a repro and hand holding through wasm build/test cycle.

Non-wasm (micro?)benchmarks will suffer some.

Other than number of locals, could be large recursive functions give grief. Could also be the many temporaries implied by stack machine, again, with a large recursive function. Guessing.

Fixes https://github.com/mono/mono/issues/15981.
Should fix https://github.com/mono/mono/issues/15989.
Should fix https://github.com/mono/mono/issues/16144.
Should fix https://github.com/mono/mono/issues/16172.
Should fix https://github.com/mono/mono/issues/16986.
Should fix https://github.com/chanan/BlazorStrap/issues/226.
Two examples tested, not all of the above.
Updated form of https://github.com/mono/mono/pull/16786.

### CODE REVIEW

**Comment by jaykrell** [comment]
Very small number of failures.
Should be ok to test the WebAssembly problem.

**Comment by jaykrell** [comment]
Tests looking better now. Some cleanup & experimentation to do still, if they all pass.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Confirmed to fix Blazor.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
This has been proven to work in preliminary tests.  With this PR we are now able to have a Blazor app startup and run.

Thanks for all the help with this @jaykrell !!

**Comment by jaykrell** [comment]
There are still a few cases that recurse
with a larger frame.

I know how to fix. Would likely drive
wasm stack use a little lower 
and non-wasm a little higher.

Current PR should help all platforms
albeit wasm much more than others.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build  failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows i386

**Comment by jaykrell** [comment]
@monojenkins build Linux ARMv5

**Comment by jaykrell** [comment]
@monojenkins build OS X x64

**Comment by jaykrell** [comment]
@monojenkins build  Windows x64 C++

**Comment by jaykrell** [comment]
@monojenkins build Linux x64 C++

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build Windows x64

**Comment by jaykrell** [comment]
I was also able to confirm this fixes the problem.
I ran Blazor "counter" example on ios13 phone. I got the stack exceeded error with the release mono, and worked with my mono. I didn't actually try master itself. However with a smaller non-Blazor mono, I did try toggling between master and this PR, and got the expected error/success.

Granted: Only tested the first commit in this PR. Did not test the small-ish followups. But, faith in CI?

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Windows x64 Interpreter

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Failures all seem network related. If they don't resolve, I guess go back to first commit.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
Change the interpreter only, and wade through lots of non-interpreter failures, alas.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by kjpou1** [comment]
I confirmed with a fresh rebuild of Blazor from source that it is working on iPhone X device mobile safari iOS13.1.2.

**Comment by kjpou1** [comment]
Verified  https://github.com/mono/mono/issues/15981  application here that includes updated mono runtime  https://kjpou1.github.io/WasmWorker2/

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
This version slows down non-wasm due to call being caller.
There is a version that preserves the perf of non-wasm, via `#if`.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by BrzVlad** [comment]
Went with non-recursive interpreter

**Pull request closed without merging**
