### PR TITLE
[System] Fix DeflateStream throw on empty flush, double flush. Fixes #28777

### PR DESCRIPTION
**Pull request by Garciat**

### CODE REVIEW

**Comment by tritao** [comment]
approve

**Comment by tritao** [comment]
Fixes look good to me, I'll merge tomorrow when build bots have had a chance to finish.

**Comment by Garciat** [comment]
Build failed. Probably should've branched from a green commit, my bad. Should I rebase off mono#1682, for example?

**Comment by tritao** [comment]
build

**Pull request merged**
