### PR TITLE
[System.Reflection] CoreFX import for ExceptionHandlingClauseOptions

### PR DESCRIPTION
**Pull request by MaximLipnin**
Part of #9660.

Previously ExceptionHandlingClauseOptions was placed in referencesource  [methodbody.cs](https://github.com/mono/mono/blob/master/mcs/class/referencesource/mscorlib/system/reflection/methodbody.cs) where other content is hidden by `#if !MONO` condition.

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@monojenkins build OS X x64

**Comment by MaximLipnin** [comment]
@monojenkins build Linux x64 Hybrid Suspend

**Comment by marek-safar** [comment]
@monojenkins commit apidiff and csproj

**Comment by MaximLipnin** [comment]
Thanks for review!

**Pull request merged**
