### PR TITLE
System.Drawing: Start consuming sources from corefx

### PR DESCRIPTION
**Pull request by qmfrederik**
Sources for System.Drawing have landed in corefx. Where possible, start using sources from corefx in Mono's System.Drawing.

### CODE REVIEW

**Comment by mellinoe** [comment]
The removals look okay to me. Question, since I'm not familiar with mono's CI: Are the drawing tests run in all the legs?

**Comment by akoeplinger** [comment]
> Are the drawing tests run in all the legs?

Yep, in all the ones that matter :)

**Comment by akoeplinger** [comment]
Merged manually since I had to fixup our API diff. Thanks!

**Comment by mellinoe** [comment]
👍

**Pull request closed without merging**
