### PR TITLE
[jit] Implement devirtualization of some EqualityComparer<T>.Equals calls, the corefx code assumes this.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by joncham** [comment]
What does `The corefx code excepts these calls to be devirtualized.` mean? That the behavior is wrong without devirtualization? Or just that code assumes `EqualityComparer<T>.Equals` is fast?

**Comment by vargaz** [comment]
It assumes its fast, it calls it in inner loops etc.

**Comment by vargaz** [comment]
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs#L291

**Comment by joncham** [comment]
Thanks!

**Comment by migueldeicaza** [comment]
I do not understand @kumpera 's comment.   It seems like this is a way of attaching a meaning that is only handled at a later stage.   What is it that you are suggesting?

**Comment by vargaz** [comment]
@monojenkins build OS X x64 iOS SDK

**Comment by vargaz** [comment]
@monojenkins build Linux x64 Acceptance Tests

**Pull request merged**
