### PR TITLE
[aot] Add MONO_PATCH_INFO_INTERRUPTION_REQUEST_FLAG to the preinited got slots.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by directhex** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build Windows x64

**Comment by vargaz** [comment]
@monojenkins build Windows i386

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
