### PR TITLE
Throw ArgumentNullException if null method is passed to delegate cons…

### PR DESCRIPTION
**Pull request by joncham**
…tructor via invoke.

Fixes Unity issue: https://issuetracker.unity3d.com/issues/editor-crashes-with-g-logv-when-entering-play-mode-with-active-flowcanvas-script

### CODE REVIEW

**Comment by marek-safar** [comment]
This also need interpreter update

/cc @lewurm

**Comment by joncham** [comment]
I pushed change for interpreter as well.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
