### PR TITLE
[runtime] Synchronize calls to getprotobyname() which is thread-unsafe

### PR DESCRIPTION
**Pull request by alexischr**
Fixes https://github.com/mono/mono/issues/7087

### CODE REVIEW

**Comment by jaykrell** [comment]
There must be a way without having private custom locks? So that uncoordinated code in the process can work. You know, what about all the other non-mono code in the process that needs this information? It will race with mono just the same.

**Comment by jaykrell** [comment]
`getprotobyname_r`

**Comment by alexischr** [comment]
@jaykrell I understand, and explored other options and were not sufficient/even less sufficient. There are multiple paths to `fetch_protocol` which calls `getprotobyname` differently, and all of them can be called from any managed thread via a Socket internal call.

getprotobyname_r is the right way to go though, thanks :) If it exists in all our targets I will do that.

**Comment by jaykrell** [comment]
Android getprotobyname appears to always fail, but not certain.

I think you need to autoconfigure or ifdef it.
getprotobyname_r on Linux.
getprotobyname w/o lock on Darwin, or w/ superfluous lock for ease.
getprotobyname w/o lock on Windows it appears, or w/ superfluous lock for ease.
It'd be good to confirm that Android just fails here, or add a lock of uncertain.

Key is that that `_r` should be used if available, and where it isn't available, it seems the code was already ok.

**Comment by jaykrell** [comment]
getprotobyname_r is also on Solaris and OpenBSD.
Use `_r` if present, autoconf, else probably non-`_r` is ok (Darwin, Windows).

**Comment by alexischr** [comment]
Superseded by https://github.com/mono/mono/pull/10163 for now

**Pull request closed without merging**
