### PR TITLE
[runtime] Fix OSX 32-bit build definition

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by vargaz** [comment]
Why is this needed ? The --build= argument should already force it.

**Comment by alexanderkyte** [comment]
We were seeing fat archives on this lane elsewhere

**Comment by akoeplinger** [comment]
@alexanderkyte do we really need the `--host` as well or is the `-m32` enough?

**Comment by alexanderkyte** [comment]
@alexischr requested changes were made

**Comment by alexanderkyte** [comment]
This fixes the OSX-i386 build when cherry picked onto https://github.com/mono/mono/pull/5643

**Comment by akoeplinger** [comment]
This was included in https://github.com/mono/mono/pull/5643, closing.

**Pull request closed without merging**
