### PR TITLE
Add autoconf checks for platforms without IPv6

### PR DESCRIPTION
**Pull request by joshpeterson**
* There is an existing check for the `sockaddr_in6` struct.
* Use it to wrap code that implements IPv6.
* This makes porting to platforms that don't support IPv6 easier.
* It should have no impact on platforms that do support IPv6.

### CODE REVIEW

**Comment by xmcclure** [comment]
Josh, we have now approved this but it seems to have developed a conflict due to code drift since submission. Please correct and we will merge then.

**Comment by joshpeterson** [comment]
I've resolved the conflicts (it was a conflict with my own change) :).

**Comment by xmcclure** [comment]
@joshpeterson, I made a couple style edits to your commit, which you can see in this PR https://github.com/mono/mono/pull/4745

I think in your current version, the first couple of those #if HAVE_STRUCT_SOCKADDR_IN6 blocks will actually result in a compile error if HAVE_STRUCT_SOCKADDR_IN6 is not true. Letting you know in case you had any comments.

**Comment by joshpeterson** [comment]
Those changes look fine - sorry for the mistakes. Thanks!

**Comment by joshpeterson** [comment]
@xmcclure: Can you revert the changes from this PR? It breaks the Windows build. I'd like to correct that and come back with a new PR.

**Comment by joshpeterson** [comment]
Also, I've opened a new PR to correct the Windows build, if you would rather take it: https://github.com/mono/mono/pull/4747

I'm fine with either option.

**Comment by lateralusX** [comment]
Looks like this PR introduced a larger number of test failures on Windows platforms (both x86/x64), around 80 new test failures in System.Runtime.Remoting test package + some additional tests failing in other packages. Most error seems connection related and look pretty much similar (hopefully the same underlying cause), example of one failure:
Server stack trace:
at System.Runtime.Remoting.Channels.Tcp.HostConnectionPool.CreateConnection () [0x0002a] in D:\j\workspace\x\mcs\class\System.Runtime.Remoting\System.Runtime.Remoting.Channels.Tcp\TcpConnectionPool.cs:270
at System.Runtime.Remoting.Channels.Tcp.HostConnectionPool.GetConnection () [0x0009d] in D:\j\workspace\x\mcs\class\System.Runtime.Remoting\System.Runtime.Remoting.Channels.Tcp\TcpConnectionPool.cs:254
at System.Runtime.Remoting.Channels.Tcp.TcpConnectionPool.GetConnection (System.String host, System.Int32 port) [0x00056] in D:\j\workspace\x\mcs\class\System.Runtime.Remoting\System.Runtime.Remoting.Channels.Tcp\TcpConnectionPool.cs:103
at System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x00022] in D:\j\workspace\x\mcs\class\System.Runtime.Remoting\System.Runtime.Remoting.Channels.Tcp\TcpClientTransportSink.cs:183
at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in D:\j\workspace\x\mcs\class\System.Runtime.Remoting\System.Runtime.Remoting.Channels\BinaryClientFormatterSink.cs:157
Exception rethrown at [0]:
at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_remoting_wrapper (intptr,intptr)
at (wrapper remoting-invoke) System.Runtime.Remoting.Activation.IActivator:Activate (System.Runtime.Remoting.Activation.IConstructionCallMessage)
at System.Runtime.Remoting.Activation.AppDomainLevelActivator.Activate (System.Runtime.Remoting.Activation.IConstructionCallMessage ctorCall) [0x0002c] in D:\j\workspace\x\mcs\class\corlib\System.Runtime.Remoting.Activation\AppDomainLevelActivator.cs:70
Exception rethrown at [1]:
at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_remoting_wrapper (intptr,intptr)
at (wrapper remoting-invoke) MonoTests.Remoting.CaObject1:.ctor ()
at (wrapper remoting-invoke-with-check) MonoTests.Remoting.CaObject1:.ctor ()
at MonoTests.Remoting.ActivationTests.TestCreateTcpCao () [0x00000] in D:\j\workspace\x\mcs\class\System.Runtime.Remoting\Test\ActivationTests.cs:59
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in D:\j\workspace\x\mcs\class\corlib\System.Reflection\MonoMethod.cs:305

**Comment by joshpeterson** [comment]
The tests should be fixed with https://github.com/mono/mono/pull/4754

**Pull request merged**
