### PR TITLE
handle path stripping correctly for root of watched tree

### PR DESCRIPTION
**Pull request by razzfazz**

### CODE REVIEW

**Comment by alexischr** [comment]
Hi! Could you please provide an example or test that demonstrates the bug?

**Comment by razzfazz** [comment]
The case that this is intended to fix is when the root dir of the watched hierarchy is modified. In that case, 'path' would be equal to 'fullPathNoLastSlash', and thus 'path.Substring (fullPathNoLastSlash.Length + 1)' is illegal (offset exceeds length of string).

**Comment by razzfazz** [comment]
@alexischr, is that example sufficient, or do you need anything else here?

**Comment by alexischr** [comment]
Yes that's great, thank you!!

**Comment by knocte** [comment]
But next time, please provide the explanation in the commit message.

**Pull request merged**
