### PR TITLE
[runtime] Treat calling a non-virtual method through an open delegate the same as the normal case instead of the OPEN_VIRTUAL case.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Needs tests etc.

**Comment by vargaz** [comment]
The failures are relevant.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins backport 2019-10

**Comment by chamons** [comment]
@vargaz Can this go in 2019-08 as well?

**Comment by vargaz** [comment]
@monojenkins backport 2019-08

**Pull request merged**
