### PR TITLE
[aot] change method table generation so that it works for larger assemblies on ARM

### PR DESCRIPTION
**Pull request by lewurm**
At the end of the AOT compilation, we dump a table containing all method
entrypoints using the toolchain linker to resolve the addresses. Previously
we used `bl` for that, however on larger assemblies the offset might
overflow the 24bit immediate (thus, the linker bailing out with
"Error: branch out of range"). Instead, using `ldr pc,=<label>` followed
by `.ltorg` emits the full 32bit address to a method. That takes 8 bytes
for each method instead of 4 bytes.

( I couldn't reopen https://github.com/mono/mono/pull/3486 anymore)

### CODE REVIEW

**Comment by lewurm** [comment]
PR verified on Android by @grendello. We gonna need to backport this up to `2018-10`

**Comment by lewurm** [comment]
@monojenkins squash

**Comment by marek-safar** [comment]
@monojenkins backport 2019-04

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Pull request merged**
