### PR TITLE
[arm64] Set a llvm target layout. Assert in llvm if the target layout is not set, the defaults used by 'opt' are not correct.

### PR DESCRIPTION
**Pull request by vargaz**
It is important to provide this, otherwise the `opt` command will make modifications of every GC safepoint load. For the SmartHotel360 Android app, this can result in `opt` taking 19 minutes and 20 seconds to finish the optimization of the Mono.Android.dll AOT modules.

### IR Example: 

Before Opt:
```
   >   %GC_SAFE_POINT_FLAG_7 = load i64*, i64** getelementptr inbounds ([166068 x i64*], [166068 x i64*]* @mono_aot_Mono_Android_llvm_got, i32 0, i32 7), !invariant.load !139597
    >   %4 = load volatile i64, i64* %GC_SAFE_POINT_FLAG_7
    >   %5 = icmp eq i64 %4, 0
    >   br i1 %5, label %CONT_BB2, label %POLL_BB1
```

After Opt:
```
    <   %GC_SAFE_POINT_FLAG_7 = load i64*, i64** getelementptr inbounds ([166068 x i64*], [166068 x i64*]* @mono_aot_Mono_Android_llvm_got, i64 0, i64 7), align 8, !invariant.load !139597
    <   %3 = load volatile i64, i64* %GC_SAFE_POINT_FLAG_7, align 4
    <   %4 = icmp eq i64 %3, 0
    <   br i1 %4, label %BB2, label %POLL_BB1
```

This has a huge impact on build time, giving InstCombine a huge slowdown. This change removes the need for opt to rewrite all of these basic blocks. 

- Added by @alexanderkyte

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@vargaz looks like the `g_assert_not_reached` you added is failing on x64, etc

**Comment by alexanderkyte** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@monojenkins backport 2019-06

**Pull request merged**
