### PR TITLE
Disable AnonymousPipe tests as 3 are failing in several PRs.

### PR DESCRIPTION
**Pull request by jaykrell**
https://github.com/mono/mono/issues/9776
They are new from about 3 days ago, commit 0f0e31842f1f394c4e95d3726c20af547e706278.

### CODE REVIEW

**Comment by filipnavara** [comment]
Can we disable only the failing ones? Either the one or two xtest files or directly the tests in CoreFX. I can submit PRs for that...

**Comment by jaykrell** [comment]
git grep was failing me so I disabled them all, but yes.

**Comment by filipnavara** [comment]
Please don't merge. I think I found the cause and it's a broken PAL compilation for TARGET_WIN32 as described in #9776. The pipes are just a symptom of it.

**Comment by jaykrell** [comment]
https://github.com/mono/mono/pull/9780 instead

**Comment by jaykrell** [comment]
Not sure -- from Filip's comments. But the other commit didn't seem to go through CI at all.

**Comment by jaykrell** [comment]
Abandon this if https://github.com/mono/mono/pull/9780 succeeds.

**Comment by akoeplinger** [comment]
#9780 was merged.

**Pull request closed without merging**
