### PR TITLE
Updates CoreFX to track 2.1 release

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Coop GC

**Comment by luhenry** [comment]
@monojenkins build Linux x64

**Comment by luhenry** [comment]
@marek-safar are the `Linux x64 mcs` compilation errors cases of MCS not supporting some C# features?

```
../../../external/corefx/src/System.Memory/src/System/Buffers/StandardFormat.cs(106,76): error CS1525: Unexpected symbol `?'
../../../external/corefx/src/System.Memory/src/System/ReadOnlySpan.cs(372,31): error CS1519: Unexpected symbol `readonly' in class, struct, or interface member declaration
../../../external/corefx/src/System.Memory/src/System/ReadOnlySpan.cs(372,35): error CS0106: The modifier `readonly' is not valid for this item
```

**Comment by marek-safar** [comment]
build Linux x64 mcs

**Comment by marek-safar** [comment]
build Linux x64

**Comment by marek-safar** [comment]
@monojenkins build Linux x64

**Comment by marek-safar** [comment]
@monojenkins build Linux x64

**Comment by marek-safar** [comment]
@monojenkins commit apidiff

**Pull request merged**
