### PR TITLE
[corlib] Make all Encoding types serializable

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/mono/mono/issues/11529 
Fixes https://github.com/mono/mono/issues/11663

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by EgorBo** [comment]
Failures due to Reflection stuff in `external/corefx` changes I pulled with my PR

**Comment by marek-safar** [comment]
@monojenkins backport 2018-10

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Comment by marek-safar** [comment]
@EgorBo please also backport to 2018-10

**Pull request merged**
