### PR TITLE
[wasm] WebAssembly IO Portability

### PR DESCRIPTION
**Pull request by kjpou1**
Configure WASM to not disable IO portability.  WebAssembly runtime can run on windows or *nix type of files systems.  With turning on the IO portability we can attempt to support both nomenclatures.

fixes: https://github.com/mono/mono/issues/18933

### CODE REVIEW

**Comment by kjpou1** [comment]
@monojenkins build Linux i386

**Comment by kjpou1** [comment]
@monojenkins build Linux WebAssembly

**Comment by kjpou1** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by kjpou1** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Comment by kjpou1** [comment]
@monojenkins build Windows x64 FullAOT+LLVM

**Comment by baulig** [comment]
According to the [man page](https://github.com/mono/mono/blob/a4a19c3cb4d881d4c4f0798927dc8a6f8952aae7/man/mono.1#L1557), `MONO_IOMAP` is deprecated and no longer works with Mono 6.0.

Instead of setting the environment variable, I think it'd be better to completely disable it by adding a compiler conditional for WASM to the code.

**Comment by vargaz** [comment]
io portability is for running legacy .net apps on mono, its not really relevant for webassembly.

**Comment by kjpou1** [comment]
Perfect will do.  Thanks

**Comment by kjpou1** [comment]
closed in favor of https://github.com/mono/mono/pull/19488

**Pull request closed without merging**
