### PR TITLE
[aot] Avoid passing -march=arm to llc when using thumb, it forces arm32 code generation.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/14247.

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins backport 2019-02

**Comment by lewurm** [comment]
we should untangle this code with some `ifdef TARGET_IOS`, `ifdef TARGET_LINUX`, etc because mixing that stuff makes it a maintenance nightmare.

**Comment by jaykrell** [comment]
@lewurm but runtime `if` better than compile-time `#if` or `#ifdef` so one compiler can target multiple.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-04

**Pull request merged**
