### PR TITLE
Implement CustomErrorsMode for RemotingConfiguration

### LINKED ISSUE #13250: Setting CustomErrorsMode for RemotingConfiguration throws NotImplementedException
## Steps to Reproduce

1. set CustomErrorsMode for RemotingConfiguration
`RemotingConfiguration.CustomErrorsMode = CustomErrorsModes.Off;`

### Current Behavior
Throws NotImplementedException.

### Expected Behavior
CustomErrorsMode must be setted and used in remoting

## On which platforms did you notice this

[ ] macOS
[x] Linux
[x] Windows

**Version Used**:
5.21

### PR DESCRIPTION
**Pull request by sancheolz**
fixes #13250

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@sancheolz this seems to break a bunch of tests in System.Runtime.Remoting and System.Web. Can you please take a look?

**Comment by sancheolz** [comment]
@akoeplinger  sorry I didn`t run this tests before. Last commit must fix it

**Comment by sancheolz** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
@monojenkins build

**Comment by akoeplinger** [comment]
Failures are unrelated: https://github.com/mono/mono/issues/13289

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff

**Comment by akoeplinger** [comment]
Thank you for the contribution!

**Comment by sancheolz** [comment]
@marek-safar could you backport it to 2019-02

**Pull request merged**
