### PR TITLE
Infrastructure support / fixes for making compiler server the default

### PR DESCRIPTION
**Pull request by kg**
Test PR

### CODE REVIEW

**Comment by kg** [comment]
It looks like most lanes work with the compiler server forced on, though it's unclear whether they're actually using it. We'd need to add a check for it to every lane (maybe just one that does a diagnostic print at the end so we can check?)

/cc @directhex @akoeplinger @marek-safar

**Comment by kg** [comment]
From a quick build timing comparison, All Profiles is roughly the same speed (~30 seconds faster with compiler server, which is basically noise) and Linux x64 is ~2 minutes slower. I don't think it's reasonable to make the compiler server default on (maybe on for -j 1 if we can detect it, and off for multithreaded builds?)

**Comment by Therzok** [comment]
Is there any VB project being built? We had to disable it in VSMac due to VBCSCompilerServer hanging around with 100% CPU usage.

**Comment by kg** [comment]
> Is there any VB project being built? We had to disable it in VSMac due to VBCSCompilerServer hanging around with 100% CPU usage.

The two main causes of hangs should have been fixed by my somewhat recent changes. IIRC there were bugs in the native runtime and in the timers implementation that caused very high CPU usage. If you can point to a sample VB project I can try to add that to the compiler server tests

**Comment by kg** [comment]
@monojenkins build failed

**Comment by kg** [comment]
Currently blocked on https://github.com/dotnet/corefx/issues/27152 (which was marked as blocked on mono's integration of named pipes in https://github.com/mono/mono/issues/7143, but corefx named pipes also don't seem to work on mac under mono)
The current issue is that an exception is thrown dealing with paths during initial named pipe setup (I sure wish we ran these things with --debug):
```
03:09:33 Unhandled Exception:
03:09:33 System.IO.IOException: Error on creating named pipe: error code -1
03:09:33   at System.IO.Pipes.UnixNamedPipe.EnsureTargetFile (System.String name) [0x00029] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at System.IO.Pipes.UnixNamedPipeClient..ctor (System.IO.Pipes.NamedPipeClientStream owner, System.String serverName, System.String pipeName, System.IO.Pipes.PipeAccessRights desiredAccessRights, System.IO.Pipes.PipeOptions options, System.IO.HandleInheritability inheritability) [0x00080] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at System.IO.Pipes.NamedPipeClientStream..ctor (System.String serverName, System.String pipeName, System.IO.Pipes.PipeAccessRights desiredAccessRights, System.IO.Pipes.PipeOptions options, System.Security.Principal.TokenImpersonationLevel impersonationLevel, System.IO.HandleInheritability inheritability) [0x0003b] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at System.IO.Pipes.NamedPipeClientStream..ctor (System.String serverName, System.String pipeName, System.IO.Pipes.PipeDirection direction, System.IO.Pipes.PipeOptions options, System.Security.Principal.TokenImpersonationLevel impersonationLevel, System.IO.HandleInheritability inheritability) [0x00009] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at System.IO.Pipes.NamedPipeClientStream..ctor (System.String serverName, System.String pipeName, System.IO.Pipes.PipeDirection direction, System.IO.Pipes.PipeOptions options, System.Security.Principal.TokenImpersonationLevel impersonationLevel) [0x00000] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at System.IO.Pipes.NamedPipeClientStream..ctor (System.String serverName, System.String pipeName, System.IO.Pipes.PipeDirection direction, System.IO.Pipes.PipeOptions options) [0x00000] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at System.IO.Pipes.NamedPipeClientStream..ctor (System.String serverName, System.String pipeName, System.IO.Pipes.PipeDirection direction) [0x00000] in <7505d9a21cfc4fc7b41cb4768918fdb4>:0 
03:09:33   at (wrapper remoting-invoke-with-check) System.IO.Pipes.NamedPipeClientStream..ctor(string,string,System.IO.Pipes.PipeDirection)
03:09:33   at Microsoft.CodeAnalysis.CommandLine.BuildClient.AreNamedPipesSupported () [0x00020] in <c5b69312ab114f1599988504540296fa>:0 
```

**Comment by kg** [comment]
@monojenkins build failed

**Comment by kg** [comment]
The root cause of the OS X issues is that our OS X machines have system mono manually configured, and the system mono does not have current (functioning) named pipes. One fix would be to update system mono, but builds shouldn't even be using system mono at all.

**Comment by kg** [comment]
@monojenkins build failed

**Comment by kg** [comment]
@marek-safar So I've had a few builds pass on every lane now with the compiler server defaulted on, and from looking at the logs it's working. Do we want to merge that? If not, I can adjust this PR so the default is 'off', but keep all the infrastructure changes so it's easy for us to flip on later and easier to test.

**Comment by marek-safar** [comment]
@kg yes, would love to get this in with the default on

**Comment by kg** [comment]
@marek-safar  How do we want to deal with the downsides? Off the top of my head:
1. The compiler server is not faster than regular compiles in all scenarios, particularly -j 4 and above on fast machines
2. It may not work on some people's build configurations
3. We don't know how it behaves in constrained memory scenarios
If we want to flush out issues by setting it as default so people hit issues on their local dev machines then that makes sense but I wanted to make sure that's what we are doing here. Should we announce it via email/slack first before merging?

**Comment by marek-safar** [comment]
It'd be good to document the opt-out mode at https://www.mono-project.com/docs/compiling-mono/linux/

**Comment by kg** [comment]
After discussion with @akoeplinger we will be waiting until after 2019-06 branches to merge this

**Comment by kg** [comment]
Plans changed, I set the default to off and will be merging this. The default will be flipped separately after the 2019-06 branch is ready

**Comment by kg** [comment]
@monojenkins build failed

**Pull request merged**
