### PR TITLE
PPC JIT optimizations (System.Math instruction inlining)

### PR DESCRIPTION
**Pull request by NattyNarwhal**
Optimizes a bunch of functions with expensive function call overhead into neat one or two instructions inlined. Optimizations are based on amd64 mini instruction emitting. Instructions used are still within the POWER5 optimizations applied.

`rcheck` in mini passes, and output seems sane from prodding code. Linux, PASE, and ppc32 are untested. Floating point I know can be.... delicate, but since amd64 tries to take the HW shortcuts, and IEEE floating point should be consistent, try this.

Functions affected:

* `System.Math`

  *  `Min (int32, int32)`

  *  `Min (uint32, uint32)`

  *  `Min (int64, int64)` (don't enable long int arith functions on ppc32 though, based on implications in mini for ppc32)

  *  `Min (uint64, uint64)`

  *  `Sqrt (double)`

  *  `Abs (double)`

  *  `Round (double)`

  *  `Truncate (double)`

  *  `Ceiling (double)`

  *  `Floor (double)`

* `System.MathF`

  *  `Sqrt (float)`

Other easy wins to add later: It'd be nice to add the double/float overloads for Min/Max working, (even if fsel is a bit wonky, compare-and-branch inlining could work?) integer modulo on POWER9, popcount/trailing zeroes on POWER9. (I don't have anything past POWER7 to test with.)

### CODE REVIEW

**Comment by marek-safar** [comment]
@lewurm could you please review

**Comment by lewurm** [comment]
@monojenkins build Linux PPC64 little endian

**Comment by luhenry** [comment]
@NattyNarwhal is that still good to merge?

**Comment by luhenry** [comment]
@monojenkins build

**Comment by NattyNarwhal** [comment]
I think it should be fine, only caveat is I haven't tested it on Linux, nor have I tested on G5. I tried to check for the appropriate flags though, so...

**Pull request merged**
