### PR TITLE
[ci] Precompile runtime tests on the mac-sdk lane before running them with llvm.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by akoeplinger** [comment]
@monojenkins build OS X Extended

**Comment by vargaz** [comment]
The buildtime on that lane is down to 2 hours.

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
Looks good, the errors on the lane are preexisting and will need to be looked at separately so let's get this in.

**Pull request merged**
