### PR TITLE
Reduce #ifdef MONO_ARCH_SOFT_FLOAT_FALLBACK, and #if SIZEOF_VOID_P == 4.

### PR DESCRIPTION
**Pull request by jaykrell**
The optimizer should be able to do the same.

This reduces ARM32-specific breaks, as more code compiles
for all architectures (but is optimized away).

### CODE REVIEW

**Comment by vargaz** [comment]
It was kept ifdef-ed because its a large body of code, and we only want to include it if needed.

**Comment by jaykrell** [comment]
Optimizer should handle it the same. All the runtime ifs will evaluate to constant false when the ifdef was false.

**Comment by jaykrell** [comment]
I don't see how. Let me double check.
Taking the address of a function under if (0) should not keep the function, for example.

**Comment by jaykrell** [comment]
Huh, apparently Unix linkers don't throw out unused functions, unless they are also static.
Most of these functions in jit-icalls.c are only referenced from mini-runtime.c so I moved them there and made them static and then they are gone. As well, though I didn't check, they should have been comprised of "only" unreached() (which could be bloaty with assertion failure, file, line).

**Comment by vargaz** [comment]
Those functions are jit icalls, so logically they should be in jit-icalls.c, is it really worth doing all this work just to get rid of one ifdef ?

**Comment by jaykrell** [comment]
The overall symbol or the specific instance(s)? I can put back one or two instances if desired, i.e. around the functions and their registration, and still achieve similar. The "work" is easy and quick, but the churn and desired structure of the code matter, granted.

static does have side benefits that weren't the original point.

**Comment by jaykrell** [comment]
Hm. I like the static. Can the registration be moved to jit-icalls instead of mini-runtime.c? Let me see.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
@monojenkins build Linux AArch64

**Comment by luhenry** [comment]
This doesn’t have any positive impact, and it seems to be mostly about fitting personal preferences.

**Pull request closed without merging**
