### PR TITLE
Some external_only/internal split, and inlining.

### PR DESCRIPTION
**Pull request by jaykrell**
mono_type_get_type
 mono_type_get_signature
 mono_type_is_byref
 mono_type_get_class
 mono_type_get_array_type

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by jaykrell** [comment]
master or CI seems to be in a bad state.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by SamMonoRT** [comment]
Is there any performance/functional improvement here with splitting internal/external ? Trying to understand motivation behind these changes.

**Comment by jaykrell** [comment]
Internal/external is/was the general direction.
Avoiding the GC mode switches ditto.
Inlining seems like common sense here.
It is too bad we don’t use LTCG,it’d Inline.

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by lambdageek** [comment]
@monojenkins squash

**Pull request merged**
