### PR TITLE
[corlib] Import System.IO.TextWriter/StreamWriter from CoreFX

### PR DESCRIPTION
**Pull request by alexischr**
Contributes to #7246

### CODE REVIEW

**Comment by alexischr** [comment]
@monojenkins commit csproj

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@alexischr could you resolve the conflicts, also looking that the failure they look related but not sure why

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by alexischr** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Pull request merged**
