### PR TITLE
[msbuild] Bump to track xplat-master

### PR DESCRIPTION
**Pull request by radical**
.. to pick up https://github.com/mono/msbuild/pull/142 and
https://github.com/mono/msbuild/pull/139 .

### CODE REVIEW

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
@monojenkins build failed

**Comment by radical** [comment]
@monojenkins build OS X Extended

**Comment by radical** [comment]
`os x extended`:
```
MonoTests.runtime.threadpool-exceptions7.exe
MonoTests.test-unhandled-exception-2-1-with-managed-handler.unhandled-exception-1.exe
MonoTests.test-unhandled-exception-2-255-without-managed-handler.unhandled-exception-3.exe
RemotingServicesTest.Bug46473
```

`Linux ARMv5`: `fullaot-mixed` tests failed with a runtime crash: https://gist.github.com/radical/165344169c1444e7a69a95c9009a7b23
`Linux ARMv7 interpreter`: `fullaot-mixed` tests failed with a runtime crash https://gist.github.com/radical/2fd0f54cc03f84b9f8744043d81cc9f0

`OS X x64 C++`:
```
10:57:53 + xcodebuild -version
10:57:53 dyld: Symbol not found: _OBJC_IVAR_$_NSTextViewIvars.sharedData
10:57:53   Referenced from: /Applications/Xcode833.app/Contents/SharedFrameworks/DVTDocumentation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
10:57:53   Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
10:57:53  in /Applications/Xcode833.app/Contents/SharedFrameworks/DVTDocumentation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
10:57:53 /var/folders/nm/jc7bgcdd3x59npxl_26qlcw00000gn/T/jenkins814210116761758315.sh: line 8:  8443 Abort trap: 6           xcodebuild -version
10:57:53 Build step 'Execute shell' marked build as failure
```

**Comment by radical** [comment]
`mono-coreonly-CI (Build Linux 64)` - 4 `System.Drawing.Common` tests failed

**Comment by radical** [comment]
@akoeplinger Any idea about these failures?

**Comment by akoeplinger** [comment]
The failures are unrelated.

**Pull request merged**
