### PR TITLE
Generalize optimization avoiding struct loads for loading a field

### PR DESCRIPTION
**Pull request by mathieubourgeois**
This fix is a generalization of commit 0c6932a985175a5cf0cbc59ffd3af4abf3db248e. The previous commit was restricted to LDLOC and LDLOCS. We now avoid loading a struct for all variants of LDLOC and LDARG. Testing on a simple armv7-a Vector3 class provides a reduction in instructions for an addition operator of about 30% (~64 -> 40 instructions)

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux i386

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Acceptance Tests

**Comment by luhenry** [comment]
@monojenkins build Linux ARMv7 hard float

**Comment by luhenry** [comment]
@mathieubourgeois please sign the CLA if you want this change to be merged. As soon as it's signed, this pull request is ready to be merged.

**Comment by mathieubourgeois** [comment]
Yeah sorry about that, I'm working on it :(

**Comment by mathieubourgeois** [comment]
Sorry for the delay again, the CLA is now signed

**Comment by lewurm** [comment]
@monojenkis backport 2017-12

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Comment by luhenry** [comment]
@monojenkins backport to 2017-10

**Pull request merged**
