### PR TITLE
Sanitize TLS handling in the profiler.

### LINKED ISSUE #7683: Assertion at /Users/builder/data/lanes/5808/1c6f300e/source/xamarin-macios/external/mono/mono/profiler/log.c:546, condition `mono_lls_insert (&log_profiler.profiler_thread_list, hp, &thread->node) && "Why can't we insert the thread in the LLS?"' not met
This comes from Xamarin.Profiler bug https://bugzilla.xamarin.com/show_bug.cgi?id=61265

Seems there is not enough information to know why that assertion is being hit, and @alexrp mentioned there should be a better assertion in mono 5.10, so moving it here so that it gets tracked in mono.

### PR DESCRIPTION
**Pull request by kumpera**
Fixes https://github.com/mono/mono/issues/7683

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build pkg

**Comment by kumpera** [comment]
something broken with this PR.

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Interpreter

**Comment by luhenry** [comment]
@monojenkins build Linux x64 FullAOT+LLVM

**Comment by marek-safar** [comment]
@monojenkins backport 2018-04

**Comment by marek-safar** [comment]
@monojenkins backport 2018-02

**Comment by marek-safar** [comment]
@monojenkins backport 2017-12

**Comment by kumpera** [comment]
@marek-safar 
2017-12:
https://github.com/mono/mono/pull/8886

2018-02:
https://github.com/mono/mono/pull/8887

Do you need 2018-04 manually done too?

**Comment by luhenry** [comment]
@kumpera 2018-04 is available at https://github.com/mono/mono/pull/8881

**Pull request merged**
