### PR TITLE
[Mono.Options] Changed the code a bit so that it works with PCL

### PR DESCRIPTION
**Pull request by mattleibow**
The `TypeDescriptor` types aren't available on PCL, but in this case I switch it out for a more basic, but cross-platform conversion using `IConvertible` through `Convert.ChangeType`.

This change should not affect the net40 running at all.

### CODE REVIEW

**Comment by akoeplinger** [comment]
whitelist

**Comment by jonpryor** [comment]
Have I mentioned how much I *love* PCLs?

(*Note*: I do not actually love PCLs.)

**Comment by jonpryor** [comment]
What's missing is any *use* of the PCL define. Should a new Makefile target be added to build this PCL version? How do we make sure that the PCL-defined version even *builds*, and doesn't stop building in the future?

**Comment by mattleibow** [comment]
@jonpryor :) We will be building it from components CI... Does this help?

**Comment by jonpryor** [comment]
@mattleibow: Yes, building it in the components CI does help, but how often will that be rebuilt?

**Comment by mattleibow** [comment]
We can set up a file watcher to notify us. We can then request a build.

Right now, I dont think it builds... I got an error when running make saying that it cant fine some excludes file. Maybe was just me.

**Comment by mattleibow** [comment]
Maybe I should clarify my previous comment. It didn't build before I made the changes... Seems to be something up with the Makefile.

**Pull request merged**
