### PR TITLE
[Loader] Solving the problem of incorrect output of library parameters

### PR DESCRIPTION
**Pull request by alexger97**
This is the first part of the functionality for solving a more global problem described in
https://github.com/mono/mono/issues/19803.

I encountered problems in testing at https://github.com/mono/mono/pull/19876, I hope to solve the problem step by step, especially since this code is necessary even without a comprehensive solution to the problem

### CODE REVIEW

**Comment by alexger97** [comment]
Please, make review and run Tests

**Comment by alexger97** [comment]
Good day! Feedback is very important, as I think this code is appropriate

**Comment by marek-safar** [comment]
@monojenkins approve

**Comment by marek-safar** [comment]
@lambdageek @CoffeeFlux could you please review this?

**Comment by marek-safar** [comment]
Closing after merging the full PR

**Pull request closed without merging**
