### PR TITLE
Cleaning up SslStream, MobileAuthenticatedStream and TaskToApm.

### PR DESCRIPTION
**Pull request by baulig**
### Overview

After the removal of the Legacy TLS Provider, we can make some cleanups and improvements to the `SslStream` class.  Since both the remaining providers use the internal `MobileAuthenticatedStream` and support Task-async code, we can get rid of some of the Begin/End async logic and the the underlying
`Stream` class handle it instead.

This also fixes a nasty issue with some of those task objects leaking unobserved exceptions.  The problem was that `SslStream.Dispose()` needs to clear out all resources, but in doing so also nulls out the `Impl` handle to the `MobileAuthenticatedStream` - so a subsequent `End*()` call will not reach it's corresponding `TaskToApm.End()` method.

There are also some cleanups in the internal APIs that were only ever used internally and not intended for public consumption.

### Mono.Security.dll

* `Mono.Security.Interface`: removed internal `ICertificateValidator2` interface.

* `Mono.Security.Interface.IMonoSslStream`: this internal interface is only used by the web-tests, which only use it as a way to get the `SslStream` instance, so all those `Begin/End` async methods are now gone.

* `Mono.Security.Interface.IMonoSslStream2`: removed another internal interface.

* `Mono.Security.Interface.MonoTlsProvider`: removed some `internal abstract` methods; these have been moved into a new `Mono.Net.Security.MobileTlsProvider` inside `System.dll`.

### System.dll

* `Mono.Net.Security.MobileTlsProvider`:
  New abstract internal base class, which received the aforementioned abstract internal methods.  The naming is such to make it consistent with the already existing `MobileTlsContext` and `MobileAuthenticatedStream`.

Since both `AppleTlsProvider` and `BtlsProvider` now have an abstract internal base class inside `System.dll`, they can use the `ChainValidationHelper` class directly and we can also avoid some `Mono.Security` dances like for instance that `MonoSslPolicyErrors` enum.

This will also help make the code easier to read and maintainer.
  
* `Mono.AppleTls.AppleTlsProvider` and `Mono.Btls.MonoBtlsProvider`: change base class into `MobileTlsProvider` and reflect above mentioned overload changes.

* `Mono.AppleTls.AppleCertificateHelper`: use `ChainValidationHelper` as well.

* `Mono.Net.Security.ChainValidationHelper`: only implement `ICertificateValidator`.
  The `ICertificateValidator` interface is still required because it is in use by the web-tests, but the previous `ICertificateValidator2` was an internal dance.

* `Mono.Net.Security.MobileAuthenticatedStream`: largely cleaned up this class.
  - we now implement the current slimmer version of `IMonoSslStream`.
  - moved all those overloads into `SslStream` that only fill in default values for some of their arguments and then call another overloaded version of their own.
  - removed lots of `Begin/End` methods that are not used anymore.

* `Mono.Net.Security.MonoTlsProviderFactory`: use `MobileTlsStream` everywhere.

* `Mono.Net.Security.MonoTlsStream`: cleanup `SslStream` creation logic; instead of going throw `provider.CreateSslStream()`, we can now use an internal constructor directly, thus avoiding the `IMonoSslStream` interface while also making the code a lot easier to read and understand.

* `System.Net.Mail.SmtpClient`: same here.

* `System.Net.HttpWebRequest`: use `MobileTlsProvider`.

* `System.Net.Security.SslStream`: largely cleaned up this class.
  - we now use `MobileAuthenticatedStream` directly instead of the `IMonoSslStream` interface and therefore could also get rid of `IMonoSslStream2`.
  - cleanup constructor logic to allow the internal constructor being used with a `MobileTlsProvider` instead of going through `provider.CreateSslStream()`.
  - all those overloads that are only filling in default values for some of their arguments before calling another overloaded version of their own now live here instead of in the `MobileAuthenticatedStream` class.  The reason is to simply that `MobileAuthenticatedStream` is already quite a complex and difficult class, and removing some of that complexity out of it will make it easier to understand.
  - handle the `TaskToApm.Begin()` / `TaskToApm.End()` here to ensure that we are not leaking any task objects with unobserved exceptions.
  - removed `BeginRead()` and `BeginWrite()` overloads to let the underlying `Stream` class handle these.

### CODE REVIEW

**Comment by steveisok** [comment]
@monojenkins build failed

**Comment by steveisok** [comment]
@baulig I think it looks good.  Only question I have is re: tests.  Are there any that try to cancel / reconnect similar to the bug that triggered this PR?

**Comment by baulig** [comment]
Well, I wanted to keep the renames and refactoring to a minimum and also avoid using ugly prefixes in too many places.  Renaming that MobileTlsProvider into MonoTlsProvider would require `MSI.` or `MNS.` prefixes to be used in most of the places where it's used.

We could of course find another name for it that does not conflict with the APIs in the `Mono.Security.Interface` namespace.

**Comment by akoeplinger** [comment]
@monojenkins commit apidiff and csproj

**Comment by steveisok** [comment]
@monojenkins backport 2019-10

**Comment by gekas** [comment]
Hi,

In our project we used **Read, Write, BeginWrite, EndWrite, BeginRead, EndRead** methods of **IMonoSslStream** that I get from **MonoTlsProvider** built by **MonoTlsProviderFactory**.

After updating Visual Studio to version Visual Studio Enterprise 2019 Version 16.8.2, this methods are gone from **IMonoSslStream**. Based on changes in this PR I understood them was replaced with async versions: **ReadAsync**, **WriteAsync**.

Based on changes in this PR I **MonoTlsProviderFactory** should now return **MobileTlsProvider** instead of **MonoTlsProvider** but version file **MonoTlsProviderFactory** remains same as before.
So looks like there are missed part of changes from this PR in specified version of VisualStudio ?

I'm using 7.1 version of Mono specified.
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    ....
    <TargetFramework>MonoAndroid71</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworkVersion>v7.1</TargetFrameworkVersion>
  </PropertyGroup>
.....

Do you have some advices or thoughts how it is possible I have not all changes from this PR?

**Pull request merged**
