### PR TITLE
[watch] Align cinfo->stack_usage to 16 on watchos.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/mono/mono/issues/7685.

### CODE REVIEW

**Comment by marek-safar** [comment]
Please backport to 2018-02 and up

**Comment by luhenry** [comment]
@monojenkins build OS X x64

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64

**Comment by vargaz** [comment]
@monojenkins backport 2018-04

**Comment by vargaz** [comment]
@monojenkins backport 2018-02

**Comment by vargaz** [comment]
@monojenkins backport 2017-12

**Pull request merged**
