### PR TITLE
[GTK] Only autoscroll viewport when accessibility is disabled

### PR DESCRIPTION
**Pull request by bratsche**
Don't review/merge this. This PR is only to create a package to test this bockbuild branch with https://github.com/mono/bockbuild/pull/134

### CODE REVIEW

**Comment by bratsche** [comment]
@monojenkins build OS X Package

**Comment by bratsche** [comment]
@monojenkins build OS X Package

**Comment by akoeplinger** [comment]
@bratsche what's the status of this PR?

**Comment by bratsche** [comment]
I think we can close this.

**Pull request closed without merging**
