### PR TITLE
Remove InetAccess and ValueAdd NUnit categories

### PR DESCRIPTION
**Pull request by akoeplinger**
**InetAccess:** We have _tons_ of tests that rely on working DNS/Internet that aren't marked with InetAccess (and they actually provide good value so we don't want to exclude them).

Since the category doesn't really make sense and just causes confusion it's better to just remove it.
## 

**ValueAdd:** It was added over a decade ago and all the tests marked with this category are passing now.

### CODE REVIEW

**Comment by vargaz** [comment]
The InetAccess category is there to make the tests less dependent on a working internet, without it, a lot of temporary net disruptions could cause the tests to fail.

**Comment by akoeplinger** [comment]
@vargaz as I said, we have tons of tests that access the net already. We could of course apply the label to all of those, but that'd exclude them from CI runs.

I think at this point it's easier to just remove the label from the few tests that still have them and see what happens. Btw. most of these tests *do* run as part of the Android test runs, so they've either been disabled there already (AndroidNotWorking, which I just put to NotWorking here) or work on Android so are apparently fine.

**Comment by alexrp** [comment]
Well, there would perhaps be some value in flagging tests as `InetAccess` if they require a connection, but *not* disabling them by default. Then one could exclude this category if working offline. However, as with most things that are not used regularly, that list of tests will probably not be maintained properly so it'll be of little use in a year or so.

So, I'm OK with removing these categories as long as nothing breaks horribly.

**Comment by akoeplinger** [comment]
Yeah, the idea of `InetAccess` is good in theory but quickly falls down in practice.

My plan was to schedule a few builds of this once we're green in CI to make sure this doesn't break anything, it's low priority :)

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by akoeplinger** [comment]
Yes, I still want this. I have it on my todo list for my next turn in the maintenance rotation.

**Pull request merged**
