### PR TITLE
[corlib] MyDocuments maps to /home/foo/Documents, not $HOME

### PR DESCRIPTION
**Pull request by knocte**
In Windows, SpecialFolder.MyDocuments maps to
"C:\Documents and Settings\foo\My Documents".

The equivalent to this in Linux should be
"/home/foo/Documents", not "/home/foo".

In fact, there's already another SpecialFolder enum member
that already maps to "/home/foo" and
"C:\Documents and Settings\foo", respectively, it is
the SpecialFolder.UserProfile member.

### CODE REVIEW

**Comment by akoeplinger** [comment]
This would break everybody that relied on `Personal` being `$HOME` though, I don't think we can change it easily. Similar PR for reference: https://github.com/mono/mono/pull/1953

**Comment by knocte** [comment]
I don't think anyone sane would have relied on that if he were developing cross-platform software. Sometimes breaking changes need to happen.

**Comment by akoeplinger** [comment]
@knocte I edited my comment above with examples from inside Mono...

**Comment by knocte** [comment]
Thanks for noticing, fixed.

**Comment by akoeplinger** [comment]
@knocte you missed my point, fixing Mono is easy (there are actually more places than the two I mentioned), but we can't fix every application out there.

**Comment by knocte** [comment]
I didn't miss your point, I know your point, but at least I fixed mono.

The release notes for vNEXT should just state this as a breaking change. This would anyway not go unnoticed very easily, as everybody tests their software. If they were using .Personal, their code was broken in the first place, they should have been using .UserProfile.

**Comment by akoeplinger** [comment]
Breaking changes should require a major version bump, so this'd need to wait until Mono 5.0.

> If they were using .Personal, their code was broken in the first place, they should have been using .UserProfile

On the contrary, even [Xamarin docs](https://developer.xamarin.com/guides/ios/application_fundamentals/working_with_the_file_system/#Creating_Files_and_Directories) show using `MyDocuments`, with your patch the path would change and apps won't find files they saved anymore.

It's not as simple as you make it sound :)

**Comment by knocte** [comment]
> On the contrary, even Xamarin docs show using MyDocuments, with your patch the path would change and apps won't find files they saved anymore.

*facepalm*

> so this'd need to wait until Mono 5.0.

Oh well. Let's leave this open until then.

**Comment by knocte** [comment]
Can you launch a build to see if this breaks anything?

**Comment by akoeplinger** [comment]
whitelist

**Comment by knocte** [comment]
I'm guessing the failures are not related?

**Comment by akoeplinger** [comment]
@knocte they are, [FileTest.cs#L50](https://github.com/mono/mono/blob/687eeff24faf3c7e7be089d650c873352224cc89/mcs/class/corlib/Test/System.IO/FileTest.cs#L50) uses `SpecialFolder.Personal`. As I said, there are many places throughout the codebase that rely on this :P

**Comment by knocte** [comment]
All green now.

**Comment by akoeplinger** [comment]
I still see a few instances of `SpecialFolder.Personal` when I grep through the codebase that are likely not covered by tests.

Anyway, the more I think about it the more worried I am about breaking people's apps, even in a major release. There's just [so much code](https://github.com/search?l=csharp&p=1&q=SpecialFolder.Personal&type=Code&utf8=%E2%9C%93) out there that relies on this.

**Comment by knocte** [comment]
> I still see a few instances of SpecialFolder.Personal when I grep through the codebase that are likely not covered by tests.

Fixed all of them now, I think.

> There's just so much code out there that relies on this.

Well, you're linking to .NET code out there, but I remind you that not all .NET code is being run in the Mono platform nowadays. I bet less than 5% does. Let's rather fix this for the upcoming 95% rather than "spoiling" the previous 5%.

**Comment by akoeplinger** [comment]
Sure, that was just an example. Even with that, two projects on the first page run on Mono (someone trying out Xamarin and a Minecraft server) so I think it's safe to assume there *will* be code out there that is broken by this. The question is do we think the improvement outweighs the pain of a breaking change?

**Comment by knocte** [comment]
> The question is do we think the improvement outweighs the pain of a breaking change?

Sure. That is exactly the question.

Obviously, you know that my opinion is that it obviously outweighs it. If we don't fix this inconsistency, I will never use the SpecialFolder enum, ever, with Mono, in my life, because I know it's buggy. And I will blog about it and satanize it as hell (in the same way I despise the System.Diagnostics.Process class, but this time blaming Mono, not Microsoft).

Really, what's the point of having this SpecialFolder abstraction, if it's broken? We already agreed that this change would go in, only for a major-version change, so that the possibility of breaking at user-time (as opposed to testing-time / dev-time / debug-time) is reduced.

**Comment by migueldeicaza** [comment]
Breaking existing apps is not worth the pain.

We have applied this sort of patch in the past, just to have a bunch of apps broken, people upset, complaining about it.

**Comment by sago007** [comment]
Is Environment.GetFolderPath officially deprecated or only SpecialFolder.Personal and SpecialFolder.MyDocuments?

It is broken by design and won't be fixed so I assume that an alternative have been introduced?

**Comment by knocte** [comment]
@sago007 According to https://github.com/dotnet/corefx/issues/12575, the alternative will be included here: https://github.com/dotnet/corefx/issues/12892

**Comment by akoeplinger** [comment]
Correct. Environment.GetFolderPath won't be deprecated in the sense that it'll go away, but there'll be other APIs with a better design in the future.

**Comment by sago007** [comment]
It sounds good. I did not expect it to go away, I just hoped for a better alternative.

**Comment by knocte** [comment]
Fixed in .NET8: https://github.com/dotnet/runtime/pull/68610

**Pull request closed without merging**
