### PR TITLE
[w32handle] Replace mono_w32handle_{ref,unref} by mono_w32handle_{duplicate, close}

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by vargaz** [comment]
Personally, I liked ref/unref more :)

**Comment by luhenry** [comment]
Duplicate/Close is closer to what exists on Win32.

**Comment by lambdageek** [comment]
build coop

I think 2b5d0fe will help with the System.Web failures on coop (that seem to be dying while shelling out to resgen.exe.

**Comment by lambdageek** [comment]
@monojenkins build coop

**Comment by lambdageek** [comment]
Yea 2b5d0fe is great for coop!  Does it make sense to cherrypick that commit to 2017-06 (and -04?)

**Comment by luhenry** [comment]
You can Cherry-Pick it to 2017-06 if you want, but 2017-04 is now closed to commits.

**Pull request merged**
