### PR TITLE
[jit] Add an intrinsics for BitConverter.IsLittleEndian.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by jaykrell** [comment]
@akoeplinger “C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [d:\j\workspace\x\msvc\build-init.vcxproj]
Done Building Project "d:\j\workspace\x\msvc\build-init.vcxproj" (default targets) -- FAILED.”

**Comment by vargaz** [comment]
The corefx PR
https://github.com/mono/corefx/pull/134
will compute it correctly, this is just an optimization.

**Comment by EgorBo** [comment]
Maybe it worth to add a test to check whether JIT is able to eliminate `if (!BitConverter.IsLittleEndian)` or not = makes a method inlineable

**Comment by luhenry** [comment]
@monojenkins build failed

**Comment by kumpera** [comment]
@EgorBo I think figuring out how to add tests for optimization would be an AMAZING step towards us ensuring we're not regressing on the work we do.

**Comment by marek-safar** [comment]
@monojenkins build

**Comment by luhenry** [comment]
This breaks the `Windows i386` and `Windows x64` builds.

**Comment by marek-safar** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
I guess we should now bump external/corefx and the corlib version

**Pull request merged**
