### PR TITLE
Reflect recent NS2.1 changes

### PR DESCRIPTION
**Pull request by EgorBo**
Due to few recent updates to `dotnet/standard` (NETStandard 2.1) we had 40 apicompat issues.
Mostly copy-pasted from `dotnet/corefx`.
Didn't implement Cryptography stuff yet.
Checked all profiles.

Implements #14609

### CODE REVIEW

**Comment by baulig** [comment]
@monojenkins commit csproj

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@EgorBo you also need to revert https://github.com/mono/mono/commit/099e00324025ae0cb09b002b63203c0209c319eb#diff-c24378cb624df435811bba8edeccf843

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-06

**Comment by marek-safar** [comment]
@monojenkins commit csproj and apidiff

**Pull request merged**
