### PR TITLE
[mini] Fix build on platforms without safe points

### PR DESCRIPTION
**Pull request by ludovic-henry**
@kumpera @vargaz is using OP_GC_SAFE_POINT this way ok for you?

### CODE REVIEW

**Comment by vargaz** [comment]
Looks ok. It might be easier to just add support for OP_GC_SAFE_POINT to those platforms as a nop. i.e. put gc_safe_point: len:0 into cpu-<ARCH>.md, and and
OP_GC_SAFE_POINT:
   break;
into mono_arch_emit_basic_block ();

**Comment by alexrp** [comment]
I think I'd prefer a nop implementation over more ifdefs too.

**Comment by ludovic-henry** [comment]
@alexrp @vargaz I updated to have the nop implementation. Would you mind checking I didn't forget anything? Thank you! :)

**Comment by alexrp** [comment]
LGTM

**Comment by ludovic-henry** [comment]
Rebasing and merging to master. Thank you @alexrp and @vargaz

**Pull request closed without merging**
