### PR TITLE
Extract F# layout to separate script to share it with Homebrew build.

### PR DESCRIPTION
**Pull request by mfilippov**

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by mfilippov** [comment]
@akoeplinger I not integrate script into fsharp.py as we discussed in char.

**Comment by akoeplinger** [comment]
Yup, I noticed after I kicked off the "build pkg" command so I canceled it :)

Will figure out how to call the script from fsharp.py so we don't duplicate the logic.

**Comment by mfilippov** [comment]
Could you put it into 2019-12 branch to avoid additional patching in the next release.

**Comment by mfilippov** [comment]
@akoeplinger the last patch from this commit https://github.com/Homebrew/homebrew-core/pull/69089/commits/22e43a2d208c42b85fe823e54c67104878bc4baa could help you with myget in fsharp

**Comment by akoeplinger** [comment]
yeah I'll put it in 2020-02 (which is our only supported branch right now) once I hooked it into fsharp.py

**Pull request merged**
