### PR TITLE
[runtime] Second batch of GC Unsafe thread state transitions for the MONO_API

### PR DESCRIPTION
**Pull request by lambdageek**
For hybrid suspend we need all entry points into the runtime from native code to be annotated with transitions to GC Unsafe mode.  This is the second set of changes after #8847. The overall project is #6921 

One sizeable change here is marking `mono_class_get_method_from_name` as external only - and updating the runtime to use `mono_class_get_method_from_name_checked`.

### CODE REVIEW

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Coop Suspend

**Comment by luhenry** [comment]
@monojenkins build Linux AArch64 Coop Suspend

**Comment by luhenry** [comment]
@monojenkins build Linux x64 Hybrid Suspend

**Comment by lambdageek** [comment]
@monojenkins build failed

**Pull request merged**
