### PR TITLE
Bump F# to 4.1.29. Fixes #6281

### LINKED ISSUE #6281: update F# Compiler in Mono to >= VS 15.5.2
The F# Compiler for Mono on Mac is from June. Can you please update it to be the same as VS 15.5.2 that just shipped or newer? I opened up the corresponding issue in the Visual F# repo so ya'll can coordinate. https://github.com/Microsoft/visualfsharp/issues/4143 cc @directhex and @nosami 

May be the version bump goes into Mono 5.6. I'm not sure about the timeline on that. 

https://github.com/mono/mono/blob/master/packaging/MacSDK/fsharp.py
https://github.com/mono/mono/blob/2017-12/packaging/MacSDK/fsharp.py

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by alexischr** [comment]
build pkg

**Comment by nosami** [comment]
build pkg

**Comment by ctaggart** [comment]
Thanks @nosami !

**Comment by akoeplinger** [comment]
@nosami this no longer installs FSharp.Core.dll into the GAC, is this expected?

```diff
@@ -2364,10 +2366,6 @@
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/Accessibility.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/Commons.Xml.Relaxng.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/CustomMarshalers.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/FSharp.Core.xml
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/Facades
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/Facades/Microsoft.Win32.Primitives.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/Facades/Microsoft.Win32.Registry.AccessControl.dll
@@ -4525,26 +4526,6 @@
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/fsi.exe.config
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/fsiAnyCpu.exe
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/fsiAnyCpu.exe.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.2.0.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.2.0.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.2.3.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.2.3.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.259.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.259.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.3.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.3.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.47.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.47.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.7.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.7.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.78.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.3.78.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.4.0.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.4.0.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.4.3.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.4.3.FSharp.Core.dll.config
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.4.4.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/fsharp/policy.4.4.FSharp.Core.dll.config
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/Accessibility
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/Accessibility/4.0.0.0__b03f5f7f11d50a3a
@@ -4558,66 +4539,6 @@
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/CustomMarshalers/4.0.0.0__b03f5f7f11d50a3a
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/CustomMarshalers/4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/CustomMarshalers/4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.pdb
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Interactive.Settings
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Interactive.Settings/4.4.1.0__f536804aa0eb945b
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Interactive.Settings/4.4.1.0__f536804aa0eb945b/FSharp.Compiler.Interactive.Settings.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Interactive.Settings/4.4.1.0__f536804aa0eb945b/FSharp.Compiler.Interactive.Settings.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Server.Shared
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Server.Shared/4.4.1.0__f536804aa0eb945b
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Server.Shared/4.4.1.0__f536804aa0eb945b/FSharp.Compiler.Server.Shared.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Compiler.Server.Shared/4.4.1.0__f536804aa0eb945b/FSharp.Compiler.Server.Shared.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.259.41.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.259.41.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.259.41.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.259.41.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.259.41.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.47.41.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.47.41.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.47.41.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.47.41.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.47.41.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.7.41.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.7.41.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.7.41.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.7.41.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.7.41.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.78.41.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.78.41.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.78.41.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.78.41.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.78.41.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.98.41.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.98.41.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.98.41.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.98.41.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.98.41.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.99.41.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.99.41.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.99.41.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.99.41.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/3.99.41.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.0.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.0.0__b03f5f7f11d50a3a/FSharp.Core.xml
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.optdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.pdb
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.sigdata
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/FSharp.Core.xml
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/I18N
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll
@@ -5307,9 +5228,6 @@
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/pango-sharp/2.12.0.0__35e10195dab3c99f/pango-sharp.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/pango-sharp/2.12.0.0__35e10195dab3c99f/pango-sharp.dll.config
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/pango-sharp/2.12.0.0__35e10195dab3c99f/pango-sharp.dll.mdb
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.0.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.0.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.0.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.2.0.FSharp.Core.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.10.atk-sharp
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.10.atk-sharp/0.0.0.0__35e10195dab3c99f
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.10.atk-sharp/0.0.0.0__35e10195dab3c99f/policy.2.10.atk-sharp.dll
@@ -5338,9 +5256,6 @@
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.10.pango-sharp/0.0.0.0__35e10195dab3c99f
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.10.pango-sharp/0.0.0.0__35e10195dab3c99f/policy.2.10.config
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.10.pango-sharp/0.0.0.0__35e10195dab3c99f/policy.2.10.pango-sharp.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.3.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.3.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.3.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.2.3.FSharp.Core.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.4.atk-sharp
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.4.atk-sharp/0.0.0.0__35e10195dab3c99f
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.4.atk-sharp/0.0.0.0__35e10195dab3c99f/policy.2.4.atk-sharp.dll
@@ -5425,30 +5340,6 @@
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.8.pango-sharp/0.0.0.0__35e10195dab3c99f
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.8.pango-sharp/0.0.0.0__35e10195dab3c99f/policy.2.8.config
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.2.8.pango-sharp/0.0.0.0__35e10195dab3c99f/policy.2.8.pango-sharp.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.259.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.259.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.259.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.3.259.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.3.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.3.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.3.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.3.3.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.47.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.47.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.47.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.3.47.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.7.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.7.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.7.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.3.7.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.78.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.78.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.3.78.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.3.78.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.0.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.0.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.0.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.4.0.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.3.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.3.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.3.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.4.3.FSharp.Core.dll
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.4.FSharp.Core
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.4.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a
-./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/policy.4.4.FSharp.Core/4.4.1.0__b03f5f7f11d50a3a/policy.4.4.FSharp.Core.dll
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/xsp4
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/xsp4/4.4.0.0__0738eb9f132ed756
 ./Library/Frameworks/Mono.framework/Versions/Current/lib/mono/gac/xsp4/4.4.0.0__0738eb9f132ed756/xsp4.exe
```

**Comment by nosami** [comment]
Yes. This was a deliberate decision to make F# on Mono behave more like it
does on Windows. It's not in the GAC on Windows either.

**Pull request merged**
