### PR TITLE
[system] WebSocket continuation frame incorrectly handles the message type

### PR DESCRIPTION
**Pull request by mattleibow**
When a frame marked with OPCODE 0, it is a continuation frame. 
This frame does not carry the message type and should be derived from the previous frame.

### CODE REVIEW

**Comment by alexrp** [comment]
approve

**Comment by alexrp** [comment]
build

**Comment by lewurm** [comment]
@mattleibow is there still interest to merge this or should it be closed?

**Comment by lewurm** [comment]
build

**Comment by migueldeicaza** [comment]
This looks like a bug, sadly, I can not find a case that breaks. 

Would love to know what this fixes in the wild.

**Comment by 564064202** [comment]
@mattleibow there is something wrong with signlar(websocket)

**Comment by 564064202** [comment]
@mattleibow there is something wrong with signlar(websocket)

**Pull request merged**
