### PR TITLE
[2018-04] Revert "[loader] LoadFrom of problematic images should reprobe"

### LINKED ISSUE #9044: New "bad" assembly loader/remapper trips on MSBuild build
We haven't been able to compile MSBuild since https://github.com/mono/mono/commit/9ad5255338386a22e7a861e8bcc7c195dc591b99 was merged.

During compilation, MSBuild uses `AssemblyName.GetAssemblyName(sourcePath)?.Version` a bunch, which according to the documentation, "This method causes the file to be opened and closed, but the assembly is not added to this domain."

It seems our implementation loads anyway.

However, the new logic for remapping problematic Windows-only assemblies isn't triggered in this case.

Good:

```
Mono: Loading reference 7 of /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/msbuild-15.problem/artifacts/mono-msbuild/Microsoft.Build.dll asmctx DEFAULT, looking for System.IO.Compression, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Mono: The request to load the assembly System.IO.Compression v4.1.2.0 was remapped to v4.0.0.0
Mono: Found assembly remapping for System.IO.Compression and was for the same version 4.0.0.0
Mono: Domain MSBuild.dll search path is:
Mono:   path[0] = '/Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/msbuild-15.problem/artifacts/mono-msbuild/'
Mono: End of domain MSBuild.dll search path.
Mono: Assembly Loader probing location: '/Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/msbuild-15.problem/artifacts/mono-msbuild/System.IO.Compression.dll'.
Mono: Denying load of problematic image /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/msbuild-15.problem/artifacts/mono-msbuild/System.IO.Compression.dll
Mono: Unloading image /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/msbuild-15.problem/artifacts/mono-msbuild/System.IO.Compression.dll [0x7f94dd1db000].
Mono: Assembly Loader probing location: '/Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/stage/lib/mono/gac/System.IO.Compression/4.0.0.0__b77a5c561934e089/System.IO.Compression.dll'.
Mono: Image addref System.IO.Compression[0x7f94dc52f960] (asmctx DEFAULT) -> /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/stage/lib/mono/gac/System.IO.Compression/4.0.0.0__b77a5c561934e089/System.IO.Compression.dll[0x7f94dd1db000]: 2
Mono: Prepared to set up assembly 'System.IO.Compression' (/Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/stage/lib/mono/gac/System.IO.Compression/4.0.0.0__b77a5c561934e089/System.IO.Compression.dll)
Mono: Assembly System.IO.Compression[0x7f94dc52f960] added to domain MSBuild.dll, ref_count=1
Mono: Assembly Loader loaded assembly from location: '/Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/stage/lib/mono/gac/System.IO.Compression/4.0.0.0__b77a5c561934e089/System.IO.Compression.dll'.
Mono: Assembly Ref addref Microsoft.Build[0x7f94dc6168d0] -> System.IO.Compression[0x7f94dc52f960]: 2
```

Bad:
```
Mono: Assembly Loader probing location: '/Users/builder/.nuget/packages/system.io.compression/4.3.0/ref/net46/System.IO.Compression.dll'.
Mono: Image addref System.IO.Compression[0x7f94def4b060] (asmctx REFONLY) -> /Users/builder/.nuget/packages/system.io.compression/4.3.0/ref/net46/System.IO.Compression.dll[0x7f94df100200]: 2
Mono: Prepared to set up assembly 'System.IO.Compression' (/Users/builder/.nuget/packages/system.io.compression/4.3.0/ref/net46/System.IO.Compression.dll)
Mono: Assembly System.IO.Compression[0x7f94def4b060] added to domain MSBuild.dll, ref_count=1
Mono: Assembly Loader loaded assembly from location: '/Users/builder/.nuget/packages/system.io.compression/4.3.0/ref/net46/System.IO.Compression.dll'.
```

The end result, during build:
```
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018: The "ResolvePackageFileConflicts" task failed unexpectedly. [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER. [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018: System.IO.FileNotFoundException:  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018: File name: '/Users/builder/.nuget/packages/system.io.compression/4.3.0/ref/net46/System.IO.Compression.dll' [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at (wrapper managed-to-native) System.Reflection.Assembly.InternalGetAssemblyName(string,Mono.MonoAssemblyName&,string&) [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at System.Reflection.AssemblyName.GetAssemblyName (System.String assemblyFile) [0x0001a] in <0a1489687ea248b2a706d89d4c87bbcf>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.FileUtilities.GetAssemblyVersion (System.String sourcePath) [0x00000] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.FileUtilities.TryGetAssemblyVersion (System.String sourcePath) [0x00016] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictItem.get_AssemblyVersion () [0x0004e] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1[TConflictItem].ResolveConflict (TConflictItem item1, TConflictItem item2) [0x000c2] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1[TConflictItem].ResolveConflicts (System.Collections.Generic.IEnumerable`1[T] conflictItems, System.Func`2[T,TResult] getItemKey, System.Action`1[T] foundConflict, System.Boolean commitWinner, System.Action`1[T] unresolvedConflict) [0x0003a] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.ExecuteCore () [0x000a6] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x00000] in <a39f5cd91a004fcf87657c269fcb8060>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x0002a] in <143af2be99a94a8480f7f49f5d47377c>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
15:43:22 @/external/bockbuild/builds/msbuild-15/artifacts/mono-msbuild/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(41,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a2] in <143af2be99a94a8480f7f49f5d47377c>:0  [@/external/bockbuild/builds/msbuild-15/src/NuGetSdkResolver.UnitTests/NuGet.MSBuildSdkResolver.UnitTests.csproj]
```

### PR DESCRIPTION
**Pull request by lambdageek**
This reverts commit efe1fdeb9dedeb2f3aba2efe63a977f3521d04b0.

Fix #9044 for `2018-04`

### CODE REVIEW

**Comment by lambdageek** [comment]
@monojenkins build pkg

**Comment by lambdageek** [comment]
Ah, nevermind. figured out what I did wrong. We don't need to do this, I think.

**Comment by lambdageek** [comment]
Reopening - my idea for a simple fix didn't seem to help.
Better to revert the bad commit for 2018-04.

**Comment by alexischr** [comment]
@monojenkins build Linux WebAssembly

**Comment by alexischr** [comment]
The WebAssembly failure is unrelated (I am just trying to see if it happens again) but msbuild still fails to build with 
```
19:19:58 Build started 6/13/2018 3:19:57 PM.
19:19:58 @/external/bockbuild/builds/msbuild-15/artifacts/toolset/restore.proj : error MSB4242: The SDK resolver "NuGetSdkResolver" failed to run. Unexpected failure reading NuGet.Config. Path: '@/external/bockbuild/builds/msbuild-15/artifacts/toolset/restore.proj/$HOME/.config/NuGet/NuGet.Config'.
19:19:58 @/external/bockbuild/builds/msbuild-15/artifacts/toolset/restore.proj : error MSB4236: The SDK 'RoslynTools.RepoToolset' specified could not be found.
19:19:58 
19:19:58 Build FAILED.
```

**Comment by akoeplinger** [comment]
@monojenkins build pkg

**Comment by lambdageek** [comment]
@monojenkins build pkg

**Comment by radical** [comment]
@monojenkins build pkg

**Comment by lambdageek** [comment]
force-pushed to remove the debug tracing commit.

**Comment by lambdageek** [comment]
From Slack: @akoeplinger and @radical tracked the `"The SDK resolver "NuGetSdkResolver" failed to run."` issue to a bad env var in the testing environment (`XDG_CONFIG_HOME="$HOME/.config"` with a literal `$HOME` in the string) - so it's not related to this PR.

**Pull request merged**
