### PR TITLE
[sgen] Fix MS block size calculation.

### PR DESCRIPTION
**Pull request by alexrp**
The block size must be a multiple of the system page size. Page size simply
cannot be determined reliably at compile time, so we must obtain the page size
through a system call on startup and use it as the block size. We still enforce
a minimum block size of 16kb on systems where the page size is smaller than
that.

The old code hardcoded page sizes for certain architectures with large pages.
THe problem is that those architectures don't necessarily have to have large
pages and on systems where this wasn't the case, we'd end up with a block size
much larger than needed.

### CODE REVIEW

**Comment by alexrp** [comment]
@BrzVlad please review

**Comment by BrzVlad** [comment]
builddeb

**Comment by BrzVlad** [comment]
@alexrp This seems to cause a serious performance regression especially on onelist. Could you double check if you can repro locally, and if so see what is the problem ? Maybe alloca related, maybe switching from a compile time def to a variable ?

**Comment by BrzVlad** [comment]
@alexrp another thing could be marking as constant variables as MS_NUM_MARK_WORDS and CARDS_PER_BLOCK which use divisions and might take longer if called repeatedly

**Comment by alexrp** [comment]
Good points, will look into it.

**Comment by kumpera** [comment]
@BrzVlad @alexrp @lewurm can you guys give this one some love?

**Comment by alexrp** [comment]
Closing; Vlad will take over on this one.

**Pull request closed without merging**
