### PR TITLE
[corlib] Refactor Type:GetName () to reduce differences with refsources and make it easier to add support for stack marks later.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by marek-safar** [comment]
@monojenkins build deb with monolite

**Comment by marek-safar** [comment]
@monojenkins build

**Comment by marek-safar** [comment]
@vargaz could you resolve the conflicts ?

**Comment by lambdageek** [comment]
@monojenkins build deb with monolite

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins commit apidiff

**Comment by vargaz** [comment]
@monojenkins build failed

**Pull request merged**
