### PR TITLE
Support for non-standard baud rate in Linux

### PR DESCRIPTION
**Pull request by rd235**
libMonoPosixHelper does not support non standard baud rates on Linux.
I needed this feature as 3D printers often use 250000baud communications.

I would like to have this feature included in mainstream code, otherwise I have to download, patch and compile mono from the source code at each new release of mono.
It is a general purpose feature, it can be useful for many other applications.

### CODE REVIEW

**Comment by kumpera** [comment]
There's a competing patch here: https://bugzilla.xamarin.com/show_bug.cgi?id=8207

They use different ioctl values. I'm not familiar with serial comms so I wonder which one is the appropriate one.

**Comment by zeha** [comment]
Defining the IOCTL codes and data values locally when there's a perfectly fine header file doesn't look appropriate to me.

**Comment by migueldeicaza** [comment]
Applied a similar patch, and also added MacOS support.

**Comment by akoeplinger** [comment]
A similar patch was just applied in https://github.com/mono/mono/commit/87357b51e98e2027603217b157d564caeb72c623 so I'm closing this one, but thanks for your contribution!

**Pull request closed without merging**
