### PR TITLE
[llvm] Disable running the llvm verifier by default, it was enabled by mistake, and it takes a long time.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by vargaz** [comment]
@monojenkins build failed

**Comment by akoeplinger** [comment]
@vargaz should we backport to 2020-02?

**Comment by vargaz** [comment]
@monojenkins backport 2020-02

**Pull request merged**
