### PR TITLE
Enable more corefx reflection tests

### PR DESCRIPTION
**Pull request by MaximLipnin**
Part of #9660 

Instead of https://github.com/mono/mono/pull/11025

https://github.com/mono/corefx/pull/152 needs to be merged.

### CODE REVIEW

**Comment by akoeplinger** [comment]
It seems there's a build error: 

```
/home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/System.Reflection/tests/TypeInfoTests.netcoreapp.cs(35,48): error CS0246: The type or namespace name 'Outside<>' could not be found (are you missing a using directive or an assembly reference?)
/home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/System.Reflection/tests/TypeInfoTests.netcoreapp.cs(36,48): error CS0246: The type or namespace name 'Outside<>' could not be found (are you missing a using directive or an assembly reference?)
/home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/System.Reflection/tests/TypeInfoTests.netcoreapp.cs(37,48): error CS0246: The type or namespace name 'Outside<>' could not be found (are you missing a using directive or an assembly reference?)
/home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/System.Reflection/tests/TypeInfoTests.netcoreapp.cs(40,73): error CS0246: The type or namespace name 'Outside<>' could not be found (are you missing a using directive or an assembly reference?)
/home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/System.Runtime/tests/System/DecimalTests.cs(390,33): warning CS1718: Comparison made to same variable; did you mean to compare something else?
/home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/System.Runtime/tests/System/DecimalTests.cs(391,34): warning CS1718: Comparison made to same variable; did you mean to compare something else?
make[2]: *** [../../class/lib/net_4_x/tests/net_4_x_corlib_xunit-test.dll] Error 1```

**Comment by MaximLipnin** [comment]
Yeah, it relies on some dummy data in other test class. mono/corefx 152 is a workaround for that.

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Comment by MaximLipnin** [comment]
@monojenkins build

**Comment by MaximLipnin** [comment]
@monojenkins build failed

**Pull request merged**
