### PR TITLE
Bump corefx

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by luhenry** [comment]
Does that mean we are not tracking the `mono/corefx:master` branch anymore but `mono/corefx:2.1-merge`? If so that would be worth communicating to the rest of the team.

**Comment by marek-safar** [comment]
We have been tracking 2.1 as soon they made the branch which is months ago. It was communicated on several occasions including the on-site meeting in December.

**Comment by luhenry** [comment]
@marek-safar what I remember from these discussions was that we weren't tracking it yet since they were still going to branch later on. And if I look at https://github.com/mono/corefx, the branch showed by default is `master`. Also all PR are submitted against `master`, and none against `2.1-merge` (https://github.com/mono/corefx/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+base%3A2.1-merge) so I am not the only one who seems to have missed it.

Finally tracking upstream [`dotnet/corefx:release/2.1`](https://github.com/dotnet/corefx/tree/release/2.1) is different than us using [`mono/corefx:2.1-merge`](https://github.com/mono/corefx/tree/2.1-merge) in `mono/mono`.

So I don't know if I am missing something from your explanation but the plan isn't clear to me.

**Comment by marek-safar** [comment]
Our master is tracking their release/2.1 as stated in our Readme. The corefx 2.1 release is out and in servicing mode so we are still picking up changes from it. To do that I usually create a temporary branch (this time called 2.1-merge) to see what breaks because they are large changes and every time something break (including this time) before I merge it to the corefx master and do real bump.

**Comment by marek-safar** [comment]
@alexischr I pulled in your enabled test but it still fails consistently on `System.IO.Tests.FileSystemWatcherTests.System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_StopCalledOnBackgroundThreadDoesNotDeadlock`. Do we have to disable it again?

**Comment by alexischr** [comment]
@marek-safar Yeah we shouldn't have merged that before its mono PR. I reverted on master and this is a PR for mono: https://github.com/mono/mono/pull/8899/files

**Pull request merged**
