### PR TITLE
[netcore] Run CoreFX tests on CI (macOS)

### PR DESCRIPTION
**Pull request by EgorBo**
Run all CoreFX tests on CI.
In order to see the test results:
1) Click on `mono-coreonly-CI` lane
2) Click on `View more details on Azure Pipelines` link
3) Click on `Tests` tab

Should look like this:
image

Command to re-run the lane: `/azp run`

### CODE REVIEW

**Comment by filipnavara** [comment]
Hmm. It is hitting error in the Makefile on the `{pdb,dll}` syntax just like on my ARM Ubuntu 1604 machine.

**Comment by EgorBo** [comment]
@filipnavara but at least it successfully ran them all on macOS (well, there were 4 failures, but anyway) 🙂 
Let me see if I can integrate it with the Test summary view

**Comment by filipnavara** [comment]
I am really looking forward to this. Unfortuantely GitHub limits me to one Hurray emoji per person :)

**Comment by EgorBo** [comment]
@filipnavara https://dev.azure.com/dnceng/public/_build/results?buildId=215193&view=ms.vss-test-web.build-test-results-tab

**Comment by filipnavara** [comment]
Not sure if it's related but many of the System.Security.Cryptography.* (eg. S.S.C.X509Certificates) tests temporarily break connectivity on my machine when they are running. Wonder if it could cause problems on the CI machines. CoreFX and CoreCLR use Helix so they may not suffer from it.

**Comment by EgorBo** [comment]
@filipnavara I've just ran `xtestall` with `ping 8.8.8.8` in a separate iterm tab and didn't see any interruptions. But I think there are cause I do remember I had ones locally previously

**Comment by filipnavara** [comment]
> @filipnavara I've just ran `xtestall` with `ping 8.8.8.8` in a separate iterm tab and didn't see any interruptions. But I think there are cause I do remember I had ones locally previously

Interesting. I don't know exactly what is happening, but if I run S.S.C.X509Certificates tests and at the same time try to browse in Chrome it always randomly fails to load pages. Maybe the system proxy settings?

**Comment by filipnavara** [comment]
The failing GDI+ tests are caused by unimplemented method in `NativeLibrary` (https://github.com/mono/mono/blob/03c6855d05250ff7fe8d105d6e56138d60807ff4/mcs/class/System.Private.CoreLib/System.Runtime.InteropServices/NativeLibrary.Unix.cs#L11).

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@marek-safar @steveisok @filipnavara So I think we can merge it now, in order to keep the lane green it builds artifacts for Windows, macOS and Linux but runs tests only for macOS. I'll enable tests for Linux and Windows in separate PRs. 

In order to see the test results:
1) Click on `mono-coreonly-CI` lane
2) Click on `View more details on Azure Pipelines` link
3) Click on `Tests` tab

Should look like this:
image

**Pull request merged**
