### PR TITLE
Don't try to access metadata for dynamic method added to non-dynamic …

### PR DESCRIPTION
**Pull request by joncham**
…image. Fixes issue #10201.

### CODE REVIEW

**Comment by jchannon** [comment]
*cough*

**Comment by joncham** [comment]
I'll add test case.

**Comment by joncham** [comment]
@marek-safar should tests go into runtime tests or classlib tests?

**Comment by marek-safar** [comment]
@joncham classlib

**Comment by steveisok** [comment]
@lambdageek are we going to take this?

**Comment by lambdageek** [comment]
Yea, we want this.  Just need to fix the merge conflict and make a testcase from the repro steps in #10201.

**Comment by lambdageek** [comment]
@monojenkins build failed

**Comment by lewing** [comment]
@bluild Linux ARMv7

**Comment by steveisok** [comment]
@monojenkins build Linux ARMv7

**Pull request merged**
