### PR TITLE
Avoid use of DEF files in Visual Studio build

### PR DESCRIPTION
**Pull request by joncham**
Avoid using def files in Visual Studio build. Export symbols via attribute/define and link object files from dependencies to ensure visibility is not lost.

Import part is the `UseLibraryDependencyInputs` setting which has MS linker fed object files rather than LIB files. The object files always have all their symbols inspected and thus exported, where LIBs are treated differently. See comments on https://github.com/mono/mono/pull/4421

### CODE REVIEW

**Comment by joncham** [comment]
Looks like the Windows main exe requires access to `mono_dl_open` and `mono_loader_register_module`. Do we want to export those?

**Comment by joncham** [comment]
```
  main.obj : error LNK2019: unresolved external symbol _mono_dl_open referenced in function _save_library [d:\j\workspace\w\msvc\mono.vcxproj]
  main.obj : error LNK2019: unresolved external symbol _mono_loader_register_module referenced in function _save_library [d:\j\workspace\w\msvc\mono.vcxproj]
```

**Comment by vargaz** [comment]
We can export them on windows only.

**Comment by lateralusX** [comment]
Looks like those symbols got introduced by the following commit:
https://github.com/mono/mono/commit/2f1e6655e2c9a9dd28c0a8b14f26d3d6b1c720bd

Since the symbols got explicitly exported by that commit and needed by the mkbundle solution I believe we should continue export them on windows.

**Comment by lateralusX** [comment]
There is a perl script that can be executed to create the def files, create_windef.pl, if we drop .def file support I believe we should drop this script as well.

**Comment by lateralusX** [comment]
Maybe we should retiree monoposixhelper.def as well?

**Comment by joncham** [comment]
@lateralusX I didn't touch `monoposixhelper.def` as it's generated. We can revisit it as well.

**Comment by joncham** [comment]
Sorry, that comment was unclear. The headers for monoposixhelper are autogenerated and to add the export attributes seems additional work for a separate PR.

**Comment by lateralusX** [comment]
@joncham does it still export correctly in the cygwin builds as well?

**Comment by joncham** [comment]
I avoid Cygwin ;-) , but let me check. I guess non of the CI paths tests this?

**Comment by lateralusX** [comment]
Correct, CI just builds cygwin builds, but all tests are then run using MSVC build binaries.

**Comment by vargaz** [comment]
Can this be rebased on master ?

**Comment by joncham** [comment]
Agree on things to verify. Will rebase and do checks as I have time.

**Comment by joncham** [comment]
Looking into this a bit more. VS makes it quite hard to export symbols from linked static libraries.

**Comment by lateralusX** [comment]
@joncham What problems are you seeing? Is the final module missing some of the exported symbols compared to the .def file solution or some other problem?

**Comment by akoeplinger** [comment]
Use of .def files was removed with https://github.com/mono/mono/pull/5656 🎉

**Pull request closed without merging**
