### PR TITLE
[interp] add safepoints and enable hybrid suspend as default

### PR DESCRIPTION
**Pull request by lewurm**
Fixes https://github.com/mono/mono/issues/10260

### CODE REVIEW

**Comment by BrzVlad** [comment]
@lewurm We are trying to get of checkpoint opocdes since opcode execution adds overhead. Maybe unify checkpoints with safepoints ?

**Comment by luhenry** [comment]
@monojenkins build failed

**Comment by lewurm** [comment]
@BrzVlad done

**Comment by lewurm** [comment]
@monojenkins squash

**Pull request merged**
