### PR TITLE
[btls] Set CMAKE_POSITION_INDEPENDENT_CODE TRUE for BUILD_DYNAMIC_BTLS

### PR DESCRIPTION
**Pull request by akihikodaki**
While `CMAKE_POSITION_INDEPENDENT_CODE` will be automatically set if `BUILD_SHARED_LIBS` is `TRUE`, it won't if `BUILD_DYNAMIC_BTLS` is `TRUE`.
This change sets `CMAKE_POSITION_INDEPENDENT_CODE` manually in such a case.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@akihikodaki can you please target the pull request against the `master` branch? We can cherry-pick to 4.8 if this is approved.

**Comment by akoeplinger** [comment]
@baulig this should basically be the same as what you suggested in https://github.com/xamarin/monodroid/pull/535#issuecomment-259975589 right?

**Comment by baulig** [comment]
build

**Comment by akihikodaki** [comment]
@akoeplinger It is not necessary for `master` branch because `BUILD_DYNAMIC_BTLS` got removed in commit d831fc4ec4c90930026342431641e529b2e34dc8.

**Comment by akoeplinger** [comment]
@akihikodaki `BUILD_DYNAMIC_BTLS ` was made the default in d831fc4 so I assume it's still necessary.

**Comment by akihikodaki** [comment]
@akoeplinger `mono/btls/CMakeLists.txt` says it builds static library unless `BUILD_SHARED_LIBS` is `TRUE`.
```diff
-if (BUILD_DYNAMIC_BTLS)
+if (BUILD_SHARED_LIBS)
 	add_library (mono-btls-shared SHARED ${MONO_BTLS_SOURCES})
-elseif (BUILD_SHARED_LIBS)
-	add_library (mono-btls-shared SHARED ${MONO_BTLS_SOURCES})
-	set_target_properties (mono-btls-shared PROPERTIES RULE_LAUNCH_LINK
-               "${PROJECT_SOURCE_DIR}/create-object-library.sh ${CMAKE_BINARY_DIR} mono-btls-shared.txt mono-btls-shared-lo.txt libmono-btls-shared.a shared ${CMAKE_AR} ${CMAKE_RANLIB} <OBJECTS> --"
-	)
 else ()
 	add_library (mono-btls-static STATIC ${MONO_BTLS_SOURCES})
-	set_target_properties (mono-btls-static PROPERTIES RULE_LAUNCH_LINK
-		"${PROJECT_SOURCE_DIR}/create-object-library.sh ${CMAKE_BINARY_DIR} mono-btls-static.txt mono-btls-static-lo.txt libmono-btls-static.a static ${CMAKE_AR} ${CMAKE_RANLIB} <OBJECTS> --"
-	)
 endif ()
```

**Comment by akoeplinger** [comment]
@akihikodaki it is set to true in https://github.com/mono/mono/blob/master/mono/btls/Makefile.am#L48 and installed in https://github.com/mono/mono/blob/master/mono/btls/Makefile.am#L66. As far as I know the static version isn't used and the code could be removed.

**Comment by akihikodaki** [comment]
@akoeplinger 
> While `CMAKE_POSITION_INDEPENDENT_CODE` will be automatically set if `BUILD_SHARED_LIBS` is `TRUE`, it won't if `BUILD_DYNAMIC_BTLS` is `TRUE`.
> This change sets `CMAKE_POSITION_INDEPENDENT_CODE` manually in such a case.

**Comment by akoeplinger** [comment]
@akihikodaki ah ok, I didn't know that. Sounds good then 👍 

I wonder why https://github.com/xamarin/monodroid/pull/535#issuecomment-259975589 would be necessary in that case though, let's see what Martin says.

**Pull request merged**
