### PR TITLE
[threads] Assert that every thread is detached when exiting

### PR DESCRIPTION
**Pull request by ludovic-henry**
cc @kumpera

### CODE REVIEW

**Comment by ludovic-henry** [comment]
build

**Comment by ludovic-henry** [comment]
build

**Comment by ntherning** [comment]
This breaks the "runtime" tests on WIndows (using MSVC built binaries) due to `DllImport("libc")` in `thread-native-exit.cs`.

**Comment by ludovic-henry** [comment]
@ntherning shouldn't the DllImport throw a `EntryPointNotFoundException` exception when trying to call the `pthread_exit`?

**Comment by akoeplinger** [comment]
@ludovic-henry it throws a DllNotFoundException: https://jenkins.mono-project.com/job/z/label=w64/3738/testReport/MonoTests/runtime/thread_native_exit_exe/

**Comment by ludovic-henry** [comment]
@akoeplinger ok, let me add a catch for this exception then

**Pull request merged**
