### PR TITLE
implement Image.SetPropertyItem() method v4

### PR DESCRIPTION
**Pull request by ralovich**
This is thought to be fixing https://bugzilla.novell.com/show_bug.cgi?id=406307.

v4: state that my changes are licensed under MIT X11 license

### CODE REVIEW

**Comment by alexrp** [comment]
Could a test case be added for this change?

**Comment by monoadmin** [comment]
Hello! I'm the build bot for the Mono project. I need approval from a Mono team member to build this pull request. A team member should reply with "approve" to approve a build of this pull request, "whitelist" to whitelist this and all future pull requests from this contributor, or "build" to explicitly request a build, even if one has already been done. Contributors can ignore this message.

**Comment by lewurm** [comment]
is there still interest to merge this or should it be closed?

**Comment by migueldeicaza** [comment]
This looks good.

**Pull request merged**
