### PR TITLE
TextInfo.ChangeCase should not use CultureInfo.CurrentCulture

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/mono/mono/issues/14102

### CODE REVIEW

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by EgorBo** [comment]
@monojenkins build failed

**Comment by marek-safar** [comment]
@monojenkins backport 2019-04

**Comment by marek-safar** [comment]
@monojenkins backport 2019-02

**Pull request merged**
