### PR TITLE
[cxx][netcore] Goto around init.

### PR DESCRIPTION
**Pull request by jaykrell**

### CODE REVIEW

**Comment by jaykrell** [comment]
@monojenkins build failed

**Comment by CoffeeFlux** [comment]
Looks sane, but for my reference what are the actual errors with these in c++? Also, do we care about netcore c++ builds? If so, we should probably add a ci lane on at least one platform. cc: @lambdageek

**Comment by imhameed** [comment]
For reference: See 6.7 subclause 3 in <http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3337.pdf>.

**Comment by CoffeeFlux** [comment]
Oh, it's that again. Gotcha, thanks.

**Comment by jaykrell** [comment]
@monojenkins squash

**Pull request merged**
